[[release-notes-7.8.1]]
== {kib} 7.8.1

For detailed information about the {kib} 7.8.1 release, review the following information.

[float]
[[security-update-7.8.1]]
=== Security updates
* In {kib} 7.8.1 and earlier, there is a denial of service (DoS) flaw in Timelion. Attackers can construct a URL that when viewed
by a {kib} user, the {kib} process consumes large amounts of CPU and becomes unresponsive,
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-7016[CVE-2020-7016].
+
You must upgrade to 7.8.1. If you are unable to upgrade, set `timelion.enabled` to `false` in your kibana.yml file to disable Timelion.

* In all {kib} versions, region map visualizations contain a stored XSS flaw. Attackers that can edit or create region map visualizations can obtain sensitive information
or perform destructive actions on behalf of {kib} users who view the region map visualization,
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-7017[CVE-2020-7017].
+
You must upgrade to 7.8.1. If you are unable to upgrade, set `xpack.maps.enabled`, `region_map.enabled`, and `tile_map.enabled` to `false` in kibana.yml to disable map visualizations.

[float]
[[breaking-changes-v7.8.1]]
=== Breaking changes

For information about the breaking changes, refer to the <<breaking-changes-7.8,breaking changes in 7.8>>.

[float]
[[bug-v7.8.1]]
=== Bug fixes
Alerting::
* Disables multiple select for preconfigured connectors to avoid requesting bulk delete on them {pull}69459[#69459]
* Fixes adding an extra space character on selecting alert variable in action text fields {pull}70028[#70028]
APM::
* Fixes service maps not loading when there are no APM ML jobs {pull}69240[#69240]
* Fixes service maps load failure when user doesn't have ML permissions {pull}70138[#70138]
Discover::
* Sorts filter fields by items that start with typed characters {pull}68585[#68585]
* Adds error and warning statuses to FilterBar filters, according to the following scenarios {pull}66979[#66979]
Lens and visualizations::
* Fixes Date Histogram error when index does not have a time field {pull}69934[#69934]
Logs::
* Avoids CCS-incompatible index name resolution {pull}70179[#70179]
Machine Learning::
* Fixes expanded row bug when job has no datafeed {pull}68074[#68074]
* Fixes forever loading indicators in expanded data frame analytics list {pull}69422[#69422]
Management::
* Updates the "Learn about timing" documentation link when creating a policy in Index Lifecycle Management {pull}68923[#68923]
* Adds AggConfig.toSerializedFieldFormat {pull}69114[#69114]
* Fixes a bug in Cross-Cluster Replication where the "Status" column in the follower indices table did not update after pausing or resuming a follower index {pull}69228[#69228]
* Fixes a bug in Index Lifecycle Management where it was not possible to clear the index priority value when saving a policy {pull}70154[#70154]
* Fixes a bug in Cross-Cluster Replication where the user was prompted with an error message when attempting to use the UI with missing cluster privileges. The user should now be prompted
with a message indicating what privileges are missing {pull}70158[#70158]
* Ignores url.url fields above 2048 characters {pull}69863[#69863]
Maps::
* Fixes mb-style interpolate style rule {pull}68413[#68413]
* Fixes unable to edit heatmap metric {pull}70606[#70606]
Metrics::
* Fixes fatal error when no data is available for Metric Threshold Alerts {pull}68678[#68678]
* Fixes EuiTheme type issue {pull}69735[#69735]
Monitoring::
* Addresses a few longstanding issues with APM Stack Monitoring {pull}69052[#69052]
* Makes sure we fetch all collection status {pull}67172[#67172]
* Adds Cloud as an optional dependency {pull}69050[#69050]
* Fixes links missing a hash {pull}69861[#69861]
Operations::
* Adds spaces settings {pull}69019[#69019]
Platform::
* Don't allow empty string for server.basePath config {pull}69377[#69377]
Reporting::
* Don't set a min-length on encryption key for reporting {pull}69827[#69827]
SIEM::
* Eliminates Superfluous Untitled Timelines {pull}65783[#65783]
* Fixes 7.8 upgrade issue within rules where you can get the error "params invalid: [lists]: definition for this key is missing" {pull}69434[#69434]
* Excludes glob-only (*) Index Pattern from map layers {pull}69736[#69736]

[[release-notes-7.8.0]]
== {kib} 7.8.0

For detailed information about the {kib} 7.8.0 release, review the following information.

[[breaking-changes-7.8]]
=== Breaking changes

Breaking changes can prevent your application from optimal operation and performance. 
efore you upgrade to 7.8.0, review the breaking change, then mitigate the impact to your application.

// The following section is re-used in the Installation and Upgrade Guide


// tag::notable-breaking-changes[]

[float]
[[breaking_78_metrics_alerts]]
==== Metrics alerts action messaging refactored to report on the no data state
*Details* +
Metrics alerts no longer expose `context.valueOf`, `context.metricOf`, or
`context.thresholdOf` to action messages. These variables are replaced
by `context.reason`. This variable explains the reason that the alert
fired and automatically includes the metric, threshold, and current value of
all configured conditions.

*Impact* +
Alerts configured in 7.7 still function as normal,
but their action messages might no longer provide useful information and
must be reconfigured. The new default action message will show an example
of how to use `context.reason`.

*via https://github.com/elastic/kibana/pull/64365[#64365]*


[float]
[[breaking_fixes_back_button]]
==== Panels removed from the URL in dashboard view mode

====
*Details* +
In dashboard in view mode, `.panels` are no longer synced with the URL.

*Impact* +
This fixes the Back button when navigating between dashboards using drilldowns.

*via https://github.com/elastic/kibana/pull/62415[#62415]*
====


// end::notable-breaking-changes[]

[float]
[[deprecation-7.8.0]]
=== Deprecations
Platform::
* Deprecates IE11 support {kib-pull}66512[#66512]
Security::
* Deprecates {kib} user in favor of kibana_system user {kib-pull}63186[#63186]

[float]
[[known-issues-7.8.0]]
=== Known issue

SIEM::
* When you duplicate a rule with a deleted action connector, the duplication fails {kib-issue}69142[#69142]

[float]
[[enhancement-7.8.0]]
=== Enhancements
Alerting::
* Adds query support to the Event Log {kib-pull}62015[#62015]
* Removes edit alert button from alerts list {kib-pull}64643[#64643]
* Implements actions server API for supporting preconfigured connectors {kib-pull}62382[#62382]
* Adds UI for pre-configured connectors. {kib-pull}63074[#63074]
APM::
* Adda new Service map external icons {kib-pull}63844[#63844]
* Improves the selected node style {kib-pull}64279[#64279]
* Adds tooltip explaining Group ID {kib-pull}60425[#60425]
* Uses navigateToApp for infra/metrics/uptime links {kib-pull}65712[#65712]
* Observability real user monitoring solution layer {kib-pull}64949[#64949]
* Spans reparenting to support inferred spans {kib-pull}63695[#63695]
* Marks an Agent configuration as applied without etag attribute {kib-pull}63967[#63967]
* Agent remote config validation for Java agent configs {kib-pull}63956[#63956]
* Annotations API {kib-pull}64796[#64796]
* Adds Error Exception Type Column {kib-pull}59596[#59596]
* Service map anomaly indicators {kib-pull}64718[#64718]
Canvas::
* Adds Top Menu {kib-pull}59982[#59982]
* Adds refresh and autoplay options to view menu {kib-pull}64375[#64375]
* Adds edit menu {kib-pull}64738[#64738]
* Reduces report generation time by re-using headless browser page in background {kib-pull}63301[#63301]
Dashboard::
* Adds duplicate panel feature {kib-pull}61367[#61367]
* Return to dashboard after editing embeddable {kib-pull}62865[#62865]
Lens and visualizations::
* Triggers a filter action on click in datatable visualization {kib-pull}63840[#63840]
* Enables include/exclude in Terms agg for numeric fields {kib-pull}59425[#59425]
* Allows user to drag and select a subset of the timeline in the chart (aka brush interaction) {kib-pull}62636[#62636]
* Uses default {kib} palette for split series {kib-pull}62241[#62241]
* Removes duplicate refresh button from vis editor menu {kib-pull}63633[#63633]
* Binds all time fields to the time picker {kib-pull}63874[#63874]
* Uses Top 5 instead of Top 3 for first suggestion {kib-pull}64726[#64726]
* Adds pie and treemap charts {kib-pull}55477[#55477]
Machine Learning::
* Wizards with dynamic model memory estimation {kib-pull}60888[#60888]
* Shows better file structure finder explanations {kib-pull}62316[#62316]
* Adds configurable file size to file data visualizer {kib-pull}62752[#62752], {kib-pull}63502[#63502], {kib-pull}64427[#64427]
* Lists global calendars on the job management page {kib-pull}63124[#63124]
* Improves parsing of large uploaded files {kib-pull}62970[#62970]
* Enables mml estimation in data recognizer module setup {kib-pull}64900[#64900]
* Updates memory estimate after adding exclude fields {kib-pull}62850[#62850]
* Replaces table with data grid {kib-pull}63650[#63650] and {kib-pull}63757[#63757]
* Fixes feature importance {kib-pull}61761[#61761]
* Adds embeddable anomaly swimlane {kib-pull}65180[#65180]
* Improves progress reporting for analytics jobs {kib-pull}65305[#65305]
Management::
* Adds Ingest Node Pipelines UI {kib-pull}62321[#62321]
* Adds Transforms single column wizard {kib-pull}64436[#64436]
* Edits transform flyout {kib-pull}65033[#65033]
* Adds docs_per_second to transform edit form {kib-pull}65365[#65365]
Maps::
* Separates layer wizards for Clusters and heatmap {kib-pull}60870[#60870]
* Allows updating requestType for ESGeoGridSource {kib-pull}62365[#62365]
* Adds date-fields to metrics selection {kib-pull}62629[#62629]
* Shows create filter button for top-term tooltip property {kib-pull}62461[#62461]
* Turns on blended layer for geojson upload {kib-pull}63200[#63200]
* Updates geospatial filters to use geo_shape query for geo_point fields {kib-pull}62966[#62966]
* Min and max zoom map settings {kib-pull}63714[#63714]
* Shows spatial filters on map to provide context when for active filters {kib-pull}63406[#63406]
* Fits geo_shape to bounds {kib-pull}64303[#64303]
* Disables edit layer button when flyout is open for add layer or map settings {kib-pull}64230[#64230]
* Do not display EMS or {kib} layer wizards when not configured {kib-pull}64554[#64554]
* Initial location map settings {kib-pull}64336[#64336]
* Adds categorical palettes with 20 and 30 categories {kib-pull}64701[#64701]
* Adds oil rig icon from @elastic/maki {kib-pull}64364[#64364]
* Highlights selected layer in TOC {kib-pull}61510[#61510]
* Adds global fit to data {kib-pull}64702[#64702]
Metrics::
* View log in context modal {kib-pull}62198[#62198]
* Refreshes the design for Inventory View, Episode 1 {kib-pull}64026[#64026]
* Adds Charts to Alert Conditions {kib-pull}64384[#64384]
* Adds 99th and 95th percentiles to Metric Explorer {kib-pull}64699[#64699]
* Adds category data quality warning based on ML job stats {kib-pull}60551[#60551]
* Adds dataset filter to ML module setup screen {kib-pull}64470[#64470]
* Alerting {kib-pull}62806[#62806]
* Enhances Alerts management page {kib-pull}64654[#64654]
* Adds inventory metric threshold alerts {kib-pull}64292[#64292]
* Adds outside range comparator {kib-pull}63993[#63993]
Platform::
* Uses brotli compression for some KP assets {kib-pull}64367[#64367]
Reporting::
* Adds a new config flag to encode with BOM for our CSVs {kib-pull}63006[#63006]
* Adds config flag to escape formula CSV values {kib-pull}63645[#63645]
Security::
* Every provider can now be configured with the access agreement message (markdown syntax) that will be presented to the
users after login. Users won't be able to use Kibana until they acknowledge this agreement {kib-pull}63563[#63563]
* Login Selector UI was refined and can now offer much more customization options {kib-pull}64142[#64142]
SIEM::
* Enhances threat hunting for Filter for/out value, Show top field, Copy to Clipboard, Draggable chart legends {kib-pull}61207[#61207]
* Adds drag between ANDs in timeline queries / add to timeline {kib-pull}65228[#65228]
* Creates template timeline {kib-pull}63136[#63136]
* Adds lists feature flag and list values to the REST interfaces {kib-pull}60171[#60171]
* Adds an error aggregator by error reason and a way to filter them {kib-pull}63513[#63513]
* Adds large list support using REST endpoints {kib-pull}62552[#62552]
* Server cutover to New Platform {kib-pull}63430[#63430]
* Updates list values in REST interfaces {kib-pull}62320[#62320]
* Updates KQL/Lucene search to include lists exceptions {kib-pull}63264[#63264]
* Updates rule.lists to be rule.exceptions_list {kib-pull}63717[#63717]
* Moves All Rules tabs to match other tabs UI {kib-pull}63920[#63920]
* Minor updates to monitoring table with unit tests {kib-pull}64020[#64020]
* Moves jira to a gold license {kib-pull}67178[#67178]
Uptime::
* Adds cert API request and runtime type checking {kib-pull}63062[#63062]
* Updates TLS settings {kib-pull}64111[#64111]
* TLS alerting {kib-pull}63913[#63913]
* Adds new nav {kib-pull}64018[#64018]
* Certificate expiration threshold settings {kib-pull}63682[#63682]
* Certificates page {kib-pull}64059[#64059]
* Filters in create alert flyout {kib-pull}64753[#64753]
* Moves status filter to monitor list {kib-pull}65049[#65049]

[float]
[[bug-7.8.0]]
=== Bug fixes
Alerting::
* TaskManager tasks scheduled without attempting to run {kib-pull}62078[#62078]
* Only fetching TaskManager's available tasks once per call to fillPool {kib-pull}61991[#61991]
* Restores migrations of old tasks in TM {kib-pull}65978[#65978]
* Fixes pre-configured docs link points to the wrong page and functional tests configs {kib-pull}68606[#68606]
APM::
* Custom links section inside the Actions menu is showing outside of the menu {kib-pull}65428[#65428]
* Removes link from active page in the breadcrumb {kib-pull}65473[#65473]
* Agent configuration: Bug makes it possible to create invalid configurations {kib-pull}65508[#65508]
* Scope APM alert creation to environment {kib-pull}65681[#65681]
* Cannot click through to details of an error on the waterfall page if the error is missing `transaction.id` {kib-pull}66386[#66386]
* Removes service maps badge row and num instances in popover {kib-pull}65492[#65492]
* Handle ML integration when ML is disabled {kib-pull}66158[#66158]
* Fixes 'Enable watcher error reports' 400 error {kib-pull}68465[#68465]
* Updates apm index pattern {kib-pull}65424[#65424]
* Ensures that `/api/apm/security/indices_privileges` doesn't fail when security is disabled {kib-pull}64627[#64627]
* Fixes query bar Japanese translation {kib-pull}68037[#68037]
* Service map fix focused node edges on unselect {kib-pull}63655[#63655]
* Fixes duplicate index patterns {kib-pull}64883[#64883]
Canvas::
* Bug/pagination enabled empty workpad {kib-pull}62050[#62050]
Dashboard::
* Improves dashboard loading error handling {kib-pull}66372[#66372]
Design::
* Adds max-height to recently viewed links {kib-pull}66297[#66297]
Discover::
* match_all query disappears when typed into Lucene query bar {kib-pull}62194[#62194]
* KQL removes leading zero and breaks query {kib-pull}62748[#62748]
* Shows doc viewer action buttons on focus {kib-pull}64912[#64912]
* Fixes renaming of saved search not displayed in breadcrumb {kib-pull}67577[#67577]
* Replaces EuiTooltip by native title for better performance {kib-pull}68280[#68280]
* Clicking cancel in saved query save modal doesn't close it {kib-pull}62774[#62774]
Graph::
* Changes the copy from blacklist to blocklist {kib-pull}65419[#65419]
Kibana UI::
* Updates home link click handler {kib-pull}68132[#68132]
* Updates Canvas location in nav {kib-pull}65519[#65519]
* Fixes Recently Viewed links allowing them to close the nav when clicked {kib-pull}66280[#66280]
Lens and visualizations::
* Fixes redirect after reload {kib-pull}66328[#66328]
* Auto interval on date histogram is getting displayed as timestamp per… {kib-pull}59171[#59171]
* Fixes visualize and lens telemetry {kib-pull}67749[#67749]
* Removes redundant formatting of percentage column {kib-pull}64948[#64948]
* Uses correct text color in metric vis on dark background {kib-pull}67481[#67481]
* Fixes the problem on adding color rules {kib-pull}67763[#67763]
* Fixes bug where suggestions didn't use filters {kib-pull}63293[#63293]
* Only show copy on save for previously saved docs {kib-pull}63535[#63535]
* Fixes escaping of field names {kib-pull}63509[#63509]
* Makes average the default metric when dragging a field directly {kib-pull}63416[#63416]
* Fixes bug in field list when _source contained fields with dots {kib-pull}63752[#63752]
* Allows table to scroll horizontally {kib-pull}63805[#63805]
* Migrates timelion vis {kib-pull}62819[#62819]
* TSVB Validation fix color rule validation {kib-pull}67759[#67759]
Machine Learning::
* Fixes the limit control on the Anomaly explorer page {kib-pull}65459[#65459]
* Hides selector helper in Anomaly Explorer swimlane {kib-pull}65522[#65522]
* Fixes dashboard URLs for auditbeat module {kib-pull}65707[#65707]
* Fixes vertical overflow on Single Metric Viewer page {kib-pull}66413[#66413]
* Catches unknown index pattern errors {kib-pull}61935[#61935]
* Disables data frame anaylics clone button based on permission {kib-pull}64830[#64830]
* Disables calendar all job switch {kib-pull}65635[#65635]
* Shows warning when the model memory limit is higher than the memory available in the ML node {kib-pull}65652[#65652]
* Removes assignment_explanation when cloning job {kib-pull}68226[#68226]
* Ensures at least one field is included in analysis before data frame analytics job is created {kib-pull}65320[#65320]
* Anomaly Explorer: if filter includes wildcard ensure matching swimlanes are not masked {kib-pull}65384[#65384]
* Fixes reordering in view by swimlane when overall cell selected {kib-pull}65290[#65290]
* Fixes anomaly charts for rare detectors when model plot is enabled {kib-pull}66075[#66075]
* Adds job timing stats to anomaly jobs {kib-pull}65696[#65696]
* Fixes anomaly dot plotted in wrong location in Single Metric Viewer {kib-pull}66071[#66071]
Management::
* Fixes error when deleting snapshots behind reverse proxy {kib-pull}66147[#66147]
* Fixes bug when editing retention of slm policy {kib-pull}67137[#67137]
* Fixes fetch policies query {kib-pull}67827[#67827]
* Adds missing time unit labels {kib-pull}68205[#68205]
* Fixes pagination bugs in CCR and Remote Clusters {kib-pull}65931[#65931]
* Cleans up doc title when navigating away from Snapshot Restore {kib-pull}67906[#67906]
* Fixes boolean cell values in analytics table result views and transforms wizard {kib-pull}62618[#62618]
* Index pattern management - field list - localization functions returning empty strings {kib-pull}64055[#64055]
Maps::
* Fixes replaceLayerList to handle case where map is not intialized {kib-pull}62202[#62202]
* Safely handles empty string and invalid strings from EuiColorPicker {kib-pull}62507[#62507]
* Do not show circle border when symbol size is zero {kib-pull}62644[#62644]
* Fixes attribution overflow with exit full screen button {kib-pull}62699[#62699]
* Creates NOT EXISTS filter for tooltip property with no value {kib-pull}62849[#62849]
* Fixes bug where toggling Scaling type does not re-fetch data {kib-pull}63326[#63326]
* Fixes double fetch when filter pill is added {kib-pull}63024[#63024]
* Fixes term join agg key collision {kib-pull}63324[#63324]
* Fixes date labels {kib-pull}63909[#63909]
* Removes SLA percentage metric {kib-pull}65718[#65718]
* Removes dateline check for geo_shape queries, split geo_bounding_box queries that cross dateline into 2 boxes {kib-pull}64598[#64598]
* Handles case where fit to bounds does not match any documents {kib-pull}66307[#66307]
* Returns bounding box for static feature collection without joins {kib-pull}66607[#66607]
* Fixes legend icon color for custom categorial palettes {kib-pull}67141[#67141]
Metrics::
* Disables search bar when live stream is on {kib-pull}65491[#65491]
* Ensures live stream always gets latest entries {kib-pull}67935[#67935]
* Fixes time picker layout issues on Inventory View {kib-pull}66094[#66094]
* Fixes validation for threshold values {kib-pull}66281[#66281]
* Prevents component errors from breaking the whole UI {kib-pull}65456[#65456]
* Fixes mistake in container ip field name {kib-pull}66198[#66198]
* Fixes time state bug {kib-pull}67630[#67630]
* Require filterQuery to be ES JSON {kib-pull}64937[#64937]
* Debounce onChange in alert creation UI {kib-pull}65167[#65167]
* Fixes default metric alert interval for new conditions {kib-pull}66610[#66610]
Platform::
* Fixes inconsistent search behaviour in Advanced Settings {kib-pull}64510[#64510]
* SavedObjects bulkCreate API should return migrationVersion and strip the type &amp; namespace from the id {kib-pull}65150[#65150]
* Fixes task manager cancel warning {kib-pull}63756[#63756]
* New Kibana app link order {kib-pull}67991[#67991]
Security::
* Fix authentication loop when upgrading Kibana from 6.8 to 7.7+ {kib-pull}67687[#67687]
* Previously, users couldn't log in with SAML Identity Provider Initiated flow (e.g. from Okta Dashboard) if they already had
an existing, but expired session. Now it should be possible {kib-pull}59686[#59686]
* Fixes EncryptedSavedObjectsClientWrapper fails on stripEncryptedAttributes for saved object with errors {kib-pull}61385[#61385]
* Adds username/password validation to login form {kib-pull}60681[#60681]
SIEM::
* Fixes import bug with non existent signals index {kib-pull}65595[#65595]
* Restricts ML rule modification to ML Admins {kib-pull}65583[#65583]
* Fixes timeline buildGlobalQuery {kib-pull}68320[#68320]
Uptime::
* Refreshes index and also show more info to user regarding index/data {kib-pull}62606[#62606]
* Updates uptime ml job id to limit to 64 char {kib-pull}64394[#64394]
* Enables deselection of stale filters {kib-pull}65523[#65523]
* Unmounts uptime app properly {kib-pull}66950[#66950]