[[release-notes-7.7.1]]
== {kib} 7.7.1

For detailed information about the {kib} 7.7.1 release, review the following information.

[float]
[[security-update-7.1.1]]
=== Security update
In {kib} 5.4.0 and later, TSVB visualizations contain a stored XSS flaw. Attackers that can
edit and create TSVB visualizations can obtain sensitive information, or perform
destructive actions, on behalf of the {kib} users who edit the TSVB visualization, CVE-2020-7015.

You must upgrade to 7.7.1. If you are unable to upgrade, set `metrics.enabled:false` in your kibana.yml file to disable TSVB.

[float]
[[breaking-changes-v7.7.1]]
=== Breaking changes

For information about the breaking changes, refer to the <<breaking-changes-7.7,breaking changes in 7.7>>.

[float]
[[bug-7.7.1]]
=== Bug fixes
Alerting::
* Fixes bug with no possibility to edit the index name after adding {kib-pull}64033[#64033]
* Corrects validation and errors handling in PagerDuty action {kib-pull}63954[#63954]
* Fixes saving doc count alerts {kib-pull}63750[#63750]
* Fixes issue when connectors dropdown not showing all avaliable connectors {kib-pull}63636[#63636]
* Fixes inability to clear numeric field in a "Group over top docs" condition {kib-pull}63543[#63543]
* Handles when an Alerting Task fails due to its Alert object being deleted mid flight {kib-pull}63093[#63093]
APM:
* Encodes spaces when creating ML job {kib-pull}63683[#63683]
Canvas::
* Fixes bring to front shortcut label {kib-pull}67374[#67374]
* Fixes add page CSS animation bug {kib-pull}66496[#66496]
Dashboard::
* Shows visualization in Safari in dashboard fullscreen {kib-pull}66894[#66894]
* Fixes saved object share link {kib-pull}66771[#66771]
* Don't lose dashboard/visualize/discover state when navigating to other applications {kib-pull}66766[#66766]
Discover::
* Don't lose dashboard/visualize/discover state when navigating to other applications {kib-pull}66766[#66766]
Lens and visualizations::
* Fixes redirect on reload {kib-pull}66491[#66491]
* Timelion graph is not refreshing content after searching or filtering {kib-pull}67023[#67023]
* Don't lose dashboard/visualize/discover state when navigating to other applications {kib-pull}66766[#66766]
* Fixes redirect on reload {kib-pull}66491[#66491]
* Shows missing values on chart setting {kib-pull}66375[#66375]
* Usage of custom plugins using the @plugin statement and inline JavaScript in less code used in the TSVB Markdown
visualization is not allowed anymore. Using it will simply not apply the styles {kib-pull}65467[#65467]
* Fixes std deviation band mode {kib-pull}64413[#64413]
* Reloads on ui state change and fix ui state for tsvb {kib-pull}63699[#63699]
Machine Learning:
* Fixes watch creation {kib-pull}65956[#65956]
* Fixes new job wizard with multiple indices {kib-pull}64567[#64567]
* Fixes optional plugin dependency types {kib-pull}64450[#64450]
* Ensures both keyword/text types are excluded for selected excluded field {kib-pull}62712[#62712]
Management::
* Fixes an integration issue with the security plugin in Ingest Pipelines and Snapshot and Restore that would incorrectly
report requiring security to be enabled when the plugins should work normally without security.
This affects the default docker distribution {kib-pull}67308[#67308]
* Preserves saved object references when saving the object {kib-pull}66584[#66584]
* Fixes detail panel for indices with % in the name {kib-pull}66435[#66435]
* Setting dev_tools.enabled: false in kibana.yml will no longer crash Kibana {kib-pull}66276[#66276]
* Fixes `mappings` keyword in Index Management plugin (Index detail pane, Mapping tab) {kib-pull}66012#66012]
Maps::
* Handle cross cluster index _settings resp {kib-pull}66797[#66797]
* Fixes edit filter {kib-pull}64586[#64586]
Metrics::
* Migrating Docker network fields {kib-pull}65133[#65133]
* Removes APM Hard Dependency {kib-pull}64952[#64952]
* Fixes for editing alerts in alert management {kib-pull}64597[#64597]
* Fixes alerting when a filter query is present {kib-pull}64575[#64575]
* Allows users to create alerts from the central Alerts UI {kib-pull}63803[#63803]
* Remove remaining field filtering {kib-pull}63398[#63398]
Monitoring::
* Uses custom route to ensure global state is preserved {kib-pull}63891[#63891]
* Ensures time picker is actually disabled {kib-pull}63709[#63709]
* Fixes server response errors {kib-pull}63181[#63181]
Platform::
* Allows any type for customResponseHeaders config {kib-pull}66689[#66689]
Security::
* Allows IdP initiated SAML login with session containing expired token {kib-pull}59686[#59686]
SIEM::
* Updates alert apiKey when the rule is updated {kib-pull}67364[#67364]
* Fixes Network Map empty tooltip {kib-pull}66828[#66828]
* Changes find_statuses route HTTP method from GET to POST {kib-pull}63508[#63508]
Uptime::
* Updates duration chart query filters {kib-pull}63620[#63620]


[[release-notes-7.7.0]]
== {kib} 7.7.0

For detailed information about the Kibana 7.7.0 release, review the following information.

[float]
[[security-update-7.7.0]]
=== Security updates
* In 7.7.0 to 7.6.2, the Upgrade Assistant contains a prototype pollution flaw. An authenticated attacker with
privileges to write to the {kib} index can insert data that could cause {kib} to execute arbitrary code. This
could lead to an attacker executing code with the permissions of the {kib} process on the host system, CVE-2020-7012.
+
By default, the Upgrade Assistant flaw is mitigated in all {kib} instances accessed through {ess}.
+
For all other installations, you must upgrade to 7.7.0. If you are unable to upgrade, set `xpack.upgrade_assistant_enabled:false` in your kibana.yml file to disable the Upgrade Assistant.

* In 7.7.0 and earlier, TSVB contains a prototype pollution flaw. Authenticated attackers with privileges to create
TSVB visualizations can insert data that could cause {kib} to execute arbitrary code. This
could lead to an attacker executing code with the permissions of the {kib} process on the host system, CVE-2020-7013.
+
By default, the Upgrade Assistant flaw is mitigated in all {kib} instances accessed through {ess}.
+
For all other installations, you must upgrade to 7.7.0. If you are unable to upgrade, set `metrics.enabled:false` in your kibana.yml file to disable TSVB.

[[breaking-changes-7.7]]
=== Breaking changes

There are no breaking changes in 7.7.0.

[float]
[[deprecation-7.7.0]]
=== Deprecations
Monitoring::
* Changes all configs to `monitoring.*` {kib-pull}54919[#54919], {kib-pull}56215[#56215]
Platform::
* Migrates Vega and Graph configs to new platform {kib-pull}57011[#57011]

[float]
[[known-issues-7.7.0]]
=== Known issues
Configuration::
* The `server.customResponseHeaders` option prevents {kib} from starting if headers are set using a type other than string.
To fix this, convert your boolean and number headers to strings.  For example, use `my-header: "true"` instead of `my-header: true`.
{kib-issue}66146[#66146]
Management::
* Editing Saved Objects (eg. Dashboards) via the "Inspect" JSON editor in Management corrupts objects {kib-issue}66542[#66542]
SIEM::
* When you deactivate an action within a rule, the rule fails {kib-issue}64870[#64870]
* When you add a timestamp to the PagerDuty action, the rule fails {kib-issue}64871[#64871]

[float]
[[enhancement-7.7.0]]
=== Enhancements
Alerting::
* Notifies user when security is enabled but TLS is not {kib-pull}60270[#60270]
* Displays warning when a permanent encryption key is missing and hides alerting UI appropriately {kib-pull}62772[#62772]
* Edits alert flyout {kib-pull}58964[#58964]
* Moves index params fields to connector config {kib-pull}60349[#60349]
* Adds the AlertDetails page {kib-pull}55671[#55671]
* License checks for actions plugin {kib-pull}59070[#59070]
APM::
* Updates monospace font family variable {kib-pull}57555[#57555]
* Shows missing permissions message to the user on the Services overview {kib-pull}56374[#56374]
* Settings list page for managing custom actions {kib-pull}56853[#56853]
* Divides &quot;Actions menu&quot; into sections to improve readability {kib-pull}56623[#56623]
* Creates settings page to manage Custom Links {kib-pull}57788[#57788]
* Creates custom link from Trace summary {kib-pull}59648[#59648]
* Writes tests for the Custom Link API {kib-pull}60899[#60899]
* Threshold alerts  {kib-pull}59566[#59566]
* Adds additional (java) options {kib-pull}59860[#59860]
* Sync badge {kib-pull}55113[#55113]
* Client.ip to metadata for RUM transactions {kib-pull}56546[#56546]
Canvas::
* Adds Lens embeddables {kib-pull}57499[#57499]
* Switches to using EUI SuperDatePicker in time filter element {kib-pull}59249[#59249]
* Adds Visualize embeddable {kib-pull}60859[#60859]
* Adds argument to open all links in new tab within markdown element {kib-pull}57017[#57017]
* Updates esdocs datasource {kib-pull}59512[#59512]
* Improves expression autocomplete {kib-pull}52035[#52035]
Dashboard::
* Use Elasticsearch `_async_search` instead of `_search` when it is available (excluding TSVB, Timelion, and Vega) {kib-pull}59224[#59224}
* When queries run more than 10 seconds, show a pop-up to allow users to run the queries beyond the configured Elasticsearch query timeout or cancel the queries {kib-pull}60706[#60706]
* Dashboard/add panel flow {kib-pull}59918[#59918]
* Moves the "Create New" button in add panel flyout to the top to make it more visible to the user {kib-pull}56428[#56428]
Lens and visualizations::
* Creates Lens filters on click with bar, line, area charts {kib-pull}57261[#57261]
* Allows number formatting within Lens {kib-pull}56253[#56253]
* Shows a warning when you have partially configured a visualization, such as a bar chart with only an X axis {kib-pull}58279[#58279]
* Improves suggestion logic when dragging fields into the chart {kib-pull}60687[#60687]
* Disallows duplicate percentiles {kib-pull}58299[#58299]
* EUICodeEditor for Visualize JSON  {kib-pull}58679[#58679]
* Supports Histogram Data Type {kib-pull}59387[#59387]
* Median aggregation labels now show "Median" instead of "50th percentile of" in Visualize. Custom labels are also used {kib-pull}58521[#58521]
* Adds positive_rate as a new aggregation to TSVB {kib-pull}59843[#59843]
* Makes linked saved search work when user navigates back using browser back button {kib-pull}59690[#59690]
* Visualization editor UI has been updated to the new styles, consistent with the rest of the platform and a more logical left-to-right flow of creating content {kib-pull}49864[#49864]
Logs::
* Uses the Super date picker in the log stream {kib-pull}54280[#54280]
* Adds expandable rows with category examples {kib-pull}54586[#54586]
* Shows navigation bar while loading source configuration {kib-pull}59997[#59997]
Machine Learning::
* Processes delimited files like semi-structured text {kib-pull}56038[#56038]
* Supports multi-line JSON notation  {kib-pull}58870[#58870]
* Validates manual model memory input {kib-pull}59056[#59056]
* Clones analytics job  {kib-pull}59791[#59791]
* Uses a new ML endpoint to estimate a model memory {kib-pull}60376[#60376]
* Module setup with dynamic model memory estimation {kib-pull}60656[#60656]
* Adds text fields to datafeed start modal {kib-pull}55560[#55560]
* Categorization examples privilege check {kib-pull}57375[#57375]
* Adds filebeat config to file dataviz {kib-pull}58152[#58152]
* Global calendars {kib-pull}57890[#57890]
* Adds indices_options to datafeed {kib-pull}59119[#59119]
* Displays multi-class results in evaluate panel {kib-pull}60760[#60760]
* Adds support for date_nanos time field in anomaly job wizard {kib-pull}59017[#59017]
* Uses EuiDataGrid for outlier result page {kib-pull}58235[#58235]
* Supports multi-line JSON notation in advanced editor {kib-pull}58015[#58015]
* Adds support for percentiles aggregation to Transform wizard {kib-pull}60763[#60763]
* Adds clone feature to transforms list {kib-pull}57837[#57837]
* Uses EuiDataGrid for transform wizard {kib-pull}52510[#52510]
* Replaces KqlFilterBar with QueryStringInput {kib-pull}59723[#59723]
Management::
* The Remote Clusters UI added support for enabling "proxy" mode when creating or editing a remote cluster {kib-pull}59221[#59221]
* Adds filter for ILM phase to Index Management {kib-pull}57402[#57402]
* Creates Painless Lab app {kib-pull}57538[#57538]
* Moves out of legacy {kib-pull}55331[#55331]
* Moves out of legacy and migrates server side to New Platform {kib-pull}55690[#55690]
* Updates Console progress bar {kib-pull}56628[#56628]
* Auto follow pause &amp; resume {kib-pull}56615[#56615]
* Supports triple quoted JSON strings and Painless highlighting to Watcher and SearchProfiler {kib-pull}57563[#57563]
* Server-side batch reindexing {kib-pull}58598[#58598]
* Better handling of closed indices {kib-pull}58890[#58890]
* Advanced settings UI change to centralize save state {kib-pull}53693[#53693]
* The autocomplete in the dev console now supports many different types of Elasticsearch pipeline processors {kib-pull}60553[#60553]
Maps::
* Improves Layer Style UI {kib-pull}58406[#58406]
* Shows field type icons in data driven styling field select {kib-pull}55166[#55166]
* Style icons by category {kib-pull}55747[#55747]
* Adds type icons to SingleFieldSelect component {kib-pull}56313[#56313]
* Disables style forms when they are not applied due to other style settings {kib-pull}55858[#55858]
* Autocompletes for custom color palettes and custom icon palettes {kib-pull}56446[#56446]
* Allows simultaneous opening of multiple tooltips {kib-pull}57226[#57226]
* Adds Top term aggregation {kib-pull}57875[#57875]
* Direct Discover &quot;visualize&quot; to open Maps application {kib-pull}58549[#58549]
* Top term percentage field property {kib-pull}59386[#59386]
* Adds UI to disable style meta and get top categories from current features {kib-pull}59707[#59707]
* Adds draw control to create distance filter {kib-pull}58163[#58163]
* Blended layer that switches between documents and clusters {kib-pull}57879[#57879]
* Default ES document layer scaling type to clusters and show scaling UI in the create wizard {kib-pull}60668[#60668]
* Disables add layer button when flyout is open {kib-pull}54932[#54932]
* Supports categorical styling for numbers and dates {kib-pull}57908[#57908]
Metrics::
* Setup commonly used time ranges in timepicker {kib-pull}56701[#56701]
* Custom Metrics for Inventory View {kib-pull}58072[#58072]
* Alerting for metrics explorer and inventory {kib-pull}58779[#58779]
* Creates a new menu for observability links {kib-pull}54847[#54847]
* Creates Metric Threshold Alert Type and Executor {kib-pull}57606[#57606]
Monitoring::
* Supports shipping directly to the monitoring cluster {kib-pull}57022[#57022]
Platform::
* Improves validation in truncate field formatter editor {kib-pull}56521[#56521]
* Variable support for interpreter {kib-pull}54788[#54788]
Reporting::
* Handles page setup errors and capture the page, don't fail the job {kib-pull}58683[#58683]
* Adds the ability to search and delete historical reports in Management > Kibana > Reporting {kib-pull}60077[#60077]
SIEM::
* Recent cases widget {kib-pull}60993[#60993]
* Adds custom reputation link {kib-pull}57814[#57814]
* Exports timeline {kib-pull}58368[#58368]
* Rule activity monitoring {kib-pull}60816[#60816]
* Removes has manage api keys requirement {kib-pull}62446[#62446]
* Adds release notes link and updates one UI section {kib-pull}60825[#60825]
* Adds rule notifications {kib-pull}59004[#59004]
* Version 7.7 rule import {kib-pull}61903[#61903]
* Creates ML Rules {kib-pull}58053[#58053]
* Case workflow api schema {kib-pull}51535[#51535]
* Service Now {kib} Action {kib-pull}53890[#53890]
* API with io-ts validation {kib-pull}59265[#59265]
* Status / Batch update {kib-pull}59856[#59856]
* Imports timeline {kib-pull}60880[#60880]
* Bug/clean up phase I {kib-pull}61354[#61354]
* Cases clean up Phase II {kib-pull}61750[#61750]
* Modifies gap detection util to accept all dateMath formats {kib-pull}56055[#56055]
* Adds note markdown field to backend {kib-pull}59796[#59796]
* Adds rule markdown field to rule create, detail, and edit flows {kib-pull}60108[#60108]
* Adds rule markdown to timeline global notes {kib-pull}61026[#61026]
* ServiceNow executor {kib-pull}58894[#58894]
* ServiceNow action improvements {kib-pull}60052[#60052]
Security::
* Uses links instead of click handlers when switching spaces {kib-pull}57730[#57730]
* Introduce a login selector screen when multiple auth providers are enabled {kib-pull}53010[#53010]
* Warn when using deprecated roles {kib-pull}57209[#57209]
* Support for subfeature privileges {kib-pull}60563[#60563]
Telemetry::
* Application Usage implemented in @kbn/analytics {kib-pull}58401[#58401]
* Server-side Migration to NP {kib-pull}60485[#60485]
* Use EuiTokens for ES field types {kib-pull}57911[#57911]
* Adds 7 day metrics to Application Usage telemetry {kib-pull}59846[#59846]
Uptime::
* Adds Settings Page {kib-pull}53550[#53550]
* Adds Alerting UI {kib-pull}57919[#57919]
* Adds configurable page size to monitor list {kib-pull}60573[#60573]
* Adds Green Icon for all up Monitors {kib-pull}56770[#56770]
* Implements drag and select on charts {kib-pull}57089[#57089]
* Fix/filter group autocomplete {kib-pull}57686[#57686]
* Ml detection of duration anomalies {kib-pull}59785[#59785]

[float]
[[bug-7.7.0]]
=== Bug fixes
Alerting::
* Retains empty AlertsList when filter has removed all items {kib-pull}60501[#60501]
* Fixes alert threshold line disappears {kib-pull}61499[#61499]
* Cleanup action task params objects after successful execution {kib-pull}55227[#55227]
* Disables action plugin functionality when ESO plugin is using an ephemeral encryption key {kib-pull}56906[#56906]
* Makes slack param validation handle empty messages {kib-pull}60468[#60468]
* Makes user and password secrets optional {kib-pull}56823[#56823]
APM::
* Changes &quot;url&quot; to &quot;urls&quot; in APM agent instructions {kib-pull}60790[#60790]
* Uses ES Permission API to check if a user has permissions to read from APM indices {kib-pull}57311[#57311]
* Filters are not prefilled when the custom link flyout is opened from a transaction page {kib-pull}61650[#61650]
* .apm-agent-configuration is not created if {kib} is started while ES is not ready {kib-pull}61610[#61610]
* Don’t include UI filters when fetching a specific transaction {kib-pull}57934[#57934]
* Uses docLinks API for APM doc links {kib-pull}61880[#61880]
* Updates APM index pattern {kib-pull}61265[#61265]
Canvas::
* Toggles footer editable controls when you turn off edit mode #52786 {kib-pull}58044[#58044]
* Fixes map embeddables not showing up on PDF reports {kib-pull}61149[#61149]
* Limits rows in debug element {kib-pull}60804[#60804]
Dashboard::
* Puts embed param into short url instead of behind it {kib-pull}58846[#58846]
* Allows markdown in error embeddable {kib-pull}62427[#62427]
Discover::
* Removes flickering when opening filter bar popover {kib-pull}56222[#56222]
* Retains pinned filters when loading and clearing saved queries {kib-pull}54307[#54307]
Graph::
* Specifies valid licenses for the Graph feature {kib-pull}55911[#55911]
* Improves graph missing workspace error message {kib-pull}58876[#58876]
Lens and visualizations::
* Filters out pinned filters from saved object of Lens {kib-pull}57197[#57197]
* Adds using queries/filters for field existence endpoint {kib-pull}59033[#59033]
* Fixes display single bar in XYChart Bar Vis {kib-pull}61452[#61452]
* Resetting a layer generates new suggestions {kib-pull}60674[#60674]
* Fixes disabled switches in the editor {kib-pull}62911[#62911]
* Fixes broken Handlebar documentation links {kib-pull}55866[#55866]
* Shows timepicker in Timelion and TSVB {kib-pull}58857[#58857]
* Makes Vega remove filter work {kib-pull}58871[#58871]
* Makes d3 place nicely with object values {kib-pull}62004[#62004]
* Fixes position calculation of ticks in non-horizontal axes {kib-pull}62309[#62309]
Logs::
* Correctly update the expanded log rate table rows {kib-pull}60306[#60306]
Machine Learning::
* Handles Empty Partition Field Values in Single Metric Viewer {kib-pull}61649[#61649]
* Fixes job wizard model memory limit warnings {kib-pull}62331[#62331]
* Files data viz fix index pattern warning after index change {kib-pull}57807[#57807]
* Uses real datafeed ID for datafeed preview {kib-pull}60275[#60275]
* Disables start trial option when license management ui is disabled {kib-pull}60987[#60987]
* Fixes jobs list filter in url {kib-pull}61822[#61822]
* Fixes job ID in edit job flyout {kib-pull}61840[#61840]
* Fixes reporting of http request errors {kib-pull}61811[#61811]
* Ensures confusion matrix label column is correct {kib-pull}60308[#60308]
* Ensures column in correct position after reselect  {kib-pull}61342[#61342]
* Ensures query bar syntax errors are shown  {kib-pull}61333[#61333]
* Ensures job state is up to date {kib-pull}61678[#61678]
* Increases number of items that can be paged in calendars and filters lists {kib-pull}61842[#61842]
* Uses index pattern field format if one exists {kib-pull}61709[#61709]
* Ensures filter works as expected {kib-pull}62041[#62041]
* Ensures destination index pattern created {kib-pull}62450[#62450]
* Fixes page heading structure {kib-pull}56741[#56741]
* Fixes handling of index pattern with special characters {kib-pull}59884[#59884]
* Fixes to error handling for analytics jobs and file data viz {kib-pull}60249[#60249]
* Fixes Anomaly Explorer swimlane label and chart tooltips {kib-pull}61327[#61327]
* Prevents training_percent of 0 for analytics job {kib-pull}61789[#61789]
* Removes duplicate page main landmarks {kib-pull}56883[#56883]
* Fixes license check {kib-pull}58343[#58343]
* Clears {kib} index pattern cache on creation or form reset {kib-pull}62184[#62184]
Management::
* Adds support for additional watch action statuses {kib-pull}55092[#55092]
* Fixes the Upgrade Assistant where the reindexing of an index was incorrectly marked as "Done", when it still required to be reindexed. This scenario could occur if a user reindexed an index, deleted it, then restored a snapshot of the index of an older version {kib-pull}60789[#60789]
* Fixes several invalid documentation links in the Snapshot and Restore UI {kib-pull}61331[#61331]
* Fixes for console error handling and loading of autocomplete {kib-pull}58587[#58587]
* Fixes a bug that caused Grokdebugger simulation to break in non-Default Kibana spaces {kib-pull}61423[#61423]
* Fixes an issue where Console would not render the request output if localStorage quota was reached {kib-pull}62424[#62424]
* Fixes a bug with Console's Copy As cURL functionality that would not properly escape single quotes in JSON string values which created issues with copying SQL queries from Console to cURL {kib-pull}63229[#63229]
* System index templates can't be edited {kib-pull}55229[#55229]
* Not possible to edit a watch that was created with the API if the ID contains a dot {kib-pull}59383[#59383]
* Fixes console a11y failures {kib-pull}57520[#57520]
Maps::
* Do not show border color for icon in legend when border width is zero {kib-pull}57501[#57501]
* Uses blended layer when linking discover to maps {kib-pull}61467[#61467]
* Fixes tooltip overflow {kib-pull}61564[#61564]
* Cleans up unsaved state check {kib-pull}61705[#61705]
* Fixes regression in loading left join fields {kib-pull}63325[#63325]
* Fixes cross origin error for icon spritesheets when Kibana secured via OAuth proxy {kib-pull}53896[#53896]
* Correctly open layer settings from add layer wizard {kib-pull}48971[#48971]
Metrics::
* Limits group by selector to only 2 fields {kib-pull}56800[#56800]
* Uses CPU Usage limits for Kubernetes pods when available {kib-pull}58424[#58424]
* Fixes toolbar popover for metrics table row {kib-pull}56796[#56796]
Monitoring::
* Handles setup mode if security is disabled {kib-pull}53306[#53306]
* Protects against no monitoring data near end of time series {kib-pull}61273[#61273]
* Adds new config for logging index name {kib-pull}56920[#56920]
Platform::
* Rollup index pattern error: must match one rollup index {kib-pull}56732[#56732]
* In scripted fields, unable to switch the `Type` {kib-pull}59285[#59285]
* Duplicates query filters in es request {kib-pull}60106[#60106]
* Bugfix dashboard unpins filters {kib-pull}62301[#62301]
* Fixes plugin enabled config options {kib-pull}60998[#60998]
* Fixes tabifyAggResponse {kib-pull}61214[#61214]
* Fixes parse interval {kib-pull}62267[#62267]
* Avoid 'app not found' flickering while awaiting for mount {kib-pull}56483[#56483]
* Creates empty string filters when value not specified {kib-pull}57442[#57442]
* Range aggregations now use the field formatter from the index pattern, instead of no formatter {kib-pull}58651[#58651]
Reporting::
* Fixes error handling for job handler in route {kib-pull}60161[#60161]
Security::
* Handling a 404 when the space's telemetry collector runs {kib-pull}55921[#55921]
SIEM::
* Allows Import timeline for authorised users {kib-pull}61438[#61438]
* Imports timeline schema update {kib-pull}61622[#61622]
* Fixes bug with timeline templates not working {kib-pull}60476[#60476]
* Fixes export of single rule and the icons {kib-pull}62394[#62394]
* Updates process and TLS tables to use ECS 1.5 fields {kib-pull}60854[#60854]
Telemetry::
* Fixes bug introduced in #55859 {kib-pull}57441[#57441]
* UI Metrics use findAll to retrieve all Saved Objects {kib-pull}59891[#59891]
Uptime::
* Updates heartbeat index name for 7.7 {kib-pull}62172[#62172]
* Shows only total in snapshot heading {kib-pull}58376[#58376]
* Fixes PingList pagination {kib-pull}61481[#61481]
* Fixes es query function null reference errors {kib-pull}61465[#61465]
* Fixes issue with Kibana Icon in Uptime App {kib-pull}56837[#56837]
* Adds tests for pages {kib-pull}56736[#56736]