/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Find Attack Discovery Schedules API endpoint
 *   version: 2023-10-31
 */

import { z } from '@kbn/zod';

import { NonEmptyString } from '../../../../../common_attributes.gen';
import { AttackDiscoveryApiSchedule } from '../schedules_api.gen';

export type FindAttackDiscoverySchedulesRequestQuery = z.infer<
  typeof FindAttackDiscoverySchedulesRequestQuery
>;
export const FindAttackDiscoverySchedulesRequestQuery = z.object({
  /**
   * Page number to return (used for pagination). Defaults to 1.
   */
  page: z.coerce.number().optional(),
  /**
   * Number of Attack discovery schedules to return per page (used for pagination). Defaults to 10.
   */
  per_page: z.coerce.number().optional(),
  /**
   * Field used to sort results. Common fields include 'name', 'created_at', 'updated_at', and 'enabled'.
   */
  sort_field: NonEmptyString.optional(),
  /**
   * Sort order direction. Use 'asc' for ascending or 'desc' for descending. Defaults to 'asc'.
   */
  sort_direction: z.enum(['asc', 'desc']).optional(),
});
export type FindAttackDiscoverySchedulesRequestQueryInput = z.input<
  typeof FindAttackDiscoverySchedulesRequestQuery
>;

export type FindAttackDiscoverySchedulesResponse = z.infer<
  typeof FindAttackDiscoverySchedulesResponse
>;
export const FindAttackDiscoverySchedulesResponse = z.object({
  /**
   * Current page number of the paginated result set.
   */
  page: z.number(),
  /**
   * Number of items requested per page.
   */
  per_page: z.number(),
  /**
   * Total number of Attack discovery schedules matching the query (across all pages).
   */
  total: z.number(),
  /**
   * Array of matched Attack discovery schedule objects.
   */
  data: z.array(AttackDiscoveryApiSchedule),
});
