/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Delete External Rule Source API endpoint
 *   version: 1
 */

import { z } from 'zod';

import { ExternalRuleSourceOutput } from '../model/external_rule_source.gen';

export type DeleteExternalRuleSourceRequestBody = z.infer<
  typeof DeleteExternalRuleSourceRequestBody
>;
export const DeleteExternalRuleSourceRequestBody = z.object({
  /**
   * The unique identifier of the external rule source
   */
  id: z.string(),
});
export type DeleteExternalRuleSourceRequestBodyInput = z.input<
  typeof DeleteExternalRuleSourceRequestBody
>;

/**
 * The external rule source that was deleted
 */
export type DeleteExternalRuleSourceResponse = z.infer<typeof DeleteExternalRuleSourceResponse>;
export const DeleteExternalRuleSourceResponse = ExternalRuleSourceOutput;
