import React from 'react';
import type { DatePickerProps } from './date_picker';
import type { FilterValueLabelProps } from './filter_value_label/filter_value_label';
import type { SelectableUrlListProps } from './exploratory_view/components/url_search/selectable_url_list';
import type { ExploratoryViewPageProps } from './exploratory_view';
export type { LazyObservabilityPageTemplateProps } from '@kbn/observability-shared-plugin/public';
export declare function FilterValueLabel(props: FilterValueLabelProps): React.JSX.Element;
export declare function SelectableUrlList(props: SelectableUrlListProps): React.JSX.Element;
export declare function ExploratoryView(props: ExploratoryViewPageProps): React.JSX.Element;
export declare function DatePicker(props: DatePickerProps): React.JSX.Element;
