import React from 'react';
import type { EuiFormRowProps } from '@elastic/eui';
import type { IUiSettingsClient, HttpSetup } from '@kbn/core/public';
import type { DataViewsPublicPluginStart } from '@kbn/data-views-plugin/public';
import type { FieldFormatsStart } from '@kbn/field-formats-plugin/public';
import type { IStorageWrapper } from '@kbn/kibana-utils-plugin/public';
import type { DataPublicPluginStart } from '@kbn/data-plugin/public';
import type { FormBasedLayer, IndexPattern, IndexPatternField, ParamEditorCustomProps, IncompleteColumn, GenericIndexPatternColumn, DateRange } from '@kbn/lens-common';
import type { KqlPluginStart } from '@kbn/kql/public';
import type { RequiredReference, GenericOperationDefinition } from '../operations';
import type { FieldChoiceWithOperationType } from './field_select';
import type { FormBasedDimensionEditorProps } from './dimension_panel';
export interface ReferenceEditorProps {
    layer: FormBasedLayer;
    layerId: string;
    activeData?: FormBasedDimensionEditorProps['activeData'];
    selectionStyle: 'full' | 'field' | 'hidden';
    validation: RequiredReference;
    columnId: string;
    column?: GenericIndexPatternColumn;
    incompleteColumn?: IncompleteColumn;
    currentIndexPattern: IndexPattern;
    functionLabel?: string;
    fieldLabel?: string;
    operationDefinitionMap: Record<string, GenericOperationDefinition>;
    isInline?: boolean;
    dateRange: DateRange;
    labelAppend?: EuiFormRowProps['labelAppend'];
    isFullscreen: boolean;
    toggleFullscreen: () => void;
    paramEditorCustomProps?: ParamEditorCustomProps;
    paramEditorUpdater: (setter: FormBasedLayer | ((prevLayer: FormBasedLayer) => FormBasedLayer) | GenericIndexPatternColumn) => void;
    onChooseField: (choice: FieldChoiceWithOperationType) => void;
    onDeleteColumn: () => void;
    onResetIncomplete: () => void;
    onChooseFunction: (operationType: string, field?: IndexPatternField) => void;
    uiSettings: IUiSettingsClient;
    storage: IStorageWrapper;
    http: HttpSetup;
    data: DataPublicPluginStart;
    fieldFormats: FieldFormatsStart;
    kql: KqlPluginStart;
    dataViews: DataViewsPublicPluginStart;
}
export declare const ReferenceEditor: (props: ReferenceEditorProps) => React.JSX.Element | null;
