/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Update value list API endpoint
 *   version: 2023-10-31
 */

import { z, lazySchema } from '@kbn/zod/v4';

import {
  ListId,
  ListName,
  ListDescription,
  ListMetadata,
  ListVersion,
  ListVersionId,
} from '../model/list_common.gen';
import { List } from '../model/list_schemas.gen';

export const UpdateListRequestBody = lazySchema(() =>
  z.object({
    id: ListId,
    name: ListName,
    description: ListDescription,
    meta: ListMetadata.optional(),
    version: ListVersion.optional(),
    _version: ListVersionId.optional(),
  })
);
export type UpdateListRequestBody = z.infer<typeof UpdateListRequestBody>;
export type UpdateListRequestBodyInput = z.input<typeof UpdateListRequestBody>;

export const UpdateListResponse = lazySchema(() => List);
export type UpdateListResponse = z.infer<typeof UpdateListResponse>;
