export { createSingleCompileConfig, type SingleCompileConfigOptions, signalShutdown, resetShutdown, } from './config/create_single_compile_config';
export { createExternalPluginConfig, type ExternalPluginConfigOptions, } from './config/create_external_plugin_config';
export { getSharedResolveConfig, getSharedResolveFallback, getSharedModuleRules, getSharedIgnoreWarnings, getScssLoaderRule, } from './config/shared_config';
export { themeLoader } from './loaders';
export { getExternals } from './config/externals';
export { runBuild, type BuildOptions, type BuildResult } from './run_build';
export { runRspackCli, type CliOptions } from './cli';
export { RspackOptimizer, type RspackOptimizerOptions, type OptimizerPhase } from './optimizer';
export { discoverPlugins, type PluginEntry } from './utils/plugin_discovery';
export { readLimits, validateLimitsForAllBundles, updateBundleLimits, DEFAULT_LIMITS_PATH, } from './limits';
export type { Limits } from './limits';
export type { ThemeTag } from './types';
export type { Configuration, Stats, Compiler, RspackPluginInstance } from '@rspack/core';
