import type * as APM_EVENT_FIELDS_MAP from '@kbn/apm-types/es_fields';
import type { DedotObject } from '@kbn/utility-types';
import type { ValuesType } from 'utility-types';
import type { AgentName } from '@kbn/elastic-agent-utils';
import type { EventOutcome, StatusCode } from '@kbn/apm-types/src/es_schemas/raw/fields';
import type { ProcessorEvent } from '@kbn/apm-types-shared';
declare const CONCRETE_FIELDS: {
    ID: "_id";
    TIMESTAMP_US: "timestamp.us";
    AT_TIMESTAMP: "@timestamp";
    AGENT_NAME: "agent.name";
    AGENT_VERSION: "agent.version";
    AGENT_ACTIVATION_METHOD: "agent.activation_method";
    DESTINATION_ADDRESS: "destination.address";
    CLOUD_AVAILABILITY_ZONE: "cloud.availability_zone";
    CLOUD_PROVIDER: "cloud.provider";
    CLOUD_REGION: "cloud.region";
    CLOUD_MACHINE_TYPE: "cloud.machine.type";
    CLOUD_ACCOUNT_ID: "cloud.account.id";
    CLOUD_ACCOUNT_NAME: "cloud.account.name";
    CLOUD_INSTANCE_ID: "cloud.instance.id";
    CLOUD_INSTANCE_NAME: "cloud.instance.name";
    CLOUD_SERVICE_NAME: "cloud.service.name";
    CLOUD_PROJECT_NAME: "cloud.project.name";
    EVENT_SUCCESS_COUNT: "event.success_count";
    SERVICE_NAME: "service.name";
    SERVICE_ENVIRONMENT: "service.environment";
    SERVICE_FRAMEWORK_NAME: "service.framework.name";
    SERVICE_FRAMEWORK_VERSION: "service.framework.version";
    SERVICE_LANGUAGE_NAME: "service.language.name";
    SERVICE_LANGUAGE_VERSION: "service.language.version";
    SERVICE_RUNTIME_NAME: "service.runtime.name";
    SERVICE_RUNTIME_VERSION: "service.runtime.version";
    SERVICE_NODE_NAME: "service.node.name";
    SERVICE_VERSION: "service.version";
    SERVICE_TARGET_TYPE: "service.target.type";
    SERVICE_OVERFLOW_COUNT: "service_transaction.aggregation.overflow_count";
    URL_FULL: "url.full";
    HTTP_REQUEST_METHOD: "http.request.method";
    HTTP_RESPONSE_STATUS_CODE: "http.response.status_code";
    USER_ID: "user.id";
    USER_AGENT_ORIGINAL: "user_agent.original";
    USER_AGENT_NAME: "user_agent.name";
    USER_AGENT_VERSION: "user_agent.version";
    OBSERVER_VERSION: "observer.version";
    OBSERVER_VERSION_MAJOR: "observer.version_major";
    OBSERVER_HOSTNAME: "observer.hostname";
    OBSERVER_LISTENING: "observer.listening";
    PROCESSOR_EVENT: "processor.event";
    PROCESSOR_NAME: "processor.name";
    TRANSACTION_MARKS_AGENT: "transaction.marks.agent";
    TRANSACTION_DURATION: "transaction.duration.us";
    TRANSACTION_DURATION_HISTOGRAM: "transaction.duration.histogram";
    TRANSACTION_DURATION_SUMMARY: "transaction.duration.summary";
    TRANSACTION_TYPE: "transaction.type";
    TRANSACTION_RESULT: "transaction.result";
    TRANSACTION_NAME: "transaction.name";
    TRANSACTION_ID: "transaction.id";
    TRANSACTION_SAMPLED: "transaction.sampled";
    TRANSACTION_PAGE_URL: "transaction.page.url";
    TRANSACTION_FAILURE_COUNT: "transaction.failure_count";
    TRANSACTION_SUCCESS_COUNT: "transaction.success_count";
    TRANSACTION_OVERFLOW_COUNT: "transaction.aggregation.overflow_count";
    TRANSACTION_ROOT: "transaction.root";
    TRANSACTION_PROFILER_STACK_TRACE_IDS: "transaction.profiler_stack_trace_ids";
    ELASTIC_PROFILER_STACK_TRACE_IDS: "elastic.profiler_stack_trace_ids";
    EVENT_OUTCOME: "event.outcome";
    TRACE_ID: "trace.id";
    SPAN_DURATION: "span.duration.us";
    SPAN_TYPE: "span.type";
    SPAN_SUBTYPE: "span.subtype";
    SPAN_SELF_TIME_SUM: "span.self_time.sum.us";
    SPAN_ACTION: "span.action";
    SPAN_NAME: "span.name";
    SPAN_ID: "span.id";
    SPAN_DESTINATION_SERVICE_RESOURCE: "span.destination.service.resource";
    SPAN_DESTINATION_SERVICE_RESPONSE_TIME_COUNT: "span.destination.service.response_time.count";
    SPAN_DESTINATION_SERVICE_RESPONSE_TIME_SUM: "span.destination.service.response_time.sum.us";
    SPAN_LINKS_TRACE_ID: "span.links.trace.id";
    SPAN_LINKS_SPAN_ID: "span.links.span.id";
    SPAN_COMPOSITE_COUNT: "span.composite.count";
    SPAN_COMPOSITE_SUM: "span.composite.sum.us";
    SPAN_COMPOSITE_COMPRESSION_STRATEGY: "span.composite.compression_strategy";
    SPAN_SYNC: "span.sync";
    PARENT_ID: "parent.id";
    ERROR_ID: "error.id";
    ERROR_GROUP_ID: "error.grouping_key";
    ERROR_GROUP_NAME: "error.grouping_name";
    ERROR_CULPRIT: "error.culprit";
    ERROR_LOG_LEVEL: "error.log.level";
    ERROR_LOG_MESSAGE: "error.log.message";
    ERROR_EXC_MESSAGE: "error.exception.message";
    ERROR_EXC_HANDLED: "error.exception.handled";
    ERROR_EXC_TYPE: "error.exception.type";
    ERROR_PAGE_URL: "error.page.url";
    ERROR_STACK_TRACE: "error.stack_trace";
    ERROR_TYPE: "error.type";
    ERROR_CODE: "error.code";
    ANOMALY_DETECTOR_TYPE: "anomaly.detector_type";
    METRIC_SYSTEM_FREE_MEMORY: "system.memory.actual.free";
    METRIC_SYSTEM_TOTAL_MEMORY: "system.memory.total";
    METRIC_SYSTEM_CPU_PERCENT: "system.cpu.total.norm.pct";
    METRIC_PROCESS_CPU_PERCENT: "system.process.cpu.total.norm.pct";
    METRIC_CGROUP_MEMORY_LIMIT_BYTES: "system.process.cgroup.memory.mem.limit.bytes";
    METRIC_CGROUP_MEMORY_USAGE_BYTES: "system.process.cgroup.memory.mem.usage.bytes";
    METRIC_JAVA_HEAP_MEMORY_MAX: "jvm.memory.heap.max";
    METRIC_JAVA_HEAP_MEMORY_COMMITTED: "jvm.memory.heap.committed";
    METRIC_JAVA_HEAP_MEMORY_USED: "jvm.memory.heap.used";
    METRIC_JAVA_NON_HEAP_MEMORY_MAX: "jvm.memory.non_heap.max";
    METRIC_JAVA_NON_HEAP_MEMORY_COMMITTED: "jvm.memory.non_heap.committed";
    METRIC_JAVA_NON_HEAP_MEMORY_USED: "jvm.memory.non_heap.used";
    METRIC_JAVA_THREAD_COUNT: "jvm.thread.count";
    METRIC_JAVA_GC_COUNT: "jvm.gc.count";
    METRIC_JAVA_GC_TIME: "jvm.gc.time";
    METRICSET_NAME: "metricset.name";
    METRICSET_INTERVAL: "metricset.interval";
    LABEL_NAME: "labels.name";
    LABEL_GC: "labels.gc";
    LABEL_TYPE: "labels.type";
    LABEL_TELEMETRY_AUTO_VERSION: "labels.telemetry_auto_version";
    LABEL_LIFECYCLE_STATE: "labels.lifecycle_state";
    HOST_HOSTNAME: "host.hostname";
    HOST_NAME: "host.name";
    HOST_OS_PLATFORM: "host.os.platform";
    HOST_ARCHITECTURE: "host.architecture";
    HOST_OS_VERSION: "host.os.version";
    CONTAINER_ID: "container.id";
    CONTAINER_IMAGE: "container.image.name";
    KUBERNETES_POD_NAME: "kubernetes.pod.name";
    KUBERNETES_POD_NAME_OTEL: "k8s.pod.name";
    KUBERNETES_POD_UID: "kubernetes.pod.uid";
    KUBERNETES_NAMESPACE: "kubernetes.namespace";
    KUBERNETES_NODE_NAME: "kubernetes.node.name";
    KUBERNETES_CONTAINER_NAME: "kubernetes.container.name";
    KUBERNETES_CONTAINER_ID: "kubernetes.container.id";
    KUBERNETES_DEPLOYMENT_NAME: "kubernetes.deployment.name";
    KUBERNETES_REPLICASET_NAME: "kubernetes.replicaset.name";
    FAAS_ID: "faas.id";
    FAAS_NAME: "faas.name";
    FAAS_COLDSTART: "faas.coldstart";
    FAAS_TRIGGER_TYPE: "faas.trigger.type";
    FAAS_DURATION: "faas.duration";
    FAAS_COLDSTART_DURATION: "faas.coldstart_duration";
    FAAS_BILLED_DURATION: "faas.billed_duration";
    METRIC_OTEL_SYSTEM_CPU_UTILIZATION: "system.cpu.utilization";
    METRIC_OTEL_SYSTEM_MEMORY_UTILIZATION: "system.memory.utilization";
    METRIC_OTEL_JVM_PROCESS_CPU_PERCENT: "process.runtime.jvm.cpu.utilization";
    METRIC_OTEL_JVM_PROCESS_MEMORY_USAGE: "process.runtime.jvm.memory.usage";
    METRIC_OTEL_JVM_PROCESS_MEMORY_COMMITTED: "process.runtime.jvm.memory.committed";
    METRIC_OTEL_JVM_PROCESS_MEMORY_LIMIT: "process.runtime.jvm.memory.limit";
    METRIC_OTEL_JVM_PROCESS_THREADS_COUNT: "process.runtime.jvm.threads.count";
    METRIC_OTEL_JVM_SYSTEM_CPU_PERCENT: "process.runtime.jvm.system.cpu.utilization";
    METRIC_OTEL_JVM_GC_DURATION: "process.runtime.jvm.gc.duration";
    METRIC_OTEL_JVM_CPU_PERCENT: "metrics.jvm.cpu.recent_utilization";
    METRIC_OTEL_JVM_MEMORY_USED: "metrics.jvm.memory.used";
    METRIC_OTEL_JVM_MEMORY_COMMITTED: "metrics.jvm.memory.committed";
    METRIC_OTEL_JVM_MEMORY_LIMIT: "metrics.jvm.memory.limit";
    METRIC_OTEL_JVM_THREAD_COUNT: "metrics.jvm.thread.count";
    METRIC_OTEL_JVM_SYSTEM_CPU: "metrics.jvm.system.cpu.utilization";
    METRIC_OTEL_JVM_GC_DURATION_SECONDS: "metrics.jvm.gc.duration";
    ATTRIBUTE_OTEL_JVM_MEMORY_TYPE: "attributes.jvm.memory.type";
    LABEL_OTEL_JVM_MEMORY_TYPE: "labels.jvm_memory_type";
    TELEMETRY_SDK_NAME: "telemetry.sdk.name";
    TELEMETRY_SDK_LANGUAGE: "telemetry.sdk.language";
    TELEMETRY_SDK_VERSION: "telemetry.sdk.version";
    URL_PATH: "url.path";
    URL_SCHEME: "url.scheme";
    SERVER_ADDRESS: "server.address";
    SERVER_PORT: "server.port";
    OTEL_SPAN_LINKS: "links";
    OTEL_SPAN_LINKS_SPAN_ID: "links.span_id";
    OTEL_SPAN_LINKS_TRACE_ID: "links.trace_id";
    NETWORK_CONNECTION_TYPE: "network.connection.type";
    DEVICE_MODEL_IDENTIFIER: "device.model.identifier";
    SESSION_ID: "session.id";
    APP_LAUNCH_TIME: "application.launch.time";
    EVENT_NAME: "event.name";
    CLIENT_GEO_COUNTRY_ISO_CODE: "client.geo.country_iso_code";
    CLIENT_GEO_REGION_ISO_CODE: "client.geo.region_iso_code";
    CLIENT_GEO_COUNTRY_NAME: "client.geo.country_name";
    CLIENT_GEO_CITY_NAME: "client.geo.city_name";
    CLIENT_GEO_REGION_NAME: "client.geo.region_name";
    CHILD_ID: "child.id";
    LOG_LEVEL: "log.level";
    PROCESS_ARGS: "process.args";
    PROCESS_PID: "process.pid";
    STATUS_CODE: "status.code";
    OTEL_EVENT_NAME: "event_name";
    EXCEPTION_TYPE: "exception.type";
    EXCEPTION_MESSAGE: "exception.message";
    DURATION: "duration";
    KIND: "kind";
    RESOURCE_ATTRIBUTES_TELEMETRY_SDK_LANGUAGE: "resource.attributes.telemetry.sdk.language";
    LINKS_TRACE_ID: "links.trace_id";
    LINKS_SPAN_ID: "links.span_id";
    ATTRIBUTE_HTTP_SCHEME: "attributes.http.scheme";
    ATTRIBUTE_HTTP_STATUS_CODE: "attributes.http.status_code";
    PROCESS_RUNTIME_VERSION: "process.runtime.version";
    ERROR_MESSAGE: "error.message";
};
export declare const ALL_FIELDS: Set<"@timestamp" | "_id" | "duration" | "http.request.method" | "span.subtype" | "span.type" | "url.path" | "links" | "event.outcome" | "error.message" | "faas.trigger.type" | "host.name" | "user.id" | "host.hostname" | "http.response.status_code" | "process.pid" | "process.args" | "cloud.account.id" | "cloud.availability_zone" | "cloud.provider" | "cloud.region" | "container.id" | "container.image.name" | "destination.address" | "device.model.identifier" | "error.type" | "event_name" | "exception.message" | "exception.type" | "faas.coldstart" | "faas.name" | "k8s.pod.name" | "kind" | "links.span_id" | "links.trace_id" | "metrics.jvm.cpu.recent_utilization" | "metrics.jvm.gc.duration" | "metrics.jvm.memory.committed" | "metrics.jvm.memory.limit" | "metrics.jvm.memory.used" | "metrics.jvm.system.cpu.utilization" | "metrics.jvm.thread.count" | "network.connection.type" | "process.runtime.version" | "server.address" | "server.port" | "service.name" | "service.version" | "session.id" | "status.code" | "telemetry.sdk.language" | "telemetry.sdk.name" | "telemetry.sdk.version" | "url.full" | "url.scheme" | "user_agent.name" | "user_agent.original" | "user_agent.version" | "agent.name" | "agent.version" | "service.node.name" | "service.environment" | "host.architecture" | "cloud.service.name" | "log.level" | "error.log.level" | "trace.id" | "parent.id" | "transaction.id" | "transaction.type" | "transaction.name" | "transaction.duration.us" | "span.name" | "span.id" | "span.action" | "span.duration.us" | "span.destination.service.resource" | "processor.event" | "resource.attributes.telemetry.sdk.language" | "span.links.trace.id" | "span.links.span.id" | "cloud.instance.id" | "error.culprit" | "error.grouping_name" | "error.exception.message" | "error.exception.type" | "error.stack_trace" | "timestamp.us" | "agent.activation_method" | "cloud.machine.type" | "cloud.account.name" | "cloud.instance.name" | "cloud.project.name" | "event.success_count" | "service.framework.name" | "service.framework.version" | "service.language.name" | "service.language.version" | "service.runtime.name" | "service.runtime.version" | "service.target.type" | "service_transaction.aggregation.overflow_count" | "observer.version" | "observer.version_major" | "observer.hostname" | "observer.listening" | "processor.name" | "transaction.marks.agent" | "transaction.duration.histogram" | "transaction.duration.summary" | "transaction.result" | "transaction.sampled" | "transaction.page.url" | "transaction.failure_count" | "transaction.success_count" | "transaction.aggregation.overflow_count" | "transaction.root" | "transaction.profiler_stack_trace_ids" | "elastic.profiler_stack_trace_ids" | "span.self_time.sum.us" | "span.destination.service.response_time.count" | "span.destination.service.response_time.sum.us" | "span.composite.count" | "span.composite.sum.us" | "span.composite.compression_strategy" | "span.sync" | "error.id" | "error.grouping_key" | "error.log.message" | "error.exception.handled" | "error.page.url" | "error.code" | "anomaly.detector_type" | "system.memory.actual.free" | "system.memory.total" | "system.cpu.total.norm.pct" | "system.process.cpu.total.norm.pct" | "system.process.cgroup.memory.mem.limit.bytes" | "system.process.cgroup.memory.mem.usage.bytes" | "jvm.memory.heap.max" | "jvm.memory.heap.committed" | "jvm.memory.heap.used" | "jvm.memory.non_heap.max" | "jvm.memory.non_heap.committed" | "jvm.memory.non_heap.used" | "jvm.thread.count" | "jvm.gc.count" | "jvm.gc.time" | "metricset.name" | "metricset.interval" | "labels.name" | "labels.gc" | "labels.type" | "labels.telemetry_auto_version" | "labels.lifecycle_state" | "host.os.platform" | "host.os.version" | "kubernetes.pod.name" | "kubernetes.pod.uid" | "kubernetes.namespace" | "kubernetes.node.name" | "kubernetes.container.name" | "kubernetes.container.id" | "kubernetes.deployment.name" | "kubernetes.replicaset.name" | "faas.id" | "faas.duration" | "faas.coldstart_duration" | "faas.billed_duration" | "system.cpu.utilization" | "system.memory.utilization" | "process.runtime.jvm.cpu.utilization" | "process.runtime.jvm.memory.usage" | "process.runtime.jvm.memory.committed" | "process.runtime.jvm.memory.limit" | "process.runtime.jvm.threads.count" | "process.runtime.jvm.system.cpu.utilization" | "process.runtime.jvm.gc.duration" | "attributes.jvm.memory.type" | "labels.jvm_memory_type" | "application.launch.time" | "event.name" | "client.geo.country_iso_code" | "client.geo.region_iso_code" | "client.geo.country_name" | "client.geo.city_name" | "client.geo.region_name" | "child.id" | "attributes.http.scheme" | "attributes.http.status_code">;
export declare const KNOWN_MULTI_VALUED_FIELDS: readonly ["child.id", "process.args", "links.trace_id", "links.span_id", "span.links.trace.id", "span.links.span.id"];
export type KnownField = ValuesType<typeof CONCRETE_FIELDS>;
type KnownSingleValuedField = Exclude<KnownField, KnownMultiValuedField>;
type KnownMultiValuedField = ValuesType<typeof KNOWN_MULTI_VALUED_FIELDS>;
export declare const KNOWN_SINGLE_VALUED_FIELDS_SET: Set<"@timestamp" | "_id" | "duration" | "http.request.method" | "span.subtype" | "span.type" | "url.path" | "links" | "event.outcome" | "error.message" | "faas.trigger.type" | "host.name" | "user.id" | "host.hostname" | "http.response.status_code" | "process.pid" | "process.args" | "cloud.account.id" | "cloud.availability_zone" | "cloud.provider" | "cloud.region" | "container.id" | "container.image.name" | "destination.address" | "device.model.identifier" | "error.type" | "event_name" | "exception.message" | "exception.type" | "faas.coldstart" | "faas.name" | "k8s.pod.name" | "kind" | "links.span_id" | "links.trace_id" | "metrics.jvm.cpu.recent_utilization" | "metrics.jvm.gc.duration" | "metrics.jvm.memory.committed" | "metrics.jvm.memory.limit" | "metrics.jvm.memory.used" | "metrics.jvm.system.cpu.utilization" | "metrics.jvm.thread.count" | "network.connection.type" | "process.runtime.version" | "server.address" | "server.port" | "service.name" | "service.version" | "session.id" | "status.code" | "telemetry.sdk.language" | "telemetry.sdk.name" | "telemetry.sdk.version" | "url.full" | "url.scheme" | "user_agent.name" | "user_agent.original" | "user_agent.version" | "agent.name" | "agent.version" | "service.node.name" | "service.environment" | "host.architecture" | "cloud.service.name" | "log.level" | "error.log.level" | "trace.id" | "parent.id" | "transaction.id" | "transaction.type" | "transaction.name" | "transaction.duration.us" | "span.name" | "span.id" | "span.action" | "span.duration.us" | "span.destination.service.resource" | "processor.event" | "resource.attributes.telemetry.sdk.language" | "span.links.trace.id" | "span.links.span.id" | "cloud.instance.id" | "error.culprit" | "error.grouping_name" | "error.exception.message" | "error.exception.type" | "error.stack_trace" | "timestamp.us" | "agent.activation_method" | "cloud.machine.type" | "cloud.account.name" | "cloud.instance.name" | "cloud.project.name" | "event.success_count" | "service.framework.name" | "service.framework.version" | "service.language.name" | "service.language.version" | "service.runtime.name" | "service.runtime.version" | "service.target.type" | "service_transaction.aggregation.overflow_count" | "observer.version" | "observer.version_major" | "observer.hostname" | "observer.listening" | "processor.name" | "transaction.marks.agent" | "transaction.duration.histogram" | "transaction.duration.summary" | "transaction.result" | "transaction.sampled" | "transaction.page.url" | "transaction.failure_count" | "transaction.success_count" | "transaction.aggregation.overflow_count" | "transaction.root" | "transaction.profiler_stack_trace_ids" | "elastic.profiler_stack_trace_ids" | "span.self_time.sum.us" | "span.destination.service.response_time.count" | "span.destination.service.response_time.sum.us" | "span.composite.count" | "span.composite.sum.us" | "span.composite.compression_strategy" | "span.sync" | "error.id" | "error.grouping_key" | "error.log.message" | "error.exception.handled" | "error.page.url" | "error.code" | "anomaly.detector_type" | "system.memory.actual.free" | "system.memory.total" | "system.cpu.total.norm.pct" | "system.process.cpu.total.norm.pct" | "system.process.cgroup.memory.mem.limit.bytes" | "system.process.cgroup.memory.mem.usage.bytes" | "jvm.memory.heap.max" | "jvm.memory.heap.committed" | "jvm.memory.heap.used" | "jvm.memory.non_heap.max" | "jvm.memory.non_heap.committed" | "jvm.memory.non_heap.used" | "jvm.thread.count" | "jvm.gc.count" | "jvm.gc.time" | "metricset.name" | "metricset.interval" | "labels.name" | "labels.gc" | "labels.type" | "labels.telemetry_auto_version" | "labels.lifecycle_state" | "host.os.platform" | "host.os.version" | "kubernetes.pod.name" | "kubernetes.pod.uid" | "kubernetes.namespace" | "kubernetes.node.name" | "kubernetes.container.name" | "kubernetes.container.id" | "kubernetes.deployment.name" | "kubernetes.replicaset.name" | "faas.id" | "faas.duration" | "faas.coldstart_duration" | "faas.billed_duration" | "system.cpu.utilization" | "system.memory.utilization" | "process.runtime.jvm.cpu.utilization" | "process.runtime.jvm.memory.usage" | "process.runtime.jvm.memory.committed" | "process.runtime.jvm.memory.limit" | "process.runtime.jvm.threads.count" | "process.runtime.jvm.system.cpu.utilization" | "process.runtime.jvm.gc.duration" | "attributes.jvm.memory.type" | "labels.jvm_memory_type" | "application.launch.time" | "event.name" | "client.geo.country_iso_code" | "client.geo.region_iso_code" | "client.geo.country_name" | "client.geo.city_name" | "client.geo.region_name" | "child.id" | "attributes.http.scheme" | "attributes.http.status_code">;
interface TypeOverrideMap {
    [APM_EVENT_FIELDS_MAP.SPAN_DURATION]: number;
    [APM_EVENT_FIELDS_MAP.AGENT_NAME]: AgentName;
    [APM_EVENT_FIELDS_MAP.EVENT_OUTCOME]: EventOutcome;
    [APM_EVENT_FIELDS_MAP.STATUS_CODE]: StatusCode;
    [APM_EVENT_FIELDS_MAP.FAAS_COLDSTART]: true;
    [APM_EVENT_FIELDS_MAP.TRANSACTION_DURATION]: number;
    [APM_EVENT_FIELDS_MAP.TIMESTAMP_US]: number;
    [APM_EVENT_FIELDS_MAP.PROCESSOR_EVENT]: ProcessorEvent;
    [APM_EVENT_FIELDS_MAP.SPAN_COMPOSITE_COUNT]: number;
    [APM_EVENT_FIELDS_MAP.SPAN_COMPOSITE_SUM]: number;
    [APM_EVENT_FIELDS_MAP.SPAN_SYNC]: boolean;
    [APM_EVENT_FIELDS_MAP.TRANSACTION_SAMPLED]: boolean;
    [APM_EVENT_FIELDS_MAP.PROCESSOR_NAME]: 'transaction' | 'metric' | 'error';
    [APM_EVENT_FIELDS_MAP.HTTP_RESPONSE_STATUS_CODE]: number;
    [APM_EVENT_FIELDS_MAP.PROCESS_PID]: number;
    [APM_EVENT_FIELDS_MAP.OBSERVER_VERSION_MAJOR]: number;
    [APM_EVENT_FIELDS_MAP.ERROR_EXC_HANDLED]: boolean;
}
type MaybeMultiValue<T extends KnownField, U> = T extends KnownMultiValuedField ? U[] : U;
type TypeOfKnownField<T extends KnownField> = MaybeMultiValue<T, T extends keyof TypeOverrideMap ? TypeOverrideMap[T] : string>;
export type MapToSingleOrMultiValue<T extends Record<string, any>> = {
    [TKey in keyof T]: TKey extends KnownField ? T[TKey] extends undefined ? TypeOfKnownField<TKey> | undefined : TypeOfKnownField<TKey> : unknown;
};
export type UnflattenedKnownFields<T extends Record<string, any>> = DedotObject<MapToSingleOrMultiValue<T>>;
export type FlattenedApmEvent = Record<KnownSingleValuedField | KnownMultiValuedField, unknown[]>;
export type UnflattenedApmEvent = UnflattenedKnownFields<FlattenedApmEvent>;
/**
 * Validates whether the field record object contains all required fields. Throws an error
 * if it does not.
 */
export declare function ensureRequiredApmFields(fields: Record<string, any>, required: string[]): void;
export {};
