export declare const ACTION_CONVERT_TO_LENS = "ACTION_CONVERT_TO_LENS";
export declare const ACTION_CONVERT_AGG_BASED_TO_LENS = "ACTION_CONVERT_AGG_BASED_TO_LENS";
export declare const ACTION_CONVERT_DASHBOARD_PANEL_TO_LENS = "ACTION_CONVERT_DASHBOARD_PANEL_TO_LENS";
