import type { SetStateAction, ReactNode, FormEventHandler } from 'react';
import React from 'react';
import type { EuiSelectableOption } from '@elastic/eui';
export type UrlOption<T = {
    [key: string]: any;
}> = {
    meta?: string[];
    isNewWildcard?: boolean;
    isWildcard?: boolean;
    title: string;
} & EuiSelectableOption<T>;
export interface SelectableUrlListProps {
    data: {
        items: UrlOption[];
        total?: number;
    };
    loading: boolean;
    rowHeight?: number;
    onInputChange: (val: string) => void;
    onSelectionApply: () => void;
    onSelectionChange: (updatedOptions: UrlOption[]) => void;
    searchValue: string;
    popoverIsOpen: boolean;
    initialValue?: string;
    setPopoverIsOpen: React.Dispatch<SetStateAction<boolean>>;
    renderOption?: (option: UrlOption, searchValue: string) => ReactNode;
    hasChanged: () => boolean;
}
export declare const formatOptions: (options: EuiSelectableOption[]) => ({
    className: string;
    "aria-label"?: string;
    'data-test-subj'?: string;
    css?: import("@emotion/serialize").Interpolation<import("@emotion/react").Theme>;
    label: string;
    searchableLabel?: string;
    key?: string;
    checked?: import("@elastic/eui/src/components/selectable/selectable_option").EuiSelectableOptionCheckedType;
    disabled?: boolean;
    isGroupLabel?: false;
    prepend?: React.ReactNode;
    append?: React.ReactNode;
    ref?: (optionIndex: number) => void;
    id?: never;
    data?: {
        [key: string]: any;
    };
    textWrap?: "truncate" | "wrap";
    truncationProps?: Partial<Omit<import("@elastic/eui").EuiTextTruncateProps, "text" | "children">>;
    toolTipContent?: import("@elastic/eui").EuiToolTipProps["content"];
    toolTipProps?: Partial<Omit<import("@elastic/eui").EuiToolTipProps, "content" | "children">>;
    defaultChecked?: boolean | undefined;
    defaultValue?: string | number | readonly string[] | undefined;
    suppressContentEditableWarning?: boolean | undefined;
    suppressHydrationWarning?: boolean | undefined;
    accessKey?: string | undefined;
    autoFocus?: boolean | undefined;
    contentEditable?: (boolean | "true" | "false") | "inherit" | "plaintext-only" | undefined;
    contextMenu?: string | undefined;
    dir?: string | undefined;
    draggable?: (boolean | "true" | "false") | undefined;
    hidden?: boolean | undefined;
    lang?: string | undefined;
    nonce?: string | undefined;
    slot?: string | undefined;
    spellCheck?: (boolean | "true" | "false") | undefined;
    style?: React.CSSProperties | undefined;
    tabIndex?: number | undefined;
    title: string;
    translate?: "yes" | "no" | undefined;
    radioGroup?: string | undefined;
    role?: React.AriaRole | undefined;
    about?: string | undefined;
    content?: string | undefined;
    datatype?: string | undefined;
    inlist?: any;
    prefix?: string | undefined;
    property?: string | undefined;
    rel?: string | undefined;
    resource?: string | undefined;
    rev?: string | undefined;
    typeof?: string | undefined;
    vocab?: string | undefined;
    autoCapitalize?: string | undefined;
    autoCorrect?: string | undefined;
    autoSave?: string | undefined;
    color?: string | undefined;
    itemProp?: string | undefined;
    itemScope?: boolean | undefined;
    itemType?: string | undefined;
    itemID?: string | undefined;
    itemRef?: string | undefined;
    results?: number | undefined;
    security?: string | undefined;
    unselectable?: "on" | "off" | undefined;
    inputMode?: "none" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | "search" | undefined;
    is?: string | undefined;
    "aria-activedescendant"?: string | undefined;
    "aria-atomic"?: (boolean | "true" | "false") | undefined;
    "aria-autocomplete"?: "none" | "inline" | "list" | "both" | undefined;
    "aria-braillelabel"?: string | undefined;
    "aria-brailleroledescription"?: string | undefined;
    "aria-busy"?: (boolean | "true" | "false") | undefined;
    "aria-checked"?: boolean | "false" | "mixed" | "true" | undefined;
    "aria-colcount"?: number | undefined;
    "aria-colindex"?: number | undefined;
    "aria-colindextext"?: string | undefined;
    "aria-colspan"?: number | undefined;
    "aria-controls"?: string | undefined;
    "aria-current"?: boolean | "false" | "true" | "page" | "step" | "location" | "date" | "time" | undefined;
    "aria-describedby"?: string | undefined;
    "aria-description"?: string | undefined;
    "aria-details"?: string | undefined;
    "aria-disabled"?: (boolean | "true" | "false") | undefined;
    "aria-dropeffect"?: "none" | "copy" | "execute" | "link" | "move" | "popup" | undefined;
    "aria-errormessage"?: string | undefined;
    "aria-expanded"?: (boolean | "true" | "false") | undefined;
    "aria-flowto"?: string | undefined;
    "aria-grabbed"?: (boolean | "true" | "false") | undefined;
    "aria-haspopup"?: boolean | "false" | "true" | "menu" | "listbox" | "tree" | "grid" | "dialog" | undefined;
    "aria-hidden"?: (boolean | "true" | "false") | undefined;
    "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined;
    "aria-keyshortcuts"?: string | undefined;
    "aria-labelledby"?: string | undefined;
    "aria-level"?: number | undefined;
    "aria-live"?: "off" | "assertive" | "polite" | undefined;
    "aria-modal"?: (boolean | "true" | "false") | undefined;
    "aria-multiline"?: (boolean | "true" | "false") | undefined;
    "aria-multiselectable"?: (boolean | "true" | "false") | undefined;
    "aria-orientation"?: "horizontal" | "vertical" | undefined;
    "aria-owns"?: string | undefined;
    "aria-placeholder"?: string | undefined;
    "aria-posinset"?: number | undefined;
    "aria-pressed"?: boolean | "false" | "mixed" | "true" | undefined;
    "aria-readonly"?: (boolean | "true" | "false") | undefined;
    "aria-relevant"?: "additions" | "additions removals" | "additions text" | "all" | "removals" | "removals additions" | "removals text" | "text" | "text additions" | "text removals" | undefined;
    "aria-required"?: (boolean | "true" | "false") | undefined;
    "aria-roledescription"?: string | undefined;
    "aria-rowcount"?: number | undefined;
    "aria-rowindex"?: number | undefined;
    "aria-rowindextext"?: string | undefined;
    "aria-rowspan"?: number | undefined;
    "aria-selected"?: (boolean | "true" | "false") | undefined;
    "aria-setsize"?: number | undefined;
    "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined;
    "aria-valuemax"?: number | undefined;
    "aria-valuemin"?: number | undefined;
    "aria-valuenow"?: number | undefined;
    "aria-valuetext"?: string | undefined;
    children?: ReactNode | undefined;
    dangerouslySetInnerHTML?: {
        __html: string | TrustedHTML;
    } | undefined;
    onCopy?: React.ClipboardEventHandler<HTMLLIElement> | undefined;
    onCopyCapture?: React.ClipboardEventHandler<HTMLLIElement> | undefined;
    onCut?: React.ClipboardEventHandler<HTMLLIElement> | undefined;
    onCutCapture?: React.ClipboardEventHandler<HTMLLIElement> | undefined;
    onPaste?: React.ClipboardEventHandler<HTMLLIElement> | undefined;
    onPasteCapture?: React.ClipboardEventHandler<HTMLLIElement> | undefined;
    onCompositionEnd?: React.CompositionEventHandler<HTMLLIElement> | undefined;
    onCompositionEndCapture?: React.CompositionEventHandler<HTMLLIElement> | undefined;
    onCompositionStart?: React.CompositionEventHandler<HTMLLIElement> | undefined;
    onCompositionStartCapture?: React.CompositionEventHandler<HTMLLIElement> | undefined;
    onCompositionUpdate?: React.CompositionEventHandler<HTMLLIElement> | undefined;
    onCompositionUpdateCapture?: React.CompositionEventHandler<HTMLLIElement> | undefined;
    onFocus?: React.FocusEventHandler<HTMLLIElement> | undefined;
    onFocusCapture?: React.FocusEventHandler<HTMLLIElement> | undefined;
    onBlur?: React.FocusEventHandler<HTMLLIElement> | undefined;
    onBlurCapture?: React.FocusEventHandler<HTMLLIElement> | undefined;
    onChange?: FormEventHandler<HTMLLIElement> | undefined;
    onChangeCapture?: FormEventHandler<HTMLLIElement> | undefined;
    onBeforeInput?: FormEventHandler<HTMLLIElement> | undefined;
    onBeforeInputCapture?: FormEventHandler<HTMLLIElement> | undefined;
    onInput?: FormEventHandler<HTMLLIElement> | undefined;
    onInputCapture?: FormEventHandler<HTMLLIElement> | undefined;
    onReset?: FormEventHandler<HTMLLIElement> | undefined;
    onResetCapture?: FormEventHandler<HTMLLIElement> | undefined;
    onSubmit?: FormEventHandler<HTMLLIElement> | undefined;
    onSubmitCapture?: FormEventHandler<HTMLLIElement> | undefined;
    onInvalid?: FormEventHandler<HTMLLIElement> | undefined;
    onInvalidCapture?: FormEventHandler<HTMLLIElement> | undefined;
    onLoad?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onLoadCapture?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onError?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onErrorCapture?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onKeyDown?: React.KeyboardEventHandler<HTMLLIElement> | undefined;
    onKeyDownCapture?: React.KeyboardEventHandler<HTMLLIElement> | undefined;
    onKeyPress?: React.KeyboardEventHandler<HTMLLIElement> | undefined;
    onKeyPressCapture?: React.KeyboardEventHandler<HTMLLIElement> | undefined;
    onKeyUp?: React.KeyboardEventHandler<HTMLLIElement> | undefined;
    onKeyUpCapture?: React.KeyboardEventHandler<HTMLLIElement> | undefined;
    onAbort?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onAbortCapture?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onCanPlay?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onCanPlayCapture?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onCanPlayThrough?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onCanPlayThroughCapture?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onDurationChange?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onDurationChangeCapture?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onEmptied?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onEmptiedCapture?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onEncrypted?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onEncryptedCapture?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onEnded?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onEndedCapture?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onLoadedData?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onLoadedDataCapture?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onLoadedMetadata?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onLoadedMetadataCapture?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onLoadStart?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onLoadStartCapture?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onPause?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onPauseCapture?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onPlay?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onPlayCapture?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onPlaying?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onPlayingCapture?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onProgress?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onProgressCapture?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onRateChange?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onRateChangeCapture?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onResize?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onResizeCapture?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onSeeked?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onSeekedCapture?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onSeeking?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onSeekingCapture?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onStalled?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onStalledCapture?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onSuspend?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onSuspendCapture?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onTimeUpdate?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onTimeUpdateCapture?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onVolumeChange?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onVolumeChangeCapture?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onWaiting?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onWaitingCapture?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onAuxClick?: React.MouseEventHandler<HTMLLIElement> | undefined;
    onAuxClickCapture?: React.MouseEventHandler<HTMLLIElement> | undefined;
    onClick?: React.MouseEventHandler<HTMLLIElement> | undefined;
    onClickCapture?: React.MouseEventHandler<HTMLLIElement> | undefined;
    onContextMenu?: React.MouseEventHandler<HTMLLIElement> | undefined;
    onContextMenuCapture?: React.MouseEventHandler<HTMLLIElement> | undefined;
    onDoubleClick?: React.MouseEventHandler<HTMLLIElement> | undefined;
    onDoubleClickCapture?: React.MouseEventHandler<HTMLLIElement> | undefined;
    onDrag?: React.DragEventHandler<HTMLLIElement> | undefined;
    onDragCapture?: React.DragEventHandler<HTMLLIElement> | undefined;
    onDragEnd?: React.DragEventHandler<HTMLLIElement> | undefined;
    onDragEndCapture?: React.DragEventHandler<HTMLLIElement> | undefined;
    onDragEnter?: React.DragEventHandler<HTMLLIElement> | undefined;
    onDragEnterCapture?: React.DragEventHandler<HTMLLIElement> | undefined;
    onDragExit?: React.DragEventHandler<HTMLLIElement> | undefined;
    onDragExitCapture?: React.DragEventHandler<HTMLLIElement> | undefined;
    onDragLeave?: React.DragEventHandler<HTMLLIElement> | undefined;
    onDragLeaveCapture?: React.DragEventHandler<HTMLLIElement> | undefined;
    onDragOver?: React.DragEventHandler<HTMLLIElement> | undefined;
    onDragOverCapture?: React.DragEventHandler<HTMLLIElement> | undefined;
    onDragStart?: React.DragEventHandler<HTMLLIElement> | undefined;
    onDragStartCapture?: React.DragEventHandler<HTMLLIElement> | undefined;
    onDrop?: React.DragEventHandler<HTMLLIElement> | undefined;
    onDropCapture?: React.DragEventHandler<HTMLLIElement> | undefined;
    onMouseDown?: React.MouseEventHandler<HTMLLIElement> | undefined;
    onMouseDownCapture?: React.MouseEventHandler<HTMLLIElement> | undefined;
    onMouseEnter?: React.MouseEventHandler<HTMLLIElement> | undefined;
    onMouseLeave?: React.MouseEventHandler<HTMLLIElement> | undefined;
    onMouseMove?: React.MouseEventHandler<HTMLLIElement> | undefined;
    onMouseMoveCapture?: React.MouseEventHandler<HTMLLIElement> | undefined;
    onMouseOut?: React.MouseEventHandler<HTMLLIElement> | undefined;
    onMouseOutCapture?: React.MouseEventHandler<HTMLLIElement> | undefined;
    onMouseOver?: React.MouseEventHandler<HTMLLIElement> | undefined;
    onMouseOverCapture?: React.MouseEventHandler<HTMLLIElement> | undefined;
    onMouseUp?: React.MouseEventHandler<HTMLLIElement> | undefined;
    onMouseUpCapture?: React.MouseEventHandler<HTMLLIElement> | undefined;
    onSelect?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onSelectCapture?: React.ReactEventHandler<HTMLLIElement> | undefined;
    onTouchCancel?: React.TouchEventHandler<HTMLLIElement> | undefined;
    onTouchCancelCapture?: React.TouchEventHandler<HTMLLIElement> | undefined;
    onTouchEnd?: React.TouchEventHandler<HTMLLIElement> | undefined;
    onTouchEndCapture?: React.TouchEventHandler<HTMLLIElement> | undefined;
    onTouchMove?: React.TouchEventHandler<HTMLLIElement> | undefined;
    onTouchMoveCapture?: React.TouchEventHandler<HTMLLIElement> | undefined;
    onTouchStart?: React.TouchEventHandler<HTMLLIElement> | undefined;
    onTouchStartCapture?: React.TouchEventHandler<HTMLLIElement> | undefined;
    onPointerDown?: React.PointerEventHandler<HTMLLIElement> | undefined;
    onPointerDownCapture?: React.PointerEventHandler<HTMLLIElement> | undefined;
    onPointerMove?: React.PointerEventHandler<HTMLLIElement> | undefined;
    onPointerMoveCapture?: React.PointerEventHandler<HTMLLIElement> | undefined;
    onPointerUp?: React.PointerEventHandler<HTMLLIElement> | undefined;
    onPointerUpCapture?: React.PointerEventHandler<HTMLLIElement> | undefined;
    onPointerCancel?: React.PointerEventHandler<HTMLLIElement> | undefined;
    onPointerCancelCapture?: React.PointerEventHandler<HTMLLIElement> | undefined;
    onPointerEnter?: React.PointerEventHandler<HTMLLIElement> | undefined;
    onPointerLeave?: React.PointerEventHandler<HTMLLIElement> | undefined;
    onPointerOver?: React.PointerEventHandler<HTMLLIElement> | undefined;
    onPointerOverCapture?: React.PointerEventHandler<HTMLLIElement> | undefined;
    onPointerOut?: React.PointerEventHandler<HTMLLIElement> | undefined;
    onPointerOutCapture?: React.PointerEventHandler<HTMLLIElement> | undefined;
    onGotPointerCapture?: React.PointerEventHandler<HTMLLIElement> | undefined;
    onGotPointerCaptureCapture?: React.PointerEventHandler<HTMLLIElement> | undefined;
    onLostPointerCapture?: React.PointerEventHandler<HTMLLIElement> | undefined;
    onLostPointerCaptureCapture?: React.PointerEventHandler<HTMLLIElement> | undefined;
    onScroll?: React.UIEventHandler<HTMLLIElement> | undefined;
    onScrollCapture?: React.UIEventHandler<HTMLLIElement> | undefined;
    onWheel?: React.WheelEventHandler<HTMLLIElement> | undefined;
    onWheelCapture?: React.WheelEventHandler<HTMLLIElement> | undefined;
    onAnimationStart?: React.AnimationEventHandler<HTMLLIElement> | undefined;
    onAnimationStartCapture?: React.AnimationEventHandler<HTMLLIElement> | undefined;
    onAnimationEnd?: React.AnimationEventHandler<HTMLLIElement> | undefined;
    onAnimationEndCapture?: React.AnimationEventHandler<HTMLLIElement> | undefined;
    onAnimationIteration?: React.AnimationEventHandler<HTMLLIElement> | undefined;
    onAnimationIterationCapture?: React.AnimationEventHandler<HTMLLIElement> | undefined;
    onTransitionEnd?: React.TransitionEventHandler<HTMLLIElement> | undefined;
    onTransitionEndCapture?: React.TransitionEventHandler<HTMLLIElement> | undefined;
} | {
    className: string;
    data?: {
        [key: string]: any;
    } | undefined;
    id?: undefined;
    key?: string | undefined;
    "aria-label"?: string | undefined;
    ref?: ((optionIndex: number) => void) | undefined;
    label: string;
    'data-test-subj'?: string | undefined;
    css?: import("@emotion/serialize").Interpolation<import("@emotion/react").Theme>;
    disabled?: boolean | undefined;
    checked?: "on" | "off" | "mixed" | undefined;
    toolTipContent?: ReactNode;
    toolTipProps?: Partial<Omit<import("@elastic/eui").EuiToolTipProps, "content" | "children">> | undefined;
    prepend?: ReactNode;
    append?: ReactNode;
    truncationProps?: Partial<Omit<import("@elastic/eui").EuiTextTruncateProps, "text" | "children">> | undefined;
    searchableLabel?: string | undefined;
    textWrap?: "truncate" | "wrap" | undefined;
    defaultChecked?: boolean | undefined;
    defaultValue?: string | number | readonly string[] | undefined;
    suppressContentEditableWarning?: boolean | undefined;
    suppressHydrationWarning?: boolean | undefined;
    accessKey?: string | undefined;
    autoFocus?: boolean | undefined;
    contentEditable?: (boolean | "true" | "false") | "inherit" | "plaintext-only" | undefined;
    contextMenu?: string | undefined;
    dir?: string | undefined;
    draggable?: (boolean | "true" | "false") | undefined;
    hidden?: boolean | undefined;
    lang?: string | undefined;
    nonce?: string | undefined;
    slot?: string | undefined;
    spellCheck?: (boolean | "true" | "false") | undefined;
    style?: React.CSSProperties | undefined;
    tabIndex?: number | undefined;
    title: string;
    translate?: "yes" | "no" | undefined;
    radioGroup?: string | undefined;
    role?: React.AriaRole | undefined;
    about?: string | undefined;
    content?: string | undefined;
    datatype?: string | undefined;
    inlist?: any;
    prefix?: string | undefined;
    property?: string | undefined;
    rel?: string | undefined;
    resource?: string | undefined;
    rev?: string | undefined;
    typeof?: string | undefined;
    vocab?: string | undefined;
    autoCapitalize?: string | undefined;
    autoCorrect?: string | undefined;
    autoSave?: string | undefined;
    color?: string | undefined;
    itemProp?: string | undefined;
    itemScope?: boolean | undefined;
    itemType?: string | undefined;
    itemID?: string | undefined;
    itemRef?: string | undefined;
    results?: number | undefined;
    security?: string | undefined;
    unselectable?: "on" | "off" | undefined;
    inputMode?: "none" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | "search" | undefined;
    is?: string | undefined;
    "aria-activedescendant"?: string | undefined;
    "aria-atomic"?: (boolean | "true" | "false") | undefined;
    "aria-autocomplete"?: "none" | "inline" | "list" | "both" | undefined;
    "aria-braillelabel"?: string | undefined;
    "aria-brailleroledescription"?: string | undefined;
    "aria-busy"?: (boolean | "true" | "false") | undefined;
    "aria-checked"?: boolean | "false" | "mixed" | "true" | undefined;
    "aria-colcount"?: number | undefined;
    "aria-colindex"?: number | undefined;
    "aria-colindextext"?: string | undefined;
    "aria-colspan"?: number | undefined;
    "aria-controls"?: string | undefined;
    "aria-current"?: boolean | "false" | "true" | "page" | "step" | "location" | "date" | "time" | undefined;
    "aria-describedby"?: string | undefined;
    "aria-description"?: string | undefined;
    "aria-details"?: string | undefined;
    "aria-disabled"?: (boolean | "true" | "false") | undefined;
    "aria-dropeffect"?: "none" | "copy" | "execute" | "link" | "move" | "popup" | undefined;
    "aria-errormessage"?: string | undefined;
    "aria-expanded"?: (boolean | "true" | "false") | undefined;
    "aria-flowto"?: string | undefined;
    "aria-grabbed"?: (boolean | "true" | "false") | undefined;
    "aria-haspopup"?: boolean | "false" | "true" | "menu" | "listbox" | "tree" | "grid" | "dialog" | undefined;
    "aria-hidden"?: (boolean | "true" | "false") | undefined;
    "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined;
    "aria-keyshortcuts"?: string | undefined;
    "aria-labelledby"?: string | undefined;
    "aria-level"?: number | undefined;
    "aria-live"?: "off" | "assertive" | "polite" | undefined;
    "aria-modal"?: (boolean | "true" | "false") | undefined;
    "aria-multiline"?: (boolean | "true" | "false") | undefined;
    "aria-multiselectable"?: (boolean | "true" | "false") | undefined;
    "aria-orientation"?: "horizontal" | "vertical" | undefined;
    "aria-owns"?: string | undefined;
    "aria-placeholder"?: string | undefined;
    "aria-posinset"?: number | undefined;
    "aria-pressed"?: boolean | "false" | "mixed" | "true" | undefined;
    "aria-readonly"?: (boolean | "true" | "false") | undefined;
    "aria-relevant"?: "additions" | "additions removals" | "additions text" | "all" | "removals" | "removals additions" | "removals text" | "text" | "text additions" | "text removals" | undefined;
    "aria-required"?: (boolean | "true" | "false") | undefined;
    "aria-roledescription"?: string | undefined;
    "aria-rowcount"?: number | undefined;
    "aria-rowindex"?: number | undefined;
    "aria-rowindextext"?: string | undefined;
    "aria-rowspan"?: number | undefined;
    "aria-selected"?: (boolean | "true" | "false") | undefined;
    "aria-setsize"?: number | undefined;
    "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined;
    "aria-valuemax"?: number | undefined;
    "aria-valuemin"?: number | undefined;
    "aria-valuenow"?: number | undefined;
    "aria-valuetext"?: string | undefined;
    children?: ReactNode | undefined;
    dangerouslySetInnerHTML?: {
        __html: string | TrustedHTML;
    } | undefined;
    onCopy?: React.ClipboardEventHandler<HTMLDivElement> | undefined;
    onCopyCapture?: React.ClipboardEventHandler<HTMLDivElement> | undefined;
    onCut?: React.ClipboardEventHandler<HTMLDivElement> | undefined;
    onCutCapture?: React.ClipboardEventHandler<HTMLDivElement> | undefined;
    onPaste?: React.ClipboardEventHandler<HTMLDivElement> | undefined;
    onPasteCapture?: React.ClipboardEventHandler<HTMLDivElement> | undefined;
    onCompositionEnd?: React.CompositionEventHandler<HTMLDivElement> | undefined;
    onCompositionEndCapture?: React.CompositionEventHandler<HTMLDivElement> | undefined;
    onCompositionStart?: React.CompositionEventHandler<HTMLDivElement> | undefined;
    onCompositionStartCapture?: React.CompositionEventHandler<HTMLDivElement> | undefined;
    onCompositionUpdate?: React.CompositionEventHandler<HTMLDivElement> | undefined;
    onCompositionUpdateCapture?: React.CompositionEventHandler<HTMLDivElement> | undefined;
    onFocus?: React.FocusEventHandler<HTMLDivElement> | undefined;
    onFocusCapture?: React.FocusEventHandler<HTMLDivElement> | undefined;
    onBlur?: React.FocusEventHandler<HTMLDivElement> | undefined;
    onBlurCapture?: React.FocusEventHandler<HTMLDivElement> | undefined;
    onChange?: FormEventHandler<HTMLDivElement> | undefined;
    onChangeCapture?: FormEventHandler<HTMLDivElement> | undefined;
    onBeforeInput?: FormEventHandler<HTMLDivElement> | undefined;
    onBeforeInputCapture?: FormEventHandler<HTMLDivElement> | undefined;
    onInput?: FormEventHandler<HTMLDivElement> | undefined;
    onInputCapture?: FormEventHandler<HTMLDivElement> | undefined;
    onReset?: FormEventHandler<HTMLDivElement> | undefined;
    onResetCapture?: FormEventHandler<HTMLDivElement> | undefined;
    onSubmit?: FormEventHandler<HTMLDivElement> | undefined;
    onSubmitCapture?: FormEventHandler<HTMLDivElement> | undefined;
    onInvalid?: FormEventHandler<HTMLDivElement> | undefined;
    onInvalidCapture?: FormEventHandler<HTMLDivElement> | undefined;
    onLoad?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onLoadCapture?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onError?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onErrorCapture?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onKeyDown?: React.KeyboardEventHandler<HTMLDivElement> | undefined;
    onKeyDownCapture?: React.KeyboardEventHandler<HTMLDivElement> | undefined;
    onKeyPress?: React.KeyboardEventHandler<HTMLDivElement> | undefined;
    onKeyPressCapture?: React.KeyboardEventHandler<HTMLDivElement> | undefined;
    onKeyUp?: React.KeyboardEventHandler<HTMLDivElement> | undefined;
    onKeyUpCapture?: React.KeyboardEventHandler<HTMLDivElement> | undefined;
    onAbort?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onAbortCapture?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onCanPlay?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onCanPlayCapture?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onCanPlayThrough?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onCanPlayThroughCapture?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onDurationChange?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onDurationChangeCapture?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onEmptied?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onEmptiedCapture?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onEncrypted?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onEncryptedCapture?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onEnded?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onEndedCapture?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onLoadedData?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onLoadedDataCapture?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onLoadedMetadata?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onLoadedMetadataCapture?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onLoadStart?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onLoadStartCapture?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onPause?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onPauseCapture?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onPlay?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onPlayCapture?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onPlaying?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onPlayingCapture?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onProgress?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onProgressCapture?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onRateChange?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onRateChangeCapture?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onResize?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onResizeCapture?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onSeeked?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onSeekedCapture?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onSeeking?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onSeekingCapture?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onStalled?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onStalledCapture?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onSuspend?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onSuspendCapture?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onTimeUpdate?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onTimeUpdateCapture?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onVolumeChange?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onVolumeChangeCapture?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onWaiting?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onWaitingCapture?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onAuxClick?: React.MouseEventHandler<HTMLDivElement> | undefined;
    onAuxClickCapture?: React.MouseEventHandler<HTMLDivElement> | undefined;
    onClick?: React.MouseEventHandler<HTMLDivElement> | undefined;
    onClickCapture?: React.MouseEventHandler<HTMLDivElement> | undefined;
    onContextMenu?: React.MouseEventHandler<HTMLDivElement> | undefined;
    onContextMenuCapture?: React.MouseEventHandler<HTMLDivElement> | undefined;
    onDoubleClick?: React.MouseEventHandler<HTMLDivElement> | undefined;
    onDoubleClickCapture?: React.MouseEventHandler<HTMLDivElement> | undefined;
    onDrag?: React.DragEventHandler<HTMLDivElement> | undefined;
    onDragCapture?: React.DragEventHandler<HTMLDivElement> | undefined;
    onDragEnd?: React.DragEventHandler<HTMLDivElement> | undefined;
    onDragEndCapture?: React.DragEventHandler<HTMLDivElement> | undefined;
    onDragEnter?: React.DragEventHandler<HTMLDivElement> | undefined;
    onDragEnterCapture?: React.DragEventHandler<HTMLDivElement> | undefined;
    onDragExit?: React.DragEventHandler<HTMLDivElement> | undefined;
    onDragExitCapture?: React.DragEventHandler<HTMLDivElement> | undefined;
    onDragLeave?: React.DragEventHandler<HTMLDivElement> | undefined;
    onDragLeaveCapture?: React.DragEventHandler<HTMLDivElement> | undefined;
    onDragOver?: React.DragEventHandler<HTMLDivElement> | undefined;
    onDragOverCapture?: React.DragEventHandler<HTMLDivElement> | undefined;
    onDragStart?: React.DragEventHandler<HTMLDivElement> | undefined;
    onDragStartCapture?: React.DragEventHandler<HTMLDivElement> | undefined;
    onDrop?: React.DragEventHandler<HTMLDivElement> | undefined;
    onDropCapture?: React.DragEventHandler<HTMLDivElement> | undefined;
    onMouseDown?: React.MouseEventHandler<HTMLDivElement> | undefined;
    onMouseDownCapture?: React.MouseEventHandler<HTMLDivElement> | undefined;
    onMouseEnter?: React.MouseEventHandler<HTMLDivElement> | undefined;
    onMouseLeave?: React.MouseEventHandler<HTMLDivElement> | undefined;
    onMouseMove?: React.MouseEventHandler<HTMLDivElement> | undefined;
    onMouseMoveCapture?: React.MouseEventHandler<HTMLDivElement> | undefined;
    onMouseOut?: React.MouseEventHandler<HTMLDivElement> | undefined;
    onMouseOutCapture?: React.MouseEventHandler<HTMLDivElement> | undefined;
    onMouseOver?: React.MouseEventHandler<HTMLDivElement> | undefined;
    onMouseOverCapture?: React.MouseEventHandler<HTMLDivElement> | undefined;
    onMouseUp?: React.MouseEventHandler<HTMLDivElement> | undefined;
    onMouseUpCapture?: React.MouseEventHandler<HTMLDivElement> | undefined;
    onSelect?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onSelectCapture?: React.ReactEventHandler<HTMLDivElement> | undefined;
    onTouchCancel?: React.TouchEventHandler<HTMLDivElement> | undefined;
    onTouchCancelCapture?: React.TouchEventHandler<HTMLDivElement> | undefined;
    onTouchEnd?: React.TouchEventHandler<HTMLDivElement> | undefined;
    onTouchEndCapture?: React.TouchEventHandler<HTMLDivElement> | undefined;
    onTouchMove?: React.TouchEventHandler<HTMLDivElement> | undefined;
    onTouchMoveCapture?: React.TouchEventHandler<HTMLDivElement> | undefined;
    onTouchStart?: React.TouchEventHandler<HTMLDivElement> | undefined;
    onTouchStartCapture?: React.TouchEventHandler<HTMLDivElement> | undefined;
    onPointerDown?: React.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerDownCapture?: React.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerMove?: React.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerMoveCapture?: React.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerUp?: React.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerUpCapture?: React.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerCancel?: React.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerCancelCapture?: React.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerEnter?: React.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerLeave?: React.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerOver?: React.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerOverCapture?: React.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerOut?: React.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerOutCapture?: React.PointerEventHandler<HTMLDivElement> | undefined;
    onGotPointerCapture?: React.PointerEventHandler<HTMLDivElement> | undefined;
    onGotPointerCaptureCapture?: React.PointerEventHandler<HTMLDivElement> | undefined;
    onLostPointerCapture?: React.PointerEventHandler<HTMLDivElement> | undefined;
    onLostPointerCaptureCapture?: React.PointerEventHandler<HTMLDivElement> | undefined;
    onScroll?: React.UIEventHandler<HTMLDivElement> | undefined;
    onScrollCapture?: React.UIEventHandler<HTMLDivElement> | undefined;
    onWheel?: React.WheelEventHandler<HTMLDivElement> | undefined;
    onWheelCapture?: React.WheelEventHandler<HTMLDivElement> | undefined;
    onAnimationStart?: React.AnimationEventHandler<HTMLDivElement> | undefined;
    onAnimationStartCapture?: React.AnimationEventHandler<HTMLDivElement> | undefined;
    onAnimationEnd?: React.AnimationEventHandler<HTMLDivElement> | undefined;
    onAnimationEndCapture?: React.AnimationEventHandler<HTMLDivElement> | undefined;
    onAnimationIteration?: React.AnimationEventHandler<HTMLDivElement> | undefined;
    onAnimationIterationCapture?: React.AnimationEventHandler<HTMLDivElement> | undefined;
    onTransitionEnd?: React.TransitionEventHandler<HTMLDivElement> | undefined;
    onTransitionEndCapture?: React.TransitionEventHandler<HTMLDivElement> | undefined;
    isGroupLabel: true;
})[];
export declare function SelectableUrlList({ data, loading, onInputChange, onSelectionChange, onSelectionApply, searchValue, popoverIsOpen, setPopoverIsOpen, initialValue, renderOption, rowHeight, hasChanged, }: SelectableUrlListProps): React.JSX.Element;
export default SelectableUrlList;
