[role="xpack"]
[[configuring-reporting]]
== Configuring Reporting

You can configure settings in `kibana.yml` to control how {reporting}
communicates with the Kibana server, manages background jobs, and captures
screenshots. See <<reporting-settings-kb, Reporting Settings>> for the complete
list of settings.

=== Encryption Keys for Multiple Kibana Instances

By default, a new encryption key is generated for {reporting} each time
you start Kibana. This means if a static encryption key is not persisted in the
Kibana configuration, any pending reports will fail when you restart Kibana.

If you are load balancing across multiple Kibana instances, they need to have
the same reporting encryption key. Otherwise, report generation will fail if a
report is queued through one instance and another instance picks up the job
from the report queue. The other instance will not be able to decrypt the
reporting job metadata.

To set a static encryption key for reporting, set the
`xpack.reporting.encryptionKey` property in the `kibana.yml`
configuration file. You can use any text string as the encryption key.

[source,yaml]
--------------------------------------------------------------------------------
xpack.reporting.encryptionKey: "something_secret"
--------------------------------------------------------------------------------

=== Reporting Indices for Multiple Kibana Workspaces

If you divide workspaces in an Elastic cluster using multiple Kibana instances
with a different `kibana.index` setting per instance, you must set a unique `xpack.reporting.index`
setting per `kibana.index`. Otherwise, report generation will periodically fail
if a report is queued through an instance with one `kibana.index` setting, and
an instance with a different `kibana.index` attempts to claim the job.

Kibana instance A:
[source,yaml]
--------------------------------------------------------------------------------
kibana.index: ".kibana-a"
xpack.reporting.index: ".reporting-a"
--------------------------------------------------------------------------------

Kibana instance B:
[source,yaml]
--------------------------------------------------------------------------------
kibana.index: ".kibana-b"
xpack.reporting.index: ".reporting-b"
--------------------------------------------------------------------------------

NOTE: If security is enabled, the `xpack.reporting.index` setting should begin
with `.reporting-` in order for the `kibana_system` role to have the necessary
privileges over the index.

=== Using Reverse proxies

If you use a reverse-proxy (NGINX, Apache, etc.) to access Kibana, you need
to configure the <<reporting-kibana-server-settings, Kibana server settings>>

include::{kib-repo-dir}/security/reporting.asciidoc[]
