/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Emit PND Detection Change Signal API endpoint
 *   version: 1
 */

import { z, lazySchema } from '@kbn/zod/v4';
import { isNonEmptyString } from '@kbn/zod-helpers/v4';

export const EmitDetectionChangeSignalRequestBody = lazySchema(() =>
  z.object({
    /**
      * Attack Discovery 2.0 alert id the claim is about. The Floor maps the producer event's alert id onto this field at the boundary, the same way `_derive` does.

      */
    correlationId: z.string().max(1024).superRefine(isNonEmptyString),
    /**
      * The investigation worker's rationale, verbatim. Clipped by the emit helper to this bound. Empty or whitespace-only is refused: a coverage claim that says nothing is worse than no claim.

      */
    gapDescription: z.string().max(2000).superRefine(isNonEmptyString),
    /**
     * Workflow execution id of the Floor run that concluded.
     */
    sourceRunId: z.string().max(1024).superRefine(isNonEmptyString),
  })
);
export type EmitDetectionChangeSignalRequestBody = z.infer<
  typeof EmitDetectionChangeSignalRequestBody
>;
export type EmitDetectionChangeSignalRequestBodyInput = z.input<
  typeof EmitDetectionChangeSignalRequestBody
>;

export const EmitDetectionChangeSignalResponse = lazySchema(() =>
  z.object({
    /**
      * True when the claim fired. False when it could not (missing correlation id, blank rationale, or a Workflows failure). The run still completed; this is the R4 signal that the subscriber was not woken.

      */
    emitted: z.boolean(),
  })
);
export type EmitDetectionChangeSignalResponse = z.infer<typeof EmitDetectionChangeSignalResponse>;
