/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

export const ELASTIC_AI_ASSISTANT_API_CURRENT_VERSION = '2023-10-31';
export const ELASTIC_AI_ASSISTANT_INTERNAL_API_VERSION = '1';

export const ELASTIC_AI_ASSISTANT_URL = '/api/elastic_assistant';

export const ELASTIC_AI_ASSISTANT_CONVERSATIONS_URL = `${ELASTIC_AI_ASSISTANT_URL}/conversations`;
export const ELASTIC_AI_ASSISTANT_CURRENT_USER_CONVERSATIONS_URL = `${ELASTIC_AI_ASSISTANT_CONVERSATIONS_URL}/current_user`;
export const ELASTIC_AI_ASSISTANT_CONVERSATIONS_URL_BY_ID = `${ELASTIC_AI_ASSISTANT_CONVERSATIONS_URL}/{conversationId}`;
export const ELASTIC_AI_ASSISTANT_CURRENT_USER_CONVERSATIONS_LAST = `${ELASTIC_AI_ASSISTANT_CURRENT_USER_CONVERSATIONS_URL}/_last`;

export const ELASTIC_AI_ASSISTANT_CONVERSATIONS_URL_BULK_ACTION = `${ELASTIC_AI_ASSISTANT_CONVERSATIONS_URL}/_bulk_action`;
export const ELASTIC_AI_ASSISTANT_CONVERSATIONS_URL_FIND = `${ELASTIC_AI_ASSISTANT_CONVERSATIONS_URL}/_find`;
export const ELASTIC_AI_ASSISTANT_CONVERSATIONS_URL_FIND_USER_CONVERSATIONS = `${ELASTIC_AI_ASSISTANT_CURRENT_USER_CONVERSATIONS_URL}/_find`;

export const ELASTIC_AI_ASSISTANT_PROMPTS_URL = `${ELASTIC_AI_ASSISTANT_URL}/prompts`;
export const ELASTIC_AI_ASSISTANT_PROMPTS_URL_BY_ID = `${ELASTIC_AI_ASSISTANT_PROMPTS_URL}/{promptId}`;
export const ELASTIC_AI_ASSISTANT_PROMPTS_URL_FIND = `${ELASTIC_AI_ASSISTANT_PROMPTS_URL}/_find`;

export const ELASTIC_AI_ASSISTANT_ANONIMIZATION_FIELDS_URL = `${ELASTIC_AI_ASSISTANT_URL}/anonimization_fields`;
export const ELASTIC_AI_ASSISTANT_ANONIMIZATION_FIELDS_URL_BULK_ACTION = `${ELASTIC_AI_ASSISTANT_ANONIMIZATION_FIELDS_URL}/_bulk_action`;
export const ELASTIC_AI_ASSISTANT_ANONIMIZATION_FIELDS_URL_FIND = `${ELASTIC_AI_ASSISTANT_ANONIMIZATION_FIELDS_URL}/_find`;
