/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Shared Primitives Schema
 *   version: not applicable
 */

import { z, lazySchema } from '@kbn/zod/v4';
import { isNonEmptyString } from '@kbn/zod-helpers/v4';

/**
 * A string that does not contain only whitespace characters
 */
export const NonEmptyString = lazySchema(() => z.string().min(1).superRefine(isNonEmptyString));
export type NonEmptyString = z.infer<typeof NonEmptyString>;

/**
 * A universally unique identifier
 */
export const UUID = lazySchema(() => z.string().uuid());
export type UUID = z.infer<typeof UUID>;
