[[development-plugin-resources]]
== Plugin Resources

Here are some resources that are helpful for getting started with plugin development.

[discrete]
=== Some light reading
If you haven't already, start with <<development-getting-started>>. If you are planning to add your plugin to the {kib} repo, read the <<contributing>> guide, if you are building a plugin externally, read <<external-plugin-development>>. In both cases, read up on our recommended <<development-best-practices>>.

[discrete]
=== Creating an empty plugin

You can use the <<automatic-plugin-generator>> to get a basic structure for a new plugin. Plugins that are not part of the
{kib} repo should be developed inside the `plugins` folder.  If you are building a new plugin to check in to the {kib} repo,
you will choose between a few locations:

 - {kib-repo}tree/{branch}/x-pack/plugins[x-pack/plugins] for commercially licensed plugins
 - {kib-repo}tree/{branch}/src/plugins[src/plugins] for open source licensed plugins
 - {kib-repo}tree/{branch}/examples[examples] for developer example plugins (these will not be included in the distributables)

[discrete]
=== Elastic UI Framework
If you're developing a plugin that has a user interface, take a look at our https://elastic.github.io/eui[Elastic UI Framework].
It documents the CSS and React components we use to build {kib}'s user interface.

You're welcome to use these components, but be aware that they are rapidly evolving, and we might introduce breaking changes that will disrupt your plugin's UI.

[discrete]
=== TypeScript Support
We recommend your plugin code is written in http://www.typescriptlang.org/[TypeScript].
To enable TypeScript support, create a `tsconfig.json` file at the root of your plugin that looks something like this:

["source","js"]
-----------
{
  // extend {kib}'s tsconfig, or use your own settings
  "extends": "../../kibana/tsconfig.json",

  // tell the TypeScript compiler where to find your source files
  "include": [
    "server/**/*",
    "public/**/*"
  ]
}
-----------

TypeScript code is automatically converted into JavaScript during development,
but not in the distributable version of {kib}. If you use the
{kib-repo}blob/{branch}/packages/kbn-plugin-helpers[@kbn/plugin-helpers] to build your plugin, then your `.ts` and `.tsx` files will be permanently transpiled before your plugin is archived. If you have your own build process, make sure to run the TypeScript compiler on your source files and ship the compilation output so that your plugin will work with the distributable version of {kib}.

[discrete]
=== {kib} platform migration guide

{kib-repo}blob/{branch}/src/core/MIGRATION.md#migrating-legacy-plugins-to-the-new-platform[This guide]
provides an action plan for moving a legacy plugin to the new platform. 

[discrete]
=== Externally developed plugins

If you are building a plugin outside of the {kib} repo, read <<external-plugin-development>>.

