[[kibana-sass]]
=== Styling with SASS

When writing a new component, create a sibling SASS file of the same
name and import directly into the *top* of JS/TS component file. Doing so ensures
the styles are never separated or lost on import and allows for better
modularization (smaller individual plugin asset footprint).

All SASS (.scss) files will automatically build with the
https://elastic.github.io/eui/#/guidelines/sass[EUI] & {kib} invisibles (SASS variables, mixins, functions) from
the {kib-repo}tree/{branch}/src/legacy/ui/public/styles/_globals_v7light.scss[globals_THEME.scss] file.

While the styles for this component will only be loaded if the component exists on the page,
the styles *will* be global and so it is recommended to use a three letter prefix on your
classes to ensure proper scope.

*Example:*

[source,tsx]
----
// component.tsx

import './component.scss';

export const Component = () => {
  return (
    <div className="plgComponent" />
  );
}
----

[source,scss]
----
// component.scss

.plgComponent { ... }
----

Do not use the underscore `_` SASS file naming pattern when importing
directly into a javascript file.