export declare const workflowExecutionEventNames: {
    workflows_execution_workflow_completed: string;
    workflows_execution_workflow_failed: string;
    workflows_execution_workflow_cancelled: string;
};
export declare const workflowExecutionEventSchemas: {
    workflows_execution_workflow_completed: {
        eventName: import("@kbn/core/server").SchemaValue<string>;
        startedAt: import("@kbn/core/server").SchemaValue<string>;
        completedAt: import("@kbn/core/server").SchemaValue<string>;
        duration: import("@kbn/core/server").SchemaValue<number>;
        timeToFirstStep: import("@kbn/core/server").SchemaValue<number | undefined>;
        stepCount: import("@kbn/core/server").SchemaValue<number>;
        stepTypes: import("@kbn/core/server").SchemaValue<string[]>;
        connectorTypes: import("@kbn/core/server").SchemaValue<string[]>;
        hasScheduledTriggers: import("@kbn/core/server").SchemaValue<boolean>;
        hasAlertTriggers: import("@kbn/core/server").SchemaValue<boolean>;
        hasTimeout: import("@kbn/core/server").SchemaValue<boolean>;
        hasConcurrency: import("@kbn/core/server").SchemaValue<boolean>;
        hasOnFailure: import("@kbn/core/server").SchemaValue<boolean>;
        executedStepCount: import("@kbn/core/server").SchemaValue<number>;
        successfulStepCount: import("@kbn/core/server").SchemaValue<number>;
        failedStepCount: import("@kbn/core/server").SchemaValue<number>;
        skippedStepCount: import("@kbn/core/server").SchemaValue<number>;
        executedConnectorTypes: import("@kbn/core/server").SchemaValue<string[]>;
        maxExecutionDepth: import("@kbn/core/server").SchemaValue<number>;
        hasRetries: import("@kbn/core/server").SchemaValue<boolean>;
        hasErrorHandling: import("@kbn/core/server").SchemaValue<boolean>;
        uniqueStepIdsExecuted: import("@kbn/core/server").SchemaValue<number>;
        queueDelayMs: import("@kbn/core/server").SchemaValue<number | null | undefined>;
        timedOut: import("@kbn/core/server").SchemaValue<boolean>;
        timeoutMs: import("@kbn/core/server").SchemaValue<number | undefined>;
        timeoutExceededByMs: import("@kbn/core/server").SchemaValue<number | undefined>;
        stepDurations: import("@kbn/core/server").SchemaValue<{
            stepId: string;
            stepType?: string;
            duration: number;
        }[] | undefined>;
        stepAvgDurationsByType: import("@kbn/core/server").SchemaValue<Record<string, number> | undefined>;
        workflowExecutionId: import("@kbn/core/server").SchemaValue<string>;
        workflowId: import("@kbn/core/server").SchemaValue<string>;
        spaceId: import("@kbn/core/server").SchemaValue<string>;
        triggerType: import("@kbn/core/server").SchemaValue<"alert" | "manual" | "scheduled">;
        isTestRun: import("@kbn/core/server").SchemaValue<boolean>;
        ruleId: import("@kbn/core/server").SchemaValue<string | undefined>;
    };
    workflows_execution_workflow_failed: {
        eventName: import("@kbn/core/server").SchemaValue<string>;
        startedAt: import("@kbn/core/server").SchemaValue<string>;
        failedAt: import("@kbn/core/server").SchemaValue<string>;
        duration: import("@kbn/core/server").SchemaValue<number>;
        timeToFirstStep: import("@kbn/core/server").SchemaValue<number | undefined>;
        stepCount: import("@kbn/core/server").SchemaValue<number>;
        stepTypes: import("@kbn/core/server").SchemaValue<string[]>;
        connectorTypes: import("@kbn/core/server").SchemaValue<string[]>;
        hasScheduledTriggers: import("@kbn/core/server").SchemaValue<boolean>;
        hasAlertTriggers: import("@kbn/core/server").SchemaValue<boolean>;
        hasTimeout: import("@kbn/core/server").SchemaValue<boolean>;
        hasConcurrency: import("@kbn/core/server").SchemaValue<boolean>;
        hasOnFailure: import("@kbn/core/server").SchemaValue<boolean>;
        errorMessage: import("@kbn/core/server").SchemaValue<string>;
        errorType: import("@kbn/core/server").SchemaValue<string>;
        failedStepId: import("@kbn/core/server").SchemaValue<string | undefined>;
        failedStepType: import("@kbn/core/server").SchemaValue<string | undefined>;
        executedStepCount: import("@kbn/core/server").SchemaValue<number>;
        successfulStepCount: import("@kbn/core/server").SchemaValue<number>;
        errorHandled: import("@kbn/core/server").SchemaValue<boolean>;
        executedConnectorTypes: import("@kbn/core/server").SchemaValue<string[]>;
        maxExecutionDepth: import("@kbn/core/server").SchemaValue<number>;
        hasRetries: import("@kbn/core/server").SchemaValue<boolean>;
        hasErrorHandling: import("@kbn/core/server").SchemaValue<boolean>;
        uniqueStepIdsExecuted: import("@kbn/core/server").SchemaValue<number>;
        queueDelayMs: import("@kbn/core/server").SchemaValue<number | null | undefined>;
        timedOut: import("@kbn/core/server").SchemaValue<boolean>;
        timeoutMs: import("@kbn/core/server").SchemaValue<number | undefined>;
        timeoutExceededByMs: import("@kbn/core/server").SchemaValue<number | undefined>;
        stepDurations: import("@kbn/core/server").SchemaValue<{
            stepId: string;
            stepType?: string;
            duration: number;
        }[] | undefined>;
        stepAvgDurationsByType: import("@kbn/core/server").SchemaValue<Record<string, number> | undefined>;
        workflowExecutionId: import("@kbn/core/server").SchemaValue<string>;
        workflowId: import("@kbn/core/server").SchemaValue<string>;
        spaceId: import("@kbn/core/server").SchemaValue<string>;
        triggerType: import("@kbn/core/server").SchemaValue<"alert" | "manual" | "scheduled">;
        isTestRun: import("@kbn/core/server").SchemaValue<boolean>;
        ruleId: import("@kbn/core/server").SchemaValue<string | undefined>;
    };
    workflows_execution_workflow_cancelled: {
        eventName: import("@kbn/core/server").SchemaValue<string>;
        startedAt: import("@kbn/core/server").SchemaValue<string>;
        cancelledAt: import("@kbn/core/server").SchemaValue<string>;
        duration: import("@kbn/core/server").SchemaValue<number>;
        timeToFirstStep: import("@kbn/core/server").SchemaValue<number | undefined>;
        stepCount: import("@kbn/core/server").SchemaValue<number>;
        stepTypes: import("@kbn/core/server").SchemaValue<string[]>;
        connectorTypes: import("@kbn/core/server").SchemaValue<string[]>;
        hasScheduledTriggers: import("@kbn/core/server").SchemaValue<boolean>;
        hasAlertTriggers: import("@kbn/core/server").SchemaValue<boolean>;
        hasTimeout: import("@kbn/core/server").SchemaValue<boolean>;
        hasConcurrency: import("@kbn/core/server").SchemaValue<boolean>;
        hasOnFailure: import("@kbn/core/server").SchemaValue<boolean>;
        cancellationReason: import("@kbn/core/server").SchemaValue<string | undefined>;
        cancelledBy: import("@kbn/core/server").SchemaValue<string | undefined>;
        executedStepCount: import("@kbn/core/server").SchemaValue<number>;
        successfulStepCount: import("@kbn/core/server").SchemaValue<number>;
        executedConnectorTypes: import("@kbn/core/server").SchemaValue<string[]>;
        maxExecutionDepth: import("@kbn/core/server").SchemaValue<number>;
        hasRetries: import("@kbn/core/server").SchemaValue<boolean>;
        hasErrorHandling: import("@kbn/core/server").SchemaValue<boolean>;
        uniqueStepIdsExecuted: import("@kbn/core/server").SchemaValue<number>;
        queueDelayMs: import("@kbn/core/server").SchemaValue<number | null | undefined>;
        timedOut: import("@kbn/core/server").SchemaValue<boolean>;
        timeoutMs: import("@kbn/core/server").SchemaValue<number | undefined>;
        timeoutExceededByMs: import("@kbn/core/server").SchemaValue<number | undefined>;
        stepDurations: import("@kbn/core/server").SchemaValue<{
            stepId: string;
            stepType?: string;
            duration: number;
        }[] | undefined>;
        stepAvgDurationsByType: import("@kbn/core/server").SchemaValue<Record<string, number> | undefined>;
        workflowExecutionId: import("@kbn/core/server").SchemaValue<string>;
        workflowId: import("@kbn/core/server").SchemaValue<string>;
        spaceId: import("@kbn/core/server").SchemaValue<string>;
        triggerType: import("@kbn/core/server").SchemaValue<"alert" | "manual" | "scheduled">;
        isTestRun: import("@kbn/core/server").SchemaValue<boolean>;
        ruleId: import("@kbn/core/server").SchemaValue<string | undefined>;
    };
};
