/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

export type { OnechatEvent } from './base/events';
export {
  internalNamespaces as toolNamespaces,
  protectedNamespaces as toolReservedNamespaces,
  isInProtectedNamespace,
} from './base/namespaces';
export {
  ToolType,
  type ToolDefinition,
  type ToolDefinitionWithSchema,
  platformCoreTools,
  defaultAgentToolIds,
  editableToolTypes,
  isReservedToolId,
  type ByIdsToolSelection,
  type ToolSelection,
  isByIdsToolSelection,
  toolMatchSelection,
  filterToolsBySelection,
  type ToolSelectionRelevantFields,
  allToolsSelectionWildcard,
  allToolsSelection,
  type EsqlToolConfig,
  type EsqlToolFieldTypes,
  type EsqlToolParam,
  type EsqlToolDefinition,
  type EsqlToolDefinitionWithSchema,
  EsqlToolFieldType,
  toolIdRegexp,
  toolIdMaxLength,
  activeToolsCountWarningThreshold,
  validateToolId,
  ToolResultType,
  type ToolResult,
  type ErrorResult,
  type QueryResult,
  type ResourceResult,
  type TabularDataResult,
  type OtherResult,
  type IndexSearchToolDefinitionWithSchema,
} from './tools';
export {
  OnechatErrorCode,
  OnechatErrorUtils,
  isInternalError,
  isToolNotFoundError,
  isOnechatError,
  isAgentNotFoundError,
  isConversationNotFoundError,
  isBadRequestError,
  isRequestAbortedError,
  createOnechatError,
  createInternalError,
  createToolNotFoundError,
  createAgentNotFoundError,
  createConversationNotFoundError,
  createBadRequestError,
  createRequestAbortedError,
  type OnechatError,
  type OnechatInternalError,
  type OnechatToolNotFoundError,
  type OnechatAgentNotFoundError,
  type OnechatConversationNotFoundError,
  type OnechatBadRequestError,
  type OnechatRequestAbortedError,
  type SerializedOnechatError,
} from './base/errors';
export { type UserIdAndName } from './base/users';
export { EsResourceType } from './base/resources';
export {
  oneChatDefaultAgentId,
  AgentType,
  type AgentDefinition,
  type AgentConfiguration,
  type AgentCapabilities,
  type ResolvedAgentCapabilities,
  agentIdRegexp,
} from './agents';
export {
  type RoundInput,
  type AssistantResponse,
  type ToolCallWithResult,
  type ConversationRound,
  type Conversation,
  type ConversationWithoutRounds,
  type ToolCallStep,
  type ConversationRoundStep,
  type ReasoningStepData,
  type ReasoningStep,
  ConversationRoundStepType,
  isToolCallStep,
  isReasoningStep,
  ChatEventType,
  type ChatEventBase,
  type ChatEvent,
  type ConversationCreatedEvent,
  type ConversationCreatedEventData,
  type ConversationUpdatedEvent,
  type ConversationUpdatedEventData,
  type ConversationIdSetEvent,
  type ConversationIdSetEventData,
  type ChatAgentEvent,
  type ToolProgressEvent,
  type ToolProgressEventData,
  type ToolResultEvent,
  type ToolResultEventData,
  type ToolCallEvent,
  type ToolCallEventData,
  type ReasoningEvent,
  type ReasoningEventData,
  type MessageChunkEventData,
  type MessageChunkEvent,
  type MessageCompleteEventData,
  type MessageCompleteEvent,
  type RoundCompleteEventData,
  type RoundCompleteEvent,
  type ToolCallProgress,
  isToolCallEvent,
  isToolResultEvent,
  isReasoningEvent,
  isMessageChunkEvent,
  isMessageCompleteEvent,
  isRoundCompleteEvent,
  isConversationCreatedEvent,
  isConversationUpdatedEvent,
  isToolProgressEvent,
} from './chat';
