/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

import { SECURITY_ALERT_ANALYSIS_WORKFLOW } from './alert_analysis';
import {
  ATTACK_DISCOVERY_ALERT_RETRIEVAL_WORKFLOW,
  ATTACK_DISCOVERY_CUSTOM_VALIDATION_EXAMPLE_WORKFLOW,
  ATTACK_DISCOVERY_GENERATION_WORKFLOW,
  ATTACK_DISCOVERY_RUN_EXAMPLE_WORKFLOW,
  ATTACK_DISCOVERY_SKILL_ALERT_RETRIEVAL_WORKFLOW,
  ATTACK_DISCOVERY_SKILL_REPORT_WORKFLOW,
  ATTACK_DISCOVERY_VALIDATE_WORKFLOW,
} from './discoveries';
import {
  SIGNIFICANT_EVENTS_DETECTION_WORKFLOW,
  SIGNIFICANT_EVENTS_DISCOVERY_WORKFLOW,
  SIGNIFICANT_EVENTS_ORCHESTRATOR_WORKFLOW,
  SIGNIFICANT_EVENTS_SCHEDULED_DETECTION_WORKFLOW,
  SIGNIFICANT_EVENTS_SCHEDULED_REVIEW_WORKFLOW,
  SIGNIFICANT_EVENTS_TRIAGE_WORKFLOW,
} from './significant_events';
import { SIGNIFICANT_EVENTS_INVESTIGATION_WORKFLOW } from './significant_events/investigation';
import {
  SIGNIFICANT_EVENTS_KI_CONTINUOUS_ONBOARDING_WORKFLOW,
  SIGNIFICANT_EVENTS_KI_FEATURES_IDENTIFICATION_WORKFLOW,
  SIGNIFICANT_EVENTS_KI_ONBOARDING_WORKFLOW,
  SIGNIFICANT_EVENTS_KI_QUERIES_GENERATION_WORKFLOW,
} from './significant_events/knowledge_indicators';
import {
  SIGNIFICANT_EVENTS_MEMORY_CONSOLIDATION_WORKFLOW,
  SIGNIFICANT_EVENTS_MEMORY_CONVERSATION_SCRAPER_WORKFLOW,
  SIGNIFICANT_EVENTS_MEMORY_GAP_DETECTION_WORKFLOW,
  SIGNIFICANT_EVENTS_MEMORY_SYNTHESIS_WORKFLOW,
} from './significant_events/memory';
import { EXAMPLE_MANAGED_WORKFLOW } from './workflows_extensions_example';

export {
  ATTACK_DISCOVERY_ALERT_RETRIEVAL_WORKFLOW_ID,
  ATTACK_DISCOVERY_CUSTOM_VALIDATION_EXAMPLE_WORKFLOW_ID,
  ATTACK_DISCOVERY_GENERATION_WORKFLOW_ID,
  ATTACK_DISCOVERY_RUN_EXAMPLE_WORKFLOW_ID,
  ATTACK_DISCOVERY_SKILL_ALERT_RETRIEVAL_WORKFLOW_ID,
  ATTACK_DISCOVERY_SKILL_REPORT_WORKFLOW_ID,
  ATTACK_DISCOVERY_VALIDATE_WORKFLOW_ID,
} from './discoveries';
export { EXAMPLE_MANAGED_WORKFLOW_ID } from './workflows_extensions_example';
export {
  SECURITY_ALERT_ANALYSIS_WORKFLOW,
  SECURITY_ALERT_ANALYSIS_WORKFLOW_ID,
} from './alert_analysis';
export {
  SIGNIFICANT_EVENTS_KI_FEATURES_IDENTIFICATION_WORKFLOW_ID,
  SIGNIFICANT_EVENTS_KI_QUERIES_GENERATION_WORKFLOW_ID,
  SIGNIFICANT_EVENTS_KI_ONBOARDING_WORKFLOW_ID,
  SIGNIFICANT_EVENTS_KI_CONTINUOUS_ONBOARDING_WORKFLOW_ID,
} from './significant_events/knowledge_indicators';
export {
  SIGNIFICANT_EVENTS_MEMORY_SYNTHESIS_WORKFLOW_ID,
  SIGNIFICANT_EVENTS_MEMORY_CONSOLIDATION_WORKFLOW_ID,
  SIGNIFICANT_EVENTS_MEMORY_CONVERSATION_SCRAPER_WORKFLOW_ID,
  SIGNIFICANT_EVENTS_MEMORY_GAP_DETECTION_WORKFLOW_ID,
} from './significant_events/memory';
export {
  SIGNIFICANT_EVENTS_DETECTION_WORKFLOW_ID,
  SIGNIFICANT_EVENTS_DISCOVERY_WORKFLOW_ID,
  SIGNIFICANT_EVENTS_ORCHESTRATOR_WORKFLOW_ID,
  SIGNIFICANT_EVENTS_SCHEDULED_DETECTION_WORKFLOW_ID,
  SIGNIFICANT_EVENTS_SCHEDULED_REVIEW_WORKFLOW_ID,
  SIGNIFICANT_EVENTS_TRIAGE_WORKFLOW_ID,
} from './significant_events';
export { SIGNIFICANT_EVENTS_INVESTIGATION_WORKFLOW_ID } from './significant_events/investigation';

// Registering the AD workflow definitions in the managed-workflows registry is
// FF-off safe: membership only makes a definition *discoverable by id* (which the
// discoveries plugin's integrity check exercises in tests). Registry membership
// installs nothing on its own — installation into Elasticsearch is a separate,
// explicit step performed by the owner (the discoveries plugin), and that plugin
// gates the install on the `securitySolution.attackDiscoveryWorkflowsEnabled`
// feature flag (read at start; see the discoveries plugin's `start()`). So with
// the FF off these definitions are inert, discoverable data — never installed or
// executed.
export const managedWorkflowDefinitions = [
  ATTACK_DISCOVERY_ALERT_RETRIEVAL_WORKFLOW,
  ATTACK_DISCOVERY_CUSTOM_VALIDATION_EXAMPLE_WORKFLOW,
  ATTACK_DISCOVERY_GENERATION_WORKFLOW,
  ATTACK_DISCOVERY_RUN_EXAMPLE_WORKFLOW,
  ATTACK_DISCOVERY_SKILL_ALERT_RETRIEVAL_WORKFLOW,
  ATTACK_DISCOVERY_SKILL_REPORT_WORKFLOW,
  ATTACK_DISCOVERY_VALIDATE_WORKFLOW,
  EXAMPLE_MANAGED_WORKFLOW,
  SECURITY_ALERT_ANALYSIS_WORKFLOW,
  SIGNIFICANT_EVENTS_KI_FEATURES_IDENTIFICATION_WORKFLOW,
  SIGNIFICANT_EVENTS_KI_QUERIES_GENERATION_WORKFLOW,
  SIGNIFICANT_EVENTS_KI_ONBOARDING_WORKFLOW,
  SIGNIFICANT_EVENTS_MEMORY_SYNTHESIS_WORKFLOW,
  SIGNIFICANT_EVENTS_MEMORY_CONSOLIDATION_WORKFLOW,
  SIGNIFICANT_EVENTS_MEMORY_CONVERSATION_SCRAPER_WORKFLOW,
  SIGNIFICANT_EVENTS_MEMORY_GAP_DETECTION_WORKFLOW,
  SIGNIFICANT_EVENTS_KI_CONTINUOUS_ONBOARDING_WORKFLOW,
  SIGNIFICANT_EVENTS_DETECTION_WORKFLOW,
  SIGNIFICANT_EVENTS_DISCOVERY_WORKFLOW,
  SIGNIFICANT_EVENTS_ORCHESTRATOR_WORKFLOW,
  SIGNIFICANT_EVENTS_TRIAGE_WORKFLOW,
  SIGNIFICANT_EVENTS_INVESTIGATION_WORKFLOW,
  SIGNIFICANT_EVENTS_SCHEDULED_DETECTION_WORKFLOW,
  SIGNIFICANT_EVENTS_SCHEDULED_REVIEW_WORKFLOW,
] as const;
