/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

import { SECURITY_ALERT_ANALYSIS_WORKFLOW } from './alert_analysis';
import {
  SIGNIFICANT_EVENTS_DETECTION_WORKFLOW,
  SIGNIFICANT_EVENTS_DISCOVERY_WORKFLOW,
  SIGNIFICANT_EVENTS_ORCHESTRATOR_WORKFLOW,
  SIGNIFICANT_EVENTS_SCHEDULED_DETECTION_WORKFLOW,
  SIGNIFICANT_EVENTS_SCHEDULED_REVIEW_WORKFLOW,
  SIGNIFICANT_EVENTS_TRIAGE_WORKFLOW,
} from './significant_events';
import { SIGNIFICANT_EVENTS_INVESTIGATION_WORKFLOW } from './significant_events/investigation';
import {
  SIGNIFICANT_EVENTS_KI_CONTINUOUS_ONBOARDING_WORKFLOW,
  SIGNIFICANT_EVENTS_KI_FEATURES_IDENTIFICATION_WORKFLOW,
  SIGNIFICANT_EVENTS_KI_ONBOARDING_WORKFLOW,
  SIGNIFICANT_EVENTS_KI_QUERIES_GENERATION_WORKFLOW,
} from './significant_events/knowledge_indicators';
import {
  SIGNIFICANT_EVENTS_MEMORY_CONSOLIDATION_WORKFLOW,
  SIGNIFICANT_EVENTS_MEMORY_CONVERSATION_SCRAPER_WORKFLOW,
  SIGNIFICANT_EVENTS_MEMORY_GAP_DETECTION_WORKFLOW,
  SIGNIFICANT_EVENTS_MEMORY_SYNTHESIS_WORKFLOW,
} from './significant_events/memory';
import { EXAMPLE_MANAGED_WORKFLOW } from './workflows_extensions_example';

export { EXAMPLE_MANAGED_WORKFLOW_ID } from './workflows_extensions_example';
export {
  SECURITY_ALERT_ANALYSIS_WORKFLOW,
  SECURITY_ALERT_ANALYSIS_WORKFLOW_ID,
} from './alert_analysis';
export {
  SIGNIFICANT_EVENTS_KI_FEATURES_IDENTIFICATION_WORKFLOW_ID,
  SIGNIFICANT_EVENTS_KI_QUERIES_GENERATION_WORKFLOW_ID,
  SIGNIFICANT_EVENTS_KI_ONBOARDING_WORKFLOW_ID,
  SIGNIFICANT_EVENTS_KI_CONTINUOUS_ONBOARDING_WORKFLOW_ID,
} from './significant_events/knowledge_indicators';
export {
  SIGNIFICANT_EVENTS_MEMORY_SYNTHESIS_WORKFLOW_ID,
  SIGNIFICANT_EVENTS_MEMORY_CONSOLIDATION_WORKFLOW_ID,
  SIGNIFICANT_EVENTS_MEMORY_CONVERSATION_SCRAPER_WORKFLOW_ID,
  SIGNIFICANT_EVENTS_MEMORY_GAP_DETECTION_WORKFLOW_ID,
} from './significant_events/memory';
export {
  SIGNIFICANT_EVENTS_DETECTION_WORKFLOW_ID,
  SIGNIFICANT_EVENTS_DISCOVERY_WORKFLOW_ID,
  SIGNIFICANT_EVENTS_ORCHESTRATOR_WORKFLOW_ID,
  SIGNIFICANT_EVENTS_SCHEDULED_DETECTION_WORKFLOW_ID,
  SIGNIFICANT_EVENTS_SCHEDULED_REVIEW_WORKFLOW_ID,
  SIGNIFICANT_EVENTS_TRIAGE_WORKFLOW_ID,
} from './significant_events';
export { SIGNIFICANT_EVENTS_INVESTIGATION_WORKFLOW_ID } from './significant_events/investigation';

export const managedWorkflowDefinitions = [
  EXAMPLE_MANAGED_WORKFLOW,
  SECURITY_ALERT_ANALYSIS_WORKFLOW,
  SIGNIFICANT_EVENTS_KI_FEATURES_IDENTIFICATION_WORKFLOW,
  SIGNIFICANT_EVENTS_KI_QUERIES_GENERATION_WORKFLOW,
  SIGNIFICANT_EVENTS_KI_ONBOARDING_WORKFLOW,
  SIGNIFICANT_EVENTS_MEMORY_SYNTHESIS_WORKFLOW,
  SIGNIFICANT_EVENTS_MEMORY_CONSOLIDATION_WORKFLOW,
  SIGNIFICANT_EVENTS_MEMORY_CONVERSATION_SCRAPER_WORKFLOW,
  SIGNIFICANT_EVENTS_MEMORY_GAP_DETECTION_WORKFLOW,
  SIGNIFICANT_EVENTS_KI_CONTINUOUS_ONBOARDING_WORKFLOW,
  SIGNIFICANT_EVENTS_DETECTION_WORKFLOW,
  SIGNIFICANT_EVENTS_DISCOVERY_WORKFLOW,
  SIGNIFICANT_EVENTS_ORCHESTRATOR_WORKFLOW,
  SIGNIFICANT_EVENTS_TRIAGE_WORKFLOW,
  SIGNIFICANT_EVENTS_INVESTIGATION_WORKFLOW,
  SIGNIFICANT_EVENTS_SCHEDULED_DETECTION_WORKFLOW,
  SIGNIFICANT_EVENTS_SCHEDULED_REVIEW_WORKFLOW,
] as const;
