/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

import * as settings from '@kbn/management-settings-ids';
import { WORKFLOWS_UI_SETTING_ID } from '@kbn/workflows/common/constants';

export const OBSERVABILITY_PROJECT_SETTINGS = [
  settings.DEFAULT_ROUTE_ID,
  settings.ML_ANOMALY_DETECTION_RESULTS_ENABLE_TIME_DEFAULTS_ID,
  settings.ML_ANOMALY_DETECTION_RESULTS_TIME_DEFAULTS_ID,
  settings.OBSERVABILITY_ENABLE_COMPARISON_BY_DEFAULT_ID,
  settings.OBSERVABILITY_APM_DEFAULT_SERVICE_ENVIRONMENT_ID,
  settings.OBSERVABILITY_APM_SERVICE_GROUP_MAX_NUMBER_OF_SERVICE_ID,
  settings.OBSERVABILITY_ENABLE_INSPECT_ES_QUERIES_ID,
  settings.OBSERVABILITY_APM_AWS_LAMBDA_PRICE_FACTOR_ID,
  settings.OBSERVABILITY_APM_AWS_LAMBDA_REQUEST_COST_PER_MILLION_ID,
  settings.OBSERVABILITY_APM_PROGRESSIVE_LOADING_ID,
  settings.OBSERVABILITY_ENABLE_INFRASTRUCTURE_ASSET_CUSTOM_DASHBOARDS_ID,
  settings.OBSERVABILITY_APM_ENABLE_TABLE_SEARCH_BAR,
  settings.OBSERVABILITY_APM_ENABLE_SERVICE_INVENTORY_TABLE_SEARCH_BAR,
  settings.OBSERVABILITY_LOGS_SHARED_NEW_LOGS_OVERVIEW_ID,
  settings.OBSERVABILITY_LOGS_DATA_ACCESS_LOG_SOURCES_ID,
  settings.OBSERVABILITY_ENABLE_DIAGNOSTIC_MODE,
  settings.OBSERVABILITY_STREAMS_ENABLE_ATTACHMENTS,
  settings.OBSERVABILITY_STREAMS_ENABLE_CONTENT_PACKS,
  settings.OBSERVABILITY_STREAMS_ENABLE_QUERY_STREAMS,
];

export const OBSERVABILITY_STREAMS_TIERED_PROJECT_SETTINGS = [
  settings.OBSERVABILITY_STREAMS_ENABLE_SIGNIFICANT_EVENTS,
  settings.OBSERVABILITY_STREAMS_ENABLE_SIGNIFICANT_EVENTS_DISCOVERY,
  // This setting is only registered in complete tier. It's temporary, will be removed on 9.4.0 release.
  WORKFLOWS_UI_SETTING_ID,
];

export const OBSERVABILITY_AI_ASSISTANT_PROJECT_SETTINGS = [
  settings.OBSERVABILITY_AI_ASSISTANT_SIMULATED_FUNCTION_CALLING,
  settings.OBSERVABILITY_AI_ASSISTANT_SEARCH_CONNECTOR_INDEX_PATTERN,
  settings.AI_ANONYMIZATION_SETTINGS,
  settings.GEN_AI_SETTINGS_DEFAULT_AI_CONNECTOR,
  settings.GEN_AI_SETTINGS_DEFAULT_AI_CONNECTOR_DEFAULT_ONLY,
  settings.AI_CHAT_EXPERIENCE_TYPE,
  settings.AGENT_BUILDER_EXPERIMENTAL_FEATURES_SETTING_ID,
];
