import React from 'react';
import type { ChromeStart, CoreStart, I18nStart, ScopedHistory, ThemeServiceStart } from '@kbn/core/public';
import type { KibanaFeature } from '@kbn/features-plugin/common';
import type { ChartsPluginStart } from '@kbn/charts-plugin/public';
import type { DataPublicPluginStart } from '@kbn/data-plugin/public';
import type { DataViewsPublicPluginStart } from '@kbn/data-views-plugin/public';
import type { DataViewEditorStart } from '@kbn/data-view-editor-plugin/public';
import type { UnifiedSearchPublicPluginStart } from '@kbn/unified-search-plugin/public';
import type { PluginStartContract as AlertingStart } from '@kbn/alerting-plugin/public';
import type { SpacesPluginStart } from '@kbn/spaces-plugin/public';
import type { LicensingPluginStart } from '@kbn/licensing-plugin/public';
import type { FieldFormatsStart } from '@kbn/field-formats-plugin/public';
import type { LensPublicStart } from '@kbn/lens-plugin/public';
import type { Storage } from '@kbn/kibana-utils-plugin/public';
import type { ActionsPublicPluginSetup } from '@kbn/actions-plugin/public';
import type { ExpressionsStart } from '@kbn/expressions-plugin/public';
import type { CasesService } from '@kbn/response-ops-alerts-table/types';
import type { SecurityPluginStart } from '@kbn/security-plugin/public';
import type { CloudSetup } from '@kbn/cloud-plugin/public';
import type { FieldsMetadataPublicStart } from '@kbn/fields-metadata-plugin/public';
import type { SharePluginStart } from '@kbn/share-plugin/public';
import type { ContentManagementPublicStart } from '@kbn/content-management-plugin/public';
import type { UiActionsStart } from '@kbn/ui-actions-plugin/public';
import type { CPSPluginStart } from '@kbn/cps/public';
import type { Start as InspectorStart } from '@kbn/inspector-plugin/public';
import type { ActionTypeRegistryContract, RuleTypeRegistryContract } from '../types';
export interface TriggersAndActionsUiServices extends CoreStart {
    actions: ActionsPublicPluginSetup;
    getCasesPlugin?: () => Promise<CasesService | undefined>;
    security: SecurityPluginStart;
    cloud?: CloudSetup;
    data: DataPublicPluginStart;
    dataViews: DataViewsPublicPluginStart;
    dataViewEditor: DataViewEditorStart;
    charts: ChartsPluginStart;
    alerting?: AlertingStart;
    spaces?: SpacesPluginStart;
    storage?: Storage;
    isCloud: boolean;
    setBreadcrumbs: ChromeStart['setBreadcrumbs'];
    actionTypeRegistry: ActionTypeRegistryContract;
    ruleTypeRegistry: RuleTypeRegistryContract;
    history: ScopedHistory;
    kibanaFeatures: KibanaFeature[];
    element: HTMLElement;
    i18n: I18nStart;
    theme: ThemeServiceStart;
    unifiedSearch: UnifiedSearchPublicPluginStart;
    licensing: LicensingPluginStart;
    expressions: ExpressionsStart;
    isServerless: boolean;
    fieldFormats: FieldFormatsStart;
    lens: LensPublicStart;
    fieldsMetadata: FieldsMetadataPublicStart;
    share?: SharePluginStart;
    contentManagement?: ContentManagementPublicStart;
    uiActions?: UiActionsStart;
    cps?: CPSPluginStart;
    inspector?: InspectorStart;
}
export declare const renderApp: (deps: TriggersAndActionsUiServices) => () => void;
export declare const App: ({ deps }: {
    deps: TriggersAndActionsUiServices;
}) => React.ReactElement<any, string | React.JSXElementConstructor<any>>;
export declare const AppWithoutRouter: ({ sectionsRegex }: {
    sectionsRegex: string;
}) => React.JSX.Element;
