[role="xpack"]
[[canvas-workpad]]
=== Create a workpad

When you create a workpad, you'll start with a blank page, or you can use a workpad that is already started for you. 

. Open *Canvas*.

. Choose one of the following options:

* To start with a single, blank workpad, click *Create workpad*.

* To create a workpad from a template, select *Templates*, then select a preconfigured template.

* To import an existing workpad, click and drag a workpad JSON file to the *Import workpad JSON file* field.

For advanced workpad examples, add a {kibana-ref}/add-sample-data.html[sample Kibana data set], then select *Canvas* from the *View Data* drop-down list.

For more workpad inspiration, go to the link:elastic.co[Elastic Blog] where we share Canvas updates and customer stories. 

[float]
==== Personalize your workpad

To personalize your workpad, use the editor on the right.

. Add a *Name* to your workpad, for example, `My Canvas workpad`.

. In the *Width* and *Height* fields, specify the size of your workpad. 

. Select the layout for your workpad. 
+
For example, click *720p* for a traditional presentation layout.

. Click the *Background color* picker, then select the background color for your workpad.

//TODO ask Catherine for cool video image, then insert here

TIP: To view your workpad in fullscreen mode, click the *Enter fullscreen mode* icon in the upper left corner.

////
Add the following text to a more appropriate place.
. Add more pages to your workpad, then select the page transition.

.. Click *Page 1*, then click the *+* icon.

.. From the *Transition* drop-down list, select the page transition you want to use. 
////

//TODO After the Canvas content is built out, move the following content to the end.
[float]
=== Share your workpad

When you are ready to share your workpad, create a PDF, or export your workpad to another author.

[float]
==== Create a PDF of your workpad

To view your workpad outside of Kibana, generate a PDF. 

. Enable reporting in your config/kibana.yml file.

. From your workpad, click the *Share workpad* icon in the upper left corner, then select *PDF reports*.

. Click *Generate PDF*. 

//TODO ask Catherine for cool video image, then insert here

[float]
==== Export your workpad

To import your workpads to another author, create JSON files of your workpads.

. Go to the *Canvas workpads* page. 

. Choose one of the following options:
.. To export a single workpad, click the *Export* icon next to the template you want to export.
+
To create a JSON file from your workpad, click the *Share workpad* icon in the upper left corner, then click *Download as JSON*.

.. To export multiple workpads, select the workpads you want to export, then click *Export*.

//TODO ask Catherine for cool video image, then insert here