[[canvas-getting-started]]
== Getting started with Canvas

Getting started with Canvas is easy. Your best bet is to check out one 
(or all) of the sample data sets that ship with {kib}. 

. Click the {kib} logo in the upper left hand corner of your browser to navigate 
to the {kib} home page.
. Click *Load a data set and a Kibana dashboard*. This will also load a 
Canvas workpad to go with the data set.
. Pick a data set. Let’s go with the eCommerce one for this example. 
+  
You might also click *Add* on all data sets why you’re here. You might want 
some of that data for later.

. Click the Canvas icon in the left hand navigation menu.
. Find the *[eCommerce] Revenue Tracking* workpad and click on its name to open it.

You’re in! The first thing to do is to make a copy of this 
workpad so you can come back to it later if needed. We’ll be making a mess 
of it in this tutorial. 

. Click the name of the workpad in the lower left hand corner. 
+
You’ll notice this is similar to the first screen. You could switch to a new 
workpad from here, but let's not for now.

. Click the *Clone* icon in the *[eCommerce] Revenue Tracking* row.
+
You now have a new workpad called *[eCommerce] Revenue Tracking - Copy*.


