[role="xpack"]
[[canvas-elements]]
=== Customize your workpad with elements

Elements are the building blocks of your workpad. Add and combine elements to create presentations of your data.

[float]
[[add-canvas-element]]
=== Add elements to your workpad

To customize your workpad to look the way you want, add elements to your workpad.

. Click *Add Element*, then select the best element to show off your data. 
+
//TODO add image
+
Elements come preconfigured with demo data so that you can familiarize yourself with the element. Play around with the default settings and see what the element can do. 

. To move the element, click and drag it to your preferred location.
+
You can also select the element, then use your arrow keys to move the element by 1 pixel. 
+
As you move the element, notice the alignment lines that appear to help you place the element exactly where you want it.

. To resize the element, click a corner, then drag to the size you want.

. Want to delete the element? Select the element, click the *Element options* icon in the top right corner, then select *Delete*.

[float]
[[connect-element-data]]
=== Connect the element to your data

To connect the element to your own data, use the panel on the right.

. Make sure that the element is selected, then select *Data*.

. Click *Change your data source*.

[float]
[[elasticsearch-sql-data-source]]
==== Connect the element to Elasticsearch SQL

Use Elasticsearch SQL to generate a data table.

. Click *Elasticsearch SQL*.

. In the *Elasticearch SQL query* box, enter your query, then click *Preview*.

. If your query looks correct, click *Save*. 
+ 
The element appears as a warning. 

. Click *Display*

. Change the data points to display in your element. 

. In the *Label* field, enter a name for the data.

. To specify the auto-refresh interval for the element, click the *Control settings* icon in the top left corner, then click the interval you want to use.
+
To manually refresh the data, click the *Refresh data* icon. 

Unfamiliar with writing Elasticsearch SQL queries? Go to {ref}/sql-spec.html[SQL language] for more information.

[float]
[[elasticsearch-raw-doc-data-source]]
==== Connect the element to Elasticsearch raw documents

Use the Lucene query syntax to pull back raw documentation from Elasticsearch.

. Click *Elasticsearch raw documents*.

.. From the *Index* dropdown, select the index data that you want to display. 

.. From the *Fields* dropdown, select the associated fields you want to display.

.. To sort the data, select an option from the *Sort Field* and *Sort Order* dropdowns.

.. For more targeted queries, enter a *Query* using the Lucene query string syntax. 
+
For for more information about the Lucene query string sytax, refer to <<lucene-query,Lucene Query Syntax>>.

. Click *Preview*. 

. If your query looks correct, click *Save*. 
+ 
The element appears as a warning. 

. Click *Display*

.. Change the data points to display in your element. 

.. In the *Label* field, enter a name for the data.

. To specify the auto-refresh interval for the element, click the *Control settings* icon in the top left corner, then click the interval you want to use.
+
To manually refresh the data, click the *Refresh data* icon. 

[float]
[[timelion-data-source]]
==== Connect the element to Timelion

Use Timelion queries to pull back time series data in a tabular format. 

. Click *Timelion*.

. Enter a *Query* using the Lucene query string syntax. 
+
For for more information about the Lucene query string syntax, refer to <<lucene-query,Lucene Query Syntax>>.

. Enter the *Interval*, then click *Preview*.

. If your query looks correct, click *Save*. 
+ 
The element appears as a warning. 

. Click *Display*

. Change the data points to display in your element. 

. In the *Label* field, enter a name for the data.

. To specify the auto-refresh interval for the element, click the *Control settings* icon in the top left corner, then click the interval you want to use.
+
To manually refresh the data, click the *Refresh data* icon. 

For more information about Timelion, refer to <<timelion,Timelion>>.

[float]
[[element-display-options]]
=== Choose the display options

Choose how you want the element to appear on your workpad. For each element type, the display options are different.

. Make sure that the element is selected, then select *Display*.

. Specify the display options you want to use.

. To use the advanced display options, click *+* next to *Element style*, then choose one of these options:

* To make small changes to the appearance of the element, click *Container style*.

* To apply a CSS stylesheet to the element, click *CSS*.

//For more advanced customization options, create Canvas plugins.

//To further define the appearance and behavior of the element, use the <<canvas-expression-editor,expression editor>>.

[float]
[[organize-element]]
=== Organize the elements on your workpad

. Align the elements.

.. Press Shift, then select the elements you want to align.

.. Click the *Element options* icon in the top right corner, then select *Align elements*.

.. From the *Alignment* menu, select the type of alignment.

. Distribute the elements.

.. Press Shift, then select the elements you want to distribute.

.. Click the *Element options* icon in the top right corner, then select *Distribute elements*.

.. From the *Distribution* menu, select the type of distribution.

. Change the order of the elements.

.. Click an element, then click the *Element options* icon in the top right corner. 

.. Select *Order*, then select the action.

[float]
[[element-save]]
=== Save elements

After you have made changes to elements, save them so that you can reuse them across your workpads.

. Make sure that the element is selected.
+
To save a group of elements, press Shift, then select the elements you want to save.

. Next to *Selected element*, click the *Save as new element* icon.

. In the *Create new element* window, enter a *Name* for the element.

. Enter an optional *Description*, then click *Save*.
+
To access the element, click *Add element*, then select *My elements*.

[float]
[[add-more-pages]]
=== Add more pages to the workpad

When you have run out of room on your workpad, you can add more pages.

. Click *Page 1*, then click the *+* icon.

. On the *Page* editor, select the page transition from the *Transition* dropdown. 

//TODO insert image

[float]
[[workpad-display-options]]
=== Change the workpad display options

For a better view of the elements on your workpad, change the display options.

* To view your workpad in fullscreen mode, click the *Enter fullscreen mode* icon in the upper left corner.

* To zoom in or out on the workpad, click the *Zoom controls* icon in the upper left corder, then select one of the options.

[float]
[[enable-autoplay]]
=== Enable autoplay 

Automatically cycle through your workpads pages in fullscreen mode.

. In the upper left corner, click the *Control settings* icon.

. Under *Change cycling interval*, select the cycle interval you want to use.
