[role="xpack"]
[[canvas-getting-started]]
== Getting started with Canvas

Canvas is a data visualization and presentation tool that sits within Kibana. Backed by Elasticsearch, Canvas allows you to combine data with colors, images, text, and your imagination to bring dynamic, multi-page, pixel-perfect displays to screens large and small. If you are a little bit creative, a little bit technical, and a whole lot curious, then Canvas is for you. 

With Canvas, you can:

* Create and personalize your work space with backgrounds, borders, colors, fonts, and more. 

* Customize your workpad with your own visualizations, such as images and text.

* Show off your data with charts, graphs, progress monitors, and more.

* Focus the data you want to display with filters.

<<link to some examples of Canvas in use>>

For a quick overview of Canvas, watch this video: https://www.youtube.com/watch?v=ZqvF_5-1xjQ. 

[float]
=== Before you begin

For this tutorial, you'll use the {kibana-ref}/add-sample-data.html[*Sample eCommerce orders* data].

=== Create and personalize your workpad

Your first step to working with Canvas is to create a workpad. 

. Open *Canvas*.

. Click *Create workpad*.

. To personalize the workpad and page, use the editor on the right.

.. Enter a *Name* for your workpad. For example, `Welcome to Canvas`.

.. Change the page *Background color* to light gray.

=== Customize your workpad

To customize your workpad to look the way you want, add your own images and text.

. Click *Add element*, then click *Image*.
+
The default Elastic logo image appears on your page.

. To replace the Elastic logo with your own image, select the image, then use the editor on the right.

. To move the image, click and drag it to your preferred location.
+
You'll notice that the image is tagged as an asset, which allows you to reuse the image from *Manage assets*.

//Add image

. Click *Add element*, then click *Metric*. 
+
By default, the *Metric* element is connected to a demo data source, which enables you to experiment with the element before you connect it to your own data source.

. To connect the element to your own data source, make sure that the element is selected, then click *Data*.

.. Click *Change your data source*, then click *Elasticsearch SQL*.

.. Copy and paste `SELECT sum(taxless_total_price) AS sum_total_price FROM "kibana_sample_data_ecommerce"` into the *Elasticsearch SQL query* field.
+
The query selects the total price field and sets it to the sum_total_price field. These fields are pulled from the kibana_sample_data_ecommerce index that you installed.

//Add image

.. To verify that the data is correct, click *Preview*. If you like what you see, click *Save*.
+
At this point, the element displays an error.

. Specify how to process and display the data.

.. Click *Display*

.. Under *Number*, select *Value* from the function drop-down list, then select *sum_total_price* from the column drop-down list.

//Add image

.. Change the *Label* to 'Total sales'.
+
You'll notice that the error is gone, but the number could use some formatting.

. To format the number, use the Canvas expression language.

.. In the lower right corner, click *Expression editor*.
+
You're now looking at the raw data syntax that Canvas uses to display the element.

.. Look for `math "sum_total_price"`, then add `| formatNumber "$0a"`.

.. To update the number, click *Run*.

//Add image

.. When you are done, click *Close* on the *Expression editor*.

TIP: Want to delete an element? Click the back button on your browser.

=== Show off your data

To show what your data can do, add and customize charts, graphs, progress monitors, and more.

. Click *Add element*, then click *Area chart*. 

. To connect the element to your own data source, make sure that the element is selected, then click *Data*.

.. Click *Change your data source*, then click *Elasticsearch SQL*.

.. To obtain the taxless total price by date, copy and paste `SELECT order_date, taxless_total_price FROM "kibana_sample_data_ecommerce" ORDER BY order_date` into the *Elasticsearch SQL query* field.
+
Although you used the Elasticsearch SQL data source for the metric and area chart elements, each element can display a different data source. Pages and workpads often contain multiple data sources.

.. To verify that the data is correct, click *Preview*. If you like what you see, click *Save*.

. Specify how to display the data.

.. Click *Display*

.. From the *X-axis* drop-down lists, select *Value*, then select *order_date*.

.. From the *Y-axis* drop-down lists, select *Value*, then select *taxless_total_price*.

//Add image

=== Show how your data changes over time

To focus your data on a specific time range, apply a time filter. 

. Click *Add element*, then click *Time filter*.

. Specify how to display the data.

.. Click *Display*

.. To use the date time field from the sample data, enter `order_date` in the *Column* field, then click *Set*.
+
To see how the data changes, set the time filter to *Last 7 days*. As you change the time filter options, the metrics dynamically update.

//Add image

Your workpad is now complete! Use the icons in the upper left corner to:

* Share your workpad

* Display your workpad in fullscreen mode

* Download your workpad as a PDF report or JSON object 
