FROM docker.elastic.co/kibana/kibana:7.17.28-amd64
COPY config/kibana.yml /usr/share/kibana/config/kibana.yml
COPY plugins/kibana_pendo/build/kibanaPendo-7.17.28.zip /usr/share/kibana/
RUN bin/kibana-plugin install file:///usr/share/kibana/kibanaPendo-7.17.28.zip
RUN rm /usr/share/kibana/kibanaPendo-7.17.28.zip