FROM docker.elastic.co/kibana/kibana:7.17.27-amd64

COPY plugins/kibana_pendo/build/kibanaPendo-7.17.27.zip /usr/share/kibana/
RUN bin/kibana-plugin install file:///usr/share/kibana/kibanaPendo-7.17.27.zip
