



cd /Users/gsoldevila/Work/kibana-presentation && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/kibana-presentation > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-presentation && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-reporting-services && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/kibana-reporting-services > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-reporting-services && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-security && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/kibana-security > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-security && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-visualizations && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/kibana-visualizations > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-visualizations && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-logstash && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/logstash > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-logstash && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-ml-ui && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/ml-ui > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-ml-ui && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-obs-ai-assistant && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/obs-ai-assistant > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-obs-ai-assistant && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-obs-entities && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/obs-entities > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-obs-entities && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-obs-knowledge-team && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/obs-knowledge-team > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-obs-knowledge-team && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-obs-ux-infra_services-team && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/obs-ux-infra_services-team > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-obs-ux-infra_services-team && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-obs-ux-logs-team && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/obs-ux-logs-team > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-obs-ux-logs-team && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-obs-ux-management-team && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/obs-ux-management-team > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-obs-ux-management-team && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-obs-ux-onboarding-team && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/obs-ux-onboarding-team > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-obs-ux-onboarding-team && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-observability-ui && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/observability-ui > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-observability-ui && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-response-ops && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/response-ops > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-response-ops && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-search-kibana && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/search-kibana > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-search-kibana && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-security-asset-management && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/security-asset-management > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-security-asset-management && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-security-defend-workflows && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/security-defend-workflows > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-security-defend-workflows && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-security-detection-engine && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/security-detection-engine > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-security-detection-engine && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-security-detection-rule-management && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/security-detection-rule-management > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-security-detection-rule-management && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-security-detections-response && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/security-detections-response > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-security-detections-response && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-security-generative-ai && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/security-generative-ai > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-security-generative-ai && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-security-scalability && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/security-scalability > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-security-scalability && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-security-solution && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/security-solution > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-security-solution && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-security-threat-hunting-explore && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/security-threat-hunting-explore > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-security-threat-hunting-explore && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-security-threat-hunting-investigations && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/security-threat-hunting-investigations > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-security-threat-hunting-investigations && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-security-threat-hunting && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/security-threat-hunting > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-security-threat-hunting && git add . && git restore --staged ./packages/kbn-manifest/*
cd /Users/gsoldevila/Work/kibana-stack-monitoring && git pull && cp ../kibana/packages/kbn-manifest/* ./packages/kbn-manifest/ && rm -fR node_modules && yarn kbn bootstrap && node scripts/manifest --max-old-space-size=16384 --relocate @elastic/stack-monitoring > relocate.out 2>relocate.err && git branch kbn-team-1309-move-kibana-stack-monitoring && git add . && git restore --staged ./packages/kbn-manifest/*
