import React from 'react';
import type { JsonCodeEditorProps } from './components';
import { UnifiedDocViewerPublicPlugin } from './plugin';
export type { UnifiedDocViewerSetup, UnifiedDocViewerStart } from './plugin';
export declare const JsonCodeEditor: React.ForwardRefExoticComponent<JsonCodeEditorProps & import("@kbn/shared-ux-utility").WithSuspenseExtendedDeps & React.RefAttributes<{}>>;
export { useEsDocSearch } from './hooks';
export { UnifiedDocViewer } from './components/lazy_doc_viewer';
export type { UnifiedDocViewerFlyoutProps } from './components/doc_viewer_flyout/doc_viewer_flyout';
export { UnifiedDocViewerFlyout } from './components/lazy_doc_viewer_flyout';
export { ContentFrameworkSection } from './components/content_framework/lazy_content_framework_section';
export type { LogsOverviewProps as UnifiedDocViewerLogsOverviewProps, LogsOverviewApi as UnifiedDocViewerLogsOverviewApi, } from './components/doc_viewer_logs_overview/logs_overview';
export { UnifiedDocViewerLogsOverview } from './components/lazy_doc_viewer_logs_overview';
export { UnifiedDocViewerObservabilityTracesOverview } from './components/observability/traces/doc_viewer_overview/lazy_doc_viewer_obs_traces_overview';
export { UnifiedDocViewerObservabilityGenericOverview } from './components/observability/generic/doc_viewer_overview/lazy_doc_viewer_obs_generic_overview';
export { UnifiedDocViewerObservabilityAttributesOverview } from './components/observability/attributes/doc_viewer_attributes_overview/lazy_doc_viewer_obs_attributes_overview';
export { UnifiedDocViewerObservabilityTraceDocFlyout } from './components/observability/traces/components/full_screen_waterfall/waterfall_flyout/lazy_trace_doc_flyout';
export type { TraceDocFlyoutProps as UnifiedDocViewerObservabilityTraceDocFlyoutProps } from './components/observability/traces/components/full_screen_waterfall/waterfall_flyout/trace_doc_flyout';
export type { TraceDocFlyoutType as UnifiedDocViewerObservabilityTracesDocumentType } from './components/observability/traces/components/full_screen_waterfall/waterfall_flyout/trace_doc_flyout';
export declare const plugin: () => UnifiedDocViewerPublicPlugin;
