/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { CatMlJobsRequest } from '../schemas/cat_ml_jobs'
import type { EsApiDefinition } from '../types'

export const catMlJobsApis: EsApiDefinition[] = [
 {
  name: "ml-jobs",
  namespace: "cat",
  description: "Get anomaly detection jobs.",
  method: "GET",
  path: "/_cat/ml/anomaly_detectors/{job_id}",
  input: CatMlJobsRequest,
  responseType: 'text',
 },
]
