/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { CatCountRequest } from '../schemas/cat_count'
import type { EsApiDefinition } from '../types'

export const catCountApis: EsApiDefinition[] = [
 {
  name: "count",
  namespace: "cat",
  description: "Get a document count.",
  method: "POST",
  path: "/_cat/count/{index}",
  input: CatCountRequest,
  responseType: 'text',
 },
]
