/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { ClusterDeleteComponentTemplateRequest } from '../schemas/cluster_delete_component_template'
import type { EsApiDefinition } from '../types'

export const clusterDeleteComponentTemplateApis: EsApiDefinition[] = [
 {
  name: "delete-component-template",
  namespace: "cluster",
  description: "Delete component templates.",
  method: "DELETE",
  path: "/_component_template/{name}",
  input: ClusterDeleteComponentTemplateRequest,
 },
]
