/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { EqlDeleteRequest } from '../schemas/eql_delete'
import type { EsApiDefinition } from '../types'

export const eqlDeleteApis: EsApiDefinition[] = [
 {
  name: "delete",
  namespace: "eql",
  description: "Delete an async EQL search.",
  method: "DELETE",
  path: "/_eql/search/{id}",
  input: EqlDeleteRequest,
 },
]
