/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IndicesFlushRequest } from '../schemas/indices_flush'
import type { EsApiDefinition } from '../types'

export const indicesFlushApis: EsApiDefinition[] = [
 {
  name: "flush",
  namespace: "indices",
  description: "Flush data streams or indices.",
  method: "POST",
  path: "/{index}/_flush",
  input: IndicesFlushRequest,
 },
]
