/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IndicesPutDataStreamOptionsRequest } from '../schemas/indices_put_data_stream_options'
import type { EsApiDefinition } from '../types'

export const indicesPutDataStreamOptionsApis: EsApiDefinition[] = [
 {
  name: "put-data-stream-options",
  namespace: "indices",
  description: "Update data stream options.",
  method: "PUT",
  path: "/_data_stream/{name}/_options",
  input: IndicesPutDataStreamOptionsRequest,
 },
]
