/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { MlDeleteForecastRequest } from '../schemas/ml_delete_forecast'
import type { EsApiDefinition } from '../types'

export const mlDeleteForecastApis: EsApiDefinition[] = [
 {
  name: "delete-forecast",
  namespace: "ml",
  description: "Delete forecasts from a job.",
  method: "DELETE",
  path: "/_ml/anomaly_detectors/{job_id}/_forecast/{forecast_id}",
  input: MlDeleteForecastRequest,
 },
]
