/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { MlInferTrainedModelRequest } from '../schemas/ml_infer_trained_model'
import type { EsApiDefinition } from '../types'

export const mlInferTrainedModelApis: EsApiDefinition[] = [
 {
  name: "infer-trained-model",
  namespace: "ml",
  description: "Evaluate a trained model.",
  method: "POST",
  path: "/_ml/trained_models/{model_id}/_infer",
  input: MlInferTrainedModelRequest,
 },
]
