/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { MlRevertModelSnapshotRequest } from '../schemas/ml_revert_model_snapshot'
import type { EsApiDefinition } from '../types'

export const mlRevertModelSnapshotApis: EsApiDefinition[] = [
 {
  name: "revert-model-snapshot",
  namespace: "ml",
  description: "Revert to a snapshot.",
  method: "POST",
  path: "/_ml/anomaly_detectors/{job_id}/model_snapshots/{snapshot_id}/_revert",
  input: MlRevertModelSnapshotRequest,
 },
]
