/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { z } from '@kbn/zod/v4'
import { MsearchRequest } from '../schemas/msearch'
import type { EsApiDefinition } from '../types'

const MsearchRequestPassthrough = MsearchRequest.extend({
  searches: z.array(z.any()).optional().meta({ found_in: 'body' })
})

export const msearchApis: EsApiDefinition[] = [
 {
  name: "msearch",
  description: "Run multiple searches.",
  method: "GET",
  path: "/{index}/_msearch",
  input: MsearchRequestPassthrough,
  bodyFormat: 'ndjson',
 },
]
