/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SqlTranslateRequest } from '../schemas/sql_translate'
import type { EsApiDefinition } from '../types'

export const sqlTranslateApis: EsApiDefinition[] = [
 {
  name: "translate",
  namespace: "sql",
  description: "Translate SQL into Elasticsearch queries.",
  method: "POST",
  path: "/_sql/translate",
  input: SqlTranslateRequest,
 },
]
