/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: SIEM Migration common components
 *   version: not applicable
 */

import { z, lazySchema } from '@kbn/zod/v4';

import { NonEmptyString } from '../../api/model/primitives.gen';
import { SplunkResourceType } from './vendor/common/splunk.gen';
import { QradarResourceType } from './vendor/common/qradar.gen';

/**
 * The GenAI connector id to use.
 */
export const ConnectorId = lazySchema(() => z.string());
export type ConnectorId = z.infer<typeof ConnectorId>;

/**
 * The LangSmith options object.
 */
export const LangSmithOptions = lazySchema(() =>
  z.object({
    /**
     * The project name.
     */
    project_name: z.string(),
    /**
     * The API key to use for tracing.
     */
    api_key: z.string(),
  })
);
export type LangSmithOptions = z.infer<typeof LangSmithOptions>;

/**
 * The LangSmith settings object for evaluations.
 */
export const LangSmithEvaluationOptions = lazySchema(() =>
  LangSmithOptions.merge(
    z.object({
      /**
       * The dataset name to use for evaluations.
       */
      dataset: z.string(),
    })
  )
);
export type LangSmithEvaluationOptions = z.infer<typeof LangSmithEvaluationOptions>;

/**
 * The vendor identifier.
 */
export const SiemMigrationVendor = lazySchema(() =>
  z.enum(['splunk', 'qradar', 'microsoft-sentinel'])
);
export type SiemMigrationVendor = z.infer<typeof SiemMigrationVendor>;
export type SiemMigrationVendorEnum = typeof SiemMigrationVendor.enum;
export const SiemMigrationVendorEnum = SiemMigrationVendor.enum;

/**
 * A comment for the migration process
 */
export const MigrationComment = lazySchema(() =>
  z.object({
    /**
     * The message of the migration comment
     */
    message: z.string(),
    /**
     * The moment of creation of the comment
     */
    created_at: z.string(),
    /**
     * The user profile ID of the user who created the comment, or `assistant` if it was generated by the LLM
     */
    created_by: z.string(),
  })
);
export type MigrationComment = z.infer<typeof MigrationComment>;

/**
 * The comments for the migration including a summary from the LLM in markdown.
 */
export const MigrationComments = lazySchema(() => z.array(MigrationComment));
export type MigrationComments = z.infer<typeof MigrationComments>;

/**
 * The status of migration.
 */
export const MigrationStatus = lazySchema(() =>
  z.enum(['pending', 'processing', 'completed', 'failed'])
);
export type MigrationStatus = z.infer<typeof MigrationStatus>;
export type MigrationStatusEnum = typeof MigrationStatus.enum;
export const MigrationStatusEnum = MigrationStatus.enum;

/**
 * The status of the migration task.
 */
export const MigrationTaskStatus = lazySchema(() =>
  z.enum(['ready', 'running', 'stopped', 'finished', 'interrupted'])
);
export type MigrationTaskStatus = z.infer<typeof MigrationTaskStatus>;
export type MigrationTaskStatusEnum = typeof MigrationTaskStatus.enum;
export const MigrationTaskStatusEnum = MigrationTaskStatus.enum;

/**
 * The last execution of a migration task.
 */
export const MigrationLastExecution = lazySchema(() =>
  z.object({
    /**
     * The total execution time in milliseconds for the migration. This includes duration of last_execution and any previous executions.
     */
    total_execution_time_ms: z.number().int().optional(),
    /**
     * The moment the last execution started.
     */
    started_at: z.string().optional(),
    /**
     * The moment the last execution finished.
     */
    finished_at: z.string().nullable().optional(),
    /**
     * The connector ID used for the last execution.
     */
    connector_id: z.string().optional(),
    /**
     * The error message if the last execution failed.
     */
    error: z.string().nullable().optional(),
    /**
     * Indicates if the last execution was stopped by the user.
     */
    is_stopped: z.boolean().optional(),
  })
);
export type MigrationLastExecution = z.infer<typeof MigrationLastExecution>;

/**
 * The items migration translation stats object.
 */
export const MigrationTranslationStats = lazySchema(() =>
  z.object({
    /**
     * The migration id
     */
    id: NonEmptyString,
    /**
     * The items migration translation stats.
     */
    items: z.object({
      /**
       * The total number of items in the migration.
       */
      total: z.number().int(),
      /**
       * The number of items that have been successfully translated.
       */
      success: z.object({
        /**
         * The total number of items that have been successfully translated.
         */
        total: z.number().int(),
        /**
         * The translation results
         */
        result: z.object({
          /**
           * The number of items that have been fully translated.
           */
          full: z.number().int(),
          /**
           * The number of items that have been partially translated.
           */
          partial: z.number().int(),
          /**
           * The number of items that could not be translated.
           */
          untranslatable: z.number().int(),
        }),
        /**
         * The number of items that have been successfully translated and can be installed.
         */
        installable: z.number().int(),
      }),
      /**
       * The number of items that have failed translation.
       */
      failed: z.number().int(),
    }),
  })
);
export type MigrationTranslationStats = z.infer<typeof MigrationTranslationStats>;

/**
 * The migration translation result.
 */
export const MigrationTranslationResult = lazySchema(() =>
  z.enum(['full', 'partial', 'untranslatable'])
);
export type MigrationTranslationResult = z.infer<typeof MigrationTranslationResult>;
export type MigrationTranslationResultEnum = typeof MigrationTranslationResult.enum;
export const MigrationTranslationResultEnum = MigrationTranslationResult.enum;

/**
 * The migration items stats.
 */
export const MigrationTaskItemsStats = lazySchema(() =>
  z.object({
    /**
     * The total number of items to migrate.
     */
    total: z.number().int(),
    /**
     * The number of items that are pending migration.
     */
    pending: z.number().int(),
    /**
     * The number of items that are being migrated.
     */
    processing: z.number().int(),
    /**
     * The number of items that have been migrated successfully.
     */
    completed: z.number().int(),
    /**
     * The number of items that have failed migration.
     */
    failed: z.number().int(),
  })
);
export type MigrationTaskItemsStats = z.infer<typeof MigrationTaskItemsStats>;

/**
 * The migration task stats object.
 */
export const MigrationTaskStats = lazySchema(() =>
  z.object({
    /**
     * The migration id
     */
    id: NonEmptyString,
    /**
     * The migration name
     */
    name: NonEmptyString,
    /**
     * Indicates if the migration task status.
     */
    status: MigrationTaskStatus,
    /**
     * The migration items stats.
     */
    items: MigrationTaskItemsStats,
    /**
     * The moment the migration was created.
     */
    created_at: z.string(),
    /**
     * The moment of the last update.
     */
    last_updated_at: z.string(),
    /**
     * The last execution of the migration task.
     */
    last_execution: MigrationLastExecution.optional(),
    /**
     * The migration vendor.
     */
    vendor: SiemMigrationVendor.optional(),
  })
);
export type MigrationTaskStats = z.infer<typeof MigrationTaskStats>;

export const SiemMigrationResourceType = lazySchema(() =>
  z.union([SplunkResourceType, QradarResourceType])
);
export type SiemMigrationResourceType = z.infer<typeof SiemMigrationResourceType>;

/**
 * A resource of a migration
 */
export const SiemMigrationResourceBase = lazySchema(() =>
  z.object({
    type: SiemMigrationResourceType,
    /**
     * The name of the resource
     */
    name: NonEmptyString,
  })
);
export type SiemMigrationResourceBase = z.infer<typeof SiemMigrationResourceBase>;

export const SiemMigrationResourceContent = lazySchema(() =>
  z.object({
    /**
     * The resource content value. Can be an empty string.
     */
    content: z.string(),
    /**
     * The resource arbitrary metadata.
     */
    metadata: z.object({}).catchall(z.unknown()).optional(),
  })
);
export type SiemMigrationResourceContent = z.infer<typeof SiemMigrationResourceContent>;

/**
 * The rule migration resource data.
 */
export const SiemMigrationResourceData = lazySchema(() =>
  SiemMigrationResourceBase.merge(SiemMigrationResourceContent)
);
export type SiemMigrationResourceData = z.infer<typeof SiemMigrationResourceData>;

/**
 * The rule migration resource document object.
 */
export const SiemMigrationResource = lazySchema(() =>
  SiemMigrationResourceBase.merge(SiemMigrationResourceContent.partial()).merge(
    z.object({
      /**
       * The rule resource migration id
       */
      id: NonEmptyString,
      /**
       * The migration id
       */
      migration_id: NonEmptyString,
      /**
       * The moment of the last update
       */
      updated_at: z.string().optional(),
      /**
       * The user who last updated the resource
       */
      updated_by: z.string().optional(),
    })
  )
);
export type SiemMigrationResource = z.infer<typeof SiemMigrationResource>;
