/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: SIEM Rule Migration components
 *   version: not applicable
 */

import { z, lazySchema } from '@kbn/zod/v4';

import { NonEmptyString } from '../../api/model/primitives.gen';
import { Threat } from '../../api/detection_engine/model/rule_schema/common_attributes.gen';
import { RuleResponse } from '../../api/detection_engine/model/rule_schema/rule_schemas.gen';
import {
  MigrationTranslationResult,
  MigrationStatus,
  MigrationComments,
  MigrationTaskStats,
  MigrationLastExecution,
} from './common.gen';

/**
 * The original rule vendor identifier.
 */
export const OriginalRuleVendor = lazySchema(() =>
  z.enum(['splunk', 'qradar', 'microsoft-sentinel'])
);
export type OriginalRuleVendor = z.infer<typeof OriginalRuleVendor>;
export type OriginalRuleVendorEnum = typeof OriginalRuleVendor.enum;
export const OriginalRuleVendorEnum = OriginalRuleVendor.enum;

/**
 * The original rule annotations containing additional information.
 */
export const OriginalRuleAnnotations = lazySchema(() =>
  z
    .object({
      /**
       * The original rule Mitre Attack IDs.
       */
      mitre_attack: z.array(z.string()).optional().describe('The original rule Mitre Attack IDs.'),
    })
    .catchall(z.unknown())
);
export type OriginalRuleAnnotations = z.infer<typeof OriginalRuleAnnotations>;

/**
 * The original rule to migrate.
 */
export const OriginalRule = lazySchema(() =>
  z.object({
    /**
     * The original rule id.
     */
    id: NonEmptyString.describe('The original rule id.'),
    /**
     * The original rule vendor identifier.
     */
    vendor: OriginalRuleVendor.describe('The original rule vendor identifier.'),
    /**
     * The original rule name.
     */
    title: NonEmptyString.describe('The original rule name.'),
    /**
     * The original rule description.
     */
    description: z.string().describe('The original rule description.'),
    /**
     * The original rule query.
     */
    query: z.string().min(1).describe('The original rule query.'),
    /**
     * The original rule query language.
     */
    query_language: z.string().describe('The original rule query language.'),
    /**
     * The original rule annotations containing additional information.
     */
    annotations: OriginalRuleAnnotations.optional().describe(
      'The original rule annotations containing additional information.'
    ),
    /**
     * The original rule's severity or some representation of it.
     */
    severity: z
      .string()
      .optional()
      .describe("The original rule's severity or some representation of it."),
    /**
     * The MITRE ATT&CK threat information for this rule.
     */
    threat: z
      .array(Threat)
      .optional()
      .describe('The MITRE ATT&CK threat information for this rule.'),
  })
);
export type OriginalRule = z.infer<typeof OriginalRule>;

/**
 * The migrated elastic rule.
 */
export const ElasticRule = lazySchema(() =>
  z.object({
    /**
     * The migrated rule title.
     */
    title: z.string().describe('The migrated rule title.'),
    /**
     * The migrated rule description.
     */
    description: z.string().optional().describe('The migrated rule description.'),
    /**
     * The migrated rule severity.
     */
    severity: z.string().optional().describe('The migrated rule severity.'),
    /**
     * The migrated rule risk_score value, integer between 0 and 100.
     */
    risk_score: z
      .number()
      .optional()
      .describe('The migrated rule risk_score value, integer between 0 and 100.'),
    /**
     * The translated elastic query.
     */
    query: z.string().optional().describe('The translated elastic query.'),
    /**
     * The translated elastic query language.
     */
    query_language: z.literal('esql').optional().describe('The translated elastic query language.'),
    /**
     * The Elastic prebuilt rule id matched.
     */
    prebuilt_rule_id: NonEmptyString.nullable()
      .optional()
      .describe('The Elastic prebuilt rule id matched.'),
    /**
     * The IDs of the Elastic integrations suggested to be installed for this rule.
     */
    integration_ids: z
      .array(z.string())
      .optional()
      .describe('The IDs of the Elastic integrations suggested to be installed for this rule.'),
    /**
     * The Elastic rule id installed as a result.
     */
    id: NonEmptyString.optional().describe('The Elastic rule id installed as a result.'),
    /**
     * The MITRE ATT&CK threat information for this rule.
     */
    threat: z
      .array(Threat)
      .optional()
      .describe('The MITRE ATT&CK threat information for this rule.'),
  })
);
export type ElasticRule = z.infer<typeof ElasticRule>;

/**
 * The partial version of the migrated elastic rule.
 */
export const ElasticRulePartial = lazySchema(() => ElasticRule.partial());
export type ElasticRulePartial = z.infer<typeof ElasticRulePartial>;

/**
 * The prebuilt rule version.
 */
export const PrebuiltRuleVersion = lazySchema(() =>
  z.object({
    /**
     * The latest available version of prebuilt rule.
     */
    target: RuleResponse.describe('The latest available version of prebuilt rule.'),
    /**
     * The currently installed version of prebuilt rule.
     */
    current: RuleResponse.optional().describe('The currently installed version of prebuilt rule.'),
  })
);
export type PrebuiltRuleVersion = z.infer<typeof PrebuiltRuleVersion>;

/**
 * The last execution of the rule migration task.
 */
export const RuleMigrationLastExecution = lazySchema(() =>
  MigrationLastExecution.merge(
    z.object({
      /**
       * Indicates if the last execution skipped matching prebuilt rules.
       */
      skip_prebuilt_rules_matching: z
        .boolean()
        .optional()
        .describe('Indicates if the last execution skipped matching prebuilt rules.'),
    })
  )
);
export type RuleMigrationLastExecution = z.infer<typeof RuleMigrationLastExecution>;

/**
 * The rule migration object ( without Id ) with its settings.
 */
export const RuleMigrationData = lazySchema(() =>
  z.object({
    /**
     * The user profile ID of the user who created the migration.
     */
    created_by: NonEmptyString.describe(
      'The user profile ID of the user who created the migration.'
    ),
    /**
     * The moment migration was created
     */
    created_at: NonEmptyString.describe('The moment migration was created'),
    /**
     * The last execution details of a rule migration task.
     */
    last_execution: RuleMigrationLastExecution.optional().describe(
      'The last execution details of a rule migration task.'
    ),
  })
);
export type RuleMigrationData = z.infer<typeof RuleMigrationData>;

/**
 * The rule migration object with its settings.
 */
export const RuleMigration = lazySchema(() =>
  z
    .object({
      /**
       * The rule migration id
       */
      id: NonEmptyString.describe('The rule migration id'),
      /**
       * The rule migration name
       */
      name: NonEmptyString.describe('The rule migration name'),
    })
    .merge(RuleMigrationData)
);
export type RuleMigration = z.infer<typeof RuleMigration>;

/**
 * The rule migration document object.
 */
export const RuleMigrationRuleData = lazySchema(() =>
  z.object({
    /**
     * The moment of creation
     */
    '@timestamp': z.string().describe('The moment of creation'),
    /**
     * The migration id.
     */
    migration_id: NonEmptyString.describe('The migration id.'),
    /**
     * The user profile ID of the user who created the migration.
     */
    created_by: NonEmptyString.describe(
      'The user profile ID of the user who created the migration.'
    ),
    /**
     * The original rule to migrate.
     */
    original_rule: OriginalRule.describe('The original rule to migrate.'),
    /**
     * The migrated elastic rule.
     */
    elastic_rule: ElasticRule.optional().describe('The migrated elastic rule.'),
    /**
     * The rule translation result.
     */
    translation_result: MigrationTranslationResult.optional().describe(
      'The rule translation result.'
    ),
    /**
     * The status of the rule migration process.
     */
    status: MigrationStatus.default('pending').describe(
      'The status of the rule migration process.'
    ),
    /**
     * The comments for the migration including a summary from the LLM in markdown.
     */
    comments: MigrationComments.optional().describe(
      'The comments for the migration including a summary from the LLM in markdown.'
    ),
    /**
     * The moment of the last update
     */
    updated_at: z.string().optional().describe('The moment of the last update'),
    /**
     * The user who last updated the migration
     */
    updated_by: z.string().optional().describe('The user who last updated the migration'),
  })
);
export type RuleMigrationRuleData = z.infer<typeof RuleMigrationRuleData>;

/**
 * The rule migration document object.
 */
export const RuleMigrationRule = lazySchema(() =>
  z
    .object({
      /**
       * The rule migration id
       */
      id: NonEmptyString.describe('The rule migration id'),
    })
    .merge(RuleMigrationRuleData)
);
export type RuleMigrationRule = z.infer<typeof RuleMigrationRule>;

/**
 * The rule migration task stats object.
 */
export const RuleMigrationTaskStats = lazySchema(() =>
  MigrationTaskStats.merge(
    z.object({
      /**
       * The last execution of the rule migration task.
       */
      last_execution: RuleMigrationLastExecution.optional().describe(
        'The last execution of the rule migration task.'
      ),
    })
  )
);
export type RuleMigrationTaskStats = z.infer<typeof RuleMigrationTaskStats>;

/**
 * The rule migration translation stats object.
 */
export const RuleMigrationTranslationStats = lazySchema(() =>
  z.object({
    /**
     * The migration id
     */
    id: NonEmptyString.describe('The migration id'),
    /**
     * The rules migration translation stats.
     */
    rules: z
      .object({
        /**
         * The total number of rules in the migration.
         */
        total: z.number().int().describe('The total number of rules in the migration.'),
        /**
         * The number of rules that have been successfully translated.
         */
        success: z
          .object({
            /**
             * The total number of rules that have been successfully translated.
             */
            total: z
              .number()
              .int()
              .describe('The total number of rules that have been successfully translated.'),
            /**
             * The translation results
             */
            result: z
              .object({
                /**
                 * The number of rules that have been fully translated.
                 */
                full: z
                  .number()
                  .int()
                  .describe('The number of rules that have been fully translated.'),
                /**
                 * The number of rules that have been partially translated.
                 */
                partial: z
                  .number()
                  .int()
                  .describe('The number of rules that have been partially translated.'),
                /**
                 * The number of rules that could not be translated.
                 */
                untranslatable: z
                  .number()
                  .int()
                  .describe('The number of rules that could not be translated.'),
              })
              .describe('The translation results'),
            /**
             * The number of rules that have been successfully translated and can be installed.
             */
            installable: z
              .number()
              .int()
              .describe(
                'The number of rules that have been successfully translated and can be installed.'
              ),
            /**
             * The number of rules that have been successfully translated and matched Elastic prebuilt rules.
             */
            prebuilt: z
              .number()
              .int()
              .describe(
                'The number of rules that have been successfully translated and matched Elastic prebuilt rules.'
              ),
            /**
             * The number of rules that have the placeholder for the missing index pattern in the query.
             */
            missing_index: z
              .number()
              .int()
              .describe(
                'The number of rules that have the placeholder for the missing index pattern in the query.'
              ),
          })
          .describe('The number of rules that have been successfully translated.'),
        /**
         * The number of rules that have failed translation.
         */
        failed: z.number().int().describe('The number of rules that have failed translation.'),
      })
      .describe('The rules migration translation stats.'),
  })
);
export type RuleMigrationTranslationStats = z.infer<typeof RuleMigrationTranslationStats>;

/**
 * The rule migration data object for rule update operation
 */
export const UpdateRuleMigrationRule = lazySchema(() =>
  z.object({
    /**
     * The rule migration id
     */
    id: NonEmptyString.describe('The rule migration id'),
    /**
     * The migrated elastic rule attributes to update.
     */
    elastic_rule: ElasticRulePartial.optional().describe(
      'The migrated elastic rule attributes to update.'
    ),
    /**
     * The comments for the migration including a summary from the LLM in markdown.
     */
    comments: MigrationComments.optional().describe(
      'The comments for the migration including a summary from the LLM in markdown.'
    ),
  })
);
export type UpdateRuleMigrationRule = z.infer<typeof UpdateRuleMigrationRule>;

/**
 * Indicates the filter to retry the migrations rules translation
 */
export const RuleMigrationRetryFilter = lazySchema(() =>
  z.enum(['failed', 'not_fully_translated', 'selected'])
);
export type RuleMigrationRetryFilter = z.infer<typeof RuleMigrationRetryFilter>;
export type RuleMigrationRetryFilterEnum = typeof RuleMigrationRetryFilter.enum;
export const RuleMigrationRetryFilterEnum = RuleMigrationRetryFilter.enum;

/**
 * The migration rules integration stats object.
 */
export const RuleMigrationIntegrationStats = lazySchema(() =>
  z.object({
    /**
     * The integration id
     */
    id: NonEmptyString.describe('The integration id'),
    /**
     * The number of rules that are associated with the integration.
     */
    total_rules: z
      .number()
      .int()
      .describe('The number of rules that are associated with the integration.'),
  })
);
export type RuleMigrationIntegrationStats = z.infer<typeof RuleMigrationIntegrationStats>;

/**
 * The integrations stats objects of all the rule of all the migrations.
 */
export const RuleMigrationAllIntegrationsStats = lazySchema(() =>
  z.array(RuleMigrationIntegrationStats)
);
export type RuleMigrationAllIntegrationsStats = z.infer<typeof RuleMigrationAllIntegrationsStats>;

/**
 * The rule migration task execution settings.
 */
export const RuleMigrationTaskExecutionSettings = lazySchema(() =>
  z.object({
    /**
     * The connector ID used for the last execution.
     */
    connector_id: z.string().describe('The connector ID used for the last execution.'),
    /**
     * Indicates if the current execution should skip matching prebuilt rules.
     */
    skip_prebuilt_rules_matching: z
      .boolean()
      .optional()
      .describe('Indicates if the current execution should skip matching prebuilt rules.'),
  })
);
export type RuleMigrationTaskExecutionSettings = z.infer<typeof RuleMigrationTaskExecutionSettings>;
