[role="xpack"]
[[tines-action-type]]
=== Tines connector
++++
<titleabbrev>Tines</titleabbrev>
++++

The Tines connector uses https://www.tines.com/docs/actions/types/webhook[Webhook actions] to send events via POST request.

[float]
[[tines-connector-configuration]]
==== Connector configuration

Tines connectors have the following configuration properties.

URL::        The Tines Tenant URL. If you are using the <<action-settings, `xpack.actions.allowedHosts`>> setting, make sure the hostname is added to the allowed hosts.
Email::      The email used to sign in to Tines.
API Token::  A Tines API token created by the user. https://www.tines.com/api/authentication#generate-api-token[Docs]

[float]
[[tines-connector-parameters]]
==== Connector parameters

Webhook actions have the following properties.

Story::   The Story to send the events to.
Webhook:: The Webhook action from the previous story that will receive the events, it is the data entry point. 

[float]
[[tines-action-format]]
==== Action format

Tines connector will send the data to Tines in JSON format. 
The message contains execution specific fields, such as `alertId`, `date`, `_index`, `kibanaBaseUrl`, along with the `rule` and `params` objects. 

The number of alerts (signals) can be found at `state.signals_count`.

The alerts (signals) data is stored in the `context.alerts` array, following the https://www.elastic.co/guide/en/ecs/current/ecs-field-reference.html[ECS] format.
