/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

import type { Meta, StoryObj } from '@storybook/react';
import { setUnifiedDocViewerServices } from '@kbn/unified-doc-viewer-plugin/public/plugin';
import { SpanOverview } from './span_overview';

const meta: Meta<typeof SpanOverview> = {
  component: SpanOverview,
};

export default meta;
type Story = StoryObj<typeof SpanOverview>;

const exampleArgs = {
  columns: ['_source'],
  hit: {
    id: '.ds-traces-generic.otel-default-2025.04.10-000001::AZYlBqLkm697I6_zLstq::',
    raw: {
      _index: '.ds-traces-generic.otel-default-2025.04.10-000001',
      _id: 'AZYlBqLkm697I6_zLstq',
      _version: 1,
      _score: null,
      fields: {
        'resource.attributes.telemetry.sdk.name.text': ['opentelemetry'],
        'attributes.rpc.service': ['oteldemo.ProductCatalogService'],
        'scope.name': [
          'go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc',
        ],
        'resource.attributes.telemetry.sdk.name': ['opentelemetry'],
        'process.command_args': ['./product-catalog'],
        'service.language.name': ['go'],
        'transaction.result': ['OK'],
        'resource.attributes.process.runtime.version': ['go1.22.12'],
        'transaction.id': ['2732653ff858d2d6'],
        'attributes.event.success_count': [1],
        'attributes.timestamp.us': [1744377929348540],
        'process.owner': ['root'],
        'telemetry.sdk.language': ['go'],
        'attributes.rpc.grpc.status_code': [0],
        'agent.name': ['opentelemetry/go'],
        'event.outcome': ['success'],
        'scope.attributes.service.framework.name': [
          'go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc',
        ],
        span_id: ['2732653ff858d2d6'],
        'attributes.transaction.duration.us': [124],
        'attributes.transaction.name': ['oteldemo.ProductCatalogService/ListProducts'],
        'transaction.duration.us': [124],
        'resource.attributes.process.executable.path': ['/usr/src/app/product-catalog'],
        'service.runtime.version': ['go1.22.12'],
        'span.id': ['2732653ff858d2d6'],
        'attributes.rpc.method': ['ListProducts'],
        'resource.attributes.telemetry.sdk.version': ['1.35.0'],
        'resource.attributes.process.runtime.description': ['go version go1.22.12 linux/arm64'],
        'transaction.name': ['oteldemo.ProductCatalogService/ListProducts'],
        'scope.attributes.service.framework.version': ['0.60.0'],
        'resource.attributes.service.name': ['product-catalog'],
        'attributes.transaction.representative_count': [1],
        'resource.attributes.process.executable.name': ['product-catalog'],
        'span.name': ['oteldemo.ProductCatalogService/ListProducts'],
        'resource.attributes.agent.version': ['1.35.0'],
        'app.products.count': [10],
        'attributes.transaction.id': ['2732653ff858d2d6'],
        'resource.attributes.os.type': ['linux'],
        'resource.attributes.agent.name': ['opentelemetry/go'],
        'resource.attributes.docker.cli.cobra.command_path': ['docker compose'],
        'process.executable.name': ['product-catalog'],
        'status.code': ['Unset'],
        'transaction.sampled': [true],
        'telemetry.sdk.name': ['opentelemetry'],
        'attributes.transaction.name.text': ['oteldemo.ProductCatalogService/ListProducts'],
        'transaction.root': [false],
        'rpc.grpc.status_code': [0],
        'net.sock.peer.port': [40136],
        'resource.attributes.host.name': ['023f8d5512a8'],
        'attributes.app.products.count': [10],
        'resource.attributes.process.command_args': ['./product-catalog'],
        'docker.cli.cobra.command_path': ['docker compose'],
        'rpc.system': ['grpc'],
        'attributes.net.sock.peer.addr': ['172.20.0.20'],
        '@timestamp': ['2025-04-11T13:25:29.348Z'],
        'host.os.platform': ['linux'],
        'data_stream.dataset': ['generic.otel'],
        'attributes.event.outcome': ['success'],
        'attributes.transaction.type': ['request'],
        'scope.version': ['0.60.0'],
        'resource.attributes.os.description': [
          'Alpine Linux 3.21.3 (Linux 023f8d5512a8 6.10.14-linuxkit #1 SMP Mon Feb 24 16:35:16 UTC 2025 aarch64)',
        ],
        'rpc.service': ['oteldemo.ProductCatalogService'],
        'host.os.full': [
          'Alpine Linux 3.21.3 (Linux 023f8d5512a8 6.10.14-linuxkit #1 SMP Mon Feb 24 16:35:16 UTC 2025 aarch64)',
        ],
        'resource.attributes.agent.name.text': ['opentelemetry/go'],
        'transaction.representative_count': [1],
        'process.runtime.version': ['go1.22.12'],
        'process.pid': [1],
        'process.runtime.name': ['go'],
        'attributes.net.sock.peer.port': [40136],
        'resource.attributes.process.pid': [1],
        'processor.event': ['transaction'],
        'resource.schema_url': ['https://opentelemetry.io/schemas/1.26.0'],
        'host.name': ['023f8d5512a8'],
        'telemetry.sdk.version': ['1.35.0'],
        'attributes.transaction.sampled': [true],
        parent_span_id: ['11161e9ed10e4b42'],
        kind: ['Server'],
        'data_stream.type': ['traces'],
        'timestamp.us': [1744377929348540],
        'process.executable.path': ['/usr/src/app/product-catalog'],
        'resource.attributes.process.owner': ['root'],
        name: ['oteldemo.ProductCatalogService/ListProducts'],
        'agent.version': ['1.35.0'],
        'parent.id': ['11161e9ed10e4b42'],
        'resource.attributes.service.name.text': ['product-catalog'],
        'attributes.rpc.system': ['grpc'],
        'net.sock.peer.addr': ['172.20.0.20'],
        'service.framework.version': ['0.60.0'],
        'os.type': ['linux'],
        'resource.attributes.telemetry.sdk.language': ['go'],
        duration: [124833],
        'attributes.transaction.result': ['OK'],
        'trace.id': ['c116fd52b6ce04a304cb9dabbfc65c47'],
        'event.success_count': [1],
        'os.description': [
          'Alpine Linux 3.21.3 (Linux 023f8d5512a8 6.10.14-linuxkit #1 SMP Mon Feb 24 16:35:16 UTC 2025 aarch64)',
        ],
        'rpc.method': ['ListProducts'],
        'scope.attributes.service.framework.name.text': [
          'go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc',
        ],
        'attributes.transaction.root': [false],
        'process.executable': ['/usr/src/app/product-catalog'],
        'resource.attributes.process.executable.name.text': ['product-catalog'],
        trace_id: ['c116fd52b6ce04a304cb9dabbfc65c47'],
        'service.name': ['product-catalog'],
        'service.framework.name': [
          'go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc',
        ],
        'data_stream.namespace': ['default'],
        'service.runtime.name': ['go'],
        'resource.attributes.process.runtime.name': ['go'],
        'transaction.type': ['request'],
        'attributes.processor.event': ['transaction'],
        'process.runtime.description': ['go version go1.22.12 linux/arm64'],
        'event.dataset': ['generic.otel'],
      },
      highlight: {
        'transaction.id': ['@kibana-highlighted-field@2732653ff858d2d6@/kibana-highlighted-field@'],
        'trace.id': [
          '@kibana-highlighted-field@c116fd52b6ce04a304cb9dabbfc65c47@/kibana-highlighted-field@',
        ],
        trace_id: [
          '@kibana-highlighted-field@c116fd52b6ce04a304cb9dabbfc65c47@/kibana-highlighted-field@',
        ],
        'attributes.processor.event': [
          '@kibana-highlighted-field@transaction@/kibana-highlighted-field@',
        ],
        'attributes.transaction.id': [
          '@kibana-highlighted-field@2732653ff858d2d6@/kibana-highlighted-field@',
        ],
        'processor.event': ['@kibana-highlighted-field@transaction@/kibana-highlighted-field@'],
      },
      sort: ['2025-04-11T13:25:29.348Z', 14930381],
    },
    flattened: {
      '@timestamp': ['2025-04-11T13:25:29.348Z'],
      'agent.name': ['opentelemetry/go'],
      'agent.version': ['1.35.0'],
      'app.products.count': [10],
      'attributes.app.products.count': [10],
      'attributes.event.outcome': ['success'],
      'attributes.event.success_count': [1],
      'attributes.net.sock.peer.addr': ['172.20.0.20'],
      'attributes.net.sock.peer.port': [40136],
      'attributes.processor.event': ['transaction'],
      'attributes.rpc.grpc.status_code': [0],
      'attributes.rpc.method': ['ListProducts'],
      'attributes.rpc.service': ['oteldemo.ProductCatalogService'],
      'attributes.rpc.system': ['grpc'],
      'attributes.timestamp.us': [1744377929348540],
      'attributes.transaction.duration.us': [124],
      'attributes.transaction.id': ['2732653ff858d2d6'],
      'attributes.transaction.name': ['oteldemo.ProductCatalogService/ListProducts'],
      'attributes.transaction.name.text': ['oteldemo.ProductCatalogService/ListProducts'],
      'attributes.transaction.representative_count': [1],
      'attributes.transaction.result': ['OK'],
      'attributes.transaction.root': [false],
      'attributes.transaction.sampled': [true],
      'attributes.transaction.type': ['request'],
      'data_stream.dataset': ['generic.otel'],
      'data_stream.namespace': ['default'],
      'data_stream.type': ['traces'],
      'docker.cli.cobra.command_path': ['docker compose'],
      duration: [124833],
      'event.dataset': ['generic.otel'],
      'event.outcome': ['success'],
      'event.success_count': [1],
      'host.name': ['023f8d5512a8'],
      'host.os.full': [
        'Alpine Linux 3.21.3 (Linux 023f8d5512a8 6.10.14-linuxkit #1 SMP Mon Feb 24 16:35:16 UTC 2025 aarch64)',
      ],
      'host.os.platform': ['linux'],
      kind: ['Server'],
      name: ['oteldemo.ProductCatalogService/ListProducts'],
      'net.sock.peer.addr': ['172.20.0.20'],
      'net.sock.peer.port': [40136],
      'os.description': [
        'Alpine Linux 3.21.3 (Linux 023f8d5512a8 6.10.14-linuxkit #1 SMP Mon Feb 24 16:35:16 UTC 2025 aarch64)',
      ],
      'os.type': ['linux'],
      'parent.id': ['11161e9ed10e4b42'],
      parent_span_id: ['11161e9ed10e4b42'],
      'process.command_args': ['./product-catalog'],
      'process.executable': ['/usr/src/app/product-catalog'],
      'process.executable.name': ['product-catalog'],
      'process.executable.path': ['/usr/src/app/product-catalog'],
      'process.owner': ['root'],
      'process.pid': [1],
      'process.runtime.description': ['go version go1.22.12 linux/arm64'],
      'process.runtime.name': ['go'],
      'process.runtime.version': ['go1.22.12'],
      'processor.event': ['transaction'],
      'resource.attributes.agent.name': ['opentelemetry/go'],
      'resource.attributes.agent.name.text': ['opentelemetry/go'],
      'resource.attributes.agent.version': ['1.35.0'],
      'resource.attributes.docker.cli.cobra.command_path': ['docker compose'],
      'resource.attributes.host.name': ['023f8d5512a8'],
      'resource.attributes.os.description': [
        'Alpine Linux 3.21.3 (Linux 023f8d5512a8 6.10.14-linuxkit #1 SMP Mon Feb 24 16:35:16 UTC 2025 aarch64)',
      ],
      'resource.attributes.os.type': ['linux'],
      'resource.attributes.process.command_args': ['./product-catalog'],
      'resource.attributes.process.executable.name': ['product-catalog'],
      'resource.attributes.process.executable.name.text': ['product-catalog'],
      'resource.attributes.process.executable.path': ['/usr/src/app/product-catalog'],
      'resource.attributes.process.owner': ['root'],
      'resource.attributes.process.pid': [1],
      'resource.attributes.process.runtime.description': ['go version go1.22.12 linux/arm64'],
      'resource.attributes.process.runtime.name': ['go'],
      'resource.attributes.process.runtime.version': ['go1.22.12'],
      'resource.attributes.service.name': ['product-catalog'],
      'resource.attributes.service.name.text': ['product-catalog'],
      'resource.attributes.telemetry.sdk.language': ['go'],
      'resource.attributes.telemetry.sdk.name': ['opentelemetry'],
      'resource.attributes.telemetry.sdk.name.text': ['opentelemetry'],
      'resource.attributes.telemetry.sdk.version': ['1.35.0'],
      'resource.schema_url': ['https://opentelemetry.io/schemas/1.26.0'],
      'rpc.grpc.status_code': [0],
      'rpc.method': ['ListProducts'],
      'rpc.service': ['oteldemo.ProductCatalogService'],
      'rpc.system': ['grpc'],
      'scope.attributes.service.framework.name': [
        'go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc',
      ],
      'scope.attributes.service.framework.name.text': [
        'go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc',
      ],
      'scope.attributes.service.framework.version': ['0.60.0'],
      'scope.name': ['go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc'],
      'scope.version': ['0.60.0'],
      'service.framework.name': [
        'go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc',
      ],
      'service.framework.version': ['0.60.0'],
      'service.language.name': ['go'],
      'service.name': ['product-catalog'],
      'service.runtime.name': ['go'],
      'service.runtime.version': ['go1.22.12'],
      'span.id': ['2732653ff858d2d6'],
      'span.name': ['oteldemo.ProductCatalogService/ListProducts'],
      span_id: ['2732653ff858d2d6'],
      'status.code': ['Unset'],
      'telemetry.sdk.language': ['go'],
      'telemetry.sdk.name': ['opentelemetry'],
      'telemetry.sdk.version': ['1.35.0'],
      'timestamp.us': [1744377929348540],
      'trace.id': ['c116fd52b6ce04a304cb9dabbfc65c47'],
      trace_id: ['c116fd52b6ce04a304cb9dabbfc65c47'],
      'transaction.duration.us': [124],
      'transaction.id': ['2732653ff858d2d6'],
      'transaction.name': ['oteldemo.ProductCatalogService/ListProducts'],
      'transaction.representative_count': [1],
      'transaction.result': ['OK'],
      'transaction.root': [false],
      'transaction.sampled': [true],
      'transaction.type': ['request'],
      _id: 'AZYlBqLkm697I6_zLstq',
      _index: '.ds-traces-generic.otel-default-2025.04.10-000001',
      _score: null,
    },
  },
  transactionIndexPattern: 'traces-apm*,apm-*,traces-*.otel-*,trace,traces',
  parsedDoc: {
    name: 'oteldemo.ProductCatalogService/ListProducts',
    span_id: '2732653ff858d2d6',
    trace_id: 'c116fd52b6ce04a304cb9dabbfc65c47',
    parent_span_id: '11161e9ed10e4b42',
    kind: 'Server',
    '@timestamp': '2025-04-11T13:25:29.348Z',
    'status.code': 'Unset',
    duration: 124833,
  },
};

setUnifiedDocViewerServices({
  core: { application: { capabilities: {} }, notifications: { toasts: { add: () => {} } } },
  share: { url: { locators: { get: () => {} } } },
  data: { query: { timefilter: { timefilter: { getAbsoluteTime: () => 0, getTime: () => 0 } } } },
});

export const Basic: Story = { args: exampleArgs };
