/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Entity Relations Common Schema
 *   version: 1
 */

import { z } from 'zod';

/**
 * The type of the related entities.
 */
export type RelatedEntityType = z.infer<typeof RelatedEntityType>;
export const RelatedEntityType = z.enum(['user', 'host']);
export type RelatedEntityTypeEnum = typeof RelatedEntityType.enum;
export const RelatedEntityTypeEnum = RelatedEntityType.enum;

/**
 * The relation between the entity and the related entity.
 */
export type RelatedEntityRelation = z.infer<typeof RelatedEntityRelation>;
export const RelatedEntityRelation = z.enum(['is_same', 'is_different']);
export type RelatedEntityRelationEnum = typeof RelatedEntityRelation.enum;
export const RelatedEntityRelationEnum = RelatedEntityRelation.enum;

export type EntityRelationRecord = z.infer<typeof EntityRelationRecord>;
export const EntityRelationRecord = z.object({
  entity_type: RelatedEntityType,
  /**
   * The related entity.
   */
  related_entity: z.object({
    /**
     * The ID of the entity.
     */
    id: z.string(),
    /**
     * The name of the entity.
     */
    name: z.string(),
  }),
  relation: RelatedEntityRelation,
  /**
   * The entity.
   */
  entity: z.object({
    name: z.string(),
  }),
});
