/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Read alerts index name API endpoint
 *   version: 2023-10-31
 */

import { z } from '@kbn/zod';

export type ReadAlertsIndexResponse = z.infer<typeof ReadAlertsIndexResponse>;
export const ReadAlertsIndexResponse = z.object({
  name: z.string(),
  index_mapping_outdated: z.boolean().nullable(),
});
