import type { PluginInitializerContext } from '@kbn/core/public';
import { KqlPlugin } from './plugin';
export type { KqlPluginStart, KqlPluginSetup } from './plugin';
export type { QueryStringInputProps } from './components/query_string_input';
export { QueryStringInput } from './components/query_string_input';
export { QueryLanguageSwitcher } from './components/query_string_input/language_switcher';
export { FilterButtonGroup } from './components/query_string_input/filter_button_group';
export { fromUser } from './components/query_string_input/from_user';
export type { QuerySuggestion, QuerySuggestionGetFn, QuerySuggestionGetFnArgs, AutocompleteStart, } from './autocomplete';
export { type SuggestionsAbstraction } from './components/typeahead/suggestions_component';
export type { SuggestionsListSize } from './components/typeahead/suggestions_component';
export { QuerySuggestionTypes } from './autocomplete/providers/query_suggestion_provider';
export declare function plugin(initializerContext: PluginInitializerContext): KqlPlugin;
