/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

export type { AgentBuilderEvent } from './base/events';
export {
  internalNamespaces as toolNamespaces,
  protectedNamespaces as toolReservedNamespaces,
  isInProtectedNamespace,
} from './base/namespaces';
export {
  ToolType,
  type ToolDefinition,
  type ToolDefinitionWithSchema,
  platformCoreTools,
  filestoreTools,
  defaultAgentToolIds,
  editableToolTypes,
  isReservedToolId,
  type ByIdsToolSelection,
  type ToolSelection,
  isByIdsToolSelection,
  toolMatchSelection,
  filterToolsBySelection,
  type ToolSelectionRelevantFields,
  allToolsSelectionWildcard,
  allToolsSelection,
  type EsqlToolConfig,
  type EsqlToolFieldTypes,
  type EsqlToolParam,
  type EsqlToolParamValue,
  type EsqlToolDefinition,
  type EsqlToolDefinitionWithSchema,
  EsqlToolFieldType,
  toolIdRegexp,
  toolIdMaxLength,
  activeToolsCountWarningThreshold,
  validateToolId,
  ToolResultType,
  type ToolResult,
  type ErrorResult,
  type QueryResult,
  type ResourceResult,
  type EsqlResults,
  type OtherResult,
  type IndexSearchToolDefinitionWithSchema,
  type BrowserApiToolMetadata,
} from './tools';
export {
  AgentBuilderErrorCode,
  AgentBuilderErrorUtils,
  isInternalError,
  isToolNotFoundError,
  isAgentBuilderError,
  isAgentNotFoundError,
  isConversationNotFoundError,
  isBadRequestError,
  isRequestAbortedError,
  isAgentExecutionError,
  isContextLengthExceededAgentError,
  createAgentBuilderError,
  createInternalError,
  createToolNotFoundError,
  createAgentNotFoundError,
  createConversationNotFoundError,
  createBadRequestError,
  createRequestAbortedError,
  type AgentBuilderError,
  type AgentBuilderInternalError,
  type AgentBuilderToolNotFoundError,
  type AgentBuilderAgentNotFoundError,
  type AgentBuilderConversationNotFoundError,
  type AgentBuilderBadRequestError,
  type AgentBuilderRequestAbortedError,
  type AgentBuilderAgentExecutionError,
  type AgentBuilderHooksExecutionError,
  type SerializedAgentBuilderError,
  isHooksExecutionError,
  createHooksExecutionError,
} from './base/errors';
export { HookLifecycle, HookExecutionMode } from './hooks/lifecycle';
export { type UserIdAndName } from './base/users';
export { EsResourceType } from './base/resources';
export {
  agentBuilderDefaultAgentId,
  AgentType,
  AgentExecutionErrorCode,
  type AgentDefinition,
  type AgentConfiguration,
  type AgentConfigurationOverrides,
  type RuntimeAgentConfigurationOverrides,
  type AgentCapabilities,
  type ResolvedAgentCapabilities,
  type AgentAnswerStepConfiguration,
  type AgentResearchStepConfiguration,
  agentIdRegexp,
} from './agents';
export {
  type RoundInput,
  type ConverseInput,
  type AssistantResponse,
  type ToolCallWithResult,
  type ConversationRound,
  type Conversation,
  type ConversationWithoutRounds,
  type ToolCallStep,
  type ConversationRoundStep,
  type ReasoningStepData,
  type ReasoningStep,
  type RoundModelUsageStats,
  ConversationRoundStepType,
  isToolCallStep,
  isReasoningStep,
  ChatEventType,
  ConversationRoundStatus,
  type ChatEventBase,
  type ChatEvent,
  type ConversationAction,
  type ConversationCreatedEvent,
  type ConversationCreatedEventData,
  type ConversationUpdatedEvent,
  type ConversationUpdatedEventData,
  type ConversationIdSetEvent,
  type ConversationIdSetEventData,
  type ChatAgentEvent,
  type ToolProgressEvent,
  type ToolProgressEventData,
  type ToolUiEventData,
  type ToolUiEvent,
  type ToolResultEvent,
  type ToolResultEventData,
  type ToolCallEvent,
  type ToolCallEventData,
  type BrowserToolCallEvent,
  type BrowserToolCallEventData,
  type ReasoningEvent,
  type ReasoningEventData,
  type MessageChunkEventData,
  type MessageChunkEvent,
  type MessageCompleteEventData,
  type MessageCompleteEvent,
  type ThinkingCompleteEventData,
  type ThinkingCompleteEvent,
  type RoundCompleteEventData,
  type RoundCompleteEvent,
  type ToolCallProgress,
  isToolCallEvent,
  isBrowserToolCallEvent,
  isToolResultEvent,
  isToolUiEvent,
  isReasoningEvent,
  isMessageChunkEvent,
  isMessageCompleteEvent,
  isThinkingCompleteEvent,
  isRoundCompleteEvent,
  isConversationCreatedEvent,
  isConversationUpdatedEvent,
  isToolProgressEvent,
  isPromptRequestEvent,
} from './chat';
export * from './telemetry';
export { getLatestVersion, type VersionedAttachment } from './attachments';
