/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

export type { AgentBuilderEvent } from './base/events';
export {
  internalNamespaces as toolNamespaces,
  protectedNamespaces as toolReservedNamespaces,
  isInProtectedNamespace,
} from './base/namespaces';
export { DOT_INDEX_ALLOW_LIST_PATTERNS, isVisibleSearchSource } from './base/dot_index_allow_list';
export {
  ToolType,
  ToolOrigin,
  type ToolDefinition,
  type ToolDefinitionWithSchema,
  platformCoreTools,
  platformCoreCasesTools,
  platformSignificantEventsTools,
  attachmentTools,
  internalTools,
  defaultAgentToolIds,
  editableToolTypes,
  isReservedToolId,
  type ByIdsToolSelection,
  type ToolSelection,
  isByIdsToolSelection,
  toolMatchSelection,
  filterToolsBySelection,
  type ToolSelectionRelevantFields,
  allToolsSelectionWildcard,
  allToolsSelection,
  type EsqlToolConfig,
  type EsqlToolFieldTypes,
  type EsqlToolParam,
  type EsqlToolParamValue,
  type EsqlToolDefinition,
  type EsqlToolDefinitionWithSchema,
  EsqlToolFieldType,
  toolIdRegexp,
  toolIdMaxLength,
  activeToolsCountWarningThreshold,
  validateToolId,
  ToolResultType,
  type ToolResult,
  type ErrorResult,
  type QueryResult,
  type ResourceResult,
  type EsqlResults,
  type OtherResult,
  type IndexSearchToolDefinitionWithSchema,
  type BrowserApiToolMetadata,
} from './tools';
export {
  AgentBuilderErrorCode,
  AgentBuilderErrorUtils,
  isInternalError,
  isToolNotFoundError,
  isSkillNotFoundError,
  isAgentBuilderError,
  isAgentNotFoundError,
  isAgentUnavailableError,
  isConversationNotFoundError,
  isPluginNotFoundError,
  isBadRequestError,
  isRequestAbortedError,
  isWorkflowAbortedError,
  isWorkflowExecutionError,
  isAgentExecutionError,
  isContextLengthExceededAgentError,
  createAgentBuilderError,
  createInternalError,
  createToolNotFoundError,
  createSkillNotFoundError,
  createAgentNotFoundError,
  createAgentUnavailableError,
  createConversationNotFoundError,
  createPluginNotFoundError,
  createBadRequestError,
  createRequestAbortedError,
  createWorkflowAbortedError,
  createWorkflowExecutionError,
  type AgentBuilderError,
  type AgentBuilderInternalError,
  type AgentBuilderToolNotFoundError,
  type AgentBuilderSkillNotFoundError,
  type AgentBuilderAgentNotFoundError,
  type AgentBuilderAgentUnavailableError,
  type AgentBuilderConversationNotFoundError,
  type AgentBuilderPluginNotFoundError,
  type AgentBuilderBadRequestError,
  type AgentBuilderRequestAbortedError,
  type AgentBuilderWorkflowAbortedError,
  type AgentBuilderWorkflowExecutionError,
  type AgentBuilderAgentExecutionError,
  type AgentBuilderHooksExecutionError,
  type SerializedAgentBuilderError,
  isHooksExecutionError,
  createHooksExecutionError,
} from './base/errors';
export { HookLifecycle, HookExecutionMode } from './hooks/lifecycle';
export { type UserIdAndName, type CurrentUser } from './base/users';
export { EsResourceType } from './base/resources';
export type { TimeRange } from './attachments';
export {
  agentBuilderDefaultAgentId,
  AgentType,
  chatAgentTypeId,
  AgentAccessControlMode,
  ACCESS_CONTROL_MODE_ICON,
  ACCESS_CONTROL_MODE_BADGE_COLOR,
  AgentExecutionErrorCode,
  AgentAccessControlRole,
  AGENT_ACCESS_CONTROL_MAX_ENTRIES,
  AGENT_ACCESS_CONTROL_PRINCIPAL_NAME_MAX_LENGTH,
  isAgentAccessControlRole,
  accessControlRoleMeets,
  maxAccessControlRole,
  getDefaultAgentAccessControl,
  type AgentAccessControl,
  type AgentAccessControlEntry,
  type AgentAccessControlPrincipalType,
  type AgentDefinition,
  type AgentConfiguration,
  type AgentConfigurationOverrides,
  type RuntimeAgentConfigurationOverrides,
  type AgentCapabilities,
  type ResolvedAgentCapabilities,
  agentIdRegexp,
  AgentExecutionMode,
  SubagentExecutionMode,
  ExecutionStatus,
  type SerializedExecutionError,
  type AgentListOptions,
  type AgentCreateRequest,
  type AgentUpdateRequest,
  type AgentDeleteRequest,
} from './agents';
export {
  ConversationAccessControlMode,
  getDefaultConversationAccessControl,
  type RoundInput,
  type ConverseInput,
  type AssistantResponse,
  type ConversationAccessControl,
  type ToolCallWithResult,
  type ConversationRound,
  type Conversation,
  type ConversationSource,
  type ConversationWithoutRounds,
  type ToolCallStep,
  type ConversationRoundStep,
  type ReasoningStepData,
  type ReasoningStep,
  type CompactionStepData,
  type CompactionStep,
  type RoundModelUsageStats,
  type CompactionSummary,
  type CompactionStructuredData,
  type CompactionToolCallSummary,
  type CompactionEntity,
  ConversationRoundStepType,
  ConversationSourceType,
  isToolCallStep,
  isReasoningStep,
  isCompactionStep,
  isBackgroundAgentCompleteStep,
  type BackgroundAgentCompleteStep,
  isTodosStep,
  findTodosStep,
  type TodosStep,
  carriedOverTodos,
  ChatEventType,
  ConversationRoundStatus,
  ConversationDisplayStatus,
  type ChatEventBase,
  type ChatEvent,
  type ConversationAction,
  type ConversationCreatedEvent,
  type ConversationCreatedEventData,
  type ConversationUpdatedEvent,
  type ConversationUpdatedEventData,
  type ConversationIdSetEvent,
  type ConversationIdSetEventData,
  type ChatAgentEvent,
  type ToolProgressEvent,
  type ToolProgressEventData,
  type ToolUiEventData,
  type ToolUiEvent,
  type ToolResultEvent,
  type ToolResultEventData,
  type ToolCallEvent,
  type ToolCallEventData,
  type BrowserToolCallEvent,
  type BrowserToolCallEventData,
  type ReasoningEvent,
  type ReasoningEventData,
  type MessageChunkEventData,
  type MessageChunkEvent,
  type MessageCompleteEventData,
  type MessageCompleteEvent,
  type ThinkingCompleteEventData,
  type ThinkingCompleteEvent,
  type RoundCompleteEventData,
  type RoundCompleteEvent,
  type ToolCallProgress,
  isToolCallEvent,
  isBrowserToolCallEvent,
  isToolResultEvent,
  isToolUiEvent,
  isReasoningEvent,
  isMessageChunkEvent,
  isMessageCompleteEvent,
  isThinkingCompleteEvent,
  isRoundCompleteEvent,
  isConversationCreatedEvent,
  isConversationUpdatedEvent,
  isToolProgressEvent,
  isPromptRequestEvent,
  type CompactionStartedEvent,
  type CompactionStartedEventData,
  type CompactionCompletedEvent,
  type CompactionCompletedEventData,
  isCompactionStartedEvent,
  isCompactionCompletedEvent,
  type BackgroundAgentCompleteEvent,
  type BackgroundAgentCompleteEventData,
  isBackgroundAgentCompleteEvent,
  isTodosUpdatedEvent,
  TODOS_UPDATED_UI_EVENT,
  type TodosUpdatedUiEventData,
  type AskUserQuestionStep,
  type AskUserQuestionStepData,
  createAskUserQuestionStep,
  isAskUserQuestionStep,
  type UserQuestionAskedEvent,
  type UserQuestionAskedEventData,
  type UserQuestionAnsweredEvent,
  type UserQuestionAnsweredEventData,
  isUserQuestionAskedEvent,
  isUserQuestionAnsweredEvent,
  createUserQuestionAskedEvent,
  createUserQuestionAnsweredEvent,
  type ConversationListOptions,
} from './chat';
export {
  type PublicSkillDefinition,
  type PublicSkillSummary,
  type PersistedSkillCreateRequest,
  type PersistedSkillUpdateRequest,
  type SkillReferencedContent,
  skillCreateRequestSchema,
  skillUpdateRequestSchema,
  validateSkillId,
  skillIdMaxLength,
  skillNameMaxLength,
  skillIdRegexp,
  skillNameRegexp,
  maxToolsPerSkill,
  maxReferencedContentItems,
  normalizeRelativePathSegments,
  isRootRelativePath,
  canComputeReferencedContentUniquenessKey,
  REFERENCED_CONTENT_REFINE_ISSUE_CODE,
  type ReferencedContentRefineIssueCode,
  type ReferencedContentRefineIssue,
  collectReferencedContentRefineIssues,
} from './skills';
export * from './telemetry';
export {
  getLatestVersion,
  type VersionedAttachment,
  type UpdateOriginResponse,
} from './attachments';
export {
  type PluginManifestAuthor,
  type PluginManifest,
  type ParsedSkillMeta,
  type ParsedSkillFile,
  type ParsedSkillReferencedFile,
  type UnmanagedPluginAssets,
  type ParsedPluginArchive,
  type PluginManifestMetadata,
  type PluginDefinition,
} from './plugins';
export type { RendererDefinition, RendererPayloadOf } from './renderers';
export type { WorkspaceFileContent } from './workspaces';
export { EffortLevels, type EffortLevel } from './model_provider';
export {
  type OAuthClient,
  type OAuthClientLogo,
  type OAuthClientConnectionsSummary,
  OAuthClientType,
} from './oauth_clients';
export { MCP_SERVER_PATH } from './mcp';
