/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */
import uuid from 'uuid';
// eslint-disable-next-line @kbn/eslint/no-restricted-paths
import { EventAction, ProcessEvent, EventKind } from '../../public/hooks/use_process_tree';

export const getStart = () => {
  return [
    {
      '@timestamp': new Date('Thu Oct 14 2021 12: 06: 48 GMT-0700 (Pacific Daylight Time)'),
      event: {
        kind: 'event',
        category: 'process',
        action: EventAction.exec,
      },
      process: {
        args: ['bash'],
        args_count: 1,
        command_line: 'bash',
        entity_id: '4321',
        executable: '/bin/bash',
        name: 'bash',
        interactive: true,
        working_directory: '/home/kg',
        pid: 3,
        pgid: 2,

        user: {
          id: '2',
          name: 'kg',
        },

        parent: {
          args: ['/bin/sshd'],
          args_count: 1,
          command_line: 'sshd',
          entity_id: '4322',
          executable: '/bin/sshd',
          name: 'sshd',
          interactive: true,
          working_directory: '/',
          pid: 2,
          pgid: 2,
          user: {
            id: '0',
            name: 'root',
          },
        },
        session: {
          args: ['bash'],
          args_count: 1,
          command_line: 'bash',
          entity_id: '4321',
          executable: '/bin/bash',
          name: 'bash',
          interactive: true,
          working_directory: '/home/kg',
          pid: 3,
          pgid: 2,
          user: {
            id: '2',
            name: 'kg',
          },
        },
        entry: {
          args: ['bash'],
          args_count: 1,
          command_line: 'bash',
          entity_id: '4321',
          executable: '/bin/bash',
          name: 'bash',
          interactive: true,
          working_directory: '/home/kg',
          pid: 3,
          pgid: 2,
          user: {
            id: '2',
            name: 'kg',
          },
        },
      },
    },
  ];
};

export const getEvent = () => {
  const random = [
    {
      args: ['ls', '-l'],
      command_line: 'ls -l',
      name: 'ls',
    },
    {
      args: ['pwd'],
      command_line: 'pwd',
      name: 'pwd',
    },
    {
      args: ['dir'],
      command_line: 'dir',
      name: 'dir',
    },
  ];

  const randomElement = random[Math.floor(Math.random() * random.length)];

  return [
    {
      '@timestamp': new Date('Thu Oct 14 2021 12: 06: 52 GMT-0700 (Pacific Daylight Time)'),
      event: {
        kind: 'event',
        category: 'process',
        action: EventAction.exec,
      },
      process: {
        args: randomElement.args,
        args_count: 2,
        command_line: randomElement.command_line,
        entity_id: uuid.v4().toString(),
        executable: '/bin/ls',
        name: randomElement.name,
        interactive: true,
        working_directory: '/home/kg',
        pid: 4,
        pgid: 3,
        user: {
          id: '2',
          name: 'kg',
        },
        parent: {
          args: ['bash'],
          args_count: 1,
          command_line: 'bash',
          entity_id: '4321',
          executable: '/bin/bash',
          name: 'bash',
          interactive: true,
          working_directory: '/home/kg',
          pid: 3,
          pgid: 2,
          user: {
            id: '2',
            name: 'kg',
          },
        },
        session: {
          args: ['bash'],
          args_count: 1,
          command_line: 'bash',
          entity_id: '4321',
          executable: '/bin/bash',
          name: 'bash',
          interactive: true,
          working_directory: '/home/kg',
          pid: 3,
          pgid: 2,
          user: {
            id: '2',
            name: 'kg',
          },
        },
        entry: {
          args: ['bash'],
          args_count: 1,
          command_line: 'bash',
          entity_id: '4321',
          executable: '/bin/bash',
          name: 'bash',
          interactive: true,
          working_directory: '/home/kg',
          pid: 3,
          pgid: 2,
          user: {
            id: '2',
            name: 'kg',
          },
        },
      },
    },
  ];
};

export const getEnd = () => {
  return [
    {
      '@timestamp': new Date('Thu Oct 14 2021 12: 07: 52 GMT-0700 (Pacific Daylight Time)'),
      event: {
        kind: 'event',
        category: 'process',
        action: EventAction.exec,
      },
      process: {
        args: ['df'],
        args_count: 1,
        command_line: 'df',
        entity_id: '12345',
        executable: '/bin/df',
        name: 'df',
        interactive: true,
        working_directory: '/home/kg',
        pid: 5,
        pgid: 4,
        user: {
          id: '2',
          name: 'kg',
        },
        parent: {
          args: ['bash'],
          args_count: 1,
          command_line: 'bash',
          entity_id: '4321',
          executable: '/bin/bash',
          name: 'bash',
          interactive: true,
          working_directory: '/home/kg',
          pid: 3,
          pgid: 2,
          user: {
            id: '2',
            name: 'kg',
          },
        },
        session: {
          args: ['bash'],
          args_count: 1,
          command_line: 'bash',
          entity_id: '4321',
          executable: '/bin/bash',
          name: 'bash',
          interactive: true,
          working_directory: '/home/kg',
          pid: 3,
          pgid: 2,
          user: {
            id: '2',
            name: 'kg',
          },
        },
        entry: {
          args: ['bash'],
          args_count: 1,
          command_line: 'bash',
          entity_id: '4321',
          executable: '/bin/bash',
          name: 'bash',
          interactive: true,
          working_directory: '/home/kg',
          pid: 3,
          pgid: 2,
          user: {
            id: '2',
            name: 'kg',
          },
        },
      },
    },
    {
      '@timestamp': new Date('Thu Oct 14 2021 12: 07: 56 GMT-0700 (Pacific Daylight Time)'),
      event: {
        kind: 'event',
        category: 'process',
        action: EventAction.fork,
      },
      process: {
        args: ['df', 'nested'],
        args_count: 2,
        command_line: 'df nested',
        entity_id: '123456',
        executable: '/bin/df',
        name: 'df',
        interactive: true,
        working_directory: '/home/kg',
        pid: 6,
        pgid: 4,

        user: {
          id: '2',
          name: 'kg',
        },

        parent: {
          args: ['df'],
          args_count: 1,
          command_line: 'df',
          entity_id: '12345',
          executable: '/bin/df',
          name: 'df',
          interactive: true,
          working_directory: '/home/kg',
          pid: 5,
          pgid: 4,
          user: {
            id: '2',
            name: 'kg',
          },
        },
        session: {
          args: ['bash'],
          args_count: 1,
          command_line: 'bash',
          entity_id: '4321',
          executable: '/bin/bash',
          name: 'bash',
          interactive: true,
          working_directory: '/home/kg',
          pid: 3,
          pgid: 2,
          user: {
            id: '2',
            name: 'kg',
          },
        },
        entry: {
          args: ['bash'],
          args_count: 1,
          command_line: 'bash',
          entity_id: '4321',
          executable: '/bin/bash',
          name: 'bash',
          interactive: true,
          working_directory: '/home/kg',
          pid: 3,
          pgid: 2,
          user: {
            id: '2',
            name: 'kg',
          },
        },
      },
    },
    {
      '@timestamp': new Date('Thu Oct 14 2021 12: 07: 56 GMT-0700 (Pacific Daylight Time)'),
      event: {
        kind: 'event',
        category: 'process',
        action: EventAction.exec,
      },
      process: {
        args: ['df', 'nested'],
        args_count: 2,
        command_line: 'df nested',
        entity_id: '123456',
        executable: '/bin/df',
        name: 'df',
        interactive: true,
        working_directory: '/home/kg',
        pid: 6,
        pgid: 4,

        user: {
          id: '2',
          name: 'kg',
        },

        parent: {
          args: ['df'],
          args_count: 1,
          command_line: 'df',
          entity_id: '12345',
          executable: '/bin/df',
          name: 'df',
          interactive: true,
          working_directory: '/home/kg',
          pid: 5,
          pgid: 4,
          user: {
            id: '2',
            name: 'kg',
          },
        },
        session: {
          args: ['bash'],
          args_count: 1,
          command_line: 'bash',
          entity_id: '4321',
          executable: '/bin/bash',
          name: 'bash',
          interactive: true,
          working_directory: '/home/kg',
          pid: 3,
          pgid: 2,
          user: {
            id: '2',
            name: 'kg',
          },
        },
        entry: {
          args: ['bash'],
          args_count: 1,
          command_line: 'bash',
          entity_id: '4321',
          executable: '/bin/bash',
          name: 'bash',
          interactive: true,
          working_directory: '/home/kg',
          pid: 3,
          pgid: 2,
          user: {
            id: '2',
            name: 'kg',
          },
        },
      },
    },
    {
      '@timestamp': new Date('Thu Oct 14 2021 12: 08: 56 GMT-0700 (Pacific Daylight Time)'),
      event: {
        kind: 'event',
        category: 'process',
        action: EventAction.exit,
      },
      process: {
        args: ['df', 'nested'],
        args_count: 2,
        command_line: 'df nested',
        entity_id: '123456',
        executable: '/bin/df',
        name: 'df',
        interactive: true,
        working_directory: '/home/kg',
        pid: 6,
        pgid: 4,
        end: 'Thu Oct 14 2021 12: 08: 56 GMT-0700 (Pacific Daylight Time)',
        exit_code: 137,

        user: {
          id: '2',
          name: 'kg',
        },

        parent: {
          args: ['df'],
          args_count: 1,
          command_line: 'df',
          entity_id: '12345',
          executable: '/bin/df',
          name: 'df',
          interactive: true,
          working_directory: '/home/kg',
          pid: 5,
          pgid: 4,
          user: {
            id: '2',
            name: 'kg',
          },
        },
        session: {
          args: ['bash'],
          args_count: 1,
          command_line: 'bash',
          entity_id: '4321',
          executable: '/bin/bash',
          name: 'bash',
          interactive: true,
          working_directory: '/home/kg',
          pid: 3,
          pgid: 2,
          user: {
            id: '2',
            name: 'kg',
          },
        },
        entry: {
          args: ['bash'],
          args_count: 1,
          command_line: 'bash',
          entity_id: '4321',
          executable: '/bin/bash',
          name: 'bash',
          interactive: true,
          working_directory: '/home/kg',
          pid: 3,
          pgid: 2,
          user: {
            id: '2',
            name: 'kg',
          },
        },
      },
    },
  ];
};

export const mockData: ProcessEvent[] = [
  {
    '@timestamp': new Date('Thu Oct 14 2021 12: 06: 48 GMT-0700 (Pacific Daylight Time)'),
    event: {
      kind: EventKind.event,
      category: 'process',
      action: EventAction.exec,
    },
    process: {
      args: ['bash'],
      args_count: 1,
      command_line: 'bash',
      entity_id: '4321',
      executable: '/bin/bash',
      name: 'bash',
      interactive: true,
      working_directory: '/home/kg',
      pid: 3,
      pgid: 2,

      user: {
        id: '2',
        name: 'kg',
      },

      parent: {
        args: ['/bin/sshd'],
        args_count: 1,
        command_line: 'sshd',
        entity_id: '4322',
        executable: '/bin/sshd',
        name: 'sshd',
        interactive: true,
        working_directory: '/',
        pid: 2,
        pgid: 2,
        user: {
          id: '0',
          name: 'root',
        },
      },
      session: {
        args: ['bash'],
        args_count: 1,
        command_line: 'bash',
        entity_id: '4321',
        executable: '/bin/bash',
        name: 'bash',
        interactive: true,
        working_directory: '/home/kg',
        pid: 3,
        pgid: 2,
        user: {
          id: '2',
          name: 'kg',
        },
      },
      entry: {
        args: ['bash'],
        args_count: 1,
        command_line: 'bash',
        entity_id: '4321',
        executable: '/bin/bash',
        name: 'bash',
        interactive: true,
        working_directory: '/home/kg',
        pid: 3,
        pgid: 2,
        user: {
          id: '2',
          name: 'kg',
        },
      },
    },
  },
  {
    '@timestamp': new Date('Thu Oct 14 2021 12: 06: 52 GMT-0700 (Pacific Daylight Time)'),
    event: {
      kind: EventKind.event,
      category: 'process',
      action: EventAction.exec,
    },
    process: {
      args: ['ls', '-l'],
      args_count: 2,
      command_line: 'ls -l',
      entity_id: '1234',
      executable: '/bin/ls',
      name: 'ls',
      interactive: true,
      working_directory: '/home/kg',
      pid: 4,
      pgid: 3,
      user: {
        id: '2',
        name: 'kg',
      },
      parent: {
        args: ['bash'],
        args_count: 1,
        command_line: 'bash',
        entity_id: '4321',
        executable: '/bin/bash',
        name: 'bash',
        interactive: true,
        working_directory: '/home/kg',
        pid: 3,
        pgid: 2,
        user: {
          id: '2',
          name: 'kg',
        },
      },
      session: {
        args: ['bash'],
        args_count: 1,
        command_line: 'bash',
        entity_id: '4321',
        executable: '/bin/bash',
        name: 'bash',
        interactive: true,
        working_directory: '/home/kg',
        pid: 3,
        pgid: 2,
        user: {
          id: '2',
          name: 'kg',
        },
      },
      entry: {
        args: ['bash'],
        args_count: 1,
        command_line: 'bash',
        entity_id: '4321',
        executable: '/bin/bash',
        name: 'bash',
        interactive: true,
        working_directory: '/home/kg',
        pid: 3,
        pgid: 2,
        user: {
          id: '2',
          name: 'kg',
        },
      },
    },
  },
  {
    '@timestamp': new Date('Thu Oct 14 2021 12: 07: 52 GMT-0700 (Pacific Daylight Time)'),
    event: {
      kind: EventKind.event,
      category: 'process',
      action: EventAction.exec,
    },
    process: {
      args: ['df'],
      args_count: 1,
      command_line: 'df',
      entity_id: '12345',
      executable: '/bin/df',
      name: 'df',
      interactive: true,
      working_directory: '/home/kg',
      pid: 5,
      pgid: 4,
      user: {
        id: '2',
        name: 'kg',
      },
      parent: {
        args: ['bash'],
        args_count: 1,
        command_line: 'bash',
        entity_id: '4321',
        executable: '/bin/bash',
        name: 'bash',
        interactive: true,
        working_directory: '/home/kg',
        pid: 3,
        pgid: 2,
        user: {
          id: '2',
          name: 'kg',
        },
      },
      session: {
        args: ['bash'],
        args_count: 1,
        command_line: 'bash',
        entity_id: '4321',
        executable: '/bin/bash',
        name: 'bash',
        interactive: true,
        working_directory: '/home/kg',
        pid: 3,
        pgid: 2,
        user: {
          id: '2',
          name: 'kg',
        },
      },
      entry: {
        args: ['bash'],
        args_count: 1,
        command_line: 'bash',
        entity_id: '4321',
        executable: '/bin/bash',
        name: 'bash',
        interactive: true,
        working_directory: '/home/kg',
        pid: 3,
        pgid: 2,
        user: {
          id: '2',
          name: 'kg',
        },
      },
    },
  },
  {
    '@timestamp': new Date('Thu Oct 14 2021 12: 07: 56 GMT-0700 (Pacific Daylight Time)'),
    event: {
      kind: EventKind.event,
      category: 'process',
      action: EventAction.fork,
    },
    process: {
      args: ['df', 'nested'],
      args_count: 2,
      command_line: 'df nested',
      entity_id: '123456',
      executable: '/bin/df',
      name: 'df',
      interactive: true,
      working_directory: '/home/kg',
      pid: 6,
      pgid: 4,

      user: {
        id: '2',
        name: 'kg',
      },

      parent: {
        args: ['df'],
        args_count: 1,
        command_line: 'df',
        entity_id: '12345',
        executable: '/bin/df',
        name: 'df',
        interactive: true,
        working_directory: '/home/kg',
        pid: 5,
        pgid: 4,
        user: {
          id: '2',
          name: 'kg',
        },
      },
      session: {
        args: ['bash'],
        args_count: 1,
        command_line: 'bash',
        entity_id: '4321',
        executable: '/bin/bash',
        name: 'bash',
        interactive: true,
        working_directory: '/home/kg',
        pid: 3,
        pgid: 2,
        user: {
          id: '2',
          name: 'kg',
        },
      },
      entry: {
        args: ['bash'],
        args_count: 1,
        command_line: 'bash',
        entity_id: '4321',
        executable: '/bin/bash',
        name: 'bash',
        interactive: true,
        working_directory: '/home/kg',
        pid: 3,
        pgid: 2,
        user: {
          id: '2',
          name: 'kg',
        },
      },
    },
  },
  {
    '@timestamp': new Date('Thu Oct 14 2021 12: 07: 56 GMT-0700 (Pacific Daylight Time)'),
    event: {
      kind: EventKind.event,
      category: 'process',
      action: EventAction.exec,
    },
    process: {
      args: ['df', 'nested'],
      args_count: 2,
      command_line: 'df nested',
      entity_id: '123456',
      executable: '/bin/df',
      name: 'df',
      interactive: true,
      working_directory: '/home/kg',
      pid: 6,
      pgid: 4,

      user: {
        id: '2',
        name: 'kg',
      },

      parent: {
        args: ['df'],
        args_count: 1,
        command_line: 'df',
        entity_id: '12345',
        executable: '/bin/df',
        name: 'df',
        interactive: true,
        working_directory: '/home/kg',
        pid: 5,
        pgid: 4,
        user: {
          id: '2',
          name: 'kg',
        },
      },
      session: {
        args: ['bash'],
        args_count: 1,
        command_line: 'bash',
        entity_id: '4321',
        executable: '/bin/bash',
        name: 'bash',
        interactive: true,
        working_directory: '/home/kg',
        pid: 3,
        pgid: 2,
        user: {
          id: '2',
          name: 'kg',
        },
      },
      entry: {
        args: ['bash'],
        args_count: 1,
        command_line: 'bash',
        entity_id: '4321',
        executable: '/bin/bash',
        name: 'bash',
        interactive: true,
        working_directory: '/home/kg',
        pid: 3,
        pgid: 2,
        user: {
          id: '2',
          name: 'kg',
        },
      },
    },
  },
  {
    '@timestamp': new Date('Thu Oct 14 2021 12: 08: 56 GMT-0700 (Pacific Daylight Time)'),
    event: {
      kind: EventKind.event,
      category: 'process',
      action: EventAction.exit,
    },
    process: {
      args: ['df', 'nested'],
      args_count: 2,
      command_line: 'df nested',
      entity_id: '123456',
      executable: '/bin/df',
      name: 'df',
      interactive: true,
      working_directory: '/home/kg',
      pid: 6,
      pgid: 4,
      end: 'Thu Oct 14 2021 12: 08: 56 GMT-0700 (Pacific Daylight Time)',
      exit_code: 137,

      user: {
        id: '2',
        name: 'kg',
      },

      parent: {
        args: ['df'],
        args_count: 1,
        command_line: 'df',
        entity_id: '12345',
        executable: '/bin/df',
        name: 'df',
        interactive: true,
        working_directory: '/home/kg',
        pid: 5,
        pgid: 4,
        user: {
          id: '2',
          name: 'kg',
        },
      },
      session: {
        args: ['bash'],
        args_count: 1,
        command_line: 'bash',
        entity_id: '4321',
        executable: '/bin/bash',
        name: 'bash',
        interactive: true,
        working_directory: '/home/kg',
        pid: 3,
        pgid: 2,
        user: {
          id: '2',
          name: 'kg',
        },
      },
      entry: {
        args: ['bash'],
        args_count: 1,
        command_line: 'bash',
        entity_id: '4321',
        executable: '/bin/bash',
        name: 'bash',
        interactive: true,
        working_directory: '/home/kg',
        pid: 3,
        pgid: 2,
        user: {
          id: '2',
          name: 'kg',
        },
      },
    },
  },
];
