[[something-good]]
= 

[partintro]
--
The easiest way to "get started" with {kib} is to use our {es} Service. The Elasticsearch Service is available on AWS, GCP, and Azure, and automatically configures {kib} to work with {es}.

[float]
[[hosted-elasticsearch-service]]
== Hosted {es} Service

Skip managing your own Kibana installation by using our hosted Elasticsearch Service on Elastic Cloud.

//[insert image]

Try out the Elasticsearch Service for free, and then begin configuring your own user settings right in the Elasticsearch Service Console. Any changes are automatically changed in the kibana.yml configuration file. For detailed information about the kibana.yml settings, refer to <<settings, Configure {kib}>>.

[float]
[[install-and-manage-the-stack-yourself]]
== Install and manage {kib} yourself

If you’d rather install and manage {kib} yourself, review the Elastic Support Matrix for information about supported operating systems and product compatibility.

Using different versions of {es} and {kib} is unsupported. For example, using different major versions, such as {es} 2.x and {kib} 5.x, or a minor {kib} version that is newer than the {es} version, such as Kibana 5.1 and Elasticsearch 5.0, causes the installation to fail.

Using different patch versions of Kibana and Elasticsearch is generally supported, such as Kibana 5.0.0 and Elasticsearch 5.0.1, but we recommend using the same {es} and {kib} patch versions.

//[insert image]

. <<install,Download and unzip {kib}>>. Gail to rewrite.

. Open an editor, then configure the <<settings,config/kibana.yml settings>>. Kaarina to move to new location.

//*** Production considerations -- where does this go? Do we need to split it up? Need to talk to Raya.

. Start {kib}. 

. Access {kib}. Kaarina to rewrite.

. Configure security. Need to talk to Larry.

. To enable users to generate reports, install the reporting packages.

. To enable users to monitor the Elastic Stack, configure monitoring.

--

include::{kib-repo-dir}/setup/install.asciidoc[]

include::{kib-repo-dir}/setup/settings.asciidoc[]

include::{kib-repo-dir}/setup/start-stop.asciidoc[]

include::{kib-repo-dir}/setup/access.asciidoc[]

include::security/securing-kibana.asciidoc[]

include::{kib-repo-dir}/setup/configuring-reporting.asciidoc[]

include::monitoring/configuring-monitoring.asciidoc[leveloffset=+1]
include::monitoring/monitoring-metricbeat.asciidoc[leveloffset=+2]
include::monitoring/viewing-metrics.asciidoc[leveloffset=+2]
include::monitoring/monitoring-kibana.asciidoc[leveloffset=+2]
