[[visualize]]
= Visualize

[partintro]
--
_Visualize_ enables you to create visualizations of the data from your {es} indices, which you can then add to dashboards for analysis.

{kib} visualizations are based on {es} queries. By using a series of {es} {ref}/search-aggregations.html[aggregations] to extract and process your data, you can create charts that show you the trends, spikes, and dips you need to know about.

To begin, open *Visualize*, then click *Create new visualization*.

[float]
[[visualization-type]]
== Types of visualizations

To help you choose the best visualization for you data, {kib} supports many types of visualizations.

<<lens,Lens>>::
Quickly build several types of visualizations by simply dragging and dropping the data fields you want to display.

<<most-frequent,Basic visualizations>>::
* Line, area, and bar charts - Compare different series in X/Y charts.

* Pie chart - Display each source contribution to a total.

* Data table - Flattens aggregations into a table format.

* Metric - Display a single number.

* Goal and gauge - Display a number with progress indicators.

* Tag cloud - Display words in a cloud, where the size of the word corresponds to its importance.

<<TSVB,TSVB>>::
Visualize time series data using pipeline aggregations.

<<timelion,Timelion>>::
Compute and combine data from multiple time series data sets.

<<maps,Maps>>::
* <<maps,Elastic Maps>> - The most powerful way to visualize map data in {kib}.

* Coordinate map - Displays points on a map using a geohash aggregation.

* Region map - Merge any structured map data onto a shape.

* Heat map - Display shaded cells within a matrix.

<<for-dashboard,Dashboard tools>>::
* Markdown widget - Display free-form information or instructions.

* Controls widget - Add interactive inputs to a dashboard.

<<vega-graph,Vega>>::
Provides complete control over query and display.

[float]
[[choose-your-data]]
== Choose your data

Specify a search query to retrieve the data for your visualization, or used rolled up data.

* To enter new search criteria, select the <<index-patterns, index pattern>> for the indices that
contain the data you want to visualize. The visualization builder opens
with a wildcard query that matches all of the documents in the selected
indices.

* To build a visualization from a saved search, click the name of the saved
search you want to use. The visualization builder opens and loads the
selected query.
+
NOTE: When you build a visualization from a saved search, any subsequent
modifications to the saved search are reflected in the
visualization. To disable automatic updates, disconnect the visualization
from the saved search.

* [beta] Visualize rolled up data in a variety of visualization.

** For specific fields, the data in a rollup index includes only summarized metrics.
From the original raw data, you are unable to search any other field.

** Data is summarized into time buckets that might be split into sub buckets for
numeric field values or terms. To lower granularity, you can use a time aggregation that takes
several time buckets and combines them. For example,
if the rollup job was aggregated by hours, you use buckets of days.

--

include::{kib-repo-dir}/visualize/aggregations.asciidoc[]

include::{kib-repo-dir}/visualize/lens.asciidoc[]

include::{kib-repo-dir}/visualize/most-frequent.asciidoc[]

include::{kib-repo-dir}/visualize/tsvb.asciidoc[]

include::{kib-repo-dir}/visualize/timelion.asciidoc[]

include::{kib-repo-dir}/visualize/maps.asciidoc[]

include::{kib-repo-dir}/visualize/for-dashboard.asciidoc[]

include::{kib-repo-dir}/visualize/vega.asciidoc[]

include::{kib-repo-dir}/visualize/saving.asciidoc[]

include::{kib-repo-dir}/visualize/inspector.asciidoc[]
