[[visualize]]
= Visualize

[partintro]
--
_Visualize_ enables you to create visualizations of the data in your
Elasticsearch indices. You can then build <<dashboard, dashboards>> that
display related visualizations.

Kibana visualizations are based on Elasticsearch queries. By using a
series of Elasticsearch {ref}/search-aggregations.html[aggregations]
to extract and process your data, you can create charts that show
you the trends, spikes, and dips you need to know about.

You can create visualizations from a search saved from <<discover, Discover>>
or start from an <<index-patterns, index pattern>>.

**Creating a Visualization**

. Click on *Visualize* in the side navigation.
. Click the *Create new visualization* button or the **+** button.
. Choose the visualization type:
+
* *<<most-frequent,Most frequently used visualizations>>*
[horizontal]
<<most-frequent,Line&comma; Area and Bar charts>>:: Compare different series in X/Y charts.
<<most-frequent,Pie chart>>:: Display each source's contribution to a total.
<<most-frequent,Data table>>:: Flattens aggregations into table format.
<<most-frequent,Metric>>:: Display a single number.
<<most-frequent,Goal and Gauge>>:: Display a number with more decoration.
<<most-frequent,Heat maps>>:: Shade cells within a matrix.
<<most-frequent,Tag cloud>>:: Display words as a cloud in which the size of the word correspond to its importance.
* *Time Series optimized*
[horizontal]
<<TSVB,TSVB>>:: Visualize time series data using pipeline aggregations.
<<timelion,_Timelion_>>:: Compute and combine data from multiple time series
data sets. Hidden by default.
* *Maps*
[horizontal]
<<maps, Elastic maps>>:: Elastic maps is the most powerful way of visualizing map data in Kibana
<<tilemap,_Coordinate map_>>:: Displays points on a map using a geohash aggregation.
<<regionmap,_Region map_>>:: Merge any structured map data onto a shape
* *<<for-dashboard, For use in dashboards>>*
[horizontal]
<<for-dashboard,Controls>>:: Controls provide the ability to add interactive inputs to Kibana Dashboards.
<<for-dashboard,Markdown widget>>:: Display free-form information or instructions.
* *For developers*
[horizontal]
<<vega-graph,Vega>>:: Complete control over query and display.

. Specify a search query to retrieve the data for your visualization:
** To enter new search criteria, select the <<index-patterns, index pattern>> for the indices that
contain the data you want to visualize. This opens the visualization builder
with a wildcard query that matches all of the documents in the selected
indices.
** To build a visualization from a saved search, click the name of the saved
search you want to use. This opens the visualization builder and loads the
selected query.
+
NOTE: When you build a visualization from a saved search, any subsequent
modifications to the saved search are automatically reflected in the
visualization. To disable automatic updates, you can disconnect a visualization
from the saved search.

--

include::{kib-repo-dir}/visualize/saving.asciidoc[]

include::{kib-repo-dir}/visualize/most-frequent.asciidoc[]

// include::{kib-repo-dir}/visualize/xychart.asciidoc[]
// include::{kib-repo-dir}/visualize/pie.asciidoc[]
// include::{kib-repo-dir}/visualize/datatable.asciidoc[]
// include::{kib-repo-dir}/visualize/metric.asciidoc[]
// include::{kib-repo-dir}/visualize/goal.asciidoc[]
// include::{kib-repo-dir}/visualize/heatmap.asciidoc[]
// include::{kib-repo-dir}/visualize/tagcloud.asciidoc[]

include::{kib-repo-dir}/visualize/tsvb.asciidoc[]
include::{kib-repo-dir}/visualize/timelion.asciidoc[]

include::{kib-repo-dir}/visualize/tilemap.asciidoc[]
include::{kib-repo-dir}/visualize/regionmap.asciidoc[]

include::{kib-repo-dir}/visualize/for-dashboard.asciidoc[]

include::{kib-repo-dir}/visualize/vega.asciidoc[]

include::{kib-repo-dir}/visualize/inspector.asciidoc[]

include::{kib-repo-dir}/visualize/visualize_rollup_data.asciidoc[]
