/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

import type { ResilientFieldMeta } from '@kbn/connector-schemas/resilient';

export const resilientFields: ResilientFieldMeta[] = [
  {
    name: 'name',
    input_type: 'text',
    read_only: false,
    values: [],
    required: null,
    text: '',
    prefix: null,
  },
  {
    name: 'description',
    input_type: 'textarea',
    read_only: false,
    values: [],
    required: null,
    text: '',
    prefix: null,
  },
  {
    name: 'severity_code',
    input_type: 'select',
    read_only: false,
    values: [
      {
        default: false,
        enabled: true,
        hidden: false,
        value: 5,
        label: 'Low',
      },
      {
        default: false,
        enabled: true,
        hidden: false,
        value: 6,
        label: 'Medium',
      },
    ],
    required: null,
    text: '',
    prefix: null,
  },
  {
    name: 'incident_type_ids',
    input_type: 'multiselect',
    read_only: false,
    values: [
      {
        default: false,
        enabled: true,
        hidden: false,
        value: 12,
        label: 'Communication error (fax; email)',
      },
      {
        default: false,
        enabled: true,
        hidden: false,
        value: 16,
        label: 'Custom type',
      },
      {
        default: false,
        enabled: true,
        hidden: false,
        value: 1001,
        label: 'Custom type 2',
      },
    ],
    required: null,
    text: '',
    prefix: null,
  },
  {
    name: 'customField1',
    input_type: 'text',
    read_only: false,
    values: [],
    required: null,
    text: '',
    prefix: 'properties',
  },
  {
    name: 'test_text',
    input_type: 'text',
    read_only: false,
    values: [],
    required: null,
    text: '',
    prefix: 'properties',
  },
  {
    name: 'test_text_area',
    input_type: 'textarea',
    read_only: false,
    values: [],
    required: null,
    text: '',
    prefix: 'properties',
  },
  {
    name: 'test_boolean',
    input_type: 'boolean',
    read_only: false,
    values: [],
    required: null,
    text: '',
    prefix: 'properties',
  },
  {
    name: 'test_date_picker',
    input_type: 'datepicker',
    read_only: false,
    values: [],
    required: null,
    text: '',
    prefix: 'properties',
  },
  {
    name: 'test_date_time_picker',
    input_type: 'datetimepicker',
    read_only: false,
    values: [],
    required: null,
    text: '',
    prefix: 'properties',
  },
  {
    name: 'test_number',
    input_type: 'number',
    read_only: false,
    values: [],
    required: null,
    text: '',
    prefix: 'properties',
  },
  {
    name: 'test_select',
    input_type: 'select',
    read_only: false,
    values: [
      {
        default: false,
        enabled: true,
        hidden: false,
        value: 100,
        label: 'Option 1',
      },
      {
        default: true,
        enabled: true,
        hidden: false,
        value: 110,
        label: 'Option 2',
      },
      {
        default: false,
        enabled: true,
        hidden: false,
        value: 120,
        label: 'Option 3',
      },
      {
        default: false,
        enabled: true,
        hidden: false,
        value: 130,
        label: 'Option 4',
      },
    ],
    required: null,
    text: '',
    prefix: 'properties',
  },
  {
    name: 'test_multi_select',
    input_type: 'multiselect',
    read_only: false,
    values: [
      {
        default: false,
        enabled: true,
        hidden: false,
        value: 100,
        label: 'Option 1',
      },
      {
        default: true,
        enabled: true,
        hidden: false,
        value: 110,
        label: 'Option 2',
      },
      {
        default: false,
        enabled: true,
        hidden: false,
        value: 120,
        label: 'Option 3',
      },
      {
        default: false,
        enabled: true,
        hidden: false,
        value: 130,
        label: 'Option 4',
      },
    ],
    required: null,
    text: '',
    prefix: 'properties',
  },
  {
    name: 'resolution_summary',
    input_type: 'textarea',
    read_only: false,
    values: [],
    required: null,
    text: '',
    prefix: null,
  },
];

export const incidentTypes = {
  id: 16,
  name: 'incident_type_ids',
  text: 'Incident Type',
  values: [
    {
      value: 17,
      label: 'Communication error (fax; email)',
      enabled: true,
      properties: null,
      uuid: '4a8d22f7-d89e-4403-85c7-2bafe3b7f2ae',
      hidden: false,
      default: false,
    },
    {
      value: 1001,
      label: 'Custom type',
      enabled: true,
      properties: null,
      uuid: '3b51c8c2-9758-48f8-b013-bd141f1d2ec9',
      hidden: false,
      default: false,
    },
  ],
};

export const severity = [
  {
    value: 4,
    label: 'Low',
    enabled: true,
    properties: null,
    uuid: '97cae239-963d-4e36-be34-07e47ef2cc86',
    hidden: false,
    default: true,
  },
  {
    value: 5,
    label: 'Medium',
    enabled: true,
    properties: null,
    uuid: 'c2c354c9-6d1e-4a48-82e5-bd5dc5068339',
    hidden: false,
    default: false,
  },
  {
    value: 6,
    label: 'High',
    enabled: true,
    properties: null,
    uuid: '93e5c99c-563b-48b9-80a3-9572307622d8',
    hidden: false,
    default: false,
  },
];
