[[install]]
== Installing Kibana

[float]
=== Hosted Kibana

If you are running our hosted Elasticsearch Service on Elastic Cloud, you access Kibana with a single click. (You can {ess-trial}[sign up for a free trial] and start exploring data in minutes.)

[float]
=== Installing Kibana Yourself

NOTE: Starting with version 6.0.0, Kibana only supports 64 bit operating systems.

Kibana is provided in the following package formats:

[horizontal]
`tar.gz`/`zip`::

The `tar.gz` packages are provided for installation on Linux and Darwin and are
the easiest choice for getting started with Kibana.
+
The `zip` package is the only supported package for Windows.
+
<<targz>> or <<windows>>

`deb`::

The `deb` package is suitable for Debian, Ubuntu, and other Debian-based
systems.  Debian packages may be downloaded from the Elastic website or from
our Debian repository.
+
<<deb>>

`rpm`::

The `rpm` package is suitable for installation on Red Hat, Centos, SLES,
OpenSuSE and other RPM-based systems.  RPMs may be downloaded from the
Elastic website or from our RPM repository.
+
<<rpm>>

`docker`::

Images are available for running Kibana as a Docker container. They may be
downloaded from the Elastic Docker Registry.
+
<<docker,Running Kibana on Docker>>

IMPORTANT: If your Elasticsearch installation is protected by
{ref}/secure-cluster.html[{security-features}] see
{kibana-ref}/using-kibana-with-security.html[Configuring security in Kibana] for
additional setup instructions.


include::install/targz.asciidoc[]

include::install/deb.asciidoc[]

include::install/rpm.asciidoc[]

include::install/windows.asciidoc[]
