[[secure-settings]]
=== Secure settings

Some settings are sensitive, and relying on filesystem permissions to protect
their values is not sufficient. For this use case, Kibana provides a
keystore, and the `kibana-keystore` tool to manage the settings in the keystore.

NOTE: All commands here should be run as the user which will run Kibana.


NOTE: Only some settings are designed to be read from the keystore. However, the keystore has no validation to block unsupported settings when being added. Adding unsupported settings to the keystore causes Kibana to fail to start. To see whether a setting is supported in the keystore, look for a "Secure" qualifier the setting reference. Furthermore, setting values will be validated upon startup, in case you're getting validation errors, review your configuration values.

[float]
[[creating-keystore]]
=== Create the keystore

To create the `kibana.keystore`, use the `create` command:

[source,sh]
----------------------------------------------------------------
bin/kibana-keystore create
----------------------------------------------------------------

The file `kibana.keystore` will be created in the `config` directory defined by the
environment variable `KBN_PATH_CONF`.

[float]
[[list-settings]]
=== List settings in the keystore

A list of the settings in the keystore is available with the `list` command:

[source,sh]
----------------------------------------------------------------
bin/kibana-keystore list
----------------------------------------------------------------

[float]
[[add-string-to-keystore]]
=== Add string settings

NOTE: Your input will be JSON-parsed to allow for object/array input configurations. To enforce string values, use "double quotes" around your input.

Sensitive string settings, like authentication credentials for Elasticsearch
can be added using the `add` command:

[source,sh]
----------------------------------------------------------------
bin/kibana-keystore add the.setting.name.to.set
----------------------------------------------------------------

Once added to the keystore, these setting will be automatically applied
to this instance of Kibana when started. For example if you do

[source,sh]
----------------------------------------------------------------
bin/kibana-keystore add elasticsearch.username
----------------------------------------------------------------

you will be prompted to provide the value for elasticsearch.username.
(Your input will show as asterisks.)

The tool will prompt for the value of the setting. To pass the value
through stdin, use the `--stdin` flag:

[source,sh]
----------------------------------------------------------------
cat /file/containing/setting/value | bin/kibana-keystore add the.setting.name.to.set --stdin
----------------------------------------------------------------

[float]
[[remove-settings]]
=== Remove settings

To remove a setting from the keystore, use the `remove` command:

[source,sh]
----------------------------------------------------------------
bin/kibana-keystore remove the.setting.name.to.remove
----------------------------------------------------------------

[float]
[[read-settings]]
=== Read settings

To display currently configured setting values, use the `show` command:

[source, sh]
----------------------------------------------------------------
bin/kibana-keystore show setting.key
----------------------------------------------------------------
