[role="xpack"]
[[setup-xpack-kb]]
== Set Up {xpack}

{xpack} is an Elastic Stack extension that provides security, alerting,
monitoring, reporting, machine learning, graph, and many other capabilities. By 
default, when you install {kib}, {xpack} is installed.

If you want to try all of the {xpack} features, you can 
{xpack-ref}/license-management.html[start a 30-day trial]. At the end of the 
trial period, you can purchase a subscription to keep using the full 
functionality of the {xpack} components. For more information, see 
https://www.elastic.co/subscriptions.

{xpack} adds the following pages to the side navigation:

* **APM**
* **Machine Learning**
* **Graph**
* **Monitoring**

The **Management** page gains options related to configuring security. The
**Dev Tools** page gains a Search Profiler and a Grok Debugger. Where these and
other {xpack} features are mentioned in this documentation, we've added an icon
to clearly indicate that what you're reading pertains to features available only
in {xpack}.

