[[upgrade]]
== Upgrading {kib}


[IMPORTANT]
===========================================
Before upgrading {kib}:

* Consult the <<breaking-changes,breaking changes>> docs.
* Test upgrades in a dev environment before upgrading your production servers.
* Backup your data using the {es} {ref}/modules-snapshots.html[snapshots] feature.
  You **cannot roll back** to an earlier version unless you have a backup of
  your data.
* If you are using custom plugins, check that a compatible version is
  available.
===========================================

Depending on which version of {kib} you're upgrading from, the upgrade process to 7.0
will vary. 

The recommended path is to upgrade to 6.7 before upgrading to 7.0. 
This makes it easier to identify the changes you need to make to upgrade and enables 
you to perform a rolling upgrade with no downtime. 

Please see 
*{stack-ref}/upgrading-elastic-stack.html[Upgrading the Elastic Stack]* for a 
comprehensive overview of the upgrade process.

[float]
==== Upgrading from 5.x or earlier
{es} can read indices created in the previous major version. If you have indices 
created in 5.x or before, you must reindex or delete them before upgrading to 7.0.0.
See {stack-ref}/upgrading-elastic-stack.html#oss-stack-upgrade[Upgrading the Elastic Stack] 
for more information.

Once your reindex is complete, you can follow the <<upgrade-standard, Standard upgrade>> 
instructions. 

[float]
==== Upgrading from 6.x

The recommended path is to upgrade to 6.7 before upgrading to 7.0. This makes it 
easier to identify the required changes, and enables you to use the Upgrade Assistant
to prepare for your upgrade to 7.0 (see below).

*Note:* Saved searches, visualizations, and dashboards created in {kib} 6.x
can be generally imported into 7.x.

[float]
==== Upgrading from 6.7
6.7 includes an https://www.elastic.co/guide/en/kibana/6.7/upgrade-assistant.html[Upgrade Assistant] 
to help you prepare for your upgrade to 7.0. To access the assistant, go to *Management > 7.0 Upgrade Assistant*. 

After you have addressed any issues that were identified by the Upgrade Assistant, 
<<upgrade-standard,upgrade to 7.0>>.


include::upgrade/upgrade-standard.asciidoc[]

include::upgrade/upgrade-migrations.asciidoc[]

