[[upgrade]]
== Upgrading Kibana

Your existing Kibana version is generally compatible with the next minor
version release of Elasticsearch. This means you should upgrade your
Elasticsearch cluster(s) before or at the same time as Kibana. We cannot
guarantee compatibility between major version releases so in those cases both
Elasticsearch and Kibana must be upgraded together.

To upgrade Kibana:

. Create a {es-ref}modules-snapshots.html[snapshot]
of the existing `.kibana` index.
. Back up the `kibana.yml` configuration file.
. Take note of the Kibana plugins that are installed:
 * `bin/kibana plugin --list` on 4.x versions of Kibana.
 * `bin/kibana-plugin list` on 5.x versions of Kibana.
. To upgrade from an Archive File:
.. Extract the new version of Kibana into a different directory.  See steps below.
.. Migrate any custom configuration from your old kibana.yml to your new one
.. Follow other steps below to complete the new installation.
.. Once the new version is fully configured and working with required plugins, remove the previous version
of Kibana
. To upgrade using a Linux Package Manager:
.. Uninstall the existing Kibana package: `apt-get remove kibana` or `yum remove kibana`
.. Install the new Kibana package.   There have been some installer issues between various version of
Kibana so the uninstall and install process is safer than an upgrade.
