[[upgrade]]
== Upgrade {kib}

You can always upgrade to the latest patch release or from one minor version 
to another within the same major version series.

For major version upgrades:

. Upgrade to the last minor version released before the new major version.
. Use the Upgrade Assistant to determine what changes you need to make before the major version upgrade.
. When you've addressed all the critical issues, upgrade {es} and then upgrade {kib}.

IMPORTANT: You can upgrade to pre-release versions of 8.0 for testing, 
but upgrading from a pre-release to the final GA version is not supported.
Pre-releases should only be used for testing in a temporary environment.

[discrete]
[[upgrade-paths]]
=== Recommended upgrade paths to 8.0

[cols="<1,3",options="header",]
|====
|Upgrading from   
|Upgrade path 

|7.16
|Upgrade to 8.0

|6.8–7.15
a|

. Upgrade to 7.16
. Upgrade to 8.0

|6.0–6.7
a|

. Upgrade to 6.8
. Upgrade to 7.16
. Upgrade to 8.0
|====

[float]
[[upgrade-before-you-begin]]
=== Before you begin

[WARNING]
====
{kib} automatically runs upgrade migrations when required. To roll back to an
earlier version in case of an upgrade failure, you **must** have a
{ref}/snapshot-restore.html[backup snapshot] that includes the `kibana` feature
state. Snapshots include this feature state by default.

For more information, refer to <<upgrade-migrations, upgrade migrations>>.
====

Before you upgrade {kib}:

* Consult the <<breaking-changes,breaking changes>>.
* {ref}/snapshots-take-snapshot.html[Take a snapshot] of your data. To roll back to an earlier version, the snapshot must include the `kibana` feature state.
* Before you upgrade production servers, test the upgrades in a dev environment.
* See <<preventing-migration-failures, preventing migration failures>> for common reasons upgrades fail and how to prevent these.
* If you are using custom plugins, check that a compatible version is
  available.
* Shut down all {kib} instances. Running more than one {kib} version against
  the same Elasticseach index is unsupported. Upgrading while older {kib}
  instances are running can cause data loss or upgrade failures.
  
NOTE: {kib} logging system may have changed, depending on your target version. For details, see <<logging-configuration, Configure logging>>.

To identify the changes you need to make to upgrade, and to enable you to
perform an Elasticsearch rolling upgrade with no downtime, you must upgrade to
6.7 before you upgrade to 7.0.

For a comprehensive overview of the upgrade process, refer to
*{stack-ref}/upgrading-elastic-stack.html[Upgrading the Elastic Stack]*.

[float]
[[upgrade-5x-earlier]]
=== Upgrade from 5.x or earlier
{es} can read indices created in the previous major version. Before you upgrade
to 7.0.0, you must reindex or delete any indices created in 5.x or earlier.
For more information, refer to
{stack-ref}/upgrading-elastic-stack.html[Upgrading the Elastic Stack].

When your reindex is complete, follow the <<upgrade-standard, Standard upgrade>>
instructions.

[float]
[[upgrade-6x]]
=== Upgrade from 6.x

The recommended path is to upgrade to 6.8 before upgrading to 7.0. This makes it
easier to identify the required changes, and enables you to use the Upgrade
Assistant to prepare for your upgrade to 7.0.

TIP: The ability to import {kib} 6.x saved searches, visualizations, and
dashboards is supported.

[float]
[[upgrade-67]]
=== Upgrade from 6.8
To help you prepare for your upgrade to 7.0, 6.8 includes an https://www.elastic.co/guide/en/kibana/6.8/upgrade-assistant.html[Upgrade Assistant]
To access the assistant, go to *Management > 7.0 Upgrade Assistant*.

After you have addressed any issues that were identified by the Upgrade
Assistant, <<upgrade-standard,upgrade to 7.0>>.


include::upgrade/upgrade-standard.asciidoc[]

include::upgrade/upgrade-migrations.asciidoc[]

include::upgrade/logging-configuration-changes.asciidoc[]
