/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Dismiss attack discovery generations API endpoint
 *   version: 2023-10-31
 */

import type { NonEmptyString } from '../../../../common_attributes.gen';

export interface PostAttackDiscoveryGenerationsDismissRequestParams {
  /**
   * The unique identifier for the Attack discovery generation execution. This UUID is returned when an attack discovery generation is created and can be found in generation responses.
   */
  execution_uuid: NonEmptyString;
}
export interface PostAttackDiscoveryGenerationsDismissRequestParamsInput {
  /**
   * The unique identifier for the Attack discovery generation execution. This UUID is returned when an attack discovery generation is created and can be found in generation responses.
   */
  execution_uuid: NonEmptyString;
}

export interface PostAttackDiscoveryGenerationsDismissResponse {
  /**
   * The number of alerts that were sent as context to the LLM for this generation.
   */
  alerts_context_count?: number;
  /**
   * The unique identifier of the connector used to generate the attack discoveries.
   */
  connector_id: string;
  /**
   * Statistical information about the connector's performance for this user, providing insights into usage patterns and success rates.
   */
  connector_stats?: {
    /**
     * The average duration in nanoseconds for successful generations using this connector by the current user.
     */
    average_successful_duration_nanoseconds?: number;
    /**
     * The total number of Attack discoveries successfully created for this generation
     */
    successful_generations?: number;
  };
  /**
   * The number of attack discoveries that were generated during this execution.
   */
  discoveries: number;
  /**
   * The timestamp when the generation process completed, in ISO 8601 format. This field may be absent for generations that haven't finished.
   */
  end?: string;
  /**
   * The unique identifier for this attack discovery generation execution. This UUID can be used to reference this specific generation in other API calls.
   */
  execution_uuid: string;
  /**
   * A human-readable message describing the current state or progress of the generation process. Provides context about what the AI is analyzing.
   */
  loading_message: string;
  /**
   * Additional context or reasoning provided when a generation fails or encounters issues. This field helps diagnose problems with the generation process.
   */
  reason?: string;
  /**
   * The timestamp when the generation process began, in ISO 8601 format. This marks the beginning of the AI analysis.
   */
  start: string;
  /**
   * The current status of the attack discovery generation. After dismissing, this will be set to "dismissed".
   */
  status: 'canceled' | 'dismissed' | 'failed' | 'started' | 'succeeded';
}
