import type { ElasticsearchClient } from '@kbn/core/server';
import type { MsearchRequestItem, MsearchResponseItem, SearchRequest } from '@elastic/elasticsearch/lib/api/types';
import type { Alert } from '@kbn/alerts-as-data-utils';
import type { SummarizedAlerts, AlertInstanceContext, AlertInstanceState, RuleAlertData, WithoutReservedActionGroups, DataStreamAdapter } from '../types';
import type { CreateAlertsClientParams } from '../alerts_service/alerts_service';
import type { LogAlertsOpts, SearchResult, DetermineDelayedAlertsOpts, AlertsToUpdateWithMaintenanceWindows, AlertsToUpdateWithLastScheduledActions, IAlertsClient, InitializeExecutionOpts, ReportedAlert, ReportedAlertData, UpdateableAlert, GetSummarizedAlertsParams } from './types';
export interface AlertsClientParams extends CreateAlertsClientParams {
    elasticsearchClientPromise: Promise<ElasticsearchClient>;
    kibanaVersion: string;
    dataStreamAdapter: DataStreamAdapter;
    isServerless: boolean;
}
export declare class AlertsClient<AlertData extends RuleAlertData, LegacyState extends AlertInstanceState, LegacyContext extends AlertInstanceContext, ActionGroupIds extends string, RecoveryActionGroupId extends string> implements IAlertsClient<AlertData, LegacyState, LegacyContext, ActionGroupIds, RecoveryActionGroupId> {
    private readonly options;
    private legacyAlertsClient;
    private trackedAlerts;
    private startedAtString;
    private runTimestampString;
    private rule;
    private ruleType;
    private readonly isServerless;
    private indexTemplateAndPattern;
    private reportedAlerts;
    private _isUsingDataStreams;
    private ruleInfoMessage;
    private logTags;
    constructor(options: AlertsClientParams);
    initializeExecution(opts: InitializeExecutionOpts): Promise<void>;
    search<Aggregation = unknown>(queryBody: SearchRequest): Promise<SearchResult<AlertData, Aggregation>>;
    msearch<Aggregation = unknown>(searches: MsearchRequestItem[]): Promise<Array<MsearchResponseItem<Alert & AlertData>>>;
    report(alert: ReportedAlert<AlertData, LegacyState, LegacyContext, WithoutReservedActionGroups<ActionGroupIds, RecoveryActionGroupId>>): ReportedAlertData<AlertData>;
    setAlertData(alert: UpdateableAlert<AlertData, LegacyState, LegacyContext, ActionGroupIds>): void;
    isTrackedAlert(id: string): boolean;
    hasReachedAlertLimit(): boolean;
    getMaxAlertLimit(): number;
    checkLimitUsage(): void;
    processAlerts(): Promise<void>;
    determineFlappingAlerts(): void;
    determineDelayedAlerts(opts: DetermineDelayedAlertsOpts): void;
    logAlerts(opts: LogAlertsOpts): void;
    getProcessedAlerts(type: 'new' | 'active' | 'trackedActiveAlerts' | 'recovered' | 'trackedRecoveredAlerts'): Record<string, import("../alert").Alert<LegacyState, LegacyContext, ActionGroupIds, import("@kbn/alerts-as-data-utils").AADAlert>> | Record<string, import("../alert").Alert<LegacyState, LegacyContext, RecoveryActionGroupId, import("@kbn/alerts-as-data-utils").AADAlert>>;
    getRawAlertInstancesForState(shouldOptimizeTaskState?: boolean): {
        rawActiveAlerts: Record<string, import("@kbn/alerting-state-types/src/task_state").LatestRawAlertInstanceSchema>;
        rawRecoveredAlerts: Record<string, import("@kbn/alerting-state-types/src/task_state").LatestRawAlertInstanceSchema>;
    };
    factory(): import("../alert/create_alert_factory").PublicAlertFactory<LegacyState, LegacyContext, WithoutReservedActionGroups<ActionGroupIds, RecoveryActionGroupId>>;
    getSummarizedAlerts({ ruleId, spaceId, excludedAlertInstanceIds, alertsFilter, start, end, executionUuid, }: GetSummarizedAlertsParams): Promise<SummarizedAlerts>;
    persistAlerts(): Promise<void>;
    updatePersistedAlerts({ alertsToUpdateWithMaintenanceWindows, alertsToUpdateWithLastScheduledActions, }: {
        alertsToUpdateWithMaintenanceWindows: AlertsToUpdateWithMaintenanceWindows;
        alertsToUpdateWithLastScheduledActions: AlertsToUpdateWithLastScheduledActions;
    }): Promise<void>;
    private getMaintenanceWindowScopedQueryAlerts;
    getAlertsToUpdateWithMaintenanceWindows(): Promise<AlertsToUpdateWithMaintenanceWindows>;
    getAlertsToUpdateWithLastScheduledActions(): AlertsToUpdateWithLastScheduledActions;
    client(): {
        report: (alert: ReportedAlert<AlertData, LegacyState, LegacyContext, WithoutReservedActionGroups<ActionGroupIds, RecoveryActionGroupId>>) => ReportedAlertData<AlertData>;
        isTrackedAlert: (id: string) => boolean;
        setAlertData: (alert: UpdateableAlert<AlertData, LegacyState, LegacyContext, RecoveryActionGroupId>) => void;
        getAlertLimitValue: () => number;
        setAlertLimitReached: (reached: boolean) => void;
        getRecoveredAlerts: () => {
            alert: import("../alert").Alert<LegacyState, LegacyContext, WithoutReservedActionGroups<ActionGroupIds, RecoveryActionGroupId>, import("@kbn/alerts-as-data-utils").AADAlert>;
            hit: {
                '@timestamp': string | number;
                'kibana.alert.instance.id': string;
                'kibana.alert.rule.category': string;
                'kibana.alert.rule.consumer': string;
                'kibana.alert.rule.name': string;
                'kibana.alert.rule.producer': string;
                'kibana.alert.rule.revision': string | number;
                'kibana.alert.rule.rule_type_id': string;
                'kibana.alert.rule.uuid': string;
                'kibana.alert.status': string;
                'kibana.alert.uuid': string;
                'kibana.space_ids': string[];
            } & {
                'data_stream.dataset'?: string | undefined;
                'data_stream.namespace'?: string | undefined;
                'data_stream.type'?: string | undefined;
                'event.action'?: string | undefined;
                'event.kind'?: string | undefined;
                'event.original'?: string | undefined;
                'kibana.alert.action_group'?: string | undefined;
                'kibana.alert.case_ids'?: string[] | undefined;
                'kibana.alert.consecutive_matches'?: string | number | undefined;
                'kibana.alert.duration.us'?: string | number | undefined;
                'kibana.alert.end'?: string | number | undefined;
                'kibana.alert.flapping'?: boolean | undefined;
                'kibana.alert.flapping_history'?: boolean[] | undefined;
                'kibana.alert.index_pattern'?: string | undefined;
                'kibana.alert.intended_timestamp'?: string | number | undefined;
                'kibana.alert.last_detected'?: string | number | undefined;
                'kibana.alert.maintenance_window_ids'?: string[] | undefined;
                'kibana.alert.maintenance_window_names'?: string[] | undefined;
                'kibana.alert.muted'?: boolean | undefined;
                'kibana.alert.pending_recovered_count'?: string | number | undefined;
                'kibana.alert.previous_action_group'?: string | undefined;
                'kibana.alert.reason'?: string | undefined;
                'kibana.alert.rule.execution.timestamp'?: string | number | undefined;
                'kibana.alert.rule.execution.type'?: string | undefined;
                'kibana.alert.rule.execution.uuid'?: string | undefined;
                'kibana.alert.rule.parameters'?: unknown;
                'kibana.alert.rule.tags'?: string[] | undefined;
                'kibana.alert.scheduled_action.date'?: string | undefined;
                'kibana.alert.scheduled_action.group'?: string | undefined;
                'kibana.alert.severity'?: string | undefined;
                'kibana.alert.severity_improving'?: boolean | undefined;
                'kibana.alert.start'?: string | number | undefined;
                'kibana.alert.time_range'?: {
                    gte?: string | number | undefined;
                    lte?: string | number | undefined;
                } | undefined;
                'kibana.alert.updated_at'?: string | number | undefined;
                'kibana.alert.updated_by.user.id'?: string | undefined;
                'kibana.alert.updated_by.user.name'?: string | undefined;
                'kibana.alert.url'?: string | undefined;
                'kibana.alert.workflow_assignee_ids'?: string[] | undefined;
                'kibana.alert.workflow_status'?: string | undefined;
                'kibana.alert.workflow_tags'?: string[] | undefined;
                'kibana.cps_scope.expression'?: string | undefined;
                'kibana.cps_scope.linked_projects'?: unknown[] | undefined;
                'kibana.version'?: string | undefined;
                tags?: string[] | undefined;
            } & AlertData;
        }[];
    };
    isUsingDataStreams(): boolean;
    private throwIfHasClusterBlockException;
}
