[[Machine_learning_APIs]]
== Machine learning APIs

* <<ml-sync-default>>
* <<ml-sync>>

[[ml-sync-default]]
=== Sync machine learning saved objects in the default space

Synchronizes Kibana saved objects for machine learning jobs and trained models in the default space. You must have `all` privileges for the *Machine Learning* feature in the *Analytics* section of the Kibana feature privileges. This API runs automatically when you start Kibana and periodically thereafter.


==== Request

`GET /api/ml/saved_objects/sync`

==== Query parameters

[options="header"]
|==========
|Name |Type |Required |Description
|`simulate` |+boolean+; default: ++false++ |N |When true, simulates the synchronization by returning only the list actions that would be performed.

|==========
==== Responses

`200`::
+
--
(<<SyncResponse,`SyncResponse`>>)

Indicates a successful call.

--

==== Request example

[source,json]
--------
curl -XGET https://localhost:5601/api/ml/saved_objects/sync \
-u USER:PASSWORD
--------
[[ml-sync]]
=== Sync machine learning saved objects

Synchronizes Kibana saved objects for machine learning jobs and trained models. You must have `all` privileges for the *Machine Learning* feature in the *Analytics* section of the Kibana feature privileges. This API runs automatically when you start Kibana and periodically thereafter.


==== Request

`GET /s/{spaceId}/api/ml/saved_objects/sync`

==== Path parameters

[options="header"]
|==========
|Name |Type |Required |Description
|`spaceId` |+string+ |Y |An identifier for the space.

|==========
==== Query parameters

[options="header"]
|==========
|Name |Type |Required |Description
|`simulate` |+boolean+; default: ++false++ |N |When true, simulates the synchronization by returning only the list actions that would be performed.

|==========
==== Responses

`200`::
+
--
(<<SyncResponse,`SyncResponse`>>)

Indicates a successful call.

--

==== Request example

[source,json]
--------
curl -XGET https://localhost:5601/s/{spaceId}/api/ml/saved_objects/sync \
-u USER:PASSWORD
--------
[[definitions]]
== Definitions

* <<DatafeedsAdded>>
* <<DatafeedsRemoved>>
* <<SavedObjectsCreated>>
* <<SavedObjectsDeleted>>
* <<SyncDatafeed>>
* <<SyncJob>>
* <<SyncModel>>
* <<SyncResponse>>
* <<SyncSuccess>>

[[DatafeedsAdded]]
=== `DatafeedsAdded`

If a saved object for an anomaly detection job is missing a datafeed identifier, it is added when you run the sync machine learning saved objects API.


==== Example

[source,json]
--------
{}

--------

[[DatafeedsRemoved]]
=== `DatafeedsRemoved`

If a saved object for an anomaly detection job references a datafeed that no longer exists, it is deleted when you run the sync machine learning saved objects API.


==== Example

[source,json]
--------
{}

--------

[[SavedObjectsCreated]]
=== `SavedObjectsCreated`

If saved objects are missing for machine learning jobs or trained models, they are created when you run the sync machine learning saved objects API.


==== Properties

`anomaly-detector` (++map[string,++<<SyncJob,`SyncJob`>>++]++)::
This object is present if there are anomaly detection jobs affected by the synchronization.


`data-frame-analytics` (++map[string,++<<SyncJob,`SyncJob`>>++]++)::
This object is present if there are data frame analytics jobs affected by the synchronization.


`trained-model` (++map[string,++<<SyncModel,`SyncModel`>>++]++)::
This object is present if there are trained models affected by the synchronization.


==== Example

[source,json]
--------
{
   "anomaly-detector" : {
      "some_property" : {
         "success" : {}
      }
   },
   "data-frame-analytics" : {
      "some_property" : {
         "success" : {}
      }
   },
   "trained-model" : {
      "some_property" : {
         "success" : {}
      }
   }
}

--------

[[SavedObjectsDeleted]]
=== `SavedObjectsDeleted`

If saved objects exist for machine learning jobs or trained models that no longer exist, they are deleted when you run the sync machine learning saved objects API.


==== Properties

`anomaly-detector` (++map[string,++<<SyncJob,`SyncJob`>>++]++)::
This object is present if there are anomaly detection jobs affected by the synchronization.


`data-frame-analytics` (++map[string,++<<SyncJob,`SyncJob`>>++]++)::
This object is present if there are data frame analytics jobs affected by the synchronization.


`trained-model` (++map[string,++<<SyncModel,`SyncModel`>>++]++)::
This object is present if there are trained models affected by the synchronization.


==== Example

[source,json]
--------
{
   "anomaly-detector" : {
      "some_property" : {
         "success" : {}
      }
   },
   "data-frame-analytics" : {
      "some_property" : {
         "success" : {}
      }
   },
   "trained-model" : {
      "some_property" : {
         "success" : {}
      }
   }
}

--------

[[SyncDatafeed]]
=== `SyncDatafeed`

The sync machine learning saved objects API response contains this object when there are datafeeds affected by the synchronization. There is an object for each relevant datafeed, which contains the synchronization status.


==== Properties

`success` (<<SyncSuccess,`SyncSuccess`>>)::
The success or failure of the synchronization.


==== Example

[source,json]
--------
{
   "success" : {}
}

--------

[[SyncJob]]
=== `SyncJob`

The sync machine learning saved objects API response contains this object when there are machine learning jobs affected by the synchronization. There is an object for each relevant job, which contains the synchronization status.


==== Properties

`success` (<<SyncSuccess,`SyncSuccess`>>)::
The success or failure of the synchronization.


==== Example

[source,json]
--------
{
   "success" : {}
}

--------

[[SyncModel]]
=== `SyncModel`

The sync machine learning saved objects API response contains this object when there are trained models affected by the synchronization. There is an object for each relevant trained model, which contains the synchronization status.


==== Properties

`success` (<<SyncSuccess,`SyncSuccess`>>)::
The success or failure of the synchronization.


==== Example

[source,json]
--------
{
   "success" : {}
}

--------

[[SyncResponse]]
=== `SyncResponse`

A list of machine learning saved objects that required synchronization.


==== Properties

`datafeedsAdded` (<<DatafeedsAdded,`DatafeedsAdded`>>)::
If a saved object for an anomaly detection job is missing a datafeed identifier, it is added when you run the sync machine learning saved objects API.


`datafeedsRemoved` (<<DatafeedsRemoved,`DatafeedsRemoved`>>)::
If a saved object for an anomaly detection job references a datafeed that no longer exists, it is deleted when you run the sync machine learning saved objects API.


`savedObjectsCreated` (<<SavedObjectsCreated,`SavedObjectsCreated`>>)::
If saved objects are missing for machine learning jobs or trained models, they are created when you run the sync machine learning saved objects API.


`savedObjectsDeleted` (<<SavedObjectsDeleted,`SavedObjectsDeleted`>>)::
If saved objects exist for machine learning jobs or trained models that no longer exist, they are deleted when you run the sync machine learning saved objects API.


==== Example

[source,json]
--------
{
   "datafeedsAdded" : {},
   "datafeedsRemoved" : {},
   "savedObjectsCreated" : {
      "anomaly-detector" : {
         "some_property" : {
            "success" : {}
         }
      },
      "data-frame-analytics" : {
         "some_property" : {
            "success" : {}
         }
      },
      "trained-model" : {
         "some_property" : {
            "success" : {}
         }
      }
   },
   "savedObjectsDeleted" : {
      "anomaly-detector" : {
         "some_property" : {
            "success" : {}
         }
      },
      "data-frame-analytics" : {
         "some_property" : {
            "success" : {}
         }
      },
      "trained-model" : {
         "some_property" : {
            "success" : {}
         }
      }
   }
}

--------

[[SyncSuccess]]
=== `SyncSuccess`

The success or failure of the synchronization.


==== Example

[source,json]
--------
{}

--------
