[[Machine_learning_APIs-definitions]]
== Definitions

* <<MLSyncResponse>>
* <<MLSyncResponse-Datafeeds>>
* <<MLSyncResponse-Jobs>>
* <<MLSyncResponse-Models>>
* <<MLSyncResponse-SavedObjectsCreated>>
* <<MLSyncResponse-SavedObjectsDeleted>>

[[MLSyncResponse]]
=== `MLSyncResponse`

The sync machine learning saved objects API returns this list of machine learning saved objects that required synchronization.


==== Properties

`datafeedsAdded` (++map[string,++<<MLSyncResponse-Datafeeds,`MLSyncResponse-Datafeeds`>>++]++)::
If a saved object for an anomaly detection job is missing a datafeed identifier, it is added when you run the sync machine learning saved objects API.


`datafeedsRemoved` (++map[string,++<<MLSyncResponse-Datafeeds,`MLSyncResponse-Datafeeds`>>++]++)::
If a saved object for an anomaly detection job references a datafeed that no longer exists, it is deleted when you run the sync machine learning saved objects API.


`savedObjectsCreated` (<<MLSyncResponse-SavedObjectsCreated,`MLSyncResponse-SavedObjectsCreated`>>)::
If saved objects are missing for machine learning jobs or trained models, they are created when you run the sync machine learning saved objects API.


`savedObjectsDeleted` (<<MLSyncResponse-SavedObjectsDeleted,`MLSyncResponse-SavedObjectsDeleted`>>)::
If saved objects exist for machine learning jobs or trained models that no longer exist, they are deleted when you run the sync machine learning saved objects API.


==== Example

[source,json]
--------
{
   "datafeedsAdded" : {
      "some_property" : {
         "success" : true
      }
   },
   "datafeedsRemoved" : {
      "some_property" : {
         "success" : true
      }
   },
   "savedObjectsCreated" : {
      "anomaly-detector" : {
         "some_property" : {
            "success" : true
         }
      },
      "data-frame-analytics" : {
         "some_property" : {
            "success" : true
         }
      },
      "trained-model" : {
         "some_property" : {
            "success" : true
         }
      }
   },
   "savedObjectsDeleted" : {
      "anomaly-detector" : {
         "some_property" : {
            "success" : true
         }
      },
      "data-frame-analytics" : {
         "some_property" : {
            "success" : true
         }
      },
      "trained-model" : {
         "some_property" : {
            "success" : true
         }
      }
   }
}

--------

[[MLSyncResponse-Datafeeds]]
=== `MLSyncResponse-Datafeeds`

The sync machine learning saved objects API response contains this object when there are datafeeds affected by the synchronization. There is an object for each relevant datafeed, which contains the synchronization status.


==== Properties

`success` (+boolean+)::
The success or failure of the synchronization.


==== Example

[source,json]
--------
{
   "success" : true
}

--------

[[MLSyncResponse-Jobs]]
=== `MLSyncResponse-Jobs`

The sync machine learning saved objects API response contains this object when there are machine learning jobs affected by the synchronization. There is an object for each relevant job, which contains the synchronization status.


==== Properties

`success` (+boolean+)::
The success or failure of the synchronization.


==== Example

[source,json]
--------
{
   "success" : true
}

--------

[[MLSyncResponse-Models]]
=== `MLSyncResponse-Models`

The sync machine learning saved objects API response contains this object when there are trained models affected by the synchronization. There is an object for each relevant trained model, which contains the synchronization status.


==== Properties

`success` (+boolean+)::
The success or failure of the synchronization.


==== Example

[source,json]
--------
{
   "success" : true
}

--------

[[MLSyncResponse-SavedObjectsCreated]]
=== `MLSyncResponse-SavedObjectsCreated`

If saved objects are missing for machine learning jobs or trained models, they are created when you run the sync machine learning saved objects API.


==== Properties

`anomaly-detector` (++map[string,++<<MLSyncResponse-Jobs,`MLSyncResponse-Jobs`>>++]++)::
This object is present if there are anomaly detection jobs affected by the synchronization.


`data-frame-analytics` (++map[string,++<<MLSyncResponse-Jobs,`MLSyncResponse-Jobs`>>++]++)::
This object is present if there are data frame analytics jobs affected by the synchronization.


`trained-model` (++map[string,++<<MLSyncResponse-Models,`MLSyncResponse-Models`>>++]++)::
This object is present if there are trained models affected by the synchronization.


==== Example

[source,json]
--------
{
   "anomaly-detector" : {
      "some_property" : {
         "success" : true
      }
   },
   "data-frame-analytics" : {
      "some_property" : {
         "success" : true
      }
   },
   "trained-model" : {
      "some_property" : {
         "success" : true
      }
   }
}

--------

[[MLSyncResponse-SavedObjectsDeleted]]
=== `MLSyncResponse-SavedObjectsDeleted`

If saved objects exist for machine learning jobs or trained models that no longer exist, they are deleted when you run the sync machine learning saved objects API.


==== Properties

`anomaly-detector` (++map[string,++<<MLSyncResponse-Jobs,`MLSyncResponse-Jobs`>>++]++)::
This object is present if there are anomaly detection jobs affected by the synchronization.


`data-frame-analytics` (++map[string,++<<MLSyncResponse-Jobs,`MLSyncResponse-Jobs`>>++]++)::
This object is present if there are data frame analytics jobs affected by the synchronization.


`trained-model` (++map[string,++<<MLSyncResponse-Models,`MLSyncResponse-Models`>>++]++)::
This object is present if there are trained models affected by the synchronization.


==== Example

[source,json]
--------
{
   "anomaly-detector" : {
      "some_property" : {
         "success" : true
      }
   },
   "data-frame-analytics" : {
      "some_property" : {
         "success" : true
      }
   },
   "trained-model" : {
      "some_property" : {
         "success" : true
      }
   }
}

--------
