[[osquery-manager-saved-queries-api-update]]
=== Update saved query API
++++
<titleabbrev>Update saved query</titleabbrev>
++++

experimental[] Update saved queries.

WARNING: You cannot update a prebuilt saved query (`prebuilt = true`).


[[osquery-manager-saved-queries-api-update-request]]
==== Request

`PUT <kibana host>:<port>/api/osquery/saved_queries/<id>`

`PUT <kibana host>:<port>/s/<space_id>/api/osquery/saved_queries/<id>`


[[osquery-manager-saved-queries-api-update-path-params]]
==== Path parameters

`space_id`::
  (Optional, string) An identifier for the space. If `space_id` is not provided in the URL, the default space is used.

`id`::
  (Required, string) The ID of the saved query you want to update.


[[osquery-manager-saved-queries-api-update-body-params]]
==== Request body

`id`:: (Required, string) The name of the saved query.

`description`:: (Optional, string) A description of the saved query.

`platform`:: (Optional, string) Restrict this query to a given platform, default is 'all' platforms; you may use commas to set multiple platforms (e.g. 'linux,darwin').

`query`:: (Required, string) The SQL query to run.

`version`:: (Optional, string) Only run on osquery versions greater than or equal-to this version string

`internal`:: (Optional, string) An interval in seconds to run the query.

`ecs_mapping`:: (Optional, object) Config allows to map osquery results columns or static values to ECS fields.


[[osquery-manager-saved-queries-api-update-request-codes]]
==== Response code

`200`::
    Indicates a successful call.


[[osquery-manager-saved-queries-api-update-example]]
==== Examples

Update a name of the <my_saved query> saved query:

[source,sh]
--------------------------------------------------
$ curl -X PUT api/osquery/saved_queries/<id> \
{
  "id": "updated_my_saved_query_name",
}

--------------------------------------------------
// KIBANA


The API returns the saved query saved object:

[source,sh]
--------------------------------------------------
{
    "data": {...}
}
--------------------------------------------------
