export declare const formulas: {
    cpuUsage: import("../../../shared/metrics/types").SchemaBasedFormula;
    cpuUsageIowait: import("../../../shared/metrics/types").SchemaBasedFormula;
    cpuUsageIrq: import("../../../shared/metrics/types").SchemaBasedFormula;
    cpuUsageNice: import("../../../shared/metrics/types").SchemaBasedFormula;
    cpuUsageSoftirq: import("../../../shared/metrics/types").SchemaBasedFormula;
    cpuUsageSteal: import("../../../shared/metrics/types").SchemaBasedFormula;
    cpuUsageUser: import("../../../shared/metrics/types").SchemaBasedFormula;
    cpuUsageSystem: import("../../../shared/metrics/types").SchemaBasedFormula;
    diskIORead: import("../../../shared/metrics/types").SchemaBasedFormula;
    diskIOWrite: import("../../../shared/metrics/types").SchemaBasedFormula;
    diskReadThroughput: import("../../../shared/metrics/types").SchemaBasedFormula;
    diskWriteThroughput: import("../../../shared/metrics/types").SchemaBasedFormula;
    diskSpaceAvailable: import("../../../shared/metrics/types").SchemaBasedFormula;
    diskUsage: import("../../../shared/metrics/types").SchemaBasedFormula;
    diskUsageAverage: import("../../../shared/metrics/types").SchemaBasedFormula;
    hostCount: import("@kbn/lens-embeddable-utils").LensBaseLayer;
    logRate: import("@kbn/lens-embeddable-utils").LensBaseLayer;
    normalizedLoad1m: import("../../../shared/metrics/types").SchemaBasedFormula;
    load1m: import("../../../shared/metrics/types").SchemaBasedFormula;
    load5m: import("../../../shared/metrics/types").SchemaBasedFormula;
    load15m: import("../../../shared/metrics/types").SchemaBasedFormula;
    memoryUsage: import("../../../shared/metrics/types").SchemaBasedFormula;
    memoryFree: import("../../../shared/metrics/types").SchemaBasedFormula;
    memoryUsed: import("../../../shared/metrics/types").SchemaBasedFormula;
    memoryFreeExcludingCache: import("../../../shared/metrics/types").SchemaBasedFormula;
    memoryCache: import("../../../shared/metrics/types").SchemaBasedFormula;
    rx: import("../../../shared/metrics/types").SchemaBasedFormula;
    tx: import("../../../shared/metrics/types").SchemaBasedFormula;
};
export type HostFormulas = typeof formulas;
