/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/**
 * Hand-written S1–S3 snapshot matching the exec-brief-scenario ground truth
 * (investigation 12). Test/dev only.
 *
 * S1 planted: privileged a.rodriguez → LAPTOP-FIN03 → jump-box-01 → docker-host-prod-01, unaddressed.
 * S2 handled: j.chen MFA bombing → session hijack, case open, alerts acknowledged.
 * S3 no-AD:   svc-build → build-runner-02 → fileserver-03, linked by co-alerts + relationships only.
 */

import type { BriefEntity, BriefSnapshot } from '../types';

export const FIXTURE_NOW = '2026-10-08T12:00:00.000Z';

const day = (offset: number, hour = 9): string => {
  const d = new Date(FIXTURE_NOW);
  d.setUTCDate(d.getUTCDate() + offset);
  d.setUTCHours(hour, 0, 0, 0);
  return d.toISOString();
};

export const EUID = {
  rodriguez: 'user:a.rodriguez@acme.com@okta',
  laptopFin: 'host:LAPTOP-FIN03',
  jumpBox: 'host:jump-box-01',
  prodHost: 'host:docker-host-prod-01',
  chen: 'user:j.chen@acme.com@okta',
  laptopMkt: 'host:LAPTOP-MKT07',
  svcBuild: 'user:svc-build@build-runner-02@local',
  buildRunner: 'host:build-runner-02',
  fileServer: 'host:fileserver-03',
  dc: 'host:DC01',
  noiseUser: 'user:t.nguyen@acme.com@okta',
} as const;

const entity = (
  e: Omit<BriefEntity, 'watchlists' | 'isPrivileged' | 'aliases'> &
    Partial<Pick<BriefEntity, 'watchlists' | 'isPrivileged' | 'aliases'>>
): BriefEntity => ({
  watchlists: [],
  isPrivileged: false,
  aliases: [],
  ...e,
});

export const FIXTURE_ENTITIES: Record<string, BriefEntity> = {
  [EUID.rodriguez]: entity({
    evidenceId: 'ENT-1',
    euid: EUID.rodriguez,
    type: 'user',
    name: 'a.rodriguez',
    riskScoreNorm: 75,
    riskLevel: 'High',
    watchlists: ['Privileged Users'],
    isPrivileged: true,
    aliases: [
      'user:a.rodriguez@LAPTOP-FIN03@local',
      'user:a.rodriguez@jump-box-01@local',
      'user:a.rodriguez@docker-host-prod-01@local',
    ],
    riskTrend: [
      { t: day(-5), v: 22 },
      { t: day(-4), v: 41 },
      { t: day(-3), v: 58 },
      { t: day(-2), v: 69 },
      { t: day(-1), v: 75 },
    ],
  }),
  [EUID.laptopFin]: entity({
    evidenceId: 'ENT-2',
    euid: EUID.laptopFin,
    type: 'host',
    name: 'LAPTOP-FIN03',
    riskScoreNorm: 76,
    riskLevel: 'High',
    criticality: 'medium_impact',
  }),
  [EUID.jumpBox]: entity({
    evidenceId: 'ENT-3',
    euid: EUID.jumpBox,
    type: 'host',
    name: 'jump-box-01',
    riskScoreNorm: 72,
    riskLevel: 'High',
    criticality: 'high_impact',
  }),
  [EUID.prodHost]: entity({
    evidenceId: 'ENT-4',
    euid: EUID.prodHost,
    type: 'host',
    name: 'docker-host-prod-01',
    riskScoreNorm: 78,
    riskLevel: 'High',
    criticality: 'extreme_impact',
    vulnerabilities: { critical: 2, high: 5 },
    riskTrend: [
      { t: day(-3), v: 12 },
      { t: day(-2), v: 49 },
      { t: day(-1), v: 78 },
    ],
  }),
  [EUID.chen]: entity({
    evidenceId: 'ENT-5',
    euid: EUID.chen,
    type: 'user',
    name: 'j.chen',
    riskScoreNorm: 64,
    riskLevel: 'Moderate',
    aliases: ['user:j.chen@LAPTOP-MKT07@local'],
  }),
  [EUID.laptopMkt]: entity({
    evidenceId: 'ENT-6',
    euid: EUID.laptopMkt,
    type: 'host',
    name: 'LAPTOP-MKT07',
    riskScoreNorm: 51,
    riskLevel: 'Moderate',
    criticality: 'low_impact',
  }),
  [EUID.svcBuild]: entity({
    evidenceId: 'ENT-7',
    euid: EUID.svcBuild,
    type: 'user',
    name: 'svc-build',
    riskScoreNorm: 55,
    riskLevel: 'Moderate',
  }),
  [EUID.buildRunner]: entity({
    evidenceId: 'ENT-8',
    euid: EUID.buildRunner,
    type: 'host',
    name: 'build-runner-02',
    riskScoreNorm: 62,
    riskLevel: 'Moderate',
    criticality: 'medium_impact',
  }),
  [EUID.fileServer]: entity({
    evidenceId: 'ENT-9',
    euid: EUID.fileServer,
    type: 'host',
    name: 'fileserver-03',
    riskScoreNorm: 44,
    riskLevel: 'Moderate',
  }),
  [EUID.dc]: entity({
    evidenceId: 'ENT-10',
    euid: EUID.dc,
    type: 'host',
    name: 'DC01',
    riskScoreNorm: 30,
    riskLevel: 'Low',
    criticality: 'extreme_impact',
    isHub: true,
  }),
  [EUID.noiseUser]: entity({
    evidenceId: 'ENT-11',
    euid: EUID.noiseUser,
    type: 'user',
    name: 't.nguyen',
    riskScoreNorm: 71,
    riskLevel: 'High',
  }),
};

export const FIXTURE_SNAPSHOT: BriefSnapshot = {
  spaceId: 'default',
  generatedAt: FIXTURE_NOW,
  timeRange: { from: day(-7, 12), to: FIXTURE_NOW, range: '7d' },
  glance: {
    stats: [
      { id: 'postureScore', value: 49, previous: 41, delta: 8, upIsBad: true },
      { id: 'materialRiskEntities', value: 6, previous: 2, delta: 4, upIsBad: true },
      { id: 'activeSignals', value: 31, previous: 19, delta: 12, upIsBad: true },
      { id: 'stagesWithActivity', value: 7, previous: 4, delta: 3, upIsBad: true },
    ],
    needsAttention: [
      {
        id: 'entitiesWithAlerts',
        status: 'ok',
        count: 12,
        previousCount: 7,
        delta: 5,
        deltaPct: 71,
        trend: [
          { t: day(-6), v: 3 },
          { t: day(-4), v: 5 },
          { t: day(-2), v: 9 },
          { t: day(0), v: 12 },
        ],
        sample: [EUID.prodHost, EUID.laptopFin, EUID.jumpBox, EUID.rodriguez],
        sampleTruncated: true,
      },
      {
        id: 'riskMovers',
        status: 'ok',
        count: 4,
        previousCount: 1,
        delta: 3,
        deltaPct: 300,
        sample: [EUID.rodriguez, EUID.prodHost, EUID.jumpBox, EUID.chen],
        sampleTruncated: false,
      },
      {
        id: 'newlyHighCritical',
        status: 'ok',
        count: 4,
        previousCount: 0,
        delta: 4,
        sample: [EUID.prodHost, EUID.rodriguez, EUID.jumpBox, EUID.laptopFin],
        sampleTruncated: false,
      },
    ],
    concentration: [
      { type: 'host', level: 'High', count: 3 },
      { type: 'host', level: 'Moderate', count: 4 },
      { type: 'host', level: 'Low', count: 13 },
      { type: 'user', level: 'High', count: 2 },
      { type: 'user', level: 'Moderate', count: 3 },
      { type: 'user', level: 'Low', count: 15 },
    ],
    exposureLeaders: [
      EUID.prodHost,
      EUID.laptopFin,
      EUID.rodriguez,
      EUID.jumpBox,
      EUID.noiseUser,
      EUID.chen,
      EUID.buildRunner,
    ],
  },
  storylines: {
    storylines: [
      {
        evidenceId: 'STORY-1',
        rank: 1,
        score: 1.93,
        severity: 'critical',
        entityEuids: [EUID.rodriguez, EUID.laptopFin, EUID.jumpBox, EUID.prodHost],
        hubEuids: [EUID.dc],
        seeds: [
          {
            kind: 'attack_discovery',
            evidenceId: 'AD-1',
            entityEuids: [EUID.rodriguez, EUID.laptopFin, EUID.jumpBox, EUID.prodHost],
            severity: 0.92,
            at: day(-1, 11),
          },
          {
            kind: 'lead',
            evidenceId: 'LEAD-1',
            entityEuids: [EUID.rodriguez],
            severity: 1,
            at: day(-1, 6),
          },
          {
            kind: 'material_risk',
            evidenceId: 'ENT-4',
            entityEuids: [EUID.prodHost],
            severity: 0.78,
            at: day(-1, 10),
          },
        ],
        edges: [
          {
            type: 'same_ad',
            from: EUID.rodriguez,
            to: EUID.prodHost,
            weight: 1,
            evidenceIds: ['AD-1'],
          },
          {
            type: 'co_alert',
            from: EUID.rodriguez,
            to: EUID.laptopFin,
            weight: 0.8,
            evidenceIds: ['RULE-1'],
          },
          {
            type: 'co_alert',
            from: EUID.rodriguez,
            to: EUID.jumpBox,
            weight: 0.8,
            evidenceIds: ['RULE-2', 'RULE-3'],
          },
          {
            type: 'co_alert',
            from: EUID.rodriguez,
            to: EUID.prodHost,
            weight: 0.8,
            evidenceIds: ['RULE-4'],
          },
          {
            type: 'accesses_frequently',
            from: EUID.rodriguez,
            to: EUID.laptopFin,
            weight: 0.3,
            evidenceIds: [],
          },
          {
            type: 'accesses_infrequently',
            from: EUID.rodriguez,
            to: EUID.jumpBox,
            weight: 0.6,
            evidenceIds: ['EVT-1-3'],
          },
          {
            type: 'accesses_infrequently',
            from: EUID.rodriguez,
            to: EUID.prodHost,
            weight: 0.6,
            evidenceIds: ['EVT-1-5'],
          },
        ],
        events: [
          {
            evidenceId: 'EVT-1-1',
            type: 'alert_first',
            at: day(-5, 9),
            entityEuids: [EUID.laptopFin, EUID.rodriguez],
            tacticId: 'TA0001',
            summary:
              'First Initial Access alert: "Suspicious Email Attachment Opened" on LAPTOP-FIN03',
            sourceEvidenceIds: ['RULE-5'],
          },
          {
            evidenceId: 'EVT-1-2',
            type: 'alert_first',
            at: day(-4, 14),
            entityEuids: [EUID.laptopFin, EUID.rodriguez],
            tacticId: 'TA0006',
            summary: 'First Credential Access alert: "LSASS Memory Access" on LAPTOP-FIN03',
            sourceEvidenceIds: ['RULE-1'],
          },
          {
            evidenceId: 'EVT-1-3',
            type: 'relationship_first_seen',
            at: day(-3, 2),
            entityEuids: [EUID.rodriguez, EUID.jumpBox],
            summary: 'First-ever logon by a.rodriguez to jump-box-01 (RDP)',
            sourceEvidenceIds: [],
          },
          {
            evidenceId: 'EVT-1-4',
            type: 'alert_first',
            at: day(-3, 2),
            entityEuids: [EUID.jumpBox, EUID.rodriguez],
            tacticId: 'TA0008',
            summary:
              'First Lateral Movement alert: "Outbound RDP to Internal Jump Host" on jump-box-01',
            sourceEvidenceIds: ['RULE-2'],
          },
          {
            evidenceId: 'EVT-1-5',
            type: 'relationship_first_seen',
            at: day(-2, 3),
            entityEuids: [EUID.rodriguez, EUID.prodHost],
            summary: 'First-ever logon by a.rodriguez to docker-host-prod-01 (SSH)',
            sourceEvidenceIds: [],
          },
          {
            evidenceId: 'EVT-1-6',
            type: 'alert_first',
            at: day(-2, 3),
            entityEuids: [EUID.jumpBox, EUID.rodriguez],
            tacticId: 'TA0004',
            summary:
              'First Privilege Escalation alert: "Suspicious sudo Escalation" on jump-box-01',
            sourceEvidenceIds: ['RULE-3'],
          },
          {
            evidenceId: 'EVT-1-7',
            type: 'risk_jump',
            at: day(-2, 23),
            entityEuids: [EUID.prodHost],
            summary: 'docker-host-prod-01 risk 12 → 49 (Moderate)',
            sourceEvidenceIds: ['ENT-4'],
          },
          {
            evidenceId: 'EVT-1-8',
            type: 'alert_first',
            at: day(-1, 10),
            entityEuids: [EUID.prodHost, EUID.rodriguez],
            tacticId: 'TA0002',
            summary:
              'First Execution alert: "Untrusted Container Image Deployed on Production Host" on docker-host-prod-01',
            sourceEvidenceIds: ['RULE-4'],
          },
          {
            evidenceId: 'EVT-1-9',
            type: 'ad_generated',
            at: day(-1, 11),
            entityEuids: [EUID.rodriguez, EUID.laptopFin, EUID.jumpBox, EUID.prodHost],
            summary:
              'Attack Discovery: "Credential theft leading to production container deployment"',
            sourceEvidenceIds: ['AD-1'],
          },
        ],
        eventsTruncated: 0,
        tacticIds: ['TA0001', 'TA0002', 'TA0004', 'TA0006', 'TA0008'],
        linkStrength: 'strong',
        response: {
          state: 'unaddressed',
          cases: [],
          alerts: { open: 23, acknowledged: 0, closed: 0 },
        },
      },
      {
        evidenceId: 'STORY-2',
        rank: 2,
        score: 0.41,
        severity: 'high',
        entityEuids: [EUID.chen, EUID.laptopMkt],
        hubEuids: [],
        seeds: [
          {
            kind: 'attack_discovery',
            evidenceId: 'AD-2',
            entityEuids: [EUID.chen, EUID.laptopMkt],
            severity: 0.81,
            at: day(-2, 16),
          },
        ],
        edges: [
          {
            type: 'same_ad',
            from: EUID.chen,
            to: EUID.laptopMkt,
            weight: 1,
            evidenceIds: ['AD-2'],
          },
          { type: 'owns', from: EUID.chen, to: EUID.laptopMkt, weight: 0.6, evidenceIds: [] },
        ],
        events: [
          {
            evidenceId: 'EVT-2-1',
            type: 'alert_first',
            at: day(-2, 14),
            entityEuids: [EUID.chen],
            tacticId: 'TA0006',
            summary: 'First Credential Access alert: "Okta MFA Bombing" for j.chen',
            sourceEvidenceIds: ['RULE-6'],
          },
          {
            evidenceId: 'EVT-2-2',
            type: 'alert_first',
            at: day(-2, 15),
            entityEuids: [EUID.chen, EUID.laptopMkt],
            tacticId: 'TA0002',
            summary: 'First Execution alert: "Suspicious MS Office Child Process" on LAPTOP-MKT07',
            sourceEvidenceIds: ['RULE-7'],
          },
          {
            evidenceId: 'EVT-2-3',
            type: 'case_opened',
            at: day(-1, 9),
            entityEuids: [EUID.chen, EUID.laptopMkt],
            summary: 'Case opened: "MFA bombing on j.chen"',
            sourceEvidenceIds: ['CASE-1'],
          },
        ],
        eventsTruncated: 0,
        tacticIds: ['TA0002', 'TA0006'],
        linkStrength: 'strong',
        response: {
          state: 'in_progress',
          cases: [
            {
              evidenceId: 'CASE-1',
              caseId: 'case-s2',
              title: 'MFA bombing on j.chen',
              status: 'in-progress',
            },
          ],
          alerts: { open: 0, acknowledged: 6, closed: 0 },
        },
      },
      {
        evidenceId: 'STORY-3',
        rank: 3,
        score: 0.37,
        severity: 'medium',
        entityEuids: [EUID.svcBuild, EUID.buildRunner, EUID.fileServer],
        hubEuids: [],
        seeds: [
          {
            kind: 'risk_mover',
            evidenceId: 'ENT-8',
            entityEuids: [EUID.buildRunner],
            severity: 0.62,
            at: day(-1, 18),
          },
        ],
        edges: [
          {
            type: 'co_alert',
            from: EUID.svcBuild,
            to: EUID.buildRunner,
            weight: 0.8,
            evidenceIds: ['RULE-8', 'RULE-9'],
          },
          {
            type: 'communicates_with',
            from: EUID.buildRunner,
            to: EUID.fileServer,
            weight: 0.3,
            evidenceIds: [],
          },
        ],
        events: [
          {
            evidenceId: 'EVT-3-1',
            type: 'alert_first',
            at: day(-3, 22),
            entityEuids: [EUID.buildRunner, EUID.svcBuild],
            tacticId: 'TA0006',
            summary:
              'First Credential Access alert: "Password Spraying via SSH" on build-runner-02',
            sourceEvidenceIds: ['RULE-8'],
          },
          {
            evidenceId: 'EVT-3-2',
            type: 'alert_first',
            at: day(-1, 18),
            entityEuids: [EUID.buildRunner, EUID.svcBuild],
            tacticId: 'TA0010',
            summary:
              'First Exfiltration alert: "Potential Data Exfiltration Through Curl" on build-runner-02',
            sourceEvidenceIds: ['RULE-9'],
          },
        ],
        eventsTruncated: 0,
        tacticIds: ['TA0006', 'TA0010'],
        linkStrength: 'moderate',
        response: {
          state: 'unaddressed',
          cases: [],
          alerts: { open: 7, acknowledged: 0, closed: 0 },
        },
      },
    ],
    otherNotableEntities: [EUID.noiseUser],
    trace: [
      {
        action: 'union',
        detail: 'AD-1 ∪ LEAD-1 via same golden entity user:a.rodriguez@acme.com@okta',
      },
      { action: 'union', detail: 'AD-1 ∪ ENT-4 via AD membership' },
      {
        action: 'skip_hub',
        detail: 'host:DC01 (extreme_impact, degree 37) attached, not bridging',
      },
      {
        action: 'drop_rank',
        detail: 'user:t.nguyen@acme.com@okta has no mergeable links; listed as other notable',
      },
    ],
  },
  blindSpots: {
    attackStages: {
      stages: [
        {
          evidenceId: 'TAC-TA0001',
          tacticId: 'TA0001',
          tacticName: 'Initial Access',
          position: 2,
          observed: { alerts: 3, attackDiscoveries: 1, mlAnomalies: 0 },
          coverage: { enabled: 9, effective: 8 },
          flag: 'none',
          topRuleEvidenceIds: ['RULE-5'],
        },
        {
          evidenceId: 'TAC-TA0002',
          tacticId: 'TA0002',
          tacticName: 'Execution',
          position: 3,
          topTechnique: { id: 'T1610', name: 'Deploy Container' },
          observed: { alerts: 8, attackDiscoveries: 2, mlAnomalies: 0 },
          coverage: { enabled: 14, effective: 12 },
          flag: 'none',
          topRuleEvidenceIds: ['RULE-4', 'RULE-7'],
        },
        {
          evidenceId: 'TAC-TA0004',
          tacticId: 'TA0004',
          tacticName: 'Privilege Escalation',
          position: 5,
          topTechnique: { id: 'T1548.003', name: 'Sudo and Sudo Caching' },
          observed: { alerts: 5, attackDiscoveries: 1, mlAnomalies: 0 },
          coverage: { enabled: 6, effective: 5 },
          flag: 'none',
          topRuleEvidenceIds: ['RULE-3'],
        },
        {
          evidenceId: 'TAC-TA0006',
          tacticId: 'TA0006',
          tacticName: 'Credential Access',
          position: 8,
          topTechnique: { id: 'T1003.001', name: 'LSASS Memory' },
          observed: { alerts: 19, attackDiscoveries: 2, mlAnomalies: 0 },
          coverage: { enabled: 11, effective: 10 },
          flag: 'none',
          topRuleEvidenceIds: ['RULE-1', 'RULE-6', 'RULE-8'],
        },
        {
          evidenceId: 'TAC-TA0008',
          tacticId: 'TA0008',
          tacticName: 'Lateral Movement',
          position: 10,
          topTechnique: { id: 'T1021.001', name: 'Remote Desktop Protocol' },
          observed: { alerts: 6, attackDiscoveries: 1, mlAnomalies: 1 },
          coverage: { enabled: 2, effective: 1 },
          flag: 'limited_coverage',
          topRuleEvidenceIds: ['RULE-2'],
        },
        {
          evidenceId: 'TAC-TA0010',
          tacticId: 'TA0010',
          tacticName: 'Exfiltration',
          position: 13,
          observed: { alerts: 2, attackDiscoveries: 0, mlAnomalies: 0 },
          coverage: { enabled: 4, effective: 4 },
          flag: 'none',
          topRuleEvidenceIds: ['RULE-9'],
        },
      ],
      unmapped: { alerts: 9, share: 0.18, topRuleEvidenceIds: ['RULE-10'] },
    },
    gaps: [
      {
        evidenceId: 'GAP-B6',
        signal: 'B6',
        group: 'context_missing',
        severity: 'warning',
        title: 'No asset criticality on 1 material-risk entity',
        value: 1,
        fixHref: '/app/security/entity_analytics_asset_criticality',
        fixLabel: 'Assign criticality',
        entityEuids: [EUID.laptopFin],
      },
      {
        evidenceId: 'GAP-B5',
        signal: 'B5',
        group: 'context_missing',
        severity: 'info',
        title: '14 local user accounts are not resolved to an identity',
        value: 14,
        fixHref: '/app/security/entity_analytics_entity_store',
        fixLabel: 'Review resolution',
      },
      {
        evidenceId: 'GAP-B12',
        signal: 'B12',
        group: 'analytics_not_running',
        severity: 'info',
        title: 'No security ML jobs are running',
        fixHref: '/app/ml/jobs',
        fixLabel: 'Set up ML',
      },
      {
        evidenceId: 'GAP-B16',
        signal: 'B16',
        group: 'detection_coverage',
        severity: 'warning',
        title: '18% of alerts have no MITRE ATT&CK mapping',
        value: 18,
        fixHref: '/app/security/rules_coverage_overview',
        fixLabel: 'Review coverage',
      },
    ],
  },
  entities: FIXTURE_ENTITIES,
  catalog: {
    'ENT-1': { kind: 'entity', euid: EUID.rodriguez },
    'ENT-2': { kind: 'entity', euid: EUID.laptopFin },
    'ENT-3': { kind: 'entity', euid: EUID.jumpBox },
    'ENT-4': { kind: 'entity', euid: EUID.prodHost },
    'ENT-5': { kind: 'entity', euid: EUID.chen },
    'ENT-6': { kind: 'entity', euid: EUID.laptopMkt },
    'ENT-7': { kind: 'entity', euid: EUID.svcBuild },
    'ENT-8': { kind: 'entity', euid: EUID.buildRunner },
    'ENT-9': { kind: 'entity', euid: EUID.fileServer },
    'ENT-10': { kind: 'entity', euid: EUID.dc },
    'ENT-11': { kind: 'entity', euid: EUID.noiseUser },
    'RULE-1': {
      kind: 'rule',
      ruleId: 'rule-lsass',
      name: 'LSASS Memory Access',
      severity: 'critical',
      alertCount: 13,
      tacticIds: ['TA0006'],
      techniqueIds: ['T1003.001'],
    },
    'RULE-2': {
      kind: 'rule',
      ruleId: 'rule-rdp-jump',
      name: 'Outbound RDP to Internal Jump Host',
      severity: 'high',
      alertCount: 5,
      tacticIds: ['TA0008'],
      techniqueIds: ['T1021.001'],
    },
    'RULE-3': {
      kind: 'rule',
      ruleId: 'rule-sudo',
      name: 'Suspicious sudo Escalation',
      severity: 'high',
      alertCount: 5,
      tacticIds: ['TA0004'],
      techniqueIds: ['T1548.003'],
    },
    'RULE-4': {
      kind: 'rule',
      ruleId: 'rule-container',
      name: 'Untrusted Container Image Deployed on Production Host',
      severity: 'critical',
      alertCount: 5,
      tacticIds: ['TA0002'],
      techniqueIds: ['T1610'],
    },
    'RULE-5': {
      kind: 'rule',
      ruleId: 'rule-attachment',
      name: 'Suspicious Email Attachment Opened',
      severity: 'medium',
      alertCount: 3,
      tacticIds: ['TA0001'],
      techniqueIds: ['T1566.001'],
    },
    'RULE-6': {
      kind: 'rule',
      ruleId: 'rule-okta-mfa',
      name: 'Okta MFA Bombing',
      severity: 'high',
      alertCount: 4,
      tacticIds: ['TA0006'],
      techniqueIds: ['T1621'],
    },
    'RULE-7': {
      kind: 'rule',
      ruleId: 'rule-office-child',
      name: 'Suspicious MS Office Child Process',
      severity: 'medium',
      alertCount: 2,
      tacticIds: ['TA0002'],
      techniqueIds: ['T1204.002'],
    },
    'RULE-8': {
      kind: 'rule',
      ruleId: 'rule-ssh-spray',
      name: 'Password Spraying via SSH',
      severity: 'medium',
      alertCount: 5,
      tacticIds: ['TA0006'],
      techniqueIds: ['T1110.003'],
    },
    'RULE-9': {
      kind: 'rule',
      ruleId: 'rule-curl-exfil',
      name: 'Potential Data Exfiltration Through Curl',
      severity: 'medium',
      alertCount: 2,
      tacticIds: ['TA0010'],
      techniqueIds: ['T1048'],
    },
    'RULE-10': {
      kind: 'rule',
      ruleId: 'rule-edr-promotion',
      name: 'External EDR Alert Promotion',
      severity: 'high',
      alertCount: 9,
      tacticIds: [],
      techniqueIds: [],
    },
    'AD-1': {
      kind: 'attack_discovery',
      id: 'ad-s1',
      title: 'Credential theft leading to production container deployment',
      riskScore: 92,
      workflowStatus: 'open',
      alertCount: 21,
      tacticIds: ['TA0001', 'TA0002', 'TA0004', 'TA0006', 'TA0008'],
    },
    'AD-2': {
      kind: 'attack_discovery',
      id: 'ad-s2',
      title: 'MFA bombing followed by malicious Office execution',
      riskScore: 81,
      workflowStatus: 'acknowledged',
      alertCount: 6,
      tacticIds: ['TA0002', 'TA0006'],
    },
    'LEAD-1': {
      kind: 'lead',
      id: 'lead-s1',
      title: 'Privileged identity accessing new production hosts',
      priority: 10,
      status: 'active',
    },
    'CASE-1': {
      kind: 'case',
      caseId: 'case-s2',
      title: 'MFA bombing on j.chen',
      status: 'in-progress',
    },
    'TAC-TA0001': { kind: 'tactic', tacticId: 'TA0001' },
    'TAC-TA0002': { kind: 'tactic', tacticId: 'TA0002' },
    'TAC-TA0004': { kind: 'tactic', tacticId: 'TA0004' },
    'TAC-TA0006': { kind: 'tactic', tacticId: 'TA0006' },
    'TAC-TA0008': { kind: 'tactic', tacticId: 'TA0008' },
    'TAC-TA0010': { kind: 'tactic', tacticId: 'TA0010' },
    'GAP-B5': { kind: 'gap', signal: 'B5' },
    'GAP-B6': { kind: 'gap', signal: 'B6' },
    'GAP-B12': { kind: 'gap', signal: 'B12' },
    'GAP-B16': { kind: 'gap', signal: 'B16' },
    'STORY-1': { kind: 'story', rank: 1 },
    'STORY-2': { kind: 'story', rank: 2 },
    'STORY-3': { kind: 'story', rank: 3 },
    'EVT-1-1': { kind: 'event', storyEvidenceId: 'STORY-1' },
    'EVT-1-2': { kind: 'event', storyEvidenceId: 'STORY-1' },
    'EVT-1-3': { kind: 'event', storyEvidenceId: 'STORY-1' },
    'EVT-1-4': { kind: 'event', storyEvidenceId: 'STORY-1' },
    'EVT-1-5': { kind: 'event', storyEvidenceId: 'STORY-1' },
    'EVT-1-6': { kind: 'event', storyEvidenceId: 'STORY-1' },
    'EVT-1-7': { kind: 'event', storyEvidenceId: 'STORY-1' },
    'EVT-1-8': { kind: 'event', storyEvidenceId: 'STORY-1' },
    'EVT-1-9': { kind: 'event', storyEvidenceId: 'STORY-1' },
    'EVT-2-1': { kind: 'event', storyEvidenceId: 'STORY-2' },
    'EVT-2-2': { kind: 'event', storyEvidenceId: 'STORY-2' },
    'EVT-2-3': { kind: 'event', storyEvidenceId: 'STORY-2' },
    'EVT-3-1': { kind: 'event', storyEvidenceId: 'STORY-3' },
    'EVT-3-2': { kind: 'event', storyEvidenceId: 'STORY-3' },
  },
  sources: {
    needsAttention: { status: 'ok', tookMs: 420 },
    posture: { status: 'ok', tookMs: 85 },
    storylines: { status: 'ok', tookMs: 1310 },
    alertsByTactic: { status: 'ok', tookMs: 160 },
    detectionCoverage: { status: 'ok', tookMs: 640 },
    attackDiscovery: { status: 'ok', tookMs: 40 },
    anomalies: { status: 'disabled', tookMs: 0, message: 'No security ML jobs installed' },
  },
};
