[role="xpack"]
[[Security-production-considerations]]
== Security production considerations

++++
<titleabbrev>Security</titleabbrev>
++++
:keywords: administrator, analyst, concept, setup, security
:description: Consider the production components for {kib} security.

[float]
[[enabling-ssl]]
=== Enable SSL

See <<configuring-tls>>.

[float]
[[configuring-kibana-shield]]
=== Use {stack} {security-features}

You can use {stack} {security-features} to control what {es} data users can
access through {kib}.

When {security-features} are enabled, {kib} users have to log in. They need to
have a role granting <<kibana-privileges, {kib} privileges>> as well as access
to the indices they will be working with in {kib}.

If a user loads a {kib} dashboard that accesses data in an index that they
are not authorized to view, they get an error that indicates the index does
not exist.

For more information on granting access to {kib}, see <<xpack-security-authorization>>.

[float]
[[csp-strict-mode]]
=== Require Content Security Policy

{kib} uses a Content Security Policy (CSP) to help prevent the browser from allowing
unsafe scripting, but older browsers will silently ignore this policy. If your
organization does not need to support extremely old
versions of our other supported browsers, we recommend that you enable {kib}'s
`strict` mode for content security policy, which will block access to {kib}
for any browser that does not enforce even a rudimentary set of CSP
protections.

To do this, set `csp.strict` to `true` in your `kibana.yml`:

[source,js]
--------
csp.strict: true
--------
