import type { SavedObjectMigrationContext, SavedObjectUnsanitizedDoc } from '@kbn/core/server';
import type { StoredMapAttributes } from './types';
export declare const savedObjectMigrations: {
    '7.2.0': (doc: SavedObjectUnsanitizedDoc<StoredMapAttributes>, context: SavedObjectMigrationContext) => SavedObjectUnsanitizedDoc<StoredMapAttributes>;
    '7.4.0': (doc: SavedObjectUnsanitizedDoc<StoredMapAttributes>, context: SavedObjectMigrationContext) => {
        attributes: any;
        id: string;
        type: string;
        namespace?: string;
        namespaces?: string[];
        migrationVersion?: import("@kbn/core/server").SavedObjectsMigrationVersion;
        coreMigrationVersion?: string;
        typeMigrationVersion?: string;
        version?: string;
        updated_at?: string;
        updated_by?: string;
        created_at?: string;
        created_by?: string;
        originId?: string;
        managed?: boolean;
        accessControl?: import("@kbn/core/server").SavedObjectAccessControl;
        references?: import("@kbn/core/server").SavedObjectReference[];
    };
    '7.5.0': (doc: SavedObjectUnsanitizedDoc<StoredMapAttributes>, context: SavedObjectMigrationContext) => {
        attributes: any;
        id: string;
        type: string;
        namespace?: string;
        namespaces?: string[];
        migrationVersion?: import("@kbn/core/server").SavedObjectsMigrationVersion;
        coreMigrationVersion?: string;
        typeMigrationVersion?: string;
        version?: string;
        updated_at?: string;
        updated_by?: string;
        created_at?: string;
        created_by?: string;
        originId?: string;
        managed?: boolean;
        accessControl?: import("@kbn/core/server").SavedObjectAccessControl;
        references?: import("@kbn/core/server").SavedObjectReference[];
    };
    '7.6.0': (doc: SavedObjectUnsanitizedDoc<StoredMapAttributes>, context: SavedObjectMigrationContext) => {
        attributes: any;
        id: string;
        type: string;
        namespace?: string;
        namespaces?: string[];
        migrationVersion?: import("@kbn/core/server").SavedObjectsMigrationVersion;
        coreMigrationVersion?: string;
        typeMigrationVersion?: string;
        version?: string;
        updated_at?: string;
        updated_by?: string;
        created_at?: string;
        created_by?: string;
        originId?: string;
        managed?: boolean;
        accessControl?: import("@kbn/core/server").SavedObjectAccessControl;
        references?: import("@kbn/core/server").SavedObjectReference[];
    };
    '7.7.0': (doc: SavedObjectUnsanitizedDoc<StoredMapAttributes>, context: SavedObjectMigrationContext) => SavedObjectUnsanitizedDoc<StoredMapAttributes>;
    '7.8.0': (doc: SavedObjectUnsanitizedDoc<StoredMapAttributes>, context: SavedObjectMigrationContext) => SavedObjectUnsanitizedDoc<StoredMapAttributes>;
    '7.9.0': (doc: SavedObjectUnsanitizedDoc<StoredMapAttributes>, context: SavedObjectMigrationContext) => SavedObjectUnsanitizedDoc<StoredMapAttributes>;
    '7.10.0': (doc: SavedObjectUnsanitizedDoc<StoredMapAttributes>, context: SavedObjectMigrationContext) => SavedObjectUnsanitizedDoc<StoredMapAttributes>;
    '7.12.0': (doc: SavedObjectUnsanitizedDoc<StoredMapAttributes>, context: SavedObjectMigrationContext) => SavedObjectUnsanitizedDoc<StoredMapAttributes>;
    '7.14.0': (doc: SavedObjectUnsanitizedDoc<StoredMapAttributes>, context: SavedObjectMigrationContext) => SavedObjectUnsanitizedDoc<StoredMapAttributes>;
    '8.0.0': (doc: SavedObjectUnsanitizedDoc<StoredMapAttributes>, context: SavedObjectMigrationContext) => SavedObjectUnsanitizedDoc<StoredMapAttributes>;
    '8.1.0': (doc: SavedObjectUnsanitizedDoc<StoredMapAttributes>, context: SavedObjectMigrationContext) => SavedObjectUnsanitizedDoc<StoredMapAttributes>;
    '8.4.0': (doc: SavedObjectUnsanitizedDoc<StoredMapAttributes>, context: SavedObjectMigrationContext) => SavedObjectUnsanitizedDoc<StoredMapAttributes>;
};
