[[cases]]
== Cases

preview::[]

Cases are used to open and track issues directly in the {kib}. All cases list
the original reporter and all the users who contribute to a case (_participants_).
You can also send cases to third party systems by configuring external connectors.

[discrete]
[[setup-cases]]
=== Configure access to cases

//See https://www.elastic.co/guide/en/observability/current/grant-cases-access.html and https://www.elastic.co/guide/en/security/master/case-permissions.html

To access cases in *{stack-manage-app}*, you must have the appropriate {kib}
privileges:

[options="header"]
|=== 

| Action | {kib} privileges
| Give full access to manage cases 
a|
* `All` for the *Cases* feature under *Management*.
* `All` for the *Actions and Connectors* feature under *Management*.

NOTE: Roles without `All` *Actions and Connectors* feature privileges cannot create, add, delete, or modify case connectors.

| Give view-only access for cases | `Read` for the *Cases* feature under *Management*.

| Revoke all access to cases | `None` for the *Cases* feature under *Management*.

|=== 

For more details, refer to <<kibana-privileges>>.

[discrete]
[[open-cases]]
=== Open a new case

Open a new case to keep track of issues and share their details with colleagues.

. Go to *Management > {stack-manage-app} > Cases*, then click *Create case*.

. Give the case a name, add any relevant tags and a description.
+
TIP: In the `Description` area, you can use
https://www.markdownguide.org/cheat-sheet[Markdown] syntax and insert a
timeline link (click the icon in the top right corner of the area).

. For *External incident management system*, select a connector. If you’ve
previously added one, that connector displays as the default selection.
Otherwise, the default setting is `No connector selected`.

. After you’ve completed all of the required fields, click *Create case*.
[discrete]

[discrete]
[[manage-cases]]
=== Manage cases

In *Management > {stack-manage-app} > Cases*, you can search cases and filter
them by tags, reporter.

NOTE: If you create cases in the {observability} or {security-app}, they are not
visible in *{stack-manage-app}*. Likewise, the cases you create in
*{stack-manage-app}* are not visible in the {observability} or {security-app}.

To view a case, click on its name. You can then:

* Add a new comment.
* Edit existing comments and the description.
* Add a connector (if you did not select one while creating the case).
* Send updates to external systems (if external connections are configured).
* Edit tags.
* Refresh the case to retrieve the latest updates.
* Change the status.
* Close or delete the case.
* Reopen a closed case.

//=== Configure external connectors

//=== Add a Lens visualization