[[managing-saved-objects]]
== Managing Saved Searches, Visualizations, and Dashboards

You can view, edit, delete, import, and export saved objects from *Management > Saved Objects*. 
A saved object can be a search, visualization, or dashboard.

[float]
[[managing-saved-objects-view]]
=== View an object

Viewing a saved object displays the selected item in its associated application,
*Discover*, *Visualize*, or *Dashboard*.

. In *Management > Saved Objects*, select the object type.
. Hover the pointer over the object you want to view and click the *View in app* icon.

[float]
[[managing-saved-objects-edit]]
=== Edit an object

Editing a saved object enables you to directly modify the object definition. You can change the object title, add
a description, and modify the JSON that defines the object properties.

. Select the object you want to edit.
. Make your changes to the object definition.
. Click *Save*.

If you attempt to access an object whose index has been deleted, you can:

* Recreate the index so you can continue using the object.
* Delete the object and recreate it using a different index.
* Change the index name referenced in the object's `kibanaSavedObjectMeta.searchSourceJSON` to point to an existing
index pattern. This is useful if the index you were working with was renamed.

WARNING: No validation is performed for object properties. Submitting invalid changes will render the object unusable.
In general, use the *Discover*, *Visualize*, or *Dashboard* apps to create new objects instead of directly
editing existing ones.

[float]
[[managing-saved-objects-delete]]
=== Delete an object

. Select the checkboxes of the objects to delete.
. Click *Delete*, and then confirm the deletion.

[float]
[[managing-saved-objects-export]]
=== Export and import objects

In some cases you might want to export and import a set of saved objects. For example:

* You might have multiple environments for development and production. The export 
and import commands allow you to move objects between different {kib} instances.

* You have a large number of objects to update and want to batch this process. 
You can export the objects to JSON, make the JSON modification, and re-import the objects.

[float]
==== Export objects

. Select the checkboxes of the objects to export, or select the *Title* checkbox 
for all objects of that type.
. Click *Export*.
. Alternately, click *Export Everything* to export all saved dashboards, searches, 
and visualizations.

WARNING: Exported dashboards do not include their associated index patterns. Re-create the index patterns manually before
importing saved dashboards to a {kib} instance running on another {es} cluster.

[float]
==== Import objects

. Click *Import*.
. Navigate to and select the JSON file that represents the objects to import.
. If any objects will overwrite objects already present in {kib}, confirm the overwrite.
