[[managing-licenses]]
== License Management

By default, new installations have a Basic license that never expires. 
For the full list of features available at the Free and Open Basic subscription level, 
refer to {subscriptions}.

To explore all of the available solutions and features, start a 30-day free trial.
You can activate a trial subscription once per major product version. 
If you need more than 30 days to complete your evaluation, 
request an extended trial at {extendtrial}.

To view the status of your license, start a trial, or install a new
license, open the main menu, then click *Stack Management > License Management*.

[discrete]
=== Required permissions

The `manage` cluster privilege is required to access *License Management*.

To add the privilege, open the main menu, then click *Stack Management > Roles*.

[discrete]
[[license-expiration]]
=== License expiration

Licenses are valid for a specific time period. 
30 days before the license expiration date, {es} starts logging expiration warnings.
If monitoring is enabled, expiration warnings are displayed prominently in {kib}.

If your license expires, your subscription level reverts to Basic and
you will no longer be able to use https://www.elastic.co/subscriptions[Platinum or Enterprise features].

[discrete]
[[update-license]]
=== Update your license

Licenses are provided as a _JSON_ file and have an effective date and an expiration date.  
You cannot install a new license before its effective date.
License updates take effect immediately and do not require restarting {es}.

You can update your license from *Stack Management > License Management* or through the
{ref}/update-license.html[update license API]. 
