[[setup-cases]]
== Configure access to cases

:frontmatter-description: Learn about the {kib} feature privileges required to access cases.
:frontmatter-tags-products: [kibana]
:frontmatter-tags-content-type: [how-to]
:frontmatter-tags-user-goals: [configure]

To access cases in *{stack-manage-app}*, you must have the appropriate {kib}
privileges:

[discrete]
=== Give full access to manage cases and settings

**{kib} privileges**

* `All` for the *Cases* feature under *Management*.
* `All` for the *{connectors-feature}* feature under *Management*.

[NOTE]
====
The *{connectors-feature}* feature privilege is required to create, add,
delete, and modify case connectors and to send updates to external systems.

By default, `All` for the *Cases* feature includes authority to delete cases
and comments, edit case settings, add case comments and attachments, and re-open cases unless you customize the sub-feature privileges.
====

[discrete]
=== Give assignee access to cases

**{kib} privileges**

* `All` for the *Cases* feature under *Management*.

[NOTE]
====
Before a user can be assigned to a case, they must log into {kib} at
least once, which creates a user profile.

This privilege is also required to add <<cases-action-type,case actions>> to rules.
====

[discrete]
=== Give view-only access to cases

**{kib} privileges**

* `Read` for the *Cases* feature under *Management*.

NOTE: You can customize sub-feature privileges for deleting cases and comments, editing case settings, adding case comments and attachments, and re-opening cases.

[discrete]
=== Revoke all access to cases

**{kib} privileges**

`None` for the *Cases* feature under *Management*.

[discrete]
=== More details

For more details, refer to <<kibana-privileges>>.

NOTE: If you are using an on-premises {kib} deployment and you want the email
notifications and the external incident management systems to contain
links back to {kib}, you must configure the
<<server-publicBaseUrl,`server.publicBaseUrl`>> setting.
