[[setup-cases]]
== Configure access to cases

:frontmatter-description: Learn about the {kib} feature privileges required to access cases. 
:frontmatter-tags-products: [kibana]
:frontmatter-tags-content-type: [how-to] 
:frontmatter-tags-user-goals: [configure]

To access cases in *{stack-manage-app}*, you must have the appropriate {kib}
privileges:

[options="header"]
|=== 

| Action | {kib} privileges
| Give full access to manage cases and settings
a|
* `All` for the *Cases* feature under *Management*.
* `All` for the *{connectors-feature}* feature under *Management*.

[NOTE]
====
The *{connectors-feature}* feature privilege is required to create, add,
delete, and modify case connectors and to send updates to external systems.

By default, `All` for the *Cases* feature includes authority to delete cases
and comments and edit case settings unless you customize the sub-feature privileges.
====

| Give assignee access to cases
a| `All` for the *Cases* feature under *Management*.

NOTE: Before a user can be assigned to a case, they must log into {kib} at
least once, which creates a user profile.

| Give view-only access to cases
a| `Read` for the *Cases* feature under *Management*.

NOTE: By default, `Read` for the *Cases* feature does not include authority to delete cases and comments or edit case settings. You can grant this authority by customizing the sub-feature privileges.

| Revoke all access to cases | `None` for the *Cases* feature under *Management*.

|=== 

For more details, refer to <<kibana-privileges>>.

NOTE: If you are using an on-premises {kib} deployment and you want the email
notifications and the external incident management systems to contain
links back to {kib}, you must configure the 
<<server-publicBaseUrl,`server.publicBaseUrl`>> setting.
