[[setup-cases]]
== Configure access to cases

preview::[]

To access cases in *{stack-manage-app}*, you must have the appropriate {kib}
privileges:

[options="header"]
|=== 

| Action | {kib} privileges
| Give full access to manage cases 
a|
* `All` for the *Cases* feature under *Management*.
* `All` for the *Actions and Connectors* feature under *Management*.

[NOTE]
====
The *Actions and Connectors* feature privilege is required to create, add,
delete, and modify case connectors and to send updates to external systems.

By default, `All` for the *Cases* feature includes authority to delete cases
and comments unless you customize the sub-feature privileges.
====

| Give assignee access to cases
a| `All` for the *Cases* feature under *Management*.

NOTE: Before a user can be assigned to a case, they must log into {kib} at
least once, which creates a user profile.

| Give view-only access for cases | `Read` for the *Cases* feature under *Management*.

| Give access to view and delete cases | `Read` for the *Cases* feature under
*Management* with the deletion sub-feature enabled.

| Revoke all access to cases | `None` for the *Cases* feature under *Management*.

|=== 

For more details, refer to <<kibana-privileges>>.
