/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/**
 * Compact catalog of all ES|QL commands and functions.
 * Used by the picker (request_documentation) step so it can select relevant names
 * without receiving the full syntax reference or examples.
 */
export const ESQL_COMMAND_CATALOG = `ES|QL command and function catalog. Pick only what is needed for the query.

SOURCE COMMANDS
FROM, ROW, SHOW, TS

PROCESSING COMMANDS
DISSECT, DROP, ENRICH, EVAL, GROK, KEEP, LIMIT, MV_EXPAND, RENAME, SORT, STATS, WHERE
[preview] CHANGE_POINT, COMPLETION, FORK, FUSE, RERANK, SAMPLE

GROUPING FUNCTIONS (use inside STATS)
BUCKET, TBUCKET, CATEGORIZE

AGGREGATION FUNCTIONS (use inside STATS)
AVG, COUNT, COUNT_DISTINCT, MAX, MIN, SUM, MEDIAN, MEDIAN_ABSOLUTE_DEVIATION, PERCENTILE,
STD_DEV, VARIANCE, WEIGHTED_AVG, ABSENT, PRESENT, SAMPLE, TOP, VALUES,
ST_CENTROID_AGG, ST_EXTENT_AGG

CONDITIONAL FUNCTIONS
CASE, COALESCE, GREATEST, LEAST, CLAMP, CLAMP_MIN, CLAMP_MAX

SEARCH FUNCTIONS
MATCH, MATCH_PHRASE, QSTR, KQL, DECAY, SCORE, TOP_SNIPPETS

DATE/TIME FUNCTIONS
DATE_DIFF, DATE_EXTRACT, DATE_FORMAT, DATE_PARSE, DATE_TRUNC, DAY_NAME, MONTH_NAME, NOW, TRANGE

STRING FUNCTIONS
BIT_LENGTH, BYTE_LENGTH, CHUNK, CONCAT, CONTAINS, ENDS_WITH, FROM_BASE64, HASH,
LEFT, LENGTH, LOCATE, LTRIM, MD5, REPEAT, REPLACE, REVERSE, RIGHT, RTRIM, SHA1, SHA256,
SPACE, SPLIT, STARTS_WITH, SUBSTRING, TO_BASE64, TO_LOWER, TO_UPPER, TRIM,
URL_DECODE, URL_ENCODE, URL_ENCODE_COMPONENT

IP FUNCTIONS
CIDR_MATCH, IP_PREFIX

TYPE CONVERSION FUNCTIONS
TO_BOOLEAN, TO_CARTESIANPOINT, TO_CARTESIANSHAPE, TO_DATEPERIOD, TO_DATETIME, TO_DATE_NANOS,
TO_DEGREES, TO_DENSE_VECTOR, TO_DOUBLE, TO_GEOHASH, TO_GEOHEX, TO_GEOPOINT, TO_GEOSHAPE,
TO_GEOTILE, TO_INTEGER, TO_IP, TO_LONG, TO_RADIANS, TO_STRING, TO_TIMEDURATION,
TO_UNSIGNED_LONG, TO_VERSION, TO_AGGREGATE_METRIC_DOUBLE

MATHEMATICAL FUNCTIONS
ABS, ACOS, ASIN, ATAN, ATAN2, CBRT, CEIL, COS, COSH, E, EXP, FLOOR, HYPOT,
LOG, LOG10, PI, POW, ROUND, SIGNUM, SIN, SINH, SQRT, TAN, TANH, TAU

MULTI-VALUE FUNCTIONS
MV_APPEND, MV_AVG, MV_CONCAT, MV_COUNT, MV_DEDUPE, MV_FIRST, MV_LAST, MV_MAX,
MV_MEDIAN, MV_MEDIAN_ABSOLUTE_DEVIATION, MV_MIN, MV_PERCENTILE, MV_SLIDE,
MV_SORT, MV_SUM, MV_ZIP

SPATIAL FUNCTIONS
ST_CONTAINS, ST_DISJOINT, ST_DISTANCE, ST_ENVELOPE, ST_INTERSECTS, ST_WITHIN,
ST_X, ST_Y, ST_XMAX, ST_XMIN, ST_YMAX, ST_YMIN`;