[[rpm]]
=== RPMでのKibanaのインストール 
KibanaのRPMは、<<install-rpm,弊社のWebサイトからダウンロード>>するか、または<<rpm-repo,RPM RPMリポジトリ>>からダウンロードできます。これを使って、OpenSuSE、SLES、Centos、Red Hat、Oracle EnterpriseなどRPMベースのシステムにKibanaをインストールできます。

NOTE: RPMインストールは、SLES 11やCentOS 5など、古いバージョンのPRMでのデストリビューションではサポートされません。代わりに、<<targz>>を参照してください。

Kibanaの最新の安定バージョンは、link:/downloads/kibana[Kibanaのダウンロード]ページにあります。その他のバージョンは、link:/downloads/past-releases[過去のリリースページ]にあります。

[[rpm-key]]
==== Elastic PGPキーのインポート

include::key.asciidoc[]

[source,sh]
-------------------------
rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch
-------------------------

[[rpm-repo]]
==== RPTリポジトリからのインストール

ifeval::["{release-state}"=="unreleased"]

バージョン{version}のKibanaはまだリリースされていません。

endif::[]

ifeval::["{release-state}"!="unreleased"]

RedHatベースのデストリビューションの場合は`/etc/yum.repos.d/`ディレクトリ、OpenSuSEベースのデストリビューションの場合は`/etc/zypp/repos.d/`ディレクトリに、以下を含む`kibana.repo`というファイルを作成します。

ifeval::["{release-state}"=="released"]

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
[kibana-{major-version}]
name=Kibana repository for {major-version} packages
baseurl=https://artifacts.elastic.co/packages/{major-version}/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
enabled=1
autorefresh=1
type=rpm-md
--------------------------------------------------

endif::[]

ifeval::["{release-state}"=="prerelease"]

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
[kibana-{major-version}]
name=Kibana repository for {major-version} packages
baseurl=https://artifacts.elastic.co/packages/{major-version}-prerelease/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
enabled=1
autorefresh=1
type=rpm-md
--------------------------------------------------

endif::[]

リポジトリが使用できるようになります。次のいずれかのコマンドを使用してKibanaをインストールできるようになりました。

[source,sh]
--------------------------------------------------
sudo yum install kibana <1>
sudo dnf install kibana <2>
sudo zypper install kibana <3>
--------------------------------------------------
<1> CentOSと古いRed Hatベースのデストリビューションでは`yum`を使用します。
<2> Fedoraとその他の新しいRed Hatデストリビューションでは`dnf`を使用します。
<3> OpenSUSEベースのデストリビューションでは`zypper`を使用します。

endif::[]

[[install-rpm]]
==== 手動によるRPMのダウンロードとインストール

ifeval::["{release-state}"=="unreleased"]

バージョン{version}のKibanaはまだリリースされていません。

endif::[]

ifeval::["{release-state}"!="unreleased"]

Kibana v{version}のRPMは、次のようにWebサイトからダウンロードしてインストールします。

*64ビット:*
["source","sh",subs="attributes"]
--------------------------------------------
wget https://artifacts.elastic.co/downloads/kibana/kibana-{version}-x86_64.rpm
sha1sum kibana-{version}-x86_64.rpm <1>
sudo rpm --install kibana-{version}-x86_64.rpm
--------------------------------------------
<1> `sha1sum`または`shasum`により生成されたSHAを https://artifacts.elastic.co/downloads/kibana/kibana-{version}-x86_64.rpm.sha1[published SHA]と比較します。

*32ビット:*
["source","sh",subs="attributes"]
--------------------------------------------
wget https://artifacts.elastic.co/downloads/kibana/kibana-{version}-i686.rpm
sha1sum kibana-{version}-i686.rpm <1>
sudo rpm --install kibana-{version}-i686.rpm
--------------------------------------------
<1> `sha1sum`または`shasum`により生成されたSHAを https://artifacts.elastic.co/downloads/kibana/kibana-{version}-i686.rpm.sha1[published SHA]と比較します。

endif::[]

include::init-systemd.asciidoc[]

[[rpm-running-init]]
==== SysV `init`でのKibanaの実行

`chkconfig`コマンドを使用して、システムの起動時に自動的に起動するようにKibanaを設定します。

[source,sh]
--------------------------------------------------
sudo chkconfig --add kibana
--------------------------------------------------

`service`を使用して、Kibanaを起動したり停止したりできます。

[source,sh]
--------------------------------------------
sudo -i service kibana start
sudo -i service kibana stop
--------------------------------------------

何らかの理由によりKibanaの起動に失敗した場合、失敗の理由がSTDOUTに出力されます。ログファイルは`/var/log/kibana/`にあります。


[[rpm-running-systemd]]
include::systemd.asciidoc[]

[[rpm-configuring]]
==== 設定ファイルによるKibanaの設定

Kibanaは、デフォルトで`/etc/kibana/kibana.yml`ファイルから設定を読み込みます。この設定ファイルの形式については、{kibana-ref}/settings.html[設定]で説明しています。

[[rpm-layout]]
==== RPMのディレクトリ構成

RPMは、RPMベースシステムの適切な場所に設定ファイル、ログ、およびデータディレクトリを配置します。


[cols="<h,<,<m,<m",options="header",]
|=======================================================================
| タイプ | 説明 | デフォルトの場所 | 設定
| home
  | Kibanaのホームディレクトリまたは`$KIBANA_HOME`
  | /usr/share/kibana
 d|

| bin
  | Kibanaサーバーを起動するための`kibana`およびプラグインをインストールするための`kibana-plugin`を含むバイナリスクリプト
    
  | /usr/share/kibana/bin
 d|

| config
  | `kibana.yml`を含む設定ファイル
  | /etc/kibana
 d|

| data
  | Kibanaとそのプラグインによりディスクに書き込まれるデータファイルの場所
  | /var/lib/kibana
 d|

| optimize
  | トランスパイルされたソースコード。ある管理操作（プラグインのインストールなど）を行うと、その操作時にソースコードがトランスパイルされます。
    
  | /usr/share/kibana/optimize
 d|

| plugins
  | プラグインファイルの場所。各プラグインは、サブディレクトリに格納されます。
  | /usr/share/kibana/plugins
 d|

|=======================================================================
