[[targz]]
=== `.tar.gz`でのKibanaのインストール

LinuxとDarwin用のKibanaは`.tar.gz`パッケージとして提供されます。Kibanaを試用する際は、これらのパッケージが最も使いやすい形式です。

Kibanaの最新の安定バージョンは、link:/downloads/kibana[Kibanaのダウンロード]ページにあります。
その他のバージョンは、link:/downloads/past-releases[過去のリリースページ]にあります。


[[install-linux64]]
==== Linux 64ビットパッケージのダウンロードとインストール

ifeval::["{release-state}"=="unreleased"]

バージョン{version}のKibanaはまだリリースされていません。

endif::[]

ifeval::["{release-state}"!="unreleased"]

Kibana v{version}の64ビットのLinuxアーカイブは、次のようにダウンロードしてインストールします。

["source","sh",subs="attributes"]
--------------------------------------------
wget https://artifacts.elastic.co/downloads/kibana/kibana-{version}-linux-x86_64.tar.gz
sha1sum kibana-{version}-linux-x86_64.tar.gz <1>
tar -xzf kibana-{version}-linux-x86_64.tar.gz
cd kibana/ <2>
--------------------------------------------
<1> `sha1sum`または`shasum`により生成されたSHAを https://artifacts.elastic.co/downloads/kibana/kibana-{version}-linux-x86_64.tar.gz.sha1[published SHA]と比較します。
<2> このディレクトリは、`$KIBANA_HOME`です。

endif::[]


[[install-linux32]]
==== Linux 32ビットパッケージのダウンロードとインストール

ifeval::["{release-state}"=="unreleased"]

バージョン{version}のKibanaはまだリリースされていません。

endif::[]

ifeval::["{release-state}"!="unreleased"]

Kibana v{version}の32ビットのLinuxアーカイブは、次のようにダウンロードしてインストールします。

["source","sh",subs="attributes"]
--------------------------------------------
wget https://artifacts.elastic.co/downloads/kibana/kibana-{version}-linux-x86.tar.gz
sha1sum kibana-{version}-linux-x86.tar.gz <1>
tar -xzf kibana-{version}-linux-x86.tar.gz
cd kibana/ <2>
--------------------------------------------
<1> `sha1sum`または`shasum`により生成されたSHAを https://artifacts.elastic.co/downloads/kibana/kibana-{version}-linux-x86.tar.gz.sha1[published SHA]と比較します。
<2> このディレクトリは、`$KIBANA_HOME`です。

endif::[]


[[install-darwin64]]
==== Darwinパッケージのダウンロードとインストール

ifeval::["{release-state}"=="unreleased"]

バージョン{version}のKibanaはまだリリースされていません。

endif::[]

ifeval::["{release-state}"!="unreleased"]

Kibana v{version}のDarwinアーカイブは、次のようにダウンロードしてインストールします。

["source","sh",subs="attributes"]
--------------------------------------------
wget https://artifacts.elastic.co/downloads/kibana/kibana-{version}-darwin-x86_64.tar.gz
shasum kibana-{version}-darwin-x86_64.tar.gz <1>
tar -xzf kibana-{version}-darwin-x86_64.tar.gz
cd kibana/ <2>
--------------------------------------------
<1> `sha1sum`または`shasum`により生成されたSHAを https://artifacts.elastic.co/downloads/kibana/kibana-{version}-darwin-x86_64.tar.gz.sha1[published SHA]と比較します。
<2> このディレクトリは、`$KIBANA_HOME`です。

endif::[]


[[targz-running]]
==== コマンドラインからのKibanaの実行

Kibanaは、次のようにコマンドラインから起動できます。

[source,sh]
--------------------------------------------
./bin/kibana
--------------------------------------------

デフォルトでKibanaは、フォアグラウンドで実行し、そのログを標準出力（`stdout`）に出力します。`Ctrl-C`を押すと停止できます。


[[targz-configuring]]
==== 設定ファイルによるKibanaの設定

Kibanaは、デフォルトで`$KIBANA_HOME/config/kibana.yml`ファイルから設定を読み込みます。この設定ファイルの形式については、{kibana-ref}/settings.html[設定]で説明しています。


[[targz-layout]]
==== `.tar.gz`アーカイブのディレクトリ構成

`.tar.gz`パッケージは完全に自己解凍型です。デフォルトで、ファイルとディレクトリはすべて`$KIBANA_HOME`内に格納されます。このディレクトリは、アーカイブの解凍時に作成されます。

ディレクトリを作成することなくKibanaの使用を開始でき、$KIBANA_HOME`ディレクトリを削除するのと同じくらい簡単にKibanaをアンインストールできるため、非常に便利です。ただし、後で重要なデータを削除しないように、configディレクトリとdataディレクトリのデフォルトの場所を変更することをお勧めします。


[cols="<h,<,<m,<m",options="header",]
|=======================================================================
| タイプ | 説明 | デフォルトの場所 | 設定
| home
  | Kibanaのホームディレクトリまたは`$KIBANA_HOME`
 d| アーカイブの解凍により作成されるディレクトリ
 d|

| bin
  | Kibanaサーバーを起動するための`kibana`およびプラグインをインストールするための`kibana-plugin`を含むバイナリスクリプト
    
  | $KIBANA_HOME\bin
 d|

| config
  | `kibana.yml`を含む設定ファイル
  | $KIBANA_HOME\config
 d|

| data
  | Kibanaとそのプラグインによりディスクに書き込まれるデータファイルの場所
  | $KIBANA_HOME\data
 d|

| optimize
  | トランスパイルされたソースコード。ある管理操作（プラグインのインストールなど）を行うと、その操作時にソースコードがトランスパイルされます。
    
  | $KIBANA_HOME\optimize
 d|

| plugins
  | プラグインファイルの場所。各プラグインは、サブディレクトリに格納されます。
  | $KIBANA_HOME\plugins
 d|

|=======================================================================
