/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

import { http, HttpResponse } from 'msw';

export const defaultDataViewFindHandler = http.get(
  'http://localhost/internal/data_views/fields',
  ({ request }) => {
    const url = new URL(request.url);

    // Read the "id" URL query parameter using the "URLSearchParams" API.
    // Given "/product?id=1", "productId" will equal "1".
    const pattern = url.searchParams.get('pattern');

    console.log('MSW pattern', pattern);

    if (pattern === 'logs-cloud_security_posture.findings_latest-*') {
      return HttpResponse.json({
        fields: [
          {
            name: '@timestamp',
            type: 'date',
            esTypes: ['date'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: '_id',
            type: 'string',
            esTypes: ['_id'],
            searchable: true,
            aggregatable: false,
            readFromDocValues: false,
            metadata_field: true,
          },
          {
            name: '_index',
            type: 'string',
            esTypes: ['_index'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: false,
            metadata_field: true,
          },
          {
            name: '_score',
            type: 'number',
            searchable: false,
            aggregatable: false,
            readFromDocValues: false,
            metadata_field: true,
          },
          {
            name: '_source',
            type: '_source',
            esTypes: ['_source'],
            searchable: false,
            aggregatable: false,
            readFromDocValues: false,
            metadata_field: true,
          },
          {
            name: 'agent.ephemeral_id',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'agent.id',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'agent.name',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'agent.type',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'agent.version',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloud.Organization.id',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloud.Organization.name',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloud.account.id',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloud.account.name',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloud.provider',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloud.region',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloud_security_posture.package_policy.id',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloud_security_posture.package_policy.revision',
            type: 'number',
            esTypes: ['short'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloudbeat.commit_sha',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloudbeat.kubernetes.version',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloudbeat.policy.version',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloudbeat.version',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cluster_id',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'data_stream.dataset',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'data_stream.namespace',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'data_stream.type',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'ecs.version',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'event.agent_id_status',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'event.category',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'event.created',
            type: 'date',
            esTypes: ['date'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'event.id',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'event.ingested',
            type: 'date',
            esTypes: ['date'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'event.kind',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'event.outcome',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'event.sequence',
            type: 'number',
            esTypes: ['long'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'event.type',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'file.accessed',
            type: 'date',
            esTypes: ['date'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'file.ctime',
            type: 'date',
            esTypes: ['date'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'file.directory',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'file.extension',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'file.gid',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'file.group',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'file.inode',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'file.mode',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'file.mtime',
            type: 'date',
            esTypes: ['date'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'file.name',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'file.owner',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'file.path',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'file.path.text',
            type: 'string',
            esTypes: ['text'],
            searchable: true,
            aggregatable: false,
            readFromDocValues: false,
            metadata_field: false,
            subType: {
              multi: {
                parent: 'file.path',
              },
            },
          },
          {
            name: 'file.size',
            type: 'number',
            esTypes: ['long'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'file.type',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'file.uid',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'host.architecture',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'host.hostname',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'host.ip',
            type: 'ip',
            esTypes: ['ip'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'host.mac',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'host.name',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'host.os.family',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'host.os.full',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'host.os.full.text',
            type: 'string',
            esTypes: ['text'],
            searchable: true,
            aggregatable: false,
            readFromDocValues: false,
            metadata_field: false,
            subType: {
              multi: {
                parent: 'host.os.full',
              },
            },
          },
          {
            name: 'host.os.kernel',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'host.os.name',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'host.os.name.text',
            type: 'string',
            esTypes: ['text'],
            searchable: true,
            aggregatable: false,
            readFromDocValues: false,
            metadata_field: false,
            subType: {
              multi: {
                parent: 'host.os.name',
              },
            },
          },
          {
            name: 'host.os.platform',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'host.os.type',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'host.os.version',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'message',
            type: 'string',
            esTypes: ['text'],
            searchable: true,
            aggregatable: false,
            readFromDocValues: false,
            metadata_field: false,
          },
          {
            name: 'orchestrator.cluster.id',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'orchestrator.cluster.name',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'orchestrator.cluster.version',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'orchestrator.resource.id',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'orchestrator.resource.name',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'orchestrator.resource.type',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'orchestrator.type',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'process.args',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'process.args_count',
            type: 'number',
            esTypes: ['long'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'process.command_line',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'process.command_line.text',
            type: 'string',
            esTypes: ['text'],
            searchable: true,
            aggregatable: false,
            readFromDocValues: false,
            metadata_field: false,
            subType: {
              multi: {
                parent: 'process.command_line',
              },
            },
          },
          {
            name: 'process.name',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'process.name.text',
            type: 'string',
            esTypes: ['text'],
            searchable: true,
            aggregatable: false,
            readFromDocValues: false,
            metadata_field: false,
            subType: {
              multi: {
                parent: 'process.name',
              },
            },
          },
          {
            name: 'process.parent.pid',
            type: 'number',
            esTypes: ['long'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'process.parent.start',
            type: 'date',
            esTypes: ['date'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'process.pgid',
            type: 'number',
            esTypes: ['long'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'process.pid',
            type: 'number',
            esTypes: ['long'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'process.start',
            type: 'date',
            esTypes: ['date'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'process.title',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'process.title.text',
            type: 'string',
            esTypes: ['text'],
            searchable: true,
            aggregatable: false,
            readFromDocValues: false,
            metadata_field: false,
            subType: {
              multi: {
                parent: 'process.title',
              },
            },
          },
          {
            name: 'process.uptime',
            type: 'number',
            esTypes: ['long'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'resource.id',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'resource.name',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'resource.sub_type',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'resource.type',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'result.evaluation',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'rule.benchmark.id',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'rule.benchmark.name',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'rule.benchmark.posture_type',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'rule.benchmark.rule_number',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'rule.benchmark.version',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'rule.description',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'rule.id',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'rule.name',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'rule.section',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'rule.tags',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'rule.version',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
        ],
        indices: ['logs-cloud_security_posture.findings_latest-default'],
      });
    }

    if (pattern === 'logs-cloud_security_posture.vulnerabilities_latest*') {
      return HttpResponse.json({
        fields: [
          {
            name: '@timestamp',
            type: 'date',
            esTypes: ['date'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: '_id',
            type: 'string',
            esTypes: ['_id'],
            searchable: true,
            aggregatable: false,
            readFromDocValues: false,
            metadata_field: true,
          },
          {
            name: '_index',
            type: 'string',
            esTypes: ['_index'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: false,
            metadata_field: true,
          },
          {
            name: '_score',
            type: 'number',
            searchable: false,
            aggregatable: false,
            readFromDocValues: false,
            metadata_field: true,
          },
          {
            name: '_source',
            type: '_source',
            esTypes: ['_source'],
            searchable: false,
            aggregatable: false,
            readFromDocValues: false,
            metadata_field: true,
          },
          {
            name: 'agent.ephemeral_id',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'agent.id',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'agent.name',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'agent.type',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'agent.version',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloud.Tags',
            type: 'unknown',
            esTypes: ['flattened'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloud.account.id',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloud.account.name',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloud.availability_zone',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloud.instance.id',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloud.instance.name',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloud.machine.Authentication.key',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloud.machine.Image',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloud.machine.Launch_time',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloud.machine.type',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloud.provider',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloud.region',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloud.service.name',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloud_security_posture.package_policy.id',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloud_security_posture.package_policy.revision',
            type: 'number',
            esTypes: ['short'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloudbeat.commit_sha',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloudbeat.commit_time',
            type: 'date',
            esTypes: ['date'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloudbeat.policy.version',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'cloudbeat.version',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'data_stream.dataset',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'data_stream.namespace',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'data_stream.type',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'ecs.version',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'event.agent_id_status',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'event.category',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'event.created',
            type: 'date',
            esTypes: ['date'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'event.id',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'event.ingested',
            type: 'date',
            esTypes: ['date'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'event.kind',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'event.outcome',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'event.sequence',
            type: 'number',
            esTypes: ['long'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'event.type',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'host.architecture',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'host.hostname',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'host.ip',
            type: 'ip',
            esTypes: ['ip'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'host.mac',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'host.name',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'host.os.family',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'host.os.full',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'host.os.full.text',
            type: 'string',
            esTypes: ['text'],
            searchable: true,
            aggregatable: false,
            readFromDocValues: false,
            metadata_field: false,
            subType: {
              multi: {
                parent: 'host.os.full',
              },
            },
          },
          {
            name: 'host.os.kernel',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'host.os.name',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'host.os.name.text',
            type: 'string',
            esTypes: ['text'],
            searchable: true,
            aggregatable: false,
            readFromDocValues: false,
            metadata_field: false,
            subType: {
              multi: {
                parent: 'host.os.name',
              },
            },
          },
          {
            name: 'host.os.platform',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'host.os.type',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'host.os.version',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'message',
            type: 'string',
            esTypes: ['text'],
            searchable: true,
            aggregatable: false,
            readFromDocValues: false,
            metadata_field: false,
          },
          {
            name: 'network.Mac_addresses',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'network.Private_ip',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'network.Public_ip',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'package.fixed_version',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'package.name',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'package.path',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'package.type',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'package.version',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'resource.id',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'resource.name',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'vulnerability.category',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'vulnerability.class',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'vulnerability.classification',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'vulnerability.cwe',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'vulnerability.data_source.ID',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'vulnerability.data_source.Name',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'vulnerability.data_source.URL',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'vulnerability.description',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'vulnerability.description.text',
            type: 'string',
            esTypes: ['text'],
            searchable: true,
            aggregatable: false,
            readFromDocValues: false,
            metadata_field: false,
            subType: {
              multi: {
                parent: 'vulnerability.description',
              },
            },
          },
          {
            name: 'vulnerability.enumeration',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'vulnerability.id',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'vulnerability.package.fixed_version',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'vulnerability.package.name',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'vulnerability.package.version',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'vulnerability.published_date',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'vulnerability.reference',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'vulnerability.report_id',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'vulnerability.scanner.vendor',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'vulnerability.scanner.version',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'vulnerability.score.base',
            type: 'number',
            esTypes: ['float'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'vulnerability.score.version',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'vulnerability.severity',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
          {
            name: 'vulnerability.title',
            type: 'string',
            esTypes: ['keyword'],
            searchable: true,
            aggregatable: true,
            readFromDocValues: true,
            metadata_field: false,
          },
        ],
        indices: ['logs-cloud_security_posture.vulnerabilities_latest-default'],
      });
    }

    return HttpResponse.json({
      fields: [],
      indices: [],
    });
  }
);
