/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

import { ALERTZERO_ACTION_CREATE_RULE_WORKFLOW_ID } from './actions/action_create_detection_rule';
import { ALERTZERO_ACTION_EDIT_RULE_WORKFLOW_ID } from './actions/action_edit_detection_rule';
import { ALERTZERO_WORKER_DARK_CONTINUOUS_THREAT_HUNT_WORKFLOW_ID } from './dark_continuous_threat_hunt';
import { ALERTZERO_WORKER_DETECTION_RULE_CREATION_WORKFLOW_ID } from './detection_rule_creation';
import { ALERTZERO_WORKER_DETECTION_RULE_TUNING_WORKFLOW_ID } from './detection_rule_tuning';
import { ALERTZERO_WORKER_FLOOR_ALERT_TRIAGE_WORKFLOW_ID } from './floor_alert_triage';
import { ALERTZERO_WORKER_FLOOR_ATTACK_DISCOVERY_WORKFLOW_ID } from './floor_attack_discovery';
import {
  ALERTZERO_DETECTION_COVERAGE_WORKFLOW_ID,
  ALERTZERO_RULE_CREATION_WORKFLOW_ID,
  ALERTZERO_RULE_PREVIEW_WORKFLOW_ID,
  ALERTZERO_RULE_TUNING_REVIEW_WORKFLOW_ID,
  ALERTZERO_RULE_TUNING_WORKER_WORKFLOW_ID,
} from './rule_workflows';

export {
  ALERTZERO_DETECTION_COVERAGE_WORKFLOW,
  ALERTZERO_DETECTION_COVERAGE_WORKFLOW_ID,
  ALERTZERO_RULE_CREATION_WORKFLOW,
  ALERTZERO_RULE_CREATION_WORKFLOW_ID,
  ALERTZERO_RULE_PREVIEW_WORKFLOW,
  ALERTZERO_RULE_PREVIEW_WORKFLOW_ID,
  ALERTZERO_RULE_TUNING_REVIEW_WORKFLOW,
  ALERTZERO_RULE_TUNING_REVIEW_WORKFLOW_ID,
  ALERTZERO_RULE_TUNING_WORKER_WORKFLOW,
  ALERTZERO_RULE_TUNING_WORKER_WORKFLOW_ID,
} from './rule_workflows';
export {
  ALERTZERO_ACTION_CREATE_RULE_WORKFLOW,
  ALERTZERO_ACTION_CREATE_RULE_WORKFLOW_ID,
} from './actions/action_create_detection_rule';
export {
  ALERTZERO_ACTION_EDIT_RULE_WORKFLOW,
  ALERTZERO_ACTION_EDIT_RULE_WORKFLOW_ID,
} from './actions/action_edit_detection_rule';
export {
  ALERTZERO_WORKER_DARK_CONTINUOUS_THREAT_HUNT_WORKFLOW,
  ALERTZERO_WORKER_DARK_CONTINUOUS_THREAT_HUNT_WORKFLOW_ID,
} from './dark_continuous_threat_hunt';
export {
  ALERTZERO_WORKER_DETECTION_RULE_CREATION_WORKFLOW,
  ALERTZERO_WORKER_DETECTION_RULE_CREATION_WORKFLOW_ID,
} from './detection_rule_creation';
export {
  ALERTZERO_WORKER_DETECTION_RULE_TUNING_WORKFLOW,
  ALERTZERO_WORKER_DETECTION_RULE_TUNING_WORKFLOW_ID,
} from './detection_rule_tuning';
export {
  ALERTZERO_WORKER_FLOOR_ALERT_TRIAGE_WORKFLOW,
  ALERTZERO_WORKER_FLOOR_ALERT_TRIAGE_WORKFLOW_ID,
} from './floor_alert_triage';
export {
  ALERTZERO_WORKER_FLOOR_ATTACK_DISCOVERY_WORKFLOW,
  ALERTZERO_WORKER_FLOOR_ATTACK_DISCOVERY_WORKFLOW_ID,
} from './floor_attack_discovery';

export const ALERTZERO_MANAGED_WORKER_WORKFLOW_IDS = [
  ALERTZERO_WORKER_FLOOR_ALERT_TRIAGE_WORKFLOW_ID,
  ALERTZERO_WORKER_FLOOR_ATTACK_DISCOVERY_WORKFLOW_ID,
  ALERTZERO_WORKER_DARK_CONTINUOUS_THREAT_HUNT_WORKFLOW_ID,
  ALERTZERO_WORKER_DETECTION_RULE_TUNING_WORKFLOW_ID,
  ALERTZERO_WORKER_DETECTION_RULE_CREATION_WORKFLOW_ID,
] as const;

export const ALERTZERO_RULE_WORKFLOW_IDS = [
  ALERTZERO_RULE_PREVIEW_WORKFLOW_ID,
  ALERTZERO_RULE_TUNING_REVIEW_WORKFLOW_ID,
  ALERTZERO_RULE_CREATION_WORKFLOW_ID,
  ALERTZERO_DETECTION_COVERAGE_WORKFLOW_ID,
  ALERTZERO_RULE_TUNING_WORKER_WORKFLOW_ID,
] as const;

/**
 * Action workflows AlertZero may propose. Discovery is normally by the generic
 * `action` tag; this list is the install set and the fallback.
 */
export const ALERTZERO_ACTION_WORKFLOW_IDS = [
  ALERTZERO_ACTION_CREATE_RULE_WORKFLOW_ID,
  ALERTZERO_ACTION_EDIT_RULE_WORKFLOW_ID,
] as const;
