/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

import { reportingSchema } from './schema';

const flatten = (source: any, path: string[] = []): Record<string, string> => {
  if (!(source instanceof Object)) {
    return {
      [path.join('.')]: source,
    };
  }
  return Object.keys(source).reduce((result, key) => {
    const flattened = flatten(source[key], [...path, key]);
    return {
      ...result,
      ...flattened,
    };
  }, {});
};

describe('Reporting telemetry schema', () => {
  test('fields', () => {
    expect(flatten(reportingSchema, ['stack_stats', 'kibana', 'plugins', 'reporting']))
      .toMatchInlineSnapshot(`
      Object {
        "stack_stats.kibana.plugins.reporting.PNG.app.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.PNG.app.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.PNG.app.search.type": "long",
        "stack_stats.kibana.plugins.reporting.PNG.app.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.PNG.available.type": "boolean",
        "stack_stats.kibana.plugins.reporting.PNG.deprecated.type": "long",
        "stack_stats.kibana.plugins.reporting.PNG.layout.canvas.type": "long",
        "stack_stats.kibana.plugins.reporting.PNG.layout.preserve_layout.type": "long",
        "stack_stats.kibana.plugins.reporting.PNG.layout.print.type": "long",
        "stack_stats.kibana.plugins.reporting.PNG.sizes.1.0.type": "long",
        "stack_stats.kibana.plugins.reporting.PNG.sizes.25.0.type": "long",
        "stack_stats.kibana.plugins.reporting.PNG.sizes.5.0.type": "long",
        "stack_stats.kibana.plugins.reporting.PNG.sizes.50.0.type": "long",
        "stack_stats.kibana.plugins.reporting.PNG.sizes.75.0.type": "long",
        "stack_stats.kibana.plugins.reporting.PNG.sizes.95.0.type": "long",
        "stack_stats.kibana.plugins.reporting.PNG.sizes.99.0.type": "long",
        "stack_stats.kibana.plugins.reporting.PNG.total.type": "long",
        "stack_stats.kibana.plugins.reporting.PNGV2.app.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.PNGV2.app.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.PNGV2.app.search.type": "long",
        "stack_stats.kibana.plugins.reporting.PNGV2.app.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.PNGV2.available.type": "boolean",
        "stack_stats.kibana.plugins.reporting.PNGV2.deprecated.type": "long",
        "stack_stats.kibana.plugins.reporting.PNGV2.layout.canvas.type": "long",
        "stack_stats.kibana.plugins.reporting.PNGV2.layout.preserve_layout.type": "long",
        "stack_stats.kibana.plugins.reporting.PNGV2.layout.print.type": "long",
        "stack_stats.kibana.plugins.reporting.PNGV2.sizes.1.0.type": "long",
        "stack_stats.kibana.plugins.reporting.PNGV2.sizes.25.0.type": "long",
        "stack_stats.kibana.plugins.reporting.PNGV2.sizes.5.0.type": "long",
        "stack_stats.kibana.plugins.reporting.PNGV2.sizes.50.0.type": "long",
        "stack_stats.kibana.plugins.reporting.PNGV2.sizes.75.0.type": "long",
        "stack_stats.kibana.plugins.reporting.PNGV2.sizes.95.0.type": "long",
        "stack_stats.kibana.plugins.reporting.PNGV2.sizes.99.0.type": "long",
        "stack_stats.kibana.plugins.reporting.PNGV2.total.type": "long",
        "stack_stats.kibana.plugins.reporting._all.type": "long",
        "stack_stats.kibana.plugins.reporting.available.type": "boolean",
        "stack_stats.kibana.plugins.reporting.browser_type.type": "keyword",
        "stack_stats.kibana.plugins.reporting.csv.app.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.csv.app.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.csv.app.search.type": "long",
        "stack_stats.kibana.plugins.reporting.csv.app.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.csv.available.type": "boolean",
        "stack_stats.kibana.plugins.reporting.csv.deprecated.type": "long",
        "stack_stats.kibana.plugins.reporting.csv.layout.canvas.type": "long",
        "stack_stats.kibana.plugins.reporting.csv.layout.preserve_layout.type": "long",
        "stack_stats.kibana.plugins.reporting.csv.layout.print.type": "long",
        "stack_stats.kibana.plugins.reporting.csv.sizes.1.0.type": "long",
        "stack_stats.kibana.plugins.reporting.csv.sizes.25.0.type": "long",
        "stack_stats.kibana.plugins.reporting.csv.sizes.5.0.type": "long",
        "stack_stats.kibana.plugins.reporting.csv.sizes.50.0.type": "long",
        "stack_stats.kibana.plugins.reporting.csv.sizes.75.0.type": "long",
        "stack_stats.kibana.plugins.reporting.csv.sizes.95.0.type": "long",
        "stack_stats.kibana.plugins.reporting.csv.sizes.99.0.type": "long",
        "stack_stats.kibana.plugins.reporting.csv.total.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource.app.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource.app.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource.app.search.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource.app.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource.available.type": "boolean",
        "stack_stats.kibana.plugins.reporting.csv_searchsource.deprecated.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource.layout.canvas.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource.layout.preserve_layout.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource.layout.print.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource.sizes.1.0.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource.sizes.25.0.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource.sizes.5.0.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource.sizes.50.0.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource.sizes.75.0.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource.sizes.95.0.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource.sizes.99.0.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource.total.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource_immediate.app.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource_immediate.app.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource_immediate.app.search.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource_immediate.app.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource_immediate.available.type": "boolean",
        "stack_stats.kibana.plugins.reporting.csv_searchsource_immediate.deprecated.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource_immediate.layout.canvas.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource_immediate.layout.preserve_layout.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource_immediate.layout.print.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource_immediate.sizes.1.0.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource_immediate.sizes.25.0.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource_immediate.sizes.5.0.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource_immediate.sizes.50.0.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource_immediate.sizes.75.0.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource_immediate.sizes.95.0.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource_immediate.sizes.99.0.type": "long",
        "stack_stats.kibana.plugins.reporting.csv_searchsource_immediate.total.type": "long",
        "stack_stats.kibana.plugins.reporting.enabled.type": "boolean",
        "stack_stats.kibana.plugins.reporting.last7Days.PNG.app.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNG.app.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNG.app.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNG.app.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNG.available.type": "boolean",
        "stack_stats.kibana.plugins.reporting.last7Days.PNG.deprecated.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNG.layout.canvas.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNG.layout.preserve_layout.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNG.layout.print.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNG.sizes.1.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNG.sizes.25.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNG.sizes.5.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNG.sizes.50.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNG.sizes.75.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNG.sizes.95.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNG.sizes.99.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNG.total.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNGV2.app.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNGV2.app.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNGV2.app.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNGV2.app.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNGV2.available.type": "boolean",
        "stack_stats.kibana.plugins.reporting.last7Days.PNGV2.deprecated.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNGV2.layout.canvas.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNGV2.layout.preserve_layout.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNGV2.layout.print.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNGV2.sizes.1.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNGV2.sizes.25.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNGV2.sizes.5.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNGV2.sizes.50.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNGV2.sizes.75.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNGV2.sizes.95.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNGV2.sizes.99.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.PNGV2.total.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days._all.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv.app.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv.app.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv.app.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv.app.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv.available.type": "boolean",
        "stack_stats.kibana.plugins.reporting.last7Days.csv.deprecated.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv.layout.canvas.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv.layout.preserve_layout.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv.layout.print.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv.sizes.1.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv.sizes.25.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv.sizes.5.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv.sizes.50.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv.sizes.75.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv.sizes.95.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv.sizes.99.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv.total.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource.app.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource.app.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource.app.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource.app.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource.available.type": "boolean",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource.deprecated.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource.layout.canvas.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource.layout.preserve_layout.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource.layout.print.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource.sizes.1.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource.sizes.25.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource.sizes.5.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource.sizes.50.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource.sizes.75.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource.sizes.95.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource.sizes.99.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource.total.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource_immediate.app.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource_immediate.app.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource_immediate.app.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource_immediate.app.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource_immediate.available.type": "boolean",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource_immediate.deprecated.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource_immediate.layout.canvas.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource_immediate.layout.preserve_layout.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource_immediate.layout.print.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource_immediate.sizes.1.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource_immediate.sizes.25.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource_immediate.sizes.5.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource_immediate.sizes.50.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource_immediate.sizes.75.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource_immediate.sizes.95.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource_immediate.sizes.99.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.csv_searchsource_immediate.total.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.output_size.1.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.output_size.25.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.output_size.5.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.output_size.50.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.output_size.75.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.output_size.95.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.output_size.99.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf.app.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf.app.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf.app.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf.app.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf.available.type": "boolean",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf.deprecated.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf.layout.canvas.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf.layout.preserve_layout.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf.layout.print.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf.sizes.1.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf.sizes.25.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf.sizes.5.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf.sizes.50.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf.sizes.75.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf.sizes.95.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf.sizes.99.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf.total.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf_v2.app.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf_v2.app.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf_v2.app.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf_v2.app.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf_v2.available.type": "boolean",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf_v2.deprecated.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf_v2.layout.canvas.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf_v2.layout.preserve_layout.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf_v2.layout.print.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf_v2.sizes.1.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf_v2.sizes.25.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf_v2.sizes.5.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf_v2.sizes.50.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf_v2.sizes.75.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf_v2.sizes.95.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf_v2.sizes.99.0.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.printable_pdf_v2.total.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.status.completed.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.status.completed_with_warnings.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.status.failed.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.status.pending.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.status.processing.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.PNG.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.PNG.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.PNG.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.PNG.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.PNGV2.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.PNGV2.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.PNGV2.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.PNGV2.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.csv.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.csv.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.csv.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.csv.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.csv_searchsource.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.csv_searchsource.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.csv_searchsource.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.csv_searchsource.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.csv_searchsource_immediate.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.csv_searchsource_immediate.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.csv_searchsource_immediate.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.csv_searchsource_immediate.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.printable_pdf.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.printable_pdf.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.printable_pdf.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.printable_pdf.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.printable_pdf_v2.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.printable_pdf_v2.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.printable_pdf_v2.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed.printable_pdf_v2.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.PNG.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.PNG.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.PNG.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.PNG.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.PNGV2.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.PNGV2.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.PNGV2.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.PNGV2.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.csv.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.csv.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.csv.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.csv.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.csv_searchsource.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.csv_searchsource.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.csv_searchsource.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.csv_searchsource.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.csv_searchsource_immediate.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.csv_searchsource_immediate.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.csv_searchsource_immediate.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.csv_searchsource_immediate.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.printable_pdf.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.printable_pdf.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.printable_pdf.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.printable_pdf.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.printable_pdf_v2.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.printable_pdf_v2.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.printable_pdf_v2.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.completed_with_warnings.printable_pdf_v2.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.PNG.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.PNG.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.PNG.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.PNG.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.PNGV2.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.PNGV2.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.PNGV2.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.PNGV2.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.csv.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.csv.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.csv.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.csv.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.csv_searchsource.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.csv_searchsource.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.csv_searchsource.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.csv_searchsource.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.csv_searchsource_immediate.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.csv_searchsource_immediate.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.csv_searchsource_immediate.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.csv_searchsource_immediate.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.printable_pdf.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.printable_pdf.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.printable_pdf.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.printable_pdf.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.printable_pdf_v2.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.printable_pdf_v2.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.printable_pdf_v2.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.failed.printable_pdf_v2.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.PNG.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.PNG.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.PNG.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.PNG.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.PNGV2.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.PNGV2.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.PNGV2.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.PNGV2.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.csv.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.csv.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.csv.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.csv.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.csv_searchsource.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.csv_searchsource.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.csv_searchsource.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.csv_searchsource.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.csv_searchsource_immediate.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.csv_searchsource_immediate.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.csv_searchsource_immediate.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.csv_searchsource_immediate.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.printable_pdf.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.printable_pdf.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.printable_pdf.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.printable_pdf.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.printable_pdf_v2.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.printable_pdf_v2.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.printable_pdf_v2.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.pending.printable_pdf_v2.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.PNG.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.PNG.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.PNG.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.PNG.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.PNGV2.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.PNGV2.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.PNGV2.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.PNGV2.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.csv.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.csv.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.csv.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.csv.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.csv_searchsource.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.csv_searchsource.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.csv_searchsource.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.csv_searchsource.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.csv_searchsource_immediate.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.csv_searchsource_immediate.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.csv_searchsource_immediate.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.csv_searchsource_immediate.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.printable_pdf.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.printable_pdf.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.printable_pdf.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.printable_pdf.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.printable_pdf_v2.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.printable_pdf_v2.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.printable_pdf_v2.search.type": "long",
        "stack_stats.kibana.plugins.reporting.last7Days.statuses.processing.printable_pdf_v2.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.output_size.1.0.type": "long",
        "stack_stats.kibana.plugins.reporting.output_size.25.0.type": "long",
        "stack_stats.kibana.plugins.reporting.output_size.5.0.type": "long",
        "stack_stats.kibana.plugins.reporting.output_size.50.0.type": "long",
        "stack_stats.kibana.plugins.reporting.output_size.75.0.type": "long",
        "stack_stats.kibana.plugins.reporting.output_size.95.0.type": "long",
        "stack_stats.kibana.plugins.reporting.output_size.99.0.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf.app.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf.app.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf.app.search.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf.app.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf.available.type": "boolean",
        "stack_stats.kibana.plugins.reporting.printable_pdf.deprecated.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf.layout.canvas.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf.layout.preserve_layout.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf.layout.print.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf.sizes.1.0.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf.sizes.25.0.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf.sizes.5.0.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf.sizes.50.0.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf.sizes.75.0.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf.sizes.95.0.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf.sizes.99.0.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf.total.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf_v2.app.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf_v2.app.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf_v2.app.search.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf_v2.app.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf_v2.available.type": "boolean",
        "stack_stats.kibana.plugins.reporting.printable_pdf_v2.deprecated.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf_v2.layout.canvas.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf_v2.layout.preserve_layout.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf_v2.layout.print.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf_v2.sizes.1.0.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf_v2.sizes.25.0.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf_v2.sizes.5.0.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf_v2.sizes.50.0.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf_v2.sizes.75.0.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf_v2.sizes.95.0.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf_v2.sizes.99.0.type": "long",
        "stack_stats.kibana.plugins.reporting.printable_pdf_v2.total.type": "long",
        "stack_stats.kibana.plugins.reporting.status.completed.type": "long",
        "stack_stats.kibana.plugins.reporting.status.completed_with_warnings.type": "long",
        "stack_stats.kibana.plugins.reporting.status.failed.type": "long",
        "stack_stats.kibana.plugins.reporting.status.pending.type": "long",
        "stack_stats.kibana.plugins.reporting.status.processing.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.PNG.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.PNG.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.PNG.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.PNG.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.PNGV2.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.PNGV2.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.PNGV2.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.PNGV2.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.csv.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.csv.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.csv.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.csv.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.csv_searchsource.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.csv_searchsource.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.csv_searchsource.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.csv_searchsource.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.csv_searchsource_immediate.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.csv_searchsource_immediate.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.csv_searchsource_immediate.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.csv_searchsource_immediate.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.printable_pdf.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.printable_pdf.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.printable_pdf.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.printable_pdf.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.printable_pdf_v2.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.printable_pdf_v2.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.printable_pdf_v2.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed.printable_pdf_v2.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.PNG.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.PNG.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.PNG.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.PNG.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.PNGV2.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.PNGV2.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.PNGV2.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.PNGV2.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.csv.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.csv.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.csv.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.csv.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.csv_searchsource.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.csv_searchsource.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.csv_searchsource.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.csv_searchsource.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.csv_searchsource_immediate.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.csv_searchsource_immediate.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.csv_searchsource_immediate.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.csv_searchsource_immediate.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.printable_pdf.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.printable_pdf.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.printable_pdf.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.printable_pdf.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.printable_pdf_v2.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.printable_pdf_v2.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.printable_pdf_v2.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.completed_with_warnings.printable_pdf_v2.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.PNG.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.PNG.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.PNG.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.PNG.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.PNGV2.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.PNGV2.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.PNGV2.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.PNGV2.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.csv.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.csv.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.csv.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.csv.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.csv_searchsource.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.csv_searchsource.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.csv_searchsource.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.csv_searchsource.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.csv_searchsource_immediate.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.csv_searchsource_immediate.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.csv_searchsource_immediate.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.csv_searchsource_immediate.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.printable_pdf.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.printable_pdf.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.printable_pdf.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.printable_pdf.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.printable_pdf_v2.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.printable_pdf_v2.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.printable_pdf_v2.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.failed.printable_pdf_v2.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.PNG.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.PNG.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.PNG.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.PNG.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.PNGV2.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.PNGV2.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.PNGV2.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.PNGV2.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.csv.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.csv.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.csv.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.csv.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.csv_searchsource.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.csv_searchsource.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.csv_searchsource.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.csv_searchsource.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.csv_searchsource_immediate.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.csv_searchsource_immediate.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.csv_searchsource_immediate.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.csv_searchsource_immediate.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.printable_pdf.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.printable_pdf.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.printable_pdf.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.printable_pdf.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.printable_pdf_v2.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.printable_pdf_v2.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.printable_pdf_v2.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.pending.printable_pdf_v2.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.PNG.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.PNG.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.PNG.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.PNG.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.PNGV2.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.PNGV2.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.PNGV2.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.PNGV2.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.csv.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.csv.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.csv.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.csv.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.csv_searchsource.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.csv_searchsource.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.csv_searchsource.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.csv_searchsource.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.csv_searchsource_immediate.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.csv_searchsource_immediate.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.csv_searchsource_immediate.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.csv_searchsource_immediate.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.printable_pdf.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.printable_pdf.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.printable_pdf.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.printable_pdf.visualization.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.printable_pdf_v2.canvas workpad.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.printable_pdf_v2.dashboard.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.printable_pdf_v2.search.type": "long",
        "stack_stats.kibana.plugins.reporting.statuses.processing.printable_pdf_v2.visualization.type": "long",
      }
    `);
  });
});
