/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0 and the Server Side Public License, v 1; you may not use this file except
 * in compliance with, at your election, the Elastic License 2.0 or the Server
 * Side Public License, v 1.
 */

export const languages = [
  'Afrikaans',
  'Akan',
  'አማርኛ',
  'العربية',
  'অসমীয়া',
  'azərbaycan',
  'беларуская',
  'български',
  'bamanakan',
  'বাংলা',
  'བོད་སྐད་',
  'brezhoneg',
  'bosanski',
  'català',
  'čeština',
  'Cymraeg',
  'dansk',
  'Deutsch',
  'Österreichisches Deutsch',
  'Schweizer Hochdeutsch',
  'རྫོང་ཁ',
  'eʋegbe',
  'Ελληνικά',
  'English',
  'Australian English',
  'Canadian English',
  'British English',
  'American English',
  'esperanto',
  'español',
  'español de España',
  'español de México',
  'eesti',
  'euskara',
  'فارسی',
  'Pulaar',
  'suomi',
  'føroyskt',
  'français',
  'français canadien',
  'français suisse',
  'West-Frysk',
  'Gaeilge',
  'Gàidhlig',
  'galego',
  'ગુજરાતી',
  'Gaelg',
  'Hausa',
  'עברית',
  'हिंदी',
  'hrvatski',
  'magyar',
  'հայերեն',
  'Bahasa Indonesia',
  'Igbo',
  'ꆈꌠꉙ',
  'íslenska',
  'italiano',
  '日本語',
  'ქართული',
  'Gikuyu',
  'қазақ тілі',
  'kalaallisut',
  'ខ្មែរ',
  'ಕನ್ನಡ',
  '한국어',
  'کٲشُر',
  'kernewek',
  'кыргызча',
  'Lëtzebuergesch',
  'Luganda',
  'lingála',
  'ລາວ',
  'lietuvių',
  'Tshiluba',
  'latviešu',
  'Malagasy',
  'македонски',
  'മലയാളം',
  'монгол',
  'मराठी',
  'Bahasa Melayu',
  'Malti',
  'ဗမာ',
  'norsk bokmål',
  'isiNdebele',
  'नेपाली',
  'Nederlands',
  'Vlaams',
  'nynorsk',
  'norsk',
  'Oromoo',
  'ଓଡ଼ିଆ',
  'ирон',
  'ਪੰਜਾਬੀ',
  'polski',
  'پښتو',
  'português',
  'português do Brasil',
  'português europeu',
  'Runasimi',
  'rumantsch',
  'Ikirundi',
  'română',
  'moldovenească',
  'русский',
  'Kinyarwanda',
  'davvisámegiella',
  'Sängö',
  'Srpskohrvatski',
  'සිංහල',
  'slovenčina',
  'slovenščina',
  'chiShona',
  'Soomaali',
  'shqip',
  'српски',
  'svenska',
  'Kiswahili',
  'தமிழ்',
  'తెలుగు',
  'ไทย',
  'ትግርኛ',
  'Tagalog',
  'lea fakatonga',
  'Türkçe',
  'ئۇيغۇرچە',
  'українська',
  'اردو',
  'oʻzbekcha',
  'Tiếng Việt',
  'ייִדיש',
  'Èdè Yorùbá',
  '中文',
  '简体中文',
  '繁體中文',
  'isiZulu',
];
