import type { ValuesType } from 'utility-types';
declare const EVENT_MODULE: "event.module";
declare const ALERT_BUILDING_BLOCK_TYPE: "kibana.alert.building_block_type";
declare const ALERT_EVALUATION_THRESHOLD: "kibana.alert.evaluation.threshold";
declare const ALERT_EVALUATION_TIME_RANGE: "kibana.alert.evaluation.time_range";
declare const ALERT_EVALUATION_VALUE: "kibana.alert.evaluation.value";
declare const ALERT_CONTEXT: "kibana.alert.context";
declare const ALERT_EVALUATION_VALUES: "kibana.alert.evaluation.values";
declare const ALERT_GROUPING: "kibana.alert.grouping";
declare const ALERT_GROUP: "kibana.alert.group";
declare const ALERT_GROUP_FIELD: "kibana.alert.group.field";
declare const ALERT_GROUP_VALUE: "kibana.alert.group.value";
declare const ALERT_RULE_EXCEPTIONS_LIST: "kibana.alert.rule.exceptions_list";
declare const ALERT_RULE_NAMESPACE_FIELD: "kibana.alert.rule.namespace";
declare const ALERT_THREAT_FRAMEWORK: "kibana.alert.rule.threat.framework";
declare const ALERT_THREAT_TACTIC_ID: "kibana.alert.rule.threat.tactic.id";
declare const ALERT_THREAT_TACTIC_NAME: "kibana.alert.rule.threat.tactic.name";
declare const ALERT_THREAT_TACTIC_REFERENCE: "kibana.alert.rule.threat.tactic.reference";
declare const ALERT_THREAT_TECHNIQUE_ID: "kibana.alert.rule.threat.technique.id";
declare const ALERT_THREAT_TECHNIQUE_NAME: "kibana.alert.rule.threat.technique.name";
declare const ALERT_THREAT_TECHNIQUE_REFERENCE: "kibana.alert.rule.threat.technique.reference";
declare const ALERT_THREAT_TECHNIQUE_SUBTECHNIQUE_ID: "kibana.alert.rule.threat.technique.subtechnique.id";
declare const ALERT_THREAT_TECHNIQUE_SUBTECHNIQUE_NAME: "kibana.alert.rule.threat.technique.subtechnique.name";
declare const ALERT_THREAT_TECHNIQUE_SUBTECHNIQUE_REFERENCE: "kibana.alert.rule.threat.technique.subtechnique.reference";
declare const namespaces: {
    KIBANA_NAMESPACE: "kibana";
    ALERT_NAMESPACE: "kibana.alert";
    ALERT_RULE_NAMESPACE: "kibana.alert.rule";
};
declare const fields: {
    ECS_VERSION: "ecs.version";
    EVENT_KIND: "event.kind";
    EVENT_ACTION: "event.action";
    EVENT_MODULE: "event.module";
    TAGS: "tags";
    TIMESTAMP: "@timestamp";
    ALERT_ACTION_GROUP: "kibana.alert.action_group";
    ALERT_BUILDING_BLOCK_TYPE: "kibana.alert.building_block_type";
    ALERT_DURATION: "kibana.alert.duration.us";
    ALERT_END: "kibana.alert.end";
    ALERT_EVALUATION_THRESHOLD: "kibana.alert.evaluation.threshold";
    ALERT_EVALUATION_TIME_RANGE: "kibana.alert.evaluation.time_range";
    ALERT_EVALUATION_VALUE: "kibana.alert.evaluation.value";
    ALERT_EVALUATION_VALUES: "kibana.alert.evaluation.values";
    ALERT_GROUPING: "kibana.alert.grouping";
    ALERT_GROUP: "kibana.alert.group";
    ALERT_GROUP_FIELD: "kibana.alert.group.field";
    ALERT_GROUP_VALUE: "kibana.alert.group.value";
    ALERT_FLAPPING: "kibana.alert.flapping";
    ALERT_MAINTENANCE_WINDOW_IDS: "kibana.alert.maintenance_window_ids";
    ALERT_MAINTENANCE_WINDOW_NAMES: "kibana.alert.maintenance_window_names";
    ALERT_INSTANCE_ID: "kibana.alert.instance.id";
    ALERT_RULE_CONSUMER: "kibana.alert.rule.consumer";
    ALERT_RULE_PRODUCER: "kibana.alert.rule.producer";
    ALERT_REASON: "kibana.alert.reason";
    ALERT_CONTEXT: "kibana.alert.context";
    ALERT_RISK_SCORE: "kibana.alert.risk_score";
    ALERT_CASE_IDS: "kibana.alert.case_ids";
    ALERT_RULE_AUTHOR: "kibana.alert.rule.author";
    ALERT_RULE_CREATED_AT: "kibana.alert.rule.created_at";
    ALERT_RULE_CREATED_BY: "kibana.alert.rule.created_by";
    ALERT_RULE_DESCRIPTION: "kibana.alert.rule.description";
    ALERT_RULE_ENABLED: "kibana.alert.rule.enabled";
    ALERT_RULE_EXCEPTIONS_LIST: "kibana.alert.rule.exceptions_list";
    ALERT_RULE_EXECUTION_UUID: "kibana.alert.rule.execution.uuid";
    ALERT_RULE_FROM: "kibana.alert.rule.from";
    ALERT_RULE_INTERVAL: "kibana.alert.rule.interval";
    ALERT_RULE_LICENSE: "kibana.alert.rule.license";
    ALERT_RULE_NAME: "kibana.alert.rule.name";
    ALERT_RULE_NAMESPACE_FIELD: "kibana.alert.rule.namespace";
    ALERT_RULE_NOTE: "kibana.alert.rule.note";
    ALERT_RULE_PARAMETERS: "kibana.alert.rule.parameters";
    ALERT_RULE_REFERENCES: "kibana.alert.rule.references";
    ALERT_RULE_RULE_ID: "kibana.alert.rule.rule_id";
    ALERT_RULE_RULE_NAME_OVERRIDE: "kibana.alert.rule.rule_name_override";
    ALERT_RULE_TAGS: "kibana.alert.rule.tags";
    ALERT_RULE_TO: "kibana.alert.rule.to";
    ALERT_RULE_TYPE: "kibana.alert.rule.type";
    ALERT_RULE_TYPE_ID: "kibana.alert.rule.rule_type_id";
    ALERT_RULE_UPDATED_AT: "kibana.alert.rule.updated_at";
    ALERT_RULE_UPDATED_BY: "kibana.alert.rule.updated_by";
    ALERT_RULE_VERSION: "kibana.alert.rule.version";
    ALERT_START: "kibana.alert.start";
    ALERT_TIME_RANGE: "kibana.alert.time_range";
    ALERT_SEVERITY: "kibana.alert.severity";
    ALERT_STATUS: "kibana.alert.status";
    ALERT_SYSTEM_STATUS: "kibana.alert.system_status";
    ALERT_UUID: "kibana.alert.uuid";
    ALERT_WORKFLOW_ASSIGNEE_IDS: "kibana.alert.workflow_assignee_ids";
    ALERT_WORKFLOW_REASON: "kibana.alert.workflow_reason";
    ALERT_WORKFLOW_STATUS: "kibana.alert.workflow_status";
    ALERT_WORKFLOW_TAGS: "kibana.alert.workflow_tags";
    ALERT_WORKFLOW_USER: "kibana.alert.workflow_user";
    ALERT_RULE_UUID: "kibana.alert.rule.uuid";
    ALERT_RULE_CATEGORY: "kibana.alert.rule.category";
    ALERT_THREAT_FRAMEWORK: "kibana.alert.rule.threat.framework";
    ALERT_THREAT_TACTIC_ID: "kibana.alert.rule.threat.tactic.id";
    ALERT_THREAT_TACTIC_NAME: "kibana.alert.rule.threat.tactic.name";
    ALERT_THREAT_TACTIC_REFERENCE: "kibana.alert.rule.threat.tactic.reference";
    ALERT_THREAT_TECHNIQUE_ID: "kibana.alert.rule.threat.technique.id";
    ALERT_THREAT_TECHNIQUE_NAME: "kibana.alert.rule.threat.technique.name";
    ALERT_THREAT_TECHNIQUE_REFERENCE: "kibana.alert.rule.threat.technique.reference";
    ALERT_THREAT_TECHNIQUE_SUBTECHNIQUE_ID: "kibana.alert.rule.threat.technique.subtechnique.id";
    ALERT_THREAT_TECHNIQUE_SUBTECHNIQUE_NAME: "kibana.alert.rule.threat.technique.subtechnique.name";
    ALERT_THREAT_TECHNIQUE_SUBTECHNIQUE_REFERENCE: "kibana.alert.rule.threat.technique.subtechnique.reference";
    ALERT_SUPPRESSION_TERMS: "kibana.alert.suppression.terms";
    ALERT_SUPPRESSION_FIELD: "kibana.alert.suppression.terms.field";
    ALERT_SUPPRESSION_VALUE: "kibana.alert.suppression.terms.value";
    ALERT_SUPPRESSION_START: "kibana.alert.suppression.start";
    ALERT_SUPPRESSION_END: "kibana.alert.suppression.end";
    ALERT_SUPPRESSION_DOCS_COUNT: "kibana.alert.suppression.docs_count";
    SPACE_IDS: "kibana.space_ids";
    VERSION: "kibana.version";
};
export { ALERT_BUILDING_BLOCK_TYPE, ALERT_EVALUATION_THRESHOLD, ALERT_EVALUATION_TIME_RANGE, ALERT_EVALUATION_VALUE, ALERT_CONTEXT, ALERT_EVALUATION_VALUES, ALERT_GROUPING, ALERT_GROUP, ALERT_GROUP_FIELD, ALERT_GROUP_VALUE, ALERT_RULE_EXCEPTIONS_LIST, ALERT_RULE_NAMESPACE_FIELD, ALERT_THREAT_FRAMEWORK, ALERT_THREAT_TACTIC_ID, ALERT_THREAT_TACTIC_NAME, ALERT_THREAT_TACTIC_REFERENCE, ALERT_THREAT_TECHNIQUE_ID, ALERT_THREAT_TECHNIQUE_NAME, ALERT_THREAT_TECHNIQUE_REFERENCE, ALERT_THREAT_TECHNIQUE_SUBTECHNIQUE_ID, ALERT_THREAT_TECHNIQUE_SUBTECHNIQUE_NAME, ALERT_THREAT_TECHNIQUE_SUBTECHNIQUE_REFERENCE, EVENT_MODULE, };
export type TechnicalRuleDataFieldName = ValuesType<typeof fields & typeof namespaces>;
