[role="xpack"]
[[alerting-production-considerations]]
== Production considerations

{kib} alerting run both alert checks and actions as persistent background tasks managed by the {kib} Task Manager.

When relying on Alerts and Actions as mission critical services, it is important to ensure the {kib} Task Manager <<task-manager-production-considerations>> are followed.


[float]
=== Running background alert checks and actions

{kib} uses <<task-manager>> to run Alerts and Actions as background tasks, distributed across all {kib} nodes in the cluster.

By default, each {kib} instance polls for work at 3 second intervals, and can run a maximum of 10 concurrent tasks.
These tasks are then ran on the {kib} server.

In the case of alerts which are recurring background checks, upon completion the task is scheduled again according to the <<defining-alerts-general-details, check interval>>.

For more details on Task Manager, see <<task-manager-background-tasks>>.

[IMPORTANT]
==============================================
It is possible for alert and action tasks to be run late or at an inconsistent schedule.
This is usually a symptom of the specific usage of the cluster in question.

Such issues can be addressed by tweaking the {kib} <<task-manager>> or adjusting the cluster scaling strategy to better suit the unique use case.

For detailed guidance, see <<alerting-troubleshooting,`Alerting Troubelshooting`>>.
==============================================
