[role="xpack"]
[[alert-types]]
== Alerts

Kibana provides two types of alerts:

* Stack alerts, which are built into {kib}
* Domain-specific alerts, which are registered by {kib} apps.

[float]
==== Standard stack alerts

{kib} provides two stack alerts: 

* <<alert-type-index-threshold>>
* <<alert-type-es-query>>

Users require the `all` privilege to access the *Stack Alerts* feature and create and edit alerts.
See <<kibana-feature-privileges, feature privileges>> for more information.

[float]
==== Domain-specific alerts

For domain-specific alerts, refer to the documentation for that app.
{kib} supports these alerts:

* {observability-guide}/create-alerts.html[Observability alerts]
* {security-guide}/prebuilt-rules.html[Security alerts]
* <<geo-alerting, Maps alerts>>
* {ml-docs}/ml-configuring-alerts.html[{ml-cap} alerts] beta:[]

[NOTE]
==============================================
Some alert types are subscription features, while others are free features.
For a comparison of the Elastic subscription levels,
see {subscriptions}[the subscription page].
==============================================


include::stack-alerts/index-threshold.asciidoc[]
include::stack-alerts/es-query.asciidoc[]
include::maps-alerts/geo-alert-types.asciidoc[]
