[role="xpack"]
[[rule-types]]
== Rule types

A rule is a set of <<alerting-concepts-conditions, conditions>>, <<alerting-concepts-scheduling, schedules>>, and <<alerting-concepts-actions, actions>> that enable notifications. {kib} provides rules built into the Elastic Stack and rules registered by one of the {kib} apps.

[NOTE]
==============================================
Some rule types are subscription features, while others are free features.
For a comparison of the Elastic subscription levels,
see {subscriptions}[the subscription page].
==============================================

[float]
[[stack-rules]]
=== Stack rules

<<create-and-manage-rules, Stack rules>> are built into {kib}. To access the *Stack Rules* feature and create and edit rules, users require the `all` privilege. See <<kibana-feature-privileges, feature privileges>> for more information. In the full rules list in the UI, Stack rules are shown under the proper category `STACK RULES`.

[cols="2*<"]
|===

| <<rule-type-es-query>>
| Run a user-configured {es} query, compare the number of matches to a configured threshold, and schedule actions to run when the threshold condition is met.

| <<rule-type-index-threshold>>
| Aggregate field values from documents using {es} queries, compare them to threshold values, and schedule actions to run when the thresholds are met.

| {ref}/transform-alerts.html[{transform-cap} rules] beta:[]
| beta:[] Run scheduled checks on a {ctransform} to check its health. If a {ctransform} meets the conditions, an alert is created and the associated action is triggered.

| <<geo-alerting, Tracking containment>>
| Run an {es} query to determine if any documents are currently contained in any boundaries from a specified boundary index and generate alerts when a rule's conditions are met.

|===

[float]
[[observability-rules]]
=== Observability rules

In the rules list in the Management UI, Observability rules are shown under the multiple categories `APM AND USER EXPERIENCE`, `LOGS`, `METRICS`, `STACK MONITORING` and `UPTIME`.

[cols="2*<"]
|===


| <<apm-alerts, APM and User Experience>>
| Allows to define rules to detect complex conditions within *APM* data and trigger built-in actions when those conditions are met.

| {observability-guide}/create-alerts.html[Logs rules]
| Detect complex conditions in the *Logs* app.

| {observability-guide}/create-alerts.html[Metrics rules]
| Detect complex conditions in the *Metrics* app.

| <<kibana-alerts,Stack Monitoring>>
| Provide {kib} Alerting rules out-of-the box to notify you of potential issues in the Elastic Stack.

| {observability-guide}/create-alerts.html[Uptime rules]
| Detect complex conditions in the *Uptime* app.

|===

[float]
[[ml-rules]]
=== Machine learning rules

beta:[] {ml-docs}/ml-configuring-alerts.html[{ml-cap} rules] run scheduled checks on an {anomaly-job} to detect anomalies with certain conditions. If an anomaly meets the conditions, an alert is created and the associated action is triggered. In the rules list in the Management UI, Machine learning rules are shown under the proper category `MACHINE LEARNING`.

[float]
[[security-rules]]
=== Security rules

Security rules detect suspicious source events with pre-built or custom rules and create alerts when a rule’s conditions are met. For more information, refer to {security-guide}/prebuilt-rules.html[Security rules].

include::rule-types/index-threshold.asciidoc[]
include::rule-types/es-query.asciidoc[]
include::rule-types/geo-rule-types.asciidoc[]
