steps:
  - command: .buildkite/scripts/steps/jest_bench.sh
    label: 'Jest Bench'
    key: jest_bench
    agents:
      machineType: n4-standard-16
      diskType: hyperdisk-balanced
      zones: us-central1-a,us-east4-b,us-east1-b
      diskSizeGb: 100
    timeout_in_minutes: 60
    soft_fail: true
