#!/bin/bash

set -euo pipefail

export VAULT_ADDR=https://secrets.elastic.co:8200

VAULT_ROLE_ID="$(gcloud secrets versions access latest --secret=kibana-buildkite-vault-role-id)"
# export VAULT_ROLE_ID

VAULT_SECRET_ID="$(gcloud secrets versions access latest --secret=kibana-buildkite-vault-secret-id)"
# export VAULT_SECRET_ID

vault login -no-print "$(vault write -field=token auth/approle/login role_id="$VAULT_ROLE_ID" secret_id="$VAULT_SECRET_ID")"

export DOCKER_BUILDKIT=1
