/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Entity Analytics API client for Scout tests
 *   version: Bundle (no version)
 */

import type { ApiClientFixture, ApiClientOptions, ApiClientResponse } from '@kbn/scout';
import {
  ELASTIC_HTTP_VERSION_HEADER,
  X_ELASTIC_INTERNAL_ORIGIN_REQUEST,
} from '@kbn/core-http-common';
import { encodePathParams, replaceParams } from '@kbn/openapi-common/shared';
import { stringify as stringifyQuery } from 'query-string';

import type { ApplyEntityEngineDataviewIndicesResponse } from '@kbn/security-solution-plugin/common/api/entity_analytics/entity_store/engine/apply_dataview_indices.gen';
import type { AssetCriticalityGetPrivilegesResponse } from '@kbn/security-solution-plugin/common/api/entity_analytics/asset_criticality/get_asset_criticality_privileges.gen';
import type {
  BulkUpsertAssetCriticalityRecordsRequestBodyInput,
  BulkUpsertAssetCriticalityRecordsResponse,
} from '@kbn/security-solution-plugin/common/api/entity_analytics/asset_criticality/bulk_upload_asset_criticality.gen';
import type { CleanUpRiskEngineResponse } from '@kbn/security-solution-plugin/common/api/entity_analytics/risk_engine/engine_cleanup_route.gen';
import type {
  ConfigureRiskEngineSavedObjectRequestBodyInput,
  ConfigureRiskEngineSavedObjectResponse,
} from '@kbn/security-solution-plugin/common/api/entity_analytics/risk_engine/engine_configure_saved_object_route.gen';
import type {
  CreateAssetCriticalityRecordRequestBodyInput,
  CreateAssetCriticalityRecordResponse,
} from '@kbn/security-solution-plugin/common/api/entity_analytics/asset_criticality/create_asset_criticality.gen';
import type {
  DeleteAssetCriticalityRecordRequestQueryInput,
  DeleteAssetCriticalityRecordResponse,
} from '@kbn/security-solution-plugin/common/api/entity_analytics/asset_criticality/delete_asset_criticality.gen';
import type {
  DeleteEntityEngineRequestQueryInput,
  DeleteEntityEngineRequestParamsInput,
  DeleteEntityEngineResponse,
} from '@kbn/security-solution-plugin/common/api/entity_analytics/entity_store/engine/delete.gen';
import type {
  DeprecatedTriggerRiskScoreCalculationRequestBodyInput,
  DeprecatedTriggerRiskScoreCalculationResponse,
  TriggerRiskScoreCalculationRequestBodyInput,
  TriggerRiskScoreCalculationResponse,
} from '@kbn/security-solution-plugin/common/api/entity_analytics/risk_engine/entity_calculation_route.gen';
import type { DisableRiskEngineResponse } from '@kbn/security-solution-plugin/common/api/entity_analytics/risk_engine/engine_disable_route.gen';
import type { EnableRiskEngineResponse } from '@kbn/security-solution-plugin/common/api/entity_analytics/risk_engine/engine_enable_route.gen';
import type { EntityStoreGetPrivilegesResponse } from '@kbn/security-solution-plugin/common/api/entity_analytics/entity_store/engine/get_privileges.gen';
import type {
  FindAssetCriticalityRecordsRequestQueryInput,
  FindAssetCriticalityRecordsResponse,
} from '@kbn/security-solution-plugin/common/api/entity_analytics/asset_criticality/list_asset_criticality.gen';
import type {
  GetAssetCriticalityRecordRequestQueryInput,
  GetAssetCriticalityRecordResponse,
} from '@kbn/security-solution-plugin/common/api/entity_analytics/asset_criticality/get_asset_criticality.gen';
import type { GetAssetCriticalityStatusResponse } from '@kbn/security-solution-plugin/common/api/entity_analytics/asset_criticality/get_asset_criticality_status.gen';
import type {
  GetEntityEngineRequestParamsInput,
  GetEntityEngineResponse,
} from '@kbn/security-solution-plugin/common/api/entity_analytics/entity_store/engine/get.gen';
import type {
  GetEntityStoreStatusRequestQueryInput,
  GetEntityStoreStatusResponse,
} from '@kbn/security-solution-plugin/common/api/entity_analytics/entity_store/status.gen';
import type { GetRiskEngineStatusResponse } from '@kbn/security-solution-plugin/common/api/entity_analytics/risk_engine/engine_status_route.gen';
import type {
  InitEntityEngineRequestParamsInput,
  InitEntityEngineRequestBodyInput,
  InitEntityEngineResponse,
} from '@kbn/security-solution-plugin/common/api/entity_analytics/entity_store/engine/init.gen';
import type {
  InitEntityStoreRequestBodyInput,
  InitEntityStoreResponse,
} from '@kbn/security-solution-plugin/common/api/entity_analytics/entity_store/enable.gen';
import type { InitRiskEngineResponse } from '@kbn/security-solution-plugin/common/api/entity_analytics/risk_engine/engine_init_route.gen';
import type {
  InternalUploadAssetCriticalityRecordsResponse,
  UploadAssetCriticalityRecordsResponse,
} from '@kbn/security-solution-plugin/common/api/entity_analytics/asset_criticality/upload_asset_criticality_csv.gen';
import type {
  ListEntitiesRequestQueryInput,
  ListEntitiesResponse,
} from '@kbn/security-solution-plugin/common/api/entity_analytics/entity_store/entities/list_entities.gen';
import type { ListEntityEnginesResponse } from '@kbn/security-solution-plugin/common/api/entity_analytics/entity_store/engine/list.gen';
import type {
  PreviewRiskScoreRequestBodyInput,
  PreviewRiskScoreResponse,
} from '@kbn/security-solution-plugin/common/api/entity_analytics/risk_engine/preview_route.gen';
import type { ReadRiskEngineSettingsResponse } from '@kbn/security-solution-plugin/common/api/entity_analytics/risk_engine/engine_settings_route.gen';
import type { RiskEngineGetPrivilegesResponse } from '@kbn/security-solution-plugin/common/api/entity_analytics/risk_engine/get_risk_engine_privileges.gen';
import type { RunEntityAnalyticsMigrationsResponse } from '@kbn/security-solution-plugin/common/api/entity_analytics/migrations/run_migrations_route.gen';
import type { ScheduleRiskEngineNowResponse } from '@kbn/security-solution-plugin/common/api/entity_analytics/risk_engine/engine_schedule_now_route.gen';
import type {
  StartEntityEngineRequestParamsInput,
  StartEntityEngineResponse,
} from '@kbn/security-solution-plugin/common/api/entity_analytics/entity_store/engine/start.gen';
import type {
  StopEntityEngineRequestParamsInput,
  StopEntityEngineResponse,
} from '@kbn/security-solution-plugin/common/api/entity_analytics/entity_store/engine/stop.gen';

export type ScoutResponseType = NonNullable<ApiClientOptions['responseType']>;

/**
 * Body the Scout `apiClient` yields for a given `responseType`: the OpenAPI response for 'json',
 * a string for 'text' and a Buffer for 'buffer'.
 */
export type ScoutResponseBody<
  TResponseType extends ScoutResponseType,
  TJsonBody = ApiClientResponse['body']
> = TResponseType extends 'text' ? string : TResponseType extends 'buffer' ? Buffer : TJsonBody;

export interface ScoutApiRequestOptions<
  TResponseType extends ScoutResponseType = ScoutResponseType
> {
  /** Extra headers merged on top of the defaults, e.g. an API key or a SAML cookie for auth */
  headers?: Record<string, string>;
  /** Kibana space id the request targets. Omit or pass 'default' for the default space */
  kibanaSpace?: string;
  /**
   * How the response body should be parsed. Defaults to 'json'.
   * Use 'text' or 'buffer' for endpoints returning non-JSON payloads, e.g. NDJSON or CSV exports;
   * the returned `body` is then typed as a string or a Buffer accordingly.
   */
  responseType?: TResponseType;
  /**
   * Raw request body for operations whose payload is not described by the OpenAPI request body,
   * e.g. multipart/form-data imports. Ignored for operations with a typed request body.
   */
  body?: ApiClientOptions['body'];
}

const securitySolutionScoutApiServiceFactory = (apiClient: ApiClientFixture) => ({
  /**
   * Synchronize data view index patterns to all running entity engines so that newly added indices are picked up by the transforms.
   */
  async applyEntityEngineDataviewIndices<TResponseType extends ScoutResponseType = 'json'>(
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<
    ApiClientResponse<ScoutResponseBody<TResponseType, ApplyEntityEngineDataviewIndicesResponse>>
  > {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/api/entity_store/engines/apply_dataview_indices`;

    return apiClient.post<
      ScoutResponseBody<TResponseType, ApplyEntityEngineDataviewIndicesResponse>
    >(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      body: options.body,
      responseType: options.responseType ?? 'json',
    });
  },
  async assetCriticalityGetPrivileges<TResponseType extends ScoutResponseType = 'json'>(
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<
    ApiClientResponse<ScoutResponseBody<TResponseType, AssetCriticalityGetPrivilegesResponse>>
  > {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/internal/asset_criticality/privileges`;

    return apiClient.get<ScoutResponseBody<TResponseType, AssetCriticalityGetPrivilegesResponse>>(
      path,
      {
        headers: {
          'kbn-xsrf': 'true',
          [ELASTIC_HTTP_VERSION_HEADER]: '1',
          [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
          ...options.headers,
        },
        body: options.body,
        responseType: options.responseType ?? 'json',
      }
    );
  },
  /**
      * Bulk upsert up to 1000 asset criticality records.

If asset criticality records already exist for the specified entities, those records are overwritten with the specified values. If asset criticality records don't exist for the specified entities, new records are created.

      */
  async bulkUpsertAssetCriticalityRecords<TResponseType extends ScoutResponseType = 'json'>(
    props: BulkUpsertAssetCriticalityRecordsProps,
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<
    ApiClientResponse<ScoutResponseBody<TResponseType, BulkUpsertAssetCriticalityRecordsResponse>>
  > {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/api/asset_criticality/bulk`;

    return apiClient.post<
      ScoutResponseBody<TResponseType, BulkUpsertAssetCriticalityRecordsResponse>
    >(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      body: props.body,
      responseType: options.responseType ?? 'json',
    });
  },
  /**
   * Cleaning up the the Risk Engine by removing the indices, mapping and transforms
   */
  async cleanUpRiskEngine<TResponseType extends ScoutResponseType = 'json'>(
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<ApiClientResponse<ScoutResponseBody<TResponseType, CleanUpRiskEngineResponse>>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/api/risk_score/engine/dangerously_delete_data`;

    return apiClient.delete<ScoutResponseBody<TResponseType, CleanUpRiskEngineResponse>>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      body: options.body,
      responseType: options.responseType ?? 'json',
    });
  },
  /**
   * Configuring the Risk Engine Saved Object
   */
  async configureRiskEngineSavedObject<TResponseType extends ScoutResponseType = 'json'>(
    props: ConfigureRiskEngineSavedObjectProps,
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<
    ApiClientResponse<ScoutResponseBody<TResponseType, ConfigureRiskEngineSavedObjectResponse>>
  > {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/api/risk_score/engine/saved_object/configure`;

    return apiClient.patch<
      ScoutResponseBody<TResponseType, ConfigureRiskEngineSavedObjectResponse>
    >(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      body: props.body,
      responseType: options.responseType ?? 'json',
    });
  },
  /**
      * Create or update an asset criticality record for a specific entity.

If a record already exists for the specified entity, that record is overwritten with the specified value. If a record doesn't exist for the specified entity, a new record is created.

      */
  async createAssetCriticalityRecord<TResponseType extends ScoutResponseType = 'json'>(
    props: CreateAssetCriticalityRecordProps,
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<
    ApiClientResponse<ScoutResponseBody<TResponseType, CreateAssetCriticalityRecordResponse>>
  > {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/api/asset_criticality`;

    return apiClient.post<ScoutResponseBody<TResponseType, CreateAssetCriticalityRecordResponse>>(
      path,
      {
        headers: {
          'kbn-xsrf': 'true',
          [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
          [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
          ...options.headers,
        },
        body: props.body,
        responseType: options.responseType ?? 'json',
      }
    );
  },
  /**
   * Delete the asset criticality record for a specific entity.
   */
  async deleteAssetCriticalityRecord<TResponseType extends ScoutResponseType = 'json'>(
    props: DeleteAssetCriticalityRecordProps,
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<
    ApiClientResponse<ScoutResponseBody<TResponseType, DeleteAssetCriticalityRecordResponse>>
  > {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/api/asset_criticality`;

    return apiClient.delete<ScoutResponseBody<TResponseType, DeleteAssetCriticalityRecordResponse>>(
      `${path}?${stringifyQuery(props.query, { arrayFormat: 'none' })}`,
      {
        headers: {
          'kbn-xsrf': 'true',
          [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
          [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
          ...options.headers,
        },
        body: options.body,
        responseType: options.responseType ?? 'json',
      }
    );
  },
  async deleteEntityEngine<TResponseType extends ScoutResponseType = 'json'>(
    props: DeleteEntityEngineProps,
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<ApiClientResponse<ScoutResponseBody<TResponseType, DeleteEntityEngineResponse>>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}${replaceParams(
      '/api/entity_store/engines/{entityType}',
      encodePathParams(props.params)
    )}`;

    return apiClient.delete<ScoutResponseBody<TResponseType, DeleteEntityEngineResponse>>(
      `${path}?${stringifyQuery(props.query, { arrayFormat: 'none' })}`,
      {
        headers: {
          'kbn-xsrf': 'true',
          [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
          [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
          ...options.headers,
        },
        body: options.body,
        responseType: options.responseType ?? 'json',
      }
    );
  },
  /**
   * Calculates and persists Risk Scores for an entity, returning the calculated risk score.
   */
  async deprecatedTriggerRiskScoreCalculation<TResponseType extends ScoutResponseType = 'json'>(
    props: DeprecatedTriggerRiskScoreCalculationProps,
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<
    ApiClientResponse<
      ScoutResponseBody<TResponseType, DeprecatedTriggerRiskScoreCalculationResponse>
    >
  > {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/api/risk_scores/calculation/entity`;

    return apiClient.post<
      ScoutResponseBody<TResponseType, DeprecatedTriggerRiskScoreCalculationResponse>
    >(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '1',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      body: props.body,
      responseType: options.responseType ?? 'json',
    });
  },
  async disableRiskEngine<TResponseType extends ScoutResponseType = 'json'>(
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<ApiClientResponse<ScoutResponseBody<TResponseType, DisableRiskEngineResponse>>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/internal/risk_score/engine/disable`;

    return apiClient.post<ScoutResponseBody<TResponseType, DisableRiskEngineResponse>>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '1',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      body: options.body,
      responseType: options.responseType ?? 'json',
    });
  },
  async enableRiskEngine<TResponseType extends ScoutResponseType = 'json'>(
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<ApiClientResponse<ScoutResponseBody<TResponseType, EnableRiskEngineResponse>>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/internal/risk_score/engine/enable`;

    return apiClient.post<ScoutResponseBody<TResponseType, EnableRiskEngineResponse>>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '1',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      body: options.body,
      responseType: options.responseType ?? 'json',
    });
  },
  /**
   * Check whether the current user has the required Elasticsearch and Kibana privileges to use the Entity Store.
   */
  async entityStoreGetPrivileges<TResponseType extends ScoutResponseType = 'json'>(
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<
    ApiClientResponse<ScoutResponseBody<TResponseType, EntityStoreGetPrivilegesResponse>>
  > {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/internal/entity_store/privileges`;

    return apiClient.get<ScoutResponseBody<TResponseType, EntityStoreGetPrivilegesResponse>>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '1',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      body: options.body,
      responseType: options.responseType ?? 'json',
    });
  },
  /**
   * List asset criticality records, paging, sorting and filtering as needed.
   */
  async findAssetCriticalityRecords<TResponseType extends ScoutResponseType = 'json'>(
    props: FindAssetCriticalityRecordsProps,
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<
    ApiClientResponse<ScoutResponseBody<TResponseType, FindAssetCriticalityRecordsResponse>>
  > {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/api/asset_criticality/list`;

    return apiClient.get<ScoutResponseBody<TResponseType, FindAssetCriticalityRecordsResponse>>(
      `${path}?${stringifyQuery(props.query, { arrayFormat: 'none' })}`,
      {
        headers: {
          'kbn-xsrf': 'true',
          [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
          [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
          ...options.headers,
        },
        body: options.body,
        responseType: options.responseType ?? 'json',
      }
    );
  },
  /**
   * Get the asset criticality record for a specific entity.
   */
  async getAssetCriticalityRecord<TResponseType extends ScoutResponseType = 'json'>(
    props: GetAssetCriticalityRecordProps,
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<
    ApiClientResponse<ScoutResponseBody<TResponseType, GetAssetCriticalityRecordResponse>>
  > {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/api/asset_criticality`;

    return apiClient.get<ScoutResponseBody<TResponseType, GetAssetCriticalityRecordResponse>>(
      `${path}?${stringifyQuery(props.query, { arrayFormat: 'none' })}`,
      {
        headers: {
          'kbn-xsrf': 'true',
          [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
          [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
          ...options.headers,
        },
        body: options.body,
        responseType: options.responseType ?? 'json',
      }
    );
  },
  async getAssetCriticalityStatus<TResponseType extends ScoutResponseType = 'json'>(
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<
    ApiClientResponse<ScoutResponseBody<TResponseType, GetAssetCriticalityStatusResponse>>
  > {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/internal/asset_criticality/status`;

    return apiClient.get<ScoutResponseBody<TResponseType, GetAssetCriticalityStatusResponse>>(
      path,
      {
        headers: {
          'kbn-xsrf': 'true',
          [ELASTIC_HTTP_VERSION_HEADER]: '1',
          [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
          ...options.headers,
        },
        body: options.body,
        responseType: options.responseType ?? 'json',
      }
    );
  },
  /**
   * Get the engine descriptor for a specific entity type, including its configuration and current status.
   */
  async getEntityEngine<TResponseType extends ScoutResponseType = 'json'>(
    props: GetEntityEngineProps,
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<ApiClientResponse<ScoutResponseBody<TResponseType, GetEntityEngineResponse>>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}${replaceParams(
      '/api/entity_store/engines/{entityType}',
      encodePathParams(props.params)
    )}`;

    return apiClient.get<ScoutResponseBody<TResponseType, GetEntityEngineResponse>>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      body: options.body,
      responseType: options.responseType ?? 'json',
    });
  },
  /**
   * Get the overall Entity Store status and per-engine statuses, optionally including component-level health details.
   */
  async getEntityStoreStatus<TResponseType extends ScoutResponseType = 'json'>(
    props: GetEntityStoreStatusProps,
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<ApiClientResponse<ScoutResponseBody<TResponseType, GetEntityStoreStatusResponse>>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/api/entity_store/status`;

    return apiClient.get<ScoutResponseBody<TResponseType, GetEntityStoreStatusResponse>>(
      `${path}?${stringifyQuery(props.query, { arrayFormat: 'none' })}`,
      {
        headers: {
          'kbn-xsrf': 'true',
          [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
          [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
          ...options.headers,
        },
        body: options.body,
        responseType: options.responseType ?? 'json',
      }
    );
  },
  /**
   * Returns the status of both the legacy transform-based risk engine, as well as the new risk engine
   */
  async getRiskEngineStatus<TResponseType extends ScoutResponseType = 'json'>(
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<ApiClientResponse<ScoutResponseBody<TResponseType, GetRiskEngineStatusResponse>>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/internal/risk_score/engine/status`;

    return apiClient.get<ScoutResponseBody<TResponseType, GetRiskEngineStatusResponse>>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '1',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      body: options.body,
      responseType: options.responseType ?? 'json',
    });
  },
  /**
   * Initialize a single entity engine for the specified entity type.
   */
  async initEntityEngine<TResponseType extends ScoutResponseType = 'json'>(
    props: InitEntityEngineProps,
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<ApiClientResponse<ScoutResponseBody<TResponseType, InitEntityEngineResponse>>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}${replaceParams(
      '/api/entity_store/engines/{entityType}/init',
      encodePathParams(props.params)
    )}`;

    return apiClient.post<ScoutResponseBody<TResponseType, InitEntityEngineResponse>>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      body: props.body,
      responseType: options.responseType ?? 'json',
    });
  },
  /**
   * Initialize the entire Entity Store, creating engines for all or specified entity types.
   */
  async initEntityStore<TResponseType extends ScoutResponseType = 'json'>(
    props: InitEntityStoreProps,
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<ApiClientResponse<ScoutResponseBody<TResponseType, InitEntityStoreResponse>>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/api/entity_store/enable`;

    return apiClient.post<ScoutResponseBody<TResponseType, InitEntityStoreResponse>>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      body: props.body,
      responseType: options.responseType ?? 'json',
    });
  },
  /**
   * Initializes the Risk Engine by creating the necessary indices and mappings, removing old transforms, and starting the new risk engine
   */
  async initRiskEngine<TResponseType extends ScoutResponseType = 'json'>(
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<ApiClientResponse<ScoutResponseBody<TResponseType, InitRiskEngineResponse>>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/internal/risk_score/engine/init`;

    return apiClient.post<ScoutResponseBody<TResponseType, InitRiskEngineResponse>>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '1',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      body: options.body,
      responseType: options.responseType ?? 'json',
    });
  },
  async internalUploadAssetCriticalityRecords<TResponseType extends ScoutResponseType = 'json'>(
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<
    ApiClientResponse<
      ScoutResponseBody<TResponseType, InternalUploadAssetCriticalityRecordsResponse>
    >
  > {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/internal/asset_criticality/upload_csv`;

    return apiClient.post<
      ScoutResponseBody<TResponseType, InternalUploadAssetCriticalityRecordsResponse>
    >(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '1',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      body: options.body,
      responseType: options.responseType ?? 'json',
    });
  },
  /**
   * List entities records, paging, sorting and filtering as needed.
   */
  async listEntities<TResponseType extends ScoutResponseType = 'json'>(
    props: ListEntitiesProps,
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<ApiClientResponse<ScoutResponseBody<TResponseType, ListEntitiesResponse>>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/api/entity_store/entities/list`;

    return apiClient.get<ScoutResponseBody<TResponseType, ListEntitiesResponse>>(
      `${path}?${stringifyQuery(props.query, { arrayFormat: 'none' })}`,
      {
        headers: {
          'kbn-xsrf': 'true',
          [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
          [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
          ...options.headers,
        },
        body: options.body,
        responseType: options.responseType ?? 'json',
      }
    );
  },
  /**
   * Get a list of all installed entity engines and their current status.
   */
  async listEntityEngines<TResponseType extends ScoutResponseType = 'json'>(
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<ApiClientResponse<ScoutResponseBody<TResponseType, ListEntityEnginesResponse>>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/api/entity_store/engines`;

    return apiClient.get<ScoutResponseBody<TResponseType, ListEntityEnginesResponse>>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      body: options.body,
      responseType: options.responseType ?? 'json',
    });
  },
  /**
   * Calculates and returns a list of Risk Scores, sorted by identifier_type and risk score.
   */
  async previewRiskScore<TResponseType extends ScoutResponseType = 'json'>(
    props: PreviewRiskScoreProps,
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<ApiClientResponse<ScoutResponseBody<TResponseType, PreviewRiskScoreResponse>>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/internal/risk_score/preview`;

    return apiClient.post<ScoutResponseBody<TResponseType, PreviewRiskScoreResponse>>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '1',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      body: props.body,
      responseType: options.responseType ?? 'json',
    });
  },
  async readRiskEngineSettings<TResponseType extends ScoutResponseType = 'json'>(
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<ApiClientResponse<ScoutResponseBody<TResponseType, ReadRiskEngineSettingsResponse>>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/internal/risk_score/engine/settings`;

    return apiClient.get<ScoutResponseBody<TResponseType, ReadRiskEngineSettingsResponse>>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '1',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      body: options.body,
      responseType: options.responseType ?? 'json',
    });
  },
  async riskEngineGetPrivileges<TResponseType extends ScoutResponseType = 'json'>(
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<ApiClientResponse<ScoutResponseBody<TResponseType, RiskEngineGetPrivilegesResponse>>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/internal/risk_engine/privileges`;

    return apiClient.get<ScoutResponseBody<TResponseType, RiskEngineGetPrivilegesResponse>>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '1',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      body: options.body,
      responseType: options.responseType ?? 'json',
    });
  },
  async runEntityAnalyticsMigrations<TResponseType extends ScoutResponseType = 'json'>(
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<
    ApiClientResponse<ScoutResponseBody<TResponseType, RunEntityAnalyticsMigrationsResponse>>
  > {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/internal/entity_analytics/migrations/run`;

    return apiClient.post<ScoutResponseBody<TResponseType, RunEntityAnalyticsMigrationsResponse>>(
      path,
      {
        headers: {
          'kbn-xsrf': 'true',
          [ELASTIC_HTTP_VERSION_HEADER]: '1',
          [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
          ...options.headers,
        },
        body: options.body,
        responseType: options.responseType ?? 'json',
      }
    );
  },
  /**
   * Schedule the risk scoring engine to run as soon as possible. You can use this to recalculate entity risk scores after updating their asset criticality.
   */
  async scheduleRiskEngineNow<TResponseType extends ScoutResponseType = 'json'>(
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<ApiClientResponse<ScoutResponseBody<TResponseType, ScheduleRiskEngineNowResponse>>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/api/risk_score/engine/schedule_now`;

    return apiClient.post<ScoutResponseBody<TResponseType, ScheduleRiskEngineNowResponse>>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      body: options.body,
      responseType: options.responseType ?? 'json',
    });
  },
  /**
   * Start a previously stopped entity engine, resuming transform processing for the given entity type.
   */
  async startEntityEngine<TResponseType extends ScoutResponseType = 'json'>(
    props: StartEntityEngineProps,
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<ApiClientResponse<ScoutResponseBody<TResponseType, StartEntityEngineResponse>>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}${replaceParams(
      '/api/entity_store/engines/{entityType}/start',
      encodePathParams(props.params)
    )}`;

    return apiClient.post<ScoutResponseBody<TResponseType, StartEntityEngineResponse>>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      body: options.body,
      responseType: options.responseType ?? 'json',
    });
  },
  /**
   * Stop a running entity engine, pausing transform processing for the given entity type.
   */
  async stopEntityEngine<TResponseType extends ScoutResponseType = 'json'>(
    props: StopEntityEngineProps,
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<ApiClientResponse<ScoutResponseBody<TResponseType, StopEntityEngineResponse>>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}${replaceParams(
      '/api/entity_store/engines/{entityType}/stop',
      encodePathParams(props.params)
    )}`;

    return apiClient.post<ScoutResponseBody<TResponseType, StopEntityEngineResponse>>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      body: options.body,
      responseType: options.responseType ?? 'json',
    });
  },
  /**
   * Calculates and persists Risk Scores for an entity, returning the calculated risk score.
   */
  async triggerRiskScoreCalculation<TResponseType extends ScoutResponseType = 'json'>(
    props: TriggerRiskScoreCalculationProps,
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<
    ApiClientResponse<ScoutResponseBody<TResponseType, TriggerRiskScoreCalculationResponse>>
  > {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/internal/risk_score/calculation/entity`;

    return apiClient.post<ScoutResponseBody<TResponseType, TriggerRiskScoreCalculationResponse>>(
      path,
      {
        headers: {
          'kbn-xsrf': 'true',
          [ELASTIC_HTTP_VERSION_HEADER]: '1',
          [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
          ...options.headers,
        },
        body: props.body,
        responseType: options.responseType ?? 'json',
      }
    );
  },
  async uploadAssetCriticalityRecords<TResponseType extends ScoutResponseType = 'json'>(
    options: ScoutApiRequestOptions<TResponseType> = {}
  ): Promise<
    ApiClientResponse<ScoutResponseBody<TResponseType, UploadAssetCriticalityRecordsResponse>>
  > {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/api/asset_criticality/upload_csv`;

    return apiClient.post<ScoutResponseBody<TResponseType, UploadAssetCriticalityRecordsResponse>>(
      path,
      {
        headers: {
          'kbn-xsrf': 'true',
          [ELASTIC_HTTP_VERSION_HEADER]: '1',
          [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
          ...options.headers,
        },
        body: options.body,
        responseType: options.responseType ?? 'json',
      }
    );
  },
});

export function SecuritySolutionScoutApiServiceProvider(apiClient: ApiClientFixture) {
  return securitySolutionScoutApiServiceFactory(apiClient);
}

export interface BulkUpsertAssetCriticalityRecordsProps {
  body: BulkUpsertAssetCriticalityRecordsRequestBodyInput;
}
export interface ConfigureRiskEngineSavedObjectProps {
  body: ConfigureRiskEngineSavedObjectRequestBodyInput;
}
export interface CreateAssetCriticalityRecordProps {
  body: CreateAssetCriticalityRecordRequestBodyInput;
}
export interface DeleteAssetCriticalityRecordProps {
  query: DeleteAssetCriticalityRecordRequestQueryInput;
}
export interface DeleteEntityEngineProps {
  query: DeleteEntityEngineRequestQueryInput;
  params: DeleteEntityEngineRequestParamsInput;
}
export interface DeprecatedTriggerRiskScoreCalculationProps {
  body: DeprecatedTriggerRiskScoreCalculationRequestBodyInput;
}
export interface FindAssetCriticalityRecordsProps {
  query: FindAssetCriticalityRecordsRequestQueryInput;
}
export interface GetAssetCriticalityRecordProps {
  query: GetAssetCriticalityRecordRequestQueryInput;
}
export interface GetEntityEngineProps {
  params: GetEntityEngineRequestParamsInput;
}
export interface GetEntityStoreStatusProps {
  query: GetEntityStoreStatusRequestQueryInput;
}
export interface InitEntityEngineProps {
  params: InitEntityEngineRequestParamsInput;
  body: InitEntityEngineRequestBodyInput;
}
export interface InitEntityStoreProps {
  body: InitEntityStoreRequestBodyInput;
}
export interface ListEntitiesProps {
  query: ListEntitiesRequestQueryInput;
}
export interface PreviewRiskScoreProps {
  body: PreviewRiskScoreRequestBodyInput;
}
export interface StartEntityEngineProps {
  params: StartEntityEngineRequestParamsInput;
}
export interface StopEntityEngineProps {
  params: StopEntityEngineRequestParamsInput;
}
export interface TriggerRiskScoreCalculationProps {
  body: TriggerRiskScoreCalculationRequestBodyInput;
}
