/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: API client for Scout tests
 *   version: Bundle (no version)
 */

import type { ApiClientFixture, ApiClientResponse } from '@kbn/scout';
import {
  ELASTIC_HTTP_VERSION_HEADER,
  X_ELASTIC_INTERNAL_ORIGIN_REQUEST,
} from '@kbn/core-http-common';
import { replaceParams } from '@kbn/openapi-common/shared';
import { stringify as stringifyQuery } from 'query-string';

import type {
  GetAgentDetailsRequestParamsInput,
  GetAgentDetailsResponse,
  GetAgentPackagePoliciesResponse,
  GetAgentPoliciesResponse,
  GetAgentPolicyRequestParamsInput,
  GetAgentPolicyResponse,
  GetAgentsRequestQueryInput,
  GetAgentsResponse,
} from '@kbn/osquery-plugin/common/api/fleet_wrapper/fleet_wrapper.gen';
import type {
  OsqueryCopyPacksRequestParamsInput,
  OsqueryCopyPacksResponse,
  OsqueryCreatePacksRequestBodyInput,
  OsqueryCreatePacksResponse,
  OsqueryDeletePacksRequestParamsInput,
  OsqueryDeletePacksResponse,
  OsqueryFindPacksRequestQueryInput,
  OsqueryFindPacksResponse,
  OsqueryGetPacksDetailsRequestParamsInput,
  OsqueryGetPacksDetailsResponse,
  OsqueryUpdatePacksRequestParamsInput,
  OsqueryUpdatePacksRequestBodyInput,
  OsqueryUpdatePacksResponse,
} from '@kbn/osquery-plugin/common/api/packs/packs.gen';
import type {
  OsqueryCopySavedQueryRequestParamsInput,
  OsqueryCopySavedQueryResponse,
  OsqueryCreateSavedQueryRequestBodyInput,
  OsqueryCreateSavedQueryResponse,
  OsqueryDeleteSavedQueryRequestParamsInput,
  OsqueryDeleteSavedQueryResponse,
  OsqueryFindSavedQueriesRequestQueryInput,
  OsqueryFindSavedQueriesResponse,
  OsqueryGetSavedQueryDetailsRequestParamsInput,
  OsqueryGetSavedQueryDetailsResponse,
  OsqueryUpdateSavedQueryRequestParamsInput,
  OsqueryUpdateSavedQueryRequestBodyInput,
  OsqueryUpdateSavedQueryResponse,
} from '@kbn/osquery-plugin/common/api/saved_query/saved_query.gen';
import type {
  OsqueryCreateLiveQueryRequestBodyInput,
  OsqueryCreateLiveQueryResponse,
  OsqueryExportLiveQueryResultsRequestQueryInput,
  OsqueryExportLiveQueryResultsRequestParamsInput,
  OsqueryExportLiveQueryResultsRequestBodyInput,
  OsqueryExportLiveQueryResultsResponse,
  OsqueryFindLiveQueriesRequestQueryInput,
  OsqueryFindLiveQueriesResponse,
  OsqueryGetLiveQueryDetailsRequestParamsInput,
  OsqueryGetLiveQueryDetailsResponse,
  OsqueryGetLiveQueryResultsRequestQueryInput,
  OsqueryGetLiveQueryResultsRequestParamsInput,
  OsqueryGetLiveQueryResultsResponse,
} from '@kbn/osquery-plugin/common/api/live_query/live_queries.gen';
import type {
  OsqueryExportScheduledQueryResultsRequestQueryInput,
  OsqueryExportScheduledQueryResultsRequestParamsInput,
  OsqueryExportScheduledQueryResultsRequestBodyInput,
  OsqueryExportScheduledQueryResultsResponse,
  OsqueryGetScheduledActionResultsRequestQueryInput,
  OsqueryGetScheduledActionResultsRequestParamsInput,
  OsqueryGetScheduledActionResultsResponse,
  OsqueryGetScheduledQueryResultsRequestQueryInput,
  OsqueryGetScheduledQueryResultsRequestParamsInput,
  OsqueryGetScheduledQueryResultsResponse,
} from '@kbn/osquery-plugin/common/api/scheduled_results/scheduled_results.gen';
import type {
  OsqueryGetUnifiedHistoryRequestQueryInput,
  OsqueryGetUnifiedHistoryResponse,
} from '@kbn/osquery-plugin/common/api/unified_history/unified_history.gen';
import type {
  ReadAssetsStatusRequestQueryInput,
  ReadAssetsStatusResponse,
  UpdateAssetsStatusRequestQueryInput,
  UpdateAssetsStatusResponse,
} from '@kbn/osquery-plugin/common/api/asset/assets.gen';
import type { ReadInstallationStatusResponse } from '@kbn/osquery-plugin/common/api/status/status.gen';
import type { ReadPrivilegesCheckResponse } from '@kbn/osquery-plugin/common/api/status/privileges_check.gen';

export interface ScoutApiRequestOptions {
  /** Extra headers merged on top of the defaults, e.g. an API key or a SAML cookie for auth */
  headers?: Record<string, string>;
  /** Kibana space id the request targets. Omit or pass 'default' for the default space */
  kibanaSpace?: string;
}

const securitySolutionScoutApiServiceFactory = (apiClient: ApiClientFixture) => ({
  async getAgentDetails(
    props: GetAgentDetailsProps,
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<GetAgentDetailsResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}${replaceParams(
      '/internal/osquery/fleet_wrapper/agents/{id}',
      props.params
    )}`;

    return apiClient.get<GetAgentDetailsResponse>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '1',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      responseType: 'json',
    });
  },
  async getAgentPackagePolicies(
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<GetAgentPackagePoliciesResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/internal/osquery/fleet_wrapper/package_policies`;

    return apiClient.get<GetAgentPackagePoliciesResponse>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '1',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      responseType: 'json',
    });
  },
  async getAgentPolicies(
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<GetAgentPoliciesResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/internal/osquery/fleet_wrapper/agent_policies`;

    return apiClient.get<GetAgentPoliciesResponse>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '1',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      responseType: 'json',
    });
  },
  async getAgentPolicy(
    props: GetAgentPolicyProps,
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<GetAgentPolicyResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}${replaceParams(
      '/internal/osquery/fleet_wrapper/agent_policies/{id}',
      props.params
    )}`;

    return apiClient.get<GetAgentPolicyResponse>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '1',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      responseType: 'json',
    });
  },
  async getAgents(
    props: GetAgentsProps,
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<GetAgentsResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/internal/osquery/fleet_wrapper/agents`;

    return apiClient.get<GetAgentsResponse>(
      `${path}?${stringifyQuery(props.query, { arrayFormat: 'comma' })}`,
      {
        headers: {
          'kbn-xsrf': 'true',
          [ELASTIC_HTTP_VERSION_HEADER]: '1',
          [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
          ...options.headers,
        },
        responseType: 'json',
      }
    );
  },
  /**
   * Create a copy of a query pack with a unique name by appending a `_copy` suffix. If the name already exists, a numeric suffix is added (e.g., `_copy_2`). The copied pack is always created with `enabled` set to `false`.
   */
  async osqueryCopyPacks(
    props: OsqueryCopyPacksProps,
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<OsqueryCopyPacksResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}${replaceParams('/api/osquery/packs/{id}/copy', props.params)}`;

    return apiClient.post<OsqueryCopyPacksResponse>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      responseType: 'json',
    });
  },
  /**
   * Create a copy of a saved query with a unique name by appending a `_copy` suffix. If the name already exists, a numeric suffix is added (e.g., `_copy_2`).
   */
  async osqueryCopySavedQuery(
    props: OsqueryCopySavedQueryProps,
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<OsqueryCopySavedQueryResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}${replaceParams(
      '/api/osquery/saved_queries/{id}/copy',
      props.params
    )}`;

    return apiClient.post<OsqueryCopySavedQueryResponse>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      responseType: 'json',
    });
  },
  /**
   * Create and run a live query.
   */
  async osqueryCreateLiveQuery(
    props: OsqueryCreateLiveQueryProps,
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<OsqueryCreateLiveQueryResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/api/osquery/live_queries`;

    return apiClient.post<OsqueryCreateLiveQueryResponse>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      body: props.body,
      responseType: 'json',
    });
  },
  /**
   * Create a query pack.
   */
  async osqueryCreatePacks(
    props: OsqueryCreatePacksProps,
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<OsqueryCreatePacksResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/api/osquery/packs`;

    return apiClient.post<OsqueryCreatePacksResponse>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      body: props.body,
      responseType: 'json',
    });
  },
  /**
   * Create and save a query for later use.
   */
  async osqueryCreateSavedQuery(
    props: OsqueryCreateSavedQueryProps,
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<OsqueryCreateSavedQueryResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/api/osquery/saved_queries`;

    return apiClient.post<OsqueryCreateSavedQueryResponse>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      body: props.body,
      responseType: 'json',
    });
  },
  /**
   * Delete a query pack using the pack ID.
   */
  async osqueryDeletePacks(
    props: OsqueryDeletePacksProps,
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<OsqueryDeletePacksResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}${replaceParams('/api/osquery/packs/{id}', props.params)}`;

    return apiClient.delete<OsqueryDeletePacksResponse>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      responseType: 'json',
    });
  },
  /**
   * Delete a saved query using the query ID.
   */
  async osqueryDeleteSavedQuery(
    props: OsqueryDeleteSavedQueryProps,
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<OsqueryDeleteSavedQueryResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}${replaceParams('/api/osquery/saved_queries/{id}', props.params)}`;

    return apiClient.delete<OsqueryDeleteSavedQueryResponse>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      responseType: 'json',
    });
  },
  /**
      * Export the results of a live query action as a downloadable file. The response is a streaming file attachment in the requested format.

      */
  async osqueryExportLiveQueryResults(
    props: OsqueryExportLiveQueryResultsProps,
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<OsqueryExportLiveQueryResultsResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}${replaceParams(
      '/api/osquery/live_queries/{id}/results/{actionId}/_export',
      props.params
    )}`;

    return apiClient.post<OsqueryExportLiveQueryResultsResponse>(
      `${path}?${stringifyQuery(props.query, { arrayFormat: 'comma' })}`,
      {
        headers: {
          'kbn-xsrf': 'true',
          [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
          [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
          ...options.headers,
        },
        body: props.body,
        responseType: 'json',
      }
    );
  },
  /**
      * Export all result rows for a specific scheduled query execution as a downloadable file. The response is a streaming file attachment in the requested format.

      */
  async osqueryExportScheduledQueryResults(
    props: OsqueryExportScheduledQueryResultsProps,
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<OsqueryExportScheduledQueryResultsResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}${replaceParams(
      '/api/osquery/scheduled_results/{scheduleId}/{executionCount}/_export',
      props.params
    )}`;

    return apiClient.post<OsqueryExportScheduledQueryResultsResponse>(
      `${path}?${stringifyQuery(props.query, { arrayFormat: 'comma' })}`,
      {
        headers: {
          'kbn-xsrf': 'true',
          [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
          [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
          ...options.headers,
        },
        body: props.body,
        responseType: 'json',
      }
    );
  },
  /**
   * Get a list of all live queries.
   */
  async osqueryFindLiveQueries(
    props: OsqueryFindLiveQueriesProps,
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<OsqueryFindLiveQueriesResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/api/osquery/live_queries`;

    return apiClient.get<OsqueryFindLiveQueriesResponse>(
      `${path}?${stringifyQuery(props.query, { arrayFormat: 'comma' })}`,
      {
        headers: {
          'kbn-xsrf': 'true',
          [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
          [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
          ...options.headers,
        },
        responseType: 'json',
      }
    );
  },
  /**
   * Get a list of all query packs.
   */
  async osqueryFindPacks(
    props: OsqueryFindPacksProps,
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<OsqueryFindPacksResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/api/osquery/packs`;

    return apiClient.get<OsqueryFindPacksResponse>(
      `${path}?${stringifyQuery(props.query, { arrayFormat: 'comma' })}`,
      {
        headers: {
          'kbn-xsrf': 'true',
          [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
          [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
          ...options.headers,
        },
        responseType: 'json',
      }
    );
  },
  /**
   * Get a list of all saved queries.
   */
  async osqueryFindSavedQueries(
    props: OsqueryFindSavedQueriesProps,
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<OsqueryFindSavedQueriesResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/api/osquery/saved_queries`;

    return apiClient.get<OsqueryFindSavedQueriesResponse>(
      `${path}?${stringifyQuery(props.query, { arrayFormat: 'comma' })}`,
      {
        headers: {
          'kbn-xsrf': 'true',
          [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
          [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
          ...options.headers,
        },
        responseType: 'json',
      }
    );
  },
  /**
   * Get the details of a live query using the query ID.
   */
  async osqueryGetLiveQueryDetails(
    props: OsqueryGetLiveQueryDetailsProps,
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<OsqueryGetLiveQueryDetailsResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}${replaceParams('/api/osquery/live_queries/{id}', props.params)}`;

    return apiClient.get<OsqueryGetLiveQueryDetailsResponse>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      responseType: 'json',
    });
  },
  /**
   * Get the results of a live query using the query action ID.
   */
  async osqueryGetLiveQueryResults(
    props: OsqueryGetLiveQueryResultsProps,
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<OsqueryGetLiveQueryResultsResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}${replaceParams(
      '/api/osquery/live_queries/{id}/results/{actionId}',
      props.params
    )}`;

    return apiClient.get<OsqueryGetLiveQueryResultsResponse>(
      `${path}?${stringifyQuery(props.query, { arrayFormat: 'comma' })}`,
      {
        headers: {
          'kbn-xsrf': 'true',
          [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
          [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
          ...options.headers,
        },
        responseType: 'json',
      }
    );
  },
  /**
   * Get the details of a query pack using the pack ID.
   */
  async osqueryGetPacksDetails(
    props: OsqueryGetPacksDetailsProps,
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<OsqueryGetPacksDetailsResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}${replaceParams('/api/osquery/packs/{id}', props.params)}`;

    return apiClient.get<OsqueryGetPacksDetailsResponse>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      responseType: 'json',
    });
  },
  /**
   * Get the details of a saved query using the query ID.
   */
  async osqueryGetSavedQueryDetails(
    props: OsqueryGetSavedQueryDetailsProps,
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<OsqueryGetSavedQueryDetailsResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}${replaceParams('/api/osquery/saved_queries/{id}', props.params)}`;

    return apiClient.get<OsqueryGetSavedQueryDetailsResponse>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      responseType: 'json',
    });
  },
  /**
      * Get paginated per-agent action results for a specific scheduled query execution, with success/failure aggregation and execution metadata (pack name, query name/text, timestamp).

      */
  async osqueryGetScheduledActionResults(
    props: OsqueryGetScheduledActionResultsProps,
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<OsqueryGetScheduledActionResultsResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}${replaceParams(
      '/api/osquery/scheduled_results/{scheduleId}/{executionCount}',
      props.params
    )}`;

    return apiClient.get<OsqueryGetScheduledActionResultsResponse>(
      `${path}?${stringifyQuery(props.query, { arrayFormat: 'comma' })}`,
      {
        headers: {
          'kbn-xsrf': 'true',
          [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
          [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
          ...options.headers,
        },
        responseType: 'json',
      }
    );
  },
  /**
      * Get paginated query result rows (the actual osquery output data) for a specific scheduled query execution.

      */
  async osqueryGetScheduledQueryResults(
    props: OsqueryGetScheduledQueryResultsProps,
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<OsqueryGetScheduledQueryResultsResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}${replaceParams(
      '/api/osquery/scheduled_results/{scheduleId}/{executionCount}/results',
      props.params
    )}`;

    return apiClient.get<OsqueryGetScheduledQueryResultsResponse>(
      `${path}?${stringifyQuery(props.query, { arrayFormat: 'comma' })}`,
      {
        headers: {
          'kbn-xsrf': 'true',
          [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
          [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
          ...options.headers,
        },
        responseType: 'json',
      }
    );
  },
  /**
      * Get a unified, time-sorted history of live, rule-triggered, and scheduled osquery executions. The response uses cursor-based pagination.

      */
  async osqueryGetUnifiedHistory(
    props: OsqueryGetUnifiedHistoryProps,
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<OsqueryGetUnifiedHistoryResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/api/osquery/history`;

    return apiClient.get<OsqueryGetUnifiedHistoryResponse>(
      `${path}?${stringifyQuery(props.query, { arrayFormat: 'comma' })}`,
      {
        headers: {
          'kbn-xsrf': 'true',
          [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
          [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
          ...options.headers,
        },
        responseType: 'json',
      }
    );
  },
  /**
      * Update a query pack using the pack ID.
> info
> You cannot update a prebuilt pack.

      */
  async osqueryUpdatePacks(
    props: OsqueryUpdatePacksProps,
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<OsqueryUpdatePacksResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}${replaceParams('/api/osquery/packs/{id}', props.params)}`;

    return apiClient.put<OsqueryUpdatePacksResponse>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      body: props.body,
      responseType: 'json',
    });
  },
  /**
      * Update a saved query using the query ID.
> info
> You cannot update a prebuilt saved query.

      */
  async osqueryUpdateSavedQuery(
    props: OsqueryUpdateSavedQueryProps,
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<OsqueryUpdateSavedQueryResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}${replaceParams('/api/osquery/saved_queries/{id}', props.params)}`;

    return apiClient.put<OsqueryUpdateSavedQueryResponse>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '2023-10-31',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      body: props.body,
      responseType: 'json',
    });
  },
  async readAssetsStatus(
    props: ReadAssetsStatusProps,
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<ReadAssetsStatusResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/internal/osquery/assets`;

    return apiClient.get<ReadAssetsStatusResponse>(
      `${path}?${stringifyQuery(props.query, { arrayFormat: 'comma' })}`,
      {
        headers: {
          'kbn-xsrf': 'true',
          [ELASTIC_HTTP_VERSION_HEADER]: '1',
          [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
          ...options.headers,
        },
        responseType: 'json',
      }
    );
  },
  async readInstallationStatus(
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<ReadInstallationStatusResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/internal/osquery/status`;

    return apiClient.get<ReadInstallationStatusResponse>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '1',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      responseType: 'json',
    });
  },
  async readPrivilegesCheck(
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<ReadPrivilegesCheckResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/internal/osquery/privileges_check`;

    return apiClient.get<ReadPrivilegesCheckResponse>(path, {
      headers: {
        'kbn-xsrf': 'true',
        [ELASTIC_HTTP_VERSION_HEADER]: '1',
        [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
        ...options.headers,
      },
      responseType: 'json',
    });
  },
  async updateAssetsStatus(
    props: UpdateAssetsStatusProps,
    options: ScoutApiRequestOptions = {}
  ): Promise<ApiClientResponse<UpdateAssetsStatusResponse>> {
    const basePath =
      options.kibanaSpace && options.kibanaSpace !== 'default' ? `/s/${options.kibanaSpace}` : '';
    const path = `${basePath}/internal/osquery/assets/update`;

    return apiClient.post<UpdateAssetsStatusResponse>(
      `${path}?${stringifyQuery(props.query, { arrayFormat: 'comma' })}`,
      {
        headers: {
          'kbn-xsrf': 'true',
          [ELASTIC_HTTP_VERSION_HEADER]: '1',
          [X_ELASTIC_INTERNAL_ORIGIN_REQUEST]: 'kibana',
          ...options.headers,
        },
        responseType: 'json',
      }
    );
  },
});

export function SecuritySolutionScoutApiServiceProvider(apiClient: ApiClientFixture) {
  return securitySolutionScoutApiServiceFactory(apiClient);
}

export interface GetAgentDetailsProps {
  params: GetAgentDetailsRequestParamsInput;
}
export interface GetAgentPolicyProps {
  params: GetAgentPolicyRequestParamsInput;
}
export interface GetAgentsProps {
  query: GetAgentsRequestQueryInput;
}
export interface OsqueryCopyPacksProps {
  params: OsqueryCopyPacksRequestParamsInput;
}
export interface OsqueryCopySavedQueryProps {
  params: OsqueryCopySavedQueryRequestParamsInput;
}
export interface OsqueryCreateLiveQueryProps {
  body: OsqueryCreateLiveQueryRequestBodyInput;
}
export interface OsqueryCreatePacksProps {
  body: OsqueryCreatePacksRequestBodyInput;
}
export interface OsqueryCreateSavedQueryProps {
  body: OsqueryCreateSavedQueryRequestBodyInput;
}
export interface OsqueryDeletePacksProps {
  params: OsqueryDeletePacksRequestParamsInput;
}
export interface OsqueryDeleteSavedQueryProps {
  params: OsqueryDeleteSavedQueryRequestParamsInput;
}
export interface OsqueryExportLiveQueryResultsProps {
  query: OsqueryExportLiveQueryResultsRequestQueryInput;
  params: OsqueryExportLiveQueryResultsRequestParamsInput;
  body: OsqueryExportLiveQueryResultsRequestBodyInput;
}
export interface OsqueryExportScheduledQueryResultsProps {
  query: OsqueryExportScheduledQueryResultsRequestQueryInput;
  params: OsqueryExportScheduledQueryResultsRequestParamsInput;
  body: OsqueryExportScheduledQueryResultsRequestBodyInput;
}
export interface OsqueryFindLiveQueriesProps {
  query: OsqueryFindLiveQueriesRequestQueryInput;
}
export interface OsqueryFindPacksProps {
  query: OsqueryFindPacksRequestQueryInput;
}
export interface OsqueryFindSavedQueriesProps {
  query: OsqueryFindSavedQueriesRequestQueryInput;
}
export interface OsqueryGetLiveQueryDetailsProps {
  params: OsqueryGetLiveQueryDetailsRequestParamsInput;
}
export interface OsqueryGetLiveQueryResultsProps {
  query: OsqueryGetLiveQueryResultsRequestQueryInput;
  params: OsqueryGetLiveQueryResultsRequestParamsInput;
}
export interface OsqueryGetPacksDetailsProps {
  params: OsqueryGetPacksDetailsRequestParamsInput;
}
export interface OsqueryGetSavedQueryDetailsProps {
  params: OsqueryGetSavedQueryDetailsRequestParamsInput;
}
export interface OsqueryGetScheduledActionResultsProps {
  query: OsqueryGetScheduledActionResultsRequestQueryInput;
  params: OsqueryGetScheduledActionResultsRequestParamsInput;
}
export interface OsqueryGetScheduledQueryResultsProps {
  query: OsqueryGetScheduledQueryResultsRequestQueryInput;
  params: OsqueryGetScheduledQueryResultsRequestParamsInput;
}
export interface OsqueryGetUnifiedHistoryProps {
  query: OsqueryGetUnifiedHistoryRequestQueryInput;
}
export interface OsqueryUpdatePacksProps {
  params: OsqueryUpdatePacksRequestParamsInput;
  body: OsqueryUpdatePacksRequestBodyInput;
}
export interface OsqueryUpdateSavedQueryProps {
  params: OsqueryUpdateSavedQueryRequestParamsInput;
  body: OsqueryUpdateSavedQueryRequestBodyInput;
}
export interface ReadAssetsStatusProps {
  query: ReadAssetsStatusRequestQueryInput;
}
export interface UpdateAssetsStatusProps {
  query: UpdateAssetsStatusRequestQueryInput;
}
