[[release-notes-6.0.0]]
== 6.0.0 Release Notes

Also see <<breaking-changes-6.0>>.

[float]
[[enhancement-6.0.0]]
=== Enhancements
Core::
* Remove legacy pre-4.2 configurations {pull}12013[#12013]
* NODE_ENV no longer has an impact on Kibana {pull}12010[#12010]
* Only support 64 bit operating systems {pull}11941[#11941]
* Remove field_stats pre-flight option for index patterns {pull}12814[#12814]
* [Fixes #13439] Upgrade Angular to 1.6.5 {pull}13543[#13543]
Design::
* Palette swap for accessibility / kibana 6 {pull}12085[#12085]
  - We re-skinned a decent portion of Kibana to be mostly AA accessibility compatible in regards to coloring of major navigation elements.
* [UI Framework] Reactify menu {pull}12135[#12135]
* Adding for and id attributes to labels and form elements {pull}12215[#12215]
* [UI Framework] Reactify kuiEvent and related CSS components (#12226) {pull}12228[#12228]
* [UI Framework] Reactify actionItem {pull}12142[#12142]
* [UI Framework] Reactify kuiCollapseButton {pull}12225[#12225]
* [UI Framework] Reactify kuiFieldGroup and related CSS components {pull}12260[#12260]
* [UI Framework] Update LocalNav examples to use tabIndex instead of tabindex, to eliminate React console warnings. {pull}12284[#12284]
* [UI Framework] Reactify kuiCard and related CSS components {pull}12197[#12197]
* [UI Framework] Reactify kuiBar {pull}12167[#12167]
* [UI Framework] Reactify kuiGallery and related CSS components {pull}12277[#12277]
* [UI Framework] Fix examples of Table component with ToolBar. {pull}12326[#12326]
* [UI Framework] Improve Warning Button contrast {pull}12327[#12327]
* [UI Framework] Reactify kuiHeaderBar and related CSS components {pull}12280[#12280]
* [UI Framework] Define consistent default, small, and wide sizing for form fields, and support them within ExpressionItems. {pull}12190[#12190]
* [UI Framework] Order UI Framework React component exports to be alphabetical {pull}12526[#12526]
* [UI Framework] Reactify kuiTabs and related CSS components {pull}12302[#12302]
* Replace brand-danger color with new global red color. {pull}12654[#12654]
* Make ui-select appearance match other inputs. {pull}12652[#12652]
* [UI Framework] remove check for ng-untouched class from formControlInvalid mixin {pull}12153[#12153]
* [UI Framework] reactify prompt for items {pull}12151[#12151]
* [UI Framework] Allow custom placeholder for Tool Bar Search Box {pull}12959[#12959]
* [UI Framework] Add new react color picker to ui framework with tests {pull}12245[#12245]
Discover::
* Implement new Kibana query language {pull}12624[#12624]
  - This PR adds a new experimental query language to Kibana. The new language is turned off by default but can be enabled in the Management > Advanced Settings via the search:queryLanguage:switcher:enable option. Changing this setting to true will add a language selector to the query bar that allows users to choose the new language for their query. Details of the new query language can be found in the issue description (#12282).
* Remove highlight query {pull}13231[#13231]
* [Fixes #12635]  Improve the accessibility of the Discover screen {pull}12681[#12681]
* [Fixes #12343] Remove custom keyboard navigation in datepicker {pull}13644[#13644]
* Accessible sort buttons {pull}12217[#12217]
* [Accessibility] Avoid empty th in doc-table header row {pull}12364[#12364]
  - The discover document table header cells provide appropriate hints to screen-readers.
* [Accessibility] Add button to skip past the discover doc table {pull}12539[#12539]
  - The new "Skip to bottom"-button in Discover is invisible unless focused. When activated it displays all remaining rows that were already loaded and focuses an anchor located below the table.
* Timepicker on the right {pull}11980[#11980]
Management::
* [indexPatterns] remove support for time patterns {pull}12158[#12158]
  - Removes ability to create index patterns based on time patterns/intervals  - Adds a warning that informs users when they are using an index pattern that is now unsupported (disabled by default until #10442 is done, #12322)  - Does not address editing/remapping index patterns, see last task in #12242
* [Fix for #11526, #8225] Move build info from management section to status page {pull}13341[#13341]
* [Management] Provide a way to fetch indices and template index patterns {pull}12200[#12200]
* [Management] More universal solution for fetching indices and aliases {pull}12405[#12405]
* Add breadcrumb-page-title to management-app {pull}12765[#12765]
  - The bread-crumbs component allows for the consumer to pass in a page-title value which is appended as the final breadcrumb in the chain. This PR adds a scope argument to the management-app to take advantage of it.
Operations::
* Updates to status API, re-align status page {pull}10180[#10180]
* [Fix for #10181] Revert same port http -> https redirect {pull}10930[#10930]
  - Kibana 5.x redirected requests from http to https on the same port if TLS was configured. Starting in Kibana 6.0.0 Kibana no longer redirects basic http traffic to https.
* Update mappings for kibana index {pull}9280[#9280]
* Use single ES document type {pull}12794[#12794]
  - Starting in Elasticsearch 6.0, you are no longer able to create new indices with multiple index types. To accomplish the same effect as index types, a new type field was added to identify the document and the value mapped under the index to allow for strict mapping.
* [logging] Downgrade hapi connection errors when connecting with the w… {pull}11209[#11209]
* [status] 15m load average should use the 3rd index {pull}11202[#11202]
* [Fixes #9436] [optimizer] remove support for .jsx extension {pull}12712[#12712]
* Sets ES mapping to single_type=false {pull}11451[#11451]
Platform::
* [Fix for #12012] Fail to start if settings include unknown keys {pull}12554[#12554]
  - When a config file includes invalid keys or values, Kibana usually logs a message describing the issue and fails to start. There has been an exception to this rule since 4.2 that allowed top-level keys to be unknown/misspelled and only caused a warning to be logged. That exception has been removed and now any unknown or misspelled config key passed to Kibana (via the config file or command line flags) will prevent it from starting.
* Remove the es_admin proxy {pull}13000[#13000]
* Restrict ES data proxy to msearch and search {pull}13020[#13020]
* [server/indexPatterns] expose indexPatternService getter/factory {pull}13012[#13012]
* Remove client-side management of Kibana index mappings {pull}12820[#12820]
* Uses uuid for auto-generated ids and prepends type (#12834) {pull}12877[#12877]
* [uiSettings] support defining settings with uiExports {pull}12250[#12250]
  - define a uiExports.uiSettingDefaults key your plugin definition to add uiSettingDefaults - uiSettingDefaults must be unique. If a key is already defined elsewhere then the server will not start. - defined settings will display in the advanced settings editor, along with the intended default value and description - the REST API is identical to before - the browser API is identical to before - defaults for timelion have been extracted to the timelion plugin definition and the existing defaults are defined in the kibana plugin definition
* Refactor commaList filter logic into common util {pull}12553[#12553]
* [kbnServer/extensions] formalize request factories with helper {pull}12697[#12697]
* Allow plugins to turn off the "link to last URL" navigation helper {pull}13044[#13044]
Sharing::
* Add label and clear link to color picker {pull}12422[#12422]
* Expose the variables for dynamically building doc links {pull}12513[#12513]
* Reactify stateless table components {pull}12349[#12349]
* Full screen mode implementation for dashboard {pull}12265[#12265]
  - You can now enter full screen mode when viewing a dashboard. This hides the Chrome and the top nav bar.  If you have any filters applied, you'll see the filter bar, otherwise that will be hidden as well.  To exit full screen mode, hover over and click the Kibana button on the lower left side of the page, or simple press the ESC key.
Visualize::
* Visualize Refactor {pull}11786[#11786]
  - When creating new visualizations, developers are no longer restricted to using just Angular as a rendering technology. The changes now also enables developers to create custom editors that do not conform to the current sidebar-layout. Commonly used functionality - such as access to the query bar or timefilter - is now also exposed on the visualization object. This avoids the need to import individual modules from inside Kibana. These changes are a first step in a longer term effort to provide a robust long-lived programming interface for building visualizations in Kibana.
* Replace "marked" with "markdown-it" {pull}13623[#13623]
* Upgrade kibana to leaflet 1.x {pull}12367[#12367]
* Duration Formatting for TSVB {pull}13337[#13337]
* allows more flexible timelion queries {pull}10961[#10961]
* Support multiline Timelion queries {pull}11972[#11972]
* Fix ui-select error border color and placeholder font color. {pull}12411[#12411]
* Fix appearance of error indicator in Visualize sidebar.  {pull}12410[#12410]
* [Fix for #11193] hide current time marker when the timespan doesn't include the current time {pull}12266[#12266]
  - Only display current time marker on  a visualization when the x-axis extent includes the current time.
* [Fix for #7040] Add github-markdown.css to markdown visualization {pull}12377[#12377]
* Filter geohash_grid aggregation to map view box with collar {pull}12806[#12806]
* add font size control to markdown visualization {pull}12860[#12860]
* [vis/resizeChecker] swap out implemenation with ResizeObserver polyfill {pull}9439[#9439]
* Add imports for SavedObjectRegistryProvider.register, fixing Timelion {pull}12844[#12844]
* [Fix for #7572] add polygon drawing tool {pull}11578[#11578]
  - On a coordinate map, users can now make a selection on the map by drawing a freehand polygon. Just like the earlier boundary selection, this adds a boundary filter to the filter bar.
* [Fixes #12491, #12904, #12887] Improve accessibility of visualizations {pull}13507[#13507]
* [Fixes #11856, #12888, #12900] Improve accessibility of visualization view {pull}13726[#13726]


[float]
[[bug-6.0.0]]
=== Bug fixes
Core::
* update logstash data and mappings for single type {pull}13001[#13001]
Design::
* #12656 Fixes Aria-Hidden without value {pull}12658[#12658]
* [UI Framework] Fix disappearing borders for LocalNav search select. {pull}12803[#12803]
* Make breadcrumb a heading for screen readers, fix #12885 {pull}13734[#13734]
* [Fixes #12634] Improve date picker accessibility {pull}12676[#12676]
* [UI Framework] Fix margin for KuiLocalTabs which are applied to typographic elements. {pull}14451[#14451]
* Remove truncate from viz form text, remove additional wrapper {pull}14311[#14311]
Dev Tools::
* [Fix for #10504] [console] Replace text/plain fallback with application/json {pull}12294[#12294]
* [Fixes #13142] Allow console to send multiline strings with CRLF line endings {pull}14094[#14094]
  - Console will now allow sending multiline strings on Windows.
Discover::
* Remove simple_query_string hack now that multi_match supports * properly {pull}13285[#13285]
* Add documentation link to query bar when Kuery is selected {pull}13300[#13300]
* [Fixes #12970] Make 'time picker' button in Discover no results prompt keyboard and screen-reader accessible. {pull}13046[#13046]
* [Fixes #12692] Re-enable filter editor suggestions {pull}13376[#13376]
* [Fixes #13738] Fix 'is one of' filter editor {pull}13771[#13771]
* [Fixes #12639] Make filter pills keyboard accessible {pull}13331[#13331]
* [Fixes #12640] Make 'all filters' actions keyboard accessible {pull}13391[#13391]
* [Fixes #11830] Disable creation of 'exists' filters for scripted fields {pull}13538[#13538]
* Fix relative z-index of spy panel and filter editor {pull}13717[#13717]
* [Fixes #5164] Check sort:options for Discover default sort order {pull}13708[#13708]
* [Fixes #13075] Improve missing index pattern error message {pull}13915[#13915]
* [Fixes #13743] Refetch even when the query has not changed {pull}13759[#13759]
* [Fixes #14270] Handle strings in source mapped as numbers in filter editor {pull}14318[#14318]
* [Fixes #7767] Fix invisible filters caused by missing index pattern {pull}14131[#14131]
* [Fixes #14319] Loosen check for dashboard queries in filters array {pull}14338[#14338]
Management::
* Limit scripted fields to painless and expression langs {pull}9172[#9172]
* [Fix for #12249] Fixes issue #12249 {pull}12254[#12254]
* Refine getIndices() to return an empty array if there are no matching indices. {pull}12659[#12659]
* [Fix for #9352] Change mapping of index-pattern fields to text {pull}9353[#9353]
* [Fix for #12861, #12862, #12863, #12865, #12868, #12870, #11526] [Management] Improve accessibility within management {pull}13364[#13364]
* [Fix for #12864] [Management] Accessibility - continued {pull}13576[#13576]
* [Fix for #13542] [Management] Fix breaking scope changes in the field format editor samples {pull}13549[#13549]
* [Fix for #12872] Adds getAriaName function and applies it to advanced settings {pull}13448[#13448]
* Remove premature abstraction {pull}13042[#13042]
* fix create_index_pattern_method to handle no timefields {pull}13852[#13852]
* Work around #11959 for now {pull}12051[#12051]
* [Fixes #14350] [Management] Fix FF quirk with max width in the import saved object modal {pull}14352[#14352]
Operations::
* Use es6 exports, replace module.exports {pull}12084[#12084]
* Removing mapper.dynamic setting from the esArchiver mappings {pull}13970[#13970]
* Add linting rules for formatting JSX. {pull}12810[#12810]
* Upgrade eslint config to 0.8.1. {pull}13128[#13128]
* Move eslint-config-kibana into core {pull}12725[#12725]
* [npm] Upgrade wreck {pull}13849[#13849]
* Eslint/remove last amd modules {pull}14282[#14282]
Platform::
* Update HTML style guide with rule for camel casing attribute values. {pull}11653[#11653]
* Add title and tooltip accessibility information to HTML style guide. {pull}11655[#11655]
* [Fix for #12580] Update HTML style guide with rule about putting nested elements on multiple lines. {pull}12812[#12812]
* [Fix for #12047] [uiSettings] make service request based {pull}12243[#12243]
  - removes server.uiSettings() (throws error with instructions)  - Adds request.getUiSettingsService() which returns a unique instance of UiSettingsService per request  - Methods on UiSettingsService no longer require a request object  - Adds server.uiSettingsServiceFactory(options) which can be used to create an instance of UiSettingsService with a custom callCluster() function
* [Fix for #12436] Fix stats permissions and use underscore instead of dash {pull}12478[#12478]
* [ftr] remove timestamp prefix, jenkins has it built in now {pull}13825[#13825]
* [ftr/config] prevent mochaOpts and timeouts conflict {pull}14060[#14060]
* create babel-preset and babel-register modules {pull}13973[#13973]
* [vis/requesting] only call when actually requesting {pull}14017[#14017]
* [Fixes #14255] Use Boom.boomify instead of deprecated Boom.wrap {pull}14325[#14325]
* [Fixes #14497] Import Babel polyfill when running Jest tests {pull}14508[#14508]
Sharing::
* Restoring the dashboard-grid padding to appease Gridster {pull}12613[#12613]
* [Fix for #11857] Accessibility: Sharing UI - associate labels with controls {pull}12143[#12143]
* [Fix for #11860] Make add edit buttons accessible {pull}12320[#12320]
* Need to trigger renderComplete when there are no results {pull}12380[#12380]
* remove inline awaits {pull}13043[#13043]
* Stabilize and bring back flaky tests {pull}13034[#13034]
* [Fix for #12484, #12485, #12483] Fix accessibility issues with saved object finder {pull}13152[#13152]
* [Fix for #12987] Children of buttons won't capture hover events in firefox {pull}13015[#13015]
* [Fixes #13421] Dashboard dark-theme fixes {pull}13690[#13690]
* [Fixes #12233] Be case insensitive when sorting on the visualize and dashboard landing pages {pull}13397[#13397]
* Fix bug with Dashboard breadcrumb alignment. {pull}13580[#13580]
* [Fixes #13040] Make sure no one can show the chrome if the default setting is hidden. {pull}13250[#13250]
* [Fixes #13297] Fix full screen toggle button when panel is expanded {pull}13320[#13320]
* Show full screen option even when write controls are hidden {pull}13247[#13247]
* [Fixes #13289] Use find service instead of remote  {pull}13296[#13296]
* [Fixes #13754] Small clean up with visualize test + extra debug log {pull}13755[#13755]
* [Fixes #13588] Fix map updates not propagating to the dashboard {pull}13589[#13589]
* Set pie chart border to match background in dark mode {pull}14375[#14375]
* [Fixes #14462] Prevent event handlers from being triggered after they are &quot;off&quot;ed {pull}14463[#14463]
Visualize::
* update spy table headers when columns update {pull}13225[#13225]
* Fixes #12757 - Fixing field fetching for index patterns for TSVB {pull}12771[#12771]
* [Fix for #4599] Add "Sum of series in legend" option {pull}7970[#7970]
* [Fix for #9053] [timelion/fit/carry] do nothing if there is not any data {pull}9054[#9054]
* [Fix for #8763] [vislib/tilemap/heatmap] scale the heatmap maxZoom with map zoom {pull}8765[#8765]
* [Fix for #9184] fixes error with custom interval in datetime aggregation {pull}9427[#9427]
* Fix timelion's flot when neither thor nor monitoring are installed {pull}10412[#10412]
* Fixes #12763 - Add show_grid to the default vis structure for TSVB {pull}12769[#12769]
* Fixes #12777 - Add onBrush to Visualization component for TSVB {pull}12778[#12778]
* [Fix for #12802, #12762] Fix TSVB Visualizations to honor darkTheme {pull}12804[#12804]
* [Fix for #8076] Scaled date format for date histogram aggregation {pull}12384[#12384]
  - Format date_histogram aggregation bucket labels with format specified in Advanced Setting's "dateFormat:scaled"
* [Fix for #3230] Make vertical bar chart gutter widths consistent {pull}12264[#12264]
  - Histogram intervals are not always equal widths (monthly time intervals). Keeping gutter widths consistent and reducing the bar width provides a more visually appealing bar chart.
* [Fix for #3173] Date histogram brush - add range filter when field is not index pattern time field. {pull}12286[#12286]
* Remove event listener for resizeChecker when directive is destroyed {pull}12734[#12734]
* Date histogram axis label not getting updated when time interval changes {pull}12815[#12815]
* [Fix for #12782] visualize should send ready:vis event when done {pull}12796[#12796]
* [Fix for #12811] reload visualization on auto refresh trigger {pull}12823[#12823]
* [Fix for #12882] changing query should update url state {pull}12912[#12912]
* vis with saved search should not show query and filter panels {pull}12911[#12911]
* [Fix for #12925] analyze wildcard should not be part of default query {pull}12938[#12938]
* [Fix for #12940] query queue should be cleared on failure {pull}12942[#12942]
* Handle date histogram scaling for table vis and avg_buckets metric {pull}11929[#11929]
* [Fix for #11414] remove default WMS settings {pull}11573[#11573]
* [Fix for #12497] allows to order percentiles freely {pull}12498[#12498]
* [Fix for #12732] Should only run visualization on Discover page when the indexpattern is time based {pull}12741[#12741]
* reload on global fetch event and emit vis:ready {pull}12805[#12805]
* [Fix for #12919] Fix excessive redraw {pull}12931[#12931]
* [Fix for #13181, elastic/beats#4777] Add Checks to Dashboard Context {pull}13182[#13182]
* [Fix for #11586] Use ui-select for agg selector {pull}13292[#13292]
* [Fix for #13227] Send map filters through $newFilters so they get picked up by both kuery and lucene {pull}13251[#13251]
* [Fix for #12827] removes :filters from label {pull}12962[#12962]
* [Fix for #12983] resize was not detected correctly {pull}13239[#13239]
* [Fix for #13011] Should respect pinned filters {pull}13019[#13019]
* Visualization accessibility issues {pull}13226[#13226]
* Fixes #12685 - Improve error handling for TSVB {pull}12688[#12688]
* [Fix for #13246] Fixes #13246 - Add checks for empty annotations {pull}13422[#13422]
* [Fix for #13010] Fixes #13010 - Add dateFormat config to TSVB Visualizations {pull}13626[#13626]
* [Fix for #13625] Map filter not set appropriately when spy panel is open {pull}13678[#13678]
* [Fix for #13156] fixing disabling aggregations {pull}13686[#13686]
  - Disabled aggregations are no longer removed on applying visualization configuration.
* [Fix for #12896, #12897, #12898, #12899] Visualize Accessibility Issues {pull}13428[#13428]
* Fix a bug with the interval label for TSVB {pull}13440[#13440]
* [Fix for #12113] Fixes #12113 - Add timezone to date histogram aggregations for TSVB {pull}13378[#13378]
* [Fix for #13471] Closes #13471 - Change split behavior of gauges and metrics vis {pull}13583[#13583]
* [Fix for #12227] Fix discover sidebar Visualize button for geo_point fields {pull}13539[#13539]
* Clamp the centroid to stay within the box boundaries {pull}13581[#13581]
* [Fix for #13551] fix heatmap sizing on dashboard {pull}13636[#13636]
* ensure editor mode propagates correctly {pull}13355[#13355]
* [Fix for #13517] remove geo_bounds agg from visualizations {pull}13536[#13536]
* [Fix for #13424] Exclude filter agg from visualizations {pull}13680[#13680]
* [Fix for #13572] Show a warning for non accessible charts for screen readers {pull}13573[#13573]
* date_histogram: some bars are too big {pull}13068[#13068]
* [Fixes #13713] [Accessibility] Use aria-label in TSVB React components, instead of ariaLabel. {pull}13714[#13714]
* [TSVB] Adding check for model and visData {pull}13854[#13854]
* Fixes a bug with PR #13854 {pull}13873[#13873]
* [TSVB] Fix chart legend formatting in bottom position {pull}14084[#14084]
* [Fixes #12733, #12781] fixing refresh and auto refresh {pull}12752[#12752]
* [Fixes #12836] fix spy panel on discovery page {pull}12853[#12853]
* visual builder should set vis.initialized when ready {pull}13779[#13779]
* [Fixes #13770] updating time picker should not set vis to dirty {pull}13793[#13793]
* editor render method should not be called if request is pending {pull}13858[#13858]
* [Fixes #12759, #12761, #12763] Fix TSVB UX flow {pull}12770[#12770]
* fixing region map click handler {pull}12790[#12790]
* use parentNode iso parentElement {pull}13842[#13842]
* wrap responsehandler in angular promise {pull}14095[#14095]
* [TSVB] Greater Than or Equal to Interval Pattern {pull}13872[#13872]
* [Fixes #14470] [TSVB] Fixes #14470 - Remove field restriction on cardinality agg {pull}14483[#14483]
* [TSVB] Fix CSS Bug with Top N Values {pull}14254[#14254]
* [Fixes #14357] Fixes #14357 - Add courier's migrateFilters to dashboard context {pull}14481[#14481]
* [Fixes #14040, #13997] Show query and filter bars even when there's a linked search {pull}14212[#14212]
* [Fixes #13287] adds stroke back to area charts {pull}14149[#14149]
* [Fixes #13193] fixes legend refreshing {pull}14150[#14150]
* [Fixes #13252] fixes error when expanding gauge to full screen {pull}14114[#14114]
* pie chart design guidelines {pull}13661[#13661]
* [Fixes #14028] removing check for vis type on saved visualizations {pull}14093[#14093]
* [Fixes #10543] fixing ordering of series in legend {pull}14113[#14113]
  - order of legend for series should be same as provided in the configuration.
* [Fixes #14078] fixes console error when selecting a pipeline aggregation {pull}14148[#14148]
* allows visualize to load saved vis {pull}14146[#14146]
* [Fixes #13570] don't show spy panel with tsvb or timelion {pull}14090[#14090]
* moving shouldShowSpyPanel to visualize {pull}14269[#14269]
* refactor tagcloud to use tabify responseHandler {pull}14266[#14266]
* some updates to visualize loader {pull}14404[#14404]
* Visualize loader updates {pull}14528[#14528]
* [Fixes #13705] use correct element for size {pull}14105[#14105]
* [Fixes #12953] remove junk tests {pull}14191[#14191]
* use tabify for regionmap {pull}14364[#14364]
* [Fixes #13144] Fixes 13144 - Add ability to select percentiles in pipeline aggs {pull}13453[#13453]
* [Fixes #12069] apply field formatter to tag cloud {pull}14230[#14230]
* [Fixes #12134] add tickDecimals option to yaxis {pull}14371[#14371]
* [Fixes #14457] Set configurable to true so AggConfig decorated properties can be deleted {pull}14569[#14569]
* [Fixes #10236, #9053] Timelion .fit() - avoid removing values that are zero {pull}14560[#14560]
* [Fixes #13874] Allow panning beyond dateline {pull}13955[#13955]
  - Users can now pan and zoom the map beyond the date line.
* [TSVB] Allow negative time offsets {pull}14494[#14494]
* [Fixes #14565] Fix tagcloud sync issues, fix #14565 {pull}14566[#14566]
