[[release-notes-6.2.0]]
== 6.2.0 Release Notes

Also see <<breaking-changes-6.0>>.


[float]
[[enhancement-6.2.0]]
=== Enhancements
Discover::
* [Fixes #15642] Introduce simple kibana query language {pull}15646[#15646]
Management::
* [Fixes #9228, #8983] add support for number format internationalization {pull}14019[#14019]
* [Fixes #15922] [Management] Index pattern step in React! {pull}15936[#15936]
* Advanced Settings - Image Input {pull}15342[#15342]
Operations::
* Use auto_expand_replicas to stay green on 1 node clusters {pull}15694[#15694]
* Feat: Add config provider to disable state management {pull}15275[#15275]
* [optimizer] More aggressive chunking of common/vendor code {pull}15907[#15907]
  - Improved the build optimize time by more aggressively chunking common code, resulting in the removal of duplicate code. This drastically cuts the build and plugin install time and overall bundle asset size.
* [Fixes #14813] [ui/bundles][optimizer] only use caches when in dev mode {pull}15780[#15780]
* [optimizer] run webpack compilation ASAP (no more laziness) {pull}15795[#15795]
Platform::
* [Fixes #6520] [optimizer] allow http caching for bundles {pull}15880[#15880]
* Make it possible to disable CSRF check for the specified list of paths. {pull}13904[#13904]
Sharing::
* [Fixes #2758] Add advanced setting to control quick ranges {pull}15975[#15975]
* [input controls] Horizontal layout {pull}14918[#14918]
* Kibana Home page - phase two {pull}14749[#14749]
* Add &quot;use time filter&quot; option to input controls {pull}15852[#15852]
Visualization::
* [Fixes #13992] Grab the default index pattern and use it in TSVB {pull}14739[#14739]
  - TSVB now uses Kibana's default index pattern by default.
* [TSVB] Add params._interval to mathjs {pull}14944[#14944]
  - Make the bucket interval available as a parameter.
* [Fixes #13781] [timelion] allow sum, subtract, multiply, divide functions to accept seriesList with multiple series {pull}14891[#14891]
* [Fixes #8953] Add Timelion percentiles aggregation support (#8953) {pull}15154[#15154]
* [Fixes #9845] [timelion] highlight series on legend mouseover {pull}15229[#15229]
* add time to visualization status {pull}15856[#15856]
* few enhancements to default sidebar editor {pull}15619[#15619]
  - Its now possible to resize the sidebar editor and auto apply is possible in markdown visualization.
* [Fixes #1961] other and missing bucket support for terms agg {pull}15525[#15525]
  - 'other' and 'missing' bucket for the terms aggregation resolves #1961
* [Fixes #15146] Refactor and improve Visualize Loader {pull}15157[#15157]
  - Do not use the &lt;visualize&gt; directive anymore to embed a visualization. Use the Visualize Loader instead.
* [Fixes #15153] Use visualize loader for dashboards {pull}15444[#15444]
* Refactor rendering events {pull}15895[#15895]
* Migrating vega_vis from plugin {pull}15014[#15014]

[float]
[[bug-6.2.0]]
=== Bug fixes
Discover::
* display NOT when new filter is negated {pull}15865[#15865]
* [Fixes #15364] Truncate long names in the discover index pattern selection {pull}15510[#15510]
* Add missing discover labels {pull}16030[#16030]
Management::
* [Fixes #16098] [Management] Allow wildcard anywhere in the search query {pull}16109[#16109]
* [Fixes #16192] [Management] Update pager with new props in Index Pattern Creation {pull}16195[#16195]
* [Fixes #15922] Hide caret when indices has no time fields, remove indices object containing unused string {pull}16412[#16412]
Sharing::
* [Fixes #16307] link to dashboards by id instead of title {pull}16319[#16319]
Visualization::
* [Fixes #16349] Fix issue with disabled lab mode {pull}16351[#16351]
* [TSVB] Changing the behaivor of getLastValue to get the actual last value {pull}14919[#14919]
* [TSVB] Stacked series should not contain null values {pull}14923[#14923]
* [Fixes #15273] disable input control when field contains no values in index pattern {pull}15317[#15317]
* Set list-style-type for list items in markdown-body {pull}15827[#15827]
* Visualization render status - pass correct parameters to resize check {pull}15855[#15855]
* fixes angular vis type so it correctly propagates events up to visualize {pull}15629[#15629]
* [Fixes #15427] fixing dot ratio slider {pull}15860[#15860]
  - dot size slider for line chart works again
* fixing log scale error {pull}15984[#15984]
  - log scale now works with empty buckets
* [Fixes #15114] fixing boolean filters {pull}15927[#15927]
* [Fixes #15931, #15656] check if data hash changed instead of stringifying {pull}15988[#15988]
  - performance of visualization rendering is improved
* Remove SVG element styling rules {pull}15906[#15906]
* [Fixes #15553] Fix bug where negative time offsets in visual builder will shift x-axis range {pull}15554[#15554]
* [6.x] Fix maps for reporting (#15272) {pull}15357[#15357]
* Sharing - exposing Dashboard and Visualize title and type {pull}14946[#14946]
* [Fixes #14730] pass bucket size as _interval param to calculation metric script {pull}14731[#14731]
* [Fixes #15672, #14353] Revert Resize and FlotChart components to 6.0 {pull}15717[#15717]
* [Fixes #15501] [TSVB] Fixes #15501 - Change xaxis formatter to honor dateFormat:tz {pull}15512[#15512]
* [TSVB] Make form font-sizes consistent (after EUI upgrade) {pull}15909[#15909]
* Remove MathJS Feature {pull}15652[#15652]
* [TSVB] Add checks for scaledDataFormat and dateFormat in xaxisFormatter {pull}15997[#15997]
* [TSVB] Fix typo is filter ratio path for table visualization {pull}16052[#16052]
* [Fixes #14888] [timelion] provide argument suggestions when argument name not provided {pull}15081[#15081]
* [Fixes #15594] fixes pie chart size to normal if labels are not applied {pull}15641[#15641]
* [Fixes #15818] fixing collapsible side bar editor {pull}15826[#15826]
* [Fixes #15703] refactoring vis uiState {pull}15709[#15709]
* [Fixes #15673] fixes table padding on dashboard {pull}15862[#15862]
* [Fixes #15778] fixing tag cloud and region map click handler {pull}15861[#15861]
* fixes renderComplete in angular vis type {pull}16150[#16150]
* [Fixes #16217] fixing axis title position for firefox {pull}16278[#16278]
* [Fixes #13822] visualize editor should not show if embed is set to true in url {pull}16310[#16310]
* [Fixes #16083] configure Kibana with production endpoint for EMSv3 {pull}16108[#16108]
* [Fixes #13813] Use a width range instead of a fixed width for visualize legends {pull}13818[#13818]
* should always set base layer {pull}16213[#16213]
* Extract lab HTML on dashboard into own file {pull}15546[#15546]
* Remove implementsRenderComplete property {pull}15579[#15579]
* [Fixes #15255] Set uiState to Vis from visualization {pull}15549[#15549]
* [Fixes #15618] Fix broken initial uiState set {pull}15630[#15630]
* [Fixes #15742] Only apply forced max mode when panel is shown {pull}15752[#15752]
* Fix JSON hint styling and accessibility {pull}15890[#15890]
* [Fixes #15712] Fix broken editor styles {pull}15735[#15735]
* [Fixes #15713] Use euiCallOut for experimental banner {pull}15989[#15989]
* Fix some styling issues {pull}16023[#16023]
* Listen to resize events in &lt;visualize&gt; {pull}16048[#16048]
* [Fixes #16216] Prevent rendering into 0 size containers {pull}16287[#16287]
* [Fixes #14331] Add topojson support / EMS v3 support {pull}15361[#15361]

