import type { PluginInitializerContext } from '@kbn/core/server';
export { config } from './config';
export declare function plugin(initializerContext: PluginInitializerContext): Promise<import("./plugin").WorkflowsExtensionsServerPlugin>;
export type { ServerTriggerDefinition, WorkflowsExtensionsRequestHandlerContext, WorkflowsExtensionsServerPluginSetup, WorkflowsExtensionsServerPluginStart, WorkflowsExtensionsServerPluginSetupDeps, WorkflowsExtensionsServerPluginStartDeps, } from './types';
export type { EventChainContext } from './event_chain_context';
export { EVENT_CHAIN_DEPTH_HEADER, EVENT_CHAIN_EMITTER_EXECUTION_ID_HEADER, EVENT_CHAIN_VISITED_WORKFLOW_IDS_HEADER, EVENT_CHAIN_SOURCE_EXECUTION_HEADER, WORKFLOW_EVENT_CHAIN_CONTEXT, X_ELASTIC_INTERNAL_ORIGIN_REQUEST, getEmitterWorkflowExecutionIdFromRequest, getEventChainContext, getEventChainDepthFromHeaders, getOutboundEventChainHeaders, setWorkflowEventChainContext, } from './event_chain_context';
export type { ServerStepDefinition, StepHandler, StepHandlerContext, StepHandlerResult, OnCancelHandler, } from './step_registry/types';
export { createServerStepDefinition } from './step_registry/types';
export { TriggerRegistry } from './trigger_registry';
export { WORKFLOW_EXECUTION_FAILED_TRIGGER_ID } from './triggers';
export type { WorkflowExecutionFailedEvent } from './triggers';
