steps:
  - name: 'Reconcile PR Labels'
    command: .buildkite/scripts/steps/version_bump/reconcile_pr_labels.sh
    soft_fail: true
    agents:
      image: family/kibana-ubuntu-2404
      imageProject: elastic-images-prod
      provider: gcp
      machineType: n2-standard-4
