steps:
  - name: Trigger DRA Snapshot Build
    key: trigger-dra-snapshot
    trigger: kibana-artifacts-snapshot
    async: false
    if: build.env("DRY_RUN") != "true"
    build:
      branch: 'main'
