import type { PluginInitializerContext } from '@kbn/core/public';
import { AdvancedUiActionsPublicPlugin } from './plugin';
export declare function plugin(initializerContext: PluginInitializerContext): AdvancedUiActionsPublicPlugin;
export { AdvancedUiActionsPublicPlugin as Plugin };
export type { SetupContract as AdvancedUiActionsSetup, StartContract as AdvancedUiActionsStart, } from './plugin';
export type { ActionFactoryDefinition as UiActionsEnhancedActionFactoryDefinition, SerializedAction as UiActionsEnhancedSerializedAction, SerializedEvent as UiActionsEnhancedSerializedEvent, DynamicActionManagerParams as UiActionsEnhancedDynamicActionManagerParams, DynamicActionManagerState as UiActionsEnhancedDynamicActionManagerState, BaseActionFactoryContext as UiActionsEnhancedBaseActionFactoryContext, BaseActionConfig as UiActionsEnhancedBaseActionConfig, } from './dynamic_actions';
export { ActionFactory as UiActionsEnhancedActionFactory, AbstractActionStorage as UiActionsEnhancedAbstractActionStorage, DynamicActionManager as UiActionsEnhancedDynamicActionManager, MemoryActionStorage as UiActionsEnhancedMemoryActionStorage, } from './dynamic_actions';
export type { DynamicActionsState } from './services/ui_actions_service_enhancements';
export type { UrlDrilldownConfig, UrlDrilldownGlobalScope, UrlDrilldownScope, UrlDrilldownOptions, } from './drilldowns/url_drilldown';
export { urlDrilldownCompileUrl, UrlDrilldownCollectConfig, UrlDrilldownOptionsComponent, urlDrilldownGlobalScopeProvider, urlDrilldownValidateUrl, urlDrilldownValidateUrlTemplate, DEFAULT_URL_DRILLDOWN_OPTIONS, } from './drilldowns/url_drilldown';
