[[brew]]
=== Install {kib} on macOS with Homebrew

Elastic publishes Homebrew formulae so you can install {kib} with the https://brew.sh/[Homebrew] package manager.

To install with Homebrew, you first need to tap the Elastic Homebrew repository:

[source,sh]
-------------------------
brew tap elastic/tap
-------------------------

Once you've tapped the Elastic Homebrew repo, you can use `brew install` to
install the default distribution of {kib}:

[source,sh]
-------------------------
brew install elastic/tap/kibana-full
-------------------------

This installs the most recently released default distribution of {kib}. To install the OSS distribution,
specify `elastic/tap/kibana-oss`.

[[brew-layout]]
==== Directory layout for Homebrew installs

When you install {kib} with `brew install`, the config files, logs,
and data directory are stored in the following locations.

[cols="<h,<,<m,<m",options="header",]
|=======================================================================
| Type | Description | Default Location | Setting
| home
  | Kibana home directory or `$KIBANA_HOME`
  | /usr/local/var/homebrew/linked/kibana-full
 d|

| bin
  | Binary scripts including `kibana` to start a node
    and `kibana-plugin` to install plugins
  | /usr/local/var/homebrew/linked/kibana-full/bin
 d|

| conf
  | Configuration files including `kibana.yml`
  | /usr/local/etc/kibana
 d|  

| data
  | The location of the data files of each index / shard allocated
    on the node. Can hold multiple locations.
  | /usr/local/var/lib/kibana
  | path.data

| logs
  | Log files location.
  | /usr/local/var/log/kibana
  | path.logs

| plugins
  | Plugin files location. Each plugin will be contained in a subdirectory.
  | /usr/local/var/homebrew/linked/kibana-full/plugins
 d|

|=======================================================================
