[[deb]]
=== Install {kib} with Debian package
++++
<titleabbrev>Install with Debian package</titleabbrev>
++++

The Debian package for Kibana can be <<install-deb,downloaded from our website>>
or from our <<deb-repo,APT repository>>. It can be used to install
Kibana on any Debian-based system such as Debian and Ubuntu.

This package contains both free and subscription features.
<<managing-licenses,Start a 30-day trial>> to try out all of the features.

The latest stable version of Kibana can be found on the
link:/downloads/kibana[Download Kibana] page. Other versions can
be found on the link:/downloads/past-releases[Past Releases page].

[[deb-key]]
==== Import the Elastic PGP key

include::key.asciidoc[]

[source,sh]
-------------------------
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
-------------------------

[[deb-repo]]
==== Install from the APT repository

ifeval::["{release-state}"=="unreleased"]

Version {version} of Kibana has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

You may need to install the `apt-transport-https` package on Debian before proceeding:

[source,sh]
--------------------------------------------------
sudo apt-get install apt-transport-https
--------------------------------------------------

Save the repository definition to  +/etc/apt/sources.list.d/elastic-{major-version}.list+:

ifeval::["{release-state}"=="released"]

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
echo "deb https://artifacts.elastic.co/packages/{major-version}/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-{major-version}.list
--------------------------------------------------

endif::[]

ifeval::["{release-state}"=="prerelease"]

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
echo "deb https://artifacts.elastic.co/packages/{major-version}-prerelease/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-{major-version}.list
--------------------------------------------------

endif::[]


[WARNING]
==================================================

Do not use `add-apt-repository` as it will add a `deb-src` entry as well, but
we do not provide a source package. If you have added the `deb-src` entry, you
will see an error like the following:

    Unable to find expected entry 'main/source/Sources' in Release file
    (Wrong sources.list entry or malformed file)

Delete the `deb-src` entry from the `/etc/apt/sources.list` file and the
installation should work as expected.
==================================================

You can install the Kibana Debian package with:

[source,sh]
--------------------------------------------------
sudo apt-get update && sudo apt-get install kibana
--------------------------------------------------

[WARNING]
==================================================
If two entries exist for the same Kibana repository, you will see an error like this during `apt-get update`:

["literal",subs="attributes,callouts"]

Duplicate sources.list entry https://artifacts.elastic.co/packages/{major-version}/apt/ ...`

Examine +/etc/apt/sources.list.d/kibana-{major-version}.list+ for the duplicate entry or locate the duplicate entry amongst the files in `/etc/apt/sources.list.d/` and the `/etc/apt/sources.list` file.
==================================================

endif::[]

[[install-deb]]
==== Download and install the Debian package manually

ifeval::["{release-state}"=="unreleased"]

Version {version} of Kibana has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

The Debian package for Kibana v{version} can be downloaded from the website and installed as follows:

["source","sh",subs="attributes"]
--------------------------------------------
wget https://artifacts.elastic.co/downloads/kibana/kibana-{version}-amd64.deb
shasum -a 512 kibana-{version}-amd64.deb <1>
sudo dpkg -i kibana-{version}-amd64.deb
--------------------------------------------
<1> Compare the SHA produced by `shasum` with the
    https://artifacts.elastic.co/downloads/kibana/kibana-{version}-amd64.deb.sha512[published SHA].

endif::[]

[[deb-enroll]]
==== Start {es} and generate an enrollment token for {kib}
++++
<titleabbrev>Generate an enrollment token</titleabbrev>
++++

When you start {es} for the first time, the following security configuration
occurs automatically:

* Authentication and authorization are enabled, and a password is generated for the `elastic` built-in superuser.
* Certificates and keys for TLS are generated for the transport and HTTP layer, and TLS is enabled and configured with these keys and certificates.

The password and certificate and keys are output to your terminal.

You can then generate an enrollment token for {kib} with the
{ref}/create-enrollment-token.html[`elasticsearch-create-enrollment-token`] tool:

[source,sh]
----
bin/elasticsearch-create-enrollment-token -s kibana
----

Start {kib} and enter the enrollment token to securely connect {kib} with {es}.

[[deb-running-systemd]]
include::systemd.asciidoc[]

[[deb-configuring]]
==== Configure {kib} via the config file

Kibana loads its configuration from the `/etc/kibana/kibana.yml`
file by default.  The format of this config file is explained in
{kibana-ref}/settings.html[Configuring Kibana].

[[deb-layout]]
==== Directory layout of Debian package

The Debian package places config files, logs, and the data directory in the appropriate
locations for a Debian-based system:


[cols="<h,<,<m,<m",options="header",]
|=======================================================================
| Type | Description | Default Location | Setting
| home
  | Kibana home directory or `$KIBANA_HOME`
  | /usr/share/kibana
 d|

| bin
  | Binary scripts including `kibana` to start the Kibana server
    and `kibana-plugin` to install plugins
  | /usr/share/kibana/bin
 d|

| config
  | Configuration files including `kibana.yml`
  | /etc/kibana
  | <<settings,KBN_PATH_CONF>>

| data
  | The location of the data files written to disk by Kibana and its plugins
  | /var/lib/kibana
  | path.data

| logs
  | Logs files location
  | /var/log/kibana
  | path.logs

| plugins
  | Plugin files location. Each plugin will be contained in a subdirectory.
  | /usr/share/kibana/plugins
 d|

|=======================================================================
