import type { DisplayedAssetTypes } from '../types/models';
export declare const PACKAGES_SAVED_OBJECT_TYPE = "epm-packages";
export declare const ASSETS_SAVED_OBJECT_TYPE = "epm-packages-assets";
export declare const MAX_TIME_COMPLETE_INSTALL: number;
export declare const MAX_REINSTALL_RETRIES = 3;
export declare const FLEET_SYSTEM_PACKAGE = "system";
export declare const FLEET_ELASTIC_AGENT_PACKAGE = "elastic_agent";
export declare const FLEET_SERVER_PACKAGE = "fleet_server";
export declare const FLEET_ENDPOINT_PACKAGE = "endpoint";
export declare const FLEET_APM_PACKAGE = "apm";
export declare const FLEET_SYNTHETICS_PACKAGE = "synthetics";
export declare const FLEET_KUBERNETES_PACKAGE = "kubernetes";
export declare const FLEET_OTEL_COLLECTOR_INTERNAL_TELEMETRY_PACKAGE = "otel_collector_internal_telemetry";
export declare const FLEET_UNIVERSAL_PROFILING_SYMBOLIZER_PACKAGE = "profiler_symbolizer";
export declare const FLEET_UNIVERSAL_PROFILING_COLLECTOR_PACKAGE = "profiler_collector";
export declare const FLEET_CLOUD_SECURITY_POSTURE_PACKAGE = "cloud_security_posture";
export declare const FLEET_CLOUD_SECURITY_ASSET_PACKAGE = "cloud_asset_inventory";
export declare const FLEET_CLOUD_SECURITY_POSTURE_KSPM_POLICY_TEMPLATE = "kspm";
export declare const FLEET_CLOUD_SECURITY_POSTURE_CSPM_POLICY_TEMPLATE = "cspm";
export declare const FLEET_CLOUD_SECURITY_POSTURE_ASSET_INVENTORY_POLICY_TEMPLATE = "asset_inventory";
export declare const FLEET_CLOUD_SECURITY_POSTURE_CNVM_POLICY_TEMPLATE = "vuln_mgmt";
export declare const FLEET_CLOUD_DEFEND_PACKAGE = "cloud_defend";
export declare const FLEET_CLOUD_BEAT_PACKAGE = "cloudbeat";
export declare const FLEET_CONNECTORS_PACKAGE = "elastic_connectors";
export declare const GLOBAL_DATA_TAG_EXCLUDED_INPUTS: Set<string>;
export declare const PACKAGE_TEMPLATE_SUFFIX = "@package";
export declare const USER_SETTINGS_TEMPLATE_SUFFIX = "@custom";
export declare const OTEL_TEMPLATE_SUFFIX = "otel";
export declare const DATASET_VAR_NAME = "data_stream.dataset";
export declare const DATA_STREAM_TYPE_VAR_NAME = "data_stream.type";
export declare const USE_APM_VAR_NAME = "use_apm";
export declare const CUSTOM_INTEGRATION_PACKAGE_SPEC_VERSION = "2.9.0";
export declare const GENERIC_DATASET_NAME = "generic";
export declare const autoUpdatePackages: string[];
export declare const HIDDEN_API_REFERENCE_PACKAGES: string[];
export declare const EXCLUDED_FROM_PACKAGE_POLICY_COPY_PACKAGES: string[];
export declare const autoUpgradePoliciesPackages: string[];
export declare const agentAssetTypes: {
    readonly Input: "input";
};
export declare const dataTypes: {
    readonly Logs: "logs";
    readonly Metrics: "metrics";
    readonly Traces: "traces";
};
export declare const monitoringTypes: ("metrics" | "logs" | "traces")[];
export declare const installationStatuses: {
    readonly Installed: "installed";
    readonly Installing: "installing";
    readonly InstallFailed: "install_failed";
    readonly NotInstalled: "not_installed";
};
export declare const displayedAssetTypes: DisplayedAssetTypes;
export declare const displayedAssetTypesLookup: Set<string>;
export declare const OTEL_COLLECTOR_INPUT_TYPE = "otelcol";
