export { INTEGRATIONS_PLUGIN_ID, PLUGIN_ID } from './plugin';
export { INGEST_SAVED_OBJECT_INDEX, FLEET_SETUP_LOCK_TYPE, CLOUD_CONNECTOR_SAVED_OBJECT_TYPE, } from './saved_objects';
export * from './routes';
export * from './agent';
export * from './agent_policy';
export * from './agentless';
export * from './package_policy';
export * from './epm';
export * from './output';
export * from './enrollment_api_key';
export * from './settings';
export * from './preconfiguration';
export * from './download_source';
export * from './fleet_server_policy_config';
export * from './authz';
export * from './file_storage';
export * from './message_signing_keys';
export * from './locators';
export * from './secrets';
export * from './uninstall_token';
export * from './space_awareness';
export * from './security_search_ai_lake';
export * from './cloud_connector';
export declare const SO_SEARCH_LIMIT = 10000;
export declare const ES_SEARCH_LIMIT = 10000;
export declare const FLEET_SERVER_INDICES_VERSION = 1;
export declare const FLEET_SERVER_ARTIFACTS_INDEX = ".fleet-artifacts";
export declare const FLEET_SERVER_INDICES: string[];
export declare const DATA_TIERS: string[];
export declare const FLEET_ENROLLMENT_API_PREFIX = "fleet-enrollment-api-keys";
export declare const REQUEST_DIAGNOSTICS_TIMEOUT_MS: number;
export * from './mappings';
export declare const AUTO_UPGRADE_DEFAULT_RETRIES: string[];
export declare const FLEET_LOG_INDICES: string[];
