steps:
  - command: .buildkite/scripts/steps/functional/security_serverless_ai4dsoc.sh
    cancel_on_build_failing: true
    label: 'Serverless AI4DSOC - Security Solution Cypress Tests'
    agents:
      machineType: n2-standard-4
      preemptible: true
      spotZones: us-central1-f,us-central1-c,us-central1-a
    depends_on:
      - build
<<<<<<< HEAD
      - quick_checks
      - checks
      - linting
      - linting_with_types
      - check_types
      - check_oas_snapshot
=======
>>>>>>> b0447fb21e84 ([CI] Add optimistic cancellation for PR pipeline gate failures (#254621))
    timeout_in_minutes: 60
    parallelism: 1
    retry:
      automatic:
        - exit_status: '-1'
          limit: 1
