/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Privileged User Monitoring API
 *   version: 2023-10-31
 */

import type { z } from '@kbn/zod';

import { UserName, MonitoredUserDoc } from './common.gen';

export type CreatePrivMonUserRequestBody = z.infer<typeof CreatePrivMonUserRequestBody>;
export const CreatePrivMonUserRequestBody = UserName;
export type CreatePrivMonUserRequestBodyInput = z.input<typeof CreatePrivMonUserRequestBody>;

export type CreatePrivMonUserResponse = z.infer<typeof CreatePrivMonUserResponse>;
export const CreatePrivMonUserResponse = MonitoredUserDoc;
