[role="xpack"]
[[xpack-security]]
== Security

{xpack} security enables you to easily secure a cluster. With security, you can
password-protect your data as well as implement more advanced security measures
such as encrypting communications, role-based access control, IP filtering, and
auditing. For more information, see
{xpack-ref}/xpack-security.html[Securing {es} and {kib}] and
<<using-kibana-with-security,Configuring Security in {kib}>>.

[float]
=== Users

You can create and manage users on the *Management* / *Security* / *Users* page.
You can also change their passwords and roles. For more information about
authentication and built-in users, see
{xpack-ref}/setting-up-authentication.html[Setting Up User Authentication].

[float]
=== Roles

To manage roles that are stored in Elasticsearch's `native` realm, you can use the
*Management* / *Security* / *Roles* page, or {kib}'s <<role-management-api>>.

[NOTE]
============================================================================
It is *not* supported to manage Roles which grant <<kibana-privileges>> using 
{es}'s {ref}/security-api-roles.html[Role Management APIs], and 
doing so will likely cause Kibana's authorization to behave unexpectedly. 
============================================================================

For more information, see <<xpack-security-authorization>> and 
{xpack-ref}/authorization.html[Configuring Role-based Access Control].

include::authorization/index.asciidoc[]
include::authorization/kibana-privileges.asciidoc[]
