[role="xpack"]
[[xpack-security]]
== Security

{xpack} security enables you to easily secure a cluster. With security, you can
password-protect your data as well as implement more advanced security measures
such as encrypting communications, role-based access control, IP filtering, and
auditing. For more information, see
{xpack-ref}/elasticsearch-security.html[Securing {es} and {kib}] and
<<using-kibana-with-security,Configuring Security in {kib}>>.

[float]
=== Users

You can create and manage users on the *Management* / *Security* / *Users* page.
You can also change their passwords and roles. For more information about
authentication and built-in users, see
{xpack-ref}/setting-up-authentication.html[Setting Up User Authentication].

[float]
=== Roles

You can manage roles on the *Management* / *Security* / *Roles* page, or use
{kib}'s <<role-management-api>>. For more information on configuring roles for
{kib} see <<xpack-security-authorization, {kib} Authorization>>.

For a more holistic overview of configuring roles for the entire stack,
see {xpack-ref}/authorization.html[Configuring Role-based Access Control].

[NOTE]
============================================================================
Managing roles that grant <<kibana-privileges>> using the {es} 
{ref}/security-api.html#security-role-apis[role management APIs] is not supported. Doing so will likely
cause Kibana's authorization to behave unexpectedly.
============================================================================

include::authorization/index.asciidoc[]
include::authorization/kibana-privileges.asciidoc[]
