import type { ReactElement } from 'react';
import type { QueryDslFieldLookup } from '@elastic/elasticsearch/lib/api/types';
import type { SearchResponseWarning } from '@kbn/search-response-warnings';
import type { GeoJsonProperties, Geometry, Position } from 'geojson';
import type { KibanaExecutionContext } from '@kbn/core/public';
import { type TimeRange } from '@kbn/es-query';
import type { DataView, SortDirectionNumeric } from '@kbn/data-plugin/common';
import type { Adapters } from '@kbn/inspector-plugin/common/adapters';
import { AbstractESSource } from '../es_source';
import { VECTOR_SHAPE_TYPE } from '../../../../common/constants';
import { ESDocField } from '../../fields/es_doc_field';
import type { DataRequestMeta, ESSearchSourceDescriptor, Timeslice, TooltipFeatureAction, VectorSourceRequestMeta } from '../../../../common/descriptor_types';
import type { ImmutableSourceProperty, SourceEditorArgs } from '../source';
import type { IField } from '../../fields/field';
import type { GetFeatureActionsArgs, GeoJsonWithMeta, IMvtVectorSource, SourceStatus } from '../vector_source';
import type { ITooltipProperty } from '../../tooltips/tooltip_property';
import type { DataRequest } from '../../util/data_request';
type ESSearchSourceSyncMeta = Pick<ESSearchSourceDescriptor, 'geoField' | 'filterByMapBounds' | 'sortField' | 'sortOrder' | 'scalingType' | 'topHitsGroupByTimeseries' | 'topHitsSplitField' | 'topHitsSize'>;
export declare function timerangeToTimeextent(timerange: TimeRange): Timeslice | undefined;
export declare const sourceTitle: string;
export declare class ESSearchSource extends AbstractESSource implements IMvtVectorSource {
    readonly _descriptor: Required<ESSearchSourceDescriptor>;
    protected readonly _tooltipFields: ESDocField[];
    static createDescriptor(descriptor: Partial<ESSearchSourceDescriptor>): Required<ESSearchSourceDescriptor>;
    constructor(descriptor: Partial<ESSearchSourceDescriptor>);
    getGeoFieldName(): string;
    renderSourceSettingsEditor(sourceEditorArgs: SourceEditorArgs): ReactElement<any> | null;
    getFields(): Promise<IField[]>;
    getFieldByName(fieldName: string): ESDocField;
    isMvt(): boolean;
    getImmutableProperties(): Promise<ImmutableSourceProperty[]>;
    _buildEsSort(): Array<Record<string, SortDirectionNumeric>>;
    _getTopHits(layerName: string, requestMeta: VectorSourceRequestMeta, registerCancelCallback: (callback: () => void) => void, inspectorAdapters: Adapters): Promise<{
        hits: any[];
        meta: {
            areResultsTrimmed: boolean;
            areEntitiesTrimmed: boolean;
            entityCount: any;
            totalEntities: any;
            warnings: import("@kbn/search-response-warnings/src/types").SearchResponseIncompleteWarning[];
        };
    }>;
    _getSearchHits(layerName: string, requestMeta: VectorSourceRequestMeta, registerCancelCallback: (callback: () => void) => void, inspectorAdapters: Adapters): Promise<{
        hits: any;
        meta: {
            resultsCount: any;
            areResultsTrimmed: boolean;
            timeExtent: Timeslice | undefined;
            isTimeExtentForTimeslice: boolean;
            warnings: import("@kbn/search-response-warnings/src/types").SearchResponseIncompleteWarning[];
        };
    }>;
    _isTopHits(): boolean;
    _getSourceIndexList(): Promise<string[]>;
    supportsFeatureEditing(): Promise<boolean>;
    _getNewFeatureFields(): Promise<Record<string, Record<string, string>>>;
    _isDrawingIndex(): Promise<boolean>;
    _hasSort(): boolean;
    getMaxResultWindow(): Promise<number>;
    isFieldAware(): boolean;
    getInspectorRequestIds(): string[];
    getGeoJsonWithMeta(layerName: string, requestMeta: VectorSourceRequestMeta, registerCancelCallback: (callback: () => void) => void, isRequestStillActive: () => boolean, inspectorAdapters: Adapters): Promise<GeoJsonWithMeta>;
    hasTooltipProperties(): boolean;
    _loadTooltipProperties(docId: string | number, index: string, indexPattern: DataView, executionContext: KibanaExecutionContext): Promise<Record<string, string>>;
    _getTooltipPropertyNames(): string[];
    getTooltipProperties(properties: GeoJsonProperties, executionContext: KibanaExecutionContext): Promise<ITooltipProperty[]>;
    isFilterByMapBounds(): boolean;
    getLeftJoinFields(): Promise<IField[]>;
    getSupportedShapeTypes(): Promise<VECTOR_SHAPE_TYPE[]>;
    getSourceStatus(sourceDataRequest?: DataRequest): SourceStatus;
    getSyncMeta(): ESSearchSourceSyncMeta;
    _getPreIndexedShape(properties: GeoJsonProperties): Promise<QueryDslFieldLookup | null>;
    supportsJoins(): boolean;
    _getEditableIndex(): Promise<string>;
    addFeature(geometry: Geometry | Position[]): Promise<void>;
    deleteFeature(featureId: string): Promise<void>;
    getTileSourceLayer(): string;
    getTileUrl(requestMeta: VectorSourceRequestMeta, refreshToken: string, hasLabels: boolean, buffer: number): Promise<string>;
    getTimesliceMaskFieldName(): Promise<string | null>;
    getUpdateDueToTimeslice(prevMeta: DataRequestMeta, timeslice?: Timeslice): boolean;
    private _getFeaturesCountRequestId;
    canLoadAllDocuments(layerName: string, requestMeta: VectorSourceRequestMeta, registerCancelCallback: (callback: () => void) => void, inspectorAdapters: Adapters, onWarning: (warning: SearchResponseWarning) => void): Promise<boolean>;
    getFeatureActions({ addFilters, geoFieldNames, getActionContext, getFilterActions, mbFeature, onClose, }: GetFeatureActionsArgs): TooltipFeatureAction[];
}
export {};
