import type { AlertingAuthorizationFilterOpts } from '../../authorization';
export { systemConnectorActionRefPrefix, preconfiguredConnectorActionRefPrefix, } from '../../../common';
export declare const extractedSavedObjectParamReferenceNamePrefix = "param:";
export declare const alertingAuthorizationFilterOpts: AlertingAuthorizationFilterOpts;
export declare const MAX_RULES_NUMBER_FOR_BULK_OPERATION = 10000;
export declare const API_KEY_GENERATE_CONCURRENCY = 50;
export declare const RULE_TYPE_CHECKS_CONCURRENCY = 50;
export declare const MIN_BULK_CREATE_BATCH_SIZE = 10;
export declare const DEFAULT_BULK_CREATE_BATCH_SIZE = 100;
export declare const MAX_BULK_CREATE_BATCH_SIZE = 500;
