import type { TypeOf } from '@kbn/config-schema';
import type { KibanaRequest, RequestHandler } from '@kbn/core/server';
import { type AgentClient } from '../../services/agents';
import type { GetAgentPoliciesRequestSchema, GetOneAgentPolicyRequestSchema, CreateAgentPolicyRequestSchema, UpdateAgentPolicyRequestSchema, CopyAgentPolicyRequestSchema, DeleteAgentPolicyRequestSchema, GetFullAgentPolicyRequestSchema, GetK8sManifestRequestSchema, FleetRequestHandler, BulkGetAgentPoliciesRequestSchema, AgentPolicy, FleetRequestHandlerContext, GetAgentPolicyOutputsRequestSchema, GetListAgentPolicyOutputsRequestSchema, GetAutoUpgradeAgentsStatusRequestSchema, CreateAgentAndPackagePolicyRequestSchema, RunAgentPolicyRevisionsCleanupTaskRequestSchema } from '../../types';
export declare function populateAssignedAgentsCount(agentClient: AgentClient, agentPolicies: AgentPolicy[]): Promise<void>;
export declare function getAuthorizedSpacesWithAgentPoliciesAllPrivileges(request: KibanaRequest, context: FleetRequestHandlerContext): Promise<string[]>;
export declare const getAgentPoliciesHandler: FleetRequestHandler<undefined, TypeOf<typeof GetAgentPoliciesRequestSchema.query>>;
export declare const bulkGetAgentPoliciesHandler: FleetRequestHandler<undefined, TypeOf<typeof BulkGetAgentPoliciesRequestSchema.query>, TypeOf<typeof BulkGetAgentPoliciesRequestSchema.body>>;
export declare const getOneAgentPolicyHandler: FleetRequestHandler<TypeOf<typeof GetOneAgentPolicyRequestSchema.params>, TypeOf<typeof GetOneAgentPolicyRequestSchema.query>>;
export declare const getAutoUpgradeAgentsStatusHandler: FleetRequestHandler<TypeOf<typeof GetAutoUpgradeAgentsStatusRequestSchema.params>, undefined>;
export declare const createAgentPolicyHandler: FleetRequestHandler<undefined, TypeOf<typeof CreateAgentPolicyRequestSchema.query>, TypeOf<typeof CreateAgentPolicyRequestSchema.body>>;
export declare const createAgentAndPackagePoliciesHandler: FleetRequestHandler<undefined, TypeOf<typeof CreateAgentAndPackagePolicyRequestSchema.query>, TypeOf<typeof CreateAgentAndPackagePolicyRequestSchema.body>>;
export declare const updateAgentPolicyHandler: FleetRequestHandler<TypeOf<typeof UpdateAgentPolicyRequestSchema.params>, TypeOf<typeof UpdateAgentPolicyRequestSchema.query>, TypeOf<typeof UpdateAgentPolicyRequestSchema.body>>;
export declare const copyAgentPolicyHandler: RequestHandler<TypeOf<typeof CopyAgentPolicyRequestSchema.params>, TypeOf<typeof CopyAgentPolicyRequestSchema.query>, TypeOf<typeof CopyAgentPolicyRequestSchema.body>>;
export declare const deleteAgentPoliciesHandler: RequestHandler<unknown, unknown, TypeOf<typeof DeleteAgentPolicyRequestSchema.body>>;
export declare const getFullAgentPolicy: FleetRequestHandler<TypeOf<typeof GetFullAgentPolicyRequestSchema.params>, TypeOf<typeof GetFullAgentPolicyRequestSchema.query>>;
export declare const downloadFullAgentPolicy: FleetRequestHandler<TypeOf<typeof GetFullAgentPolicyRequestSchema.params>, TypeOf<typeof GetFullAgentPolicyRequestSchema.query>>;
export declare const getK8sManifest: FleetRequestHandler<undefined, TypeOf<typeof GetK8sManifestRequestSchema.query>>;
export declare const downloadK8sManifest: FleetRequestHandler<undefined, TypeOf<typeof GetK8sManifestRequestSchema.query>>;
export declare const GetAgentPolicyOutputsHandler: FleetRequestHandler<TypeOf<typeof GetAgentPolicyOutputsRequestSchema.params>, undefined>;
export declare const GetListAgentPolicyOutputsHandler: FleetRequestHandler<undefined, undefined, TypeOf<typeof GetListAgentPolicyOutputsRequestSchema.body>>;
export declare const RunAgentPolicyRevisionsCleanupTaskHandler: FleetRequestHandler<undefined, undefined, TypeOf<typeof RunAgentPolicyRevisionsCleanupTaskRequestSchema.body>>;
