[[add-parameters-api]]
== Add Parameters API
++++
<titleabbrev>Add Parameters</titleabbrev>
++++

Adds one or more parameters to the system.

=== {api-request-title}

`POST <your-api-host>/api/synthetics/params`

=== {api-prereq-title}

To use this API, you must have appropriate permissions for adding parameters.

[[parameters-add-request-body]]
==== Request body

The request body can contain either a single parameter object or an array of parameter objects. The parameter object schema includes the following attributes:

`key`::
(Required, string) The key of the parameter.

`value`::
(Required, string) The value associated with the parameter.

`description`::
(Optional, string) A description of the parameter.

`tags`::
(Optional, array of strings) An array of tags to categorize the parameter.

`share_across_spaces`::
(Optional, boolean) Whether the parameter should be shared across spaces.

When adding a single parameter, provide a single object. When adding multiple parameters, provide an array of parameter objects.

[[parameters-add-example]]
==== Example

Here are examples of POST requests to add parameters, either as a single parameter or as an array of parameters:

To add a single parameter:

[source,sh]
--------------------------------------------------
POST /api/synthetics/params
{
  "key": "api_key",
  "value": "your-api-key-value",
  "description": "API Key for authentication",
  "tags": ["authentication", "security"],
  "share_across_spaces": true
}
--------------------------------------------------

To add multiple parameters:

[source,sh]
--------------------------------------------------
POST /api/synthetics/params
[
  {
    "key": "param1",
    "value": "value1"
  },
  {
    "key": "param2",
    "value": "value2"
  }
]
--------------------------------------------------

The API returns a response based on the request. If you added a single parameter, it will return a single parameter object. If you added multiple parameters, it will return an array of parameter objects.

This example provides documentation for adding parameters, whether as a single parameter or an array of parameters, using the specified schema. You can replace `<your-api-host>` with the actual host where your API is available.
