/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Apply PND Tuning API endpoint
 *   version: 1
 */

import { z, lazySchema } from '@kbn/zod/v4';
import { isNonEmptyString } from '@kbn/zod-helpers/v4';

import { PndTuningChange } from '../components/tuning.gen';

export const ApplyTuningRequestParams = lazySchema(() =>
  z.object({
    /**
     * Id of the tuning proposal being applied
     */
    proposalId: z.string().max(1024),
  })
);
export type ApplyTuningRequestParams = z.infer<typeof ApplyTuningRequestParams>;
export type ApplyTuningRequestParamsInput = z.input<typeof ApplyTuningRequestParams>;

export const ApplyTuningRequestBody = lazySchema(() =>
  z.object({
    /**
      * Detection rule id. LLM-authored in the draft, so the approval dialog prefills it in an editable field and the analyst confirms it — otherwise `_apply` 404s on a rule the model invented.

      */
    id: z.string().max(1024).optional(),
    /**
     * Detection rule `rule_id`, as an alternative to `id`
     */
    rule_id: z.string().max(1024).optional(),
    change: PndTuningChange.optional(),
    /**
     * Required, non-empty human rationale for applying the tuning
     */
    rationale: z.string().max(2000).superRefine(isNonEmptyString),
  })
);
export type ApplyTuningRequestBody = z.infer<typeof ApplyTuningRequestBody>;
export type ApplyTuningRequestBodyInput = z.input<typeof ApplyTuningRequestBody>;

export const ApplyTuningResponse = lazySchema(() =>
  z.object({
    proposalId: z.string().max(1024),
    /**
     * Detection rule id that was updated
     */
    ruleId: z.string().max(1024),
    applied: z.boolean(),
  })
);
export type ApplyTuningResponse = z.infer<typeof ApplyTuningResponse>;
