[role="xpack"]
[[spaces-api-get-shareable-references]]
=== Get shareable references API
++++
<titleabbrev>Get shareable references</titleabbrev>
++++

experimental[] Get shareable references.

Collects references and spaces context for saved objects.

[[spaces-api-get-shareable-references-request]]
==== {api-request-title}

`POST <kibana host>:<port>/api/spaces/_get_shareable_references`

[[spaces-api-get-shareable-references-request-body]]
==== {api-request-body-title}

`objects`::
  (Required, object array) The saved objects to collect outbound references for.
+
.Properties of `objects`
[%collapsible%open]
=====
  `type`:::
    (Required, string) The saved object type.

  `id`:::
    (Required, string) The saved object ID.
=====

[role="child_attributes"]
[[spaces-api-get-shareable-references-response-body]]
==== {api-response-body-title}

`objects`::
  (object array) The returned input object or one of its references, with additional context.
+
.Properties of `objects`
[%collapsible%open]
=====
  `type`:::
    (string) The saved object type.

  `id`:::
    (string) The saved object ID.

  `originId`:::
    (string) The origin ID of the referenced object (if it has one).

  `inboundReferences`:::
    (object array) References to this object.
+
NOTE: This does not contain _all inbound references everywhere_, it only contains inbound references to this object within the scope of this operation.
+
.Properties of `inboundReferences`
[%collapsible%open]
======
    `type`::::
      (string) The type of the object that has the inbound reference.

    `id`::::
      (string) The ID of the object that has the inbound reference.

    `name`::::
      (string) The name of the inbound reference.
======

  `spaces`:::
    (string array) The space(s) that the referenced saved object exists in.

  `spacesWithMatchingAliases`:::
    (string array) The space(s) that legacy URL aliases matching this type/id exist in. (if there are any)

  `spacesWithMatchingOrigins`:::
    (string array) The space(s) that objects matching this origin exist in (including this one). (if there are any)

  `isMissing`:::
    (boolean) Whether or not this object or reference is missing.
=====
