[[alerts-api-health]]
=== Get alert framework health API
++++
<titleabbrev>Get alert framework health</titleabbrev>
++++

Retrieve the Alerting framework health status.

[[alerts-api-health-request]]
==== Request

`GET <kibana host>:<port>/api/alerts/_health`

[[alerts-api-health-codes]]
==== Response code

`200`::
    Indicates a successful call.

[[alerts-api-health-example]]
==== Example

Retrieve the health status of the alert framework:

[source,sh]
--------------------------------------------------
$ curl -X GET api/alerts/_health
--------------------------------------------------
// KIBANA

The API returns the following:

[source,sh]
--------------------------------------------------
{
   "isSufficientlySecure":true,
   "hasPermanentEncryptionKey":true,
   "alertingFrameworkHeath":{
      "decryptionHealth":{
         "status":"ok",
         "timestamp":"2021-02-10T23:35:04.949Z"
      },
      "executionHealth":{
         "status":"ok",
         "timestamp":"2021-02-10T23:35:04.949Z"
      },
      "readHealth":{
         "status":"ok",
         "timestamp":"2021-02-10T23:35:04.949Z"
      }
   }
}
--------------------------------------------------

The health API response contains the following properties:

[cols="2*<"]
|===

| `isSufficientlySecure`
| Returns`false` if security is enabled, but TLS is not.

| `hasPermanentEncryptionKey`
| Return the state true if Encryption Saved Object plugin has a permanent encryption Key

| `alertingFrameworkHeath`
| This state property has three substates that identify the health of the alerting framework API: `decryptionHealth`, `executionHealth`, and `readHealth`.

|===

alertingFrameworkHeath itself consists from the following properties:

[cols="2*<"]
|===

| `decryptionHealth`
| Returns the timestamp and status  of the alert decryption: `ok`, `warn` or `error` .

| `executionHealth`
| Return the latest status `ok`, `warn` or `error` with the timestamp, which identify if the alerts executions have results with the errors.

| `readHealth`
| Return the latest status `ok`, `warn` or `error` with the timestamp, which identify if the alerts read events have any errors.

|===
