[[alerts-api-update]]
=== Update alert API
++++
<titleabbrev>Update alert</titleabbrev>
++++

Update the attributes for existing {kib} alerts.

[[alerts-api-update-request]]
==== Request

`PUT <kibana host>:<port>/api/alerts/alert/<id>`

[[alerts-api-update-path-params]]
==== Path parameters

`id`::
  (Required, string) The alert ID to update.

[[alerts-api-update-request-body]]
==== Request body

`name`::
  (Required, string) A name to reference and search in the future.

`tags`::
  (Optional, string array) A list of keywords to reference and search in the future.

`schedule`::
  (Required, object) The schedule specifying when this alert should be run, using one of the available schedule formats specified under _Schedule Formats_ below.

`throttle`::
  (Optional, string) A Duration specifying how often this alert should fire the same actions. This will prevent the alert from sending out the same notification over and over. For example, if an alert with a `schedule` of 1 minute stays in a triggered state for 90 minutes, setting a `throttle` of `10m` or `1h` will prevent it from sending 90 notifications over this period.

`notifyWhen`::
  (Required, string) Defines the conditions for notifications thottling from the three available option types 'onActionGroupChange', 'onActiveAlert', 'onThrottleInterval'.

`params`::
  (Required, object) The parameters to pass in to the alert type executor `params` value. This will also validate against the alert type params validator if defined.

`actions`::
  (Optional, object array) Array of the following:<br> - `group` (string): We support grouping actions in the scenario of escalations or different types of alert instances. If you don't need this, feel free to use `default` as a value.<br>- `id` (string): The id of the action saved object to execute.<br>- `params` (object): The map to the `params` the action type will receive. In order to help apply context to strings, we handle them as mustache templates and pass in a default set of context. (see templating actions).

[[alerts-api-update-errors-codes]]
==== Response code

`200`::
    Indicates a successful call.

[[alerts-api-update-example]]
==== Example

Update an existing alert with ID `ac4e6b90-6be7-11eb-ba0d-9b1c1f912d74`, with a different name:

[source,sh]
--------------------------------------------------
$ curl -X PUT api/alerts/alert/ac4e6b90-6be7-11eb-ba0d-9b1c1f912d74

{
  "notifyWhen": "onActionGroupChange",
  "params": {
    "aggType": "avg",
  },
  "schedule": {
    "interval": "1m"
  },
  "actions": [],
  "tags": [],
  "name": "new name",
  "throttle": null,
}
--------------------------------------------------
// KIBANA

The API returns the following:

[source,sh]
--------------------------------------------------
{
  "id": "ac4e6b90-6be7-11eb-ba0d-9b1c1f912d74",
  "notifyWhen": "onActionGroupChange",
  "params": {
    "aggType": "avg",
  },
  "consumer": "alerts",
  "alertTypeId": "test.alert.type",
  "schedule": {
    "interval": "1m"
  },
  "actions": [],
  "tags": [],
  "name": "new name",
  "enabled": true,
  "throttle": null,
  "apiKeyOwner": "elastic",
  "createdBy": "elastic",
  "updatedBy": "elastic",
  "muteAll": false,
  "mutedInstanceIds": [],
  "updatedAt": "2021-02-10T05:37:19.086Z",
  "createdAt": "2021-02-10T05:37:19.086Z",
  "scheduledTaskId": "0b092d90-6b62-11eb-9e0d-85d233e3ee35",
  "executionStatus": {
    "lastExecutionDate": "2021-02-10T17:55:14.262Z",
    "status": "ok"
  }
}
--------------------------------------------------
