import type { CoreSetup, CoreStart, Plugin, PluginInitializerContext } from '@kbn/core/public';
import type { ObservabilityAIAssistantPublicStart } from '@kbn/observability-ai-assistant-plugin/public';
import type { UnifiedSearchPublicPluginStart } from '@kbn/unified-search-plugin/public';
import type { ManagementSetup } from '@kbn/management-plugin/public';
import type { LocatorPublic, SharePluginSetup, SharePluginStart } from '@kbn/share-plugin/public';
import type { DataPublicPluginStart } from '@kbn/data-plugin/public';
import type { HomePublicPluginSetup } from '@kbn/home-plugin/public';
import type { EmbeddableSetup, EmbeddableStart } from '@kbn/embeddable-plugin/public';
import type { SpacesPluginStart } from '@kbn/spaces-plugin/public';
import type { LensPublicStart } from '@kbn/lens-plugin/public';
import type { UiActionsSetup, UiActionsStart } from '@kbn/ui-actions-plugin/public';
import type { LicenseManagementUIPluginSetup } from '@kbn/license-management-plugin/public';
import type { LicensingPluginSetup, LicensingPluginStart } from '@kbn/licensing-plugin/public';
import type { SecurityPluginStart } from '@kbn/security-plugin/public';
import type { SavedObjectsManagementPluginStart } from '@kbn/saved-objects-management-plugin/public';
import type { ContentManagementPublicStart } from '@kbn/content-management-plugin/public';
import type { MapsStartApi, MapsSetupApi } from '@kbn/maps-plugin/public';
import type { TriggersAndActionsUIPublicPluginSetup, TriggersAndActionsUIPublicPluginStart } from '@kbn/triggers-actions-ui-plugin/public';
import type { DataVisualizerPluginStart } from '@kbn/data-visualizer-plugin/public';
import type { PluginSetupContract as AlertingSetup } from '@kbn/alerting-plugin/public';
import type { UsageCollectionSetup } from '@kbn/usage-collection-plugin/public';
import type { FieldFormatsSetup } from '@kbn/field-formats-plugin/public';
import type { DashboardStart } from '@kbn/dashboard-plugin/public';
import type { ChartsPluginStart } from '@kbn/charts-plugin/public';
import type { CasesPublicSetup, CasesPublicStart } from '@kbn/cases-plugin/public';
import type { SavedSearchPublicPluginStart } from '@kbn/saved-search-plugin/public';
import type { PresentationUtilPluginStart } from '@kbn/presentation-util-plugin/public';
import type { DataViewEditorStart } from '@kbn/data-view-editor-plugin/public';
import type { FieldFormatsRegistry } from '@kbn/field-formats-plugin/common';
import type { FieldsMetadataPublicStart } from '@kbn/fields-metadata-plugin/public';
import type { FileUploadPluginStart } from '@kbn/file-upload-plugin/public';
import type { KqlPluginStart } from '@kbn/kql/public';
import type { CPSPluginStart } from '@kbn/cps/public/types';
import type { MlLocatorParams } from './locator';
import { type ConfigSchema } from '../common/constants/app';
import type { ElasticModels } from './application/services/elastic_models_service';
import type { MlApi } from './application/services/ml_api_service';
import type { AnomalySwimLane } from './shared_components';
import type { MlManagementLocatorInternal } from './locator/ml_management_locator';
import type { ITelemetryClient } from './application/services/telemetry/types';
export interface MlStartDependencies {
    cases?: CasesPublicStart;
    charts: ChartsPluginStart;
    contentManagement: ContentManagementPublicStart;
    dashboard: DashboardStart;
    data: DataPublicPluginStart;
    dataViewEditor: DataViewEditorStart;
    dataVisualizer: DataVisualizerPluginStart;
    embeddable: EmbeddableStart;
    fieldFormats: FieldFormatsRegistry;
    lens: LensPublicStart;
    licensing: LicensingPluginStart;
    maps?: MapsStartApi;
    observabilityAIAssistant?: ObservabilityAIAssistantPublicStart;
    presentationUtil: PresentationUtilPluginStart;
    savedObjectsManagement: SavedObjectsManagementPluginStart;
    savedSearch: SavedSearchPublicPluginStart;
    security: SecurityPluginStart;
    share: SharePluginStart;
    spaces?: SpacesPluginStart;
    triggersActionsUi?: TriggersAndActionsUIPublicPluginStart;
    uiActions: UiActionsStart;
    unifiedSearch: UnifiedSearchPublicPluginStart;
    kql: KqlPluginStart;
    telemetry: ITelemetryClient;
    fieldsMetadata: FieldsMetadataPublicStart;
    fileUpload: FileUploadPluginStart;
    cps: CPSPluginStart;
}
export interface MlSetupDependencies {
    alerting?: AlertingSetup;
    cases?: CasesPublicSetup;
    embeddable: EmbeddableSetup;
    fieldFormats: FieldFormatsSetup;
    home?: HomePublicPluginSetup;
    kibanaVersion: string;
    licenseManagement?: LicenseManagementUIPluginSetup;
    licensing: LicensingPluginSetup;
    management?: ManagementSetup;
    maps?: MapsSetupApi;
    share: SharePluginSetup;
    triggersActionsUi?: TriggersAndActionsUIPublicPluginSetup;
    uiActions: UiActionsSetup;
    usageCollection?: UsageCollectionSetup;
}
export type MlCoreSetup = CoreSetup<MlStartDependencies, MlPluginStart>;
export declare class MlPlugin implements Plugin<MlPluginSetup, MlPluginStart> {
    private initializerContext;
    private appUpdater$;
    private locator;
    private managementLocator;
    private sharedMlServices;
    private isServerless;
    private enabledFeatures;
    private experimentalFeatures;
    private nlpSettings;
    private telemetry;
    constructor(initializerContext: PluginInitializerContext<ConfigSchema>);
    setup(core: MlCoreSetup, pluginsSetup: MlSetupDependencies): {
        locator?: LocatorPublic<MlLocatorParams>;
        managementLocator?: MlManagementLocatorInternal;
        elasticModels?: ElasticModels;
    };
    start(core: CoreStart, deps: MlStartDependencies): {
        locator?: LocatorPublic<MlLocatorParams>;
        managementLocator?: MlManagementLocatorInternal;
        elasticModels?: ElasticModels;
        mlApi?: MlApi;
        components: {
            AnomalySwimLane: typeof AnomalySwimLane;
        };
    };
    stop(): void;
}
export type MlPluginSetup = ReturnType<MlPlugin['setup']>;
export type MlPluginStart = ReturnType<MlPlugin['start']>;
