ruby "1.9.3", :engine => 'jruby', :engine_version => '1.7.13'

source "https://rubygems.org"

gem 'sinatra', :require => 'sinatra/base'
gem 'sinatra-contrib'
gem 'puma'
gem 'warbler'
gem 'elasticsearch'
gem 'rack-reverse-proxy', :require => 'rack/reverse_proxy'
