/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Risk Scoring API
 *   version: 2023-10-31
 */

import { z, lazySchema } from '@kbn/zod/v4';

export const CleanUpRiskEngineErrorResponse = lazySchema(() =>
  z.object({
    cleanup_successful: z.boolean(),
    errors: z.array(
      z.object({
        seq: z.number().int(),
        error: z.string(),
      })
    ),
  })
);
export type CleanUpRiskEngineErrorResponse = z.infer<typeof CleanUpRiskEngineErrorResponse>;

export const CleanUpRiskEngineResponse = lazySchema(() =>
  z.object({
    cleanup_successful: z.boolean().optional(),
  })
);
export type CleanUpRiskEngineResponse = z.infer<typeof CleanUpRiskEngineResponse>;
