/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Risk Score History API
 *   version: 1
 */

import { z, lazySchema } from '@kbn/zod/v4';
import { BooleanFromString } from '@kbn/zod-helpers/v4';

import {
  IdentifierType,
  EntityRiskLevels,
  RiskScoreInput,
  RiskScoreModifier,
} from '../common/common.gen';
import { AssetCriticalityLevel } from '../asset_criticality/common.gen';

export const RiskScoreHistoryEntry = lazySchema(() =>
  z.object({
    '@timestamp': z.string().max(33).datetime(),
    calculated_score_norm: z.number().min(0).max(100),
    calculated_level: EntityRiskLevels,
    calculated_score: z.number().optional(),
    score_type: z.enum(['base', 'propagated', 'resolution']).optional(),
    category_1_score: z.number().optional(),
    category_1_count: z.number().int().optional(),
    /**
     * Present only when requested with `include_contributions=true`.
     */
    inputs: z.array(RiskScoreInput).optional(),
    /**
     * Present only when requested with `include_contributions=true`.
     */
    modifiers: z.array(RiskScoreModifier).optional(),
    category_2_score: z.number().optional(),
    category_2_count: z.number().int().optional(),
    criticality_level: AssetCriticalityLevel.optional(),
  })
);
export type RiskScoreHistoryEntry = z.infer<typeof RiskScoreHistoryEntry>;

export const RiskScoreHistoryResponse = lazySchema(() =>
  z.object({
    entity_id: z.string().max(1000),
    entity_type: IdentifierType,
    entries: z.array(RiskScoreHistoryEntry),
  })
);
export type RiskScoreHistoryResponse = z.infer<typeof RiskScoreHistoryResponse>;

export const GetRiskScoreHistoryRequestQuery = lazySchema(() =>
  z.object({
    /**
     * The type of entity to retrieve history for.
     */
    entity_type: IdentifierType,
    /**
     * The identifier of the entity to retrieve history for.
     */
    entity_id: z.string().max(1000),
    /**
     * Start of the time range, in date-math syntax. Defaults to 90 days ago.
     */
    from: z.string().max(100).optional().default('now-90d'),
    /**
     * End of the time range, in date-math syntax. Defaults to now.
     */
    to: z.string().max(100).optional().default('now'),
    /**
     * Filter entries by the type of score recorded (`base`, `propagated`, or `resolution`).
     */
    score_type: z.enum(['base', 'propagated', 'resolution']).optional(),
    /**
     * Maximum number of history entries to return per request.
     */
    page_size: z.coerce.number().int().min(1).max(1000).optional().default(100),
    /**
     * When true, each entry also includes the contributions recorded for that scoring run (`inputs`, `modifiers`, category 2 fields, and `criticality_level`), when present on the underlying document.
     */
    include_contributions: BooleanFromString.optional().default(false),
  })
);
export type GetRiskScoreHistoryRequestQuery = z.infer<typeof GetRiskScoreHistoryRequestQuery>;
export type GetRiskScoreHistoryRequestQueryInput = z.input<typeof GetRiskScoreHistoryRequestQuery>;

export const GetRiskScoreHistoryResponse = lazySchema(() => RiskScoreHistoryResponse);
export type GetRiskScoreHistoryResponse = z.infer<typeof GetRiskScoreHistoryResponse>;
