[role="xpack"]
[[xpack-security-authorization]]
=== Authorization

Authorizing users to use {kib} in most configurations is as simple as assigning the user
either the `kibana_user` or `kibana_dashboard_only_user` reserved role. If you're running 
a single tenant of {kib} against your {es} cluster, this is entirely sufficient and no other 
action is required.

==== Multi-tenant {kib}

When running multiple tenants of {kib}, by changing the `kibana.index` in your `kibana.yml`, you 
must create custom roles which authorize the user for that specific tenant. To do so, you can use
either the *Management / Security / Roles* page in {kib} or {kib}'s <<role-management-api>>
to assign a specific <<kibana-privileges, Kibana privilege>> at that tenant. After creating the
custom role, you should assign this role to the user(s) that you wish to have access.

==== Legacy roles

Prior to {kib} 6.4, it was required to give {kib} users index privileges to the `kibana.index`
in {es}. This approach is deprecated starting in 6.4, and you will need to switch to using
<<kibana-privileges>> before 7.0. When a user logs into {kib} and we detect that they're using
a legacy role, the following will be logged to you {kib} logs:

[source,js]
----------------------------------
<username> relies on index privileges on the Kibana index. This is deprecated and will be removed in Kibana 7.0
----------------------------------

To disable legacy roles from being authorized in {kib} set `xpack.security.authorization.legacyFallback` to `false`
in your `kibana.yml`.
