import type { PluginConfigDescriptor, PluginInitializerContext } from '@kbn/core/server';
import { type ConfigSchema } from '../common/constants/app';
export type { MlPluginSetup, MlPluginStart } from './plugin';
export type { DatafeedStats as MlDatafeedStats } from '@kbn/ml-common-types/anomaly_detection_jobs/datafeed_stats';
export type { Job as MlJob } from '@kbn/ml-common-types/anomaly_detection_jobs/job';
export type { MlSummaryJob, SummaryJobState as MlSummaryJobState, } from '@kbn/ml-common-types/anomaly_detection_jobs/summary_job';
export type { AlertingService as MlAlertingService, AnomalyDetectors as MlAnomalyDetectors, JobService as MlJobService, MlSystem as MlMlSystem, Modules as MlModules, ResultsService as MlResultsService, TrainedModels as MlTrainedModels, } from './shared';
export { UnknownMLCapabilitiesError, InsufficientMLCapabilities, MLPrivilegesUninitialized, } from './shared';
export declare const config: PluginConfigDescriptor<ConfigSchema>;
export declare const plugin: (ctx: PluginInitializerContext<ConfigSchema>) => Promise<import("./plugin").MlServerPlugin>;
