[[data-views-api-create]]
=== Create data view API
++++
<titleabbrev>Create data view</titleabbrev>
++++

experimental[] Create data views.


[[data-views-api-create-request]]
==== Request

`POST <kibana host>:<port>/api/data_views/data_view`

`POST <kibana host>:<port>/s/<space_id>/api/data_views/data_view`


[[data-views-api-create-path-params]]
==== Path parameters

`space_id`::
  (Optional, string) An identifier for the space. If `space_id` is not provided in the URL, the default space is used.


[[data-views-api-create-body-params]]
==== Request body

`override`:: (Optional, boolean) Overrides an existing data view if a
data view with the provided title already exists. The default is `false`.

`refresh_fields`:: (Optional, boolean) Reloads data view fields after
the data view is stored. The default is `false`.

`data_view`:: (Required, object) The data view object. All fields are optional.


[[data-views-api-create-request-codes]]
==== Response code

`200`::
    Indicates a successful call.


[[data-views-api-create-example]]
==== Examples

Create a data view to view data in the `logstash-*` indices:

[source,sh]
--------------------------------------------------
$ curl -X POST api/data_views/data_view
{
  "data_view": {
     "title": "logstash-*",
     "name": "My Logstash Data View"
  }
}
--------------------------------------------------
// KIBANA

Customize the creation behavior:

[source,sh]
--------------------------------------------------
$ curl -X POST api/data_views/data_view
{
  "override": false,
  "refresh_fields": true,
  "data_view": {
     "title": "logstash-*",
     "name": "My Logstash Data View"
  }
}
--------------------------------------------------
// KIBANA

At creation, all data view fields are optional:

[source,sh]
--------------------------------------------------
$ curl -X POST api/data_views/data_view
{
  "data_view": {
      "id": "...",
      "version": "...",
      "title": "...",
      "name": "...",
      "type": "...",
      "timeFieldName": "...",
      "sourceFilters": [],
      "typeMeta": {},
      "fieldAttrs": {},
      "runtimeFieldMap": {}
      "allowNoIndex": "..."
    }
}
--------------------------------------------------
// KIBANA

The API returns the data view object:

[source,sh]
--------------------------------------------------
{
    "data_view": {...}
}
--------------------------------------------------

[[data-views-api-path-parameters]]

==== Path Parameters

`title`::
(Optional, string) Comma-separated list of data streams, indices, and aliases to search. Supports wildcards
(`*`).

`name`::
(Optional, string) Human readable name to differentiate the data view.

`id`::
(Optional, string) Saved object ID.

`version`::
(Optional, string) Saved object version.

`type`::
(Optional, string) When set to `rollup`, this is used to identify rollup data views.

`typeMeta`::
(Optional, object) When using rollup indices, this contains the field list for the rollup-specific
data view API endpoints.

`timeFieldName`::
(Optional, string) Timestamp field name, for time-based data views.

`sourceFilters`::
(Optional, string[]) Array of filters to hide fields in Kibana.

`fieldAttrs`::
(Optional, object) Map of field attributes by field name. See
{kibana-ref}/data-views-fields-api-update.html[Update data view fields API].

`runtimeFieldMap`::
(Optional, object) Map of runtime field definitions by field name. See
{kibana-ref}/data-views-runtime-field-api-create.html[Create runtime field API].

`fieldFormatMap`::
(Optional, object) Map field formats by field name.
+
.Properties of `fieldFormatMap` objects
[%collapsible%open]
=====
`[fieldName]`::
(Optional, object) Name of the field in the data view to map the format.
+
.Properties of `[fieldName]`
[%collapsible%open]
=====
`id`::
(Required, string) Name of the field data type. See {ref}/mapping-types.html[Field data types].

`params`::
(Optional, object) Formatting parameters, such as the pattern by which to format numbers and dates.
=====

`allowNoIndex`::
(Optional, boolean) Allows the data view to exist before data is present.

`namespaces`::
(Optional, string[]) Array of namespace IDs
