[[data-views-api-delete]]
=== Delete data view API
++++
<titleabbrev>Delete data view</titleabbrev>
++++

experimental[] Delete data views.

WARNING: Once you delete a data view, _it cannot be recovered_.

[float]
[[data-views-api-delete-request]]
==== Request

`DELETE <kibana host>:<port>/api/data_views/data_view/<id>`

`DELETE <kibana host>:<port>/s/<space_id>/api/data_views/data_view/<id>`

[float]
[[data-views-api-delete-path-params]]
==== Path parameters

`space_id`::
  (Optional, string) An identifier for the space. If `space_id` is not provided in the URL, the default space is used.

`id`::
  (Required, string) The ID of the data view you want to delete.

[float]
[[data-views-api-delete-response-codes]]
==== Response code

`200`::
  Indicates that data view is deleted. Returns an empty response body. 

[float]
==== Example

Delete a data view object with the `my-view` ID:

[source,sh]
--------------------------------------------------
$ curl -X DELETE api/data_views/data_view/my-view
--------------------------------------------------
// KIBANA

[discrete]
=== Delete data view API (deprecated)

[float]
[[data-views-api-delete-request-deprecated]]
==== Request

`DELETE <kibana host>:<port>/api/index_patterns/index_pattern/<id>`

`DELETE <kibana host>:<port>/s/<space_id>/api/index_patterns/index_pattern/<id>`

[float]
[[data-views-api-delete-path-params-deprecated]]
==== Path parameters

`space_id`::
  (Optional, string) An identifier for the space. If `space_id` is not provided in the URL, the default space is used.

`id`::
  (Required, string) The ID of the data view you want to delete.

[float]
[[data-views-api-delete-response-codes-deprecated]]
==== Response code

`200`::
  Indicates that data view is deleted. Returns an empty response body. 

[float]
==== Example

Delete a data view object with the `my-pattern` ID:

[source,sh]
--------------------------------------------------
$ curl -X DELETE api/index_patterns/index_pattern/my-pattern
--------------------------------------------------
// KIBANA
