[[data-table]]
=== Data table

The nested structure of Elasticsearch responses is flattened into a table.
Multiple tables can be displayed by configuring a bucket as a "Split table".

The table visualization has support for bucket aggregations beyond other visualizations:

{ref}/search-aggregations-bucket-geohashgrid-aggregation.html[Geohash]:: Displays points based on a geohash.

{ref}/search-aggregations-bucket-geotilegrid-aggregation.html[Geotile]:: Groups points based on web map tiling.

Once you've specified a bucket type aggregation, you can define sub-buckets to refine the visualization.

. To define a sub-bucket, click *+ Add*.

. Choose *Split rows* or *Split table*.

. From the list of types, select an aggregation.

. In the *Custom Label* field, enter a label name.

. To display customization options for your metrics or bucket aggregations, click *Advanced*.
* *Exclude Pattern* - Specifies a pattern in this field to exclude from the results.
* *Include Pattern* - Specifies a pattern in this field to include in the results.
include::json-input.asciidoc[]

To make changes to the table, select *Options*, then change the following options:

* *Per Page* - Controls the pagination of the table. The default value is ten rows per page.
* *Show metrics for every bucket/level* - Displays the intermediate results for each bucket aggregation.
* *Show partial rows* - Displays a row even when there is no result.
* *Show total* - Displays a row at the bottom of the table with each column's total value.
* *Total function* - Controls the function used to calculate totals that you can toggle with the **Show total** checkbox.
* *Percentage column* - Select a column to add a percentage based column on the same data.

NOTE: Enabling the *Options* behaviors may have a substantial effect on performance.
