[[data-table]]
=== Data Table

The nested structure of Elasticsearch responses is flattened into a table.
Multiple tables can be displayed by configuring a bucket as a "Split table".

The table visualization has support for bucket aggregations beyond other visualizations:

*Geohash*:: The {ref}/search-aggregations-bucket-geohashgrid-aggregation.html[_geohash_] aggregation displays points
based on a geohash.
*Geotile*:: The {ref}/search-aggregations-bucket-geotilegrid-aggregation.html[_geotile_] aggregation groups points
based on web map tiling.

Tables can 
Once you've specified a bucket type aggregation, you can define sub-buckets to refine the visualization. Click
*+ Add* to define a sub-bucket, then choose *Split rows* or *Split table*, then select an
aggregation from the list of types.

Enter a string in the *Custom Label* field to change the display label.

You can click the *Advanced* link to display more customization options for your metrics or bucket aggregation:

*Exclude Pattern*:: Specify a pattern in this field to exclude from the results.
*Include Pattern*:: Specify a pattern in this field to include in the results.
include::json-input.asciidoc[]

Select the *Options* tab to change the following aspects of the table:

*Per Page*:: This field controls the pagination of the table. The default value is ten rows per page.
*Show metrics for every bucket/level*:: Check this box to display the intermediate results for each bucket aggregation.
*Show partial rows*:: Check this box to display a row even when there is no result.
*Show total*:: Check this box to display a row at the bottom of the table with each column's total value.
*Total function*:: This field controls the function used to calculate totals that you can toggle with the **Show total** checkbox.
*Percentage column*:: Select a column to add a percentage based column on the same data.

NOTE: Enabling these behaviors may have a substantial effect on performance.
