[[goal-chart]]
== Goal and Gauge

A goal visualization displays how your metric progresses toward a fixed goal. A gauge visualization displays in which
predefined range falls your metric.

include::y-axis-aggs.asciidoc[]

Open the *Advanced* link to display more customization options:

*JSON Input*:: A text field where you can add specific JSON-formatted properties to merge with the aggregation
definition, as in the following example:

[source,shell]
{ "script" : "doc['grade'].value * 1.2" }

NOTE: In Elasticsearch releases 1.4.3 and later, this functionality requires you to enable
{ref}/modules-scripting.html[dynamic Groovy scripting].

The availability of these options varies depending on the aggregation you choose.

Click the *Options* tab to change the following options:

* *Gauge Type* select between arc, circle and metric display type.
* *Percentage Mode* will show all values as percentages
* *Vertical Split* will put the gauges one under another instead of one next to another
* *Show Labels* selects whether you want to show or hide the labels
* *Sub Text* text for the label that appears below the value
* *Auto Extend Range* automatically grows the gauge if value is over its extents.
* *Ranges* you can add custom ranges. Each range will get assigned a color. If value falls within that range it will get
assigned that color.
** A chart with a single range is called a *goal* chart.
** A chart with multiple ranges is called a *gauge* chart. Gauge charts are initialized with a predefined set of ranges. Adjust the ranges to fit the need of your data set and use case.
** *Caution:* Field formatters can be applied to the displayed value causing the range values and the displayed values to be different. For example: The _bytes_ field formatter applied to the Metrics field will have displayed values like "30MB". The raw value is really closer to 30,000,000. You will need to set your range values to the raw value and not the formatted value.
* *Color Options* define how to color your ranges (which color schema to use). Color options are only visible if more than
one range is defined.
* *Style - Show Scale* shows or hides the scale
* *Style - Color Labels* whether the labels should have the same color as the range where the value falls in
