[[lens]]
== Lens

*Lens* provides you with a simple way to create and build basic visualizations.

With Lens, you can:

* Easily make sense of your data with basic visualizations. 
* Use aggregations to plot any data set, no matter how large.
* Focus the data you want to display with searches.
* Add your visualizations to Canvas, Dashboards, Discover, and notepads.

//TODO For an overview of Lens, watch <<Lens video, Lens video>>.

[float]
[[choose-lens-visualization]]
=== Types of Lens visualizations

Lens comes with these types of visualizations:

Bar:: Display numerical comparisons across multiple categories. In bar charts, 
data is displayed using a number of bars that represent a particular category.

//TODO add bar chart image

Stacked Bar:: Display numerical comparisons across multiple categories, with the 
added ability to compare the different parts of a particular category. In 
stacked bar charts, each bar represents a particular category, and the segments 
of the bar represent the sub categories of that bar.

//TODO add stacked bar chart image

Line:: Display data trends over time. In line charts, data is displayed as a 
series of data points that are connected by line segments.

//TODO add line chart image

Area:: Display one or more quantities over time. In area charts, points are
plotted and connected by lines to show the value of a quantity at several
different times.

//TODO add area chart image

Stacked Area:: Display the evolution of numeric variables for several 
categories stacked on top of each other.  

//TODO add stacked area chart image

Data Table:: Display your raw data or aggregation results in a tabular format.

//TODO add data table image

Metric:: Dislay the latest number in a data series.

//TODO add metric image

[float]
[[create-lens-visualization]]
=== Create Lens visualizations

To create your Lens visualizations, use the Lens visualization builder.

[float]
[[change-index]]
==== Change the index

With Lens, you can change your index right from the Lens visualization builder. 

In the editor on the left, click *change*, then select the index.

//TODO insert image

[float]
[[choose-your-data]]
==== Choose the data you want to display

Choose from the data fields in the editor on the left. 

//TODO insert image

If you want to see the top values of a field, click *i* next to the field.

//TODO insert image

To narrow the data fields that are displayed:

* Use *Search for fields*.

//TODO insert image

* Click *Fields filtered*, then click the filter type.

//TODO insert image

[float]
[[add-data]]
==== Add the data you want to display

To add data to the Lens visualization builder, you drag and drop the data fields to one of these locations:

* *Create a visualization* window

//TODO insert image

* *X-axis* and *Y-axis* fields

//TODO insert image

[float]
[[change-visualization-type]]
==== Change the visualization type

If you want to display your data in a different visualization, use one of the following options:

* Click *change* in the editor on the right

//TODO insert image

* Click the *Suggestions*

//TODO insert image

When you've finished making changes to the visualization, *Save* it.

[float]
[[lens-next-steps]]
==== Next steps

Add your Lens visualizations to:

* <<discover, Discover>>

* <<dashboard, Dashboard>>

* <<canvas, Canvas>>
