[[pie-chart]]
=== Pie Charts

Pie charts do not support {es} {ref}/search-aggregations-pipeline.html[pipeline] aggregations.

The slice size can be based off a limited set of aggregations, specifically:

* {ref}/search-aggregations-metrics-valuecount-aggregation.html[Count]
* {ref}/search-aggregations-metrics-sum-aggregation.html[Sum]
* *Unique Count*: Uses the {ref}/search-aggregations-metrics-cardinality-aggregation.html[_cardinality_] aggregation.
* *Top Hit*: Uses the {ref}/search-aggregations-metrics-top-hits-aggregation.html[_top hits_]
aggregation to return a sample of individual documents. If more than one document is matched by this aggregation, you must choose a technique for combining the values. These techniques are average, min, max, and sum.

You can click the *Advanced* link to display more customization options for your metrics or bucket aggregation:

*Exclude Pattern*:: Specify a pattern in this field to exclude from the results.
*Include Pattern*:: Specify a pattern in this field to include in the results.
include::json-input.asciidoc[]

Select the *Options* tab to change the following aspects of the table:

*Donut*:: Display the chart as a sliced ring instead of a sliced pie.
*Show Tooltip*:: Check this box to enable the display of tooltips.

After changing options, click the *Apply changes* button to update your visualization, or the grey *Discard
changes* button to keep your visualization in its current state.
