[[pie-chart]]
== Pie Charts

Pie charts allow you to plot aggregated data from a saved query or index pattern.
Pie charts support multiple levels of {es} {ref}/search-aggregations-bucket.html[bucket]
aggregations and base their slice size at each lavel on a
{es} {ref}/search-aggregations-metrics.html[metric] aggregations.

Pie charts do not support {es} {ref}/search-aggregations-pipeline.html[pipeline] aggregations.

The slice size can be based off these aggregations:

* {ref}/search-aggregations-metrics-valuecount-aggregation.html[Count]
* {ref}/search-aggregations-metrics-sum-aggregation.html[Sum]
* *Unique Count*: Uses the {ref}/search-aggregations-metrics-cardinality-aggregation.html[_cardinality_] aggregation.
* *Top Hit*: Uses the {ref}/search-aggregations-metrics-top-hits-aggregation.html[_top hits_]
aggregation to return a sample of individual documents. If more than one document is matched by this aggregation, you must choose a technique for combining the values. These techniques are average, min, max, and sum.

Enter a string in the *Custom Label* field to change the display label.

The _buckets_ aggregations determine what information is being retrieved from your data set.

Before you choose a buckets aggregation, specify if you are splitting slices within a single chart or splitting into
multiple charts. A multiple chart split must run before any other aggregations. When you split a chart, you can change
if the splits are displayed in a row or a column by clicking the *Rows | Columns* selector.

You can specify any of the following bucket aggregations for your pie chart:

include::bucket-aggs.asciidoc[]

After defining an initial bucket aggregation, you can define sub-buckets to refine the visualization. Click *+ Add*
to define a sub-aggregation, then choose *Split Slices* to select a sub-bucket from the list of
types.

When multiple aggregations are defined on a chart's axis, you can use the up or down arrows to the right of the
aggregation's type to change the aggregation's priority.

include::color-picker.asciidoc[]

Enter a string in the *Custom Label* field to change the display label.

You can click the *Advanced* link to display more customization options for your metrics or bucket aggregation:

*Exclude Pattern*:: Specify a pattern in this field to exclude from the results.
*Include Pattern*:: Specify a pattern in this field to include in the results.
include::json-input.asciidoc[]

Select the *Options* tab to change the following aspects of the table:

*Donut*:: Display the chart as a sliced ring instead of a sliced pie.
*Show Tooltip*:: Check this box to enable the display of tooltips.

After changing options, click the *Apply changes* button to update your visualization, or the grey *Discard
changes* button to keep your visualization in its current state.
