[[tagcloud-chart]]
=== Tag Clouds

A tag cloud visualization is a visual representation of text data, typically used to visualize free form text.
Tags are usually single words, and the importance of each tag is shown with font size or color.

The tag cloud only supports one type of bucket aggregation:

*Terms*:: A {ref}/search-aggregations-bucket-terms-aggregation.html[_terms_] aggregation enables you to specify the top
or bottom _n_ elements of a  given field to display, ordered by count or a custom metric.

You can click the *Advanced* link to display more customization options for your metrics or bucket aggregation:

include::json-input.asciidoc[]

Select the *Options* tab to change the following aspects of the chart:

*Text Scale*:: You can select *linear*, *log*, or *square root* scales for the text scale. You can use a log
scale to display data that varies exponentially or a square root scale to
regularize the display of data sets with variabilities that are themselves highly variable.
*Orientation*:: You can select how to orientate your text in the tag cloud. You can choose one of the following options:
Single, right angles and multiple.
*Font Size*:: Allows you to set minimum and maximum font size to use for this visualization.
