import type { MapState } from './types';
export declare const DEFAULT_MAP_STATE: MapState;
export declare function map(state: MapState | undefined, action: Record<string, any>): {
    openTooltips: any;
    executionContext: import("@kbn/core/server").KibanaExecutionContext;
    ready: boolean;
    mapInitError?: string | null;
    goto?: import("../../../common/descriptor_types").Goto | null;
    mapState: import("./types").MapContext;
    selectedLayerId: string | null;
    layerList: import("../../../common").LayerDescriptor[];
    waitingForMapReadyLayerList: import("../../../common").LayerDescriptor[];
    settings: import("../../../server").MapSettings;
    __rollbackSettings: import("../../../server").MapSettings | null;
    __pauseSyncData: boolean;
} | {
    goto: {
        center: any;
        bounds: any;
    };
    executionContext: import("@kbn/core/server").KibanaExecutionContext;
    ready: boolean;
    mapInitError?: string | null;
    openTooltips: import("../../../common/descriptor_types").TooltipState[];
    mapState: import("./types").MapContext;
    selectedLayerId: string | null;
    layerList: import("../../../common").LayerDescriptor[];
    waitingForMapReadyLayerList: import("../../../common").LayerDescriptor[];
    settings: import("../../../server").MapSettings;
    __rollbackSettings: import("../../../server").MapSettings | null;
    __pauseSyncData: boolean;
} | {
    settings: any;
    executionContext: import("@kbn/core/server").KibanaExecutionContext;
    ready: boolean;
    mapInitError?: string | null;
    goto?: import("../../../common/descriptor_types").Goto | null;
    openTooltips: import("../../../common/descriptor_types").TooltipState[];
    mapState: import("./types").MapContext;
    selectedLayerId: string | null;
    layerList: import("../../../common").LayerDescriptor[];
    waitingForMapReadyLayerList: import("../../../common").LayerDescriptor[];
    __rollbackSettings: import("../../../server").MapSettings | null;
    __pauseSyncData: boolean;
} | {
    mapState: any;
    executionContext: import("@kbn/core/server").KibanaExecutionContext;
    ready: boolean;
    mapInitError?: string | null;
    goto?: import("../../../common/descriptor_types").Goto | null;
    openTooltips: import("../../../common/descriptor_types").TooltipState[];
    selectedLayerId: string | null;
    layerList: import("../../../common").LayerDescriptor[];
    waitingForMapReadyLayerList: import("../../../common").LayerDescriptor[];
    settings: import("../../../server").MapSettings;
    __rollbackSettings: import("../../../server").MapSettings | null;
    __pauseSyncData: boolean;
} | {
    selectedLayerId: any;
    executionContext: import("@kbn/core/server").KibanaExecutionContext;
    ready: boolean;
    mapInitError?: string | null;
    goto?: import("../../../common/descriptor_types").Goto | null;
    openTooltips: import("../../../common/descriptor_types").TooltipState[];
    mapState: import("./types").MapContext;
    layerList: import("../../../common").LayerDescriptor[];
    waitingForMapReadyLayerList: import("../../../common").LayerDescriptor[];
    settings: import("../../../server").MapSettings;
    __rollbackSettings: import("../../../server").MapSettings | null;
    __pauseSyncData: boolean;
} | {
    __pauseSyncData: any;
    executionContext: import("@kbn/core/server").KibanaExecutionContext;
    ready: boolean;
    mapInitError?: string | null;
    goto?: import("../../../common/descriptor_types").Goto | null;
    openTooltips: import("../../../common/descriptor_types").TooltipState[];
    mapState: import("./types").MapContext;
    selectedLayerId: string | null;
    layerList: import("../../../common").LayerDescriptor[];
    waitingForMapReadyLayerList: import("../../../common").LayerDescriptor[];
    settings: import("../../../server").MapSettings;
    __rollbackSettings: import("../../../server").MapSettings | null;
} | {
    layerList: any;
    executionContext: import("@kbn/core/server").KibanaExecutionContext;
    ready: boolean;
    mapInitError?: string | null;
    goto?: import("../../../common/descriptor_types").Goto | null;
    openTooltips: import("../../../common/descriptor_types").TooltipState[];
    mapState: import("./types").MapContext;
    selectedLayerId: string | null;
    waitingForMapReadyLayerList: import("../../../common").LayerDescriptor[];
    settings: import("../../../server").MapSettings;
    __rollbackSettings: import("../../../server").MapSettings | null;
    __pauseSyncData: boolean;
} | {
    waitingForMapReadyLayerList: any[];
    executionContext: import("@kbn/core/server").KibanaExecutionContext;
    ready: boolean;
    mapInitError?: string | null;
    goto?: import("../../../common/descriptor_types").Goto | null;
    openTooltips: import("../../../common/descriptor_types").TooltipState[];
    mapState: import("./types").MapContext;
    selectedLayerId: string | null;
    layerList: import("../../../common").LayerDescriptor[];
    settings: import("../../../server").MapSettings;
    __rollbackSettings: import("../../../server").MapSettings | null;
    __pauseSyncData: boolean;
} | {
    mapInitError: any;
    executionContext: import("@kbn/core/server").KibanaExecutionContext;
    ready: boolean;
    goto?: import("../../../common/descriptor_types").Goto | null;
    openTooltips: import("../../../common/descriptor_types").TooltipState[];
    mapState: import("./types").MapContext;
    selectedLayerId: string | null;
    layerList: import("../../../common").LayerDescriptor[];
    waitingForMapReadyLayerList: import("../../../common").LayerDescriptor[];
    settings: import("../../../server").MapSettings;
    __rollbackSettings: import("../../../server").MapSettings | null;
    __pauseSyncData: boolean;
} | {
    executionContext: any;
    ready: boolean;
    mapInitError?: string | null;
    goto?: import("../../../common/descriptor_types").Goto | null;
    openTooltips: import("../../../common/descriptor_types").TooltipState[];
    mapState: import("./types").MapContext;
    selectedLayerId: string | null;
    layerList: import("../../../common").LayerDescriptor[];
    waitingForMapReadyLayerList: import("../../../common").LayerDescriptor[];
    settings: import("../../../server").MapSettings;
    __rollbackSettings: import("../../../server").MapSettings | null;
    __pauseSyncData: boolean;
};
