export declare const APP_ID = "data_visualizer";
export declare const SUPPORTED_FIELD_TYPES: {
    readonly BOOLEAN: "boolean";
    readonly CONFLICT: "conflict";
    readonly DATE: "date";
    readonly DATE_RANGE: "date_range";
    readonly GEO_POINT: "geo_point";
    readonly GEO_SHAPE: "geo_shape";
    readonly HISTOGRAM: "histogram";
    readonly IP: "ip";
    readonly IP_RANGE: "ip_range";
    readonly KEYWORD: "keyword";
    readonly MURMUR3: "murmur3";
    readonly NUMBER: "number";
    readonly NESTED: "nested";
    readonly STRING: "string";
    readonly TEXT: "text";
    readonly SEMANTIC_TEXT: "semantic_text";
    readonly DENSE_VECTOR: "dense_vector";
    readonly SPARSE_VECTOR: "sparse_vector";
    readonly VERSION: "version";
    readonly UNKNOWN: "unknown";
};
export declare const OMIT_FIELDS: string[];
export declare const NON_AGGREGATABLE_FIELD_TYPES: Set<string>;
export declare const FILE_DATA_VIS_TAB_ID = "fileDataViz";
export declare const applicationPath = "/app/home#/tutorial_directory/fileDataViz";
export declare const featureTitle: string;
export declare const featureId = "file_data_visualizer";
export declare const SUPPORTED_FIELD_TYPES_LIST: string[];
