version: '1'
name: 'sources.amazon_s3.list'
description: 'List available Amazon S3 Buckets.'
tags: ['agent-builder-tool']
enabled: true
triggers:
  - type: 'manual'
inputs:
  - name: region
    type: string
    required: false
    description: "The AWS region to list buckets from. If not specified, buckets from default region in the authorization credentials will be listed."
  - name: prefix
    type: string
    required: false
    description: "An optional prefix to filter bucket names."
steps:
  - name: listBuckets
    type: amazon_s3.listBuckets
    connector-id: <%= amazon_s3-stack-connector-id %>
    with:
      region: "${{ inputs.region }}"
      prefix: "${{ inputs.prefix }}"
