/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Watchlist Management API
 *   version: 2023-10-31
 */

import { z, lazySchema } from '@kbn/zod/v4';

import { WatchlistObject } from './common.gen';

export const UpdateWatchlistRequestParams = lazySchema(() =>
  z.object({
    /**
     * The ID of the watchlist to update
     */
    id: z.string().max(256).describe('The ID of the watchlist to update'),
  })
);
export type UpdateWatchlistRequestParams = z.infer<typeof UpdateWatchlistRequestParams>;
export type UpdateWatchlistRequestParamsInput = z.input<typeof UpdateWatchlistRequestParams>;

export const UpdateWatchlistRequestBody = lazySchema(() =>
  z.object({
    /**
     * Unique name of the watchlist
     */
    name: z.string().max(256).describe('Unique name of the watchlist'),
    /**
     * Description of the watchlist
     */
    description: z.string().max(1000).optional().describe('Description of the watchlist'),
    /**
     * Risk score modifier associated with the watchlist
     */
    riskModifier: z
      .number()
      .min(0)
      .max(2)
      .describe('Risk score modifier associated with the watchlist'),
    /**
     * Indicates if the watchlist is managed by the system
     */
    managed: z.boolean().optional().describe('Indicates if the watchlist is managed by the system'),
  })
);
export type UpdateWatchlistRequestBody = z.infer<typeof UpdateWatchlistRequestBody>;
export type UpdateWatchlistRequestBodyInput = z.input<typeof UpdateWatchlistRequestBody>;

export const UpdateWatchlistResponse = lazySchema(() => WatchlistObject);
export type UpdateWatchlistResponse = z.infer<typeof UpdateWatchlistResponse>;
