[[words]]
== 

**_Learn the shared concepts for analyzing and visualizing your data_**

Data analysis is a core functionality of {kib}. These are the 
You can quickly search through large amounts of data, explore fields and values,
and then use {kib}’s drag-and-drop interface to rapidly build charts, tables, metrics, and more.

=== Add data

{kib} supports several methods to add your data. The best way to add {es} data to {kib} is to use one of our guided processes,
available from the <<kibana-home-page,home page>>.

=== Work with index patterns

{kib} requires an index pattern to tell it which {es} data you want to access,
and whether the data is time-based. An index pattern can point to one or more {es}
data streams, indices, or index aliases by name.
For example, `logs-elasticsearch-prod-*` is an index pattern,
and it is time-based with a time field of `@timestamp`. The time field is not editable.

Index patterns are typically created by an administrator when sending data to {es}.
You can <<index-patterns,create or update index patterns>> in *Stack Management*, or by using a script
that accesses the {kib} API.

For this getting started experience, the sample ecommerce data comes with an index pattern for you to visualize. To see what the index pattern contains, open it in Discover!

{kib} uses the index pattern to show you a list of fields in the Analytics apps, where you can explore and visualize the data.

You can customize the display name and format for each field.
For example, you can tell {kib} to display `event.duration` in seconds.
{kib} has <<managing-fields,field formatters>> for strings,
dates, geopoints, and numbers.

=== Semistructured search

This is where we talk about query bar, including KQL, Lucene, and how to save these queries.

=== Filter the data

This is where we talk about filter pills and time filter.

--

include::{kib-repo-dir}/concepts/quick-start-guide.asciidoc[Quick start] 

include::{kib-repo-dir}/setup/connect-to-elasticsearch.asciidoc[Add data] 

include::{kib-repo-dir}/concepts/index-patterns.asciidoc[Working with index patterns] 

include::{kib-repo-dir}/concepts/kuery.asciidoc[KQL] 

include::{kib-repo-dir}/concepts/lucene.asciidoc[Lucene]] 

include::{kib-repo-dir}/concepts/save-query.asciidoc[Save queries]

include::{kib-repo-dir}/concepts/set-time-filter.asciidoc[Time filter]












| *Share.*
| Ready to <<reporting-getting-started, share>> your findings with a larger audience? {kib} lets you save objects for your own future use or for sharing with others.
Each <<managing-saved-objects,saved object>> type has different abilities. For example, you can save
your search queries made with *Discover*, which lets you:

* Share a link to your search
* Download the full search results in CSV form
* Start an aggregated visualization using the same search query
* Embed the *Discover* search results into a dashboard
* Embed the *Discover* search results into a Canvas workpad

For organization, every saved object can have a name, <<kibana-navigation-search,tags>>, and type.
Use the global search to quickly open a saved object.
|===





[float]
=== Three things to know about {es}

You don't need to know everything about {es} to use {kib}, but the most important concepts follow:

* *{es} makes JSON documents searchable and aggregatable.* The documents are
stored in an {ref}/documents-indices.html[index] or {ref}/data-streams.html[data stream], which represent one type of data.

* **_Searchable_ means that you can filter the documents for conditions.**
For example, you can filter for data "within the last 7 days" or data that "contains the word {kib}".
{kib} provides many ways for you to construct filters, which are also called queries or search terms.

* **_Aggregatable_ means that you can extract summaries from matching documents.**
The simplest aggregation is *count*, and it is frequently used in combination
with the *date histogram*, to see count over time. The *terms* aggregation shows the most frequent values.