/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

import type { EcsSecurityExtension as Ecs } from '@kbn/securitysolution-ecs';

// This data was generated using the endpoint test alert generator
export const getMockAlertDetailsFieldsResponse = () => ({
  _index: '.internal.alerts-security.alerts-default-000001',
  _id: 'f6aa8643ecee466753c45308ea8dc72aba0a44e1faac5f6183fd2ad6666c1325',
  _score: 1,
  fields: {
    'kibana.alert.severity': ['medium'],
    'process.hash.md5': ['fake md5'],
    'kibana.alert.rule.updated_by': ['elastic'],
    'signal.ancestors.depth': [0],
    'event.category': ['malware'],
    'kibana.alert.rule.rule_name_override': ['message'],
    'Endpoint.capabilities': ['isolation', 'kill_process', 'suspend_process', 'running_processes'],
    'process.parent.pid': [1],
    'process.hash.sha256': ['fake sha256'],
    'host.hostname': ['Host-4cfuh42w7g'],
    'kibana.alert.rule.tags': ['Elastic', 'Endpoint Security'],
    'host.mac': ['f2-32-1b-dc-ec-80'],
    'elastic.agent.id': ['d08ed3f8-9852-4d0c-a5b1-b48060705369'],
    'dll.hash.sha256': ['8ad40c90a611d36eb8f9eb24fa04f7dbca713db383ff55a03aa0f382e92061a2'],
    'kibana.alert.ancestors.depth': [0],
    'signal.rule.enabled': ['true'],
    'signal.rule.max_signals': [10000],
    'host.os.version': ['10.0'],
    'signal.rule.updated_at': ['2022-09-29T19:39:38.137Z'],
    'kibana.alert.risk_score': [47],
    'Endpoint.policy.applied.id': ['C2A9093E-E289-4C0A-AA44-8C32A414FA7A'],
    'kibana.alert.rule.severity_mapping.severity': ['low', 'medium', 'high', 'critical'],
    'event.agent_id_status': ['auth_metadata_missing'],
    'kibana.alert.original_event.id': ['7799e1d5-5dc1-4173-9d11-562496cd863b'],
    'kibana.alert.rule.risk_score_mapping.value': [''],
    'process.Ext.ancestry': ['kj0le842x0', '1r4s9i1br4'],
    'signal.original_event.code': ['memory_signature'],
    'kibana.alert.original_event.module': ['endpoint'],
    'kibana.alert.rule.interval': ['5m'],
    'kibana.alert.rule.type': ['query'],
    'signal.original_event.sequence': [1232],
    'Endpoint.state.isolation': [true],
    'host.architecture': ['x7n6yt4fol'],
    'kibana.alert.rule.immutable': ['true'],
    'kibana.alert.original_event.type': ['info'],
    'event.code': ['memory_signature'],
    'agent.id': ['d08ed3f8-9852-4d0c-a5b1-b48060705369'],
    'signal.original_event.module': ['endpoint'],
    'kibana.alert.rule.exceptions_list.list_id': ['endpoint_list'],
    'signal.rule.from': ['now-10m'],
    'kibana.alert.rule.exceptions_list.type': ['endpoint'],
    'process.group_leader.entity_id': ['b74mw1jkrm'],
    'dll.Ext.malware_classification.version': ['3.0.0'],
    'kibana.alert.rule.enabled': ['true'],
    'kibana.alert.rule.version': ['100'],
    'kibana.alert.ancestors.type': ['event'],
    'process.entry_leader.name': ['fake entry'],
    'dll.Ext.compile_time': [1534424710],
    'signal.ancestors.index': ['.ds-logs-endpoint.alerts-default-2022.09.29-000001'],
    'dll.Ext.malware_classification.score': [0],
    'process.entity_id': ['d3v4to81q9'],
    'host.ip': ['10.184.3.36', '10.170.218.86'],
    'agent.type': ['endpoint'],
    'signal.original_event.category': ['malware'],
    'signal.original_event.id': ['7799e1d5-5dc1-4173-9d11-562496cd863b'],
    'process.uptime': [0],
    'Endpoint.policy.applied.name': ['With Eventing'],
    'host.id': ['04794e4e-59cb-4c4a-a8ee-3e6c5b65743c'],
    'process.Ext.code_signature.subject_name': ['bad signer'],
    'process.Ext.token.integrity_level_name': ['high'],
    'signal.original_event.type': ['info'],
    'kibana.alert.rule.max_signals': [10000],
    'signal.rule.author': ['Elastic'],
    'kibana.alert.rule.risk_score': [47],
    'dll.Ext.malware_classification.identifier': ['Whitelisted'],
    'dll.Ext.mapped_address': [5362483200],
    'signal.original_event.dataset': ['endpoint'],
    'kibana.alert.rule.consumer': ['siem'],
    'kibana.alert.rule.indices': ['logs-endpoint.alerts-*'],
    'kibana.alert.rule.category': ['Custom Query Rule'],
    'host.os.Ext.variant': ['Windows Server'],
    'event.ingested': ['2022-09-29T19:37:00.000Z'],
    'event.action': ['start'],
    'signal.rule.updated_by': ['elastic'],
    '@timestamp': ['2022-09-29T19:40:26.051Z'],
    'kibana.alert.original_event.action': ['start'],
    'host.os.platform': ['Windows'],
    'process.session_leader.entity_id': ['b74mw1jkrm'],
    'kibana.alert.rule.severity': ['medium'],
    'kibana.alert.original_event.agent_id_status': ['auth_metadata_missing'],
    'Endpoint.status': ['enrolled'],
    'data_stream.dataset': ['endpoint.alerts'],
    'signal.rule.timestamp_override': ['event.ingested'],
    'kibana.alert.rule.execution.uuid': ['abf39d36-0f1c-4bf9-ae42-1039285380b5'],
    'kibana.alert.uuid': ['f6aa8643ecee466753c45308ea8dc72aba0a44e1faac5f6183fd2ad6666c1325'],
    'kibana.version': ['8.6.0'],
    'process.hash.sha1': ['fake sha1'],
    'event.id': ['7799e1d5-5dc1-4173-9d11-562496cd863b'],
    'process.entry_leader.pid': [865],
    'signal.rule.license': ['Elastic License v2'],
    'signal.ancestors.type': ['event'],
    'kibana.alert.rule.rule_id': ['9a1a2dae-0b5f-4c3d-8305-a268d404c306'],
    'process.session_leader.pid': [745],
    'signal.rule.type': ['query'],
    'Endpoint.policy.applied.version': [5],
    'dll.hash.md5': ['1f2d082566b0fc5f2c238a5180db7451'],
    'kibana.alert.ancestors.id': ['7L3AioMBWJvcpv7vlX2O'],
    'user.name': ['root'],
    'source.ip': ['10.184.3.46'],
    'signal.rule.rule_name_override': ['message'],
    'process.group_leader.name': ['fake leader'],
    'host.os.full': ['Windows Server 2016'],
    'kibana.alert.original_event.code': ['memory_signature'],
    'kibana.alert.rule.risk_score_mapping.field': ['event.risk_score'],
    'kibana.alert.rule.description': [
      'Generates a detection alert each time an Elastic Endpoint Security alert is received. Enabling this rule allows you to immediately begin investigating your Endpoint alerts.',
    ],
    'process.pid': [2],
    'kibana.alert.rule.producer': ['siem'],
    'kibana.alert.rule.to': ['now'],
    'signal.rule.interval': ['5m'],
    'signal.rule.created_by': ['elastic'],
    'kibana.alert.rule.created_by': ['elastic'],
    'kibana.alert.rule.timestamp_override': ['event.ingested'],
    'kibana.alert.original_event.ingested': ['2022-09-29T19:37:00.000Z'],
    'signal.rule.id': ['738e91f2-402e-11ed-be15-7be3bb26d7b2'],
    'process.parent.entity_id': ['kj0le842x0'],
    'signal.rule.risk_score': [47],
    'signal.reason': [
      'malware event with process explorer.exe, on Host-4cfuh42w7g created medium alert Endpoint Security.',
    ],
    'host.os.name': ['Windows'],
    'kibana.alert.rule.name': ['Endpoint Security'],
    'host.name': ['Host-4cfuh42w7g'],
    'signal.status': ['open'],
    'event.kind': ['signal'],
    'kibana.alert.rule.severity_mapping.value': ['21', '47', '73', '99'],
    'signal.rule.tags': ['Elastic', 'Endpoint Security'],
    'signal.rule.created_at': ['2022-09-29T19:39:38.137Z'],
    'kibana.alert.workflow_status': ['open'],
    'Endpoint.policy.applied.status': ['warning'],
    'kibana.alert.rule.uuid': ['738e91f2-402e-11ed-be15-7be3bb26d7b2'],
    'kibana.alert.original_event.category': ['malware'],
    'dll.Ext.malware_classification.threshold': [0],
    'kibana.alert.reason': [
      'malware event with process explorer.exe, on Host-4cfuh42w7g created medium alert Endpoint Security.',
    ],
    'dll.pe.architecture': ['x64'],
    'data_stream.type': ['logs'],
    'signal.original_time': ['2022-10-09T07:14:42.194Z'],
    'signal.ancestors.id': ['7L3AioMBWJvcpv7vlX2O'],
    'process.name': ['explorer.exe'],
    'ecs.version': ['1.6.0'],
    'signal.rule.severity': ['medium'],
    'kibana.alert.ancestors.index': ['.ds-logs-endpoint.alerts-default-2022.09.29-000001'],
    'Endpoint.configuration.isolation': [true],
    'Memory_protection.feature': ['signature'],
    'dll.code_signature.trusted': [true],
    'process.Ext.code_signature.trusted': [false],
    'kibana.alert.depth': [1],
    'agent.version': ['8.6.0'],
    'kibana.alert.rule.risk_score_mapping.operator': ['equals'],
    'host.os.family': ['windows'],
    'kibana.alert.rule.from': ['now-10m'],
    'Memory_protection.self_injection': [true],
    'process.start': ['2022-10-09T07:14:42.194Z'],
    'kibana.alert.rule.parameters': [
      {
        severity_mapping: [
          {
            severity: 'low',
            field: 'event.severity',
            value: '21',
            operator: 'equals',
          },
          {
            severity: 'medium',
            field: 'event.severity',
            value: '47',
            operator: 'equals',
          },
          {
            severity: 'high',
            field: 'event.severity',
            value: '73',
            operator: 'equals',
          },
          {
            severity: 'critical',
            field: 'event.severity',
            value: '99',
            operator: 'equals',
          },
        ],
        references: [],
        description:
          'Generates a detection alert each time an Elastic Endpoint Security alert is received. Enabling this rule allows you to immediately begin investigating your Endpoint alerts.',
        language: 'kuery',
        type: 'query',
        rule_name_override: 'message',
        exceptions_list: [
          {
            list_id: 'endpoint_list',
            namespace_type: 'agnostic',
            id: 'endpoint_list',
            type: 'endpoint',
          },
        ],
        timestamp_override: 'event.ingested',
        from: 'now-10m',
        severity: 'medium',
        max_signals: 10000,
        risk_score: 47,
        risk_score_mapping: [
          {
            field: 'event.risk_score',
            value: '',
            operator: 'equals',
          },
        ],
        author: ['Elastic'],
        query: 'event.kind:alert and event.module:(endpoint and not endgame)\n',
        index: ['logs-endpoint.alerts-*'],
        version: 100,
        rule_id: '9a1a2dae-0b5f-4c3d-8305-a268d404c306',
        license: 'Elastic License v2',
        required_fields: [
          {
            ecs: true,
            name: 'event.kind',
            type: 'keyword',
          },
          {
            ecs: true,
            name: 'event.module',
            type: 'keyword',
          },
        ],
        immutable: true,
        related_integrations: [],
        setup: '',
        false_positives: [],
        threat: [],
        to: 'now',
      },
    ],
    'signal.rule.version': ['100'],
    'signal.original_event.kind': ['alert'],
    'kibana.alert.status': ['active'],
    'kibana.alert.rule.severity_mapping.field': [
      'event.severity',
      'event.severity',
      'event.severity',
      'event.severity',
    ],
    'kibana.alert.original_event.dataset': ['endpoint'],
    'signal.depth': [1],
    'signal.rule.immutable': ['true'],
    'process.group_leader.pid': [116],
    'event.sequence': [1232],
    'kibana.alert.rule.rule_type_id': ['siem.queryRule'],
    'process.session_leader.name': ['fake session'],
    'signal.rule.name': ['Endpoint Security'],
    'signal.rule.rule_id': ['9a1a2dae-0b5f-4c3d-8305-a268d404c306'],
    'event.module': ['endpoint'],
    'dll.hash.sha1': ['ca85243c0af6a6471bdaa560685c51eefd6dbc0d'],
    'kibana.alert.rule.severity_mapping.operator': ['equals', 'equals', 'equals', 'equals'],
    'process.Ext.malware_signature.all_names': ['Windows.Trojan.FakeAgent'],
    'kibana.alert.rule.license': ['Elastic License v2'],
    'kibana.alert.original_event.kind': ['alert'],
    'process.executable': ['C:/fake/explorer.exe'],
    'kibana.alert.rule.updated_at': ['2022-09-29T19:39:38.137Z'],
    'signal.rule.description': [
      'Generates a detection alert each time an Elastic Endpoint Security alert is received. Enabling this rule allows you to immediately begin investigating your Endpoint alerts.',
    ],
    'dll.Ext.mapped_size': [0],
    'data_stream.namespace': ['default'],
    'kibana.alert.rule.author': ['Elastic'],
    'dll.code_signature.subject_name': ['Cybereason Inc'],
    'Endpoint.policy.applied.endpoint_policy_version': [3],
    'kibana.alert.original_event.sequence': [1232],
    'dll.path': ['C:\\Program Files\\Cybereason ActiveProbe\\AmSvc.exe'],
    'process.Ext.user': ['SYSTEM'],
    'signal.original_event.action': ['start'],
    'signal.rule.to': ['now'],
    'kibana.alert.rule.created_at': ['2022-09-29T19:39:38.137Z'],
    'process.Ext.malware_signature.identifier': ['diagnostic-malware-signature-v1-fake'],
    'kibana.alert.rule.exceptions_list.namespace_type': ['agnostic'],
    'event.type': ['info'],
    'kibana.space_ids': ['default'],
    'process.entry_leader.entity_id': ['b74mw1jkrm'],
    'kibana.alert.rule.exceptions_list.id': ['endpoint_list'],
    'event.dataset': ['endpoint'],
    'kibana.alert.original_time': ['2022-10-09T07:14:42.194Z'],
  },
});

export const getMockAlertDetailsTimelineResponse = () => [
  {
    category: 'kibana',
    field: 'kibana.alert.severity',
    values: ['medium'],
    originalValue: ['medium'],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.hash.md5',
    values: ['fake md5'],
    originalValue: ['fake md5'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.updated_by',
    values: ['elastic'],
    originalValue: ['elastic'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.ancestors.depth',
    values: ['0'],
    originalValue: ['0'],
    isObjectArray: false,
  },
  {
    category: 'event',
    field: 'event.category',
    values: ['malware'],
    originalValue: ['malware'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.rule_name_override',
    values: ['message'],
    originalValue: ['message'],
    isObjectArray: false,
  },
  {
    category: 'Endpoint',
    field: 'Endpoint.capabilities',
    values: ['isolation', 'kill_process', 'suspend_process', 'running_processes'],
    originalValue: ['isolation', 'kill_process', 'suspend_process', 'running_processes'],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.parent.pid',
    values: ['1'],
    originalValue: ['1'],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.hash.sha256',
    values: ['fake sha256'],
    originalValue: ['fake sha256'],
    isObjectArray: false,
  },
  {
    category: 'host',
    field: 'host.hostname',
    values: ['Host-4cfuh42w7g'],
    originalValue: ['Host-4cfuh42w7g'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.tags',
    values: ['Elastic', 'Endpoint Security'],
    originalValue: ['Elastic', 'Endpoint Security'],
    isObjectArray: false,
  },
  {
    category: 'host',
    field: 'host.mac',
    values: ['f2-32-1b-dc-ec-80'],
    originalValue: ['f2-32-1b-dc-ec-80'],
    isObjectArray: false,
  },
  {
    category: 'elastic',
    field: 'elastic.agent.id',
    values: ['d08ed3f8-9852-4d0c-a5b1-b48060705369'],
    originalValue: ['d08ed3f8-9852-4d0c-a5b1-b48060705369'],
    isObjectArray: false,
  },
  {
    category: 'dll',
    field: 'dll.hash.sha256',
    values: ['8ad40c90a611d36eb8f9eb24fa04f7dbca713db383ff55a03aa0f382e92061a2'],
    originalValue: ['8ad40c90a611d36eb8f9eb24fa04f7dbca713db383ff55a03aa0f382e92061a2'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.ancestors.depth',
    values: ['0'],
    originalValue: ['0'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.rule.enabled',
    values: ['true'],
    originalValue: ['true'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.rule.max_signals',
    values: ['10000'],
    originalValue: ['10000'],
    isObjectArray: false,
  },
  {
    category: 'host',
    field: 'host.os.version',
    values: ['10.0'],
    originalValue: ['10.0'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.rule.updated_at',
    values: ['2022-09-29T19:39:38.137Z'],
    originalValue: ['2022-09-29T19:39:38.137Z'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.risk_score',
    values: ['47'],
    originalValue: ['47'],
    isObjectArray: false,
  },
  {
    category: 'Endpoint',
    field: 'Endpoint.policy.applied.id',
    values: ['C2A9093E-E289-4C0A-AA44-8C32A414FA7A'],
    originalValue: ['C2A9093E-E289-4C0A-AA44-8C32A414FA7A'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.severity_mapping.severity',
    values: ['low', 'medium', 'high', 'critical'],
    originalValue: ['low', 'medium', 'high', 'critical'],
    isObjectArray: false,
  },
  {
    category: 'event',
    field: 'event.agent_id_status',
    values: ['auth_metadata_missing'],
    originalValue: ['auth_metadata_missing'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.original_event.id',
    values: ['7799e1d5-5dc1-4173-9d11-562496cd863b'],
    originalValue: ['7799e1d5-5dc1-4173-9d11-562496cd863b'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.risk_score_mapping.value',
    values: [''],
    originalValue: [''],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.Ext.ancestry',
    values: ['kj0le842x0', '1r4s9i1br4'],
    originalValue: ['kj0le842x0', '1r4s9i1br4'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.original_event.code',
    values: ['memory_signature'],
    originalValue: ['memory_signature'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.original_event.module',
    values: ['endpoint'],
    originalValue: ['endpoint'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.interval',
    values: ['5m'],
    originalValue: ['5m'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.type',
    values: ['query'],
    originalValue: ['query'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.original_event.sequence',
    values: ['1232'],
    originalValue: ['1232'],
    isObjectArray: false,
  },
  {
    category: 'Endpoint',
    field: 'Endpoint.state.isolation',
    values: ['true'],
    originalValue: ['true'],
    isObjectArray: false,
  },
  {
    category: 'host',
    field: 'host.architecture',
    values: ['x7n6yt4fol'],
    originalValue: ['x7n6yt4fol'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.immutable',
    values: ['true'],
    originalValue: ['true'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.original_event.type',
    values: ['info'],
    originalValue: ['info'],
    isObjectArray: false,
  },
  {
    category: 'event',
    field: 'event.code',
    values: ['memory_signature'],
    originalValue: ['memory_signature'],
    isObjectArray: false,
  },
  {
    category: 'agent',
    field: 'agent.id',
    values: ['d08ed3f8-9852-4d0c-a5b1-b48060705369'],
    originalValue: ['d08ed3f8-9852-4d0c-a5b1-b48060705369'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.original_event.module',
    values: ['endpoint'],
    originalValue: ['endpoint'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.exceptions_list.list_id',
    values: ['endpoint_list'],
    originalValue: ['endpoint_list'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.rule.from',
    values: ['now-10m'],
    originalValue: ['now-10m'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.exceptions_list.type',
    values: ['endpoint'],
    originalValue: ['endpoint'],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.group_leader.entity_id',
    values: ['b74mw1jkrm'],
    originalValue: ['b74mw1jkrm'],
    isObjectArray: false,
  },
  {
    category: 'dll',
    field: 'dll.Ext.malware_classification.version',
    values: ['3.0.0'],
    originalValue: ['3.0.0'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.enabled',
    values: ['true'],
    originalValue: ['true'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.version',
    values: ['100'],
    originalValue: ['100'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.ancestors.type',
    values: ['event'],
    originalValue: ['event'],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.entry_leader.name',
    values: ['fake entry'],
    originalValue: ['fake entry'],
    isObjectArray: false,
  },
  {
    category: 'dll',
    field: 'dll.Ext.compile_time',
    values: ['1534424710'],
    originalValue: ['1534424710'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.ancestors.index',
    values: ['.ds-logs-endpoint.alerts-default-2022.09.29-000001'],
    originalValue: ['.ds-logs-endpoint.alerts-default-2022.09.29-000001'],
    isObjectArray: false,
  },
  {
    category: 'dll',
    field: 'dll.Ext.malware_classification.score',
    values: ['0'],
    originalValue: ['0'],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.entity_id',
    values: ['d3v4to81q9'],
    originalValue: ['d3v4to81q9'],
    isObjectArray: false,
  },
  {
    category: 'host',
    field: 'host.ip',
    values: ['10.184.3.36', '10.170.218.86'],
    originalValue: ['10.184.3.36', '10.170.218.86'],
    isObjectArray: false,
  },
  {
    category: 'agent',
    field: 'agent.type',
    values: ['endpoint'],
    originalValue: ['endpoint'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.original_event.category',
    values: ['malware'],
    originalValue: ['malware'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.original_event.id',
    values: ['7799e1d5-5dc1-4173-9d11-562496cd863b'],
    originalValue: ['7799e1d5-5dc1-4173-9d11-562496cd863b'],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.uptime',
    values: ['0'],
    originalValue: ['0'],
    isObjectArray: false,
  },
  {
    category: 'Endpoint',
    field: 'Endpoint.policy.applied.name',
    values: ['With Eventing'],
    originalValue: ['With Eventing'],
    isObjectArray: false,
  },
  {
    category: 'host',
    field: 'host.id',
    values: ['04794e4e-59cb-4c4a-a8ee-3e6c5b65743c'],
    originalValue: ['04794e4e-59cb-4c4a-a8ee-3e6c5b65743c'],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.Ext.code_signature.subject_name',
    values: ['bad signer'],
    originalValue: ['bad signer'],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.Ext.token.integrity_level_name',
    values: ['high'],
    originalValue: ['high'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.original_event.type',
    values: ['info'],
    originalValue: ['info'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.max_signals',
    values: ['10000'],
    originalValue: ['10000'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.rule.author',
    values: ['Elastic'],
    originalValue: ['Elastic'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.risk_score',
    values: ['47'],
    originalValue: ['47'],
    isObjectArray: false,
  },
  {
    category: 'dll',
    field: 'dll.Ext.malware_classification.identifier',
    values: ['Whitelisted'],
    originalValue: ['Whitelisted'],
    isObjectArray: false,
  },
  {
    category: 'dll',
    field: 'dll.Ext.mapped_address',
    values: ['5362483200'],
    originalValue: ['5362483200'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.original_event.dataset',
    values: ['endpoint'],
    originalValue: ['endpoint'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.consumer',
    values: ['siem'],
    originalValue: ['siem'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.indices',
    values: ['logs-endpoint.alerts-*'],
    originalValue: ['logs-endpoint.alerts-*'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.category',
    values: ['Custom Query Rule'],
    originalValue: ['Custom Query Rule'],
    isObjectArray: false,
  },
  {
    category: 'host',
    field: 'host.os.Ext.variant',
    values: ['Windows Server'],
    originalValue: ['Windows Server'],
    isObjectArray: false,
  },
  {
    category: 'event',
    field: 'event.ingested',
    values: ['2022-09-29T19:37:00.000Z'],
    originalValue: ['2022-09-29T19:37:00.000Z'],
    isObjectArray: false,
  },
  {
    category: 'event',
    field: 'event.action',
    values: ['start'],
    originalValue: ['start'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.rule.updated_by',
    values: ['elastic'],
    originalValue: ['elastic'],
    isObjectArray: false,
  },
  {
    category: 'base',
    field: '@timestamp',
    values: ['2022-09-29T19:40:26.051Z'],
    originalValue: ['2022-09-29T19:40:26.051Z'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.original_event.action',
    values: ['start'],
    originalValue: ['start'],
    isObjectArray: false,
  },
  {
    category: 'host',
    field: 'host.os.platform',
    values: ['Windows'],
    originalValue: ['Windows'],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.session_leader.entity_id',
    values: ['b74mw1jkrm'],
    originalValue: ['b74mw1jkrm'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.severity',
    values: ['medium'],
    originalValue: ['medium'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.original_event.agent_id_status',
    values: ['auth_metadata_missing'],
    originalValue: ['auth_metadata_missing'],
    isObjectArray: false,
  },
  {
    category: 'Endpoint',
    field: 'Endpoint.status',
    values: ['enrolled'],
    originalValue: ['enrolled'],
    isObjectArray: false,
  },
  {
    category: 'data_stream',
    field: 'data_stream.dataset',
    values: ['endpoint.alerts'],
    originalValue: ['endpoint.alerts'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.rule.timestamp_override',
    values: ['event.ingested'],
    originalValue: ['event.ingested'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.execution.uuid',
    values: ['abf39d36-0f1c-4bf9-ae42-1039285380b5'],
    originalValue: ['abf39d36-0f1c-4bf9-ae42-1039285380b5'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.uuid',
    values: ['f6aa8643ecee466753c45308ea8dc72aba0a44e1faac5f6183fd2ad6666c1325'],
    originalValue: ['f6aa8643ecee466753c45308ea8dc72aba0a44e1faac5f6183fd2ad6666c1325'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.version',
    values: ['8.6.0'],
    originalValue: ['8.6.0'],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.hash.sha1',
    values: ['fake sha1'],
    originalValue: ['fake sha1'],
    isObjectArray: false,
  },
  {
    category: 'event',
    field: 'event.id',
    values: ['7799e1d5-5dc1-4173-9d11-562496cd863b'],
    originalValue: ['7799e1d5-5dc1-4173-9d11-562496cd863b'],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.entry_leader.pid',
    values: ['865'],
    originalValue: ['865'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.rule.license',
    values: ['Elastic License v2'],
    originalValue: ['Elastic License v2'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.ancestors.type',
    values: ['event'],
    originalValue: ['event'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.rule_id',
    values: ['9a1a2dae-0b5f-4c3d-8305-a268d404c306'],
    originalValue: ['9a1a2dae-0b5f-4c3d-8305-a268d404c306'],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.session_leader.pid',
    values: ['745'],
    originalValue: ['745'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.rule.type',
    values: ['query'],
    originalValue: ['query'],
    isObjectArray: false,
  },
  {
    category: 'Endpoint',
    field: 'Endpoint.policy.applied.version',
    values: ['5'],
    originalValue: ['5'],
    isObjectArray: false,
  },
  {
    category: 'dll',
    field: 'dll.hash.md5',
    values: ['1f2d082566b0fc5f2c238a5180db7451'],
    originalValue: ['1f2d082566b0fc5f2c238a5180db7451'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.ancestors.id',
    values: ['7L3AioMBWJvcpv7vlX2O'],
    originalValue: ['7L3AioMBWJvcpv7vlX2O'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.rule.rule_name_override',
    values: ['message'],
    originalValue: ['message'],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.group_leader.name',
    values: ['fake leader'],
    originalValue: ['fake leader'],
    isObjectArray: false,
  },
  {
    category: 'host',
    field: 'host.os.full',
    values: ['Windows Server 2016'],
    originalValue: ['Windows Server 2016'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.original_event.code',
    values: ['memory_signature'],
    originalValue: ['memory_signature'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.risk_score_mapping.field',
    values: ['event.risk_score'],
    originalValue: ['event.risk_score'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.description',
    values: [
      'Generates a detection alert each time an Elastic Endpoint Security alert is received. Enabling this rule allows you to immediately begin investigating your Endpoint alerts.',
    ],
    originalValue: [
      'Generates a detection alert each time an Elastic Endpoint Security alert is received. Enabling this rule allows you to immediately begin investigating your Endpoint alerts.',
    ],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.pid',
    values: ['2'],
    originalValue: ['2'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.producer',
    values: ['siem'],
    originalValue: ['siem'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.to',
    values: ['now'],
    originalValue: ['now'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.rule.interval',
    values: ['5m'],
    originalValue: ['5m'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.rule.created_by',
    values: ['elastic'],
    originalValue: ['elastic'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.created_by',
    values: ['elastic'],
    originalValue: ['elastic'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.timestamp_override',
    values: ['event.ingested'],
    originalValue: ['event.ingested'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.original_event.ingested',
    values: ['2022-09-29T19:37:00.000Z'],
    originalValue: ['2022-09-29T19:37:00.000Z'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.rule.id',
    values: ['738e91f2-402e-11ed-be15-7be3bb26d7b2'],
    originalValue: ['738e91f2-402e-11ed-be15-7be3bb26d7b2'],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.parent.entity_id',
    values: ['kj0le842x0'],
    originalValue: ['kj0le842x0'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.rule.risk_score',
    values: ['47'],
    originalValue: ['47'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.reason',
    values: [
      'malware event with process explorer.exe, on Host-4cfuh42w7g created medium alert Endpoint Security.',
    ],
    originalValue: [
      'malware event with process explorer.exe, on Host-4cfuh42w7g created medium alert Endpoint Security.',
    ],
    isObjectArray: false,
  },
  {
    category: 'host',
    field: 'host.os.name',
    values: ['Windows'],
    originalValue: ['Windows'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.name',
    values: ['Endpoint Security'],
    originalValue: ['Endpoint Security'],
    isObjectArray: false,
  },
  {
    category: 'host',
    field: 'host.name',
    values: ['Host-4cfuh42w7g'],
    originalValue: ['Host-4cfuh42w7g'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.status',
    values: ['open'],
    originalValue: ['open'],
    isObjectArray: false,
  },
  {
    category: 'event',
    field: 'event.kind',
    values: ['signal'],
    originalValue: ['signal'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.severity_mapping.value',
    values: ['21', '47', '73', '99'],
    originalValue: ['21', '47', '73', '99'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.rule.tags',
    values: ['Elastic', 'Endpoint Security'],
    originalValue: ['Elastic', 'Endpoint Security'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.rule.created_at',
    values: ['2022-09-29T19:39:38.137Z'],
    originalValue: ['2022-09-29T19:39:38.137Z'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.workflow_status',
    values: ['open'],
    originalValue: ['open'],
    isObjectArray: false,
  },
  {
    category: 'Endpoint',
    field: 'Endpoint.policy.applied.status',
    values: ['warning'],
    originalValue: ['warning'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.uuid',
    values: ['738e91f2-402e-11ed-be15-7be3bb26d7b2'],
    originalValue: ['738e91f2-402e-11ed-be15-7be3bb26d7b2'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.original_event.category',
    values: ['malware'],
    originalValue: ['malware'],
    isObjectArray: false,
  },
  {
    category: 'dll',
    field: 'dll.Ext.malware_classification.threshold',
    values: ['0'],
    originalValue: ['0'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.reason',
    values: [
      'malware event with process explorer.exe, on Host-4cfuh42w7g created medium alert Endpoint Security.',
    ],
    originalValue: [
      'malware event with process explorer.exe, on Host-4cfuh42w7g created medium alert Endpoint Security.',
    ],
    isObjectArray: false,
  },
  {
    category: 'dll',
    field: 'dll.pe.architecture',
    values: ['x64'],
    originalValue: ['x64'],
    isObjectArray: false,
  },
  {
    category: 'data_stream',
    field: 'data_stream.type',
    values: ['logs'],
    originalValue: ['logs'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.original_time',
    values: ['2022-10-09T07:14:42.194Z'],
    originalValue: ['2022-10-09T07:14:42.194Z'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.ancestors.id',
    values: ['7L3AioMBWJvcpv7vlX2O'],
    originalValue: ['7L3AioMBWJvcpv7vlX2O'],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.name',
    values: ['explorer.exe'],
    originalValue: ['explorer.exe'],
    isObjectArray: false,
  },
  {
    category: 'ecs',
    field: 'ecs.version',
    values: ['1.6.0'],
    originalValue: ['1.6.0'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.rule.severity',
    values: ['medium'],
    originalValue: ['medium'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.ancestors.index',
    values: ['.ds-logs-endpoint.alerts-default-2022.09.29-000001'],
    originalValue: ['.ds-logs-endpoint.alerts-default-2022.09.29-000001'],
    isObjectArray: false,
  },
  {
    category: 'Endpoint',
    field: 'Endpoint.configuration.isolation',
    values: ['true'],
    originalValue: ['true'],
    isObjectArray: false,
  },
  {
    category: 'Memory_protection',
    field: 'Memory_protection.feature',
    values: ['signature'],
    originalValue: ['signature'],
    isObjectArray: false,
  },
  {
    category: 'dll',
    field: 'dll.code_signature.trusted',
    values: ['true'],
    originalValue: ['true'],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.Ext.code_signature.trusted',
    values: ['false'],
    originalValue: ['false'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.depth',
    values: ['1'],
    originalValue: ['1'],
    isObjectArray: false,
  },
  {
    category: 'agent',
    field: 'agent.version',
    values: ['8.6.0'],
    originalValue: ['8.6.0'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.risk_score_mapping.operator',
    values: ['equals'],
    originalValue: ['equals'],
    isObjectArray: false,
  },
  {
    category: 'host',
    field: 'host.os.family',
    values: ['windows'],
    originalValue: ['windows'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.from',
    values: ['now-10m'],
    originalValue: ['now-10m'],
    isObjectArray: false,
  },
  {
    category: 'Memory_protection',
    field: 'Memory_protection.self_injection',
    values: ['true'],
    originalValue: ['true'],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.start',
    values: ['2022-10-09T07:14:42.194Z'],
    originalValue: ['2022-10-09T07:14:42.194Z'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.severity_mapping.severity',
    values: ['low', 'medium', 'high', 'critical'],
    originalValue: ['low', 'medium', 'high', 'critical'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.severity_mapping.field',
    values: ['event.severity'],
    originalValue: ['event.severity'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.severity_mapping.value',
    values: ['21', '47', '73', '99'],
    originalValue: ['21', '47', '73', '99'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.severity_mapping.operator',
    values: ['equals'],
    originalValue: ['equals'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.references',
    values: [],
    originalValue: [],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.description',
    values: [
      'Generates a detection alert each time an Elastic Endpoint Security alert is received. Enabling this rule allows you to immediately begin investigating your Endpoint alerts.',
    ],
    originalValue: [
      'Generates a detection alert each time an Elastic Endpoint Security alert is received. Enabling this rule allows you to immediately begin investigating your Endpoint alerts.',
    ],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.language',
    values: ['kuery'],
    originalValue: ['kuery'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.type',
    values: ['query'],
    originalValue: ['query'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.rule_name_override',
    values: ['message'],
    originalValue: ['message'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.exceptions_list.list_id',
    values: ['endpoint_list'],
    originalValue: ['endpoint_list'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.exceptions_list.namespace_type',
    values: ['agnostic'],
    originalValue: ['agnostic'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.exceptions_list.id',
    values: ['endpoint_list'],
    originalValue: ['endpoint_list'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.exceptions_list.type',
    values: ['endpoint'],
    originalValue: ['endpoint'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.timestamp_override',
    values: ['event.ingested'],
    originalValue: ['event.ingested'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.from',
    values: ['now-10m'],
    originalValue: ['now-10m'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.severity',
    values: ['medium'],
    originalValue: ['medium'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.max_signals',
    values: ['10000'],
    originalValue: ['10000'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.risk_score',
    values: ['47'],
    originalValue: ['47'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.risk_score_mapping.field',
    values: ['event.risk_score'],
    originalValue: ['event.risk_score'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.risk_score_mapping.value',
    values: [''],
    originalValue: [''],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.risk_score_mapping.operator',
    values: ['equals'],
    originalValue: ['equals'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.author',
    values: ['Elastic'],
    originalValue: ['Elastic'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.query',
    values: ['event.kind:alert and event.module:(endpoint and not endgame)\n'],
    originalValue: ['event.kind:alert and event.module:(endpoint and not endgame)\n'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.index',
    values: ['logs-endpoint.alerts-*'],
    originalValue: ['logs-endpoint.alerts-*'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.version',
    values: ['100'],
    originalValue: ['100'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.rule_id',
    values: ['9a1a2dae-0b5f-4c3d-8305-a268d404c306'],
    originalValue: ['9a1a2dae-0b5f-4c3d-8305-a268d404c306'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.license',
    values: ['Elastic License v2'],
    originalValue: ['Elastic License v2'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.required_fields.ecs',
    values: ['true'],
    originalValue: ['true'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.required_fields.name',
    values: ['event.kind', 'event.module'],
    originalValue: ['event.kind', 'event.module'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.required_fields.type',
    values: ['keyword'],
    originalValue: ['keyword'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.immutable',
    values: ['true'],
    originalValue: ['true'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.related_integrations',
    values: [],
    originalValue: [],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.setup',
    values: [''],
    originalValue: [''],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.false_positives',
    values: [],
    originalValue: [],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.threat',
    values: [],
    originalValue: [],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.parameters.to',
    values: ['now'],
    originalValue: ['now'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.rule.version',
    values: ['100'],
    originalValue: ['100'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.original_event.kind',
    values: ['alert'],
    originalValue: ['alert'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.status',
    values: ['active'],
    originalValue: ['active'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.severity_mapping.field',
    values: ['event.severity', 'event.severity', 'event.severity', 'event.severity'],
    originalValue: ['event.severity', 'event.severity', 'event.severity', 'event.severity'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.original_event.dataset',
    values: ['endpoint'],
    originalValue: ['endpoint'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.depth',
    values: ['1'],
    originalValue: ['1'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.rule.immutable',
    values: ['true'],
    originalValue: ['true'],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.group_leader.pid',
    values: ['116'],
    originalValue: ['116'],
    isObjectArray: false,
  },
  {
    category: 'event',
    field: 'event.sequence',
    values: ['1232'],
    originalValue: ['1232'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.rule_type_id',
    values: ['siem.queryRule'],
    originalValue: ['siem.queryRule'],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.session_leader.name',
    values: ['fake session'],
    originalValue: ['fake session'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.rule.name',
    values: ['Endpoint Security'],
    originalValue: ['Endpoint Security'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.rule.rule_id',
    values: ['9a1a2dae-0b5f-4c3d-8305-a268d404c306'],
    originalValue: ['9a1a2dae-0b5f-4c3d-8305-a268d404c306'],
    isObjectArray: false,
  },
  {
    category: 'event',
    field: 'event.module',
    values: ['endpoint'],
    originalValue: ['endpoint'],
    isObjectArray: false,
  },
  {
    category: 'dll',
    field: 'dll.hash.sha1',
    values: ['ca85243c0af6a6471bdaa560685c51eefd6dbc0d'],
    originalValue: ['ca85243c0af6a6471bdaa560685c51eefd6dbc0d'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.severity_mapping.operator',
    values: ['equals', 'equals', 'equals', 'equals'],
    originalValue: ['equals', 'equals', 'equals', 'equals'],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.Ext.malware_signature.all_names',
    values: ['Windows.Trojan.FakeAgent'],
    originalValue: ['Windows.Trojan.FakeAgent'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.license',
    values: ['Elastic License v2'],
    originalValue: ['Elastic License v2'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.original_event.kind',
    values: ['alert'],
    originalValue: ['alert'],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.executable',
    values: ['C:/fake/explorer.exe'],
    originalValue: ['C:/fake/explorer.exe'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.updated_at',
    values: ['2022-09-29T19:39:38.137Z'],
    originalValue: ['2022-09-29T19:39:38.137Z'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.rule.description',
    values: [
      'Generates a detection alert each time an Elastic Endpoint Security alert is received. Enabling this rule allows you to immediately begin investigating your Endpoint alerts.',
    ],
    originalValue: [
      'Generates a detection alert each time an Elastic Endpoint Security alert is received. Enabling this rule allows you to immediately begin investigating your Endpoint alerts.',
    ],
    isObjectArray: false,
  },
  {
    category: 'dll',
    field: 'dll.Ext.mapped_size',
    values: ['0'],
    originalValue: ['0'],
    isObjectArray: false,
  },
  {
    category: 'data_stream',
    field: 'data_stream.namespace',
    values: ['default'],
    originalValue: ['default'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.author',
    values: ['Elastic'],
    originalValue: ['Elastic'],
    isObjectArray: false,
  },
  {
    category: 'dll',
    field: 'dll.code_signature.subject_name',
    values: ['Cybereason Inc'],
    originalValue: ['Cybereason Inc'],
    isObjectArray: false,
  },
  {
    category: 'user',
    field: 'user.name',
    values: ['root'],
    originalValue: ['root'],
    isObjectArray: false,
  },
  {
    category: 'source',
    field: 'source.ip',
    values: ['10.184.3.46'],
    originalValue: ['10.184.3.46'],
    isObjectArray: false,
  },
  {
    category: 'Endpoint',
    field: 'Endpoint.policy.applied.endpoint_policy_version',
    values: ['3'],
    originalValue: ['3'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.original_event.sequence',
    values: ['1232'],
    originalValue: ['1232'],
    isObjectArray: false,
  },
  {
    category: 'dll',
    field: 'dll.path',
    values: ['C:\\Program Files\\Cybereason ActiveProbe\\AmSvc.exe'],
    originalValue: ['C:\\Program Files\\Cybereason ActiveProbe\\AmSvc.exe'],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.Ext.user',
    values: ['SYSTEM'],
    originalValue: ['SYSTEM'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.original_event.action',
    values: ['start'],
    originalValue: ['start'],
    isObjectArray: false,
  },
  {
    category: 'signal',
    field: 'signal.rule.to',
    values: ['now'],
    originalValue: ['now'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.created_at',
    values: ['2022-09-29T19:39:38.137Z'],
    originalValue: ['2022-09-29T19:39:38.137Z'],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.Ext.malware_signature.identifier',
    values: ['diagnostic-malware-signature-v1-fake'],
    originalValue: ['diagnostic-malware-signature-v1-fake'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.exceptions_list.namespace_type',
    values: ['agnostic'],
    originalValue: ['agnostic'],
    isObjectArray: false,
  },
  {
    category: 'event',
    field: 'event.type',
    values: ['info'],
    originalValue: ['info'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.space_ids',
    values: ['default'],
    originalValue: ['default'],
    isObjectArray: false,
  },
  {
    category: 'process',
    field: 'process.entry_leader.entity_id',
    values: ['b74mw1jkrm'],
    originalValue: ['b74mw1jkrm'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.rule.exceptions_list.id',
    values: ['endpoint_list'],
    originalValue: ['endpoint_list'],
    isObjectArray: false,
  },
  {
    category: 'event',
    field: 'event.dataset',
    values: ['endpoint'],
    originalValue: ['endpoint'],
    isObjectArray: false,
  },
  {
    category: 'kibana',
    field: 'kibana.alert.original_time',
    values: ['2022-10-09T07:14:42.194Z'],
    originalValue: ['2022-10-09T07:14:42.194Z'],
    isObjectArray: false,
  },
  {
    category: '_index',
    field: '_index',
    values: ['.internal.alerts-security.alerts-default-000001'],
    originalValue: ['.internal.alerts-security.alerts-default-000001'],
    isObjectArray: false,
  },
  {
    category: '_id',
    field: '_id',
    values: ['f6aa8643ecee466753c45308ea8dc72aba0a44e1faac5f6183fd2ad6666c1325'],
    originalValue: ['f6aa8643ecee466753c45308ea8dc72aba0a44e1faac5f6183fd2ad6666c1325'],
    isObjectArray: false,
  },
  {
    category: '_score',
    field: '_score',
    values: ['1'],
    originalValue: ['1'],
    isObjectArray: false,
  },
];

export const getMockAlertNestedDetailsTimelineResponse = (): Ecs => ({
  _id: 'f6aa8643ecee466753c45308ea8dc72aba0a44e1faac5f6183fd2ad6666c1325',
  timestamp: '2022-09-29T19:40:26.051Z',
  _index: '.internal.alerts-security.alerts-default-000001',
  kibana: {
    alert: {
      rule: {
        from: ['now-10m'],
        name: ['Endpoint Security'],
        to: ['now'],
        uuid: ['738e91f2-402e-11ed-be15-7be3bb26d7b2'],
        type: ['query'],
        version: ['100'],
        parameters: {},
      },
      workflow_status: ['open'],
      original_time: ['2022-10-09T07:14:42.194Z'],
      severity: ['medium'],
    },
  },
  event: {
    code: ['memory_signature'],
    module: ['endpoint'],
    action: ['start'],
    category: ['malware'],
    dataset: ['endpoint'],
    id: ['7799e1d5-5dc1-4173-9d11-562496cd863b'],
    kind: ['signal'],
    type: ['info'],
  },
  host: {
    name: ['Host-4cfuh42w7g'],
    os: {
      family: ['windows'],
      name: ['Windows'],
    },
    id: ['04794e4e-59cb-4c4a-a8ee-3e6c5b65743c'],
    ip: ['10.184.3.36', '10.170.218.86'],
  },
  source: {
    ip: ['10.184.3.46'],
  },
  agent: {
    type: ['endpoint'],
    id: ['d08ed3f8-9852-4d0c-a5b1-b48060705369'],
  },
  process: {
    hash: {
      md5: ['fake md5'],
      sha1: ['fake sha1'],
      sha256: ['fake sha256'],
    },
    parent: {
      pid: [1],
    },
    pid: [2],
    name: ['explorer.exe'],
    entity_id: ['d3v4to81q9'],
    executable: ['C:/fake/explorer.exe'],
    entry_leader: {
      entity_id: ['b74mw1jkrm'],
      name: ['fake entry'],
      pid: ['865'],
    },
    session_leader: {
      entity_id: ['b74mw1jkrm'],
      name: ['fake session'],
      pid: ['745'],
    },
    group_leader: {
      entity_id: ['b74mw1jkrm'],
      name: ['fake leader'],
      pid: ['116'],
    },
  },
  user: {
    name: ['root'],
  },
});

export const mockAlertDetailsFieldsResponse = getMockAlertDetailsFieldsResponse();

export const mockAlertDetailsTimelineResponse = getMockAlertDetailsTimelineResponse();

export const mockAlertNestedDetailsTimelineResponse = getMockAlertNestedDetailsTimelineResponse();
