import type { AllCasesTableState } from '../components/all_cases/types';
import type { FilterOptions, QueryParams, SingleCaseMetricsFeature } from './types';
export declare const DEFAULT_TABLE_ACTIVE_PAGE = 1;
export declare const DEFAULT_TABLE_LIMIT = 10;
export declare const casesQueriesKeys: {
    all: readonly ["cases"];
    users: readonly ["users"];
    connectors: readonly ["connectors"];
    alerts: readonly ["alerts"];
    userActions: readonly ["user-actions"];
    templates: readonly ["templates"];
    template: (templateId: string, version?: number, includeDeleted?: boolean) => readonly ["templates", "detail", string, number | "latest", boolean];
    templatesList: () => readonly ["templates", "list"];
    templatesAll: (params: unknown) => readonly ["templates", "list", unknown];
    templatesTags: () => readonly ["templates", "tags"];
    templatesCreators: () => readonly ["templates", "creators"];
    fieldDefinitions: readonly ["field-definitions"];
    fieldDefinitionsList: (params: unknown) => readonly ["field-definitions", "list", unknown];
    connectorsList: () => readonly ["connectors", "list"];
    casesList: () => readonly ["cases", "list"];
    casesMetrics: () => readonly ["cases", "list", "metrics"];
    casesStatuses: () => readonly ["cases", "list", "statuses"];
    cases: (params: unknown) => readonly ["cases", "list", "all-cases", unknown];
    similarCases: (id: string, params: unknown) => readonly ["cases", "case", string, "similar", unknown];
    caseView: () => readonly ["cases", "case"];
    case: (id: string) => readonly ["cases", "case", string];
    caseFiles: (id: string, params: unknown) => readonly ["cases", "case", string, "files", unknown];
    caseFileStats: (id: string, params?: unknown) => readonly ["cases", "case", string, "files", "stats", unknown];
    caseMetrics: (id: string, features: SingleCaseMetricsFeature[]) => readonly ["cases", "case", string, "metrics", SingleCaseMetricsFeature[]];
    caseConnectors: (id: string) => string[];
    caseUsers: (id: string) => string[];
    caseUserActions: (id: string, params: unknown) => readonly ["cases", "case", string, "user-actions", unknown];
    caseUserActionsStats: (id: string) => string[];
    userProfiles: () => readonly ["users", "user-profiles"];
    userProfilesList: (ids: string[]) => readonly ["users", "user-profiles", string[]];
    currentUser: () => readonly ["users", "current-user"];
    suggestUsers: (params: unknown) => readonly ["users", "suggest", unknown];
    connectorTypes: () => readonly ["connectors", "types"];
    license: () => readonly ["connectors", "license"];
    tags: () => readonly ["cases", "tags"];
    categories: () => readonly ["cases", "categories"];
    alertFeatureIds: (alertIds: string[]) => readonly ["alerts", "features", string[]];
    configuration: (params: unknown) => readonly ["cases", "configuration", unknown];
};
export declare const casesMutationsKeys: {
    createCase: readonly ["create-case"];
    deleteCases: readonly ["delete-cases"];
    updateCase: readonly ["update-case"];
    updateCases: readonly ["update-cases"];
    pushCase: readonly ["push-case"];
    updateComment: readonly ["update-comment"];
    deleteComment: readonly ["delete-comment"];
    deleteFileAttachment: readonly ["delete-file-attachment"];
    bulkCreateAttachments: readonly ["bulk-create-attachments"];
    persistCaseConfiguration: readonly ["persist-case-configuration"];
    replaceCustomField: readonly ["replace-custom-field"];
    postObservable: readonly ["post-observable"];
    patchObservable: readonly ["patch-observable"];
    deleteObservable: readonly ["delete-observable"];
    bulkPostObservables: readonly ["bulk-post-observables"];
    createTemplate: readonly ["create-template"];
    updateTemplate: readonly ["update-template"];
    deleteTemplate: readonly ["delete-template"];
    createFieldDefinition: readonly ["create-field-definition"];
    updateFieldDefinition: readonly ["update-field-definition"];
    deleteFieldDefinition: readonly ["delete-field-definition"];
    exportTemplate: readonly ["export-template"];
    bulkDeleteTemplates: readonly ["bulk-delete-templates"];
    bulkExportTemplates: readonly ["bulk-export-templates"];
    changeAppliedTemplate: readonly ["change-applied-template"];
};
export declare const inferenceKeys: {
    getConnectors: () => readonly ["get-inference-connectors"];
};
export declare const DEFAULT_FROM_DATE = "now-30d";
export declare const DEFAULT_TO_DATE = "now";
export declare const DEFAULT_FILTER_OPTIONS: FilterOptions;
export declare const DEFAULT_QUERY_PARAMS: QueryParams;
export declare const DEFAULT_CASES_TABLE_STATE: AllCasesTableState;
