[[logstash-configuration-management-api-create]]
=== Create Pipeline

experimental[This functionality is experimental and may be changed or removed completely in a future release.]

The Create Pipeline API enables you to create a centrally-managed Logstash Pipeline.

==== Request

`PUT /api/logstash/pipeline/<id>`

==== Path Parameters

`id` (required)::
  (string) ID for pipeline. Only alphanumeric characters, hyphens, and underscores may be used.



==== Request Body

`description` (optional)::
  (string) Description for the pipeline

`pipeline` (required)::
  (string) Pipeline definition

`settings` (optional)::
  (object) Pipeline settings. Supported settings, represented as object keys, are `pipeline.workers`, `pipeline.batch.size`, `pipeline.batch.delay`, `queue.type`, `queue.max_bytes`, and `queue.checkpoint.writes`


==== Examples

[source,js]
--------------------------------------------------
PUT api/logstash/pipeline/hello-world
{
  "pipeline": "input { stdin {} } output { stdout {} }",
  "settings": {
    "queue.type": "persistent"
  }
}
--------------------------------------------------
// KIBANA

A successful call returns a JSON structure similar to the following example:

[source,js]
--------------------------------------------------
{
  "id": "getting-started",
  "username": "elastic", <1>
  "pipeline": "input { stdin {} } output { stdout {} }",
  "settings": {
    "queue.type": "persistent"
  }
}
--------------------------------------------------

<1> This will be the username of the Elasticsearch Security user used when making the the API request