[role="xpack"]
[[logstash-configuration-management-api-create]]
=== Create Pipeline

experimental[This functionality is *experimental* and may be changed or removed completely in a future release.]

The Create Pipeline API enables you to create a centrally-managed Logstash pipeline. You can also use
it to update an existing pipeline.

Note: You cannot access this endpoint via the Console in Kibana.

[float]
==== Request

`PUT /api/logstash/pipeline/<id>`

[float]
==== Path Parameters

`id` (required)::
  (string) ID for pipeline. Only alphanumeric characters, hyphens, and underscores may be used.


[float]
==== Request Body

`description` (optional)::
  (string) Description for the pipeline

`pipeline` (required)::
  (string) Pipeline definition

`settings` (optional)::
  (object) Pipeline settings. Supported settings, represented as object keys, are `pipeline.workers`, `pipeline.batch.size`, `pipeline.batch.delay`, `queue.type`, `queue.max_bytes`, and `queue.checkpoint.writes`


[float]
==== Examples

[source,js]
--------------------------------------------------
PUT api/logstash/pipeline/hello-world
{
  "pipeline": "input { stdin {} } output { stdout {} }",
  "settings": {
    "queue.type": "persisted"
  }
}
--------------------------------------------------
// KIBANA

A successful call returns an HTTP `204 No Content` response.
