/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

export type TestSubjects =
  | 'aliasesTabContent'
  | 'appTitle'
  | 'cell'
  | 'indexManagementHeaderContent'
  | 'noIndicesMessage'
  | 'component_templatesTab'
  | 'data_streamsTab'
  | 'closeDetailsButton'
  | 'createLegacyTemplateButton'
  | 'createTemplateButton'
  | 'dataStreamsEmptyPromptTemplateLink'
  | 'dataStreamTable'
  | 'deleteDataStreamsButton'
  | 'deleteDataStreamButton'
  | 'deleteSystemTemplateCallOut'
  | 'deleteTemplateButton'
  | 'deleteTemplatesConfirmation'
  | 'documentationLink'
  | 'emptyPrompt'
  | 'filterList.filterItem'
  | 'ilmPolicyLink'
  | 'includeStatsSwitch'
  | 'includeManagedSwitch'
  | 'indexTable'
  | 'indexTableIncludeHiddenIndicesToggle'
  | 'indexTableIndexNameLink'
  | 'indexContextMenu'
  | 'indexTableContextMenuButton_closeindex'
  | 'indexTableContextMenuButton_openindex'
  | 'indicesList'
  | 'indicesTab'
  | 'legacyTemplateTable'
  | 'manageTemplateButton'
  | 'mappingsTabContent'
  | 'noAliasesCallout'
  | 'noMappingsCallout'
  | 'noSettingsCallout'
  | 'previewTabContent'
  | 'reloadButton'
  | 'reloadIndicesButton'
  | 'row'
  | 'sectionError'
  | 'sectionLoading'
  | 'settingsTabContent'
  | 'simulateTemplatePreview'
  | 'summaryTab'
  | 'summaryTitle'
  | 'systemTemplatesSwitch'
  | 'templateDetails'
  | 'templateDetails.manageTemplateButton'
  | 'templateDetails.sectionLoading'
  | 'templateDetails.tab'
  | 'templateDetails.title'
  | 'templateList'
  | 'templatesTab'
  | 'templateTable'
  | 'title'
  | 'viewButton';
