/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License;
 * you may not use this file except in compliance with the Elastic License.
 */

export type TestSubjects =
  | 'aliasesTab'
  | 'appTitle'
  | 'cell'
  | 'closeDetailsButton'
  | 'createLegacyTemplateButton'
  | 'createTemplateButton'
  | 'dataStreamTable'
  | 'dataStreamTable'
  | 'deleteSystemTemplateCallOut'
  | 'deleteTemplateButton'
  | 'deleteTemplatesConfirmation'
  | 'documentationLink'
  | 'emptyPrompt'
  | 'filterList.filterItem'
  | 'indexTable'
  | 'indexTableIncludeHiddenIndicesToggle'
  | 'indexTableIndexNameLink'
  | 'indicesList'
  | 'indicesTab'
  | 'legacyTemplateTable'
  | 'manageTemplateButton'
  | 'mappingsTab'
  | 'noAliasesCallout'
  | 'noMappingsCallout'
  | 'noSettingsCallout'
  | 'reloadButton'
  | 'reloadIndicesButton'
  | 'row'
  | 'sectionError'
  | 'sectionLoading'
  | 'settingsTab'
  | 'summaryTab'
  | 'summaryTitle'
  | 'systemTemplatesSwitch'
  | 'templateDetails'
  | 'templateDetails.manageTemplateButton'
  | 'templateDetails.sectionLoading'
  | 'templateDetails.tab'
  | 'templateDetails.title'
  | 'templateList'
  | 'templatesTab'
  | 'templateTable'
  | 'viewButton';
