export type { AsDuration, AsPercent, TimeUnitChar, TimeFormatter } from './utils/formatters';
export { formatDurationFromTimeUnitChar, asPercent, getDurationFormatter, asDuration, asDynamicBytes, asAbsoluteDateTime, asInteger, } from './utils/formatters';
export { getInspectResponse } from './utils/get_inspect_response';
export { getAlertDetailsUrl, getAlertUrl } from './utils/alerting/alert_url';
export { convertToBuiltInComparators } from './utils/convert_legacy_outside_comparator';
export { ProcessorEvent } from './processor_event';
export { ElapsedTimestampTooltip } from './components/elapsed_timestamp_tooltip';
export { enableInspectEsQueries, maxSuggestions, enableComparisonByDefault, defaultApmServiceEnvironment, apmProgressiveLoading, apmServiceGroupMaxNumberOfServices, enableInfrastructureAssetCustomDashboards, apmEnableTableSearchBar, apmAWSLambdaPriceFactor, apmAWSLambdaRequestCostPerMillion, syntheticsThrottlingEnabled, profilingShowErrorFrames, profilingCo2PerKWH, profilingDatacenterPUE, profilingPervCPUWattX86, profilingPervCPUWattArm64, profilingAWSCostDiscountRate, profilingCostPervCPUPerHour, profilingAzureCostDiscountRate, apmEnableTransactionProfiling, apmEnableServiceInventoryTableSearchBar, enableDiagnosticMode, } from './ui_settings_keys';
export { ProgressiveLoadingQuality, getProbabilityFromProgressiveLoadingQuality, } from './progressive_loading';
/** @deprecated deprecated in 8.17. Please use casesFeatureIdV2 instead */
export declare const casesFeatureId = "observabilityCases";
export declare const casesFeatureIdV2 = "observabilityCasesV2";
export declare const casesFeatureIdV3 = "observabilityCasesV3";
export declare const sloFeatureId = "slo";
export declare const observabilityAppId = "observability-overview";
export declare const observabilityFeatureId = "observability";
export { uptimeOverviewLocatorID } from '@kbn/deeplinks-observability';
export declare const casesOverviewLocatorID = "OBSERVABILITY_CASES_OVERVIEW_LOCATOR";
export declare const casesDetailLocatorID = "OBSERVABILITY_CASES_DETAIL_LOCATOR";
export declare const syntheticsMonitorDetailLocatorID = "SYNTHETICS_MONITOR_DETAIL_LOCATOR";
export declare const syntheticsMonitorLocationQueryLocatorID = "SYNTHETICS_MONITOR_GROUP_BY_LOCATION_LOCATOR";
export declare const syntheticsEditMonitorLocatorID = "SYNTHETICS_EDIT_MONITOR_LOCATOR";
export declare const syntheticsAddMonitorLocatorID = "SYNTHETICS_ADD_MONITOR_LOCATOR";
export declare const syntheticsSettingsLocatorID = "SYNTHETICS_SETTINGS";
export declare const alertsLocatorID = "ALERTS_LOCATOR";
export declare const observabilityPaths: {
    alerts: string;
    annotations: string;
    alertDetails: (alertId: string) => string;
    rules: string;
    ruleDetails: (ruleId: string) => string;
    createRule: (ruleTypeId: string) => string;
    createRuleFromTemplate: (templateId: string) => string;
    editRule: (id: string) => string;
};
export type { AlertsLocator, AlertsLocatorParams } from './locators/alerts';
export { AlertsLocatorDefinition } from './locators/alerts';
export { observabilityAlertFeatureIds } from './constants';
export { OBSERVABILITY_TIERED_FEATURES, OBSERVABILITY_COMPLETE_LANDING_PAGE_FEATURE, } from './product_features';
export { NOT_AVAILABLE_LABEL } from './i18n';
