/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Automatic Import Integrations API endpoint
 *   version: 1
 */

import { z, lazySchema } from '@kbn/zod/v4';

import { NonEmptyString, SafeIdentifier, SemVer } from '../../primitive.gen';
import {
  LangSmithOptions,
  DataStream,
  AllIntegrationsResponseIntegration,
  InputType,
  IntegrationResponse,
} from '../../common_attributes.gen';

/**
 * The intent of the download request.
 */
export const DownloadIntent = lazySchema(() => z.enum(['download', 'install']));
export type DownloadIntent = z.infer<typeof DownloadIntent>;
export type DownloadIntentEnum = typeof DownloadIntent.enum;
export const DownloadIntentEnum = DownloadIntent.enum;

export const ApproveIntegrationRequest = lazySchema(() =>
  z
    .object({
      /**
       * The version of the integration
       */
      version: SemVer.describe('The version of the integration'),
      /**
       * The categories of the integration
       */
      categories: z
        .array(NonEmptyString)
        .min(1)
        .max(50)
        .describe('The categories of the integration'),
      /**
       * The LangSmith tracing options
       */
      langSmithOptions: LangSmithOptions.optional().describe('The LangSmith tracing options'),
    })
    .strict()
);
export type ApproveIntegrationRequest = z.infer<typeof ApproveIntegrationRequest>;

export const ApproveAutoImportIntegrationRequestParams = lazySchema(() =>
  z.object({
    /**
     * The integration identifier
     */
    integration_id: SafeIdentifier.describe('The integration identifier'),
  })
);
export type ApproveAutoImportIntegrationRequestParams = z.infer<
  typeof ApproveAutoImportIntegrationRequestParams
>;
export type ApproveAutoImportIntegrationRequestParamsInput = z.input<
  typeof ApproveAutoImportIntegrationRequestParams
>;

export const ApproveAutoImportIntegrationRequestBody = lazySchema(() => ApproveIntegrationRequest);
export type ApproveAutoImportIntegrationRequestBody = z.infer<
  typeof ApproveAutoImportIntegrationRequestBody
>;
export type ApproveAutoImportIntegrationRequestBodyInput = z.input<
  typeof ApproveAutoImportIntegrationRequestBody
>;

export const CreateAutoImportIntegrationRequestBody = lazySchema(() =>
  z
    .object({
      /**
       * The connector id
       */
      connectorId: NonEmptyString.describe('The connector id'),
      /**
       * The integration id
       */
      integrationId: SafeIdentifier.describe('The integration id'),
      /**
       * The title of the integration
       */
      title: NonEmptyString.describe('The title of the integration'),
      /**
       * The description of the integration
       */
      description: NonEmptyString.describe('The description of the integration'),
      /**
       * The LangSmith tracing options
       */
      langSmithOptions: LangSmithOptions.optional().describe('The LangSmith tracing options'),
      /**
       * The logo of the integration
       */
      logo: NonEmptyString.optional().describe('The logo of the integration'),
      /**
       * The data streams of the integration
       */
      dataStreams: z
        .array(DataStream)
        .max(50)
        .optional()
        .describe('The data streams of the integration'),
    })
    .strict()
);
export type CreateAutoImportIntegrationRequestBody = z.infer<
  typeof CreateAutoImportIntegrationRequestBody
>;
export type CreateAutoImportIntegrationRequestBodyInput = z.input<
  typeof CreateAutoImportIntegrationRequestBody
>;

export const CreateAutoImportIntegrationResponse = lazySchema(() =>
  z
    .object({
      /**
       * The integration id created in state.
       */
      integration_id: NonEmptyString.optional().describe('The integration id created in state.'),
    })
    .strict()
);
export type CreateAutoImportIntegrationResponse = z.infer<
  typeof CreateAutoImportIntegrationResponse
>;

export const DeleteAutoImportIntegrationRequestParams = lazySchema(() =>
  z.object({
    /**
     * The integration identifier
     */
    integration_id: SafeIdentifier.describe('The integration identifier'),
  })
);
export type DeleteAutoImportIntegrationRequestParams = z.infer<
  typeof DeleteAutoImportIntegrationRequestParams
>;
export type DeleteAutoImportIntegrationRequestParamsInput = z.input<
  typeof DeleteAutoImportIntegrationRequestParams
>;

export const DownloadAutoImportIntegrationRequestQuery = lazySchema(() =>
  z.object({
    /**
     * The intent of the download request. When set to 'install', install telemetry is reported.
     */
    intent: DownloadIntent.optional().describe(
      "The intent of the download request. When set to 'install', install telemetry is reported."
    ),
  })
);
export type DownloadAutoImportIntegrationRequestQuery = z.infer<
  typeof DownloadAutoImportIntegrationRequestQuery
>;
export type DownloadAutoImportIntegrationRequestQueryInput = z.input<
  typeof DownloadAutoImportIntegrationRequestQuery
>;

export const DownloadAutoImportIntegrationRequestParams = lazySchema(() =>
  z.object({
    /**
     * The integration identifier
     */
    integration_id: SafeIdentifier.describe('The integration identifier'),
  })
);
export type DownloadAutoImportIntegrationRequestParams = z.infer<
  typeof DownloadAutoImportIntegrationRequestParams
>;
export type DownloadAutoImportIntegrationRequestParamsInput = z.input<
  typeof DownloadAutoImportIntegrationRequestParams
>;

export const GetAllAutoImportIntegrationsResponse = lazySchema(() =>
  z.array(AllIntegrationsResponseIntegration)
);
export type GetAllAutoImportIntegrationsResponse = z.infer<
  typeof GetAllAutoImportIntegrationsResponse
>;

export const GetAutoImportIntegrationRequestParams = lazySchema(() =>
  z.object({
    /**
     * The integration identifier
     */
    integration_id: SafeIdentifier.describe('The integration identifier'),
  })
);
export type GetAutoImportIntegrationRequestParams = z.infer<
  typeof GetAutoImportIntegrationRequestParams
>;
export type GetAutoImportIntegrationRequestParamsInput = z.input<
  typeof GetAutoImportIntegrationRequestParams
>;

export const GetAutoImportIntegrationResponse = lazySchema(() =>
  z
    .object({
      integrationResponse: IntegrationResponse,
    })
    .strict()
);
export type GetAutoImportIntegrationResponse = z.infer<typeof GetAutoImportIntegrationResponse>;

export const UpdateAutoImportIntegrationRequestParams = lazySchema(() =>
  z.object({
    /**
     * The integration identifier
     */
    integration_id: SafeIdentifier.describe('The integration identifier'),
  })
);
export type UpdateAutoImportIntegrationRequestParams = z.infer<
  typeof UpdateAutoImportIntegrationRequestParams
>;
export type UpdateAutoImportIntegrationRequestParamsInput = z.input<
  typeof UpdateAutoImportIntegrationRequestParams
>;

export const UpdateAutoImportIntegrationRequestBody = lazySchema(() =>
  z
    .object({
      /**
       * Integration description
       */
      description: NonEmptyString.optional().describe('Integration description'),
      /**
       * Integration logo image blob
       */
      logo: NonEmptyString.optional().describe('Integration logo image blob'),
      /**
       * The LangSmith tracing options
       */
      langSmithOptions: LangSmithOptions.optional().describe('The LangSmith tracing options'),
      /**
       * The data streams of the integration
       */
      dataStreams: z
        .array(
          z
            .object({
              /**
               * The description of the data stream
               */
              description: NonEmptyString.optional().describe('The description of the data stream'),
              /**
               * The input types of the data stream
               */
              inputTypes: z
                .array(InputType)
                .max(100)
                .optional()
                .describe('The input types of the data stream'),
              /**
               * The raw samples of the data stream
               */
              rawSamples: z
                .array(NonEmptyString)
                .max(1000)
                .optional()
                .describe('The raw samples of the data stream'),
            })
            .strict()
        )
        .max(50)
        .optional()
        .describe('The data streams of the integration'),
    })
    .strict()
);
export type UpdateAutoImportIntegrationRequestBody = z.infer<
  typeof UpdateAutoImportIntegrationRequestBody
>;
export type UpdateAutoImportIntegrationRequestBodyInput = z.input<
  typeof UpdateAutoImportIntegrationRequestBody
>;
