[[maintenance-windows]]
== Maintenance windows

preview::[]

Schedule single or recurring maintenance windows to temporarily reduce rule notifications.
For example, a maintenance window prevents false alarms during planned outages.

Alerts continue to be generated during maintenance windows, however notifications are suppressed as follows:

- When an alert occurs during a maintenance window, there are no notifications.
When the alert recovers, there are no notifications--even if the recovery occurs after the maintenance window ends.
- When an alert occurs before a maintenance window and recovers during or after the maintenance window, notifications are sent as usual.

[discrete]
[[setup-maintenance-windows]]
== Configure access to maintenance windows

To access maintenance windows in *{stack-manage-app}*, you must have the appropriate {kib} privileges:

- To have full access to maintenance windows, you must have `All` privileges for the *Maintenance Windows* feature under *Management*.
- To have view-only access to maintenance windows, you must have `Read` privileges for the *Maintenance Windows* feature under *Management*.

For more details, refer to <<kibana-privileges>>.
