/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

import type { Datatable } from '@kbn/expressions-plugin/common';

export const mockESQLResponse: Datatable = {
  type: 'datatable',
  meta: {
    type: 'es_ql',
  },
  columns: [
    {
      id: '@timestamp',
      name: '@timestamp',
      meta: {
        type: 'date',
        esType: 'date',
      },
      isNull: false,
    },
    {
      id: 'agent.type',
      name: 'agent.type',
      meta: {
        type: 'string',
        esType: 'keyword',
      },
      isNull: false,
    },
    {
      id: 'process.args',
      name: 'process.args',
      meta: {
        type: 'string',
        esType: 'keyword',
      },
      isNull: false,
    },
    {
      id: 'source.ip',
      name: 'source.ip',
      meta: {
        type: 'ip',
        esType: 'ip',
      },
      isNull: false,
    },
    {
      id: 'destination.ip',
      name: 'destination.ip',
      meta: {
        type: 'ip',
        esType: 'ip',
      },
      isNull: false,
    },
    {
      id: 'user.name',
      name: 'user.name',
      meta: {
        type: 'string',
        esType: 'keyword',
      },
      isNull: false,
    },
    {
      id: 'host.name',
      name: 'host.name',
      meta: {
        type: 'string',
        esType: 'keyword',
      },
      isNull: false,
    },
    {
      id: 'event.kind',
      name: 'event.kind',
      meta: {
        type: 'string',
        esType: 'keyword',
      },
      isNull: false,
    },
    {
      id: 'process.uptime',
      name: 'process.uptime',
      meta: {
        type: 'number',
        esType: 'long',
      },
      isNull: true,
    },
    {
      id: 'message',
      name: 'message',
      meta: {
        type: 'string',
        esType: 'text',
      },
      isNull: true,
    },
  ],
  rows: [
    {
      '@timestamp': '2024-05-21T08:54:19.671Z',
      'agent.type': 'endpoint',
      'process.args': null,
      'source.ip': '10.67.3.17',
      'destination.ip': '10.102.28.68',
      'user.name': 'g23t2xt5qf',
      'host.name': 'Host-7hkeyye28q',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T08:55:20.682Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\explorer.exe"', '--v1s'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': 'xqe9xxsda6',
      'host.name': 'Host-u6lxydi7eh',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T08:55:20.683Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\notepad.exe"', '--mqy'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': 'rgi7ixr56a',
      'host.name': 'Host-u6lxydi7eh',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T08:55:20.684Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\notepad.exe"', '--ew0'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': 'm1dyfn9fu1',
      'host.name': 'Host-u6lxydi7eh',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T08:55:20.685Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\iexlorer.exe"', '--qb9'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': '7arntokvhw',
      'host.name': 'Host-u6lxydi7eh',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T08:56:23.747Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\lsass.exe"', '--1p7'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': 'tnfeq0lck0',
      'host.name': 'Host-wo43rhsnym',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T08:56:23.749Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\iexlorer.exe"', '--r7f'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': 'u2qkddbf1b',
      'host.name': 'Host-wo43rhsnym',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T08:56:23.750Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\mimikatz.exe"', '--3up'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': 'qrr5p49at0',
      'host.name': 'Host-wo43rhsnym',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T08:56:23.751Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\explorer.exe"', '--2uk'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': 'ceosleczbp',
      'host.name': 'Host-wo43rhsnym',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T08:56:23.753Z',
      'agent.type': 'endpoint',
      'process.args': null,
      'source.ip': '10.249.145.153',
      'destination.ip': '10.13.40.160',
      'user.name': 'ksqtro7dt2',
      'host.name': 'Host-wo43rhsnym',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T08:57:26.712Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\mimikatz.exe"', '--avj'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': '727dpjl3te',
      'host.name': 'Host-5ugh9bs0ge',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T08:57:26.713Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\powershell.exe"', '--eyd'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': '0ebgog70hw',
      'host.name': 'Host-5ugh9bs0ge',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T08:57:26.714Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\iexlorer.exe"', '--n42'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': 'pg81wesd40',
      'host.name': 'Host-5ugh9bs0ge',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T08:57:26.715Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\mimikatz.exe"', '--tqk'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': 'koq54mnqb9',
      'host.name': 'Host-5ugh9bs0ge',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T08:58:29.719Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\explorer.exe"', '--o1x'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': '0dekk8h99y',
      'host.name': 'Host-e425ope77i',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T08:58:29.720Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\mimikatz.exe"', '--efb'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': '257q08u7co',
      'host.name': 'Host-e425ope77i',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T08:58:29.721Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\explorer.exe"', '--x6t'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': '5n1tpruevi',
      'host.name': 'Host-e425ope77i',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T08:58:29.721Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\iexlorer.exe"', '--fyv'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': 'chgjmzgmu1',
      'host.name': 'Host-e425ope77i',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T08:58:29.723Z',
      'agent.type': 'endpoint',
      'process.args': null,
      'source.ip': '10.13.77.185',
      'destination.ip': '10.73.228.245',
      'user.name': 'uulpu94m5t',
      'host.name': 'Host-e425ope77i',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T08:58:29.724Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\lsass.exe"', '--ead'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': 'kow8vlkbwd',
      'host.name': 'Host-e425ope77i',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T08:59:32.967Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\notepad.exe"', '--b93'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': 'wcrul3q5ia',
      'host.name': 'Host-e026sxe8p4',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T08:59:32.970Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\notepad.exe"', '--eqp'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': 't4exi4feni',
      'host.name': 'Host-e026sxe8p4',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T08:59:32.975Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\mimikatz.exe"', '--zru'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': 'kcmcwec0w6',
      'host.name': 'Host-e026sxe8p4',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T08:59:32.977Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\mimikatz.exe"', '--f2j'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': '8kvyh0c1op',
      'host.name': 'Host-e026sxe8p4',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T09:00:35.709Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\powershell.exe"', '--xmc'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': 'z8w57fjhfj',
      'host.name': 'Host-24808d342m',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T09:00:35.710Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\mimikatz.exe"', '--015'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': '9bt2kgraf3',
      'host.name': 'Host-24808d342m',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T09:00:35.710Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\iexlorer.exe"', '--7uj'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': '99sw7b7si3',
      'host.name': 'Host-24808d342m',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T09:01:38.735Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\powershell.exe"', '--tye'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': 'a2zeuahj0i',
      'host.name': 'Host-po707ju4yb',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T09:01:38.738Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\powershell.exe"', '--qly'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': 'kj19jh9a05',
      'host.name': 'Host-po707ju4yb',
      'event.kind': 'signal',
    },
    {
      '@timestamp': '2024-05-21T09:01:38.739Z',
      'agent.type': 'endpoint',
      'process.args': ['"C:\\powershell.exe"', '--w6g'],
      'source.ip': null,
      'destination.ip': null,
      'user.name': 'xl60lemzdc',
      'host.name': 'Host-po707ju4yb',
      'event.kind': 'signal',
    },
  ],
};

export const mockESQLTimelineData = {
  rows: mockESQLResponse.rows.map((row, idx) => {
    return {
      id: String(idx),
      raw: row,
      flattened: row,
    };
  }),
  columns: mockESQLResponse.columns,
};

export const mockESQLTimelineErrorResponse = {
  type: 'error',
  response: {
    error: {
      message: "Error executing ESQL query: 'Error: [illegal_argument_exception]",
    },
  },
};

export const mockESQLTimelineNoResultResponse: Datatable = {
  type: 'datatable',
  meta: {
    type: 'es_ql',
  },
  columns: [],
  rows: [],
  warning: '299 Elasticsearch-8.15.0-bac320829ca1385bcda70f70e5124570b513bf9e "No results found"',
};

export const mockESQLTimelineNoResultsData = {
  rows: mockESQLTimelineNoResultResponse.rows.map((row, idx) => {
    return {
      id: String(idx),
      raw: row,
      flattened: row,
    };
  }),
  columns: mockESQLTimelineNoResultResponse.columns,
};
