[role="xpack"]
[[automating-report-generation]]
== Automatically generate reports

To automatically generate PDF and CSV reports, generate a POST URL, then submit the HTTP `POST` request using {watcher} or a script.

[IMPORTANT]
===================
The interval between report requests must be longer than the time it
takes to generate the reports--otherwise, the report queue can back up. To 
avoid this, increase the time between report requests. 

By default, report generation fails if the report is unable to generate
within two minutes. When you generate reports that contain many complex
visualizations, or your machine is slow or under constant heavy load, it
can take longer than two minutes to generate a report. To increase
the time between report requests, configure <<xpack-reporting-q-timeout,`xpack.reporting.queue.timeout`.
===================

[float]
=== Create a POST URL

Create the POST URL that triggers a report to generate PDF and CSV reports.

To create the POST URL for PDF reports:

. Open the main menu, then click *Dashboard, *Visualize Library*, or *Canvas*.

. Open the dashboard, visualization, or **Canvas** workpad you want to share.

. From the toolbar, click *Share > PDF Reports*, then choose an option:

* If you are using *Dashboard* or *Visulize Library*, click *Copy POST URL*.

* If you are using *Canvas*, click *Advanced options > Copy POST URL*.

To create the POST URL for CSV reports:

. Open the main menu, then click *Discover*.

. Open the saved search you want to share.

. In the toolbar, click *Share > CSV Reports > Copy POST URL*.

[float]
=== Submit the request with {watcher}

include::watch-example.asciidoc[]

[float]
=== Submit the request with a script

include::script-example.asciidoc[]

[float]
=== HTTP response codes

include::response-codes.asciidoc[]

[float]
=== Deprecated report URLs

The following POST URL paths are deprecated.

* Dashboard reports:  `/api/reporting/generate/dashboard/<dashboard-id>`
* Visualize reports:  `/api/reporting/generate/visualization/<visualization-id>`
* Saved Search reports: `/api/reporting/generate/search/<saved-search-id>`

If there are problems using the paths after you upgrade {kib}, regenerate the POST URL for the report.

[IMPORTANT]
===================
In previous {kib} versions, generation URLs included a `&sync` parameter that held requests open until documents finished generating. The `&sync` parameter has been removed.
If you use the `&sync` parameter, such as in Watcher, you must update the generation URLs.
===================
