[role="xpack"]
[[configuring-reporting]]
== Reporting configuration

Control how the {report-features}
communicate with the {kib} server, manage background jobs, and capture
screenshots. For more information, refer to <<reporting-settings-kb, Reporting Settings>>.

[float]
[[encryption-keys]]
=== Encryption keys for multiple {kib} instances

By default, a new encryption key is generated for the {report-features} each
time you start {kib}. When a static encryption key is not persisted in
the {kib} configuration, any pending reports fail when you restart {kib}.

When you are load balancing across multiple {kib} instances, each instance must have
the same reporting encryption key. When the encryption keys are different, report generation fails when a
report queues through one instance and another instance picks up the job
from the queue. The other instance is unable to decrypt the reporting job metadata.

To configure a static encryption key for reporting: 

[source,yaml]
--------------------------------------------------------------------------------
xpack.reporting.encryptionKey: "something_secret"
--------------------------------------------------------------------------------

The encryption key must be at least 32 characters long, a text string, and can include any alphanumeric character.

[float]
[[report-indices]]
=== Report indices for multiple {kib} workspaces

When you divide workspaces in an Elastic cluster using multiple {kib} instances
with a different `kibana.index` setting per instance, you must configure a unique `xpack.reporting.index`
setting per `kibana.index`. If a report is queued through an instance with one `kibana.index` setting, and
an instance with a different `kibana.index` attempts to claim the job, report generation fails. 

{kib} instance A:
[source,yaml]
--------------------------------------------------------------------------------
kibana.index: ".kibana-a"
xpack.reporting.index: ".reporting-a"
xpack.reporting.encryptionKey: "something_secret"
--------------------------------------------------------------------------------

{kib} instance B:
[source,yaml]
--------------------------------------------------------------------------------
kibana.index: ".kibana-b"
xpack.reporting.index: ".reporting-b"
xpack.reporting.encryptionKey: "something_secret"
--------------------------------------------------------------------------------

NOTE: When security is enabled, begin `xpack.reporting.index` with `.reporting-` to enable the necessary privileges over the index for the `kibana_system` role.

[float]
[[using-reverse-proxies]]
=== Use reverse proxies

When your {kib} instance requires a reverse proxy, such as NGINX, Apache, etc., for
access due to rewrite rules or special headers added by the proxy, configure `xpack.reporting.kibanaServer` 
to make the headless browser process connect to the proxy in <<reporting-kibana-server-settings, Kibana server settings>>. 


NOTE: A headless browser runs on the {kib} server to open a {kib} page for
capturing screenshots. When you configure `xpack.reporting.kibanaServer` to point to a proxy host, 
the {kib} server must have network access to the proxy.

include::{kib-repo-dir}/user/security/reporting.asciidoc[]
include::network-policy.asciidoc[]
