[role="xpack"]
[[reporting-network-policy]]
=== Restrict requests with a network policy

When you generate PDF reports, {kib} uses the Chromium browser to load the {kib} page on the server, which
potentially involves sending requests to external hosts. For example, when a request is sent to an external image server to show a
field formatted as an image, or to show an image in a Markdown visualization.

When the Chromium browser is asked to send a request that violates the network policy, {kib} stops processing the page
before the request goes out, and the report fails. Additional information about the failure appears in
the {kib} server logs.

[NOTE]
============
{kib} installations are not designed to be publicly accessible over the internet. The network policy and Elastic Stack security features do not change this condition.
============

[float]
==== Configure a network policy

A network policy is specified as an array of objects that describe what to allow or deny based on a host or protocol. When a host or protocol
are unspecified, the rule matches any host or protocol.

The rule objects are sequentially evaluated from the beginning to the end of the array, and continue until there is a matching rule.
If no rules allow a request, the request is denied.

[source,yaml]
-------------------------------------------------------
# Only allow requests to placeholder.com
xpack.reporting.capture.networkPolicy:
  rules: [ { allow: true, host: "placeholder.com" } ] 
-------------------------------------------------------

[source,yaml]
-------------------------------------------------------
# Only allow requests to https://placeholder.com 
xpack.reporting.capture.networkPolicy:
  rules: [ { allow: true, host: "placeholder.com", protocol: "https:" } ] 
-------------------------------------------------------

A final `allow` rule with no host or protocol allows all requests that are not explicitly denied.

[source,yaml]
-------------------------------------------------------
# Denies requests from http://placeholder.com, but anything else is allowed.
xpack.reporting.capture.networkPolicy:
  rules: [{ allow: false, host: "placeholder.com", protocol: "http:" }, { allow: true }];
-------------------------------------------------------

A network policy can include multiple rules.

[source,yaml]
-------------------------------------------------------
# Allow any request to http://placeholder.com but for any other host, https is required
xpack.reporting.capture.networkPolicy
  rules: [
    { allow: true, host: "placeholder.com", protocol: "http:" },
    { allow: true, protocol: "https:" },
  ]
-------------------------------------------------------

[NOTE]
============
The `file:` protocol is always denied, even if when no network policy is configured.
============

[float]
==== Disable a network policy

To disable a network policy, open kibana.yml, then specify the following:

[source,yaml]
-------------------------------------------------------
xpack.reporting.capture.networkPolicy.enabled: false
-------------------------------------------------------
