To automatically generate reports with a watch, you need to configure {watcher} to trust the {kib} server certificate. 
For more information, refer to {kibana-ref}/secure-reporting.html[Securing Reporting].

To configure a watch to email reports, use the `reporting` attachment type in an `email` action. 
For more information, refer to {ref}/actions-email.html#configuring-email[Configuring email accounts].

For example, to generate and email a PDF report every hour:

[source,js]
---------------------------------------------------------
PUT _watcher/watch/error_report
{
  "trigger" : {
    "schedule": {
      "interval": "1h"
    }
  },
  "actions" : {
    "email_admin" : { <1>
      "email": {
        "to": "'Recipient Name <recipient@example.com>'",
        "subject": "Error Monitoring Report",
        "attachments" : {
          "error_report.pdf" : {
            "reporting" : {
              "url": "http://0.0.0.0:5601/api/reporting/generate/printablePdf?jobParams=...", <2>
              "retries":40, <3>
              "interval":"15s", <4>
              "auth":{ <5>
                "basic":{
                  "username":"elastic",
                  "password":"changeme"
                }
              }
            }
          }
        }
      }
    }
  }
}
---------------------------------------------------------
// CONSOLE

<1> Configure at least one email account to enable Watcher to send emails. For more information, refer to {ref}/actions-email.html#configuring-email[Configuring email accounts].
<2> An example POST URL.
<3> Optional, the default is 40.
<4> Optional, the default is 15s.
<5> The user credentials for a user with permissions to access {kib} and the {report-features}.
//For more information, see <<secure-reporting>>.
//<<reporting-app-users, Setting up a Reporting Role>>.

[NOTE]
====
Reporting is integrated with Watcher only as an email attachment type.

The report Generation URL might contain date-math expressions that cause the watch to fail with a `parse_exception`.
Remove curly braces `{`  `}` from date-math expressions and URL-encode characters to avoid this.
For example: `...(range:(%27@timestamp%27:(gte:now-15m%2Fd,lte:now%2Fd))))...`

For more information about configuring watches, refer to {ref}/how-watcher-works.html[How Watcher works].
====
