# ------------------------------------------------------------------------------------
# Vagrant setup for running Elastic agent on the created VM.0
# This setup is mostly used for CI runs, since multipass is not used in that env.
# ------------------------------------------------------------------------------------
hostname = ENV["VMNAME"] || 'ubuntu'
cachedAgentSource = ENV["CACHED_AGENT_SOURCE"] || ''
cachedAgentFilename = ENV["CACHED_AGENT_FILENAME"] || ''
agentDestinationFolder = ENV["AGENT_DESTINATION_FOLDER"] || ''

Vagrant.configure("2") do |config|
  config.vm.hostname = hostname
  config.vm.box = 'ubuntu/jammy64'
  config.vm.box_check_update = false
  config.vm.boot_timeout = 600

  config.vm.provider :virtualbox do |vb|
    vb.memory = 4096
    vb.cpus = 2
  end

  config.vm.provider :vmware_desktop do |v, override|
    override.vm.box = "starboard/ubuntu-arm64-20.04.5"
    override.vm.box_version = "20221120.20.40.0"
    override.vm.box_download_insecure = true
    override.vm.network "private_network", type: "dhcp"

    v.ssh_info_public = true
    v.gui = true
    v.linked_clone = false
    v.vmx["ethernet0.virtualdev"] = "vmxnet3"
  end

  config.vm.provision "file", source: cachedAgentSource, destination: "~/#{cachedAgentFilename}"
  config.vm.provision "shell", inline: "mkdir #{agentDestinationFolder}"
  config.vm.provision "shell", inline: "tar -zxf #{cachedAgentFilename} --directory #{agentDestinationFolder} --strip-components=1 && rm -f #{cachedAgentFilename}"
  config.vm.provision "shell", inline: "sudo apt-get update"
  config.vm.provision "shell", inline: "sudo apt-get install unzip"
end
