/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

import {
  ALERT_DURATION,
  ALERT_END,
  ALERT_ID,
  ALERT_SEVERITY_LEVEL,
  ALERT_SEVERITY_VALUE,
  ALERT_START,
  ALERT_STATUS,
  ALERT_UUID,
} from '@kbn/rule-data-utils';

export const apmAlertResponseExample = [
  {
    'rule.id': ['apm.error_rate'],
    'service.name': ['opbeans-java'],
    'rule.name': ['Error count threshold | opbeans-java (smith test)'],
    [ALERT_DURATION]: [180057000],
    [ALERT_STATUS]: ['open'],
    [ALERT_SEVERITY_LEVEL]: ['warning'],
    tags: ['apm', 'service.name:opbeans-java'],
    [ALERT_UUID]: ['0175ec0a-a3b1-4d41-b557-e21c2d024352'],
    'rule.uuid': ['474920d0-93e9-11eb-ac86-0b455460de81'],
    'event.action': ['active'],
    '@timestamp': ['2021-04-12T13:53:49.550Z'],
    [ALERT_ID]: ['apm.error_rate_opbeans-java_production'],
    [ALERT_START]: ['2021-04-12T13:50:49.493Z'],
    'kibana.producer': ['apm'],
    'event.kind': ['state'],
    'rule.category': ['Error count threshold'],
    'service.environment': ['production'],
    'processor.event': ['error'],
  },
  {
    'rule.id': ['apm.error_rate'],
    'service.name': ['opbeans-java'],
    'rule.name': ['Error count threshold | opbeans-java (smith test)'],
    [ALERT_DURATION]: [2419005000],
    [ALERT_END]: ['2021-04-12T13:49:49.446Z'],
    [ALERT_STATUS]: ['closed'],
    tags: ['apm', 'service.name:opbeans-java'],
    [ALERT_UUID]: ['32b940e1-3809-4c12-8eee-f027cbb385e2'],
    'rule.uuid': ['474920d0-93e9-11eb-ac86-0b455460de81'],
    'event.action': ['close'],
    '@timestamp': ['2021-04-12T13:49:49.446Z'],
    [ALERT_ID]: ['apm.error_rate_opbeans-java_production'],
    [ALERT_START]: ['2021-04-12T13:09:30.441Z'],
    'kibana.producer': ['apm'],
    'event.kind': ['state'],
    'rule.category': ['Error count threshold'],
    'service.environment': ['production'],
    'processor.event': ['error'],
  },
];

export const dynamicIndexPattern = {
  fields: [
    {
      name: '@timestamp',
      type: 'date',
      esTypes: ['date'],
      searchable: true,
      aggregatable: true,
      readFromDocValues: true,
    },
    {
      name: 'event.action',
      type: 'string',
      esTypes: ['keyword'],
      searchable: true,
      aggregatable: true,
      readFromDocValues: true,
    },
    {
      name: 'event.kind',
      type: 'string',
      esTypes: ['keyword'],
      searchable: true,
      aggregatable: true,
      readFromDocValues: true,
    },
    {
      name: 'host.name',
      type: 'string',
      esTypes: ['keyword'],
      searchable: true,
      aggregatable: true,
      readFromDocValues: true,
    },
    {
      name: ALERT_DURATION,
      type: 'number',
      esTypes: ['long'],
      searchable: true,
      aggregatable: true,
      readFromDocValues: true,
    },
    {
      name: ALERT_END,
      type: 'date',
      esTypes: ['date'],
      searchable: true,
      aggregatable: true,
      readFromDocValues: true,
    },
    {
      name: ALERT_ID,
      type: 'string',
      esTypes: ['keyword'],
      searchable: true,
      aggregatable: true,
      readFromDocValues: true,
    },
    {
      name: ALERT_SEVERITY_LEVEL,
      type: 'string',
      esTypes: ['keyword'],
      searchable: true,
      aggregatable: true,
      readFromDocValues: true,
    },
    {
      name: ALERT_SEVERITY_VALUE,
      type: 'number',
      esTypes: ['long'],
      searchable: true,
      aggregatable: true,
      readFromDocValues: true,
    },
    {
      name: ALERT_START,
      type: 'date',
      esTypes: ['date'],
      searchable: true,
      aggregatable: true,
      readFromDocValues: true,
    },
    {
      name: ALERT_STATUS,
      type: 'string',
      esTypes: ['keyword'],
      searchable: true,
      aggregatable: true,
      readFromDocValues: true,
    },
    {
      name: ALERT_UUID,
      type: 'string',
      esTypes: ['keyword'],
      searchable: true,
      aggregatable: true,
      readFromDocValues: true,
    },
    {
      name: 'kibana.producer',
      type: 'string',
      esTypes: ['keyword'],
      searchable: true,
      aggregatable: true,
      readFromDocValues: true,
    },
    {
      name: 'processor.event',
      type: 'string',
      esTypes: ['keyword'],
      searchable: true,
      aggregatable: true,
      readFromDocValues: true,
    },
    {
      name: 'rule.category',
      type: 'string',
      esTypes: ['keyword'],
      searchable: true,
      aggregatable: true,
      readFromDocValues: true,
    },
    {
      name: 'rule.id',
      type: 'string',
      esTypes: ['keyword'],
      searchable: true,
      aggregatable: true,
      readFromDocValues: true,
    },
    {
      name: 'rule.name',
      type: 'string',
      esTypes: ['keyword'],
      searchable: true,
      aggregatable: true,
      readFromDocValues: true,
    },
    {
      name: 'rule.uuid',
      type: 'string',
      esTypes: ['keyword'],
      searchable: true,
      aggregatable: true,
      readFromDocValues: true,
    },
    {
      name: 'service.environment',
      type: 'string',
      esTypes: ['keyword'],
      searchable: true,
      aggregatable: true,
      readFromDocValues: true,
    },
    {
      name: 'service.name',
      type: 'string',
      esTypes: ['keyword'],
      searchable: true,
      aggregatable: true,
      readFromDocValues: true,
    },
    {
      name: 'tags',
      type: 'string',
      esTypes: ['keyword'],
      searchable: true,
      aggregatable: true,
      readFromDocValues: true,
    },
    {
      name: 'transaction.type',
      type: 'string',
      esTypes: ['keyword'],
      searchable: true,
      aggregatable: true,
      readFromDocValues: true,
    },
  ],
  timeFieldName: '@timestamp',
  title: '.kibana_smith-alerts-observability*',
};
