[[tutorial-define-index]]
== Index Patternの定義

Elasticsearchに読み込まれたデータの各セットには、Index Patternがあります。前のセクションで、シェイクスピアデータセットには&#8203;`shakespeare`&#8203;という名前のインデックスがあり、口座データセットには&#8203;`bank`&#8203;という名前のインデックスがありました。_index pattern_&#8203;は、複数のインデックスに一致するオプションのワイルドカードを持つ文字列です。たとえば、一般的なロギング事例では、典型的なインデックス名はYYYY.MM.DD形式の日付が含まれ、5月のIndex Patternは&#8203;`logstash-2015.05*`&#8203;のようになります。

このチュートリアルの場合、読み込んだインデックスの名前に一致するパターンが機能します。ブラウザを開き、&#8203;`localhost:5601`&#8203;に移動します。*Settings* タブをクリックしてから、*Indices* タブをクリックします。*Add New* をクリックして、新しいIndex Patternを定義します。2つのサンプルデータセット、シェイクスピアの戯曲と金融口座には、時系列データは含まれません。
これらのデータセットのIndex Patternを作成するときは、*Index contains time-based events* ボックスがオフになっていることを確認してください。
シェイクスピアデータセットのIndex Patternとして&#8203;`shakes*`&#8203;を指定し、*Create* をクリックしてIndex Patternを定義してから、&#8203;`ba*`&#8203;という名前の2つ目のIndex Patternを定義します。

Logstashデータセットには時系列データが含まれるため、*Add New* をクリックしてこのデータセットのインデックスを定義した後、*Index contains time-based events* ボックスがオンになっていることを確認して、*Time-field name* ドロップダウンから&#8203;`@timestamp`&#8203;フィールドを選択してください。

NOTE: Index Patternを定義するときは、そのパターンに一致するインデックスがElasticsearchに存在しなければなりません。そのインデックスには、データが含まれている必要があります。
