/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Watchlist Entities Assign Schema
 *   version: 2023-10-31
 */

import { z } from '@kbn/zod/v4';

export type WatchlistEntityAssignResponseItem = z.infer<typeof WatchlistEntityAssignResponseItem>;
export const WatchlistEntityAssignResponseItem = z.object({
  /**
   * The EUID of the entity
   */
  euid: z.string(),
  status: z.enum(['success', 'failure', 'not_found']),
  /**
   * Error message if the entity failed to process
   */
  error: z.string().optional(),
});

export type AssignWatchlistEntitiesRequestParams = z.infer<
  typeof AssignWatchlistEntitiesRequestParams
>;
export const AssignWatchlistEntitiesRequestParams = z.object({
  /**
   * The ID of the watchlist to add entities to
   */
  watchlist_id: z.string(),
});
export type AssignWatchlistEntitiesRequestParamsInput = z.input<
  typeof AssignWatchlistEntitiesRequestParams
>;

export type AssignWatchlistEntitiesRequestBody = z.infer<typeof AssignWatchlistEntitiesRequestBody>;
export const AssignWatchlistEntitiesRequestBody = z.object({
  /**
   * The EUIDs of the entities to assign
   */
  euids: z.array(z.string()),
});
export type AssignWatchlistEntitiesRequestBodyInput = z.input<
  typeof AssignWatchlistEntitiesRequestBody
>;

export type AssignWatchlistEntitiesResponse = z.infer<typeof AssignWatchlistEntitiesResponse>;
export const AssignWatchlistEntitiesResponse = z.object({
  /**
   * Number of entities successfully assigned
   */
  successful: z.number().int(),
  /**
   * Number of entities that failed to process
   */
  failed: z.number().int(),
  /**
   * Number of entities not found in the entity store
   */
  not_found: z.number().int(),
  /**
   * Total number of entities processed
   */
  total: z.number().int(),
  items: z.array(WatchlistEntityAssignResponseItem),
});
