export declare const SIGNIFICANT_EVENT_TYPE_OPERATIONAL: "operational";
export declare const SIGNIFICANT_EVENT_TYPE_CONFIGURATION: "configuration";
export declare const SIGNIFICANT_EVENT_TYPE_RESOURCE_HEALTH: "resource_health";
export declare const SIGNIFICANT_EVENT_TYPE_ERROR: "error";
export declare const SIGNIFICANT_EVENT_TYPE_SECURITY: "security";
export type SignificantEventType = typeof SIGNIFICANT_EVENT_TYPE_OPERATIONAL | typeof SIGNIFICANT_EVENT_TYPE_CONFIGURATION | typeof SIGNIFICANT_EVENT_TYPE_RESOURCE_HEALTH | typeof SIGNIFICANT_EVENT_TYPE_ERROR | typeof SIGNIFICANT_EVENT_TYPE_SECURITY;
