[[role-management-api-put]]
=== Create or Update Roles

To create or update a role in Elasticsearch's `native` realm, issue a PUT request to the 
`/api/security/role/<rolename>` endpoint.

==== Request Body

The following parameters can be specified in the body of a PUT request to add or update a role:

`metadata`:: (object) Optional meta-data. Within the `metadata` object, keys
that begin with `_` are reserved for system usage.

`elasticsearch`:: (object) Optional Elasticsearch cluster and index privileges, valid keys are 
`cluster`, `indices` and `run_as`. For more information, see {xpack-ref}/defining-roles.html[Defining Roles].

`kibana`:: (list) A list of objects that specify the Kibana Privileges.

==== Authorization

To use this API, you must have at least the `manage_security` cluster privilege.

==== Example

[source,js]
--------------------------------------------------
PUT /api/security/role/my_kibana_role
{
  "metadata" : {
    "version" : 1
  },
  "elasticsearch": {
    "cluster" : [ "all" ],
    "indices" : [ {
      "names" : [ "index1", "index2" ],
      "privileges" : [ "all" ],
      "field_security" : {
        "grant" : [ "title", "body" ]
      },
      "query" : "{\"match\": {\"title\": \"foo\"}}"
    } ],
  },
  "kibana": [ {
      "privileges": [ "all" ]
  } ],
}
--------------------------------------------------
// KIBANA

A successful call returns a response code of `204` and no response body.
