[[role-management-api-put]]
=== Create or Update Role

experimental[This API is experimental and may be changed or removed completely in a future release. Although the underlying mechanism of enforcing role-based access control is stable, the APIs for managing the roles are currently experimental.]

Creates a new {kib} role or updates the attributes of an existing role. {kib} roles are stored in the
{es} native realm.

Note: You cannot access this endpoint via the Console in Kibana.

==== Authorization

To use this API, you must have at least the `manage_security` cluster privilege.

==== Request

To create or update a role, issue a PUT request to the 
`/api/security/role/<rolename>` endpoint.

[source,js]
--------------------------------------------------
PUT /api/security/role/my_kibana_role
--------------------------------------------------

==== Request Body

The following parameters can be specified in the body of a PUT request to add or update a role:

`metadata`:: (object) Optional meta-data. Within the `metadata` object, keys
that begin with `_` are reserved for system usage.

`elasticsearch`:: (object) Optional {es} cluster and index privileges, valid keys are 
`cluster`, `indices` and `run_as`. For more information, see {xpack-ref}/defining-roles.html[Defining Roles].

`kibana`:: (array) An array of objects that specifies the <<kibana-privileges>> for this role:
[source,js]
--------------------------------------------------
[{
  // An optional base privilege. 
  // If specified, must either be ["all"] or ["read"].
  // You can't revoke or downgrade privileges via the `feature` section.
  // "all" grants read/write access to all Kibana features for the specified spaces.
  // "read" grants read-only access to all Kibana features for the specified spaces.
  "base": [],

  // Object containing privileges for specific features.
  // Privileges are added to the base privilege, if one is provided.
  // For example, specifying `base: ["read"]` will grant read access to every feature,
  // even if they aren't granted anything in this feature section.
  // Use the Features API to retrieve a list of available features. <1>
  "feature": {
    "advancedSettings": ["all"],
    "discover": ["all"],
    "visualize": ["all"],
    "dashboard": ["read"]
  },
  
  // The spaces these privileges should be applied to.
  // To grant access to all spaces, set this to `["*"]`, or omit the value.
  "spaces": ["default", "marketing", "sales"]
}]
--------------------------------------------------

<1> <<features-api>>

===== Example 1
Granting read access to all features in all spaces, with full access to Advanced Settings.

[source,js]
--------------------------------------------------
PUT /api/security/role/my_kibana_role
{
  "metadata" : {
    "version" : 1
  },
  "elasticsearch": {
    "cluster" : [ "all" ],
    "indices" : [ {
      "names" : [ "index1", "index2" ],
      "privileges" : [ "all" ],
      "field_security" : {
        "grant" : [ "title", "body" ]
      },
      "query" : "{\"match\": {\"title\": \"foo\"}}"
    } ]
  },
  "kibana": [
    {
      "base": [
        "read"
      ],
      "feature": {
        "advancedSettings": ["all"]
      },
      "spaces": [
        "*"
      ]
    }
  ]
}
--------------------------------------------------
// KIBANA

===== Example 2
Granting "dashboard only" access to only the Marketing space.

[source,js]
--------------------------------------------------
PUT /api/security/role/my_kibana_role
{
  "metadata" : {
    "version" : 1
  },
  "elasticsearch": {
    "cluster" : [ "all" ],
    "indices" : [ {
      "names" : [ "index1", "index2" ],
      "privileges" : [ "all" ],
      "field_security" : {
        "grant" : [ "title", "body" ]
      },
      "query" : "{\"match\": {\"title\": \"foo\"}}"
    } ]
  },
  "kibana": [
    {
      "base": [],
      "feature": {
        "dashboard": ["read"]
      },
      "spaces": [
        "marketing"
      ]
    }
  ]
}
--------------------------------------------------

===== Example 3
Granting full access to all features in the Default space.

[source,js]
--------------------------------------------------
PUT /api/security/role/my_kibana_role
{
  "metadata" : {
    "version" : 1
  },
  "elasticsearch": {
    "cluster" : [ "all" ],
    "indices" : [ {
      "names" : [ "index1", "index2" ],
      "privileges" : [ "all" ],
      "field_security" : {
        "grant" : [ "title", "body" ]
      },
      "query" : "{\"match\": {\"title\": \"foo\"}}"
    } ]
  },
  "kibana": [
    {
      "base": ["all"],
      "feature": {
      },
      "spaces": [
        "default"
      ]
    }
  ]
}
--------------------------------------------------

==== Response

A successful call returns a response code of `204` and no response body.
