
// This is a generated file; please don't update it directly.
// Instead, the updatable source for these settings can be found in kibana-general-settings.yml
// Collection: General settings in Kibana
// Product: Kibana

Use these settings to configure general features available in Kibana.



[float]
[[general-kibana-settings]]
=== General settings


`console.ui.enabled`::
+
====
Toggling this causes the server to regenerate assets on the next startup, which may cause a delay before pages start being served. Set to `false` to disable Console.

Data type: `bool` +
Default: `true` +
====

`console.ui.enabled`::
+
====
Add sources for the [Content Security Policy `script-src` directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src).

Data type: `string` +
====

`console.ui.enabled`::
+
====
**Deprecated:** Deprecated in 8.7.0. Use `csp.script_src: ['unsafe-eval']` instead if you wish to enable `unsafe-eval`. This config option will have no effect in a future version.

Set this to `false` to add the [`unsafe-eval`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_eval_expressions) source expression to the `script-src` directive.

When `csp.disableUnsafeEval` is set to `true`, Kibana will use a custom version of the Handlebars template library. Handlebars is used in various locations in the Kibana frontend where custom templates can be supplied by the user when for instance setting up a visualisation. If you experience any issues rendering Handlebars templates, please set this setting to `false` and [open an issue](https://github.com/elastic/kibana/issues/new/choose) in the Kibana GitHub repository.

Data type: `bool` +
Default: `true` +
====

`csp.worker_src`::
+
====
Add sources for the [Content Security Policy `worker-src` directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/worker-src).

Data type: `string` +
====

`csp.style_src`::
+
====
Add sources for the [Content Security Policy `style-src` directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src).

Data type: `string` +
====

`csp.connect_src`::
+
====
Add sources for the [Content Security Policy `connect-src` directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/connect-src).

Data type: `string` +
====

`csp.default_src`::
+
====
Add sources for the [Content Security Policy `default-src` directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/default-src).

Data type: `string` +
====

`csp.font_src`::
+
====
Add sources for the [Content Security Policy `font-src` directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/font-src).

Data type: `string` +
====

`csp.frame_src`::
+
====
Add sources for the [Content Security Policy `frame-src` directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src).

Data type: `string` +
====

`csp.img_src`::
+
====
Add sources for the [Content Security Policy `img-src` directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src).

Data type: `string` +
====

`csp.frame_ancestors`::
+
====
Add sources for the [Content Security Policy `frame-ancestors` directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors).


NOTE: The `frame-ancestors` directive can also be configured by using [`server.securityResponseHeaders.disableEmbedding`](#server-securityResponseHeaders-disableEmbedding). In that case, that takes precedence and any values in `csp.frame_ancestors` are ignored.
Data type: `string` +
====

`csp.report_only.form_action`::
+
====
Add sources for the [Content Security Policy `form-action` directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/form-action) in reporting mode.

Data type: `string` +
====

`csp.report_uri`::
+
====
Add sources for the [Content Security Policy `report-uri` directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-uri).

Data type: `string` +
====


[[csp-strict]]
`csp.strict`::
+
====
Blocks {{kib}} access to any browser that does not enforce even rudimentary CSP rules. In practice, this disables support for older, less safe browsers like Internet Explorer.

Data type: `bool` +
Default: `true` +
====

`csp.warnLegacyBrowsers`::
+
====
Shows a warning message after loading {{kib}} to any browser that does not enforce even rudimentary CSP rules, though {{kib}} is still accessible. This configuration is effectively ignored when [`csp.strict`](#csp-strict) is enabled.

Data type: `bool` +
Default: `true` +
====

`data.autocomplete.valueSuggestions.terminateAfter`::
+
====
Specifies the max number of documents loaded by each shard to generate autocomplete suggestions. Allowed values are between 1 and 10000000.

Data type: `int` +
Default: `100000` +
====

`data.autocomplete.valueSuggestions.timeout`::
+
====
Specifies the time in milliseconds to wait for autocomplete suggestions from Elasticsearch. Allowed values are between 1 and 1200000.

Data type: `int` +
Default: `1000` +
====


[[elasticsearch-maxSockets]]
`elasticsearch.maxSockets`::
+
====
The maximum number of sockets that can be used for communications with {{es}}. This setting is available in {{ecloud}} 8.2.0 and later versions.

Data type: `string` +
Default: `Infinity` +
====


[[elasticsearch-maxResponseSize]]
`elasticsearch.maxResponseSize`::
+
====
Either `false` or a `byteSize` value. When set, responses from {{es}} with a size higher than the defined limit will be rejected. This is intended to be used as a circuit-breaker mechanism to avoid memory errors in case of unexpectedly high responses coming from {{es}}.

Data type: `string` +
Default: `false` +
====


[[elasticsearch-maxIdleSockets]]
`elasticsearch.maxIdleSockets`::
+
====
The maximum number of idle sockets to keep open between {{kib}} and {{es}}. If more sockets become idle, they will be closed.

Data type: `int` +
Default: `256` +
====


[[elasticsearch-idleSocketTimeout]]
`elasticsearch.idleSocketTimeout`::
+
====
The timeout for idle sockets kept open between {{kib}} and {{es}}. If the socket is idle for longer than this timeout, it will be closed. If you have a transparent proxy between {{kib}} and {{es}} be sure to set this value lower than or equal to the proxy's timeout.

Data type: `string` +
Default: `60s` +
====

`elasticsearch.customHeaders`::
+
====
Header names and values to send to {{es}}. Any custom headers cannot be overwritten by client-side headers, regardless of the [`elasticsearch.requestHeadersWhitelist`](#elasticsearch-requestHeadersWhitelist) configuration.

Data type: `string` +
Default: `{}` +
====


[[elasticsearch-hosts]]
`elasticsearch.hosts`::
+
====
The URLs of the {{es}} instances to use for all your queries. All nodes listed here must be on the same cluster.

To enable SSL/TLS for outbound connections to {{es}}, use the `https` protocol in this setting.

Data type: `string` +
Default: `[ "http://localhost:9200" ]` +
====


[[elasticsearch-publicBaseUrl]]
`elasticsearch.publicBaseUrl`::
+
====
The URL through which Elasticsearch is publicly accessible, if any. This will be shown to users in Kibana when they need connection details for your Elasticsearch cluster.

Data type: `string` +
====


[[elasticsearch-pingTimeout]]
`elasticsearch.pingTimeout`::
+
====
Time in milliseconds to wait for {{es}} to respond to pings.

Data type: `int` +
Default: `The value of the [`elasticsearch.requestTimeout`](#elasticsearch-requestTimeout) setting` +
====


[[elasticsearch-requestHeadersWhitelist]]
`elasticsearch.requestHeadersWhitelist`::
+
====
List of {{kib}} client-side headers to send to {{es}}. To send **no** client-side headers, set this value to [] (an empty list). Removing the `authorization` header from being whitelisted means that you cannot use [basic authentication](docs-content://deploy-manage/users-roles/cluster-or-deployment-auth/kibana-authentication.md#basic-authentication) in {{kib}}.

Data type: `string` +
Default: `[ 'authorization', 'es-client-authentication' ]` +
====


[[elasticsearch-requestTimeout]]
`elasticsearch.requestTimeout`::
+
====
Time in milliseconds to wait for responses from the back end or {{es}}. This value must be a positive integer.

Data type: `int` +
Default: `30000` +
====

`elasticsearch.shardTimeout`::
+
====
Time in milliseconds for {{es}} to wait for responses from shards. Set to 0 to disable.

Data type: `int` +
Default: `30000` +
====

`elasticsearch.compression`::
+
====
Specifies whether {{kib}} should use compression for communications with {{es}}. This setting is available in {{ecloud}} 8.3.0 and later versions.

Data type: `bool` +
Default: `false` +
====

`elasticsearch.sniffInterval`::
+
====
Time in milliseconds between requests to check {{es}} for an updated list of nodes.

Data type: `int` +
====

`elasticsearch.sniffOnStart`::
+
====
Attempt to find other {{es}} nodes on startup.

Data type: `bool` +
Default: `false` +
====

`elasticsearch.sniffOnConnectionFault`::
+
====
Update the list of {{es}} nodes immediately following a connection fault.

Data type: `bool` +
Default: `false` +
====


[[elasticsearch-ssl-alwaysPresentCertificate]]
`elasticsearch.ssl.alwaysPresentCertificate`::
+
====
Controls {{kib}} behavior in regard to presenting a client certificate when requested by {{es}}. This setting applies to all outbound SSL/TLS connections to {{es}}, including requests that are proxied for end users.


WARNING: When {{es}} uses certificates to authenticate end users with a PKI realm and [`elasticsearch.ssl.alwaysPresentCertificate`](#elasticsearch-ssl-alwaysPresentCertificate) is `true`, proxied requests may be executed as the identity that is tied to the {{kib}} server.
Data type: `bool` +
Default: `false` +
====


[[elasticsearch-ssl-certificate]]
`elasticsearch.ssl.certificate`::
+
====
Use with [`elasticsearch.ssl.key`](#elasticsearch-ssl-cert-key). Paths to a PEM-encoded X.509 client certificate and its corresponding private key. These are used by {{kib}} to authenticate itself when making outbound SSL/TLS connections to {{es}}. For these settings to take effect, the `xpack.security.http.ssl.client_authentication` setting in {{es}} must be also be set to `"required"` or `"optional"` to request a client certificate from {{kib}}.


NOTE: These settings cannot be used in conjunction with [`elasticsearch.ssl.keystore.path`](#elasticsearch-ssl-keystore-path).
Data type: `string` +
====


[[elasticsearch-ssl-cert-key]]
`elasticsearch.ssl.key`::
+
====
Use with [`elasticsearch.ssl.certificate`](#elasticsearch-ssl-certificate). Paths to a PEM-encoded X.509 client certificate and its corresponding private key. These are used by {{kib}} to authenticate itself when making outbound SSL/TLS connections to {{es}}. For these settings to take effect, the `xpack.security.http.ssl.client_authentication` setting in {{es}} must be also be set to `"required"` or `"optional"` to request a client certificate from {{kib}}.


NOTE: These settings cannot be used in conjunction with [`elasticsearch.ssl.keystore.path`](#elasticsearch-ssl-keystore-path).
Data type: `string` +
====


[[elasticsearch-ssl-certificateAuthorities]]
`elasticsearch.ssl.certificateAuthorities`::
+
====
Paths to one or more PEM-encoded X.509 certificate authority (CA) certificates, which make up a trusted certificate chain for {{es}}. This chain is used by {{kib}} to establish trust when making outbound SSL/TLS connections to {{es}}.

In addition to this setting, trusted certificates may be specified via [`elasticsearch.ssl.keystore.path`](#elasticsearch-ssl-keystore-path) and/or [`elasticsearch.ssl.truststore.path`](#elasticsearch-ssl-truststore-path).

Data type: `string` +
====

`elasticsearch.ssl.keyPassphrase`::
+
====
The password that decrypts the private key that is specified via [`elasticsearch.ssl.key`](#elasticsearch-ssl-cert-key). This value is optional, as the key may not be encrypted.

Data type: `string` +
====


[[elasticsearch-ssl-keystore-path]]
`elasticsearch.ssl.keystore.path`::
+
====
Path to a PKCS#12 keystore that contains an X.509 client certificate and it’s corresponding private key. These are used by {{kib}} to authenticate itself when making outbound SSL/TLS connections to {{es}}. For this setting, you must also set the `xpack.security.http.ssl.client_authentication` setting in {{es}} to `"required"` or `"optional"` to request a client certificate from {{kib}}.

If the keystore contains any additional certificates, they are used as a trusted certificate chain for {{es}}. This chain is used by {{kib}} to establish trust when making outbound SSL/TLS connections to {{es}}. In addition to this setting, trusted certificates may be specified via [`elasticsearch.ssl.certificateAuthorities`](#elasticsearch-ssl-certificateAuthorities) and/or [`elasticsearch.ssl.truststore.path`](#elasticsearch-ssl-truststore-path).


NOTE: This setting cannot be used in conjunction with [`elasticsearch.ssl.certificate`](#elasticsearch-ssl-cert-key) or [`elasticsearch.ssl.key`](#elasticsearch-ssl-cert-key).
Data type: `string` +
====

`elasticsearch.ssl.keystore.password`::
+
====
The password that decrypts the keystore specified via [`elasticsearch.ssl.keystore.path`](#elasticsearch-ssl-keystore-path). If the keystore has no password, leave this as blank. If the keystore has an empty password, set this to `""`.

Data type: `string` +
====


[[elasticsearch-ssl-truststore-path]]
`elasticsearch.ssl.truststore.path`::
+
====
Path to a PKCS#12 trust store that contains one or more X.509 certificate authority (CA) certificates, which make up a trusted certificate chain for {{es}}. This chain is used by {{kib}} to establish trust when making outbound SSL/TLS connections to {{es}}.

In addition to this setting, trusted certificates may be specified via [`elasticsearch.ssl.certificateAuthorities`](#elasticsearch-ssl-certificateAuthorities) and/or [`elasticsearch.ssl.keystore.path`](#elasticsearch-ssl-keystore-path).

Data type: `string` +
====

`elasticsearch.ssl.truststore.password`::
+
====
The password that decrypts the trust store specified via [`elasticsearch.ssl.truststore.path`](#elasticsearch-ssl-truststore-path). If the trust store has no password, leave this as blank. If the trust store has an empty password, set this to `""`.

Data type: `string` +
====


[[elasticsearch-ssl-verificationMode]]
`elasticsearch.ssl.verificationMode`::
+
====
Controls the verification of the server certificate that {{kib}} receives when making an outbound SSL/TLS connection to {{es}}. Valid values are `"full"`, `"certificate"`, and `"none"`. Using `"full"` performs hostname verification, using `"certificate"` skips hostname verification, and using `"none"` skips verification entirely.

Data type: `string` +
Default: `full` +
====


[[elasticsearch-user-passwd]]
`elasticsearch.password`::
+
====
Use with [`elasticsearch.username`](#elasticsearch-user-username). If your {{es}} is protected with basic authentication, these settings provide the username and password that the {{kib}} server uses to perform maintenance on the {{kib}} index at startup. {{kib}} users still need to authenticate with {{es}}, which is proxied through the {{kib}} server.

Data type: `string` +
Default: `full` +
====


[[elasticsearch-user-username]]
`elasticsearch.username`::
+
====
Use with [`elasticsearch.password`](#elasticsearch-user-passwd). If your {{es}} is protected with basic authentication, these settings provide the username and password that the {{kib}} server uses to perform maintenance on the {{kib}} index at startup. {{kib}} users still need to authenticate with {{es}}, which is proxied through the {{kib}} server.

Data type: `string` +
Default: `full` +
====


[[elasticsearch-service-account-token$]]
`elasticsearch.serviceAccountToken`::
+
====
If your {{es}} is protected with basic authentication, this token provides the credentials that the {{kib}} server uses to perform maintenance on the {{kib}} index at startup. This setting is an alternative to `elasticsearch.username` and `elasticsearch.password`.

Data type: `string` +
====

`execution_context.enabled`::
+
====
Propagate request-specific metadata to Elasticsearch server by way of the `x-opaque-id` header. This setting is available in {{ecloud}} 8.1.0 and later versions.

Data type: `bool` +
====


[[logging-root]]
`logging.root`::
+
====
The `root` logger has is a [dedicated logger](docs-content://deploy-manage/monitor/logging-configuration/kibana-logging.md#dedicated-loggers) and is pre-configured. The `root` logger logs at `info` level by default. If any other logging configuration is specified, `root` *must* also be explicitly configured.

Data type: `string` +
====


[[logging-root-appenders]]
`logging.root.appenders`::
+
====
A list of logging appenders to forward the root level logger instance to.  By default `root` is configured with the `default` appender that logs to stdout with a `pattern` layout. This is the configuration that all custom loggers will use unless they’re re-configured explicitly. You can override the default behavior by configuring a different [appender](docs-content://deploy-manage/monitor/logging-configuration/kibana-logging.md#logging-appenders) to apply to `root`.

Data type: `string` +
====


[[logging-root-level]]
`logging.root.level`::
+
====
Level at which a log record should be logged. Supported levels are: *all*, *fatal*, *error*, *warn*, *info*, *debug*, *trace*, *off*. Levels are ordered from *all* (highest) to *off* and a log record will be logged it its level is higher than or equal to the level of its logger, otherwise the log record is ignored. Use this value to [change the overall log level](docs-content://deploy-manage/monitor/logging-configuration/kibana-log-settings-examples.md#change-overall-log-level).


TIP: Set to `all` to log all events, including system usage information and all requests. Set to `off` to silence all logs.  You can also use the logging [cli commands](docs-content://deploy-manage/monitor/logging-configuration/kib-advanced-logging.md#logging-cli-migration) to set log level to `verbose` or silence all logs.
Data type: `string` +
Default: `info` +


The following example shows a valid verbose `logging.root` configuration:
```text
logging:
  appenders:
    console_appender:
      type: console
      layout:
        type: pattern
        highlight: true
  root:
    appenders: [console_appender]
    level: all
```


====


[[logging-loggers]]
`logging.loggers[]`::
+
====
Allows you to [customize a specific logger instance](docs-content://deploy-manage/monitor/logging-configuration/kibana-log-settings-examples.md#customize-specific-log-records).

Data type: `string` +
====

`logging.appenders[]`::
+
====
[Appenders](docs-content://deploy-manage/monitor/logging-configuration/kibana-logging.md#logging-appenders) define how and where log messages are displayed (eg. **stdout** or console) and stored (eg. file on the disk).

Data type: `string` +
====

`map.includeElasticMapsService`::
+
====
Set to `false` to disable connections to Elastic Maps Service. When `includeElasticMapsService` is turned off, only tile layer configured by [`map.tilemap.url`](#tilemap-url) is available in [Maps](docs-content://explore-analyze/visualize/maps.md).

Data type: `bool` +
Default: `true` +
====

`map.emsUrl`::
+
====
Specifies the URL of a self hosted [{{hosted-ems}}](docs-content://explore-analyze/visualize/maps/maps-connect-to-ems.md#elastic-maps-server).

Data type: `string` +
====


[[tilemap-settings]]
`map.tilemap.options.attribution`::
+
====
The map attribution string. Provide attributions in markdown and use `\|` to delimit attributions, for example: `"[attribution 1](https://www.attribution1)\|[attribution 2](https://www.attribution2)"`.

Data type: `string` +
Default: `© [Elastic Maps Service](https://www.elastic.co/elastic-maps-service)` +
====


[[tilemap-max-zoom]]
`map.tilemap.options.maxZoom`::
+
====
The maximum zoom level.

Data type: `int` +
Default: `10` +
====


[[tilemap-min-zoom]]
`map.tilemap.options.minZoom`::
+
====
The minimum zoom level.

Data type: `int` +
Default: `1` +
====


[[tilemap-subdomains]]
`map.tilemap.options.subdomains`::
+
====
An array of subdomains used by the tile service. Specify the position of the subdomain the URL with the token `{{s}}`.

Data type: `string` +
====


[[tilemap-url]]
`map.tilemap.url`::
+
====
The URL to the service that {{kib}} uses as the default basemap in [maps](docs-content://explore-analyze/visualize/maps.md) and [vega maps](docs-content://explore-analyze/visualize/custom-visualizations-with-vega.md#vega-with-a-map). By default, {{kib}} sets a basemap from the [Elastic Maps Service](docs-content://explore-analyze/visualize/maps/maps-connect-to-ems.md), but users can point to their own Tile Map Service.

Data type: `string` +


For example: "https://tiles.elastic.co/v2/default/{{z}}/{x}/{{y}}.png?elastic_tile_service_tos=agree&my_app_name=kibana"


====

`migrations.batchSize`::
+
====
Defines the number of documents migrated at a time. The higher the value, the faster the Saved Objects migration process performs at the cost of higher memory consumption. If upgrade migrations results in {{kib}} crashing with an out of memory exception or fails due to an Elasticsearch `circuit_breaking_exception`, use a smaller `batchSize` value to reduce the memory pressure.

Data type: `int` +
Default: `1000` +
====

`migrations.discardUnknownObjects`::
+
====
Discard saved objects with unknown types during a migration. Must be set to the target version, for example: `8.4.0`. This setting is available in {{ecloud}} 8.4.0 and later versions.

Data type: `string` +
Default: `undefined` +
====

`migrations.discardCorruptObjects`::
+
====
Discard corrupt saved objects, as well as those that cause transform errors during a migration. Must be set to the target version, for example: `8.4.0`. Default: undefined. This setting is available in {{ecloud}} 8.4.0 and later versions.

Data type: `string` +
====

`migrations.maxBatchSizeBytes`::
+
====
Defines the maximum payload size for indexing batches of upgraded saved objects to avoid migrations failing due to a 413 Request Entity Too Large response from Elasticsearch. This value should be lower than or equal to your Elasticsearch cluster's `http.max_content_length` configuration option.

Data type: `string` +
Default: `100mb` +
====

`migrations.retryAttempts`::
+
====
The number of times migrations retry temporary failures, such as a network timeout, 503 status code, or `snapshot_in_progress_exception`. When upgrade migrations frequently fail after exhausting all retry attempts with a message such as `Unable to complete the [...] step after 15 attempts, terminating.`, increase the setting value.

Data type: `int` +
Default: `15` +
====

`newsfeed.enabled`::
+
====
Controls whether to enable the newsfeed system for the {{kib}} UI notification center. Set to `false` to disable the newsfeed system.

Data type: `bool` +
Default: `true` +
====

`node.roles`::
+
====


preview::[]

Indicates which roles to configure the {{kib}} process with, which will effectively run {{kib}} in different modes. Valid options are `background_tasks` and `ui`, or `*` to select all roles.

Data type: `string` +
Default: `*` +
====

`notifications.connectors.default.email`::
+
====
Choose the default email connector for user notifications. As of `8.6.0`, {{kib}} is shipping with a new notification mechanism that will send email notifications for various user actions, e.g. assigning a *Case* to a user. To enable notifications, an email connector must be [preconfigured](/reference/connectors-kibana/pre-configured-connectors.md) in the system via `kibana.yml`, and the notifications plugin must be configured to point to the ID of that connector.

Data type: `string` +
====

`ops.interval`::
+
====
Set the interval in milliseconds to sample system and process performance metrics. The minimum value is 100.

Data type: `string` +
Default: `5000` +
====


[[ops-cGroupOverrides-cpuPath]]
`ops.cGroupOverrides.cpuPath`::
+
====
Override for cgroup cpu path when mounted in a manner that is inconsistent with `/proc/self/cgroup`.

Data type: `string` +
====


[[ops-cGroupOverrides-cpuAcctPath]]
`ops.cGroupOverrides.cpuAcctPath`::
+
====
Override for cgroup cpuacct path when mounted in a manner that is inconsistent with `/proc/self/cgroup`.

Data type: `string` +
====


[[path-data]]
`path.data`::
+
====
The path where {{kib}} stores persistent data not saved in {{es}}.

Data type: `string` +
Default: `data` +
====

`permissionsPolicy.report_to`::
+
====
Add sources for the [Permissions Policy `report-to` directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy).

Data type: `string` +
====

`pid.file`::
+
====
Specifies the path where {{kib}} creates the process ID file.

Data type: `string` +
====


[[savedObjects-maxImportExportSize]]
`savedObjects.maxImportExportSize`::
+
====
The maximum count of saved objects that can be imported or exported. This setting exists to prevent the {{kib}} server from running out of memory when handling large numbers of saved objects. It is recommended to only raise this setting if you are confident your server can hold this many objects in memory.

Data type: `int` +
Default: `10000` +
====


[[savedObjects-maxImportPayloadBytes]]
`savedObjects.maxImportPayloadBytes`::
+
====
The maximum byte size of a saved objects import that the {{kib}} server will accept. This setting exists to prevent the {{kib}} server from running out of memory when handling a large import payload. Note that this setting overrides the more general [`server.maxPayload`](#server-maxPayload) for saved object imports only.

Data type: `string` +
Default: `26214400` +
====


[[server-basePath]]
`server.basePath`::
+
====
Enables you to specify a path to mount {{kib}} at if you are running behind a proxy. Use the [`server.rewriteBasePath`](#server-rewriteBasePath) setting to tell {{kib}} if it should remove the basePath from requests it receives, and to prevent a deprecation warning at startup. This setting cannot end in a slash (`/`).

Data type: `string` +
====

`server.defaultRoute`::
+
====
Specifies the default route when opening Kibana. You can use this setting to modify the landing page when opening Kibana.

Data type: `string` +
====


[[$$$server-publicBaseUrl]]
`server.publicBaseUrl`::
+
====
The publicly available URL that end-users access Kibana at. Must include the protocol, hostname, port (if different than the defaults for `http` and `https`, 80 and 443 respectively), and the [`server.basePath`](#server-basePath) (when that setting is configured explicitly). This setting cannot end in a slash (`/`).

Data type: `string` +
====


[[server-compression]]
`server.compression.enabled`::
+
====
Set to `false` to disable HTTP compression for all responses.

Data type: `bool` +
Default: `true` +
====

`server.cors.enabled`::
+
====


preview::[]

Set to `true` to allow cross-origin API calls.

Data type: `string` +
Default: `false` +
====

`server.cors.allowCredentials`::
+
====


preview::[]

Set to `true` to allow browser code to access response body whenever request performed with user credentials.

Data type: `bool` +
Default: `false` +
====

`server.cors.allowOrigin`::
+
====
**Experimental:** List of origins permitted to access resources. You must specify explicit hostnames and not use `server.cors.allowOrigin: ["*"]` when `server.cors.allowCredentials: true`.

Data type: `string` +
Default: `*` +
====

`server.compression.referrerWhitelist`::
+
====
Specifies an array of trusted hostnames, such as the {{kib}} host, or a reverse proxy sitting in front of it. This determines whether HTTP compression may be used for responses, based on the request `Referer` header. This setting may not be used when [`server.compression.enabled`](#server-compression) is set to `false`.

Data type: `string` +
Default: `none` +
====

`server.compression.brotli.enabled`::
+
====
Set to `true` to enable brotli (br) compression format. This setting is available in {{ecloud}} 8.6.0 and later versions.


NOTE: Browsers not supporting brotli compression will fallback to using gzip instead. This setting may not be used when [`server.compression.enabled`](#server-compression) is set to `false`.
Data type: `bool` +
Default: `false` +
====


[[server-securityResponseHeaders-strictTransportSecurity]]
`server.securityResponseHeaders.strictTransportSecurity`::
+
====
Controls whether the [`Strict-Transport-Security`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security) header is used in all responses to the client from the {{kib}} server, and specifies what value is used. Allowed values are any text value or `null`. To disable, set to `null`.

Data type: `string` +
Default: `null` +
====


[[server-securityResponseHeaders-xContentTypeOptions]]
`server.securityResponseHeaders.xContentTypeOptions`::
+
====
Controls whether the [`X-Content-Type-Options`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options) header is used in all responses to the client from the {{kib}} server, and specifies what value is used. Allowed values are `nosniff` or `null`. To disable, set to `null`.

Data type: `string` +
Default: `nosniff` +
====


[[server-securityResponseHeaders-referrerPolicy]]
`server.securityResponseHeaders.referrerPolicy`::
+
====
Controls whether the [`Referrer-Policy`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy) header is used in all responses to the client from the {{kib}} server, and specifies what value is used. Allowed values are `no-referrer`, `no-referrer-when-downgrade`, `origin`, `origin-when-cross-origin`, `same-origin`, `strict-origin`, `strict-origin-when-cross-origin`, `unsafe-url`, or `null`. To disable, set to `null`.

Data type: `string` +
Default: `strict-origin-when-cross-origin` +
====


[[$$$server-securityResponseHeaders-permissionsPolicy]]
`server.securityResponseHeaders.permissionsPolicy`::
+
====


preview::[]

Controls whether the [`Permissions-Policy`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy) header is used in all responses to the client from the {{kib}} server, and specifies what value is used. Allowed values are any text value or `null`. Refer to the [`Permissions-Policy` documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy) for defined directives, values, and text format. To disable, set to `null`.

Data type: `string` +
Default: `camera=(), display-capture=(), fullscreen=(self), geolocation=(), microphone=(), web-share=()` +
====


[[server-securityResponseHeaders-permissionsPolicyReportOnly]]
`server.securityResponseHeaders.permissionsPolicyReportOnly`::
+
====


preview::[]

Controls whether the [`Permissions-Policy-Report-Only`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy) header is used in all responses to the client from the {{kib}} server, and specifies what value is used. Allowed values are any text value or `null`. Refer to the [`Permissions-Policy` documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy) for defined directives, values, and text format.

Data type: `string` +
====


[[server-securityResponseHeaders-disableEmbedding]]
`server.securityResponseHeaders.disableEmbedding`::
+
====
Controls whether the [`Content-Security-Policy`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) and [`X-Frame-Options`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) headers are configured to disable embedding {{kib}} in other webpages using iframes. When set to `true`, secure headers are used to disable embedding, which adds the `frame-ancestors: 'self'` directive to the `Content-Security-Policy` response header and adds the `X-Frame-Options: SAMEORIGIN` response header.

Data type: `bool` +
Default: `false` +
====


[[server-securityResponseHeaders-crossOriginOpenerPolicy]]
`server.securityResponseHeaders.crossOriginOpenerPolicy`::
+
====
Controls whether the [`Cross-Origin-Opener-Policy`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy) header is used in all responses to the client from the {{kib}} server, and specifies what value is used. Allowed values are `unsafe-none`, `same-origin-allow-popups`, `same-origin`, or `null`. To disable, set to `null`. This setting is available in {{ecloud}} 8.7.0 and later versions.

Data type: `string` +
Default: `same-origin` +
====

`server.customResponseHeaders`::
+
====
Header names and values to send on all responses to the client from the {{kib}} server.

Data type: `string` +
Default: `{}` +
====


[[server-shutdownTimeout]]
`server.shutdownTimeout`::
+
====
Sets the grace period for {{kib}} to attempt to resolve any ongoing HTTP requests after receiving a `SIGTERM`/`SIGINT` signal, and before shutting down. Any new HTTP requests received during this period are rejected, because the incoming socket is closed without further processing.

Data type: `string` +
Default: `30s` +
====


[[server-host]]
`server.host`::
+
====
This setting specifies the host of the back end server. To allow remote users to connect, set the value to the IP address or DNS name of the {{kib}} server. Use `0.0.0.0` to make Kibana listen on all IPs (public and private).

Data type: `string` +
Default: `localhost` +
====

`server.keepaliveTimeout`::
+
====
The number of milliseconds to wait for additional data before restarting the [`server.socketTimeout`](#server-socketTimeout) counter.

Data type: `int` +
Default: `120000` +
====


[[server-maxPayload]]
`server.maxPayload`::
+
====
The maximum payload size in bytes for incoming server requests.

Data type: `int` +
Default: `1048576` +
====

`server.name`::
+
====
A human-readable display name that identifies this {{kib}} instance.

Data type: `string` +
Default: `your-hostname` +
====


[[server-port]]
`server.port`::
+
====
{{kib}} is served by a back end server. This setting specifies the port to use.

Data type: `int` +
Default: `5601` +
====


[[$$$server-protocol]]
`server.protocol`::
+
====


preview::[]

The HTTP protocol to use, either `http1` or `http2`. Set to `http1` to opt out of `HTTP/2` support when TLS is enabled. Use of `http1` may impact browser loading performance especially for dashboards with many panels.


NOTE: By default, enabling `http2` requires a valid `h2c` configuration, meaning that TLS must be enabled via [`server.ssl.enabled`](#server-ssl-enabled) and [`server.ssl.supportedProtocols`](#server-ssl-supportedProtocols), if specified, must contain at least `TLSv1.2` or `TLSv1.3`. Strict validation of the `h2c` setup can be disabled by adding `server.http2.allowUnsecure: true` to the configuration.
Data type: `string` +
Default: `'http2' if TLS is enabled, otherwise 'http1'` +
====


[[server-rate-limiter-enabled]]
`server.rateLimiter.enabled`::
+
====


preview::[]

Enables rate-limiting of requests to the {{kib}} server based on Node.js' Event Loop Utilization. If the average event loop utilization for the specified term exceeds the configured threshold, the server will respond with a `429 Too Many Requests` status code.

Data type: `bool` +
Default: `false` +
====


[[server-rate-limiter-enabled]]
`server.rateLimiter.enabled`::
+
====
Enables rate-limiting of requests to the {{kib}} server based on Node.js' Event Loop Utilization. If the average event loop utilization for the specified term exceeds the configured threshold, the server will respond with a `429 Too Many Requests` status code.

This functionality should be used carefully as it may impact the server’s availability. The configuration options vary per environment, so it is recommended to enable this option in a testing environment first, adjust the rate-limiter configuration, and then roll it out to production.

Data type: `bool` +
Default: `false` +
====

`server.rateLimiter.elu`::
+
====
The Event Loop Utilization (ELU) threshold for rate-limiting requests to the {{kib}} server. The ELU is a value between 0 and 1, representing the average event loop utilization over the specified term. If the average ELU exceeds this threshold, the server will respond with a `429 Too Many Requests` status code.

In a multi-instance environment with autoscaling, this value is usually between 0.6 and 0.8 to give the autoscaler enough time to react. This value can be higher in a single-instance environment but should not exceed 1.0. In general, the lower the value, the more aggressive the rate limiting. And the highest possible option should be used to prevent the {{kib}} server from being terminated.

Data type: `float` +
====

`server.rateLimiter.term`::
+
====
This value is one of `short`, `medium`, or `long`, representing the term over which the average event loop utilization is calculated. It uses exponential moving averages (EMA) to smooth out the utilization values. Each term corresponds to `15s`, `30s`, and `60s`, respectively.

The term value also changes the way the rate limiter sees the trend in the load:

* `short`: `elu.short > server.rateLimiter.term`;

* `medium`: `elu.short > server.rateLimiter.elu AND elu.medium > server.rateLimiter.elu`;

* `long`: `elu.short > server.rateLimiter.elu AND elu.medium > server.rateLimiter.elu AND elu.long > server.rateLimiter.elu`.

This behavior prevents requests from being throttled if the load starts decreasing. In general, the shorter the term, the more aggressive the rate limiting. In the multi-instance environment, the `medium` term makes the most sense as it gives the {{kib}} server enough time to spin up a new instance and prevents the existing instances from being terminated.

Data type: `enum` +

Options:

* `short` - 15s
* `medium` - 30s
* `long` - 60s

====


[[server-requestId-allowFromAnyIp]]
`server.requestId.allowFromAnyIp`::
+
====
Sets whether or not the `X-Opaque-Id` header should be trusted from any IP address for identifying requests in logs and forwarded to Elasticsearch.

Data type: `bool` +
====

`server.requestId.ipAllowlist`::
+
====
A list of IPv4 and IPv6 address which the `X-Opaque-Id` header should be trusted from. Normally this would be set to the IP addresses of the load balancers or reverse-proxy that end users use to access Kibana. If any are set, [`server.requestId.allowFromAnyIp`](#server-requestId-allowFromAnyIp) must also be set to `false.`

Data type: `string` +
====


[[server-rewriteBasePath]]
`server.rewriteBasePath`::
+
====
Specifies whether {{kib}} should rewrite requests that are prefixed with [`server.basePath`](#server-basePath) or require that they are rewritten by your reverse proxy.

Data type: `bool` +
Default: `false` +
====


[[server-socketTimeout]]
`server.socketTimeout`::
+
====
The number of milliseconds to wait before closing an inactive socket.

Data type: `int` +
Default: `120000` +
====


[[server-payloadTimeout]]
`server.payloadTimeout`::
+
====
Sets the maximum time allowed for the client to transmit the request payload (body) before giving up and responding with a Request Timeout (408) error response.

Data type: `int` +
Default: `20000` +
====


[[server-ssl-cert]]
`server.ssl.certificate`::
+
====
Use with [`server.ssl.key`](#server-ssl-cert-key). Paths to a PEM-encoded X.509 server certificate and its corresponding private key. These are used by {{kib}} to establish trust when receiving inbound SSL/TLS connections from users.


NOTE: These settings cannot be used in conjunction with [`server.ssl.keystore.path`](#server-ssl-keystore-path).
Data type: `string` +
====


[[server-ssl-cert-key]]
`server.ssl.key`::
+
====
Use with [`server.ssl.certificate`](#server-ssl-cert). Paths to a PEM-encoded X.509 server certificate and its corresponding private key. These are used by {{kib}} to establish trust when receiving inbound SSL/TLS connections from users.


NOTE: These settings cannot be used in conjunction with [`server.ssl.keystore.path`](#server-ssl-keystore-path).
Data type: `string` +
====


[[server-ssl-certificateAuthorities]]
`server.ssl.certificateAuthorities`::
+
====
Paths to one or more PEM-encoded X.509 certificate authority (CA) certificates which make up a trusted certificate chain for {{kib}}. This chain is used by {{kib}} to establish trust when receiving inbound SSL/TLS connections from end users. If PKI authentication is enabled, this chain is also used by {{kib}} to verify client certificates from end users.

In addition to this setting, trusted certificates may be specified via [`server.ssl.keystore.path`](#server-ssl-keystore-path) and/or [`server.ssl.truststore.path`](#server-ssl-truststore-path).

Data type: `string` +
====


[[server-ssl-cipherSuites]]
`server.ssl.cipherSuites`::
+
====
Details on the format, and the valid options, are available via the [OpenSSL cipher list format documentation](https://www.openssl.org/docs/man1.1.1/man1/ciphers.md#CIPHER-LIST-FORMAT).

Data type: `string` +
Default: `TLS_AES_256_GCM_SHA384 TLS_CHACHA20_POLY1305_SHA256 TLS_AES_128_GCM_SHA256 ECDHE-RSA-AES128-GCM-SHA256, ECDHE-ECDSA-AES128-GCM-SHA256, ECDHE-RSA-AES256-GCM-SHA384, ECDHE-ECDSA-AES256-GCM-SHA384, DHE-RSA-AES128-GCM-SHA256, ECDHE-RSA-AES128-SHA256, DHE-RSA-AES128-SHA256, ECDHE-RSA-AES256-SHA384, DHE-RSA-AES256-SHA384, ECDHE-RSA-AES256-SHA256, DHE-RSA-AES256-SHA256, HIGH,!aNULL, !eNULL, !EXPORT, !DES, !RC4, !MD5, !PSK, !SRP, !CAMELLIA` +
====

`server.ssl.clientAuthentication`::
+
====
Controls the behavior in {{kib}} for requesting a certificate from client connections.

Data type: `enum` +

Options:

* `required` - Refuses to establish the connection unless a client presents a certificate.
* `optional` - Allows a client to present a certificate if it has one.
* `none` - Prevents a client from presenting a certificate.

Default: `none` +
====


[[server-ssl-enabled]]
`server.ssl.enabled`::
+
====
Enables SSL/TLS for inbound connections to {{kib}}. When set to `true`, a certificate and its corresponding private key must be provided. These can be specified via [`server.ssl.keystore.path`](#server-ssl-keystore-path) or the combination of [`server.ssl.certificate`](#server-ssl-cert-key) and [`server.ssl.key`](#server-ssl-cert-key).

Data type: `bool` +
Default: `false` +
====

`server.ssl.keyPassphrase`::
+
====
The password that decrypts the private key that is specified via [`server.ssl.key`](#server-ssl-cert-key). This value is optional, as the key may not be encrypted.

Data type: `string` +
====


[[server-ssl-keystore-path]]
`server.ssl.keystore.path`::
+
====
Path to a PKCS#12 keystore that contains an X.509 server certificate and its corresponding private key. If the keystore contains any additional certificates, those will be used as a trusted certificate chain for {{kib}}. All of these are used by {{kib}} to establish trust when receiving inbound SSL/TLS connections from end users. The certificate chain is also used by {{kib}} to verify client certificates from end users when PKI authentication is enabled.

In addition to this setting, trusted certificates may be specified via [`server.ssl.certificateAuthorities`](#server-ssl-certificateAuthorities) and/or [`server.ssl.truststore.path`](#server-ssl-truststore-path).


NOTE: This setting cannot be used in conjunction with [`server.ssl.certificate`](#server-ssl-cert-key) or [`server.ssl.key`](#server-ssl-cert-key).
Data type: `string` +
====

`server.ssl.keystore.password`::
+
====
The password that will be used to decrypt the keystore specified via [`server.ssl.keystore.path`](#server-ssl-keystore-path). If the keystore has no password, leave this unset. If the keystore has an empty password, set this to `""`.

Data type: `string` +
====


[[server-ssl-truststore-path]]
`server.ssl.truststore.path`::
+
====
Path to a PKCS#12 trust store that contains one or more X.509 certificate authority (CA) certificates which make up a trusted certificate chain for {{kib}}. This chain is used by {{kib}} to establish trust when receiving inbound SSL/TLS connections from end users. If PKI authentication is enabled, this chain is also used by {{kib}} to verify client certificates from end users.

In addition to this setting, trusted certificates may be specified via [`server.ssl.certificateAuthorities`](#server-ssl-certificateAuthorities) and/or [`server.ssl.keystore.path`](#server-ssl-keystore-path).

Data type: `string` +
====

`server.ssl.truststore.password`::
+
====
The password that will be used to decrypt the trust store specified via [`server.ssl.truststore.path`](#server-ssl-truststore-path). If the trust store has no password, leave this unset. If the trust store has an empty password, set this to `""`.

Data type: `string` +
====

`server.ssl.redirectHttpFromPort`::
+
====
{{kib}} binds to this port and redirects all http requests to https over the port configured as [`server.port`](#server-port).

Data type: `int` +
====


[[server-ssl-supportedProtocols]]
`server.ssl.supportedProtocols`::
+
====
An array of supported protocols with versions. Valid protocols: `TLSv1`, `TLSv1.1`, `TLSv1.2`, `TLSv1.3`. Enabling `TLSv1.1` would require both setting the `--tls-min-1.1` option in the `node.options` configuration and adding `TLSv1.1` to `server.ssl.supportedProtocols`. `HTTP/2` requires the use of minimum `TLSv1.2` for secure connections.

Data type: `string` +
Default: `TLSv1.2, TLSv1.3` +
====


[[server-uuid]]
`server.uuid`::
+
====
The unique identifier for this {{kib}} instance. It must be a valid UUIDv4. It gets automatically generated on the first startup if not specified and persisted in the `data` path.

Data type: `string` +
====


[[settings-xsrf-allowlist]]
`server.xsrf.allowlist`::
+
====
It is not recommended to disable protections for arbitrary API endpoints. Instead, supply the `kbn-xsrf` header. The [`server.xsrf.allowlist`](#settings-xsrf-allowlist) setting requires the following format:

```text

*Default: [ ]* An array of API endpoints which should be exempt from Cross-Site Request Forgery ("XSRF") protections.

```

This setting is available in {{ecloud}} 8.0.0 and later versions.

Data type: `string` +
====


[[settings-xsrf-disableProtection]]
`server.xsrf.disableProtection`::
+
====
Setting this to `true` will completely disable Cross-site request forgery protection in Kibana. This is not recommended.

Data type: `bool` +
Default: `false` +
====

`status.allowAnonymous`::
+
====
If authentication is enabled, setting this to `true` enables unauthenticated users to access the {{kib}} server status API and status page.

Data type: `bool` +
Default: `false` +
====


[[telemetry-allowChangingOptInStatus]]
`telemetry.allowChangingOptInStatus`::
+
====
When `false`, users cannot change the opt-in status through [Advanced Settings](/reference/advanced-settings.md), and {{kib}} only looks at the value of [`telemetry.optIn`](#settings-telemetry-optIn) to determine whether to send telemetry data or not.

Data type: `bool` +
Default: `true` +
====


[[settings-telemetry-optIn]]
`telemetry.optIn`::
+
====
Set to `false` to stop sending any telemetry data to Elastic. Reporting your cluster statistics helps us improve your user experience. When `false`, the telemetry data is never sent to Elastic.<br>

This setting can be changed at any time in [Advanced Settings](/reference/advanced-settings.md). To prevent users from changing it, set [`telemetry.allowChangingOptInStatus`](#telemetry-allowChangingOptInStatus) to `false`.

Data type: `string` +
Default: `true` +
====

`unifiedSearch.autocomplete.valueSuggestions.timeout`::
+
====
Time in milliseconds to wait for autocomplete suggestions from {{es}}. This value must be a whole number greater than zero.

Data type: `int` +
Default: `1000` +
====

`unifiedSearch.autocomplete.valueSuggestions.terminateAfter`::
+
====
Maximum number of documents loaded by each shard to generate autocomplete suggestions. This value must be a whole number greater than zero.


NOTE: To reload the logging settings, send a SIGHUP signal to {{kib}}. For more logging configuration options, see the [Configure Logging in {{kib}}](docs-content://deploy-manage/monitor/logging-configuration/kibana-logging.md) guide.
Data type: `string` +
Default: `100000` +
====

`vega.enableExternalUrls`::
+
====
Set to `true` to allow Vega vizualizations to use data from sources other than the linked Elasticsearch cluster. In version 8.0 and later, the `vega.enableExternalUrls` is not supported. Use `vis_type_vega.enableExternalUrls` instead.

Data type: `bool` +
====

`vis_type_table.legacyVisEnabled`::
+
====
For 7.x versions version 7.11 and later, a new version of the datatable visualization is used. Set to `true` to enable the legacy version. In version 8.0 and later, the old implementation is removed and this setting is no longer supported.

Data type: `bool` +
====

`vis_type_vega.enableExternalUrls`::
+
====
Set this value to true to allow Vega to use any URL to access external data sources and images. When false, Vega can only get data from {{es}}.

Data type: `bool` +
Default: `false` +
====

`xpack.ccr.ui.enabled`::
+
====
Set this value to false to disable the Cross-Cluster Replication UI.

Data type: `bool` +
Default: `true` +
====


[[settings-explore-data-in-context]]
`xpack.discoverEnhanced.actions.exploreDataInContextMenu.enabled`::
+
====
Enables the **Explore underlying data** option that allows you to open **Discover** from a dashboard panel and view the panel data.

When you create visualizations using the **Lens** drag-and-drop editor, you can use the toolbar to open and explore your data in **Discover**. For more information, check out [Explore the data in Discover](docs-content://explore-analyze/visualize/lens.md#explore-lens-data-in-discover).

Data type: `bool` +
Default: `false` +
====


[[$$$settings-explore-data-in-chart]]
`pack.discoverEnhanced.actions.exploreDataInChart.enabled`::
+
====
Enables you to view the underlying documents in a data series from a dashboard panel.

Data type: `bool` +
Default: `false` +
====


[[settings-explore-data-in-chart]]
`xpack.discoverEnhanced.actions.exploreDataInChart.enabled`::
+
====
Enables you to view the underlying documents in a data series from a dashboard panel.

Data type: `bool` +
Default: `false` +
====

`xpack.ilm.ui.enabled`::
+
====
Set this value to false to disable the Index Lifecycle Policies UI.

Data type: `bool` +
Default: `true` +
====

`xpack.index_management.ui.enabled`::
+
====
Set this value to false to disable the Index Management UI.

Data type: `bool` +
Default: `true` +
====

`xpack.license_management.ui.enabled`::
+
====
Set this value to false to disable the License Management UI.

Data type: `bool` +
Default: `true` +
====

`xpack.remote_clusters.ui.enabled`::
+
====
Set this value to false to disable the Remote Clusters UI.

Data type: `bool` +
Default: `true` +
====

`xpack.rollup.ui.enabled`::
+
====
**Deprecated:** Deprecated in 8.11.0.

Set this value to false to disable the Rollup Jobs UI.


WARNING: Rollups are deprecated and will be removed in a future version. Use [downsampling](docs-content://manage-data/data-store/data-streams/downsampling-time-series-data-stream.md) instead.
Data type: `bool` +
Default: `true` +
====

`xpack.securitySolution.maxUploadResponseActionFileBytes`::
+
====
Allow to configure the max file upload size for use with the Upload File Repsonse action available with the Defend Integration. To learn more, check [Endpoint Response actions](docs-content://solutions/security/endpoint-response-actions.md). This setting is available in {{ecloud}} 8.9.0 and later versions.

Data type: `bool` +
====

`xpack.snapshot_restore.ui.enabled`::
+
====
Set this value to false to disable the Snapshot and Restore UI.

Data type: `bool` +
Default: `true` +
====

`xpack.upgrade_assistant.ui.enabled`::
+
====
Set this value to false to disable the Upgrade Assistant UI.

Data type: `bool` +
Default: `true` +
====


