
// This is a generated file. Please don't update it directly.
// Collection: Example settings file
// Product: Kibana

This page is a set of example settings generated from `docs/settings-gen/source/kibana-settings-schema.yml`.

These examples includes all of the available information that we can provide for a setting, including a description, available options, the default option, a warning, etc. Note that most of these fields are optional.


[float]
[[kibana-settings-schema-planetary]]
=== Planetary settings

Planetary settings can be used to configure the planets. Currently only Mercury, Venus, and Earth are supported.

A group description, like this one, can include warnings, tips, code examples, etc., exactly the same as the settings descriptions.


[[kibana-example-setting-mercury]]
.`kibana.example.setting.mercury` {ess-icon}
[%collapsible]
====
The first planet from from <<kibana-example-setting-sun,The Sun>> and the smallest in the Solar System.

In English, it is named after the ancient Roman god Mercurius (Mercury), god of commerce and communication, and the messenger of the gods.

Mercury is adjacent to the planet <<kibana-example-setting-venus,Venus>>


WARNING: This feature is available in Kibana 7.17.4 and 8.3.0 onwards but is not supported in Kibana 8.0, 8.1 or 8.2.

Options:

* `visit` - Arrange a trip to this planet.
* `inhabit` - Build a colony on this planet.
* `avoid` - Don't visit this planet at all.

Default: `avoid` +
Type: `static` +

**Example**

include::../examples/example-setting-example.asciidoc[]
====


[[kibana-example-setting-venus]]
.`kibana.example.setting.venus`
[%collapsible]
====


preview::[]

Venus is the second planet from <<kibana-example-setting-sun,The Sun>>.

It is a terrestrial planet and is the closest in mass and size to its orbital neighbour, <<kibana-example-setting-earth,Earth>>.


IMPORTANT: All visitors to Venus must have an inter-planetary passport that will be validtip for a minimum of six months beyond your date of return.

Options:

* `visit` - Arrange a trip to this planet.
* `inhabit` - Build a colony on this planet.
* `avoid` - Don't visit this planet at all.

Default: `visit` +
Type: `static.` +
====


[[kibana-example-setting-earth]]
.`kibana.example.setting.earth`
[%collapsible]
====
**Deprecated:** Starting in version 8.0.0 this setting is deprecated. Use <<kibana-example-setting-mercury,`kibana-example-setting-mercury`>> or <<kibana-example-setting-venus,`kibana-example-setting-venus`>> instead.

Earth is the third planet from <<kibana-example-setting-sun,The Sun>> and the only astronomical object known to harbor life.

This is enabled by Earth being an ocean world, the only one in the Solar System sustaining liquid surface water.


TIP: To fully enjoy your trip we recommend bringing sunscreen and a hat.

Options:

* `visit` - Arrange a trip to this planet.
* `inhabit` - Build a colony on this planet.
* `avoid` - Don't visit this planet at all.

Default: `inhabit` +
Type: `static` +
====


[float]
[[kibana-settings-schema-solar]]
=== Celestial settings

Celestial settings can be used to configure the Sun and other non-planetary objects. Use these settings carefully as the Sun provides sustenance to <<kibana-example-setting-earth,Earth>> and all of the life that inhabits it.

Your group description can include warnings, examples, etc., just like the settings descriptions.


[[kibana-example-setting-sun]]
.`kibana.example.setting.sun` {ess-icon}
[%collapsible]
====
The Sun is the star at the center of the Solar System.

It is a massive, nearly perfect sphere of hot plasma, heated to incandescence by nuclear fusion reactions in its core, radiating the energy from its surface mainly as visible light and infrared radiation with 10% at ultraviolet energies.

Specify a value from `0` to `10`, inclusive.


WARNING: Due to the heat, visits to the sun should not exceed a day or two. Bring a fan.
Type: `dynamic` +
====


[[kibana-example-setting-arcturus]]
.`kibana.example.setting.arcturus` {ess-icon}
[%collapsible]
====
Arcturus is the brightest star in the northern constellation of Bootes.

With an apparent visual magnitude of -0.05,[2] it is the fourth-brightest star in the night sky, and the brightest in the northern celestial hemisphere.

Type: `dynamic` +
====


