
// This is a generated file; please don't update it directly.
// Instead, the updatable source for these settings can be found in kibana-alert-action-settings.yml
// Collection: Alerting and action settings in Kibana
// Product: Kibana



[float]
[[general-alert-action-settings]]
=== General settings


.`xpack.encryptedSavedObjects.encryptionKey`
[%collapsible]
====
A string of 32 or more characters used to encrypt sensitive properties on alerting rules and actions before they're stored in Elasticsearch. Third party credentials &mdash; such as the username and password used to connect to an SMTP service &mdash; are an example of encrypted properties.

Kibana offers a <<kibana-encryption-keys, CLI tool>> to help generate this encryption key.

If not set, Kibana will generate a random key on startup, but all alerting and action functions will be blocked. Generated keys are not allowed for alerting and actions because when a new key is generated on restart, existing encrypted data becomes inaccessible. For the same reason, alerting and actions in high-availability deployments of Kibana will behave unexpectedly if the key isn't the same on all instances of Kibana.

Although the key can be specified in clear text in `kibana.yml`, it's recommended to store this key securely in the <<secure-settings,Kibana Keystore>>. Be sure to back up the encryption key value somewhere safe, as your alerting rules and actions will cease to function due to decryption failures should you lose it.  If you want to rotate the encryption key, be sure to follow the instructions on <<encryption-key-rotation, encryption key rotation>>.

====


[float]
[[action-settings]]
=== Action settings


.`xpack.actions.allowedHosts` {ess-icon}
[%collapsible]
====
A list of hostnames that Kibana is allowed to connect to when built-in actions are triggered. It defaults to `["*"]`, allowing any host, but keep in mind the potential for SSRF attacks when hosts are not explicitly added to the allowed hosts. An empty list `[]` can be used to block built-in actions from making any external connections.

Note that hosts associated with built-in actions, such as Slack and PagerDuty, are not automatically added to allowed hosts. If you are not using the default `["*"]` setting, you must ensure that the corresponding endpoints are added to the allowed hosts as well.

====

.`xpack.actions.customHostSettings` {ess-icon}
[%collapsible]
====
A list of custom host settings to override existing global settings.

Each entry in the list must have a `url` property, to associate a connection type (mail or https), hostname and port with the remaining options in the entry.

The settings in `xpack.actions.customHostSettings` can be used to override the global option `xpack.actions.ssl.verificationMode` and provide customized TLS settings on a per-server basis. Set `xpack.actions.ssl.verificationMode` to the value to be used by default for all servers, then add an entry in `xpack.actions.customHostSettings` for every server that requires customized settings.

Default: `an empty list` +


include::../embeds/example-xpack-actions-customhostsettings.asciidoc[]
====

.`xpack.actions.customHostSettings[n].url` {ess-icon}
[%collapsible]
====
A URL associated with this custom host setting.  Should be in the form of `protocol://hostname:port`, where `protocol` is `https` or `smtp`.  If the port is not provided, 443 is used for `https` and 25 is used for `smtp`.  The `smtp` URLs are used for the Email actions that use this server, and the `https` URLs are used for actions which use `https` to connect to services.

Entries with `https` URLs can use the `ssl` options, and entries with `smtp` URLs can use both the `ssl` and `smtp` options.

No other URL values should be part of this URL, including paths, query strings, and authentication information.  When an http or smtp request is made as part of running an action, only the protocol, hostname, and port of the URL for that request are used to look up these configuration values.

====

.`xpack.actions.customHostSettings[n].smtp.ignoreTLS` {ess-icon}
[%collapsible]
====
A boolean value indicating that TLS must not be used for this connection. The options `smtp.ignoreTLS` and `smtp.requireTLS` can not both be set to true.

Default: `false` +
====

.`xpack.actions.customHostSettings[n].smtp.requireTLS` {ess-icon}
[%collapsible]
====
A boolean value indicating that TLS must be used for this connection. The options `smtp.ignoreTLS` and `smtp.requireTLS` can not both be set to true.

Default: `false` +
====


[[action-config-custom-host-verification-mode]]
.`xpack.actions.customHostSettings[n].ssl.verificationMode` {ess-icon}
[%collapsible]
====
Controls the verification of the server certificate that Kibana receives when making an outbound SSL/TLS connection to the host server. Valid values are `full`, `certificate`, and `none`. Use `full` to perform hostname verification, `certificate` to skip hostname verification, and `none` to skip verification. Default: `full`. <<elasticsearch-ssl-verificationMode,Equivalent Kibana setting>>. Overrides the general `xpack.actions.ssl.verificationMode` configuration for requests made for this hostname/port.

====

.`xpack.actions.customHostSettings[n].ssl.certificateAuthoritiesFiles`
[%collapsible]
====
A file name or list of file names of PEM-encoded certificate files to use to validate the server.

====

.`xpack.actions.customHostSettings[n].ssl.certificateAuthoritiesData` {ess-icon}
[%collapsible]
====
The contents of one or more PEM-encoded certificate files in multiline format. This configuration can be used for environments where the files cannot be made available.

====


[[action-config-email-domain-allowlist]]
.`xpack.actions.email.domain_allowlist` {ess-icon}
[%collapsible]
====
A list of allowed email domains which can be used with the email connector. When this setting is not used, all email domains are allowed. When this setting is used, if any email is attempted to be sent that (a) includes an addressee with an email domain that is not in the allowlist, or (b) includes a from address domain that is not in the allowlist, it will fail with a message indicating the email is not allowed.


WARNING: This feature is available in Kibana 7.17.4 and 8.3.0 onwards but is not supported in Kibana 8.0, 8.1 or 8.2. As such, this setting should be removed before upgrading from 7.17 to 8.0, 8.1 or 8.2. It is possible to configure the settings in 7.17.4 and then upgrade to 8.3.0 directly.
====

.`xpack.actions.enableFooterInEmail` {ess-icon}
[%collapsible]
====
A boolean value indicating that a footer with a relevant link should be added to emails sent as alerting actions.

Default: `true` +
====

.`xpack.actions.enabledActionTypes` {ess-icon}
[%collapsible]
====
A list of action types that are enabled. It defaults to `["*"]`, enabling all types. The names for built-in Kibana action types are prefixed with a `.` and include: `.email`, `.index`, `.jira`, `.opsgenie`, `.pagerduty`, `.resilient`, `.server-log`, `.servicenow`, .`servicenow-itom`, `.servicenow-sir`, `.slack`, `.swimlane`, `.teams`, `.tines`, `.torq`, `.xmatters`,  `.gen-ai`,  `.bedrock`, `.gemini`,  `.d3security`, and `.webhook`. An empty list `[]` will disable all action types.

Disabled action types will not appear as an option when creating new connectors, but existing connectors and actions of that type will remain in Kibana and will not function.


IMPORTANT: <<pre-configured-connectors,Preconfigured connectors>> are not affected by this setting.
====

.`xpack.actions.microsoftExchangeUrl`
[%collapsible]
====
The URL for the Microsoft Azure Active Directory endpoint to use for MS Exchange email authentication.

Default: `https://login.microsoftonline.com` +
====

.`xpack.actions.microsoftGraphApiUrl`
[%collapsible]
====
The URL for the Microsoft Graph API endpoint to use for MS Exchange email authentication.

Default: `https://graph.microsoft.com/v1.0` +
====

.`xpack.actions.microsoftGraphApiScope`
[%collapsible]
====
The URL for the Microsoft Graph API scope endpoint to use for MS Exchange email authentication.

Default: `https://graph.microsoft.com/.default` +
====

.`xpack.actions.proxyUrl` {ess-icon}
[%collapsible]
====
Specifies the proxy URL to use, if using a proxy for actions. By default, no proxy is used.

Proxies may be used to proxy http or https requests through a proxy using the http or https protocol.  Kibana only uses proxies in "CONNECT" mode (sometimes referred to as "tunneling" TCP mode, compared to HTTP mode).  That is, Kibana will always make requests through a proxy using the HTTP `CONNECT` method.

If your proxy is using the https protocol (vs the http protocol), the setting `xpack.actions.ssl.proxyVerificationMode: none` will likely be needed, unless your proxy's certificates are signed using a publicly available certificate authority.

There is currently no support for using basic authentication with a proxy (authentication for the proxy itself, not the URL being requested through the proxy).

====

.`xpack.actions.proxyBypassHosts` {ess-icon}
[%collapsible]
====
Specifies hostnames which should not use the proxy, if using a proxy for actions. The value is an array of hostnames as strings.

By default, all hosts will use the proxy, but if an action's hostname is in this list, the proxy will not be used.  The settings `xpack.actions.proxyBypassHosts` and `xpack.actions.proxyOnlyHosts` cannot be used at the same time.



include::../embeds/example-xpack-actions-proxybypasshosts.asciidoc[]
====

.`xpack.actions.proxyOnlyHosts` {ess-icon}
[%collapsible]
====
Specifies hostnames which should only use the proxy, if using a proxy for actions. The value is an array of hostnames as strings.

By default, no hosts will use the proxy, but if an action's hostname is in this list, the proxy will be used.  The settings `xpack.actions.proxyBypassHosts` and `xpack.actions.proxyOnlyHosts` cannot be used at the same time.



include::../embeds/example-xpack-actions-proxyonlyhosts.asciidoc[]
====

.`xpack.actions.proxyHeaders` {ess-icon}
[%collapsible]
====
Specifies HTTP headers for the proxy, if using a proxy for actions.

Default: `HASH(0x12bb51a88)` +
====


[[action-config-proxy-verification-mode]]
.`xpack.actions.ssl.proxyVerificationMode` {ess-icon}
[%collapsible]
====
Controls the verification for the proxy server certificate that Kibana receives when making an outbound SSL/TLS connection to the proxy server.

Use `full` to perform hostname verification, `certificate` to skip hostname verification, and `none` to skip verification.

<<elasticsearch-ssl-verificationMode,Equivalent Kibana setting>>


Options:

* `full`
* `certificate`
* `none`

Default: `full` +
====


[[action-config-verification-mode]]
.`xpack.actions.ssl.verificationMode` {ess-icon}
[%collapsible]
====
Controls the verification for the server certificate that Elastic Maps Server receives when making an outbound SSL/TLS connection for actions. Valid values are `full`, `certificate`, and `none`. Use `full` to perform hostname verification, `certificate` to skip hostname verification, and `none` to skip verification.

<<elasticsearch-ssl-verificationMode,Equivalent Kibana setting>>

This setting can be overridden for specific URLs by using the setting `xpack.actions.customHostSettings[n].ssl.verificationMode` (described above) to a different value.


Options:

* `full`
* `certificate`
* `none`

Default: `full` +
====

.`xpack.actions.maxResponseContentLength` {ess-icon}
[%collapsible]
====
Specifies the max number of bytes of the http response for requests to external resources.

Default: `1000000 (1MB)` +
====

.`xpack.actions.responseTimeout` {ess-icon}
[%collapsible]
====
Specifies the time allowed for requests to external resources. Requests that take longer are canceled. The time is formatted as a number and a time unit (`ms`, `s`, `m`, `h`, `d`, `w`, `M`, or `Y`). For example, `20m`, `24h`, `7d`, `1w`. Default: `60s`.

====

.`xpack.actions.run.maxAttempts` {ess-icon}
[%collapsible]
====
Specifies the maximum number of times an action can be attempted to run.


Options:

* `minimum 1 and maximum 10`

====

.`xpack.actions.run.connectorTypeOverrides` {ess-icon}
[%collapsible]
====
Overrides the configs under `xpack.actions.run` for the connector type with the given ID. List the connector type identifier and its settings in an array of objects.



include::../embeds/example-xpack.actions-run-connectortypeoverrides.asciidoc[]
====

.`xpack.actions.queued.max` {ess-icon}
[%collapsible]
====
Specifies the maximum number of actions that can be queued.

Default: `1000000` +
====


[float]
[[preconfigured-connector-settings]]
=== Preconfigured connector settings

These settings vary depending on which type of preconfigured connector you're adding.


include::../embeds/example-preconfigured-connector-settings.asciidoc[]

.`xpack.actions.preconfiguredAlertHistoryEsIndex` {ess-icon}
[%collapsible]
====
Enables a preconfigured alert history Elasticsearch <<index-action-type, Index>> connector.

Default: `false` +
====

.`xpack.actions.preconfigured`
[%collapsible]
====
Specifies configuration details that are specific to the type of preconfigured connector.

====

.`xpack.actions.preconfigured.<connector-id>.actionTypeId`
[%collapsible]
====
The type of preconfigured connector.


Options:

* `.email`
* `.index`
* `.opsgenie`
* `.server-log`
* `.resilient`
* `.slack`
* `.webhook`

====

.`xpack.actions.preconfigured.<connector-id>.config`
[%collapsible]
====
The configuration details, which are specific to the type of preconfigured connector.

====

.`xpack.actions.preconfigured.<connector-id>.config.apiProvider`
[%collapsible]
====
For a <<openai-action-type,OpenAI connector>>, specifies the OpenAI API provider.


Options:

* `OpenAI`
* `Azure OpenAI`

====

.`xpack.actions.preconfigured.<connector-id>.config.apiUrl`
[%collapsible]
====
A configuration URL that varies by connector:

* For an <<bedrock-action-type,{bedrock} connector>>, specifies the {bedrock} request URL.

* For an <<gemini-action-type,{gemini} connector>>, specifies the {gemini} request URL.

* For an <<inference-action-type,{inference} connector>>, specifies the Elastic {inference} request.

* For a <<openai-action-type,OpenAI connector>>, specifies the OpenAI request URL.

* For a <<resilient-action-type,{ibm-r} connector>>, specifies the {ibm-r} instance URL.

* For a <<jira-action-type,Jira connector>>, specifies the Jira instance URL.

* For an <<opsgenie-action-type,{opsgenie} connector>>, specifies the {opsgenie} URL. For example, `https://api.opsgenie.com` or `https://api.eu.opsgenie.com`.

* For a <<pagerduty-action-type,PagerDuty connector>>, specifies the PagerDuty event URL. Defaults to `https://events.pagerduty.com/v2/enqueue`.

* For a <<servicenow-action-type,{sn-itsm}>>, <<servicenow-sir-action-type,{sn-sir}>>, or <<servicenow-itom-action-type,{sn-itom} connector>> specifies the ServiceNow instance URL.

* For a <<swimlane-action-type,{swimlane} connector>>, specifies the {swimlane} instance URL.


NOTE: If you are using the `xpack.actions.allowedHosts` setting, make sure the hostname in the URL is added to the allowed hosts.
====

.`xpack.actions.preconfigured.<connector-id>.config.appId`
[%collapsible]
====
An application ID that varies by connector:

* For a <<swimlane-action-type,{swimlane} connector>>, specifies a {swimlane} application identifier.

====

.`xpack.actions.preconfigured.<connector-id>.config.clientId`
[%collapsible]
====
A client identifier that varies by connector:

* For an <<email-action-type,email connector>>, specifies a GUID format value that corresponds to the client ID, which is a part of OAuth 2.0 client credentials authentication.

* For a <<servicenow-itom-action-type,{sn-itom}>>, <<servicenow-action-type,{sn-itsm}>>, or <<servicenow-sir-action-type,{sn-sir} connector>> specifies the client identifier assigned to the OAuth application.

====

.`xpack.actions.preconfigured.<connector-id>.config.configUrl`
[%collapsible]
====
For an <<xmatters-action-type,xMatters connector>> with basic authentication, specifies the request URL for the Elastic Alerts trigger in xMatters.

====

.`xpack.actions.preconfigured.<connector-id>.config.createCommentJson`
[%collapsible]
====
For a <<cases-webhook-action-type,{webhook-cm} connector>>, specifies a stringified JSON payload with Mustache variables that is sent to the create comment URL to create a case comment. The required variable is `case.description`.


NOTE: The JSON is validated after the Mustache variables have been placed when the REST method runs. You should manually ensure that the JSON is valid, disregarding the Mustache variables, so the later validation will pass.
====

.`xpack.actions.preconfigured.<connector-id>.config.createCommentMethod`
[%collapsible]
====
For a <<cases-webhook-action-type,{webhook-cm} connector>>, specifies the REST API HTTP request method to create a case comment in the third-party system.


Options:

* `post`
* `put`
* `patch`

Default: `patch` +
====

.`xpack.actions.preconfigured.<connector-id>.config.createCommentUrl`
[%collapsible]
====
For a <<cases-webhook-action-type,{webhook-cm} connector>>, specifies a REST API URL string to create a case comment by ID in the third-party system.


NOTE: If you are using the `xpack.actions.allowedHosts` setting, make sure the hostname in the URL is added to the allowed hosts.
====

.`xpack.actions.preconfigured.<connector-id>.config.createIncidentJson`
[%collapsible]
====
For a <<cases-webhook-action-type,{webhook-cm} connector>>, specifies a stringified JSON payload with Mustache variables that is sent to the create case URL to create a case. Required variables are `case.title` and `case.description`.


NOTE: The JSON is validated after the Mustache variables have been placed when the REST method runs. You should manually ensure that the JSON is valid, disregarding the Mustache variables, so the later validation will pass.
====

.`xpack.actions.preconfigured.<connector-id>.config.createIncidentMethod`
[%collapsible]
====
For a <<cases-webhook-action-type,{webhook-cm} connector>>, specifies the REST API HTTP request method to create a case in the third-party system


Options:

* `post`
* `put`
* `patch`

Default: `post` +
====

.`xpack.actions.preconfigured.<connector-id>.config.createIncidentUrl`
[%collapsible]
====
For a <<cases-webhook-action-type,{webhook-cm} connector>>, specifies a REST API URL string to create a case in the third-party system.


NOTE: If you are using the `xpack.actions.allowedHosts` setting, make sure the hostname in the URL is added to the allowed hosts.
====

.`xpack.actions.preconfigured.<connector-id>.config.createIncidentResponseKey`
[%collapsible]
====
For a <<cases-webhook-action-type,{webhook-cm} connector>>, specifies a string from the response body of the create case method that corresponds to the external service identifier.

====

.`xpack.actions.preconfigured.<connector-id>.config.defaultModel`
[%collapsible]
====
The default model to use for requests, which varies by connector:

* For an <<bedrock-action-type,{bedrock} connector>>, current support is for the Anthropic Claude models. Defaults to `anthropic.claude-3-5-sonnet-20240620-v1:0`.

* For a <<gemini-action-type,{gemini} connector>>, current support is for the Gemini models. Defaults to `gemini-1.5-pro-002`.

* For a <<openai-action-type,OpenAI connector>>, it is optional and applicable only when `xpack.actions.preconfigured.<connector-id>.config.apiProvider` is `OpenAI`.

====

.`xpack.actions.preconfigured.<connector-id>.config.executionTimeField`
[%collapsible]
====
For an <<index-action-type,index connector>>, a field that indicates when the document was indexed.

====

.`xpack.actions.preconfigured.<connector-id>.config.from`
[%collapsible]
====
For an <<email-action-type,email connector>>, specifies the from address for all emails sent by the connector. It must be specified in `user@host-name` format.

====

.`xpack.actions.preconfigured.<connector-id>.config.getIncidentResponseExternalTitleKey`
[%collapsible]
====
For a <<cases-webhook-action-type,{webhook-cm} connector>>, specifies a string from the response body of the get case method that corresponds to the external service title.

====

.`xpack.actions.preconfigured.<connector-id>.config.getIncidentUrl`
[%collapsible]
====
For a <<cases-webhook-action-type,{webhook-cm} connector>>, specifies a REST API URL string with an external service ID Mustache variable to get the case from the third-party system.


NOTE: If you are using the `xpack.actions.allowedHosts` setting, make sure the hostname in the URL is added to the allowed hosts. 
====

.`xpack.actions.preconfigured.<connector-id>.config.hasAuth`
[%collapsible]
====
For an <<email-action-type,email>>, <<webhook-action-type,webhook>>, or <<cases-webhook-action-type,{webhook-cm} connector>>, specifies whether a user and password are required inside the secrets configuration.

Default: `true` +
====

.`xpack.actions.preconfigured.<connector-id>.config.headers`
[%collapsible]
====
For a <<webhook-action-type,webhook>> or <<cases-webhook-action-type,{webhook-cm} connector>>, specifies a set of key-value pairs sent as headers with the request.

====

.`xpack.actions.preconfigured.<connector-id>.config.host`
[%collapsible]
====
For an <<email-action-type,email connector>>, specifies the host name of the service provider.

====

.`xpack.actions.preconfigured.<connector-id>.config.index`
[%collapsible]
====
For an <<index-action-type,index connector>>, specifies the Elasticsearch index.

====

.`xpack.actions.preconfigured.<connector-id>.config.isOAuth`
[%collapsible]
====
For a <<servicenow-action-type,{sn-itsm}>>, <<servicenow-sir-action-type,{sn-sir}>>, or <<servicenow-itom-action-type,{sn-itom} connector>>, specifies whether to use basic or OAuth authentication.

====

.`xpack.actions.preconfigured.<connector-id>.config.jwtKeyId`
[%collapsible]
====
For a <<servicenow-action-type,{sn-itsm}>>, <<servicenow-sir-action-type,{sn-sir}>>, or <<servicenow-itom-action-type,{sn-itom} connector>>, specifies the key ID assigned to the JWT verifier map of your OAuth application. It is required when `xpack.actions.preconfigured.<connector-id>.config.isOAuth` is `true`.

====

.`xpack.actions.preconfigured.<connector-id>.config.mappings`
[%collapsible]
====
For a <<swimlane-action-type,Swimlane connector>>, specifies field mappings.

====

.`xpack.actions.preconfigured.<connector-id>.config.mappings.alertIdConfig`
[%collapsible]
====
For a <<swimlane-action-type,Swimlane connector>>, field mapping for the alert identifier. You must provide `fieldtype`, `id`, `key`, and `name` values.

====

.`xpack.actions.preconfigured.<connector-id>.config.mappings.caseIdConfig`
[%collapsible]
====
For a <<swimlane-action-type,Swimlane connector>>, field mapping for the case identifier. You must provide `fieldtype`, `id`, `key`, and `name` values.

====

.`xpack.actions.preconfigured.<connector-id>.config.mappings.caseNameConfig`
[%collapsible]
====
For a <<swimlane-action-type,Swimlane connector>>, field mapping for the case name. You must provide `fieldtype`, `id`, `key`, and `name` values.

====

.`xpack.actions.preconfigured.<connector-id>.config.mappings.commentsConfig`
[%collapsible]
====
For a <<swimlane-action-type,Swimlane connector>>, field mapping for the case comments. You must provide `fieldtype`, `id`, `key`, and `name` values.

====

.`xpack.actions.preconfigured.<connector-id>.config.mappings.descriptionConfig`
[%collapsible]
====
For a <<swimlane-action-type,Swimlane connector>>, field mapping for the case description. You must provide `fieldtype`, `id`, `key`, and `name` values.

====

.`xpack.actions.preconfigured.<connector-id>.config.mappings.ruleNameConfig`
[%collapsible]
====
For a <<swimlane-action-type,Swimlane connector>>, field mapping for the rule name. You must provide `fieldtype`, `id`, `key`, and `name` values.

====

.`xpack.actions.preconfigured.<connector-id>.config.mappings.severityConfig`
[%collapsible]
====
For a <<swimlane-action-type,Swimlane connector>>, specifies a field mapping for the severity. You must provide `fieldtype`, `id`, `key`, and `name` values.

====

.`xpack.actions.preconfigured.<connector-id>.config.method`
[%collapsible]
====
For a <<webhook-action-type,webhook connector>>, specifies the HTTP request method, either `post` or `put`. Defaults to `post`.

====

.`xpack.actions.preconfigured.<connector-id>.config.orgId`
[%collapsible]
====
For an <<resilient-action-type,{ibm-r} connector>>, specifies the {ibm-r} organization identifier.

====

.`xpack.actions.preconfigured.<connector-id>.config.port`
[%collapsible]
====
For an <<email-action-type,email connector>>, specifies the port to connect to on the service provider.

====

.`xpack.actions.preconfigured.<connector-id>.config.projectKey`
[%collapsible]
====
For a <<jira-action-type,Jira connector>>, specifies the Jira project key.

====

.`xpack.actions.preconfigured.<connector-id>.config.secure`
[%collapsible]
====
For an <<email-action-type,email connector>>, specifies whether the connection will use TLS when connecting to the service provider. If not true, the connection will initially connect over TCP then attempt to switch to TLS via the SMTP STARTTLS command.

====

.`xpack.actions.preconfigured.<connector-id>.config.service`
[%collapsible]
====
For an <<email-action-type,email connector>>, specifies the name of the email service. For example, `elastic_cloud`, `exchange_server`, `gmail`, `other`, `outlook365`, or `ses`.

====

.`xpack.actions.preconfigured.<connector-id>.config.tenantId`
[%collapsible]
====
For an <<email-action-type,email connector>>, specifies a GUID format value that corresponds to a tenant ID, which is a part of OAuth 2.0 client credentials authentication.

====

.`xpack.actions.preconfigured.<connector-id>.config.updateIncidentJson`
[%collapsible]
====
For a <<cases-webhook-action-type,{webhook-cm} connector>>, specifies a stringified JSON payload with Mustache variables that is sent to the update case URL to update a case. Required variables are `case.title` and `case.description`.


NOTE: The JSON is validated after the Mustache variables have been placed when the REST method runs. You should manually ensure that the JSON is valid, disregarding the Mustache variables, so the later validation will pass.
====

.`xpack.actions.preconfigured.<connector-id>.config.updateIncidentMethod`
[%collapsible]
====
For a <<cases-webhook-action-type,{webhook-cm} connector>>, specifies the REST API HTTP request method to update the case in the third-party system.


Options:

* `post`
* `put`
* `patch`

Default: `put` +
====

.`xpack.actions.preconfigured.<connector-id>.config.updateIncidentUrl`
[%collapsible]
====
For a <<cases-webhook-action-type,{webhook-cm} connector>>, specifies the REST API URL to update the case by ID in the third-party system.


NOTE: If you are using the `xpack.actions.allowedHosts` setting, make sure the hostname in the URL is added to the allowed hosts.
====

.`xpack.actions.preconfigured.<connector-id>.config.url`
[%collapsible]
====
A configuration URL that varies by connector:

* For a <<d3security-action-type,D3 Security connector>>, specifies the D3 Security API request URL.

* For a <<tines-action-type,Tines connector>>, specifies the Tines tenant URL.

* For a <<webhook-action-type,webhook connector>>, specifies the web service request URL.


NOTE: If you are using the `xpack.actions.allowedHosts` setting, make sure this hostname is added to the allowed hosts.
====

.`xpack.actions.preconfigured.<connector-id>.config.userIdentifierValue`
[%collapsible]
====
For a <<servicenow-action-type,{sn-itsm}>>, <<servicenow-sir-action-type,{sn-sir}>>, or <<servicenow-itom-action-type,{sn-itom} connector>>, specifies the user identifier. It is required when required when `xpack.actions.preconfigured.<connector-id>.config.isOAuth` is `true`.

====

.`xpack.actions.preconfigured.<connector-id>.config.usesBasic`
[%collapsible]
====
For an <<xmatters-action-type,xMatters connector>>, specifies whether it uses HTTP basic authentication.

Default: `true` +
====

.`xpack.actions.preconfigured.<connector-id>.config.usesTableApi`
[%collapsible]
====
For a <<servicenow-action-type,{sn-itsm}>> or <<servicenow-sir-action-type,{sn-sir} connector>>, specifies whether the connector uses the Table API or the Import Set API. If set to `false`, the Elastic application should be installed in ServiceNow.

====

.`xpack.actions.preconfigured.<connector-id>.config.viewIncidentUrl`
[%collapsible]
====
For a <<cases-webhook-action-type,{webhook-cm} connector>>, specifies a URL string with either the external service ID or external service title Mustache variable to view a case in the external system.

====

.`xpack.actions.preconfigured.<connector-id>.config.webhookIntegrationUrl`
[%collapsible]
====
For a <<torq-action-type,Torq connector>>, specifies the endpoint URL of the Elastic Security integration in Torq.

====

.`xpack.actions.preconfigured.<connector-id>.name`
[%collapsible]
====
The name of the preconfigured connector.

====

.`xpack.actions.preconfigured.<connector-id>.secrets`
[%collapsible]
====
Sensitive configuration details, such as username, password, and keys, which are specific to the connector type.


TIP: Sensitive properties, such as passwords, should be stored in the <<creating-keystore,Kibana keystore>>.
====

.`xpack.actions.preconfigured.<connector-id>.secrets.accessKey`
[%collapsible]
====
For an <<bedrock-action-type,{bedrock} connector>>, specifies the AWS access key for authentication.

====

.`xpack.actions.preconfigured.<connector-id>.secrets.apikey`
[%collapsible]
====
An API key secret that varies by connector.

====

.`xpack.actions.preconfigured.<connector-id>.secrets.credentialsJson`
[%collapsible]
====
For an <<gemini-action-type,{gemini} connector>>, specifies the GCP service account credentials JSON file for authentication.

* For a <<openai-action-type,OpenAI connector>>, specifies the OpenAI or Azure OpenAI API key for authentication.

* For an <<opsgenie-action-type,{opsgenie} connector>>, specifies the {opsgenie} API authentication key for HTTP basic authentication.

====

.`xpack.actions.preconfigured.<connector-id>.secrets.apiKeyId`
[%collapsible]
====
For an <<resilient-action-type,{ibm-r} connector>>, specifies the authentication key ID for HTTP basic authentication.

====

.`xpack.actions.preconfigured.<connector-id>.secrets.apiKeySecret`
[%collapsible]
====
For an <<resilient-action-type,{ibm-r} connector>>, specifies the authentication key secret for HTTP basic authentication.

====

.`xpack.actions.preconfigured.<connector-id>.secrets.apiToken`
[%collapsible]
====
For a <<jira-action-type,Jira>> or <<swimlane-action-type,{swimlane} connector>>, specifies the API authentication token for HTTP basic authentication.

====

.`xpack.actions.preconfigured.<connector-id>.secrets.clientSecret`
[%collapsible]
====
A client secret that varies by connector:

* For an <<email-action-type,email connector>>, specifies the client secret that you generated for your app in the app registration portal. It is required when the email service is `exchange_server`, which uses OAuth 2.0 client credentials authentication.

* For a <<servicenow-action-type,{sn-itsm}>>, <<servicenow-sir-action-type,{sn-sir}>>, or <<servicenow-itom-action-type,{sn-itom} connector>>, specifies the client secret assigned to the OAuth application. It is required when `xpack.actions.preconfigured.<connector-id>.config.isOAuth` is `true`.


NOTE: The client secret must be URL-encoded.
====

.`xpack.actions.preconfigured.<connector-id>.secrets.email`
[%collapsible]
====
An email address that varies by connector:

* For a <<jira-action-type,Jira connector>>, specifies the account email for HTTP basic authentication.

* For a <<tines-action-type,Tines connector>>, specifies the email used to sign in to Tines.

====

.`xpack.actions.preconfigured.<connector-id>.secrets.password`
[%collapsible]
====
A password secret that varies by connector:

* For an <<email-action-type,email>>, <<webhook-action-type,webhook>>, or <<cases-webhook-action-type,{webhook-cm} connector>>, specifies a password that is required when `xpack.actions.preconfigured.<connector-id>.config.hasAuth` is `true`.

* For a <<servicenow-action-type,{sn-itsm}>>, <<servicenow-sir-action-type,{sn-sir}>>, or <<servicenow-itom-action-type,{sn-itom} connector>>, specifies a password that is required when `xpack.actions.preconfigured.<connector-id>.config.isOAuth` is `false`.

* For an <<xmatters-action-type,xMatters connector>>, specifies a password that is required when `xpack.actions.preconfigured.<connector-id>.config.usesBasic` is `true`.

====

.`xpack.actions.preconfigured.<connector-id>.secrets.privateKey`
[%collapsible]
====
For a <<servicenow-action-type,{sn-itsm}>>, <<servicenow-sir-action-type,{sn-sir}>>, or <<servicenow-itom-action-type,{sn-itom} connector>>, specifies the RSA private key. It is required when `xpack.actions.preconfigured.<connector-id>.config.isOAuth` is `true`.

====

.`xpack.actions.preconfigured.<connector-id>.secrets.privateKeyPassword`
[%collapsible]
====
For a <<servicenow-action-type,{sn-itsm}>>, <<servicenow-sir-action-type,{sn-sir}>>, or <<servicenow-itom-action-type,{sn-itom} connector>>, specifies the password for the RSA private key.

====

.`xpack.actions.preconfigured.<connector-id>.secrets.routingKey`
[%collapsible]
====
For a <<pagerduty-action-type,PagerDuty connector>>, specifies the 32 character PagerDuty Integration Key for an integration on a service, also referred to as the routing key.

====

.`xpack.actions.preconfigured.<connector-id>.secrets.secret`
[%collapsible]
====
For an <<bedrock-action-type,{bedrock} connector>>, specifies the AWS secret for authentication.

====

.`xpack.actions.preconfigured.<connector-id>.secrets.secretsUrl`
[%collapsible]
====
For an <<xmatters-action-type,xMatters connector>> with URL authentication, specifies the request URL for the Elastic Alerts trigger in xMatters with the API key included in the URL. It is used only when `xpack.actions.preconfigured.<connector-id>.config.usesBasic` is `false`.


NOTE: If you are using the `xpack.actions.allowedHosts` setting, make sure this hostname is added to the allowed hosts.
====

.`xpack.actions.preconfigured.<connector-id>.secrets.token`
[%collapsible]
====
A token secret that varies by connector:

* For a <<d3security-action-type,D3 Security conector>>, specifies the D3 Security token.

* For a <<slack-action-type,Slack connector>>, specifies the Slack bot user OAuth token.

* For a <<tines-action-type,Tines connector>>, specifies the Tines API token.

* For a <<torq-action-type,Torq connector>>, specifies the secret of the webhook authentication header.

====

.`xpack.actions.preconfigured.<connector-id>.secrets.user`
[%collapsible]
====
A user name secret that varies by connector:

* For an <<email-action-type,email>>, <<webhook-action-type,webhook>>, or <<cases-webhook-action-type,{webhook-cm} connector>>, specifies a user name that is required when `xpack.actions.preconfigured.<connector-id>.config.hasAuth` is `true`.

* For an <<xmatters-action-type,xMatters connector>>, specifies a user name that is required when `xpack.actions.preconfigured.<connector-id>.config.usesBasic` is `true`.

====

.`xpack.actions.preconfigured.<connector-id>.secrets.webhookUrl`
[%collapsible]
====
A URL that varies by connector:

* For a <<teams-action-type,Microsoft Teams>>, specifies the URL of the incoming webhook.

* For a <<slack-action-type,Slack connector>>, specifies the Slack webhook URL.


NOTE: If you are using the `xpack.actions.allowedHosts` setting, make sure the hostname is added to the allowed hosts.
====

.`xpack.actions.preconfigured.<connector-id>.secrets.username`
[%collapsible]
====
For a <<servicenow-action-type,{sn-itsm}>>, <<servicenow-sir-action-type,{sn-sir}>>, or <<servicenow-itom-action-type,{sn-itom} connector>>, specifies a user name that is required when `xpack.actions.preconfigured.<connector-id>.config.isOAuth` is `false`.

====


[float]
[[alert-settings]]
=== Alerting settings


.`xpack.alerting.maxEphemeralActionsPerAlert` {ess-icon}
[%collapsible]
====
**Deprecated:** Deprecated in version 8.8.0

Sets the number of actions that will run ephemerally. To use this, enable ephemeral tasks in task manager first with <<task-manager-settings,`xpack.task_manager.ephemeral_tasks.enabled`>>

====

.`xpack.alerting.cancelAlertsOnRuleTimeout` {ess-icon}
[%collapsible]
====
Specifies whether to skip writing alerts and scheduling actions if rule processing was cancelled due to a timeout. This setting can be overridden by individual rule types.

Default: `true` +
====

.`xpack.alerting.rules.maxScheduledPerMinute`
[%collapsible]
====
Specifies the maximum number of rules to run per minute.

Default: `10000` +
====

.`xpack.alerting.rules.minimumScheduleInterval.value` {ess-icon}
[%collapsible]
====
Specifies the minimum schedule interval for rules. This minimum is applied to all rules created or updated after you set this value. The time is formatted as a number and a time unit (`s`, `m`, `h`, or `d`). For example, `20m`, `24h`, `7d`. This duration cannot exceed `1d`.

Default: `1m` +
====

.`xpack.alerting.rules.minimumScheduleInterval.enforce` {ess-icon}
[%collapsible]
====
Specifies the behavior when a new or changed rule has a schedule interval less than the value defined in `xpack.alerting.rules.minimumScheduleInterval.value`. If `false`, rules with schedules less than the interval will be created but warnings will be logged. If `true`, rules with schedules less than the interval cannot be created.

Default: `false` +
====

.`xpack.alerting.rules.run.actions.max` {ess-icon}
[%collapsible]
====
Specifies the maximum number of actions that a rule can generate each time detection checks run.

====

.`xpack.alerting.rules.run.alerts.max` {ess-icon}
[%collapsible]
====
Specifies the maximum number of alerts that a rule can generate each time detection checks run.


WARNING: The exact number of alerts your cluster can safely handle depends on your cluster configuration and workload, however setting a value higher than the default (`1000`) is not recommended or supported. Doing so could strain system resources and lead to performance issues, delays in alert processing, and potential disruptions during high alert activity periods.
Default: `1000` +
====

.`xpack.alerting.rules.run.timeout` {ess-icon}
[%collapsible]
====
Specifies the default timeout for tasks associated with all types of rules. The time is formatted as a number and a time unit (`ms`, `s`, `m`, `h`, `d`, `w`, `M`, or `Y`). For example, `20m`, `24h`, `7d`, `1w`. Default: `5m`.

====

.`xpack.alerting.rules.run.ruleTypeOverrides` {ess-icon}
[%collapsible]
====
Overrides the configs under `xpack.alerting.rules.run` for the rule type with the given ID. List the rule identifier and its settings in an array of objects.



include::../embeds/example-xpack-alerting-rules-run-ruletypeoverrides.asciidoc[]
====

.`xpack.alerting.rules.run.actions.connectorTypeOverrides` {ess-icon}
[%collapsible]
====
Overrides the configs under `xpack.alerting.rules.run.actions` for the connector type with the given ID. List the connector type identifier and its settings in an array of objects.



include::../embeds/example-xpack-alerting-rules-run-actions-connectortypeoverrides.asciidoc[]
====


