/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: AlertZero hunt coordinator route
 *   version: 1
 */

import { z, lazySchema } from '@kbn/zod/v4';

import { HuntIoc, HuntTechnology, HuntForThreatResult } from '../components/hunt.gen';

export const HuntCoordinatorStatus = lazySchema(() =>
  z.enum(['blocked', 'tier1_only', 'tier1_and_tier2', 'tier2_only_skipped'])
);
export type HuntCoordinatorStatus = z.infer<typeof HuntCoordinatorStatus>;
export type HuntCoordinatorStatusEnum = typeof HuntCoordinatorStatus.enum;
export const HuntCoordinatorStatusEnum = HuntCoordinatorStatus.enum;

export const HuntCoordinatorRequestBody = lazySchema(() =>
  z
    .object({
      report_id: z.string().min(1).max(512).optional(),
      /**
       * Run id supplied by the Worker fan-out so every child of one sweep shares it, which is what the packaging barrier and the conclusion dedupe key off. The route mints one only when the caller has no sweep to tie the run to.
       */
      run_id: z
        .string()
        .min(1)
        .max(128)
        .optional()
        .describe(
          'Run id supplied by the Worker fan-out so every child of one sweep shares it, which is what the packaging barrier and the conclusion dedupe key off. The route mints one only when the caller has no sweep to tie the run to.'
        ),
      /**
       * One of the HuntTechnology values to pin the hunt to that technology's index scope. Omit it, or send null or an empty string (a workflow renders an unset input as ""), and the coordinator resolves every known technology and hunts the ones whose required indices exist in the space. Any other value is a 400. Kept a plain string because a workflow caller cannot omit the key.
       */
      technology: z
        .string()
        .max(64)
        .nullable()
        .optional()
        .describe(
          'One of the HuntTechnology values to pin the hunt to that technology\'s index scope. Omit it, or send null or an empty string (a workflow renders an unset input as ""), and the coordinator resolves every known technology and hunts the ones whose required indices exist in the space. Any other value is a 400. Kept a plain string because a workflow caller cannot omit the key.'
        ),
      text: z.string().max(200000).optional(),
      iocs: z.array(HuntIoc).max(100).optional(),
      techniques: z.array(z.string().min(1).max(32)).max(100).optional(),
      time_range: z
        .object({
          from: z.string().min(1).max(64),
          to: z.string().min(1).max(64),
        })
        .optional(),
      size: z.number().int().min(1).max(100).optional(),
      max_assets: z.number().int().min(1).max(200).optional(),
      llm_confidence_threshold: z.number().min(0).max(1).optional(),
      tier2_when: z.enum(['on_hits', 'always', 'never']).optional(),
      max_tier2_sample_events: z.number().int().min(1).max(50).optional(),
      trigger: z.enum(['manual', 'scheduled']),
    })
    .strict()
);
export type HuntCoordinatorRequestBody = z.infer<typeof HuntCoordinatorRequestBody>;
export type HuntCoordinatorRequestBodyInput = z.input<typeof HuntCoordinatorRequestBody>;

export const HuntCoordinatorResponse = lazySchema(() =>
  z.object({
    status: HuntCoordinatorStatus,
    report_id: z.string().optional(),
    runId: z.string(),
    /**
     * Technologies whose indices the hunt ran against. Empty when the scope was blocked.
     */
    technologies: z
      .array(HuntTechnology)
      .describe(
        'Technologies whose indices the hunt ran against. Empty when the scope was blocked.'
      ),
    tier1: HuntForThreatResult.merge(
      z.object({
        tier: z.number().int(),
      })
    ),
    tier2: z
      .object({
        status: z.enum(['no_behaviors_found', 'no_behaviors_validated', 'behaviors_proposed']),
        report_id: z.string().optional(),
        behaviors: z.array(
          z.object({
            technique_id: z.string(),
            evidence_quote: z.string(),
            llm_confidence: z.number(),
            confidence: z.number(),
            technique_name: z.string(),
            reference: z.string(),
            tactic_ids: z.array(z.string()),
            parent_technique_id: z.string().optional(),
            proposed_esql_rule: z.string(),
            rule_name: z.string(),
            severity: z.enum(['critical', 'high', 'medium', 'low']),
            risk_score: z.number(),
            execution: z
              .object({
                /**
                 * True when dry-run passed and an execute call was attempted.
                 */
                executed: z
                  .boolean()
                  .describe('True when dry-run passed and an execute call was attempted.'),
                /**
                 * Rows remaining after the required-index filter.
                 */
                row_count: z
                  .number()
                  .int()
                  .min(0)
                  .describe('Rows remaining after the required-index filter.'),
                /**
                 * True when at least one required-index row was returned.
                 */
                hit: z
                  .boolean()
                  .describe('True when at least one required-index row was returned.'),
              })
              .optional(),
            /**
             * Distinct host.name values from required-index rows, capped at 20.
             */
            affected_hosts: z
              .array(z.string())
              .optional()
              .describe('Distinct host.name values from required-index rows, capped at 20.'),
            /**
             * Distinct user.name values from required-index rows, capped at 20.
             */
            affected_users: z
              .array(z.string())
              .optional()
              .describe('Distinct user.name values from required-index rows, capped at 20.'),
            /**
             * True when more than 20 distinct hosts were seen.
             */
            affected_hosts_truncated: z
              .boolean()
              .optional()
              .describe('True when more than 20 distinct hosts were seen.'),
            /**
             * True when more than 20 distinct users were seen.
             */
            affected_users_truncated: z
              .boolean()
              .optional()
              .describe('True when more than 20 distinct users were seen.'),
            /**
             * Required-index execute rows as Discover refs for the SSE mapper (`events[]` / `alerts[]`).
             */
            hit_refs: z
              .array(
                z.object({
                  event_id: z.string().max(512),
                  source_index: z.string().max(512),
                  timestamp: z.string().max(64).optional(),
                })
              )
              .max(50)
              .optional()
              .describe(
                'Required-index execute rows as Discover refs for the SSE mapper (`events[]` / `alerts[]`).'
              ),
          })
        ),
        indexed_behaviors: z.array(
          z.object({
            id: z.string(),
            technique_id: z.string(),
            description: z.string(),
            telemetry_targets: z.array(z.string()).optional(),
            llm_confidence: z.number(),
            confidence: z.number(),
          })
        ),
        dropped_unknown_ids: z.array(z.string()).optional(),
        message: z.string().optional(),
        next_step: z.string(),
        /**
         * True when any behavior's execute path found at least one row in a required index. Independent of Tier 1.
         */
        hasHit: z
          .boolean()
          .describe(
            "True when any behavior's execute path found at least one row in a required index. Independent of Tier 1."
          ),
        tier: z.number().int().optional(),
      })
      .nullable()
      .optional(),
    tier2_skipped_reason: z.string().optional(),
    message: z.string(),
    next_step: z.string(),
    /**
     * True when Tier 1 confirmed a required-index hit or any Tier 2 behavior executed with a required-index hit. Callers that gate SSE emit or packaging on the hit bar must read this field, not tier1.hasConfirmedHit alone.
     */
    hasConfirmedHit: z
      .boolean()
      .describe(
        'True when Tier 1 confirmed a required-index hit or any Tier 2 behavior executed with a required-index hit. Callers that gate SSE emit or packaging on the hit bar must read this field, not tier1.hasConfirmedHit alone.'
      ),
    /**
     * True when the run completed without hard errors. The calling workflow checks this before writing hunt evidence, so a failed run writes nothing.
     */
    completedSuccessfully: z
      .boolean()
      .describe(
        'True when the run completed without hard errors. The calling workflow checks this before writing hunt evidence, so a failed run writes nothing.'
      ),
  })
);
export type HuntCoordinatorResponse = z.infer<typeof HuntCoordinatorResponse>;
