import type { Agent } from '../types';
export declare const AGENT_UPGRADE_COOLDOWN_IN_MIN = 10;
export declare const AGENT_UPGARDE_DETAILS_SUPPORTED_VERSION = "8.12.0";
export declare const VERSION_MISSING_ERROR = "agent version is missing.";
export declare const UNENROLLED_ERROR = "agent has been unenrolled.";
export declare const ONGOING_UNEROLLMENT_ERROR = "agent is being unenrolled.";
export declare const NOT_UPGRADEABLE_ERROR = "agent cannot be upgraded through Fleet. It may be running in a container or it is not installed as a service.";
export declare const ALREADY_UPGRADED_ERROR = "agent is already being upgraded.";
export declare const INVALID_VERSION_ERROR = "agent version is not valid.";
export declare const SELECTED_VERSION_ERROR = "the selected version is not valid.";
export declare const RUNNING_SELECTED_VERSION_ERROR = "agent is already running on the selected version.";
export declare const DOWNGRADE_NOT_ALLOWED_ERROR = "agent does not support downgrades.";
export declare const LATEST_VERSION_NOT_VALID_ERROR = "latest version is not valid.";
export declare const AGENT_ALREADY_ON_LATEST_ERROR = "agent is already running on the latest available version.";
export declare const AGENT_ON_GREATER_VERSION_ERROR = "agent is running on a version greater than the latest available version.";
export declare function isAgentUpgradeAvailable(agent: Agent, latestAgentVersion?: string): boolean;
export declare function isAgentUpgradeable(agent: Agent): boolean;
export declare function isAgentUpgradeableToVersion(agent: Agent, versionToUpgrade?: string): boolean;
export declare const isAgentVersionLessThanLatest: (agentVersion: string, latestAgentVersion: string) => boolean;
export declare const getNotUpgradeableMessage: (agent: Agent, latestAgentVersion?: string, versionToUpgrade?: string) => string | undefined;
export declare function getRecentUpgradeInfoForAgent(agent: Agent): {
    hasBeenUpgradedRecently: boolean;
    timeToWaitMs: number;
    elapsedMinsSinceUpgrade: number;
    timeToWaitMins: number;
};
export declare function isAgentInWatchingState(agent: Agent): boolean;
export declare function isAgentUpgrading(agent: Agent): boolean | "" | null | undefined;
export declare const differsOnlyInPatch: (versionA: string, versionB: string, allowEqualPatch?: boolean) => boolean;
