/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Bulk Prompts Actions API endpoint
 *   version: 2023-10-31
 */

import type {
  BulkActionBase,
  NonEmptyString,
  NonEmptyTimestamp,
  User,
  BulkCrudActionSummary,
} from '../common_attributes.gen';

/**
 * Reason why a prompt was skipped during the bulk action.
 */
export type PromptsBulkActionSkipReason = 'PROMPT_FIELD_NOT_MODIFIED';

export interface PromptsBulkActionSkipResult {
  /**
   * The ID of the prompt that was skipped.
   */
  id: string;
  /**
   * The name of the prompt that was skipped.
   */
  name?: string;
  /**
   * The reason for skipping the prompt.
   */
  skip_reason: PromptsBulkActionSkipReason;
}

export interface PromptDetailsInError {
  /**
   * The ID of the prompt that encountered an error.
   */
  id: string;
  /**
   * The name of the prompt that encountered an error.
   */
  name?: string;
}

/**
 * Type of the prompt (either system or quick).
 */
export type PromptType = 'system' | 'quick';
export interface PromptTypeEnum {
  readonly system: 'system';
  readonly quick: 'quick';
}

export interface NormalizedPromptError {
  /**
   * A message describing the error encountered.
   */
  message: string;
  /**
   * The HTTP status code associated with the error.
   */
  status_code: number;
  /**
   * A code representing the error type.
   */
  err_code?: string;
  /**
   * List of prompts that encountered errors.
   */
  prompts: PromptDetailsInError[];
}

export interface PromptResponse {
  id: NonEmptyString;
  timestamp?: NonEmptyTimestamp;
  /**
   * The name of the prompt.
   */
  name: string;
  /**
   * The type of the prompt.
   */
  promptType: PromptType;
  /**
   * The content of the prompt.
   */
  content: string;
  /**
   * Categories associated with the prompt.
   */
  categories?: string[];
  /**
   * The color associated with the prompt.
   */
  color?: string;
  /**
   * Whether this prompt is the default for new conversations.
   */
  isNewConversationDefault?: boolean;
  /**
   * Whether this prompt is the default.
   */
  isDefault?: boolean;
  /**
   * The consumer that the prompt is associated with.
   */
  consumer?: string;
  /**
   * The timestamp of when the prompt was last updated.
   */
  updatedAt?: string;
  /**
   * The user who last updated the prompt.
   */
  updatedBy?: string;
  /**
   * The timestamp of when the prompt was created.
   */
  createdAt?: string;
  /**
   * The user who created the prompt.
   */
  createdBy?: string;
  /**
   * List of users associated with the prompt.
   */
  users?: User[];
  /**
   * Kibana space where the prompt is located.
   */
  namespace?: string;
}

export interface PromptsBulkCrudActionResults {
  /**
   * List of prompts that were updated.
   */
  updated: PromptResponse[];
  /**
   * List of prompts that were created.
   */
  created: PromptResponse[];
  /**
   * List of IDs of prompts that were deleted.
   */
  deleted: string[];
  /**
   * List of prompts that were skipped.
   */
  skipped: PromptsBulkActionSkipResult[];
}

export interface PromptsBulkCrudActionResponse {
  /**
   * Indicates if the bulk action was successful.
   */
  success?: boolean;
  /**
   * The HTTP status code of the response.
   */
  status_code?: number;
  /**
   * A message describing the result of the bulk action.
   */
  message?: string;
  /**
   * The number of prompts processed in the bulk action.
   */
  prompts_count?: number;
  attributes: {
    results: PromptsBulkCrudActionResults;
    summary: BulkCrudActionSummary;
    errors?: NormalizedPromptError[];
  };
}

export interface PromptCreateProps {
  /**
   * The name of the prompt.
   */
  name: string;
  /**
   * The type of the prompt.
   */
  promptType: PromptType;
  /**
   * The content of the prompt.
   */
  content: string;
  /**
   * The color associated with the prompt.
   */
  color?: string;
  /**
   * List of categories for the prompt.
   */
  categories?: string[];
  /**
   * Whether this prompt should be the default for new conversations.
   */
  isNewConversationDefault?: boolean;
  /**
   * Whether this prompt should be the default.
   */
  isDefault?: boolean;
  /**
   * The consumer associated with the prompt.
   */
  consumer?: string;
}

export interface PromptUpdateProps {
  /**
   * The ID of the prompt to update.
   */
  id: string;
  /**
   * The updated content for the prompt.
   */
  content?: string;
  /**
   * The updated color associated with the prompt.
   */
  color?: string;
  /**
   * The updated categories for the prompt.
   */
  categories?: string[];
  /**
   * Whether the prompt should be the default for new conversations.
   */
  isNewConversationDefault?: boolean;
  /**
   * Whether this prompt should be the default.
   */
  isDefault?: boolean;
  /**
   * The updated consumer for the prompt.
   */
  consumer?: string;
}

export interface PerformPromptsBulkActionRequestBody {
  /**
   * Criteria for deleting prompts in bulk.
   */
  delete?: BulkActionBase;
  /**
   * List of prompts to be created.
   */
  create?: PromptCreateProps[];
  /**
   * List of prompts to be updated.
   */
  update?: PromptUpdateProps[];
}
export interface PerformPromptsBulkActionRequestBodyInput {
  /**
   * Criteria for deleting prompts in bulk.
   */
  delete?: BulkActionBase;
  /**
   * List of prompts to be created.
   */
  create?: PromptCreateProps[];
  /**
   * List of prompts to be updated.
   */
  update?: PromptUpdateProps[];
}

export type PerformPromptsBulkActionResponse = PromptsBulkCrudActionResponse;
