import type { QueryClientConfig } from '@tanstack/react-query';
import { QueryClient as TanstackQueryClient } from '@tanstack/query-core';
declare class QueryClient extends TanstackQueryClient {
    constructor(config?: QueryClientConfig);
}
export { TanstackQueryClient, QueryClient, };
export type { CancelOptions, ContextOptions, DefaultedInfiniteQueryObserverOptions, DefaultedQueryObserverOptions, DefaultOptions, DefinedQueryObserverResult, DefinedUseBaseQueryResult, DefinedUseQueryResult, DehydratedState, DehydrateOptions, FetchInfiniteQueryOptions, FetchNextPageOptions, FetchPreviousPageOptions, FetchQueryOptions, FetchStatus, GetNextPageParamFunction, GetPreviousPageParamFunction, HydrateOptions, HydrateProps, InfiniteData, InfiniteQueryObserverBaseResult, InfiniteQueryObserverLoadingErrorResult, InfiniteQueryObserverLoadingResult, InfiniteQueryObserverOptions, InfiniteQueryObserverRefetchErrorResult, InfiniteQueryObserverResult, InfiniteQueryObserverSuccessResult, InitialDataFunction, InvalidateOptions, InvalidateQueryFilters, Logger, MutateFunction, MutateOptions, Mutation, // class, but exported as type-only
MutationFilters, MutationFunction, MutationKey, MutationMeta, MutationObserverBaseResult, MutationObserverErrorResult, MutationObserverIdleResult, MutationObserverLoadingResult, MutationObserverOptions, MutationObserverResult, MutationObserverSuccessResult, MutationOptions, MutationStatus, NetworkMode, NotifyEvent, NotifyEventType, PlaceholderDataFunction, QueriesOptions, QueriesResults, Query, // class, but exported as type-only
QueryClientConfig, QueryClientProviderProps, QueryErrorResetBoundaryProps, QueryFilters, QueryFunction, QueryFunctionContext, QueryKey, QueryKeyHashFunction, QueryMeta, QueryObserverBaseResult, QueryObserverLoadingErrorResult, QueryObserverLoadingResult, QueryObserverOptions, QueryObserverRefetchErrorResult, QueryObserverResult, QueryObserverSuccessResult, QueryOptions, QueryState, QueryStatus, RefetchOptions, RefetchPageFilters, RefetchQueryFilters, ResetOptions, ResetQueryFilters, ResultOptions, SetDataOptions, ShouldDehydrateMutationFunction, ShouldDehydrateQueryFunction, Updater, UseBaseMutationResult, UseBaseQueryOptions, UseBaseQueryResult, UseErrorBoundary, UseInfiniteQueryOptions, UseInfiniteQueryResult, UseMutateAsyncFunction, UseMutateFunction, UseMutationOptions, UseMutationResult, UseQueryOptions, UseQueryResult, WithRequired, } from '@tanstack/react-query';
export { CancelledError, defaultContext, defaultShouldDehydrateMutation, defaultShouldDehydrateQuery, dehydrate, focusManager, hashQueryKey, hydrate, Hydrate, isCancelledError, isError, isServer, InfiniteQueryObserver, IsRestoringProvider, matchQuery, MutationCache, MutationObserver, notifyManager, onlineManager, parseFilterArgs, parseMutationArgs, parseMutationFilterArgs, parseQueryArgs, QueriesObserver, QueryCache, QueryClientProvider, QueryErrorResetBoundary, QueryObserver, replaceEqualDeep, useHydrate, useInfiniteQuery, useIsFetching, useIsMutating, useIsRestoring, useMutation, useQueries, useQuery, useQueryClient, useQueryErrorResetBoundary, } from '@tanstack/react-query';
