---
# This file is used to generate "Metrics settings in Kibana" page in the product docs
# For the schema and an example refer to the automated settings reference: 
# https://github.com/elastic/docs-builder/blob/main/docs/syntax/automated_settings.md

product: Kibana
collection: Metrics settings in Kibana
id: infrastructure-ui-settings-kb
page_description: |
  You do not need to configure any settings to use the Metrics app in Kibana. It is enabled by default.

groups:
  - group: General metrics settings
    id: general-infra-ui-settings-kb
    settings:

      - setting: xpack.infra.sources.default.fields.message
        description: |
          Fields used to display messages in the Logs app.
        datatype: string
        default: "['message', '@message']"
        applies_to:
          stack: deprecated 8.18
          self: ga
          ech: unavailable
        deprecation_details: "Deprecated in 8.18."

      - setting: xpack.infra.alerting.inventory_threshold.group_by_page_size
        description: |
          Controls the size of the composite aggregations used by the Inventory Threshold to retrieve all the hosts.
        datatype: int
        default: 5000
        applies_to:
          stack: ga
          self: ga
          ech: unavailable

      - setting: xpack.infra.alerting.metric_threshold.group_by_page_size
        description: |
          Controls the size of the composite aggregations used by the Metric Threshold group by feature.
        datatype: int
        default: 10000
        applies_to:
          stack: ga
          self: ga
          ech: unavailable
