/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/** SPL keywords that we want to track the frequency of */
export const SPL_KEYWORDS: string[] = [
  'join',
  'multisearch',
  'abstract',
  'accum',
  'addinfo',
  'addtotals',
  'analyzefields',
  'anomalies',
  'anomalousvalue',
  'anomalydetection',
  'arules',
  'associate',
  'autoregress',
  'bucketdir',
  'cluster',
  'cofilter',
  'collect',
  'concurrency',
  'contingency',
  'correlate',
  'datamodel',
  'dbinspect',
  'delta',
  'diff',
  'erex',
  'eventcount',
  'exact',
  'fieldsummary',
  'filldown',
  'fillnull',
  'findtypes',
  'folderize',
  'foreach',
  'format',
  'gentimes',
  'geom',
  'geomfilter',
  'geostats',
  'highlight',
  'history',
  'iconify',
  'inputcsv',
  'iplocation',
  'isbool',
  'isint',
  'isstr',
  'kmeans',
  'kvform',
  'localize',
  'localop',
  'makecontinuous',
  'map',
  'mcollect',
  'metadata',
  'metasearch',
  'meventcollect',
  'mode',
  'mpreview',
  'msearch',
  'mvcombine',
  'mvfilter',
  'nullif',
  'outlier',
  'outputcsv',
  'outputlookup',
  'outputtext',
  'overlap',
  'pivot',
  'predict',
  'random',
  'rare',
  'redistribute',
  'require',
  'rest',
  'return',
  'reverse',
  'rtorder',
  'savedsearch',
  'script',
  'scrub',
  'searchtxn',
  'selfjoin',
  'sendemail',
  'set',
  'sichart',
  'sirare',
  'sistats',
  'sitimechart',
  'sitop',
  'stdevp',
  'streamstats',
  'sumsq',
  'tags',
  'tojson',
  'top',
  'transaction',
  'transpose',
  'trendline',
  'tscollect',
  'tstats',
  'typeahead',
  'typelearner',
  'typeof',
  'typer',
  'uniq',
  'untable',
  'urldecode',
  'validate',
  'walklex',
  'x11',
  'xmlkv',
  'xmlunescape',
  'xpath',
  'xyseries',
  'sendalert',
  'expand',
  'flatten',
  'into',
  'through',
  'thru',
  'select',
  'anomalousvalue',
];

export const maskSplQueryStrings = (query: string): string => {
  const maskedDoubleQuotes = query.replace(/"([^"\\]|\\.)*"/g, '"?"');
  return maskedDoubleQuotes.replace(/'([^'\\]|\\.)*'/g, "'?'");
};

export const getSPLQueryKeywords = (
  query: string,
  splKeywords: string[] = SPL_KEYWORDS
): string[] => {
  const maskedQuery = maskSplQueryStrings(query).toLowerCase();
  const pattern = new RegExp(`\\b(${splKeywords.join('|')})\\b`, 'g');
  const matches = maskedQuery.match(pattern);
  return matches ? [...new Set(matches)] : [];
};
