#!/usr/bin/env bash

set -euo pipefail

gcloud auth configure-docker us-central1-docker.pkg.dev,gcr.io,us.gcr.io --quiet # TODO remove

CI_STATS_BUILD_ID="$(buildkite-agent meta-data get ci_stats_build_id || echo '')"
export CI_STATS_BUILD_ID

if [[ "$CI_STATS_BUILD_ID" ]]; then
  echo "CI Stats Build ID: $CI_STATS_BUILD_ID"

  CI_STATS_TOKEN="$(vault read -field=api_token secret/kibana-issues/dev/kibana_ci_stats)"
  export CI_STATS_TOKEN

  CI_STATS_HOST="$(vault read -field=api_host secret/kibana-issues/dev/kibana_ci_stats)"
  export CI_STATS_HOST

  KIBANA_CI_STATS_CONFIG=$(jq -n \
    --arg buildId "$CI_STATS_BUILD_ID" \
    --arg apiUrl "https://$CI_STATS_HOST" \
    --arg apiToken "$CI_STATS_TOKEN" \
    '{buildId: $buildId, apiUrl: $apiUrl, apiToken: $apiToken}' \
  )
  export KIBANA_CI_STATS_CONFIG
fi

GITHUB_TOKEN=$(vault read -field=github_token secret/kibana-issues/dev/kibanamachine)
export GITHUB_TOKEN

if [[ "${SKIP_CI_SETUP:-}" != "true" ]]; then
  if [[ -d .buildkite/scripts && "${BUILDKITE_COMMAND:-}" != "buildkite-agent pipeline upload"* ]]; then
    source .buildkite/scripts/setup.sh
  fi
fi
