#!/usr/bin/env bash

if [ "$BUILDKITE_AGENT_META_DATA_AGENT_MANAGER" = "kibana" ]; then
  source .buildkite/scripts/lifecycle/pre_command.sh
else
  echo "Pipeline file triggered from outside the kibana executors, skipping pre_command"
fi
