Vagrant.configure("2") do |config|
  config.vm.synced_folder '../../target/', '/packages', SharedFoldersEnableSymlinksCreate: false
  config.vm.boot_timeout = 600
  config.vm.define "deb" do |deb|
    deb.vm.provider :virtualbox do |vb|
      vb.memory = 4096
      vb.cpus = 2
    end
    deb.vm.box = 'ubuntu/jammy64'
    deb.vm.provision "ansible" do |ansible|
      ansible.playbook = "deb.yml"
    end
    deb.vm.network "private_network", ip: "192.168.56.5"
  end

  config.vm.define "rpm" do |rpm|
    rpm.vm.provider :virtualbox do |vb|
      vb.memory = 4096
      vb.cpus = 2
    end
    rpm.vm.box = 'almalinux/9'
    rpm.vm.provision "ansible" do |ansible|
      ansible.playbook = "rpm.yml"
    end
    rpm.vm.network "private_network", ip: "192.168.56.6"
  end

  config.vm.define "docker" do |docker|
    docker.vm.provider :virtualbox do |vb|
      vb.memory = 4096
      vb.cpus = 2
    end
    docker.vm.box = 'ubuntu/jammy64'
    docker.vm.provision "ansible" do |ansible|
      ansible.playbook = "docker.yml"
    end
    docker.vm.network "private_network", ip: "192.168.56.7"
  end

  config.vm.define "fips" do |fips|
    fips.vm.provider :virtualbox do |vb|
      vb.memory = 4096
      vb.cpus = 2
    end
    fips.vm.box = 'generic/rhel9'
    fips.vm.provision "ansible" do |ansible|
      ansible.playbook = "fips.yml"
    end
    fips.vm.network "private_network", ip: "192.168.56.8"
  end
end
