import type { Optional } from 'utility-types';
import type { TypeOf } from '@kbn/config-schema';
import type { lensCMGetResultSchema } from '../../../../content_management';
import type { lensCreateRequestBodySchema, lensCreateResponseBodySchema, lensDeleteRequestParamsSchema, lensGetRequestParamsSchema, lensGetResponseBodySchema, lensSearchRequestQuerySchema, lensSearchResponseBodySchema, lensUpdateRequestBodySchema, lensUpdateRequestParamsSchema, lensUpdateRequestQuerySchema, lensUpdateResponseBodySchema } from './schema';
import type { lensItemMetaSchema, lensResponseItemSchema } from './schema/common';
export type LensItemMeta = TypeOf<typeof lensItemMetaSchema>;
export type LensResponseItem = TypeOf<typeof lensResponseItemSchema>;
export type CMItemResultMeta = TypeOf<typeof lensCMGetResultSchema>['meta'];
export type LensCreateRequestBody = TypeOf<typeof lensCreateRequestBodySchema>;
export type LensCreateResponseBody = TypeOf<typeof lensCreateResponseBodySchema>;
export type LensUpdateRequestParams = TypeOf<typeof lensUpdateRequestParamsSchema>;
export type LensUpdateRequestQuery = TypeOf<typeof lensUpdateRequestQuerySchema>;
export type LensUpdateRequestBody = TypeOf<typeof lensUpdateRequestBodySchema>;
export type LensUpdateResponseBody = TypeOf<typeof lensUpdateResponseBodySchema>;
export type LensGetRequestParams = TypeOf<typeof lensGetRequestParamsSchema>;
export type LensGetResponseBody = TypeOf<typeof lensGetResponseBodySchema>;
export type LensSearchRequestQuery = Optional<TypeOf<typeof lensSearchRequestQuerySchema>, 'page' | 'perPage'>;
export type LensSearchResponseBody = TypeOf<typeof lensSearchResponseBodySchema>;
export type LensDeleteRequestParams = TypeOf<typeof lensDeleteRequestParamsSchema>;
