export declare const OBSERVABILITY_AI_ASSISTANT_FEATURE_ID = "observabilityAIAssistant";
export declare const OBSERVABILITY_AI_ASSISTANT_INFERENCE_PARENT_FEATURE_ID = "observability_ai_assistant_inference_parent_feature";
export declare const OBSERVABILITY_AI_ASSISTANT_SUBFEATURE_ID = "observability_ai_assistant_inference_subfeature";
