[[upgrade-standard]]
=== Standard upgrade

NOTE: 7.17 includes an https://www.elastic.co/guide/en/kibana/7.17/upgrade-assistant.html[Upgrade Assistant]
to help you prepare for your upgrade to 8.0. To access the assistant, go to *Stack Management > Upgrade Assistant*.

[IMPORTANT]
===========================================
If you've saved and/or exported objects in {kib} that rely on the
<<search,Elasticsearch Query DSL>>, make sure to check the {es}
{ref}/breaking-changes.html[breaking changes] documentation and take the
necessary remediation steps as per those instructions.
===========================================

[float]
==== Upgrading multiple {kib} instances

NOTE: Kibana does not support rolling upgrades. If you're running multiple {kib} instances, all instances should be stopped before upgrading.

Different versions of {kib} running against the same {es} index, such as during a rolling upgrade, can cause data loss. This is because older instances will continue to write saved objects in a different format than the newer instances. To prevent this from happening ensure that all old {kib} instances are shutdown before starting up instances on a newer version.

[float]
==== Upgrade using a `deb` or `rpm` package

. Stop the existing {kib} process using the appropriate command for your
  system. If you have multiple {kib} instances connecting to the same {es}
  cluster ensure that all instances are stopped before proceeding to the next
  step to avoid data loss.
. Use `rpm` or `dpkg` to install the new package. All files should be placed in
  their proper locations and config files should not be overwritten.
+

Make sure you remove or update any configurations
that are indicated in the {kibana-ref-all}/8.0/release-notes-8.0.0.html#breaking-changes-8.0.0[8.0.0 breaking changes]
otherwise {kib} will fail to start.
--
. Upgrade any plugins by removing the existing plugin and reinstalling the
  appropriate version using the `kibana-plugin` script. Check out the
  <<kibana-plugins,plugins>> documentation for more information.
. Start the new {kib} process using the appropriate command for your system.

[float]
==== Upgrade using a `zip` or `tar.gz` archive

. Extract the `zip` or `tar.gz` archive to a new directory to be sure that you
  don't overwrite the `config` or `data` directories. +
+
--
IMPORTANT: If you use {monitor-features}, you must re-use the data directory when you upgrade {kib}. Otherwise, the {kib} instance is assigned a new persistent UUID
and becomes a new instance in the monitoring data.

--
. Copy the files from the `config` directory from your old installation to your
  new installation. Make sure you remove or update any configurations that are
  indicated in the {kibana-ref-all}/8.0/release-notes-8.0.0.html#breaking-changes-8.0.0[8.0.0 breaking changes]
  otherwise {kib} will fail to start.
. Copy the files from the `data` directory from your old installation to your
  new installation.
. Install the appropriate versions of all your plugins for your new
  installation using the `kibana-plugin` script. Check out the
  <<kibana-plugins,plugins>> documentation for more information.
. Stop the old {kib} process. If you have multiple {kib} instances connecting
  to the same {es} cluster ensure that all instances are stopped before
  proceeding to the next step to avoid data loss.
. Start the new {kib} process.
