[[upgrade-standard-reindex]]
=== Standard Upgrade with Reindex

You must perform a reindex in Elasticsearch whenever you're upgrading Kibana
that has an existing `.kibana` index created prior to Elasticsearch 2.0.

This is the case if you're upgrading directly from Kibana 4.1 or 4.0 as well as
when your existing install of Kibana 4.2+ was previously upgraded from 4.1 or
4.0.

Reindexing is the process of creating a new index with updated syntax and
mappings directly from an existing index. While it is possible to do this
manually, we recommend using the Elasticsearch Migration Plugin as described
in the Elasticsearch
{ref}/reindex-upgrade.html#reindex-upgrade[Reindex to upgrade] guide.

NOTE: The Elasticsearch Migration Plugin creates a versioned `.kibana` index
as well as an {ref}/indices-aliases.html[index alias] that points to it.
Kibana 5.0 supports this index alias, but if you want to run Kibana 4.x while
this Elastic stack upgrade is underway, you'll need to configure your Kibana
4.x install to point to the versioned index using the `kibana.index`
configuration in your `kibana.yml` file.

Once your reindex is complete, you can follow the
<<upgrade-standard, Standard Upgrade>> instructions.
