[[upgrade-standard]]
=== Standard upgrade

NOTE: 6.7 includes an https://www.elastic.co/guide/en/kibana/6.7/upgrade-assistant.html[Upgrade Assistant]
to help you prepare for your upgrade to 7.0. To access the assistant, go to *Management > 7.0 Upgrade Assistant*.

[IMPORTANT]
===========================================
If you've saved and/or exported objects in {kib} that rely on the
<<search,Elasticsearch Query DSL>>, make sure to check the {es}
{ref}/breaking-changes.html[breaking changes] documentation and take the
necessary remediation steps as per those instructions.
===========================================

[float]
==== Upgrade using a `deb` or `rpm` package

. Stop the existing {kib} process using the appropriate command for your
  system.
. Use `rpm` or `dpkg` to install the new package. All files should be placed in
  their proper locations and config files should not be overwritten.
+
[NOTE]
--
{kib} 4.x used a different config location than 5.0+, so if you're upgrading
from 4.x, you will need to copy the configurations from your old config
(`/opt/kibana/config/kibana.yml`) to your new config
(`/etc/kibana/kibana.yml`).

Make sure you remove or update any configurations
that are indicated in the <<breaking-changes,breaking changes>> documentation
otherwise {kib} will fail to start.
--
. Upgrade any plugins by removing the existing plugin and reinstalling the
  appropriate version using the `kibana-plugin` script. Check out the
  <<kibana-plugins,plugins>> documentation for more information.
. Start the new {kib} process using the appropriate command for your system.

[float]
==== Upgrade using a `zip` or `tar.gz` archive

. Extract the `zip` or `tar.gz` archive to a new directory to be sure that you
  don't overwrite the `config` or `data` directories. +
+
--
IMPORTANT: If you use {monitor-features}, you must re-use the data directory when you
upgrade {kib}. Otherwise, the {kib} instance is assigned a new persistent UUID
and becomes a new instance in the monitoring data.

--
. Copy the files from the `config` directory from your old installation to your
  new installation. Make sure you remove or update any configurations that are
  indicated in the <<breaking-changes,breaking changes>> documentation
  otherwise {kib} will fail to start.
. Copy the files from the `data` directory from your old installation to your
  new installation.
. Install the appropriate versions of all your plugins for your new
  installation using the `kibana-plugin` script. Check out the
  <<kibana-plugins,plugins>> documentation for more information.
. Stop the old {kib} process.
. Start the new {kib} process.
