/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Privileged User Monitoring API
 *   version: 2023-10-31
 */

import { z } from '@kbn/zod';

import { MonitoredUserDoc } from '../common.gen';

export type GetUserRequestParams = z.infer<typeof GetUserRequestParams>;
export const GetUserRequestParams = z.object({
  id: z.string(),
});
export type GetUserRequestParamsInput = z.input<typeof GetUserRequestParams>;

export type GetUserResponse = z.infer<typeof GetUserResponse>;
export const GetUserResponse = MonitoredUserDoc;
