[[breaking-changes-7.4]]
== Breaking changes in 7.4
++++
<titleabbrev>7.4</titleabbrev>
++++

This section discusses the changes that you need to be aware of when migrating
your application to Kibana 7.4.

//See also <<release-highlights-7.4.0, release highlights>> and <<release-notes-7.4.0, release notes>>.

//NOTE: The notable-breaking-changes tagged regions are re-used in the
//Installation and Upgrade Guide

////
The following section is re-used in the Installation and Upgrade Guide
[[breaking_70_notable]]
=== Notable breaking changes
////
// tag::notable-breaking-changes[]

[float]
[[breaking_74_search_instead_of-msearch]]
=== Use search instead of msearch when batching is disabled 

*Details:*
When the advanced setting `courier:batchSearches` is disabled, we 
previously sent the search requests as `_msearch` requests.
We now use `_search` when batching is disabled.

*Impact:*
When the advanced setting `courier:batchSearches` is disabled, 
requests from *Discover*, *Visualize*, and *Dashboard* will now query {es} 
using the `_search` endpoint rather than the `_msearch` endpoint.


// end::notable-breaking-changes[]
