[[breaking-changes-7.5]]
== Breaking changes in 7.5
++++
<titleabbrev>7.5</titleabbrev>
++++

This page discusses the breaking changes that you need to be aware of when migrating
your application to {kib} 7.5.

//See also <<release-highlights-7.5.0, release highlights>> and <<release-notes-7.5.0, release notes>>.

//NOTE: The notable-breaking-changes tagged regions are re-used in the
//Installation and Upgrade Guide

////
The following section is re-used in the Installation and Upgrade Guide
[[breaking_70_notable]]
=== Notable breaking changes
////

// tag::notable-breaking-changes[]

[float]
[[breaking_75_change_default_setting]]
=== The default setting for `courier:batchSearches` is now `false`

*Details:*
Changing the default setting for `courier:batchSearches` to `false` means 
that search requests will use the `_search` {es} endpoint rather than `_msearch`. 

*Impact:*
Dashboard panels will load individually, and search requests will terminate 
when users navigate away or update the query.

// end::notable-breaking-changes[]