[[breaking-changes-7.3]]
== Breaking changes in 7.3
++++
<titleabbrev>7.3</titleabbrev>
++++

This section discusses the changes that you need to be aware of when migrating
your application to Kibana 7.3.

See also <<release-highlights-7.3.0, release highlights>> and <<release-notes-7.3.0, release notes>>.

[float]
[[breaking_73_data_frames_date_format]]

[float]
=== Data frame transforms with date_histogram group-by configurations
*Details:* In 7.3 the `format` option for `date_histogram` 
configurations for data frame transforms is no longer supported.

*Impact:* An existing pivot transform which contains a `date_histogram` configuration might 
no longer work with 7.3. If you run into issues starting this transform, it's best to recreate
it by copying the `pivot` part of the configuration into the advanced editor of the data frame 
creation wizard.

//NOTE: The notable-breaking-changes tagged regions are re-used in the
//Installation and Upgrade Guide

//tag::notable-breaking-changes[]

// end::notable-breaking-changes[]
