import type { ElasticsearchClient } from '@kbn/core/server';
import type { Agent } from '../../types';
export declare function fetchAndAssignAgentMetrics(esClient: ElasticsearchClient, agents: Agent[]): Promise<{
    metrics: import("../../../common/types").AgentMetrics | undefined;
    id: string;
    access_api_key?: string;
    default_api_key_history?: import("../../types").FleetServerAgent["default_api_key_history"];
    outputs?: import("../../../common/types").OutputMap;
    status?: import("../../types").AgentStatus;
    packages: string[];
    sort?: any[];
    last_known_status?: import("../../types").AgentStatus;
    type: import("../../types").AgentType;
    active: boolean;
    enrolled_at: string;
    unenrolled_at?: string;
    unenrollment_started_at?: string;
    audit_unenrolled_reason?: string;
    upgraded_at?: string | null;
    upgrade_started_at?: string | null;
    upgrade_details?: import("../../../common/types").AgentUpgradeDetails;
    upgrade_attempts?: string[] | null;
    access_api_key_id?: string;
    default_api_key?: string;
    default_api_key_id?: string;
    policy_id?: string;
    policy_revision?: number | null;
    last_checkin?: string;
    last_checkin_status?: "error" | "online" | "degraded" | "updating" | "starting" | "disconnected";
    last_checkin_message?: string;
    user_provided_metadata?: import("../../types").AgentMetadata;
    local_metadata: import("../../types").AgentMetadata;
    tags?: string[];
    components?: import("../../../common/types").FleetServerAgentComponent[];
    agent?: import("../../../common").FleetServerAgentMetadata;
    unhealthy_reason?: import("../../../common/types").UnhealthyReason[];
    namespaces?: string[];
    upgrade?: import("../../../common/types").AgentUpgrade;
    identifying_attributes?: {
        [key: string]: string | number;
    };
    non_identifying_attributes?: {
        [key: string]: string | number;
    };
    sequence_num?: number;
    capabilities?: string[];
    health?: import("../../../common/types").ComponentHealth;
    effective_config?: any;
}[]>;
