import type { PublicMethodsOf } from '@kbn/utility-types';
import type { PluginInitializerContext, PluginConfigDescriptor } from '@kbn/core/server';
import type { ActionsConfig } from './config';
import type { ActionsClient as ActionsClientClass } from './actions_client';
import type { ActionsAuthorization as ActionsAuthorizationClass } from './authorization/actions_authorization';
export type { IUnsecuredActionsClient } from './unsecured_actions_client/unsecured_actions_client';
export { UnsecuredActionsClient } from './unsecured_actions_client/unsecured_actions_client';
export type ActionsClient = PublicMethodsOf<ActionsClientClass>;
export type ActionsAuthorization = PublicMethodsOf<ActionsAuthorizationClass>;
export type { ActionsPlugin, ActionResult, ActionTypeExecutorOptions, ActionType, ClassicActionType, InMemoryConnector, ActionsApiRequestHandlerContext, ConnectorLifecycleListener, ConnectorLifecyclePostCreateParams, ConnectorLifecyclePostDeleteParams, } from './types';
export type { ConnectorWithExtraFindData as FindActionResult, Connector, ConnectorType, } from './application/connector/types';
export type { PluginSetupContract, PluginStartContract } from './plugin';
export { asSavedObjectExecutionSource, asHttpRequestExecutionSource, asNotificationExecutionSource, getBasicAuthHeader, } from './lib';
export { ACTION_SAVED_OBJECT_TYPE } from './constants/saved_objects';
export declare const plugin: (initContext: PluginInitializerContext) => Promise<import("./plugin").ActionsPlugin>;
export { SubActionConnector } from './sub_action_framework/sub_action_connector';
export { CaseConnector } from './sub_action_framework/case';
export type { ServiceParams } from './sub_action_framework/types';
export declare const config: PluginConfigDescriptor<ActionsConfig>;
export { urlAllowListValidator } from './sub_action_framework/helpers';
export { ActionExecutionSourceType } from './lib/action_execution_source';
