/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

import type { SYSTEM_SECURITY_WORKER_CATALOG } from '@kbn/alertzero-common';
import {
  SYSTEM_SECURITY_WORKER_DETECTION_RULE_TUNING_ID,
  SYSTEM_SECURITY_WORKER_FLOOR_ATTACK_DISCOVERY_ID,
  SYSTEM_SECURITY_WORKER_FORENSICS_ENDPOINT_ANALYSIS_ID,
} from '@kbn/alertzero-common';
import type {
  ALERTZERO_ACTION_WORKFLOW_IDS,
  ALERTZERO_ATTACK_DISCOVERY_WORKFLOW_IDS,
  ALERTZERO_FORENSICS_WORKFLOW_IDS,
  ALERTZERO_MANAGED_WORKER_WORKFLOW_IDS,
  ALERTZERO_RULE_WORKFLOW_IDS,
} from '@kbn/workflows/managed';
import {
  ALERTZERO_ACTION_ADD_RULE_EXCEPTION_WORKFLOW_ID,
  ALERTZERO_ACTION_CREATE_RULE_WORKFLOW_ID,
  ALERTZERO_ACTION_EDIT_RULE_WORKFLOW_ID,
  ALERTZERO_ACTION_HANDOFF_TO_FORENSICS_WORKFLOW_ID,
  ALERTZERO_ACTION_ISOLATE_HOST_WORKFLOW_ID,
  ALERTZERO_ACTION_KILL_PROCESS_WORKFLOW_ID,
  ALERTZERO_ACTION_SUSPEND_PROCESS_WORKFLOW_ID,
  ALERTZERO_ATTACK_DISCOVERY_BATCHED_GENERATION_WORKFLOW_ID,
  ALERTZERO_ATTACK_DISCOVERY_FP_TP_ANALYSIS_WORKFLOW_ID,
  ALERTZERO_ATTACK_DISCOVERY_REVIEW_WORKFLOW_ID,
  ALERTZERO_ATTACK_DISCOVERY_WORKER_WORKFLOW_ID,
  ALERTZERO_COVERAGE_REVIEW_WORKFLOW_ID,
  ALERTZERO_COVERAGE_WORKER_WORKFLOW_ID,
  ALERTZERO_FORENSICS_RUN_ENDPOINT_ANALYSIS_WORKFLOW_ID,
  ALERTZERO_JOURNAL_NOTE_WORKFLOW_ID,
  ALERTZERO_RULE_CREATION_WORKFLOW_ID,
  ALERTZERO_RULE_PREVIEW_WORKFLOW_ID,
  ALERTZERO_RULE_TUNING_REVIEW_WORKFLOW_ID,
  ALERTZERO_RULE_TUNING_WORKER_WORKFLOW_ID,
  ALERTZERO_WORKER_DETECTION_RULE_CREATION_WORKFLOW_ID,
  ALERTZERO_WORKER_DETECTION_RULE_TUNING_WORKFLOW_ID,
  ALERTZERO_WORKER_FLOOR_ALERT_TRIAGE_WORKFLOW_ID,
  ALERTZERO_WORKER_FLOOR_ATTACK_DISCOVERY_WORKFLOW_ID,
  ALERTZERO_WORKER_FORENSICS_ENDPOINT_ANALYSIS_WORKFLOW_ID,
  ALERTZERO_WORKER_HUNT_CONTINUOUS_THREAT_HUNT_WORKFLOW_ID,
} from '@kbn/workflows/managed';

type CatalogWorkerId = (typeof SYSTEM_SECURITY_WORKER_CATALOG)[number]['id'];

/**
 * Every AlertZero managed definition. A new id added to one of these install
 * lists without a classification entry fails typecheck.
 */
type AlertZeroDefinitionId =
  | (typeof ALERTZERO_MANAGED_WORKER_WORKFLOW_IDS)[number]
  | (typeof ALERTZERO_RULE_WORKFLOW_IDS)[number]
  | (typeof ALERTZERO_ATTACK_DISCOVERY_WORKFLOW_IDS)[number]
  | (typeof ALERTZERO_FORENSICS_WORKFLOW_IDS)[number]
  | (typeof ALERTZERO_ACTION_WORKFLOW_IDS)[number];

type ScanFailureClassification =
  | { readonly kind: 'worker'; readonly workerId: CatalogWorkerId }
  | { readonly kind: 'exclude' }
  | { readonly kind: 'unknown' };

const worker = (workerId: CatalogWorkerId): ScanFailureClassification => ({
  kind: 'worker',
  workerId,
});

const exclude: ScanFailureClassification = { kind: 'exclude' };
const unknown: ScanFailureClassification = { kind: 'unknown' };

const DEFINITION_CLASSIFICATION = {
  [ALERTZERO_WORKER_FLOOR_ALERT_TRIAGE_WORKFLOW_ID]: worker(
    ALERTZERO_WORKER_FLOOR_ALERT_TRIAGE_WORKFLOW_ID
  ),
  [ALERTZERO_WORKER_FLOOR_ATTACK_DISCOVERY_WORKFLOW_ID]: worker(
    ALERTZERO_WORKER_FLOOR_ATTACK_DISCOVERY_WORKFLOW_ID
  ),
  [ALERTZERO_WORKER_HUNT_CONTINUOUS_THREAT_HUNT_WORKFLOW_ID]: worker(
    ALERTZERO_WORKER_HUNT_CONTINUOUS_THREAT_HUNT_WORKFLOW_ID
  ),
  [ALERTZERO_WORKER_DETECTION_RULE_TUNING_WORKFLOW_ID]: worker(
    ALERTZERO_WORKER_DETECTION_RULE_TUNING_WORKFLOW_ID
  ),
  [ALERTZERO_WORKER_DETECTION_RULE_CREATION_WORKFLOW_ID]: worker(
    ALERTZERO_WORKER_DETECTION_RULE_CREATION_WORKFLOW_ID
  ),
  [ALERTZERO_WORKER_FORENSICS_ENDPOINT_ANALYSIS_WORKFLOW_ID]: worker(
    ALERTZERO_WORKER_FORENSICS_ENDPOINT_ANALYSIS_WORKFLOW_ID
  ),
  [ALERTZERO_ATTACK_DISCOVERY_WORKER_WORKFLOW_ID]: worker(
    SYSTEM_SECURITY_WORKER_FLOOR_ATTACK_DISCOVERY_ID
  ),
  [ALERTZERO_ATTACK_DISCOVERY_BATCHED_GENERATION_WORKFLOW_ID]: worker(
    SYSTEM_SECURITY_WORKER_FLOOR_ATTACK_DISCOVERY_ID
  ),
  [ALERTZERO_ATTACK_DISCOVERY_REVIEW_WORKFLOW_ID]: worker(
    SYSTEM_SECURITY_WORKER_FLOOR_ATTACK_DISCOVERY_ID
  ),
  [ALERTZERO_ATTACK_DISCOVERY_FP_TP_ANALYSIS_WORKFLOW_ID]: worker(
    SYSTEM_SECURITY_WORKER_FLOOR_ATTACK_DISCOVERY_ID
  ),
  // Shared by Attack Discovery, forensics, and the handoff action.
  [ALERTZERO_JOURNAL_NOTE_WORKFLOW_ID]: unknown,
  [ALERTZERO_RULE_TUNING_WORKER_WORKFLOW_ID]: worker(
    SYSTEM_SECURITY_WORKER_DETECTION_RULE_TUNING_ID
  ),
  [ALERTZERO_RULE_TUNING_REVIEW_WORKFLOW_ID]: worker(
    SYSTEM_SECURITY_WORKER_DETECTION_RULE_TUNING_ID
  ),
  // Preview is a child of both Rule Tuning and the coverage chain.
  [ALERTZERO_RULE_PREVIEW_WORKFLOW_ID]: unknown,
  [ALERTZERO_COVERAGE_WORKER_WORKFLOW_ID]: unknown,
  [ALERTZERO_COVERAGE_REVIEW_WORKFLOW_ID]: unknown,
  [ALERTZERO_RULE_CREATION_WORKFLOW_ID]: unknown,
  [ALERTZERO_FORENSICS_RUN_ENDPOINT_ANALYSIS_WORKFLOW_ID]: worker(
    SYSTEM_SECURITY_WORKER_FORENSICS_ENDPOINT_ANALYSIS_ID
  ),
  [ALERTZERO_ACTION_CREATE_RULE_WORKFLOW_ID]: exclude,
  [ALERTZERO_ACTION_EDIT_RULE_WORKFLOW_ID]: exclude,
  [ALERTZERO_ACTION_ADD_RULE_EXCEPTION_WORKFLOW_ID]: exclude,
  [ALERTZERO_ACTION_ISOLATE_HOST_WORKFLOW_ID]: exclude,
  [ALERTZERO_ACTION_KILL_PROCESS_WORKFLOW_ID]: exclude,
  [ALERTZERO_ACTION_SUSPEND_PROCESS_WORKFLOW_ID]: exclude,
  [ALERTZERO_ACTION_HANDOFF_TO_FORENSICS_WORKFLOW_ID]: exclude,
} as const satisfies Record<AlertZeroDefinitionId, ScanFailureClassification>;

/** Definition ids the scan query keeps paging until it has seen, or hits the page cap. */
export const SCAN_FAILURE_DEFINITION_IDS = Object.keys(
  DEFINITION_CLASSIFICATION
) as AlertZeroDefinitionId[];

export const classifyScanFailureDefinition = (
  definitionId: string | null | undefined
): ScanFailureClassification => {
  if (!definitionId || !(definitionId in DEFINITION_CLASSIFICATION)) {
    return unknown;
  }
  return DEFINITION_CLASSIFICATION[definitionId as AlertZeroDefinitionId];
};

/** True when this definition is one of the six catalog Workers, not a child folded onto one. */
export const isCatalogWorkerDefinition = (definitionId: string | null | undefined): boolean => {
  if (!definitionId) {
    return false;
  }
  const classification = classifyScanFailureDefinition(definitionId);
  return classification.kind === 'worker' && classification.workerId === definitionId;
};
