[[development-visualize-index]]
== Developing Visualizations

Kibana Visualizations are the easiest way to add additional functionality to Kibana. 
This part of documentation is split into two parts. 
The first part tells you all you need to know on how to embed existing Kibana Visualizations in your plugin. 
The second step explains how to create your own custom visualization.

[IMPORTANT]
==============================================
These pages document internal APIs and are not guaranteed to be supported across future versions of Kibana. 
However, these docs will be kept up-to-date to reflect the current implementation of Visualization plugins in Kibana.
==============================================

* <<development-embedding-visualizations>>
* <<development-create-visualization>>


include::development-embedding-visualizations.asciidoc[]

<<<<<<< HEAD
include::development-create-visualization.asciidoc[]
=======
* The <<breaking-changes,breaking changes>> documentation, where we try to capture any changes to the APIs as they occur across minors.
* link:https://github.com/elastic/kibana/issues/44121[Meta issue] which is tracking the move of the plugin to the new Kibana platform
* Our link:https://www.elastic.co/blog/join-our-elastic-stack-workspace-on-slack[Elastic Stack workspace on Slack].
* The {kib-repo}blob/{branch}/src/plugins/visualizations[source code], which will continue to be
the most accurate source of information.
>>>>>>> d26cbef389... [DOCS] Adds kibana-pull attribute for release docs (#69554)
