/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

// Re-export from the single source of truth
export { OPERATION_TYPE_OVERRIDES } from '../../spec/kibana/aliases';

// OOM stress-test: ~100 Kibana operations (revert after CI)
export const INCLUDED_OPERATIONS = [
  // original 9
  'createCaseDefaultSpace',
  'getCaseDefaultSpace',
  'updateCaseDefaultSpace',
  'addCaseCommentDefaultSpace',
  'SetAlertsStatus',
  'SetAlertTags',
  'get-streams',
  'get-streams-name',
  'get-streams-name-significant-events',
  // +91 more — cases, rules, lists, exceptions, fleet, alerting, streams, etc.
  'findCasesDefaultSpace',
  'deleteCaseDefaultSpace',
  'getCaseAlertsDefaultSpace',
  'findCaseCommentsDefaultSpace',
  'deleteCaseCommentDefaultSpace',
  'pushCaseDefaultSpace',
  'getCaseConfigurationDefaultSpace',
  'setCaseConfigurationDefaultSpace',
  'getCaseReportersDefaultSpace',
  'getCaseTagsDefaultSpace',
  'getCasesByAlertDefaultSpace',
  'findCaseActivityDefaultSpace',
  'findCaseConnectorsDefaultSpace',
  'getCaseCommentDefaultSpace',
  'updateCaseCommentDefaultSpace',
  'updateCaseConfigurationDefaultSpace',
  'deleteCaseCommentsDefaultSpace',
  'CreateRule',
  'ReadRule',
  'UpdateRule',
  'DeleteRule',
  'FindRules',
  'PatchRule',
  'ExportRules',
  'ImportRules',
  'RulePreview',
  'CreateRuleExceptionListItems',
  'PerformRulesBulkAction',
  'ReadTags',
  'ReadPrivileges',
  'CreateExceptionList',
  'FindExceptionLists',
  'CreateExceptionListItem',
  'FindExceptionListItems',
  'ReadExceptionList',
  'ReadExceptionListItem',
  'UpdateExceptionList',
  'UpdateExceptionListItem',
  'DeleteExceptionList',
  'DeleteExceptionListItem',
  'ReadExceptionListSummary',
  'ExportExceptionList',
  'ImportExceptionList',
  'DuplicateExceptionList',
  'CreateSharedExceptionList',
  'CreateEndpointList',
  'CreateEndpointListItem',
  'FindEndpointListItems',
  'ReadEndpointListItem',
  'UpdateEndpointListItem',
  'DeleteEndpointListItem',
  'CreateList',
  'FindLists',
  'CreateListItem',
  'FindListItems',
  'ReadList',
  'ReadListItem',
  'UpdateList',
  'UpdateListItem',
  'DeleteList',
  'DeleteListItem',
  'PatchList',
  'PatchListItem',
  'CreateListIndex',
  'ReadListIndex',
  'DeleteListIndex',
  'ReadListPrivileges',
  'ExportListItems',
  'ImportListItems',
  'SearchAlerts',
  'SetAlertAssignees',
  'CreateAlertsIndex',
  'ReadAlertsIndex',
  'DeleteAlertsIndex',
  'get-alerting-rules-find',
  'get-alerting-rule-id',
  'post-alerting-rule-id',
  'put-alerting-rule-id',
  'delete-alerting-rule-id',
  'getAlertingHealth',
  'getRuleTypes',
  'get-fleet-agent-policies',
  'get-fleet-agents',
  'get-fleet-epm-packages',
  'get-fleet-package-policies',
  'get-fleet-outputs',
  'get-fleet-settings',
  'get-streams-name-ingest',
  'get-streams-name-queries',
  'put-streams-name',
  'delete-streams-name',
  'post-streams-name-fork',
  'get-streams-streamname-attachments',
];
