[[development-documentation]]
== Documentation during development

Docs should be written during development and accompany PRs when relevant. There are multiple types of documentation, and different places to add each.

[discrete]
=== Developer services documentation

Documentation about specific services a plugin offers should be encapsulated in:

* README.asciidoc at the base of the plugin folder.
* Typescript comments for all public services.

[discrete]
=== End user documentation

Documentation about user facing features should be written in http://asciidoc.org/[asciidoc] at
{kib-repo}/tree/master/docs[https://github.com/elastic/kibana/tree/master/docs]

To build the docs, you must clone the https://github.com/elastic/docs[elastic/docs]
repo as a sibling of your {kib} repo. Follow the instructions in that project's
README for getting the docs tooling set up.

**To build the docs:**

```bash
node scripts/docs.js --open
```

[discrete]
=== General developer documentation and guidelines

General developer guildlines and documentation, like this right here, should be written in http://asciidoc.org/[asciidoc]
at {kib-repo}/tree/master/docs/developer[https://github.com/elastic/kibana/tree/master/docs/developer]
