[[development-accessibility-tests]]
== Automated Accessibility Testing

To write an accessibility test, use the provided accessibility service `getService('a11y')`. Accessibility tests are fairly straightforward to write as https://github.com/dequelabs/axe-core[axe] does most of the heavy lifting. Navigate to the UI that you need to test, then call `testAppSnapshot();` from the service imported earlier to make sure axe finds no failures. Navigate through every portion of the UI for the best coverage.

An example test might look like this:
["source","js"]
----
export default function ({ getService, getPageObjects }) {
  const PageObjects = getPageObjects(['common']);
  const a11y = getService('a11y');

  describe('Kibana Home', () => {
    before(async () => {
      // navigate to a page
      await PageObjects.common.navigateToApp('home');
    });

    it('Kibana Home view', async () => {
      // run axe on the page load
      await a11y.testAppSnapshot(); // this expects that there are no failures found by axe
    });

    it('Add Kibana sample data page', async () => {
      // see a different version of this page be loading data
      await PageObjects.common.navigateToUrl('home', '/tutorial_directory/sampleData', {
        useActualUrl: true,
      });
      // re-run axe on the new UI
      await a11y.testAppSnapshot();
    });
  });
}
----

To run the tests locally:

[arabic]
. In one terminal window run
`node scripts/functional_tests_server --config test/accessibility/config.ts`
. In another terminal window run
`node scripts/functional_test_runner.js --config test/accessibility/config.ts`

To run the x-pack tests, swap the config file out for
`x-pack/test/accessibility/config.ts`.

After the server is up, you can go to this instance of {kib} at
`localhost:5620`.

The testing is done using https://github.com/dequelabs/axe-core[axe].
The same thing that runs in CI, can be run locally using their browser
plugins:

* https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US[Chrome]
* https://addons.mozilla.org/en-US/firefox/addon/axe-devtools/[Firefox]
