[[development-documentation]]
== Documentation during development

Docs should be written during development and accompany PRs when relevant. There are multiple types of documentation, and different places to add each.

[discrete]
=== End user documentation

Documentation about user facing features should be written in http://asciidoc.org/[asciidoc] at
{kib-repo}/tree/master/docs[https://github.com/elastic/kibana/tree/main/docs]

To build the docs, you must clone the https://github.com/elastic/docs[elastic/docs]
repo as a sibling of your {kib} repo. Follow the instructions in that project's
README for getting the docs tooling set up.

**To build the docs:**

```bash
node scripts/docs.js --open
```
[discrete]
==== REST APIs

REST APIs should be documented using the following recommended formats:

* https://raw.githubusercontent.com/elastic/docs/master/shared/api-ref-ex.asciidoc[API doc template]
* https://raw.githubusercontent.com/elastic/docs/master/shared/api-definitions-ex.asciidoc[API object definition template]

[discrete]
=== General developer documentation and guidelines

General developer guildlines and documentation, like this right here, should be written in http://asciidoc.org/[asciidoc]
at {kib-repo}/tree/master/docs/developer[https://github.com/elastic/kibana/tree/main/docs/developer]
