package patches.templates

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the template with id = 'DefaultTemplate'
accordingly, and delete the patch script.
*/
changeTemplate(RelativeId("DefaultTemplate")) {
    params {
        expect {
            password("env.CI_STATS_HOST", "credentialsJSON:933ba93e-4b06-44c1-8724-8c536651f2b6", display = ParameterDisplay.HIDDEN)
        }
        update {
            password("env.CI_STATS_HOST", "credentialsJSON:f8462bff-1384-4c37-8ed7-914a6407f568", display = ParameterDisplay.HIDDEN)
        }
        expect {
            password("env.KIBANA_CI_STATS_CONFIG", "", display = ParameterDisplay.HIDDEN)
        }
        update {
            password("env.KIBANA_CI_STATS_CONFIG", "credentialsJSON:549b0ee9-6e5b-496a-93e3-b6d164ea9189", display = ParameterDisplay.HIDDEN)
        }
    }
}
