/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Entity Resolution - Link Entities
 *   version: 1
 */

import { z } from '@kbn/zod';

export type ResolutionLinkRequestBody = z.infer<typeof ResolutionLinkRequestBody>;
export const ResolutionLinkRequestBody = z.object({
  /**
   * entity.id of the entity that others will resolve to
   */
  target_id: z.string(),
  /**
   * entity.id values of entities to link to the target
   */
  entity_ids: z.array(z.string()).min(1),
});
export type ResolutionLinkRequestBodyInput = z.input<typeof ResolutionLinkRequestBody>;

export type ResolutionLinkResponse = z.infer<typeof ResolutionLinkResponse>;
export const ResolutionLinkResponse = z.object({
  /**
   * Entity IDs that were newly linked
   */
  linked: z.array(z.string()),
  /**
   * Entity IDs already resolved to this target
   */
  skipped: z.array(z.string()),
  /**
   * Echoed back target entity ID
   */
  target_id: z.string(),
});
