/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License;
 * you may not use this file except in compliance with the Elastic License.
 */

import { noop } from 'lodash/fp';
import { timelineQuery } from '../../containers/timeline/index.gql_query';

export const mockEventViewerResponse = [
  {
    request: {
      query: timelineQuery,
      fetchPolicy: 'network-only',
      notifyOnNetworkStatusChange: true,
      variables: {
        fieldRequested: [
          '@timestamp',
          'message',
          'host.name',
          'event.module',
          'event.dataset',
          'event.action',
          'user.name',
          'source.ip',
          'destination.ip',
        ],
        filterQuery:
          '{"bool":{"filter":[{"bool":{"should":[{"range":{"@timestamp":{"gte":1566943856794}}}],"minimum_should_match":1}},{"bool":{"should":[{"range":{"@timestamp":{"lte":1566857456791}}}],"minimum_should_match":1}}]}}',
        sourceId: 'default',
        pagination: { limit: 25, cursor: null, tiebreaker: null },
        sortField: { sortFieldId: '@timestamp', direction: 'desc' },
        defaultIndex: ['auditbeat-*', 'filebeat-*', 'packetbeat-*', 'winlogbeat-*'],
        inspect: false,
      },
    },
    result: {
      loading: false,
      fetchMore: noop,
      refetch: noop,
      data: {
        source: {
          id: 'default',
          Timeline: {
            totalCount: 12,
            inspect: null,
            pageInfo: {
              endCursor: {
                value: '1566857636197',
                tiebreaker: '19378194',
                __typename: 'CursorType',
              },
              hasNextPage: true,
              __typename: 'PageInfo',
            },
            edges: [
              {
                node: {
                  _id: 'I8f7z2wBUZUjF-GHgVC3',
                  _index: 'auditbeat-8.0.0-2019.08.09-000020',
                  data: [
                    {
                      field: '_id',
                      value: ['I8f7z2wBUZUjF-GHgVC3'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: '_index',
                      value: ['auditbeat-8.0.0-2019.08.09-000020'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.action',
                      value: ['network_flow'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.category',
                      value: ['network_traffic'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.dataset',
                      value: ['newsocket'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.module',
                      value: ['system'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'host.name',
                      value: ['test-hostname'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'source.ip',
                      value: ['10.1.0.10'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'destination.ip',
                      value: ['10.254.169.254'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'user.name',
                      value: ['root'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: '@timestamp',
                      value: ['2019-08-26T22:11:01.197Z'],
                      __typename: 'TimelineNonEcsData',
                    },
                  ],
                  ecs: {
                    _id: 'I8f7z2wBUZUjF-GHgVC3',
                    _index: 'auditbeat-8.0.0-2019.08.09-000020',
                    timestamp: '2019-08-26T22:11:01.197Z',
                    message: null,
                    system: null,
                    event: {
                      action: ['network_flow'],
                      category: ['network_traffic'],
                      created: null,
                      dataset: ['newsocket'],
                      duration: [94641],
                      end: ['2019-08-26T22:10:55.687Z'],
                      hash: null,
                      id: null,
                      kind: ['event'],
                      module: ['system'],
                      original: null,
                      outcome: null,
                      risk_score: null,
                      risk_score_norm: null,
                      severity: null,
                      start: ['2019-08-26T22:10:55.687Z'],
                      timezone: null,
                      type: null,
                      __typename: 'EventEcsFields',
                    },
                    auditd: null,
                    file: null,
                    host: {
                      id: ['b6d5264e4b9c8880ad1053841067a4a6'],
                      name: ['test-hostname'],
                      ip: null,
                      __typename: 'HostEcsFields',
                    },
                    source: {
                      bytes: [40],
                      ip: ['10.1.0.10'],
                      packets: [1],
                      port: [47326],
                      geo: null,
                      __typename: 'SourceEcsFields',
                    },
                    destination: {
                      bytes: [20],
                      ip: ['10.254.169.254'],
                      packets: [1],
                      port: [80],
                      geo: null,
                      __typename: 'DestinationEcsFields',
                    },
                    geo: null,
                    suricata: null,
                    network: {
                      bytes: [60],
                      community_id: ['1:0CCPhe6xI5lujua9s+kTwzes4Hg='],
                      direction: ['outbound'],
                      packets: [2],
                      protocol: null,
                      transport: ['tcp'],
                      __typename: 'NetworkEcsField',
                    },
                    http: null,
                    tls: null,
                    url: null,
                    user: {
                      name: ['root'],
                      __typename: 'UserEcsFields',
                    },
                    process: {
                      pid: [779],
                      name: ['google_clock_sk'],
                      ppid: null,
                      args: ['/usr/bin/python', '/usr/bin/google_clock_skew_daemon'],
                      executable: ['/usr/bin/python2.7'],
                      title: null,
                      working_directory: null,
                      __typename: 'ProcessEcsFields',
                    },
                    zeek: null,
                    __typename: 'ECS',
                  },
                  __typename: 'TimelineItem',
                },
                __typename: 'TimelineEdges',
              },
              {
                node: {
                  _id: 'Xsf7z2wBUZUjF-GHjVBu',
                  _index: 'auditbeat-8.0.0-2019.08.09-000020',
                  data: [
                    {
                      field: '_id',
                      value: ['Xsf7z2wBUZUjF-GHjVBu'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: '_index',
                      value: ['auditbeat-8.0.0-2019.08.09-000020'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.action',
                      value: ['network_flow'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.category',
                      value: ['network_traffic'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.dataset',
                      value: ['newsocket'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.module',
                      value: ['system'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'host.name',
                      value: ['test-hostname'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'source.ip',
                      value: ['10.1.0.10'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'destination.ip',
                      value: ['10.254.169.254'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'user.name',
                      value: ['elasticsearch'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: '@timestamp',
                      value: ['2019-08-26T22:11:04.197Z'],
                      __typename: 'TimelineNonEcsData',
                    },
                  ],
                  ecs: {
                    _id: 'Xsf7z2wBUZUjF-GHjVBu',
                    _index: 'auditbeat-8.0.0-2019.08.09-000020',
                    timestamp: '2019-08-26T22:11:04.197Z',
                    message: null,
                    system: null,
                    event: {
                      action: ['network_flow'],
                      category: ['network_traffic'],
                      created: null,
                      dataset: ['newsocket'],
                      duration: [745270],
                      end: ['2019-08-26T22:11:03.690Z'],
                      hash: null,
                      id: null,
                      kind: ['event'],
                      module: ['system'],
                      original: null,
                      outcome: null,
                      risk_score: null,
                      risk_score_norm: null,
                      severity: null,
                      start: ['2019-08-26T22:11:03.690Z'],
                      timezone: null,
                      type: null,
                      __typename: 'EventEcsFields',
                    },
                    auditd: null,
                    file: null,
                    host: {
                      id: ['b6d5264e4b9c8880ad1053841067a4a6'],
                      name: ['test-hostname'],
                      ip: null,
                      __typename: 'HostEcsFields',
                    },
                    source: {
                      bytes: [80],
                      ip: ['10.1.0.10'],
                      packets: [2],
                      port: [47332],
                      geo: null,
                      __typename: 'SourceEcsFields',
                    },
                    destination: {
                      bytes: [643],
                      ip: ['10.254.169.254'],
                      packets: [3],
                      port: [80],
                      geo: null,
                      __typename: 'DestinationEcsFields',
                    },
                    geo: null,
                    suricata: null,
                    network: {
                      bytes: [723],
                      community_id: ['1:4FXauxs54+Ta2G8GLEcq13t+VTQ='],
                      direction: ['outbound'],
                      packets: [5],
                      protocol: null,
                      transport: ['tcp'],
                      __typename: 'NetworkEcsField',
                    },
                    http: null,
                    tls: null,
                    url: null,
                    user: {
                      name: ['elasticsearch'],
                      __typename: 'UserEcsFields',
                    },
                    process: {
                      pid: [14216],
                      name: ['java'],
                      ppid: null,
                      args: [
                        '/usr/share/elasticsearch/jdk/bin/java',
                        '-Xms8g',
                        '-Xmx8g',
                        '-XX:+UseConcMarkSweepGC',
                        '-XX:CMSInitiatingOccupancyFraction=75',
                        '-XX:+UseCMSInitiatingOccupancyOnly',
                        '-Des.networkaddress.cache.ttl=60',
                        '-Des.networkaddress.cache.negative.ttl=10',
                        '-XX:+AlwaysPreTouch',
                        '-Xss1m',
                        '-Djava.awt.headless=true',
                        '-Dfile.encoding=UTF-8',
                        '-Djna.nosys=true',
                        '-XX:-OmitStackTraceInFastThrow',
                        '-Dio.netty.noUnsafe=true',
                        '-Dio.netty.noKeySetOptimization=true',
                        '-Dio.netty.recycler.maxCapacityPerThread=0',
                        '-Dlog4j.shutdownHookEnabled=false',
                        '-Dlog4j2.disable.jmx=true',
                        '-Djava.io.tmpdir=/tmp/elasticsearch-11139975657297362630',
                        '-XX:+HeapDumpOnOutOfMemoryError',
                        '-XX:HeapDumpPath=/var/lib/elasticsearch',
                        '-XX:ErrorFile=/var/log/elasticsearch/hs_err_pid%p.log',
                        '-Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m',
                        '-Djava.locale.providers=COMPAT',
                        '-XX:UseAVX=2',
                        '-Dio.netty.allocator.type=pooled',
                        '-XX:MaxDirectMemorySize=4294967296',
                        '-Des.path.home=/usr/share/elasticsearch',
                        '-Des.path.conf=/etc/elasticsearch',
                        '-Des.distribution.flavor=default',
                        '-Des.distribution.type=deb',
                        '-Des.bundled_jdk=true',
                        '-cp',
                        '/usr/share/elasticsearch/lib/*',
                        'org.elasticsearch.bootstrap.Elasticsearch',
                        '-p',
                        '/var/run/elasticsearch/elasticsearch.pid',
                        '--quiet',
                      ],
                      executable: ['/usr/share/elasticsearch/jdk/bin/java'],
                      title: null,
                      working_directory: null,
                      __typename: 'ProcessEcsFields',
                    },
                    zeek: null,
                    __typename: 'ECS',
                  },
                  __typename: 'TimelineItem',
                },
                __typename: 'TimelineEdges',
              },
              {
                node: {
                  _id: 'Wcf7z2wBUZUjF-GHqFTH',
                  _index: 'auditbeat-8.0.0-2019.08.09-000020',
                  data: [
                    {
                      field: '_id',
                      value: ['Wcf7z2wBUZUjF-GHqFTH'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: '_index',
                      value: ['auditbeat-8.0.0-2019.08.09-000020'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.action',
                      value: ['network_flow'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.category',
                      value: ['network_traffic'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.dataset',
                      value: ['newsocket'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.module',
                      value: ['system'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'host.name',
                      value: ['test-hostname'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'source.ip',
                      value: ['10.1.0.10'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'destination.ip',
                      value: ['10.254.169.254'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'user.name',
                      value: ['root'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: '@timestamp',
                      value: ['2019-08-26T22:11:11.197Z'],
                      __typename: 'TimelineNonEcsData',
                    },
                  ],
                  ecs: {
                    _id: 'Wcf7z2wBUZUjF-GHqFTH',
                    _index: 'auditbeat-8.0.0-2019.08.09-000020',
                    timestamp: '2019-08-26T22:11:11.197Z',
                    message: null,
                    system: null,
                    event: {
                      action: ['network_flow'],
                      category: ['network_traffic'],
                      created: null,
                      dataset: ['newsocket'],
                      duration: [503895],
                      end: ['2019-08-26T22:10:40.962Z'],
                      hash: null,
                      id: null,
                      kind: ['event'],
                      module: ['system'],
                      original: null,
                      outcome: null,
                      risk_score: null,
                      risk_score_norm: null,
                      severity: null,
                      start: ['2019-08-26T22:10:40.961Z'],
                      timezone: null,
                      type: null,
                      __typename: 'EventEcsFields',
                    },
                    auditd: null,
                    file: null,
                    host: {
                      id: ['b6d5264e4b9c8880ad1053841067a4a6'],
                      name: ['test-hostname'],
                      ip: null,
                      __typename: 'HostEcsFields',
                    },
                    source: {
                      bytes: [398],
                      ip: ['10.1.0.10'],
                      packets: [3],
                      port: [47334],
                      geo: null,
                      __typename: 'SourceEcsFields',
                    },
                    destination: {
                      bytes: [68],
                      ip: ['10.254.169.254'],
                      packets: [3],
                      port: [80],
                      geo: null,
                      __typename: 'DestinationEcsFields',
                    },
                    geo: null,
                    suricata: null,
                    network: {
                      bytes: [466],
                      community_id: ['1:DeNTfpwzpvjVdQKa+TA0uUgYJA0='],
                      direction: ['outbound'],
                      packets: [6],
                      protocol: null,
                      transport: ['tcp'],
                      __typename: 'NetworkEcsField',
                    },
                    http: null,
                    tls: null,
                    url: null,
                    user: {
                      name: ['root'],
                      __typename: 'UserEcsFields',
                    },
                    process: {
                      pid: [781],
                      name: ['google_accounts'],
                      ppid: null,
                      args: ['/usr/bin/python', '/usr/bin/google_accounts_daemon'],
                      executable: ['/usr/bin/python2.7'],
                      title: null,
                      working_directory: null,
                      __typename: 'ProcessEcsFields',
                    },
                    zeek: null,
                    __typename: 'ECS',
                  },
                  __typename: 'TimelineItem',
                },
                __typename: 'TimelineEdges',
              },
              {
                node: {
                  _id: '48f7z2wBUZUjF-GH41he',
                  _index: 'auditbeat-8.0.0-2019.08.09-000020',
                  data: [
                    {
                      field: '_id',
                      value: ['48f7z2wBUZUjF-GH41he'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: '_index',
                      value: ['auditbeat-8.0.0-2019.08.09-000020'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.action',
                      value: ['network_flow'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.category',
                      value: ['network_traffic'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.dataset',
                      value: ['newsocket'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.module',
                      value: ['system'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'host.name',
                      value: ['test-hostname'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'source.ip',
                      value: ['10.1.0.10'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'destination.ip',
                      value: ['10.254.169.254'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'user.name',
                      value: ['root'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: '@timestamp',
                      value: ['2019-08-26T22:11:26.197Z'],
                      __typename: 'TimelineNonEcsData',
                    },
                  ],
                  ecs: {
                    _id: '48f7z2wBUZUjF-GH41he',
                    _index: 'auditbeat-8.0.0-2019.08.09-000020',
                    timestamp: '2019-08-26T22:11:26.197Z',
                    message: null,
                    system: null,
                    event: {
                      action: ['network_flow'],
                      category: ['network_traffic'],
                      created: null,
                      dataset: ['newsocket'],
                      duration: [433950],
                      end: ['2019-08-26T22:10:55.688Z'],
                      hash: null,
                      id: null,
                      kind: ['event'],
                      module: ['system'],
                      original: null,
                      outcome: null,
                      risk_score: null,
                      risk_score_norm: null,
                      severity: null,
                      start: ['2019-08-26T22:10:55.687Z'],
                      timezone: null,
                      type: null,
                      __typename: 'EventEcsFields',
                    },
                    auditd: null,
                    file: null,
                    host: {
                      id: ['b6d5264e4b9c8880ad1053841067a4a6'],
                      name: ['test-hostname'],
                      ip: null,
                      __typename: 'HostEcsFields',
                    },
                    source: {
                      bytes: [433],
                      ip: ['10.1.0.10'],
                      packets: [3],
                      port: [47336],
                      geo: null,
                      __typename: 'SourceEcsFields',
                    },
                    destination: {
                      bytes: [68],
                      ip: ['10.254.169.254'],
                      packets: [3],
                      port: [80],
                      geo: null,
                      __typename: 'DestinationEcsFields',
                    },
                    geo: null,
                    suricata: null,
                    network: {
                      bytes: [501],
                      community_id: ['1:YmpabiNDGF+hBfF2bZL3jDfHOYY='],
                      direction: ['outbound'],
                      packets: [6],
                      protocol: null,
                      transport: ['tcp'],
                      __typename: 'NetworkEcsField',
                    },
                    http: null,
                    tls: null,
                    url: null,
                    user: {
                      name: ['root'],
                      __typename: 'UserEcsFields',
                    },
                    process: {
                      pid: [779],
                      name: ['google_clock_sk'],
                      ppid: null,
                      args: ['/usr/bin/python', '/usr/bin/google_clock_skew_daemon'],
                      executable: ['/usr/bin/python2.7'],
                      title: null,
                      working_directory: null,
                      __typename: 'ProcessEcsFields',
                    },
                    zeek: null,
                    __typename: 'ECS',
                  },
                  __typename: 'TimelineItem',
                },
                __typename: 'TimelineEdges',
              },
              {
                node: {
                  _id: '5Mf7z2wBUZUjF-GH41he',
                  _index: 'auditbeat-8.0.0-2019.08.09-000020',
                  data: [
                    {
                      field: '_id',
                      value: ['5Mf7z2wBUZUjF-GH41he'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: '_index',
                      value: ['auditbeat-8.0.0-2019.08.09-000020'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.action',
                      value: ['network_flow'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.category',
                      value: ['network_traffic'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.dataset',
                      value: ['newsocket'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.module',
                      value: ['system'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'host.name',
                      value: ['test-hostname'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'source.ip',
                      value: ['10.1.0.10'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'destination.ip',
                      value: ['10.254.169.254'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'user.name',
                      value: ['root'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: '@timestamp',
                      value: ['2019-08-26T22:11:26.197Z'],
                      __typename: 'TimelineNonEcsData',
                    },
                  ],
                  ecs: {
                    _id: '5Mf7z2wBUZUjF-GH41he',
                    _index: 'auditbeat-8.0.0-2019.08.09-000020',
                    timestamp: '2019-08-26T22:11:26.197Z',
                    message: null,
                    system: null,
                    event: {
                      action: ['network_flow'],
                      category: ['network_traffic'],
                      created: null,
                      dataset: ['newsocket'],
                      duration: [42194170],
                      end: ['2019-08-26T22:10:55.728Z'],
                      hash: null,
                      id: null,
                      kind: ['event'],
                      module: ['system'],
                      original: null,
                      outcome: null,
                      risk_score: null,
                      risk_score_norm: null,
                      severity: null,
                      start: ['2019-08-26T22:10:55.686Z'],
                      timezone: null,
                      type: null,
                      __typename: 'EventEcsFields',
                    },
                    auditd: null,
                    file: null,
                    host: {
                      id: ['b6d5264e4b9c8880ad1053841067a4a6'],
                      name: ['test-hostname'],
                      ip: null,
                      __typename: 'HostEcsFields',
                    },
                    source: {
                      bytes: [80],
                      ip: ['10.1.0.10'],
                      packets: [2],
                      port: [47330],
                      geo: null,
                      __typename: 'SourceEcsFields',
                    },
                    destination: {
                      bytes: [300],
                      ip: ['10.254.169.254'],
                      packets: [2],
                      port: [80],
                      geo: null,
                      __typename: 'DestinationEcsFields',
                    },
                    geo: null,
                    suricata: null,
                    network: {
                      bytes: [380],
                      community_id: ['1:AzIProRoPcyKAuEPVrB0pcFlOoE='],
                      direction: ['outbound'],
                      packets: [4],
                      protocol: null,
                      transport: ['tcp'],
                      __typename: 'NetworkEcsField',
                    },
                    http: null,
                    tls: null,
                    url: null,
                    user: {
                      name: ['root'],
                      __typename: 'UserEcsFields',
                    },
                    process: {
                      pid: [779],
                      name: ['google_clock_sk'],
                      ppid: null,
                      args: ['/usr/bin/python', '/usr/bin/google_clock_skew_daemon'],
                      executable: ['/usr/bin/python2.7'],
                      title: null,
                      working_directory: null,
                      __typename: 'ProcessEcsFields',
                    },
                    zeek: null,
                    __typename: 'ECS',
                  },
                  __typename: 'TimelineItem',
                },
                __typename: 'TimelineEdges',
              },
              {
                node: {
                  _id: '7Mf7z2wBUZUjF-GH-lzP',
                  _index: 'auditbeat-8.0.0-2019.08.09-000020',
                  data: [
                    {
                      field: '_id',
                      value: ['7Mf7z2wBUZUjF-GH-lzP'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: '_index',
                      value: ['auditbeat-8.0.0-2019.08.09-000020'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.action',
                      value: ['network_flow'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.category',
                      value: ['network_traffic'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.dataset',
                      value: ['newsocket'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.module',
                      value: ['system'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'host.name',
                      value: ['test-hostname'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'source.ip',
                      value: ['10.1.0.10'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'destination.ip',
                      value: ['2.3.4.245'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'user.name',
                      value: ['elasticsearch'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: '@timestamp',
                      value: ['2019-08-26T22:11:32.197Z'],
                      __typename: 'TimelineNonEcsData',
                    },
                  ],
                  ecs: {
                    _id: '7Mf7z2wBUZUjF-GH-lzP',
                    _index: 'auditbeat-8.0.0-2019.08.09-000020',
                    timestamp: '2019-08-26T22:11:32.197Z',
                    message: null,
                    system: null,
                    event: {
                      action: ['network_flow'],
                      category: ['network_traffic'],
                      created: null,
                      dataset: ['newsocket'],
                      duration: [978438771],
                      end: ['2019-08-26T22:11:02.085Z'],
                      hash: null,
                      id: null,
                      kind: ['event'],
                      module: ['system'],
                      original: null,
                      outcome: null,
                      risk_score: null,
                      risk_score_norm: null,
                      severity: null,
                      start: ['2019-08-26T22:11:01.106Z'],
                      timezone: null,
                      type: null,
                      __typename: 'EventEcsFields',
                    },
                    auditd: null,
                    file: null,
                    host: {
                      id: ['b6d5264e4b9c8880ad1053841067a4a6'],
                      name: ['test-hostname'],
                      ip: null,
                      __typename: 'HostEcsFields',
                    },
                    source: {
                      bytes: [209687],
                      ip: ['10.1.0.10'],
                      packets: [161],
                      port: [9200],
                      geo: null,
                      __typename: 'SourceEcsFields',
                    },
                    destination: {
                      bytes: [1846733],
                      ip: ['2.3.4.245'],
                      packets: [127],
                      port: [54192],
                      geo: null,
                      __typename: 'DestinationEcsFields',
                    },
                    geo: null,
                    suricata: null,
                    network: {
                      bytes: [2056420],
                      community_id: ['1:QApcPm8gYSn1J9ITUVnp5bu9D84='],
                      direction: ['unknown'],
                      packets: [288],
                      protocol: null,
                      transport: ['tcp'],
                      __typename: 'NetworkEcsField',
                    },
                    http: null,
                    tls: null,
                    url: null,
                    user: {
                      name: ['elasticsearch'],
                      __typename: 'UserEcsFields',
                    },
                    process: {
                      pid: [14216],
                      name: ['java'],
                      ppid: null,
                      args: [
                        '/usr/share/elasticsearch/jdk/bin/java',
                        '-Xms8g',
                        '-Xmx8g',
                        '-XX:+UseConcMarkSweepGC',
                        '-XX:CMSInitiatingOccupancyFraction=75',
                        '-XX:+UseCMSInitiatingOccupancyOnly',
                        '-Des.networkaddress.cache.ttl=60',
                        '-Des.networkaddress.cache.negative.ttl=10',
                        '-XX:+AlwaysPreTouch',
                        '-Xss1m',
                        '-Djava.awt.headless=true',
                        '-Dfile.encoding=UTF-8',
                        '-Djna.nosys=true',
                        '-XX:-OmitStackTraceInFastThrow',
                        '-Dio.netty.noUnsafe=true',
                        '-Dio.netty.noKeySetOptimization=true',
                        '-Dio.netty.recycler.maxCapacityPerThread=0',
                        '-Dlog4j.shutdownHookEnabled=false',
                        '-Dlog4j2.disable.jmx=true',
                        '-Djava.io.tmpdir=/tmp/elasticsearch-11139975657297362630',
                        '-XX:+HeapDumpOnOutOfMemoryError',
                        '-XX:HeapDumpPath=/var/lib/elasticsearch',
                        '-XX:ErrorFile=/var/log/elasticsearch/hs_err_pid%p.log',
                        '-Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m',
                        '-Djava.locale.providers=COMPAT',
                        '-XX:UseAVX=2',
                        '-Dio.netty.allocator.type=pooled',
                        '-XX:MaxDirectMemorySize=4294967296',
                        '-Des.path.home=/usr/share/elasticsearch',
                        '-Des.path.conf=/etc/elasticsearch',
                        '-Des.distribution.flavor=default',
                        '-Des.distribution.type=deb',
                        '-Des.bundled_jdk=true',
                        '-cp',
                        '/usr/share/elasticsearch/lib/*',
                        'org.elasticsearch.bootstrap.Elasticsearch',
                        '-p',
                        '/var/run/elasticsearch/elasticsearch.pid',
                        '--quiet',
                      ],
                      executable: ['/usr/share/elasticsearch/jdk/bin/java'],
                      title: null,
                      working_directory: null,
                      __typename: 'ProcessEcsFields',
                    },
                    zeek: null,
                    __typename: 'ECS',
                  },
                  __typename: 'TimelineItem',
                },
                __typename: 'TimelineEdges',
              },
              {
                node: {
                  _id: '_sf8z2wBUZUjF-GHAlyf',
                  _index: 'auditbeat-8.0.0-2019.08.09-000020',
                  data: [
                    {
                      field: '_id',
                      value: ['_sf8z2wBUZUjF-GHAlyf'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: '_index',
                      value: ['auditbeat-8.0.0-2019.08.09-000020'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.action',
                      value: ['network_flow'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.category',
                      value: ['network_traffic'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.dataset',
                      value: ['newsocket'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.module',
                      value: ['system'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'host.name',
                      value: ['test-hostname'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'source.ip',
                      value: ['10.1.0.10'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'destination.ip',
                      value: ['10.254.169.254'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'user.name',
                      value: ['root'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: '@timestamp',
                      value: ['2019-08-26T22:11:34.197Z'],
                      __typename: 'TimelineNonEcsData',
                    },
                  ],
                  ecs: {
                    _id: '_sf8z2wBUZUjF-GHAlyf',
                    _index: 'auditbeat-8.0.0-2019.08.09-000020',
                    timestamp: '2019-08-26T22:11:34.197Z',
                    message: null,
                    system: null,
                    event: {
                      action: ['network_flow'],
                      category: ['network_traffic'],
                      created: null,
                      dataset: ['newsocket'],
                      duration: [568869],
                      end: ['2019-08-26T22:11:04.049Z'],
                      hash: null,
                      id: null,
                      kind: ['event'],
                      module: ['system'],
                      original: null,
                      outcome: null,
                      risk_score: null,
                      risk_score_norm: null,
                      severity: null,
                      start: ['2019-08-26T22:11:04.049Z'],
                      timezone: null,
                      type: null,
                      __typename: 'EventEcsFields',
                    },
                    auditd: null,
                    file: null,
                    host: {
                      id: ['b6d5264e4b9c8880ad1053841067a4a6'],
                      name: ['test-hostname'],
                      ip: null,
                      __typename: 'HostEcsFields',
                    },
                    source: {
                      bytes: [426],
                      ip: ['10.1.0.10'],
                      packets: [3],
                      port: [47338],
                      geo: null,
                      __typename: 'SourceEcsFields',
                    },
                    destination: {
                      bytes: [68],
                      ip: ['10.254.169.254'],
                      packets: [3],
                      port: [80],
                      geo: null,
                      __typename: 'DestinationEcsFields',
                    },
                    geo: null,
                    suricata: null,
                    network: {
                      bytes: [494],
                      community_id: ['1:KQhY2nIBEF+NlBZ3pA07QT8sfR0='],
                      direction: ['outbound'],
                      packets: [6],
                      protocol: null,
                      transport: ['tcp'],
                      __typename: 'NetworkEcsField',
                    },
                    http: null,
                    tls: null,
                    url: null,
                    user: {
                      name: ['root'],
                      __typename: 'UserEcsFields',
                    },
                    process: {
                      pid: [778],
                      name: ['google_network_'],
                      ppid: null,
                      args: ['/usr/bin/python', '/usr/bin/google_network_daemon'],
                      executable: ['/usr/bin/python2.7'],
                      title: null,
                      working_directory: null,
                      __typename: 'ProcessEcsFields',
                    },
                    zeek: null,
                    __typename: 'ECS',
                  },
                  __typename: 'TimelineItem',
                },
                __typename: 'TimelineEdges',
              },
              {
                node: {
                  _id: '_8f8z2wBUZUjF-GHAlyf',
                  _index: 'auditbeat-8.0.0-2019.08.09-000020',
                  data: [
                    {
                      field: '_id',
                      value: ['_8f8z2wBUZUjF-GHAlyf'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: '_index',
                      value: ['auditbeat-8.0.0-2019.08.09-000020'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.action',
                      value: ['network_flow'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.category',
                      value: ['network_traffic'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.dataset',
                      value: ['newsocket'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.module',
                      value: ['system'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'host.name',
                      value: ['test-hostname'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'source.ip',
                      value: ['10.1.0.10'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'destination.ip',
                      value: ['144.76.73.184'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'user.name',
                      value: ['elasticsearch'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: '@timestamp',
                      value: ['2019-08-26T22:11:35.197Z'],
                      __typename: 'TimelineNonEcsData',
                    },
                  ],
                  ecs: {
                    _id: '_8f8z2wBUZUjF-GHAlyf',
                    _index: 'auditbeat-8.0.0-2019.08.09-000020',
                    timestamp: '2019-08-26T22:11:35.197Z',
                    message: null,
                    system: null,
                    event: {
                      action: ['network_flow'],
                      category: ['network_traffic'],
                      created: null,
                      dataset: ['newsocket'],
                      duration: [684809938],
                      end: ['2019-08-26T22:11:04.333Z'],
                      hash: null,
                      id: null,
                      kind: ['event'],
                      module: ['system'],
                      original: null,
                      outcome: null,
                      risk_score: null,
                      risk_score_norm: null,
                      severity: null,
                      start: ['2019-08-26T22:11:03.648Z'],
                      timezone: null,
                      type: null,
                      __typename: 'EventEcsFields',
                    },
                    auditd: null,
                    file: null,
                    host: {
                      id: ['b6d5264e4b9c8880ad1053841067a4a6'],
                      name: ['test-hostname'],
                      ip: null,
                      __typename: 'HostEcsFields',
                    },
                    source: {
                      bytes: [55292],
                      ip: ['10.1.0.10'],
                      packets: [28],
                      port: [9200],
                      geo: null,
                      __typename: 'SourceEcsFields',
                    },
                    destination: {
                      bytes: [21660],
                      ip: ['11.12.13.184'],
                      packets: [14],
                      port: [58830],
                      geo: null,
                      __typename: 'DestinationEcsFields',
                    },
                    geo: null,
                    suricata: null,
                    network: {
                      bytes: [76952],
                      community_id: ['1:Vm3uNPFRE4h4ryMVaDW9wl51AdE='],
                      direction: ['unknown'],
                      packets: [42],
                      protocol: null,
                      transport: ['tcp'],
                      __typename: 'NetworkEcsField',
                    },
                    http: null,
                    tls: null,
                    url: null,
                    user: {
                      name: ['elasticsearch'],
                      __typename: 'UserEcsFields',
                    },
                    process: {
                      pid: [14216],
                      name: ['java'],
                      ppid: null,
                      args: [
                        '/usr/share/elasticsearch/jdk/bin/java',
                        '-Xms8g',
                        '-Xmx8g',
                        '-XX:+UseConcMarkSweepGC',
                        '-XX:CMSInitiatingOccupancyFraction=75',
                        '-XX:+UseCMSInitiatingOccupancyOnly',
                        '-Des.networkaddress.cache.ttl=60',
                        '-Des.networkaddress.cache.negative.ttl=10',
                        '-XX:+AlwaysPreTouch',
                        '-Xss1m',
                        '-Djava.awt.headless=true',
                        '-Dfile.encoding=UTF-8',
                        '-Djna.nosys=true',
                        '-XX:-OmitStackTraceInFastThrow',
                        '-Dio.netty.noUnsafe=true',
                        '-Dio.netty.noKeySetOptimization=true',
                        '-Dio.netty.recycler.maxCapacityPerThread=0',
                        '-Dlog4j.shutdownHookEnabled=false',
                        '-Dlog4j2.disable.jmx=true',
                        '-Djava.io.tmpdir=/tmp/elasticsearch-11139975657297362630',
                        '-XX:+HeapDumpOnOutOfMemoryError',
                        '-XX:HeapDumpPath=/var/lib/elasticsearch',
                        '-XX:ErrorFile=/var/log/elasticsearch/hs_err_pid%p.log',
                        '-Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m',
                        '-Djava.locale.providers=COMPAT',
                        '-XX:UseAVX=2',
                        '-Dio.netty.allocator.type=pooled',
                        '-XX:MaxDirectMemorySize=4294967296',
                        '-Des.path.home=/usr/share/elasticsearch',
                        '-Des.path.conf=/etc/elasticsearch',
                        '-Des.distribution.flavor=default',
                        '-Des.distribution.type=deb',
                        '-Des.bundled_jdk=true',
                        '-cp',
                        '/usr/share/elasticsearch/lib/*',
                        'org.elasticsearch.bootstrap.Elasticsearch',
                        '-p',
                        '/var/run/elasticsearch/elasticsearch.pid',
                        '--quiet',
                      ],
                      executable: ['/usr/share/elasticsearch/jdk/bin/java'],
                      title: null,
                      working_directory: null,
                      __typename: 'ProcessEcsFields',
                    },
                    zeek: null,
                    __typename: 'ECS',
                  },
                  __typename: 'TimelineItem',
                },
                __typename: 'TimelineEdges',
              },
              {
                node: {
                  _id: 'P8f8z2wBUZUjF-GHSGX9',
                  _index: 'auditbeat-8.0.0-2019.08.09-000020',
                  data: [
                    {
                      field: '_id',
                      value: ['P8f8z2wBUZUjF-GHSGX9'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: '_index',
                      value: ['auditbeat-8.0.0-2019.08.09-000020'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.action',
                      value: ['network_flow'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.category',
                      value: ['network_traffic'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.dataset',
                      value: ['newsocket'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.module',
                      value: ['system'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'host.name',
                      value: ['test-hostname'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'source.ip',
                      value: ['35.227.65.114'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'destination.ip',
                      value: ['10.1.0.10'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'user.name',
                      value: ['elasticsearch'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: '@timestamp',
                      value: ['2019-08-26T22:11:52.197Z'],
                      __typename: 'TimelineNonEcsData',
                    },
                  ],
                  ecs: {
                    _id: 'P8f8z2wBUZUjF-GHSGX9',
                    _index: 'auditbeat-8.0.0-2019.08.09-000020',
                    timestamp: '2019-08-26T22:11:52.197Z',
                    message: null,
                    system: null,
                    event: {
                      action: ['network_flow'],
                      category: ['network_traffic'],
                      created: null,
                      dataset: ['newsocket'],
                      duration: [1025645372],
                      end: ['2019-08-26T22:11:22.019Z'],
                      hash: null,
                      id: null,
                      kind: ['event'],
                      module: ['system'],
                      original: null,
                      outcome: null,
                      risk_score: null,
                      risk_score_norm: null,
                      severity: null,
                      start: ['2019-08-26T22:11:20.993Z'],
                      timezone: null,
                      type: null,
                      __typename: 'EventEcsFields',
                    },
                    auditd: null,
                    file: null,
                    host: {
                      id: ['b6d5264e4b9c8880ad1053841067a4a6'],
                      name: ['test-hostname'],
                      ip: null,
                      __typename: 'HostEcsFields',
                    },
                    source: {
                      bytes: [1569],
                      ip: ['14.15.16.114'],
                      packets: [5],
                      port: [37716],
                      geo: null,
                      __typename: 'SourceEcsFields',
                    },
                    destination: {
                      bytes: [465],
                      ip: ['10.1.0.10'],
                      packets: [4],
                      port: [9200],
                      geo: null,
                      __typename: 'DestinationEcsFields',
                    },
                    geo: null,
                    suricata: null,
                    network: {
                      bytes: [2034],
                      community_id: ['1:yr59eYNv6IDs8hBHG4CRQKZny/g='],
                      direction: ['inbound'],
                      packets: [9],
                      protocol: null,
                      transport: ['tcp'],
                      __typename: 'NetworkEcsField',
                    },
                    http: null,
                    tls: null,
                    url: null,
                    user: {
                      name: ['elasticsearch'],
                      __typename: 'UserEcsFields',
                    },
                    process: {
                      pid: [14216],
                      name: ['java'],
                      ppid: null,
                      args: [
                        '/usr/share/elasticsearch/jdk/bin/java',
                        '-Xms8g',
                        '-Xmx8g',
                        '-XX:+UseConcMarkSweepGC',
                        '-XX:CMSInitiatingOccupancyFraction=75',
                        '-XX:+UseCMSInitiatingOccupancyOnly',
                        '-Des.networkaddress.cache.ttl=60',
                        '-Des.networkaddress.cache.negative.ttl=10',
                        '-XX:+AlwaysPreTouch',
                        '-Xss1m',
                        '-Djava.awt.headless=true',
                        '-Dfile.encoding=UTF-8',
                        '-Djna.nosys=true',
                        '-XX:-OmitStackTraceInFastThrow',
                        '-Dio.netty.noUnsafe=true',
                        '-Dio.netty.noKeySetOptimization=true',
                        '-Dio.netty.recycler.maxCapacityPerThread=0',
                        '-Dlog4j.shutdownHookEnabled=false',
                        '-Dlog4j2.disable.jmx=true',
                        '-Djava.io.tmpdir=/tmp/elasticsearch-11139975657297362630',
                        '-XX:+HeapDumpOnOutOfMemoryError',
                        '-XX:HeapDumpPath=/var/lib/elasticsearch',
                        '-XX:ErrorFile=/var/log/elasticsearch/hs_err_pid%p.log',
                        '-Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m',
                        '-Djava.locale.providers=COMPAT',
                        '-XX:UseAVX=2',
                        '-Dio.netty.allocator.type=pooled',
                        '-XX:MaxDirectMemorySize=4294967296',
                        '-Des.path.home=/usr/share/elasticsearch',
                        '-Des.path.conf=/etc/elasticsearch',
                        '-Des.distribution.flavor=default',
                        '-Des.distribution.type=deb',
                        '-Des.bundled_jdk=true',
                        '-cp',
                        '/usr/share/elasticsearch/lib/*',
                        'org.elasticsearch.bootstrap.Elasticsearch',
                        '-p',
                        '/var/run/elasticsearch/elasticsearch.pid',
                        '--quiet',
                      ],
                      executable: ['/usr/share/elasticsearch/jdk/bin/java'],
                      title: null,
                      working_directory: null,
                      __typename: 'ProcessEcsFields',
                    },
                    zeek: null,
                    __typename: 'ECS',
                  },
                  __typename: 'TimelineItem',
                },
                __typename: 'TimelineEdges',
              },
              {
                node: {
                  _id: 'QMf8z2wBUZUjF-GHSGX9',
                  _index: 'auditbeat-8.0.0-2019.08.09-000020',
                  data: [
                    {
                      field: '_id',
                      value: ['QMf8z2wBUZUjF-GHSGX9'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: '_index',
                      value: ['auditbeat-8.0.0-2019.08.09-000020'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.action',
                      value: ['network_flow'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.category',
                      value: ['network_traffic'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.dataset',
                      value: ['newsocket'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.module',
                      value: ['system'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'host.name',
                      value: ['test-hostname'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'source.ip',
                      value: ['35.227.65.114'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'destination.ip',
                      value: ['10.1.0.10'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'user.name',
                      value: ['elasticsearch'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: '@timestamp',
                      value: ['2019-08-26T22:11:52.197Z'],
                      __typename: 'TimelineNonEcsData',
                    },
                  ],
                  ecs: {
                    _id: 'QMf8z2wBUZUjF-GHSGX9',
                    _index: 'auditbeat-8.0.0-2019.08.09-000020',
                    timestamp: '2019-08-26T22:11:52.197Z',
                    message: null,
                    system: null,
                    event: {
                      action: ['network_flow'],
                      category: ['network_traffic'],
                      created: null,
                      dataset: ['newsocket'],
                      duration: [1025557092],
                      end: ['2019-08-26T22:11:22.019Z'],
                      hash: null,
                      id: null,
                      kind: ['event'],
                      module: ['system'],
                      original: null,
                      outcome: null,
                      risk_score: null,
                      risk_score_norm: null,
                      severity: null,
                      start: ['2019-08-26T22:11:20.994Z'],
                      timezone: null,
                      type: null,
                      __typename: 'EventEcsFields',
                    },
                    auditd: null,
                    file: null,
                    host: {
                      id: ['b6d5264e4b9c8880ad1053841067a4a6'],
                      name: ['test-hostname'],
                      ip: null,
                      __typename: 'HostEcsFields',
                    },
                    source: {
                      bytes: [1714],
                      ip: ['22.33.44.114'],
                      packets: [5],
                      port: [37718],
                      geo: null,
                      __typename: 'SourceEcsFields',
                    },
                    destination: {
                      bytes: [465],
                      ip: ['10.1.0.10'],
                      packets: [4],
                      port: [9200],
                      geo: null,
                      __typename: 'DestinationEcsFields',
                    },
                    geo: null,
                    suricata: null,
                    network: {
                      bytes: [2179],
                      community_id: ['1:zSdWD8YUZhebc/12xQnQlB158Do='],
                      direction: ['inbound'],
                      packets: [9],
                      protocol: null,
                      transport: ['tcp'],
                      __typename: 'NetworkEcsField',
                    },
                    http: null,
                    tls: null,
                    url: null,
                    user: {
                      name: ['elasticsearch'],
                      __typename: 'UserEcsFields',
                    },
                    process: {
                      pid: [14216],
                      name: ['java'],
                      ppid: null,
                      args: [
                        '/usr/share/elasticsearch/jdk/bin/java',
                        '-Xms8g',
                        '-Xmx8g',
                        '-XX:+UseConcMarkSweepGC',
                        '-XX:CMSInitiatingOccupancyFraction=75',
                        '-XX:+UseCMSInitiatingOccupancyOnly',
                        '-Des.networkaddress.cache.ttl=60',
                        '-Des.networkaddress.cache.negative.ttl=10',
                        '-XX:+AlwaysPreTouch',
                        '-Xss1m',
                        '-Djava.awt.headless=true',
                        '-Dfile.encoding=UTF-8',
                        '-Djna.nosys=true',
                        '-XX:-OmitStackTraceInFastThrow',
                        '-Dio.netty.noUnsafe=true',
                        '-Dio.netty.noKeySetOptimization=true',
                        '-Dio.netty.recycler.maxCapacityPerThread=0',
                        '-Dlog4j.shutdownHookEnabled=false',
                        '-Dlog4j2.disable.jmx=true',
                        '-Djava.io.tmpdir=/tmp/elasticsearch-11139975657297362630',
                        '-XX:+HeapDumpOnOutOfMemoryError',
                        '-XX:HeapDumpPath=/var/lib/elasticsearch',
                        '-XX:ErrorFile=/var/log/elasticsearch/hs_err_pid%p.log',
                        '-Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m',
                        '-Djava.locale.providers=COMPAT',
                        '-XX:UseAVX=2',
                        '-Dio.netty.allocator.type=pooled',
                        '-XX:MaxDirectMemorySize=4294967296',
                        '-Des.path.home=/usr/share/elasticsearch',
                        '-Des.path.conf=/etc/elasticsearch',
                        '-Des.distribution.flavor=default',
                        '-Des.distribution.type=deb',
                        '-Des.bundled_jdk=true',
                        '-cp',
                        '/usr/share/elasticsearch/lib/*',
                        'org.elasticsearch.bootstrap.Elasticsearch',
                        '-p',
                        '/var/run/elasticsearch/elasticsearch.pid',
                        '--quiet',
                      ],
                      executable: ['/usr/share/elasticsearch/jdk/bin/java'],
                      title: null,
                      working_directory: null,
                      __typename: 'ProcessEcsFields',
                    },
                    zeek: null,
                    __typename: 'ECS',
                  },
                  __typename: 'TimelineItem',
                },
                __typename: 'TimelineEdges',
              },
              {
                node: {
                  _id: 'Qcf8z2wBUZUjF-GHSGX9',
                  _index: 'auditbeat-8.0.0-2019.08.09-000020',
                  data: [
                    {
                      field: '_id',
                      value: ['Qcf8z2wBUZUjF-GHSGX9'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: '_index',
                      value: ['auditbeat-8.0.0-2019.08.09-000020'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.action',
                      value: ['network_flow'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.category',
                      value: ['network_traffic'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.dataset',
                      value: ['newsocket'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.module',
                      value: ['system'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'host.name',
                      value: ['test-hostname'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'source.ip',
                      value: ['35.227.65.114'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'destination.ip',
                      value: ['10.1.0.10'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'user.name',
                      value: ['elasticsearch'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: '@timestamp',
                      value: ['2019-08-26T22:11:52.197Z'],
                      __typename: 'TimelineNonEcsData',
                    },
                  ],
                  ecs: {
                    _id: 'Qcf8z2wBUZUjF-GHSGX9',
                    _index: 'auditbeat-8.0.0-2019.08.09-000020',
                    timestamp: '2019-08-26T22:11:52.197Z',
                    message: null,
                    system: null,
                    event: {
                      action: ['network_flow'],
                      category: ['network_traffic'],
                      created: null,
                      dataset: ['newsocket'],
                      duration: [1025208619],
                      end: ['2019-08-26T22:11:22.019Z'],
                      hash: null,
                      id: null,
                      kind: ['event'],
                      module: ['system'],
                      original: null,
                      outcome: null,
                      risk_score: null,
                      risk_score_norm: null,
                      severity: null,
                      start: ['2019-08-26T22:11:20.994Z'],
                      timezone: null,
                      type: null,
                      __typename: 'EventEcsFields',
                    },
                    auditd: null,
                    file: null,
                    host: {
                      id: ['b6d5264e4b9c8880ad1053841067a4a6'],
                      name: ['test-hostname'],
                      ip: null,
                      __typename: 'HostEcsFields',
                    },
                    source: {
                      bytes: [1714],
                      ip: ['77.88.99.114'],
                      packets: [5],
                      port: [37720],
                      geo: null,
                      __typename: 'SourceEcsFields',
                    },
                    destination: {
                      bytes: [465],
                      ip: ['10.1.0.10'],
                      packets: [4],
                      port: [9200],
                      geo: null,
                      __typename: 'DestinationEcsFields',
                    },
                    geo: null,
                    suricata: null,
                    network: {
                      bytes: [2179],
                      community_id: ['1:TlQrQkJgzBs/8+U0QlInZhiWg6w='],
                      direction: ['inbound'],
                      packets: [9],
                      protocol: null,
                      transport: ['tcp'],
                      __typename: 'NetworkEcsField',
                    },
                    http: null,
                    tls: null,
                    url: null,
                    user: {
                      name: ['elasticsearch'],
                      __typename: 'UserEcsFields',
                    },
                    process: {
                      pid: [14216],
                      name: ['java'],
                      ppid: null,
                      args: [
                        '/usr/share/elasticsearch/jdk/bin/java',
                        '-Xms8g',
                        '-Xmx8g',
                        '-XX:+UseConcMarkSweepGC',
                        '-XX:CMSInitiatingOccupancyFraction=75',
                        '-XX:+UseCMSInitiatingOccupancyOnly',
                        '-Des.networkaddress.cache.ttl=60',
                        '-Des.networkaddress.cache.negative.ttl=10',
                        '-XX:+AlwaysPreTouch',
                        '-Xss1m',
                        '-Djava.awt.headless=true',
                        '-Dfile.encoding=UTF-8',
                        '-Djna.nosys=true',
                        '-XX:-OmitStackTraceInFastThrow',
                        '-Dio.netty.noUnsafe=true',
                        '-Dio.netty.noKeySetOptimization=true',
                        '-Dio.netty.recycler.maxCapacityPerThread=0',
                        '-Dlog4j.shutdownHookEnabled=false',
                        '-Dlog4j2.disable.jmx=true',
                        '-Djava.io.tmpdir=/tmp/elasticsearch-11139975657297362630',
                        '-XX:+HeapDumpOnOutOfMemoryError',
                        '-XX:HeapDumpPath=/var/lib/elasticsearch',
                        '-XX:ErrorFile=/var/log/elasticsearch/hs_err_pid%p.log',
                        '-Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m',
                        '-Djava.locale.providers=COMPAT',
                        '-XX:UseAVX=2',
                        '-Dio.netty.allocator.type=pooled',
                        '-XX:MaxDirectMemorySize=4294967296',
                        '-Des.path.home=/usr/share/elasticsearch',
                        '-Des.path.conf=/etc/elasticsearch',
                        '-Des.distribution.flavor=default',
                        '-Des.distribution.type=deb',
                        '-Des.bundled_jdk=true',
                        '-cp',
                        '/usr/share/elasticsearch/lib/*',
                        'org.elasticsearch.bootstrap.Elasticsearch',
                        '-p',
                        '/var/run/elasticsearch/elasticsearch.pid',
                        '--quiet',
                      ],
                      executable: ['/usr/share/elasticsearch/jdk/bin/java'],
                      title: null,
                      working_directory: null,
                      __typename: 'ProcessEcsFields',
                    },
                    zeek: null,
                    __typename: 'ECS',
                  },
                  __typename: 'TimelineItem',
                },
                __typename: 'TimelineEdges',
              },
              {
                node: {
                  _id: 'Qsf8z2wBUZUjF-GHSGX9',
                  _index: 'auditbeat-8.0.0-2019.08.09-000020',
                  data: [
                    {
                      field: '_id',
                      value: ['Qsf8z2wBUZUjF-GHSGX9'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: '_index',
                      value: ['auditbeat-8.0.0-2019.08.09-000020'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.action',
                      value: ['network_flow'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.category',
                      value: ['network_traffic'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.dataset',
                      value: ['newsocket'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'event.module',
                      value: ['system'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'host.name',
                      value: ['test-hostname'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'source.ip',
                      value: ['35.227.65.114'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'destination.ip',
                      value: ['10.1.0.10'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: 'user.name',
                      value: ['elasticsearch'],
                      __typename: 'TimelineNonEcsData',
                    },
                    {
                      field: '@timestamp',
                      value: ['2019-08-26T22:11:52.197Z'],
                      __typename: 'TimelineNonEcsData',
                    },
                  ],
                  ecs: {
                    _id: 'Qsf8z2wBUZUjF-GHSGX9',
                    _index: 'auditbeat-8.0.0-2019.08.09-000020',
                    timestamp: '2019-08-26T22:11:52.197Z',
                    message: null,
                    system: null,
                    event: {
                      action: ['network_flow'],
                      category: ['network_traffic'],
                      created: null,
                      dataset: ['newsocket'],
                      duration: [1057788472],
                      end: ['2019-08-26T22:11:22.051Z'],
                      hash: null,
                      id: null,
                      kind: ['event'],
                      module: ['system'],
                      original: null,
                      outcome: null,
                      risk_score: null,
                      risk_score_norm: null,
                      severity: null,
                      start: ['2019-08-26T22:11:20.993Z'],
                      timezone: null,
                      type: null,
                      __typename: 'EventEcsFields',
                    },
                    auditd: null,
                    file: null,
                    host: {
                      id: ['b6d5264e4b9c8880ad1053841067a4a6'],
                      name: ['test-hostname'],
                      ip: null,
                      __typename: 'HostEcsFields',
                    },
                    source: {
                      bytes: [1769],
                      ip: ['35.227.65.114'],
                      packets: [6],
                      port: [37714],
                      geo: null,
                      __typename: 'SourceEcsFields',
                    },
                    destination: {
                      bytes: [23993],
                      ip: ['10.1.0.10'],
                      packets: [6],
                      port: [9200],
                      geo: null,
                      __typename: 'DestinationEcsFields',
                    },
                    geo: null,
                    suricata: null,
                    network: {
                      bytes: [25762],
                      community_id: ['1:AqmAnxBJEopuNMVov0DBd4FYlXo='],
                      direction: ['inbound'],
                      packets: [12],
                      protocol: null,
                      transport: ['tcp'],
                      __typename: 'NetworkEcsField',
                    },
                    http: null,
                    tls: null,
                    url: null,
                    user: {
                      name: ['elasticsearch'],
                      __typename: 'UserEcsFields',
                    },
                    process: {
                      pid: [14216],
                      name: ['java'],
                      ppid: null,
                      args: [
                        '/usr/share/elasticsearch/jdk/bin/java',
                        '-Xms8g',
                        '-Xmx8g',
                        '-XX:+UseConcMarkSweepGC',
                        '-XX:CMSInitiatingOccupancyFraction=75',
                        '-XX:+UseCMSInitiatingOccupancyOnly',
                        '-Des.networkaddress.cache.ttl=60',
                        '-Des.networkaddress.cache.negative.ttl=10',
                        '-XX:+AlwaysPreTouch',
                        '-Xss1m',
                        '-Djava.awt.headless=true',
                        '-Dfile.encoding=UTF-8',
                        '-Djna.nosys=true',
                        '-XX:-OmitStackTraceInFastThrow',
                        '-Dio.netty.noUnsafe=true',
                        '-Dio.netty.noKeySetOptimization=true',
                        '-Dio.netty.recycler.maxCapacityPerThread=0',
                        '-Dlog4j.shutdownHookEnabled=false',
                        '-Dlog4j2.disable.jmx=true',
                        '-Djava.io.tmpdir=/tmp/elasticsearch-11139975657297362630',
                        '-XX:+HeapDumpOnOutOfMemoryError',
                        '-XX:HeapDumpPath=/var/lib/elasticsearch',
                        '-XX:ErrorFile=/var/log/elasticsearch/hs_err_pid%p.log',
                        '-Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m',
                        '-Djava.locale.providers=COMPAT',
                        '-XX:UseAVX=2',
                        '-Dio.netty.allocator.type=pooled',
                        '-XX:MaxDirectMemorySize=4294967296',
                        '-Des.path.home=/usr/share/elasticsearch',
                        '-Des.path.conf=/etc/elasticsearch',
                        '-Des.distribution.flavor=default',
                        '-Des.distribution.type=deb',
                        '-Des.bundled_jdk=true',
                        '-cp',
                        '/usr/share/elasticsearch/lib/*',
                        'org.elasticsearch.bootstrap.Elasticsearch',
                        '-p',
                        '/var/run/elasticsearch/elasticsearch.pid',
                        '--quiet',
                      ],
                      executable: ['/usr/share/elasticsearch/jdk/bin/java'],
                      title: null,
                      working_directory: null,
                      __typename: 'ProcessEcsFields',
                    },
                    zeek: null,
                    __typename: 'ECS',
                  },
                  __typename: 'TimelineItem',
                },
                __typename: 'TimelineEdges',
              },
            ],
            __typename: 'TimelineData',
          },
          __typename: 'Source',
        },
      },
    },
  },
];
