/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/**
 * Stable `data-ebt-*` wire values for `agent_builder_ui_click` / `ReportUiClickParams`.
 */
const ebtElement = {
  appRoot: 'agentBuilder.app',
  pageContent: 'agentBuilder.pageContent',
  sidebar: 'agentBuilder.sidebar',
  flyout: 'agentBuilder.flyout',
} as const;

const ebtAction = {
  navSidebar: {
    SIDEBAR_LAYER_TRANSITION: 'sidebar_layer_transition',
    SIDEBAR_NAVIGATION_CLICK: 'sidebar_navigation_click',
    SIDEBAR_TOGGLE: 'sidebar_toggle',
    AGENT_SWITCH: 'agent_switch',
    AGENT_SELECTOR_OPEN: 'agent_selector_open',
    MANAGE_ALL_AGENTS_CLICK: 'manage_all_agents_click',
    NEW_AGENT: 'new_agent',
  },
  conversationList: {
    CONVERSATION_START: 'conversation_start',
    CONVERSATION_RESUME: 'conversation_resume',
    CONVERSATION_SEARCH: 'conversation_search',
    OPEN_CONVERSATION_MENU: 'open_conversation_menu',
    RENAME_CONVERSATION: 'rename_conversation',
    DELETE_CONVERSATION: 'delete_conversation',
    MARK_AS_READ: 'mark_as_read',
    MARK_AS_UNREAD: 'mark_as_unread',
  },
  agentCustomization: {
    ENTITY_ADD_FROM_LIBRARY: 'entity_add_from_library',
    ENTITY_CREATE_NEW: 'entity_create_new',
    ENTITY_REMOVE: 'entity_remove',
    ENTITY_DETAIL_VIEW: 'entity_detail_view',
    ENTITY_EDIT_FROM_AGENT: 'entity_edit_from_agent',
  },
  globalManagement: {
    MANAGE_ENTITY_EDIT: 'manage_entity_edit',
    MANAGE_ENTITY_DELETE: 'manage_entity_delete',
    MANAGE_ENTITY_VIEW: 'manage_entity_view',
    MANAGE_ENTITY_CLONE: 'manage_entity_clone',
    MANAGE_ENTITY_TEST: 'manage_entity_test',
    OPEN_CONTEXT_MENU: 'open_context_menu',
    NEW_SKILL: 'new_skill',
    NEW_TOOL: 'new_tool',
    MANAGE_AGENTS_LINK: 'manage_agents_link',
    LEARN_MORE_DOCS: 'learn_more_docs',
    BULK_DELETE: 'bulk_delete',
    SELECT_ALL: 'select_all',
    CLEAR_SELECTION: 'clear_selection',
    INSTALL_PLUGIN: 'install_plugin',
    INSTALL_FROM_URL: 'install_from_url',
    UPLOAD_PLUGIN: 'upload_plugin',
    BACK_TO_LIST: 'back_to_list',
    MANAGE_MCP: 'manage_mcp',
    COPY_MCP_URL: 'copy_mcp_url',
    BULK_IMPORT_MCP: 'bulk_import_mcp',
    MANAGE_MCP_CLIENTS: 'manage_mcp_clients',
    MCP_DOCS: 'mcp_docs',
    ADD_REFERENCED_FILE: 'add_referenced_file',
    REMOVE_REFERENCED_FILE: 'remove_referenced_file',
    TOOL_CANCEL: 'tool_cancel',
    TEST_TOOL: 'test_tool',
    SAVE_AND_TEST_TOOL: 'save_and_test_tool',
    TOOL_TEST_SUBMIT: 'tool_test_submit',
    TOOL_TEST_DOCS: 'tool_test_docs',
    PLUGIN_SOURCE_LINK: 'plugin_source_link',
    PLUGIN_SKILL_LINK: 'plugin_skill_link',
    BULK_IMPORT_SUBMIT: 'bulk_import_submit',
    BULK_IMPORT_CANCEL: 'bulk_import_cancel',
    INSTALL_FROM_URL_SUBMIT: 'install_from_url_submit',
    INSTALL_FROM_URL_CANCEL: 'install_from_url_cancel',
    UPLOAD_PLUGIN_SUBMIT: 'upload_plugin_submit',
    UPLOAD_PLUGIN_CANCEL: 'upload_plugin_cancel',
    ADD_PARAM: 'add_param',
    REMOVE_PARAM: 'remove_param',
    INFER_PARAMS: 'infer_params',
    MV_CONTAINS_DOCS: 'mv_contains_docs',
    ADD_MCP_SERVER: 'add_mcp_server',
    VIEW_CONNECTORS: 'view_connectors',
  },
  inappChat: {
    OPEN_FULLSCREEN: 'inapp_open_fullscreen',
    AGENT_SWITCH: 'inapp_agent_switch',
  },
  agentList: {
    AGENT_CREATE: 'agent_create',
    AGENT_EDIT: 'agent_edit',
    AGENT_DELETE: 'agent_delete',
    LEARN_MORE_DOCS: 'learn_more_docs',
  },
  agentOverview: {
    COPY_ID: 'copy_agent_id',
    EDIT_DETAILS: 'edit_agent_details',
    DOCS_LINK: 'docs_link',
    DESCRIPTION_TOGGLE: 'description_toggle',
    ELASTIC_CAPABILITIES_TOGGLE: 'elastic_capabilities_toggle',
    EDIT_FLYOUT_SAVE: 'form_save',
    EDIT_FLYOUT_CANCEL: 'form_cancel',
  },
  agentEdit: {
    SAVE: 'form_save',
    SAVE_AND_CHAT: 'save_and_chat',
    CHAT: 'agent_chat',
    CANCEL: 'form_cancel',
    CLONE: 'agent_clone',
    DELETE: 'agent_delete',
    OPEN_MENU: 'open_menu',
    BACK_TO_LIST: 'back_to_list',
    LEARN_MORE_DOCS: 'learn_more_docs',
    MANAGE_ALL: 'manage_all',
    TOOLS_LINK: 'tools_link',
    SHOW_ACTIVE_ONLY: 'show_active_only',
  },
  access: {
    CONNECT_LLM: 'connect_llm',
    LEARN_MORE_DOCS: 'learn_more_docs',
    SUBSCRIPTION_PLANS: 'subscription_plans',
    MANAGE_LICENSE: 'manage_license',
  },
  connectors: {
    CREATE_CONNECTOR: 'create_connector',
    OPEN_CONTEXT_MENU: 'open_context_menu',
    EDIT_CONNECTOR: 'edit_connector',
    DISCONNECT_CONNECTOR: 'disconnect_connector',
    DELETE_CONNECTOR: 'delete_connector',
    DISCONNECT_CONFIRM: 'disconnect_confirm',
    DISCONNECT_CANCEL: 'disconnect_cancel',
    OAUTH_CONNECT: 'oauth_connect',
  },
  conversation: {
    START_NEW: 'start_new',
    CLOSE: 'close',
    OPEN_TITLE_MENU: 'open_title_menu',
    RENAME: 'rename',
    DELETE: 'delete',
    RENAME_SAVE: 'rename_save',
    RENAME_CANCEL: 'rename_cancel',
    OPEN_MORE_ACTIONS: 'open_more_actions',
    AGENT_DETAILS: 'agent_details',
    GENAI_SETTINGS: 'genai_settings',
    ADD_TO_DATASET: 'add_to_dataset',
    SUBMIT: 'submit',
    CANCEL: 'cancel',
    OPEN_CONNECTOR_SELECTOR: 'open_connector_selector',
    MANAGE_CONNECTORS: 'manage_connectors',
    COPY_RESPONSE: 'copy_response',
    REGENERATE: 'regenerate',
    THINKING_TOGGLE: 'thinking_toggle',
    VIEW_JSON: 'view_json',
    VIEW_TRACE: 'view_trace',
    ROUND_ADD_TO_DATASET: 'round_add_to_dataset',
    RETRY: 'retry',
    STALE_USE_UPDATED: 'stale_use_updated',
    STALE_DISMISS: 'stale_dismiss',
    SCROLL_DOWN: 'scroll_down',
    OPEN_EMBEDDABLE_MENU: 'open_embeddable_menu',
    NEW_CHAT: 'new_chat',
    SWITCH_TO_AGENTS: 'switch_to_agents',
    BACK_TO_CONVERSATIONS: 'back_to_conversations',
    EMBEDDABLE_AGENT_DETAILS: 'embeddable_agent_details',
    REMOVE_ATTACHMENT: 'remove_attachment',
    ATTACHMENT_CLOSE: 'attachment_close',
    CONFIRM_PROMPT_CONFIRM: 'confirm_prompt_confirm',
    CONFIRM_PROMPT_CANCEL: 'confirm_prompt_cancel',
    AUTH_PROMPT_AUTHORIZE: 'auth_prompt_authorize',
    AUTH_PROMPT_CANCEL: 'auth_prompt_cancel',
    DELETE_CONFIRM: 'delete_confirm',
    DELETE_CANCEL: 'delete_cancel',
    EXTERNAL_LINK_CONFIRM: 'external_link_confirm',
    EXTERNAL_LINK_CANCEL: 'external_link_cancel',
    OPEN_ROUND_METADATA: 'open_round_metadata',
    EXPAND_TOOL_CALL_STEP: 'expand_tool_call_step',
    EXPAND_TOOL_CALL_GROUP: 'expand_tool_call_group',
    VIEW_TOOL_RESPONSE: 'view_tool_response',
    VIEW_SUB_AGENT_EXECUTION: 'view_sub_agent_execution',
    OPEN_ESQL_IN_DISCOVER: 'open_esql_in_discover',
  },
  libraryPanel: {
    MANAGE_ALL: 'manage_all',
    VIEW_IN_LIBRARY: 'view_in_library',
    SORT_FILTER_OPEN: 'library_sort_filter_open',
    SORT_ASC: 'sort_asc',
    SORT_DESC: 'sort_desc',
    FILTER_ALL: 'filter_all',
    FILTER_ACTIVE: 'filter_active',
    FILTER_ELASTIC: 'filter_elastic',
    FILTER_CUSTOM: 'filter_custom',
    EMPTY_STATE_OPEN_LIBRARY: 'empty_state_open_library',
    EMPTY_STATE_MANAGE_ALL: 'empty_state_manage_all',
    CROSS_NAV_LINK: 'cross_nav_link',
    FLYOUT_SAVE: 'form_save',
    FLYOUT_CANCEL: 'form_cancel',
    SKILL_TOOL_CLICK: 'skill_tool_click',
    INSTALL_PLUGIN_TAB: 'install_plugin_tab',
    INSTALL_PLUGIN_SUBMIT: 'install_plugin_submit',
    LEARN_MORE_DOCS: 'learn_more_docs',
  },
} as const;

const ebtDetail = {
  layerTransition: {
    MANAGE_CLICK: 'manage_click',
    BACK_CLICK: 'back_click',
  },
  sidebarToggle: {
    EXPAND: 'expand',
    CONDENSE: 'condense',
  },
} as const;

const ebtEntity = {
  TOOL: 'tool',
  PLUGIN: 'plugin',
  SKILL: 'skill',
  AGENT: 'agent',
} as const;
const ebtFormat = {} as const;

export const AGENT_BUILDER_UI_EBT = {
  element: ebtElement,
  action: ebtAction,
  detail: ebtDetail,
  entity: ebtEntity,
  format: ebtFormat,
} as const;

export type AgentBuilderUiEbt = typeof AGENT_BUILDER_UI_EBT;
