[[saved-objects-api-bulk-get]]
=== Bulk get objects API
++++
<titleabbrev>Bulk get objects</titleabbrev>
++++

experimental[] Retrieve multiple {kib} saved objects by ID.

[[saved-objects-api-bulk-get-request]]
==== Request

`POST <kibana host>:<port>/api/saved_objects/_bulk_get`

`POST <kibana host>:<port>/s/<space_id>/api/saved_objects/_bulk_get`

[[saved-objects-api-bulk-get-path-params]]
==== Path parameters

`space_id`::
  (Optional, string) An identifier for the space. If `space_id` is not provided in the URL, the default space is used.

[[saved-objects-api-bulk-get-request-body]]
==== Request Body

`type`::
  (Required, string) Valid options include `visualization`, `dashboard`, `search`, `index-pattern`, `config`, and `timelion-sheet`.

`id`::
  (Required, string) ID of the retrieved object. The ID includes the {kib} unique identifier or a custom identifier.

`fields`::
  (Optional, array) The fields returned in the object response.

[[saved-objects-api-bulk-get-response-body]]
==== Response body

`saved_objects`::
  (array) Top-level property containing objects that represent the response for each of the requested objects. The order of the objects in the response is identical to the order of the objects in the request.

Saved objects that are unable to persist are replaced with an error object.

[[saved-objects-api-bulk-get-body-codes]]
==== Response code

`200`::
  Indicates a successful call.

[[saved-objects-api-bulk-get-body-example]]
==== Example

Retrieve an index pattern with the `my-pattern` ID, and a dashboard with the `my-dashboard` ID:

[source,sh]
--------------------------------------------------
$ curl -X POST "localhost:5601/api/saved_objects/_bulk_get"
[
  {
    "type": "index-pattern",
    "id": "my-pattern"
  },
  {
    "type": "dashboard",
    "id": "be3733a0-9efe-11e7-acb3-3dab96693fab"
  }
]
--------------------------------------------------
// KIBANA

The API returns the following:

[source,sh]
--------------------------------------------------
{
  "saved_objects": [
    {
      "id": "my-pattern",
      "type": "index-pattern",
      "version": 1,
      "attributes": {
        "title": "my-pattern-*"
      }
    },
    {
      "id": "my-dashboard",
      "type": "dashboard",
      "error": {
        "statusCode": 404,
        "message": "Not found"
      }
    }
  ]
}
--------------------------------------------------

Only the index pattern exists.
