[[saved-objects-api-bulk-get]]
=== Bulk get objects API
++++
<titleabbrev>Bulk get objects</titleabbrev>
++++

Retrieves multiple {kib} saved objects by ID.

experimental[This functionality is *experimental* and may be changed or removed completely in a future release.]

[[saved-objects-api-bulk-get-request]]
==== Request

`POST /api/saved_objects/_bulk_get`

[[saved-objects-api-bulk-get-request-body]]
==== Request Body

`type`::
  (Required, string) Valid options include `visualization`, `dashboard`, `search`, `index-pattern`, `config`, and `timelion-sheet`.

`id`::
  (Required, string) ID of the retrieved object.

`fields`::
  (Optional, array) The fields returned in the object response.
  
[[saved-objects-api-bulk-get-response-body]]
==== Response body

`saved_objects`:: 
  (array) Top-level property the contains objects that represent the response for each of the requested objects. The order of the objects in the response is identical to the order of the objects in the request.

Saved objects that are unable to persist are replaced with an error object.

[[saved-objects-api-bulk-get-body-codes]]
==== Response code

`200`:: 
  Indicates a successfully call.

[[saved-objects-api-bulk-get-body-example]]
==== Example

Retrieve an index pattern with the `my-pattern` ID, and a dashboard with the `my-dashboard` ID: 

[source,js]
--------------------------------------------------
POST api/saved_objects/_bulk_get
[
  {
    "type": "index-pattern",
    "id": "my-pattern"
  },
  {
    "type": "dashboard",
    "id": "my-dashboard"
  }
]
--------------------------------------------------
// KIBANA

The API returns the following:

[source,js]
--------------------------------------------------
{
  "saved_objects": [
    {
      "id": "my-pattern",
      "type": "index-pattern",
      "version": 1,
      "attributes": {
        "title": "my-pattern-*"
      }
    },
    {
      "id": "my-dashboard",
      "type": "dashboard",
      "error": {
        "statusCode": 404,
        "message": "Not found"
      }
    }
  ]
}
--------------------------------------------------

Only the index pattern exists.
