[[saved-objects-api-create]]
=== Create Object

experimental[This functionality is experimental and may be changed or removed completely in a future release.]

The create Saved Object API enables you to persist a Kibana object.

==== Request

`PUT /api/saved_objects/<type>` +

`PUT /api/saved_objects/<type>/<id>`

==== Path Parameters

`type` (required)::
  (string) Valid options, include: `visualization`, `dashboard`, `search`, `config`, and `timelion-sheet`

`id` (optional)::
  (string) Enables specifying an ID to use, as opposed to one being randomly generated


==== Query Parameters

`overwrite` (optional)::
  (boolean) If true, will overwrite the document with the same ID.


==== Request Body

`attributes`::
  (object) The data to persist


==== Examples

The following example calls creates an index pattern object with a pattern of `my-pattern-*`

[source,js]
--------------------------------------------------
POST api/saved_objects/index-pattern/my-pattern
{
  "attributes": {
    "title": "my-pattern-*"
  }
}
--------------------------------------------------
// KIBANA

A successful call returns a JSON structure similar to the following example:

[source,js]
--------------------------------------------------
{
  "id": "my-pattern", <1>
  "type": "index-pattern",
  "version": 1,
  "attributes": {
    "title": "my-pattern"
  }
}⏎
--------------------------------------------------

<1> If omitted from the path, a unique ID would have been generated.