[[saved-objects-api-delete]]
=== Delete Object

beta["This functionality is *beta*. It's on track to become a stable, permanent feature of {kib}. Caution should be exercised because it is possible a breaking change to these APIs will occur in a minor version, but we’ll avoid this wherever possible."]

The delete saved object API permanently removes a Kibana saved object. Once a
saved object has been deleted, _it cannot be recovered_.

Note: You cannot access this endpoint via the Console in Kibana.

==== Request

`DELETE /api/saved_objects/<type>/<id>`

==== Path Parameters

`type` (required)::
  (string) Valid options, include: `visualization`, `dashboard`, `search`, `index-pattern`, `config`, and `timelion-sheet`

`id` (required)::
  (string) Object ID being removed


==== Examples

The following example deletes an index pattern object with an ID of `my-pattern`

[source,js]
--------------------------------------------------
DELETE api/saved_objects/index-pattern/my-pattern
--------------------------------------------------
// KIBANA

A successful call returns a response code of `200`.
