[[saved-objects-api-export]]
=== Export objects API
++++
<titleabbrev>Export objects</titleabbrev>
++++

experimental[] Retrieve sets of saved objects that you want to import into {kib}.

[[saved-objects-api-export-request]]
==== Request

`POST <kibana host>:<port>/api/saved_objects/_export`

`POST <kibana host>:<port>/s/<space_id>/api/saved_objects/_export`

[[saved-objects-api-export-path-params]]
==== Path parameters

`space_id`::
  (Optional, string) An identifier for the space. When `space_id` is not provided in the URL, the default space is used.

[[saved-objects-api-export-request-request-body]]
==== Request body

`type`::
  (Required, array|string) The saved object types to include in the export.

`objects`::
  (Required, array) A list of objects to export.

`includeReferencesDeep`::
  (Optional, boolean) Includes all referenced objects in the exported objects.

`excludeExportDetails`::
  (Optional, boolean) Specifies to exclude the export details at the end of the stream.

TIP: To limit the number of exported saved objects, configure <<savedObjects-maxImportExportSize, `savedObjects.maxImportExportSize`>>.

[[saved-objects-api-export-request-response-body]]
==== Response body

Each exported object is exported as a valid JSON record and separated by '\n'. When `excludeExportDetails` is `false`, the export details appear after the saved object details in the record. The `excludeExportDetails` default is `false`.

The record appears in the following NDJSON format:

[source,json]
--------------------------------------------------
{
  "exportedCount": 27,
  "missingRefCount": 2,
  "missingReferences": [
    { "id": "an-id", "type": "visualisation"},
    { "id": "another-id", "type": "index-pattern"}
  ]
}
--------------------------------------------------

TIP: When you export dashboard saved objects, you must specify all references.

[[export-objects-api-create-request-codes]]
==== Response code

`200`::
    Indicates a successful call.

[[ssaved-objects-api-create-example]]
==== Examples

Export all {data-source} saved objects:

[source,sh]
--------------------------------------------------
$ curl -X POST api/saved_objects/_export -H 'kbn-xsrf: true' -H 'Content-Type: application/json' -d '
{
  "type": "index-pattern"
}'
--------------------------------------------------
// KIBANA

Export all {data-source} saved objects and exclude the export summary from the stream:

[source,sh]
--------------------------------------------------
$ curl -X POST api/saved_objects/_export -H 'kbn-xsrf: true' -H 'Content-Type: application/json' -d '
{
  "type": "index-pattern",
  "excludeExportDetails": true
}'
--------------------------------------------------
// KIBANA

Export a saved object:

[source,sh]
--------------------------------------------------
$ curl -X POST api/saved_objects/_export -H 'kbn-xsrf: true' -H 'Content-Type: application/json' -d '
{
  "objects": [
    {
      "type": "dashboard",
      "id": "be3733a0-9efe-11e7-acb3-3dab96693fab"
    }
  ]
}'
--------------------------------------------------
// KIBANA

Export a saved object and all related objects:

[source,sh]
--------------------------------------------------
$ curl -X POST api/saved_objects/_export -H 'kbn-xsrf: true' -H 'Content-Type: application/json' -d '
{
  "objects": [
    {
      "type": "dashboard",
      "id": "be3733a0-9efe-11e7-acb3-3dab96693fab"
    }
  ],
  "includeReferencesDeep": true
}'
--------------------------------------------------
// KIBANA
