[[saved-objects-api-export-by-type]]
=== Export Objects By Type

experimental[This functionality is *experimental* and may be changed or removed completely in a future release.]

The export saved objects by type API enables you to retrieve a set of saved objects that can later be imported into Kibana.

Note: You cannot access this endpoint via the Console in Kibana.

==== Request

`POST /api/saved_objects/_export_by_type/{type}`

==== Response body

The response body will have a format of newline delimited JSON. The order of these objects is not guaranteed other than having dependencies defined first.

==== Examples

The following example exports all index pattern and visualization saved objects.

[source,js]
--------------------------------------------------
POST api/saved_objects/_export_by_type/index-pattern,visualization
--------------------------------------------------
// KIBANA

A successful call returns a response code of `200` along with the exported objects as the response body.
