
[[saved-objects-api-export]]
=== Export Objects

experimental[This functionality is *experimental* and may be changed or removed completely in a future release.]

The export saved object API enables you to retrieve a set of Kibana saved objects by various conditions into a newline delimited JSON format.

Note: You cannot access this endpoint via the Console in Kibana.

==== Request

`GET /api/saved_objects/_export`

==== Query Parameters
`type` (optional)::
  (array|string) The saved object type(s) that the export should be limited to
`objects` (optional)::
  (array) A list of objects to export

==== Response body

The response body will have a format of newline delimited JSON. The order of these objects is not guaranteed other than having dependencies defined first.

==== Examples

The following example attempts to export index patterns

[source,js]
--------------------------------------------------
GET api/saved_objects/_export?type=index-patterns
--------------------------------------------------
// KIBANA

A successful call returns a response code of `200` along with the exported objects as the response body.
