[[saved-objects-api-get]]
=== Get Object

beta["This functionality is *beta*. It's on track to become a stable, permanent feature of {kib}. Caution should be exercised because it is possible a breaking change to these APIs will occur in a minor version, but we’ll avoid this wherever possible."]

The get saved object API enables you to retrieve a single Kibana saved object
by id.

Note: You cannot access this endpoint via the Console in Kibana.

==== Request

`GET /api/saved_objects/<type>/<id>`

==== Path Parameters

`type` (required)::
  (string) Valid options, include: `visualization`, `dashboard`, `search`, `index-pattern`, `config`, and `timelion-sheet`

`id` (required)::
  (string) ID of object to retrieve


==== Examples

The following example retrieves the index pattern object with an id of
`my-pattern`.

[source,js]
--------------------------------------------------
GET api/saved_objects/index-pattern/my-pattern
--------------------------------------------------
// KIBANA

A successful call returns a response code of `200` and a response body
containing a JSON structure similar to the following example:

[source,js]
--------------------------------------------------
{
  "id": "my-pattern",
  "type": "index-pattern",
  "version": 1,
  "attributes": {
    "title": "my-pattern-*"
  }
}
--------------------------------------------------
