[[saved-objects-api-import]]
=== Import objects

experimental[This functionality is *experimental* and may be changed or removed completely in a future release.]

The import saved object API enables you to create a set of Kibana saved objects.

Note: You cannot access this endpoint via the Console in Kibana.

==== Request

`POST /api/saved_objects/_import`

==== Request Body
`overwriteAll` (optional)::
  (boolean) Overwrite all saved objects in the scenario there's a conflict

`overwrites` (optional)::
  (array) A list of objects allows to be overwritten

`replaceReferences` (optional)::
  (array) A list of { type, from, to } to replace references in saved objects.

`skips` (optional)::
  (array) A list of objects to skip importing

==== Response body

The response body will have a top level `success` property that indicates
if the import was successful or not. In the scenario the import wasn't successful
a top level `errors` array will contain the objects that failed to import.

==== Examples

The following example attemps to import an index pattern and dashboard.

[source,js]
--------------------------------------------------
POST api/saved_bojects/_import
Content-Type: multipart/form-data; boundary=EXAMPLE
--EXAMPLE
Content-Disposition: form-data; name="file"; filename="export.ndjson"
Content-Type: application/ndjson

{"type":"index-pattern","id":"my-pattern","attributes":{"title":"my-pattern-*"}}
{"type":"dashboard","id":"my-dashboard","attributes":{"title":"Look at my dashboard"}}
--EXAMPLE---
--------------------------------------------------
// KIBANA

A successful call returns a response code of `200` and a response body
containing a JSON structure similar to the following example:

[source,js]
--------------------------------------------------
{
  "success": true
}
--------------------------------------------------
