/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Set attacks assignees API endpoint
 *   version: 2023-10-31
 */

import { z, lazySchema } from '@kbn/zod/v4';

import { AlertIds } from '../../../model/alert.gen';
import { AlertAssignees } from '../../model/set_alert_assignees_body.gen';
import { UpdateRelatedAlerts } from '../common/attacks.gen';

export const SetAttacksAssigneesByIds = lazySchema(() =>
  z.object({
    ids: AlertIds,
    assignees: AlertAssignees,
    update_related_alerts: UpdateRelatedAlerts.optional(),
  })
);
export type SetAttacksAssigneesByIds = z.infer<typeof SetAttacksAssigneesByIds>;

/**
 * Set attacks assignees by IDs request
 */
export const SetAttacksAssigneesRequestBody = lazySchema(() => SetAttacksAssigneesByIds);
export type SetAttacksAssigneesRequestBody = z.infer<typeof SetAttacksAssigneesRequestBody>;
export type SetAttacksAssigneesRequestBodyInput = z.input<typeof SetAttacksAssigneesRequestBody>;

/**
 * Elasticsearch update by query response
 */
export const SetAttacksAssigneesResponse = lazySchema(() => z.object({}).catchall(z.unknown()));
export type SetAttacksAssigneesResponse = z.infer<typeof SetAttacksAssigneesResponse>;
