[role="xpack"]
[[apm-getting-started]]
== Get started with APM

++++
<titleabbrev>Get started</titleabbrev>
++++

Elastic APM captures different types of information from within instrumented applications:

* *Spans* contain information about a specific code path that has been executed.
They measure from the start to end of an activity,
and they can have a parent/child relationship with other spans.
* *Transactions* are a special kind of span that have extra metadata associated with them.
You can think of transactions as the highest level of work you’re measuring within a service.
As an example, a transaction could be a request to your server, a batch job, or a custom transaction type.
* *Errors* contain information about the original exception that occurred or about a log created when the exception occurred.

TIP: Want to learn more about the Elastic APM ecosystem?
See the {apm-get-started-ref}/overview.html[APM Overview].

Each of these information types have a specific page associated with them in the APM app.
These various pages display the captured data in curated charts and tables that allow you to easily compare and debug your applications.

* <<services>>
* <<traces>>
* <<transactions>>
* <<spans>>
* <<errors>>
* <<metrics>>
* <<service-maps>>

include::services.asciidoc[]

include::traces.asciidoc[]

include::transactions.asciidoc[]

include::spans.asciidoc[]

include::errors.asciidoc[]

include::metrics.asciidoc[]

include::service-maps.asciidoc[]
