/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Delete Attack Discovery Schedule Internal API endpoint
 *   version: 2023-10-31
 */

import { z, lazySchema } from '@kbn/zod/v4';

import { NonEmptyString } from '../../../common_attributes.gen';

export const DeleteAttackDiscoveryScheduleRequestParams = lazySchema(() =>
  z.object({
    /**
     * The unique identifier of the schedule to delete
     */
    id: NonEmptyString.describe('The unique identifier of the schedule to delete'),
  })
);
export type DeleteAttackDiscoveryScheduleRequestParams = z.infer<
  typeof DeleteAttackDiscoveryScheduleRequestParams
>;
export type DeleteAttackDiscoveryScheduleRequestParamsInput = z.input<
  typeof DeleteAttackDiscoveryScheduleRequestParams
>;

export const DeleteAttackDiscoveryScheduleResponse = lazySchema(() =>
  z.object({
    /**
     * The unique identifier of the deleted schedule
     */
    id: NonEmptyString.describe('The unique identifier of the deleted schedule'),
  })
);
export type DeleteAttackDiscoveryScheduleResponse = z.infer<
  typeof DeleteAttackDiscoveryScheduleResponse
>;
