/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { KbApiDefinition } from '../types'

export const dataStreamsApis: KbApiDefinition[] = [
  {
    name: "get-fleet-data-streams",
    namespace: "data-streams",
    description: "Get data streams",
    method: "GET",
    path: "/api/fleet/data_streams",
  },
  {
    name: "get-fleet-epm-data-streams",
    namespace: "data-streams",
    description: "Get data streams",
    method: "GET",
    path: "/api/fleet/epm/data_streams",
    queryParams: [
    { name: "type", type: "string", description: "" },
    { name: "datasetQuery", type: "string", description: "" },
    { name: "sortOrder", type: "string", description: "" },
    { name: "uncategorisedOnly", type: "boolean", description: "" },
    ],
  },
]
