/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { KbApiDefinition } from '../types'

export const securityDetectionsApiApis: KbApiDefinition[] = [
  {
    name: "read-privileges",
    namespace: "security-detections-api",
    description: "Returns user privileges for the Kibana space",
    method: "GET",
    path: "/api/detection_engine/privileges",
  },
  {
    name: "delete-rule",
    namespace: "security-detections-api",
    description: "Delete a detection rule",
    method: "DELETE",
    path: "/api/detection_engine/rules",
    queryParams: [
    { name: "id", type: "string", description: "The rule's `id` value." },
    { name: "rule_id", type: "string", description: "The rule's `rule_id` value." },
    ],
  },
  {
    name: "read-rule",
    namespace: "security-detections-api",
    description: "Retrieve a detection rule",
    method: "GET",
    path: "/api/detection_engine/rules",
    queryParams: [
    { name: "id", type: "string", description: "The rule's `id` value." },
    { name: "rule_id", type: "string", description: "The rule's `rule_id` value." },
    ],
  },
  {
    name: "patch-rule",
    namespace: "security-detections-api",
    description: "Patch a detection rule",
    method: "PATCH",
    path: "/api/detection_engine/rules",
  },
  {
    name: "create-rule",
    namespace: "security-detections-api",
    description: "Create a detection rule",
    method: "POST",
    path: "/api/detection_engine/rules",
  },
  {
    name: "update-rule",
    namespace: "security-detections-api",
    description: "Update a detection rule",
    method: "PUT",
    path: "/api/detection_engine/rules",
  },
  {
    name: "perform-rules-bulk-action",
    namespace: "security-detections-api",
    description: "Apply a bulk action to detection rules",
    method: "POST",
    path: "/api/detection_engine/rules/_bulk_action",
    queryParams: [
    { name: "dry_run", cliFlag: "kb-dry-run", type: "boolean", description: "Enables dry run mode for the request call." },
    ],
  },
  {
    name: "export-rules",
    namespace: "security-detections-api",
    description: "Export detection rules",
    method: "POST",
    path: "/api/detection_engine/rules/_export",
    queryParams: [
    { name: "exclude_export_details", type: "boolean", description: "Determines whether a summary of the exported rules is returned." },
    { name: "file_name", type: "string", description: "File name for saving the exported rules." },
    ],
    bodyParams: [
    { name: "objects", type: "array", description: "Array of objects with a rule's `rule_id` field. Do not use rule's `id` here. Exports all rules when unspecified.", required: true },
    ],
  },
  {
    name: "find-rules",
    namespace: "security-detections-api",
    description: "List all detection rules",
    method: "GET",
    path: "/api/detection_engine/rules/_find",
    queryParams: [
    { name: "fields", type: "string", description: "" },
    { name: "filter", type: "string", description: "Search query" },
    { name: "sort_field", type: "string", description: "Field to sort by" },
    { name: "sort_order", type: "string", description: "Sort order" },
    { name: "page", type: "number", description: "Page number" },
    { name: "per_page", type: "number", description: "Rules per page" },
    { name: "gaps_range_start", type: "string", description: "Gaps range start" },
    { name: "gaps_range_end", type: "string", description: "Gaps range end" },
    { name: "gap_fill_statuses", type: "string", description: "Gap fill statuses" },
    { name: "gap_auto_fill_scheduler_id", type: "string", description: "Gap auto fill scheduler ID used to determine gap fill status for rules" },
    ],
  },
  {
    name: "import-rules",
    namespace: "security-detections-api",
    description: "Import detection rules",
    method: "POST",
    path: "/api/detection_engine/rules/_import",
    queryParams: [
    { name: "overwrite", type: "boolean", description: "Determines whether existing rules with the same `rule_id` are overwritten." },
    { name: "overwrite_exceptions", type: "boolean", description: "Determines whether existing exception lists with the same `list_id` are overwritten. Both the exception list container and its items are overwritten." },
    { name: "overwrite_action_connectors", type: "boolean", description: "Determines whether existing actions with the same `kibana.alert.rule.actions.id` are overwritten." },
    { name: "as_new_list", type: "boolean", description: "Generates a new list ID for each imported exception list." },
    ],
  },
  {
    name: "rule-preview",
    namespace: "security-detections-api",
    description: "Preview rule alerts generated on specified time range",
    method: "POST",
    path: "/api/detection_engine/rules/preview",
    queryParams: [
    { name: "enable_logged_requests", type: "boolean", description: "Enables logging and returning in response ES queries, performed during rule execution" },
    ],
  },
  {
    name: "set-alert-assignees",
    namespace: "security-detections-api",
    description: "Assign and unassign users from detection alerts",
    method: "POST",
    path: "/api/detection_engine/signals/assignees",
    bodyParams: [
    { name: "assignees", type: "object", description: "", required: true },
    { name: "ids", type: "array", description: "A list of alerts `id`s.", required: true },
    ],
  },
  {
    name: "search-alerts",
    namespace: "security-detections-api",
    description: "Find and/or aggregate detection alerts",
    method: "POST",
    path: "/api/detection_engine/signals/search",
    bodyParams: [
    { name: "_source", type: "string", description: "" },
    { name: "aggs", type: "object", description: "" },
    { name: "fields", type: "array", description: "" },
    { name: "query", type: "object", description: "" },
    { name: "runtime_mappings", type: "object", description: "" },
    { name: "size", type: "number", description: "" },
    { name: "sort", type: "string", description: "" },
    { name: "track_total_hits", type: "boolean", description: "" },
    ],
  },
  {
    name: "set-alerts-status",
    namespace: "security-detections-api",
    description: "Set a detection alert status",
    method: "POST",
    path: "/api/detection_engine/signals/status",
  },
  {
    name: "set-alert-tags",
    namespace: "security-detections-api",
    description: "Add and remove detection alert tags",
    method: "POST",
    path: "/api/detection_engine/signals/tags",
    bodyParams: [
    { name: "ids", type: "array", description: "A list of alerts `id`s.", required: true },
    { name: "tags", type: "object", description: "Object with list of tags to add and remove.", required: true },
    ],
  },
  {
    name: "read-tags",
    namespace: "security-detections-api",
    description: "List all detection rule tags",
    method: "GET",
    path: "/api/detection_engine/tags",
  },
]
