/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

import type { DataStreamManifestVar } from './types';

const FILESTREAM_VARS: DataStreamManifestVar[] = [
  {
    name: 'paths',
    type: 'text',
    title: 'Paths',
    multi: true,
    required: true,
    show_user: true,
    default: ['/test/path'],
    description: 'The full path to the related log file.',
  },
  {
    name: 'compression_gzip',
    type: 'bool',
    title: 'Enable gzip compression',
    required: false,
    show_user: false,
    default: false,
    description: 'Enable automatic gzip decompression of log files.',
  },
  {
    name: 'recursive_glob',
    type: 'bool',
    title: 'Recursive Glob',
    required: false,
    show_user: false,
    description: 'Enable expanding ** into a recursive glob pattern.',
  },
  {
    name: 'exclude_files',
    type: 'text',
    title: 'Exclude Files',
    description:
      'A list of regular expressions to match the files that you want Filebeat to ignore.',
    multi: true,
    required: false,
    show_user: true,
    default: ['\\.gz$'],
  },
  {
    name: 'include_files',
    type: 'text',
    title: 'Include Files',
    description:
      'A list of regular expressions to match the files that you want Filebeat to collect.',
    multi: true,
    required: false,
    show_user: false,
  },
  {
    name: 'symlinks',
    type: 'bool',
    title: 'Symlinks',
    required: false,
    show_user: false,
    description: 'Enable symlink support.',
  },
  {
    name: 'resend_on_touch',
    type: 'bool',
    title: 'Resend On Touch',
    required: false,
    show_user: false,
    description: 'Re-send a file when its metadata changes (e.g., when a file is touched).',
  },
  {
    name: 'check_interval',
    type: 'text',
    title: 'Check Interval',
    required: false,
    show_user: false,
    description:
      'How often the prospector checks for new files in the paths that are specified for harvesting.',
  },
  {
    name: 'ignore_older',
    type: 'text',
    title: 'Ignore Older',
    required: false,
    show_user: false,
    description:
      'If this option is enabled, Filebeat ignores every file that has not been modified within the specified timespan.',
  },
  {
    name: 'ignore_inactive',
    type: 'text',
    title: 'Ignore Inactive',
    required: false,
    show_user: false,
    description:
      'If this option is enabled, Filebeat ignores every file that has been inactive since the specified time. Valid options are since_first_start and since_last_start.',
  },
  {
    name: 'close_on_state_changed_inactive',
    type: 'text',
    title: 'Close On State Change Inactive',
    required: false,
    show_user: false,
    description:
      'Closes the reader when a file has not been harvested for the specified time period.',
  },
  {
    name: 'close_on_state_changed_renamed',
    type: 'bool',
    title: 'Close On State Change Renamed',
    required: false,
    show_user: false,
    description: 'Close the file handler when a file is renamed.',
  },
  {
    name: 'close_on_state_changed_removed',
    type: 'bool',
    title: 'Close On State Change Removed',
    required: false,
    show_user: false,
    description: 'Close the file handler when a file is removed.',
  },
  {
    name: 'close_reader_eof',
    type: 'bool',
    title: 'Close Reader On EOF',
    required: false,
    show_user: false,
    description: 'Close a file reader when the end of file is reached.',
  },
  {
    name: 'close_reader_after_interval',
    type: 'text',
    title: 'Close Reader After Interval',
    required: false,
    show_user: false,
    description: 'Close a reader after the specified time period.',
  },
  {
    name: 'clean_inactive',
    type: 'text',
    title: 'Clean Inactive',
    required: false,
    show_user: false,
    description: 'Remove the state of a file after the specified period of inactivity.',
  },
  {
    name: 'clean_removed',
    type: 'bool',
    title: 'Clean Removed',
    required: false,
    show_user: false,
    description: 'Remove the state entry for a file that has been removed from disk.',
  },
  {
    name: 'backoff_init',
    type: 'text',
    title: 'Backoff Init',
    required: false,
    show_user: false,
    description: 'The initial time to wait before checking a file again when EOF is reached.',
  },
  {
    name: 'backoff_max',
    type: 'text',
    title: 'Backoff Max',
    required: false,
    show_user: false,
    description: 'The maximum time to wait before checking a file again when EOF is reached.',
  },
  {
    name: 'rotation_external_strategy_copytruncate',
    type: 'yaml',
    title: 'Rotation External Strategy Copy Truncate',
    required: false,
    show_user: false,
    description: 'Configuration for the copy-truncate rotation strategy.',
  },
  {
    name: 'encoding',
    type: 'text',
    title: 'Encoding',
    required: false,
    show_user: false,
    description:
      'The file encoding to use for reading data that contains international characters.',
  },
  {
    name: 'exclude_lines',
    type: 'text',
    title: 'Exclude Lines',
    multi: true,
    required: false,
    show_user: false,
    description:
      'A list of regular expressions to match lines that should be excluded from the output.',
  },
  {
    name: 'include_lines',
    type: 'text',
    title: 'Include Lines',
    multi: true,
    required: false,
    show_user: false,
    description:
      'A list of regular expressions to match lines that should be included in the output.',
  },
  {
    name: 'buffer_size',
    type: 'integer',
    title: 'Buffer Size',
    required: false,
    show_user: false,
    description: 'The size in bytes of the buffer that each harvester uses when fetching a file.',
  },
  {
    name: 'message_max_bytes',
    type: 'integer',
    title: 'Message Max Bytes',
    required: false,
    show_user: false,
    description: 'The maximum number of bytes that a single log message can have.',
  },
  {
    name: 'parsers',
    type: 'yaml',
    title: 'Parsers',
    required: false,
    show_user: false,
    description: 'This option expects a list of parsers that the payload has to go through.',
  },
  {
    name: 'harvester_limit',
    type: 'integer',
    title: 'Harvester Limit',
    required: false,
    show_user: false,
    description: 'Limits the number of harvesters that are started in parallel.',
  },
  {
    name: 'fingerprint',
    type: 'bool',
    title: 'Use Fingerprint File Identity',
    required: false,
    show_user: false,
    default: false,
    description: 'Use file content fingerprint for file identity instead of native file identity.',
  },
  {
    name: 'fingerprint_offset',
    type: 'integer',
    title: 'Fingerprint Offset',
    required: false,
    show_user: false,
    description: 'The byte offset for the start of the fingerprint.',
  },
  {
    name: 'fingerprint_length',
    type: 'integer',
    title: 'Fingerprint Length',
    required: false,
    show_user: false,
    description: 'The number of bytes used for fingerprinting.',
  },
  {
    name: 'file_identity_native',
    type: 'bool',
    title: 'Use Native File Identity',
    required: false,
    show_user: false,
    description: 'Use native file identity (inode and device ID on Linux, file index on Windows).',
  },
  {
    name: 'condition',
    type: 'text',
    title: 'Condition',
    required: false,
    show_user: false,
    description: 'Condition to filter when the input is applied.',
  },
  {
    name: 'delete_enabled',
    type: 'bool',
    title: 'Delete Enabled',
    required: false,
    show_user: false,
    description: 'If true, files are deleted after they have been read completely.',
  },
  {
    name: 'delete_grace_period',
    type: 'text',
    title: 'Delete Grace Period',
    required: false,
    show_user: false,
    description: 'Time to wait before deleting a file after it has been fully read.',
  },
  {
    name: 'custom',
    type: 'yaml',
    title: 'Additional Filestream Configuration Options',
    required: false,
    show_user: false,
    description:
      'Configuration options that can be used to further change input configuration. Check the Filebeat documentation for more information.',
  },
];

const AWS_S3_VARS: DataStreamManifestVar[] = [
  {
    name: 'bucket_arn',
    type: 'text',
    title: 'Bucket ARN',
    multi: false,
    required: false,
    show_user: true,
    description:
      'ARN of the AWS S3 bucket that will be polled for list operation. (Required when queue_url and non_aws_bucket_name are not set).',
  },
  {
    name: 'queue_url',
    type: 'text',
    title: 'Queue URL',
    multi: false,
    required: false,
    show_user: true,
    description: 'URL of the AWS SQS queue that messages will be received from.',
  },
  {
    name: 'number_of_workers',
    type: 'integer',
    title: 'Number of Workers',
    multi: false,
    required: false,
    default: 1,
    show_user: true,
    description:
      'Number of workers that will process the S3 objects listed. (Required when bucket_arn is set).',
  },
  {
    name: 'parsers',
    type: 'yaml',
    title: 'Parsers',
    description: 'This option expects a list of parsers that the payload has to go through.',
    required: false,
    show_user: true,
    multi: false,
  },
  {
    name: 'api_timeout',
    type: 'text',
    title: 'API Timeout',
    multi: false,
    required: false,
    show_user: false,
    description:
      'The maximum duration of AWS API can take. The maximum is half of the visibility timeout value.',
  },
  {
    name: 'bucket_list_interval',
    type: 'text',
    title: 'Bucket List Interval',
    multi: false,
    required: false,
    show_user: false,
    default: '120s',
    description: 'Time interval for polling listing of the S3 bucket.',
  },
  {
    name: 'bucket_list_prefix',
    type: 'text',
    title: 'Bucket List Prefix',
    multi: false,
    required: false,
    show_user: false,
    description: 'Prefix to apply for the list request to the S3 bucket.',
  },
  {
    name: 'content_type',
    type: 'text',
    title: 'Content Type',
    multi: false,
    required: false,
    show_user: false,
    description:
      'A standard MIME type describing the format of the object data. This can be set to override the MIME type that was given to the object when it was uploaded.',
  },
  {
    name: 'encoding',
    type: 'text',
    title: 'Encoding',
    multi: false,
    required: false,
    show_user: false,
    description:
      'The file encoding to use for reading data that contains international characters. This only applies to non-JSON logs.',
  },
  {
    name: 'expand_event_list_from_field',
    type: 'text',
    title: 'Expand Event List from Field',
    multi: false,
    required: false,
    show_user: false,
    description:
      'If the fileset using this input expects to receive multiple messages bundled under a specific field then the config option expand_event_list_from_field value can be assigned the name of the field.',
  },
  {
    name: 'file_selectors',
    type: 'yaml',
    title: 'File Selectors',
    multi: true,
    required: false,
    show_user: false,
    description:
      'If the SQS queue will have events that correspond to files that this integration should not process, file_selectors can be used to limit the files that are downloaded.',
  },
  {
    name: 'fips_enabled',
    type: 'bool',
    title: 'Enable S3 FIPS',
    default: false,
    multi: false,
    required: false,
    show_user: false,
    description:
      'Enabling this option changes the service name from s3 to s3-fips for connecting to the correct service endpoint.',
  },
  {
    name: 'max_bytes',
    type: 'text',
    title: 'Max Bytes',
    default: '10MiB',
    multi: false,
    required: false,
    show_user: false,
    description:
      'The maximum number of bytes that a single log message can have. This only applies to non-JSON logs.',
  },
  {
    name: 'max_number_of_messages',
    type: 'integer',
    title: 'Maximum Concurrent SQS Messages',
    description: 'The maximum number of SQS messages that can be inflight at any time.',
    default: 5,
    required: false,
    show_user: false,
  },
  {
    name: 'visibility_timeout',
    type: 'text',
    title: 'Visibility Timeout',
    multi: false,
    required: false,
    show_user: false,
    description:
      'The duration that the received messages are hidden from subsequent retrieve requests after being retrieved by a ReceiveMessage request.',
  },
  {
    name: 'sqs.max_receive_count',
    type: 'integer',
    title: 'SQS Message Maximum Receive Count',
    multi: false,
    required: false,
    show_user: false,
    default: 5,
    description:
      'The maximum number of times a SQS message should be received (retried) before deleting it.',
  },
  {
    name: 'sqs.wait_time',
    type: 'text',
    title: 'SQS Maximum Wait Time',
    multi: false,
    required: false,
    show_user: false,
    default: '20s',
    description:
      'The maximum duration that an SQS ReceiveMessage call should wait for a message to arrive in the queue before returning.',
  },
  {
    name: 'credential_profile_name',
    type: 'text',
    title: 'Credential Profile Name',
    multi: false,
    required: false,
    show_user: false,
    description: 'Profile name in shared credentials file.',
  },
  {
    name: 'access_key_id',
    type: 'password',
    title: 'Access Key ID',
    multi: false,
    required: false,
    show_user: true,
    description: 'First part of access key.',
  },
  {
    name: 'secret_access_key',
    type: 'password',
    title: 'Secret Access Key',
    multi: false,
    required: false,
    show_user: true,
    description: 'Second part of access key.',
  },
  {
    name: 'session_token',
    type: 'password',
    title: 'Session Token',
    multi: false,
    required: false,
    show_user: true,
    description: 'Required when using temporary security credentials.',
  },
  {
    name: 'endpoint',
    type: 'text',
    title: 'Endpoint',
    multi: false,
    required: false,
    show_user: false,
    description: 'URL of the entry point for an AWS web service.',
  },
  {
    name: 'default_region',
    type: 'text',
    title: 'Default AWS Region',
    multi: false,
    required: false,
    show_user: false,
    default: '',
    description:
      'Default region to use prior to connecting to region specific services/endpoints if no AWS region is set from environment variable, credentials or instance profile.',
  },
  {
    name: 'proxy_url',
    type: 'text',
    title: 'Proxy URL',
    multi: false,
    required: false,
    show_user: false,
    description:
      'URL to proxy connections in the form of http[s]://<user>:<password>@<server name/ip>:<port>.',
  },
];

const AWS_CLOUDWATCH_VARS: DataStreamManifestVar[] = [
  {
    name: 'log_group_arn',
    type: 'text',
    title: 'Log Group ARN',
    multi: false,
    required: false,
    show_user: true,
    description: 'ARN of the log group to collect logs from.',
  },
  {
    name: 'start_position',
    type: 'text',
    title: 'Start Position',
    multi: false,
    required: false,
    default: 'beginning',
    show_user: true,
    description:
      'Allows user to specify if this input should read log files from the beginning or from the end.',
  },
  {
    name: 'log_group_name',
    type: 'text',
    title: 'Log Group Name',
    multi: false,
    required: false,
    show_user: false,
    description:
      'Name of the log group to collect logs from. region_name is required when log_group_name is given.',
  },
  {
    name: 'log_group_name_prefix',
    type: 'text',
    title: 'Log Group Name Prefix',
    multi: false,
    required: false,
    show_user: false,
    description:
      'The prefix for a group of log group names. region_name is required when log_group_name_prefix is given.',
  },
  {
    name: 'region_name',
    type: 'text',
    title: 'Region Name',
    multi: false,
    required: false,
    show_user: false,
    description: 'Region that the specified log group or log group prefix belongs to.',
  },
  {
    name: 'log_streams',
    type: 'text',
    title: 'Log Streams',
    multi: true,
    required: false,
    show_user: false,
    description: 'A list of strings of log streams names that Filebeat collect log events from.',
  },
  {
    name: 'log_stream_prefix',
    type: 'text',
    title: 'Log Stream Prefix',
    multi: false,
    required: false,
    show_user: false,
    description:
      'A string to filter the results to include only log events from log streams that have names starting with this prefix.',
  },
  {
    name: 'scan_frequency',
    type: 'text',
    title: 'Scan Frequency',
    multi: false,
    required: false,
    show_user: false,
    default: '1m',
    description:
      'This config parameter sets how often Filebeat checks for new log events from the specified log group.',
  },
  {
    name: 'api_timeout',
    type: 'text',
    title: 'API Timeout',
    multi: false,
    required: false,
    show_user: false,
    default: '120s',
    description:
      'The maximum duration of AWS API can take. If it exceeds the timeout, AWS API will be interrupted.',
  },
  {
    name: 'api_sleep',
    type: 'text',
    title: 'API Sleep',
    multi: false,
    required: false,
    show_user: false,
    default: '200ms',
    description:
      'This is used to sleep between AWS FilterLogEvents API calls inside the same collection period.',
  },
  {
    name: 'latency',
    type: 'text',
    title: 'Latency',
    multi: false,
    required: false,
    show_user: false,
    description: 'The amount of time required for the logs to be available to CloudWatch Logs.',
  },
  {
    name: 'number_of_workers',
    type: 'integer',
    title: 'Number of workers',
    required: false,
    show_user: false,
    description: 'The number of workers assigned to reading from log groups.',
  },
  {
    name: 'credential_profile_name',
    type: 'text',
    title: 'Credential Profile Name',
    multi: false,
    required: false,
    show_user: false,
  },
  {
    name: 'shared_credential_file',
    type: 'text',
    title: 'Shared Credential File',
    multi: false,
    required: false,
    show_user: false,
    description: 'Directory of the shared credentials file.',
  },
  {
    name: 'default_region',
    type: 'text',
    title: 'Default AWS Region',
    multi: false,
    required: false,
    show_user: false,
    default: '',
    description:
      'Default region to use prior to connecting to region specific services/endpoints if no AWS region is set from environment variable, credentials or instance profile.',
  },
  {
    name: 'access_key_id',
    type: 'password',
    title: 'Access Key ID',
    multi: false,
    required: false,
    show_user: true,
    description: 'First part of access key.',
  },
  {
    name: 'secret_access_key',
    type: 'password',
    title: 'Secret Access Key',
    multi: false,
    required: false,
    show_user: true,
    description: 'Second part of access key.',
  },
  {
    name: 'session_token',
    type: 'password',
    title: 'Session Token',
    multi: false,
    required: false,
    show_user: true,
    description: 'Required when using temporary security credentials.',
  },
  {
    name: 'role_arn',
    type: 'text',
    title: 'Role ARN',
    multi: false,
    required: false,
    show_user: false,
    description: 'AWS IAM Role to assume.',
  },
  {
    name: 'proxy_url',
    type: 'text',
    title: 'Proxy URL',
    multi: false,
    required: false,
    show_user: false,
    description:
      'URL to proxy connections in the form of http[s]://<user>:<password>@<server name/ip>:<port>.',
  },
];

const AZURE_BLOB_STORAGE_VARS: DataStreamManifestVar[] = [
  {
    name: 'account_name',
    type: 'text',
    title: 'Account Name',
    description:
      'This attribute is required for various internal operations with respect to authentication, creating service clients and blob clients.',
    required: true,
    show_user: true,
  },
  {
    name: 'service_account_key',
    type: 'password',
    title: 'Service Account Key',
    description:
      'This attribute contains the access key, found under the Access keys section on Azure Cloud, under the respective storage account.',
    required: false,
    show_user: true,
  },
  {
    name: 'service_account_uri',
    type: 'text',
    title: 'Service Account URI',
    description:
      'This attribute contains the connection string, found under the Access keys section on Azure Cloud, under the respective storage account.',
    required: false,
    show_user: false,
  },
  {
    name: 'storage_url',
    type: 'text',
    title: 'Storage URL',
    description:
      'Use this attribute to specify a custom storage URL if required. By default it points to azure cloud storage.',
    required: false,
    show_user: false,
  },
  {
    name: 'number_of_workers',
    type: 'integer',
    title: 'Maximum number of workers',
    multi: false,
    required: false,
    show_user: true,
    default: 3,
    description: 'Determines how many workers are spawned per container.',
  },
  {
    name: 'poll',
    type: 'bool',
    title: 'Polling',
    multi: false,
    required: false,
    show_user: true,
    default: true,
    description: 'Determines if the container will be continuously polled for new documents.',
  },
  {
    name: 'poll_interval',
    type: 'text',
    title: 'Polling interval',
    multi: false,
    required: false,
    show_user: true,
    default: '15s',
    description: 'Determines the time interval between polling operations.',
  },
  {
    name: 'containers',
    type: 'yaml',
    title: 'Containers',
    description:
      'This attribute contains the details about a specific container like name, number_of_workers, poll, poll_interval etc.',
    required: true,
    show_user: true,
    default: '- name: azure-container1\n  max_workers: 3\n  poll: true\n  poll_interval: 15s\n',
  },
  {
    name: 'file_selectors',
    type: 'yaml',
    title: 'File Selectors',
    multi: false,
    required: false,
    show_user: false,
    description:
      'If the container will have events that correspond to files that this integration should not process, file_selectors can be used to limit the files that are downloaded.',
  },
  {
    name: 'timestamp_epoch',
    type: 'integer',
    title: 'Timestamp Epoch',
    multi: false,
    required: false,
    show_user: false,
  },
  {
    name: 'expand_event_list_from_field',
    type: 'text',
    title: 'Expand Event List From Field',
    multi: false,
    required: false,
    show_user: false,
    description:
      'If the file-set using this input expects to receive multiple messages bundled under a specific field or an array of objects then the config option for expand_event_list_from_field can be specified.',
  },
];

const AZURE_EVENTHUB_VARS: DataStreamManifestVar[] = [
  {
    name: 'eventhub',
    type: 'text',
    title: 'Event Hub',
    multi: false,
    required: true,
    show_user: true,
    description:
      'Elastic recommends using one event hub for each integration. Use event hub names up to 30 characters long to avoid compatibility issues.',
  },
  {
    name: 'connection_string',
    type: 'text',
    title: 'Connection String',
    multi: false,
    required: true,
    show_user: true,
    description: 'The connection string required to communicate with Event Hubs.',
  },
  {
    name: 'storage_account',
    type: 'text',
    title: 'Storage Account',
    multi: false,
    required: true,
    show_user: true,
    description:
      'The name of the storage account where the consumer group state/offsets will be stored and updated.',
  },
  {
    name: 'storage_account_key',
    type: 'text',
    title: 'Storage Account Key',
    multi: false,
    required: true,
    show_user: true,
    description:
      'The storage account key, this key will be used to authorize access to data in your storage account.',
  },
  {
    name: 'consumer_group',
    type: 'text',
    title: 'Consumer Group',
    multi: false,
    required: true,
    show_user: true,
    default: '$Default',
  },
  {
    name: 'resource_manager_endpoint',
    type: 'text',
    title: 'Resource Manager Endpoint',
    multi: false,
    required: false,
    show_user: false,
  },
  {
    name: 'storage_account_container',
    type: 'text',
    title: 'Storage Account Container',
    multi: false,
    required: false,
    show_user: false,
    description:
      'The storage account container where the integration stores the checkpoint data for the consumer group.',
  },
  {
    name: 'sanitize_newlines',
    type: 'bool',
    title: 'Sanitizes New Lines',
    description:
      'Removes new lines in logs to ensure proper formatting of JSON data and avoid parsing issues during processing.',
    multi: false,
    required: false,
    show_user: false,
    default: false,
  },
  {
    name: 'sanitize_singlequotes',
    type: 'bool',
    title: 'Sanitizes Single Quotes',
    description:
      'Replaces single quotes with double quotes in logs to ensure proper formatting of JSON data and avoid parsing issues during processing.',
    required: true,
    show_user: false,
    multi: false,
    default: false,
  },
];

const GCP_PUBSUB_VARS: DataStreamManifestVar[] = [
  {
    name: 'project_id',
    type: 'text',
    title: 'Project ID',
    multi: false,
    required: true,
    show_user: true,
  },
  {
    name: 'topic',
    type: 'text',
    title: 'Topic',
    multi: false,
    required: true,
    show_user: true,
  },
  {
    name: 'subscription_name',
    type: 'text',
    title: 'Subscription Name',
    multi: false,
    required: true,
    show_user: true,
  },
  {
    name: 'credentials_file',
    type: 'text',
    title: 'Credentials File',
    multi: false,
    required: false,
    show_user: true,
    description: 'Path to a JSON file containing the credentials and key used to subscribe.',
  },
  {
    name: 'credentials_json',
    type: 'text',
    title: 'Credentials JSON',
    multi: false,
    required: false,
    show_user: true,
    description: 'JSON blob containing the credentials and key used to subscribe.',
  },
  {
    name: 'subscription_create',
    type: 'bool',
    title: 'Subscription Create',
    description: 'If true, the integration will create the subscription on start.',
    multi: false,
    required: false,
    show_user: true,
  },
  {
    name: 'subscription_num_goroutines',
    type: 'text',
    title: 'Subscription Num Goroutines',
    description: 'Number of goroutines created to read from the subscription.',
    multi: false,
    required: false,
    show_user: false,
  },
  {
    name: 'subscription_max_outstanding_messages',
    type: 'text',
    title: 'Subscription Max Outstanding Messages',
    description:
      'The maximum number of unprocessed messages (unacknowledged but not yet expired). If the value is negative, then there will be no limit. Default is 1000.',
    multi: false,
    required: false,
    show_user: false,
  },
  {
    name: 'alternative_host',
    type: 'text',
    title: 'Alternative host',
    multi: false,
    required: false,
    show_user: false,
  },
];

const GCS_VARS: DataStreamManifestVar[] = [
  {
    name: 'project_id',
    type: 'text',
    title: 'Project ID',
    description:
      'This attribute is required for various internal operations with respect to authentication, creating storage clients and logging.',
    multi: false,
    required: true,
    show_user: true,
    default: 'my-project-id',
  },
  {
    name: 'service_account_key',
    type: 'password',
    title: 'Service Account Key',
    description:
      'This attribute contains the json service account credentials string, which can be generated from the google cloud console.',
    multi: false,
    required: false,
    show_user: true,
  },
  {
    name: 'service_account_file',
    type: 'text',
    title: 'Service Account File',
    description:
      'This attribute contains the service account credentials file, which can be generated from the google cloud console.',
    multi: false,
    required: false,
    show_user: true,
  },
  {
    name: 'number_of_workers',
    type: 'integer',
    title: 'Maximum number of workers',
    multi: false,
    required: false,
    show_user: true,
    default: 3,
    description: 'Determines how many workers are spawned per bucket.',
  },
  {
    name: 'poll',
    type: 'bool',
    title: 'Polling',
    multi: false,
    required: false,
    show_user: true,
    default: true,
    description: 'Determines if the bucket will be continuously polled for new documents.',
  },
  {
    name: 'poll_interval',
    type: 'text',
    title: 'Polling interval',
    multi: false,
    required: false,
    show_user: true,
    default: '15s',
    description: 'Determines the time interval between polling operations.',
  },
  {
    name: 'bucket_timeout',
    type: 'text',
    title: 'Bucket Timeout',
    multi: false,
    required: false,
    show_user: true,
    default: '120s',
    description:
      'Defines the maximum time that the sdk will wait for a bucket api response before timing out.',
  },
  {
    name: 'buckets',
    type: 'yaml',
    title: 'Buckets',
    description:
      'This attribute contains the details about a specific bucket like name, number_of_workers, poll, poll_interval and bucket_timeout.',
    required: true,
    show_user: true,
    default: '- name: logs\n- name: logs_2\n',
  },
  {
    name: 'file_selectors',
    type: 'yaml',
    title: 'File Selectors',
    multi: false,
    required: false,
    show_user: false,
    description:
      'If the GCS bucket will have events that correspond to files that this integration should not process, file_selectors can be used to limit the files that are downloaded.',
  },
  {
    name: 'timestamp_epoch',
    type: 'integer',
    title: 'Timestamp Epoch',
    multi: false,
    required: false,
    show_user: false,
    description:
      'Defines the epoch time in seconds, which is used to filter out objects/files that are older than the specified timestamp.',
  },
  {
    name: 'alternative_host',
    type: 'text',
    title: 'Alternative Host',
    description:
      'Used to override the default host for the storage client (default is storage.googleapis.com).',
    required: false,
    multi: false,
    show_user: false,
  },
];

const HTTP_ENDPOINT_VARS: DataStreamManifestVar[] = [
  {
    name: 'listen_address',
    type: 'text',
    title: 'Listen Address',
    description: 'Bind address for the HTTP listener. Use 0.0.0.0 to listen on all interfaces.',
    required: true,
    show_user: true,
    default: 'localhost',
  },
  {
    name: 'listen_port',
    type: 'text',
    title: 'Listen port',
    description: 'Bind port for the listener.',
    required: true,
    show_user: true,
    default: '8080',
  },
  {
    name: 'url',
    type: 'text',
    title: 'URL',
    description: 'This options specific which URL path to accept requests on. Defaults to /.',
    required: false,
    show_user: true,
  },
  {
    name: 'prefix',
    type: 'text',
    title: 'Prefix',
    description: 'This option specifies which prefix field the incoming request will be mapped to.',
    required: false,
    show_user: false,
  },
  {
    name: 'basic_auth',
    type: 'bool',
    title: 'Basic Auth',
    description: 'Enables or disables HTTP basic auth for each incoming request.',
    required: false,
    show_user: false,
  },
  {
    name: 'username',
    type: 'text',
    title: 'Username',
    description:
      'If basic_auth is enabled, this is the username used for authentication against the HTTP listener.',
    required: false,
    show_user: false,
  },
  {
    name: 'password',
    type: 'password',
    title: 'Password',
    description:
      'If basic_auth is enabled, this is the password used for authentication against the HTTP listener.',
    required: false,
    show_user: false,
  },
  {
    name: 'secret_header',
    type: 'text',
    title: 'Secret Header',
    description: 'The header to check for a specific value specified by secret.value.',
    required: false,
    show_user: false,
  },
  {
    name: 'secret_value',
    type: 'password',
    title: 'Secret Value',
    description: 'The secret stored in the header name specified by secret.header.',
    required: false,
    show_user: false,
  },
  {
    name: 'hmac_header',
    type: 'text',
    title: 'HMAC Header',
    description: 'The name of the header that contains the HMAC signature.',
    required: false,
    show_user: false,
  },
  {
    name: 'hmac_key',
    type: 'password',
    title: 'HMAC Key',
    description: 'The secret key used to calculate the HMAC signature.',
    required: false,
    show_user: false,
  },
  {
    name: 'hmac_type',
    type: 'text',
    title: 'HMAC Type',
    description:
      'The hash algorithm to use for the HMAC comparison. Valid values are sha256 or sha1.',
    required: false,
    show_user: false,
  },
  {
    name: 'hmac_prefix',
    type: 'text',
    title: 'HMAC Prefix',
    description:
      'The prefix for the signature. Certain webhooks prefix the HMAC signature with a value, for example sha256=.',
    required: false,
    show_user: false,
  },
  {
    name: 'content_type',
    type: 'text',
    title: 'Content Type',
    description:
      'By default the input expects the incoming POST to include a Content-Type of application/json.',
    required: false,
    show_user: false,
  },
  {
    name: 'response_code',
    type: 'text',
    title: 'Response Code',
    description: 'The HTTP response code returned upon success. Should be in the 2XX range.',
    required: false,
    show_user: false,
  },
  {
    name: 'response_body',
    type: 'text',
    title: 'Response Body',
    description: 'The response body returned upon success. Should be a single line JSON string.',
    required: false,
    show_user: false,
  },
  {
    name: 'include_headers',
    type: 'text',
    title: 'Include Headers',
    description:
      'This options specifies a list of HTTP headers that should be copied from the incoming request and included in the document.',
    multi: true,
    required: false,
    show_user: false,
  },
];

const KAFKA_VARS: DataStreamManifestVar[] = [
  {
    name: 'hosts',
    type: 'text',
    title: 'Hosts',
    description: 'A list of Kafka bootstrapping hosts (brokers) for this cluster.',
    required: true,
    show_user: true,
    multi: true,
  },
  {
    name: 'topics',
    type: 'text',
    title: 'Topics',
    description: 'A list of topics to read from.',
    required: true,
    show_user: true,
    multi: true,
  },
  {
    name: 'group_id',
    type: 'text',
    title: 'Group ID',
    description: 'The Kafka consumer group id.',
    required: true,
    show_user: true,
  },
  {
    name: 'client_id',
    type: 'text',
    title: 'Client ID',
    description: 'The Kafka client id (optional).',
    required: false,
    show_user: true,
  },
  {
    name: 'version',
    type: 'text',
    title: 'Version',
    description: 'The version of the Kafka protocol to use (defaults to "1.0.0").',
    required: false,
    show_user: true,
  },
  {
    name: 'expand_event_list_from_field',
    type: 'text',
    title: 'Expand Event List from Field',
    description:
      'Split a field that contains an array of JSON objects, the value would be the name of this field.',
    required: false,
    show_user: true,
  },
  {
    name: 'parsers',
    type: 'yaml',
    title: 'Parsers',
    description: 'This option expects a list of parsers that the payload has to go through.',
    required: false,
    show_user: true,
    multi: false,
  },
  {
    name: 'username',
    type: 'text',
    title: 'Username',
    description: 'Username used for SASL authentication.',
    required: false,
    show_user: true,
  },
  {
    name: 'password',
    type: 'password',
    title: 'Password',
    description: 'Password used for SASL authentication.',
    required: false,
    show_user: true,
  },
  {
    name: 'kerberos_enabled',
    type: 'bool',
    title: 'Kerberos Enabled',
    description:
      'The enabled setting can be used to enable the Kerberos configuration by setting it to true. The default value is false.',
    required: false,
    show_user: false,
  },
  {
    name: 'kerberos_auth_type',
    type: 'text',
    title: 'Kerberos Auth Type',
    description: 'There are two options to authenticate with Kerberos KDC: password and keytab.',
    required: false,
    show_user: false,
  },
  {
    name: 'kerberos_config_path',
    type: 'text',
    title: 'Kerberos Config Path',
    description:
      'You need to set the path to the krb5.conf, so Elastic Agent can find the Kerberos KDC to retrieve a ticket.',
    required: false,
    show_user: false,
  },
  {
    name: 'kerberos_username',
    type: 'text',
    title: 'Kerberos Username',
    description: 'Name of the principal used to connect to the output.',
    required: false,
    show_user: false,
  },
  {
    name: 'kerberos_password',
    type: 'password',
    title: 'Kerberos Password',
    description:
      'If you configured password for Auth Type, you have to provide a password for the selected principal.',
    required: false,
    show_user: false,
  },
  {
    name: 'kerberos_keytab',
    type: 'text',
    title: 'Kerberos Keytab',
    description:
      'If you configured keytab for Auth Type, you have to provide the path to the keytab of the selected principal.',
    required: false,
    show_user: false,
  },
  {
    name: 'kerberos_service_name',
    type: 'text',
    title: 'Kerberos Service Name',
    description:
      'This option can only be configured for Kafka. It is the name of the Kafka service, usually "kafka".',
    required: false,
    show_user: false,
  },
  {
    name: 'kerberos_realm',
    type: 'text',
    title: 'Kerberos Realm',
    description: 'Name of the realm where the output resides.',
    required: false,
    show_user: false,
  },
  {
    name: 'kerberos_enable_krb5_fast',
    type: 'bool',
    title: 'Kerberos KRB5 Fast',
    description:
      'Enable Kerberos FAST authentication. This may conflict with some Active Directory installations. The default is false.',
    required: false,
    show_user: false,
  },
  {
    name: 'initial_offset',
    type: 'text',
    title: 'Initial Offset',
    description:
      'The initial offset to start reading, either "oldest" or "newest". Defaults to "oldest".',
    required: false,
    show_user: false,
  },
  {
    name: 'connect_backoff',
    type: 'text',
    title: 'Connect Backoff',
    description:
      'How long to wait before trying to reconnect to the kafka cluster after a fatal error. Default is 30s.',
    required: false,
    show_user: false,
  },
  {
    name: 'consume_backoff',
    type: 'text',
    title: 'Consume Backoff',
    description: 'How long to wait before retrying a failed read. Default is 2s.',
    required: false,
    show_user: false,
  },
  {
    name: 'max_wait_time',
    type: 'text',
    title: 'Max Wait Time',
    description:
      'How long to wait for the minimum number of input bytes while reading. Default is 250ms.',
    required: false,
    show_user: false,
  },
  {
    name: 'fetch_min',
    type: 'text',
    title: 'Fetch Min',
    description: 'The minimum number of bytes to wait for. Defaults to 1.',
    required: false,
    show_user: false,
  },
  {
    name: 'fetch_default',
    type: 'text',
    title: 'Fetch Default',
    description: 'The default number of bytes to read per request. Defaults to 1MB.',
    required: false,
    show_user: false,
  },
  {
    name: 'fetch_max',
    type: 'text',
    title: 'Fetch Max',
    description: 'The maximum number of bytes to read per request. Defaults to 0 (no limit).',
    required: false,
    show_user: false,
  },
  {
    name: 'rebalance_strategy',
    type: 'text',
    title: 'Rebalance Strategy',
    description: 'Either "range" or "roundrobin". Defaults to "range".',
    required: false,
    show_user: false,
  },
  {
    name: 'rebalance_timeout',
    type: 'text',
    title: 'Rebalance Timeout',
    description: 'How long to wait for an attempted rebalance. Defaults to 60s.',
    required: false,
    show_user: false,
  },
  {
    name: 'rebalance_max_retries',
    type: 'text',
    title: 'Rebalance Max Retries',
    description: 'How many times to retry if rebalancing fails. Defaults to 4.',
    required: false,
    show_user: false,
  },
  {
    name: 'rebalance_retry_backoff',
    type: 'text',
    title: 'Rebalance Retry Backoff',
    description: 'How long to wait after an unsuccessful rebalance attempt. Defaults to 2s.',
    required: false,
    show_user: false,
  },
];

const TCP_VARS: DataStreamManifestVar[] = [
  {
    name: 'listen_address',
    type: 'text',
    title: 'Listen Address',
    description: 'Bind address for the listener. Use 0.0.0.0 to listen on all interfaces.',
    required: true,
    show_user: true,
    default: 'localhost',
  },
  {
    name: 'listen_port',
    type: 'text',
    title: 'Listen port',
    description: 'Bind port for the listener.',
    required: true,
    show_user: true,
    default: '8080',
  },
  {
    name: 'max_message_size',
    type: 'text',
    title: 'Max Message Size',
    description: 'The maximum size of the message received over TCP. The default is 20MiB.',
    required: false,
    show_user: false,
  },
  {
    name: 'framing',
    type: 'text',
    title: 'Framing',
    description:
      'Specify the framing used to split incoming events. Can be one of delimiter or rfc6587. The default is delimiter.',
    required: false,
    show_user: false,
  },
  {
    name: 'line_delimiter',
    type: 'text',
    title: 'Line Delimiter',
    description: 'Specify the characters used to split the incoming events. The default is \\n.',
    required: false,
    show_user: false,
  },
  {
    name: 'max_connections',
    type: 'text',
    title: 'Max Connections',
    description: 'The at most number of connections to accept at any given point in time.',
    required: false,
    show_user: false,
  },
  {
    name: 'timeout',
    type: 'text',
    title: 'Timeout',
    description:
      'The duration of inactivity before a remote connection is closed. The default is 300s.',
    required: false,
    show_user: false,
  },
  {
    name: 'keep_null',
    type: 'bool',
    title: 'Keep Null Values',
    description:
      'If this option is set to true, fields with null values will be published in the output document. By default, keep_null is set to false.',
    required: false,
    show_user: false,
  },
];

const UDP_VARS: DataStreamManifestVar[] = [
  {
    name: 'listen_address',
    type: 'text',
    title: 'Listen Address',
    description: 'Bind address for the listener. Use 0.0.0.0 to listen on all interfaces.',
    required: true,
    show_user: true,
    default: 'localhost',
  },
  {
    name: 'listen_port',
    type: 'text',
    title: 'Listen port',
    description: 'Bind port for the listener.',
    required: true,
    show_user: true,
    default: '8080',
  },
  {
    name: 'max_message_size',
    type: 'text',
    title: 'Max Message Size',
    description: 'The maximum size of the message received over UDP. The default is 10KiB.',
    required: false,
    show_user: false,
  },
  {
    name: 'timeout',
    type: 'text',
    title: 'Timeout',
    description:
      'The duration of inactivity before a remote connection is closed. The default is 300s.',
    required: false,
    show_user: false,
  },
  {
    name: 'keep_null',
    type: 'bool',
    title: 'Keep Null Values',
    description:
      'If this option is set to true, fields with null values will be published in the output document. By default, keep_null is set to false.',
    required: false,
    show_user: false,
  },
];

const CLOUDFOUNDRY_VARS: DataStreamManifestVar[] = [
  {
    name: 'api_address',
    type: 'text',
    title: 'API Address',
    multi: false,
    required: true,
    show_user: true,
    default: 'http://api.bosh-lite.com',
    description: 'The URL of the Cloud Foundry API.',
  },
  {
    name: 'client_id',
    type: 'text',
    title: 'Client ID',
    multi: false,
    required: true,
    show_user: true,
    description: 'Client ID to authenticate with Cloud Foundry.',
  },
  {
    name: 'client_secret',
    type: 'text',
    title: 'Client Secret',
    multi: false,
    required: true,
    show_user: true,
    description: 'Client Secret to authenticate with Cloud Foundry.',
  },
  {
    name: 'shard_id',
    type: 'text',
    title: 'Shard ID',
    required: false,
    show_user: false,
    description:
      'Shard ID for the connection with Cloud Foundry. Use the same ID across multiple filebeat to shard the load of events.',
  },
  {
    name: 'version',
    type: 'text',
    title: 'Cloud Foundry API Version',
    required: false,
    show_user: false,
    description:
      'Consumer API version to connect with Cloud Foundry to collect events. Use v1 to collect events using Doppler/Traffic Control. Use v2 to collect events from the RLP Gateway. Default: "v1".',
  },
  {
    name: 'doppler_address',
    type: 'text',
    title: 'Doppler Address',
    required: false,
    show_user: false,
    description: 'The URL of the Cloud Foundry Doppler Websocket.',
  },
  {
    name: 'uaa_address',
    type: 'text',
    title: 'UAA Address',
    required: false,
    show_user: false,
    description: 'The URL of the Cloud Foundry UAA API.',
  },
  {
    name: 'rlp_address',
    type: 'text',
    title: 'RLP Address',
    required: false,
    show_user: false,
    description: 'The URL of the Cloud Foundry RLP Gateway.',
  },
];

const JOURNALD_VARS: DataStreamManifestVar[] = [
  {
    name: 'include_matches',
    type: 'text',
    title: 'Include Matches',
    multi: true,
    show_user: true,
    description:
      'A list of filter expressions used to select the logs to read (e.g. _SYSTEMD_UNIT=vault.service). Defaults to all logs.',
  },
  {
    name: 'backoff',
    type: 'text',
    title: 'Backoff Duration',
    multi: false,
    show_user: false,
    default: '1s',
    description: 'The number of seconds to wait before trying to read again from journals.',
  },
  {
    name: 'max_backoff',
    type: 'text',
    title: 'Max Backoff Duration',
    multi: false,
    show_user: false,
    default: '60s',
    description:
      'The maximum number of seconds to wait before attempting to read again from journals.',
  },
  {
    name: 'seek',
    type: 'text',
    title: 'Start Position',
    multi: false,
    show_user: false,
    description: 'The position to start reading the journal from.',
  },
  {
    name: 'cursor_seek_fallback',
    type: 'text',
    title: 'Start Position Fallback',
    multi: false,
    show_user: false,
    description:
      'The position to start reading the journal from if no cursor information is available.',
  },
  {
    name: 'since',
    type: 'text',
    title: 'Start Since',
    multi: false,
    show_user: false,
    description: 'A time offset from the current time to start reading from. Example: "-24h".',
  },
  {
    name: 'units',
    type: 'text',
    title: 'Units',
    multi: true,
    show_user: false,
    description: 'Iterate only the entries of the units specified in this option.',
  },
  {
    name: 'paths',
    type: 'text',
    title: 'Journal paths',
    multi: true,
    show_user: false,
    description: 'List of journals to read from. Defaults to the system journal.',
  },
];

const INPUT_VARS_MAP: Record<string, DataStreamManifestVar[]> = {
  filestream: FILESTREAM_VARS,
  'aws-s3': AWS_S3_VARS,
  'aws-cloudwatch': AWS_CLOUDWATCH_VARS,
  'azure-blob-storage': AZURE_BLOB_STORAGE_VARS,
  'azure-eventhub': AZURE_EVENTHUB_VARS,
  'gcp-pubsub': GCP_PUBSUB_VARS,
  gcs: GCS_VARS,
  http_endpoint: HTTP_ENDPOINT_VARS,
  kafka: KAFKA_VARS,
  tcp: TCP_VARS,
  udp: UDP_VARS,
  cloudfoundry: CLOUDFOUNDRY_VARS,
  journald: JOURNALD_VARS,
};

export const getInputVars = (inputType: string): DataStreamManifestVar[] => {
  return INPUT_VARS_MAP[inputType] ?? [];
};
