import type { DataView } from '@kbn/data-views-plugin/public';
import { type Field, type Aggregation, ML_JOB_AGGREGATION } from '@kbn/ml-anomaly-utils';
import type { SavedSearch } from '@kbn/saved-search-plugin/public';
import { type CategorizationAnalyzer, type CategoryFieldExample, type FieldExampleCheck, CATEGORY_EXAMPLES_VALIDATION_STATUS } from '@kbn/ml-category-validator';
import type { Datafeed } from '@kbn/ml-common-types/anomaly_detection_jobs/datafeed';
import type { Job } from '@kbn/ml-common-types/anomaly_detection_jobs/job';
import { JobCreator } from './job_creator';
import { JOB_TYPE } from '../../../../../../common/constants/new_job';
import type { MlApi } from '../../../../services/ml_api_service';
import type { NewJobCapsService } from '../../../../services/new_job_capabilities/new_job_capabilities_service';
type DetectorType = ML_JOB_AGGREGATION.COUNT | ML_JOB_AGGREGATION.HIGH_COUNT | ML_JOB_AGGREGATION.RARE;
export declare class CategorizationJobCreator extends JobCreator {
    protected _type: JOB_TYPE;
    private _createCountDetector;
    private _createHighCountDetector;
    private _createRareDetector;
    private _examplesLoader;
    private _categoryFieldExamples;
    private _validationChecks;
    private _overallValidStatus;
    private _detectorType;
    private _categorizationAnalyzer;
    private _defaultCategorizationAnalyzer;
    private _partitionFieldName;
    private _ccsVersionFailure;
    constructor(mlApi: MlApi, newJobCapsService: NewJobCapsService, indexPattern: DataView, savedSearch: SavedSearch | null, query: object);
    setDefaultDetectorProperties(count: Aggregation | null, highCount: Aggregation | null, rare: Aggregation | null, eventRate: Field | null): void;
    private _createDetector;
    setDetectorType(type: DetectorType): void;
    set categorizationFieldName(fieldName: string | null);
    get categorizationFieldName(): string | null;
    loadCategorizationFieldExamples(): Promise<{
        examples: CategoryFieldExample[];
        sampleSize: number;
        overallValidStatus: CATEGORY_EXAMPLES_VALIDATION_STATUS;
        validationChecks: FieldExampleCheck[];
        ccsVersionFailure: boolean;
    }>;
    private _checkCcsFailure;
    get categoryFieldExamples(): CategoryFieldExample[];
    get validationChecks(): FieldExampleCheck[];
    get overallValidStatus(): CATEGORY_EXAMPLES_VALIDATION_STATUS;
    get selectedDetectorType(): DetectorType;
    set categorizationAnalyzer(analyzer: CategorizationAnalyzer);
    get categorizationAnalyzer(): CategorizationAnalyzer;
    get categorizationPerPartitionField(): string | null;
    set categorizationPerPartitionField(fieldName: string | null);
    get perPartitionCategorization(): boolean;
    set perPartitionCategorization(enabled: boolean);
    cloneFromExistingJob(job: Job, datafeed: Datafeed): void;
}
export {};
