[[cases-api-delete-cases]]
== Delete cases API
++++
<titleabbrev>Delete cases</titleabbrev>
++++

Deletes one or more cases.

[NOTE]
====
For the most up-to-date API details, refer to the
{kib-repo}/tree/{branch}/x-pack/plugins/cases/docs/openapi[open API specification].
====

=== {api-request-title}

`DELETE <kibana host>:<port>/api/cases?ids=["<case ID1>","<case ID2>"]`

`DELETE <kibana host>:<port>/s/<space_id>/api/cases?ids=["<case ID1>","<case ID2>"]`

=== {api-prereq-title}

You must have `read` or `all` privileges and the `delete` sub-feature privilege
for the *Cases* feature in the *Management*, *{observability}*, or *Security*
section of the <<kibana-feature-privileges,{kib} feature privileges>>, depending
on the `owner` of the cases you're deleting.

=== {api-path-parms-title}

`<space_id>`::
(Optional, string) An identifier for the space. If it is not specified, the
default space is used.

=== {api-query-parms-title}

`ids`::
(Required, string) The cases that you want to remove. To retrieve case IDs, use
<<cases-api-find-cases>>.
+
NOTE: All non-ASCII characters must be URL encoded.

=== {api-response-codes-title}

`204`::
   Indicates a successful call.

=== {api-examples-title}

Delete cases with these IDs:

* `2e3a54f0-6754-11ea-a1c2-e3a8bc9f7aca`
* `40b9a450-66a0-11ea-be1b-2bd3fef48984`

[source,console]
--------------------------------------------------
DELETE api/cases?ids=%5B%222e3a54f0-6754-11ea-a1c2-e3a8bc9f7aca%22%2C%2240b9a450-66a0-11ea-be1b-2bd3fef48984%22%5D
--------------------------------------------------
// KIBANA
