[[cases-api-update-comment]]
== Update case comment API
++++
<titleabbrev>Update comment</titleabbrev>
++++

Updates a comment in a case.

=== Request

`PATCH <kibana host>:<port>/api/cases/<case_id>/comments`

`PATCH <kibana host>:<port>/s/<space_id>/api/cases/<case_id>/comments`

=== Prerequisite

////
//TBD, for example
You must have `read` privileges for the *Cases* feature in the *Management*,
*{observability}*, or *Security* section of the
<<kibana-feature-privileges,{kib} feature privileges>>, depending on the
`owner` of the cases you're seeking.
////

=== Path parameters

`<case_id>`::
The identifier for the case. To retrieve case IDs, use
<<cases-api-find-cases>>.

`<space_id>`::
(Optional, string) An identifier for the space. If it is not specified, the default space is used.

=== Request body

`alertId`::
(Required*, string) The identifier for the alert. It is required only when `type` is `alert`.

`comment`::
(Required*, string) The updated comment. It is required only when `type` is `user`.

`id`::
(Required, string) The identifier for the comment. To retrieve comment IDs, use <<cases-api-get-all-case-comments>>.

`index`::
(Required*, string) The updated alert index. It is required only when `type` is `alert`.

`owner`::
(Required, string) The application that owns the case. It can be `cases`,
`observability`, or `securitySolution`.
+
NOTE: You cannot change the owner of a comment.

`type`::
(Required, string) The comment type, which can be `user` or `alert`.
+
NOTE: You cannot change the comment type.

`version`::
(Required, string) The current comment version. To retrieve version values, use <<cases-api-get-all-case-comments>>.

=== Response code

`200`::
   Indicates a successful call.

=== Example

Update comment ID `8af6ac20-74f6-11ea-b83a-553aecdb28b6` (associated with case
ID `293f1bc0-74f6-11ea-b83a-553aecdb28b6`):

[source,sh]
--------------------------------------------------
PATCH api/cases/293f1bc0-74f6-11ea-b83a-553aecdb28b6/comments
{
  "id": "8af6ac20-74f6-11ea-b83a-553aecdb28b6",
  "type": "user",
  "comment": "That is nothing - Ethan Hunt answered a targeted social
  media campaign promoting phishy pension schemes to IMF operatives.
  Even worse, he likes baked beans.",
  "owner": "securitySolution",
  "version": "Wzk1LDFd"
}
--------------------------------------------------
// KIBANA

The API returns the updated JSON case object with the updated comment, the user who updated the
comment, and the comment's ID, version, and update time. For example: 

[source,json]
--------------------------------------------------
{
  "id": "293f1bc0-74f6-11ea-b83a-553aecdb28b6",
  "version": "WzIwNjM2LDFd",
  "comments": [
    {
      "id": "8af6ac20-74f6-11ea-b83a-553aecdb28b6",
      "version": "WzIwNjM3LDFd",
      "type": "user",
      "comment": "That is nothing - Ethan Hunt answered a targeted social media campaign promoting phishy pension schemes to IMF operatives.",
      "created_at": "2020-04-02T15:28:03.034Z",
      "created_by": {
        "email": "moneypenny@hms.gov.uk",
        "full_name": "Ms Moneypenny",
        "username": "moneypenny"
      },
      "pushed_at": null,
      "pushed_by": null,
      "updated_at": "2020-04-02T15:34:01.118Z",
      "updated_by": {
        "email": "jbond@hms.gov.uk",
        "full_name": "James Bond",
        "username": "_007"
      }
    }
  ],
  "totalComment": 1,
  "title": "This case will self-destruct in 5 seconds",
  "tags": [
    "phishing",
    "social engineering"
  ],
  "description": "James Bond clicked on a highly suspicious email banner advertising cheap holidays for underpaid civil servants.",
  "closed_at": null,
  "closed_by": null,
  "created_at": "2020-04-02T15:25:19.088Z",
  "created_by": {
    "email": "ahunley@imf.usa.gov",
    "full_name": "Alan Hunley",
    "username": "ahunley"
  },
  "external_service": null,
  "owner": "securitySolution",
  "status": "open",
  "updated_at": "2020-04-02T15:34:01.118Z",
  "updated_by": {
    "email": "jbond@hms.gov.uk",
    "full_name": "James Bond",
    "username": "_007"
  }
}
--------------------------------------------------
