[[cases-api-get-tag]]
== Get tags API
++++
<titleabbrev>Get tags</titleabbrev>
++++

Aggregates and returns a list of case tags.

[NOTE]
====
For the most up-to-date API details, refer to the
{kib-repo}/tree/{branch}/x-pack/plugins/cases/docs/openapi[open API specification].
====

=== {api-request-title}

`GET <kibana host>:<port>/api/cases/tags`

`GET <kibana host>:<port>/s/<space_id>/api/cases/tags`

=== {api-prereq-title}

You must have `read` privileges for the *Cases* feature in the *Management*,
*{observability}*, or *Security* section of the
<<kibana-feature-privileges,{kib} feature privileges>>, depending on the
`owner` of the cases you're seeking.

=== {api-path-parms-title}

`<space_id>`::
(Optional, string) An identifier for the space. If it is not specified, the
default space is used.

=== {api-query-parms-title}

`owner`::
(Optional, string or array of strings) A filter to limit the retrieved tags to a
specific set of applications. Valid values are: `cases`, `observability`, and
`securitySolution`. If this parameter is omitted, the response contains tags
from all cases that the user has access to read.

=== {api-response-codes-title}

`200`::
   Indicates a successful call.

=== {api-examples-title}

[source,sh]
--------------------------------------------------
GET api/cases/tags
--------------------------------------------------
// KIBANA

The API returns a JSON object with tags from all the cases that the user has
access to read. For example: 

[source,json]
--------------------------------------------------
[
  "observability",
  "security",
  "tag 1",
  "tag 2"
]
--------------------------------------------------
