[[cases-api-find-connectors]]
== Find connectors API
++++
<titleabbrev>Find connectors</titleabbrev>
++++

Retrieves information about <<action-types,connectors>>.

In particular, only the connectors that are supported for use in cases are
returned. Refer to the list of supported external incident management systems in
<<add-case-connectors>>.

[NOTE]
====
For the most up-to-date API details, refer to the
{kib-repo}/tree/{branch}/x-pack/plugins/cases/docs/openapi[open API specification]. For a preview, check out <<case-apis>>.
====

=== {api-request-title}

`GET <kibana host>:<port>/api/cases/configure/connectors/_find`

`GET <kibana host>:<port>/s/<space_id>/api/cases/configure/connectors/_find`

=== {api-prereq-title}

You must have `read` privileges for the *{connectors-feature}* feature in the
*Management* section of the
<<kibana-feature-privileges,{kib} feature privileges>>.

=== {api-path-parms-title}

`<space_id>`::
(Optional, string) An identifier for the space. If it is not specified, the
default space is used.

=== {api-response-codes-title}

`200`::
   Indicates a successful call.

=== {api-examples-title}

[source,sh]
--------------------------------------------------
GET api/cases/configure/connectors/_find
--------------------------------------------------
// KIBANA

The API returns a JSON object describing the connectors and their settings:

[source,json]
--------------------------------------------------
[{
  "id":"61787f53-4eee-4741-8df6-8fe84fa616f7",
  "actionTypeId": ".jira",
  "name":"my-Jira",
  "isMissingSecrets":false,
  "config": {
    "apiUrl":"https://elastic.atlassian.net/",
    "projectKey":"ES"
  },
  "isPreconfigured":false,
  "isDeprecated": false,
  "referencedByCount":0
}]
--------------------------------------------------