[[cases-api-get-tag]]
== Get tags API
++++
<titleabbrev>Get tags</titleabbrev>
++++

Aggregates and returns a list of case tags.

=== Request

`GET <kibana host>:<port>/api/cases/tags`

`GET <kibana host>:<port>/s/<space_id>/api/cases/tags`

=== Prerequisite

You must have `read` privileges for the *Cases* feature in the *Management*,
*{observability}*, or *Security* section of the
<<kibana-feature-privileges,{kib} feature privileges>>, depending on the
`owner` of the cases you're seeking.

=== Path parameters

`<space_id>`::
(Optional, string) An identifier for the space. If it is not specified, the
default space is used.

=== Query parameters

`owner`::
(Optional, string or array of strings) A filter to limit the retrieved tags to a specific set of applications. Valid values are: `cases`, `observability`, and `securitySolution`. If this parameter is omitted, the response contains tags from all cases that the user has access to read.

==== Response code

`200`::
   Indicates a successful call.

==== Example

[source,sh]
--------------------------------------------------
GET api/cases/tags
--------------------------------------------------
// KIBANA

The API returns a JSON object with tags from all the cases that the user has access to read. For example: 

[source,json]
--------------------------------------------------
[
  "windows",
  "phishing",
  "social engineering",
  "bubblegum"
]
--------------------------------------------------
