[[cases-api-push]]
== Push case API
++++
<titleabbrev>Push case</titleabbrev>
++++

Pushes a case to an external service.

[NOTE]
====
For the most up-to-date API details, refer to the
{kib-repo}/tree/{branch}/x-pack/plugins/cases/docs/openapi[open API specification]. For a preview, check out <<case-apis>>.
====

=== {api-request-title}

`POST <kibana host>:<port>/api/cases/<case_id>/connector/<connector_id>/_push`

`POST <kibana host>:<port>/s/<space_id>/api/cases/<case_id>/connector/<connector_id>/_push`

=== {api-prereq-title}

You must have `all` privileges for the *{connectors-feature}* feature in the
*Management* section of the
<<kibana-feature-privileges,{kib} feature privileges>>. You must also have `all`
privileges for the *Cases* feature in the *Management*, *{observability}*, or
*Security* section of the {kib} feature privileges, depending on the
`owner` of the case you're pushing.

=== {api-path-parms-title}

`<case_id>`::
(Required, string) The identifier for the case. To retrieve case IDs, use
<<cases-api-find-cases>>.

`<connector_id>`::
(Required, string) The identifier for the connector. To retrieve connector IDs,
use <<cases-api-find-connectors>>.

<space_id>::
(Optional, string) An identifier for the space. If it is not specified, the
default space is used.

=== {api-response-codes-title}

`200`::
   Indicates a successful call.

=== {api-examples-title}

Push the case to an external service:

[source,sh]
--------------------------------------------------
POST api/cases/b917f300-0ed9-11ed-bd18-65557fe66949/connector/09f8c0b0-0eda-11ed-bd18-65557fe66949/_push
{}
--------------------------------------------------
// KIBANA

The API returns a JSON object representing the pushed case. For example:

[source,json]
--------------------------------------------------
{
  "id": "b917f300-0ed9-11ed-bd18-65557fe66949",
  "version": "WzE3NjgsM10=",
  "comments": [],
  "totalComment": 0,
  "totalAlerts": 0,
  "description": "A case description.",
  "title": "Case title 1",
  "tags": [
    "tag 1"
  ],
  "settings": {
    "syncAlerts": true
  },
  "owner": "cases",
  "duration": null,
  "severity": "low",
  "closed_at": null,
  "closed_by": null,
  "created_at": "2022-07-29T00:59:39.444Z",
  "created_by": {
    "username": "elastic",
    "email": null,
    "full_name": null
  },
  "status": "open",
  "updated_at": "2022-07-29T01:20:58.436Z",
  "updated_by": {
    "username": "elastic",
    "full_name": null,
    "email": null
  },
  "connector": {
    "id": "09f8c0b0-0eda-11ed-bd18-65557fe66949",
    "name": "My connector",
    "type": ".jira",
    "fields": {
      "issueType": "10006",
      "parent": null,
      "priority": "Low"
    }
  },
  "external_service": {
    "pushed_at": "2022-07-29T01:20:58.436Z",
    "pushed_by": {
      "username": "elastic",
      "full_name": null,
      "email": null
    },
    "connector_name": "My connector",
    "external_id": "71926",
    "external_title": "ES-554",
    "external_url": "https://cases.jira.com",
    "connector_id": "09f8c0b0-0eda-11ed-bd18-65557fe66949"
  }
}
--------------------------------------------------
