[[cases-api-get-case-activity]]
== Get case activity API
++++
<titleabbrev>Get case activity</titleabbrev>
++++

Returns all user activity for the specified case.

deprecated::[8.1.0]

=== {api-request-title}

`GET <kibana host>:<port>/api/cases/<case ID>/user_actions`

`GET <kibana host>:<port>/s/<space_id>/api/cases/<case ID>/user_actions`

=== {api-prereq-title}

You must have `read` privileges for the *Cases* feature in the *Management*,
*{observability}*, or *Security* section of the
<<kibana-feature-privileges,{kib} feature privileges>>, depending on the
`owner` of the cases you're seeking.

=== {api-path-parms-title}

`<case_id>`::
(Required, string) An identifier for the case to retrieve. Use 
<<cases-api-find-cases>> to retrieve case IDs.

`<space_id>`::
(Optional, string) An identifier for the space. If it is not specified, the
default space is used.

=== {api-response-codes-title}

`200`::
   Indicates a successful call.

=== {api-examples-title}

Gets all activity for case ID `a18b38a0-71b0-11ea-a0b2-c51ea50a58e2`:

[source,sh]
--------------------------------------------------
GET api/cases/a18b38a0-71b0-11ea-a0b2-c51ea50a58e2/user_actions
--------------------------------------------------
// KIBANA

The API returns a JSON object with all the activity for the case. For example: 

[source,json]
--------------------------------------------------
[
  {
    "created_at": "2022-12-16T14:34:48.709Z",
    "created_by": {
      "email": "",
      "full_name": "",
      "username": "elastic"
    },
    "owner": "securitySolution",
    "action": "create",
    "payload": {
      "title": "User actions",
      "tags": [
        "user",
        "actions"
      ],
      "connector": {
        "fields": null,
        "id": "none",
        "name": "none",
        "type": ".none"
      },
      "settings": {
        "syncAlerts": true
      },
      "owner": "cases",
      "severity": "low",
      "description": "migrating user actions",
      "status": "open"  
    },
    "type": "create_case",
    "action_id": "5275af50-5e7d-11ec-9ee9-cd64f0b77b3c",
    "case_id": "5257a000-5e7d-11ec-9ee9-cd64f0b77b3c",
    "comment_id": null
  },
  {
    "created_at": "2022-12-16T14:35:42.872Z",
    "created_by": {
      "email": "",
      "full_name": "",
      "username": "elastic"
    },
    "owner": "cases",
    "action": "add", 
    "payload": {
      "tags": ["bubblegum"]
    },
    "type": "tags",
    "action_id": "72e73240-5e7d-11ec-9ee9-cd64f0b77b3c",
    "case_id": "5257a000-5e7d-11ec-9ee9-cd64f0b77b3c",
    "comment_id": null
  }
]
--------------------------------------------------