[[cases-api-get-cases-by-alert]]
== Get cases by alert API
++++
<titleabbrev>Get cases by alert</titleabbrev>
++++

preview::[]

Uses an alert ID (`alert id`) to retrieve the case IDs of any cases the alert is attached to.

=== {api-request-title}

`GET <kibana host>:<port>/api/cases/alerts/<alert_id>`

`GET <kibana host>:<port>/s/<space_id>/api/cases/alerts/<alert_id>`

=== {api-prereq-title}

////
//TBD, for example
You must have `read` privileges for the *Cases* feature in the *Management*,
*{observability}*, or *Security* section of the
<<kibana-feature-privileges,{kib} feature privileges>>, depending on the
`owner` of the cases you're seeking.
////

=== {api-path-parms-title}

`<alert_id>`::
(Required, string) The alert identifier.

`<space_id>`::
(Optional, string) An identifier for the space. If it is not specified, the default space is used.

=== {api-query-parms-title}

`owner`::
(Optional, string or array of strings) A filter to limit the retrieved cases to
a specific set of applications. Valid values are: `cases`, `observability`,
and `securitySolution`. If this parameter is omitted, the response contains all
cases that the user has access to read.

=== {api-response-codes-title}

`200`::
   Indicates a successful call.

=== {api-example-title}

Return cases with the alert ID `293f1bc0-74f6-11ea-b83a-553aecdb28b6` attached to them:

[source,sh]
--------------------------------------------------
GET api/cases/alerts/293f1bc0-74f6-11ea-b83a-553aecdb28b6
--------------------------------------------------
// KIBANA

The API returns a JSON array containing any cases associated with the specified alert. For example:

[source,json]
--------------------------------------------------
[
    {
        "id": "8af6ac20-74f6-11ea-b83a-553aecdb28b6", <1>
        "title": "Test 1"
    },
    {
        "id": "a18b38a0-71b0-11ea-a0b2-c51ea50a58e2",
        "title": "Test 2"
    }
]
--------------------------------------------------

<1> The case identifier is identical to the saved object identifier for the case.