[[cases-api-set-default-connector]]
== Set default connector for cases API
++++
<titleabbrev>Set default connector</titleabbrev>
++++

Sets the default connector for cases.

=== {api-request-title}

`POST <kibana host>:<port>/api/cases/configure`

`POST <kibana host>:<port>/s/<space_id>/api/cases/configure`

=== {api-prereq-title}

You must have `all` privileges for the *Cases* feature in the *Management*,
*{observability}*, or *Security* section of the
<<kibana-feature-privileges,{kib} feature privileges>>, depending on the
`owner` of the cases.

=== {api-description-title}

Connectors are used to interface with external systems. Before you can set the
default connector for your cases, you must create it.
//Refer to <<register-connector>>.

If you do not set a default connector, you can simply provide the connector
details when you <<cases-api-create,create>> or <<cases-api-update,update>> a
case.

=== {api-path-parms-title}

`<space_id>`::
(Optional, string) An identifier for the space. If it is not specified, the
default space is used.

=== {api-request-body-title}

`closure_type`::
(Required, string) Specifies whether a case is automatically closed when it is
pushed to external systems.
+
--
Valid values are:

* `close-by-pushing`: Cases are automatically closed when they are pushed.
* `close-by-user`: Cases are not automatically closed.
--

`connector`::
(Required, object) An object that contains the connector configuration.
+
.Properties of `connector`
[%collapsible%open]
====
`fields`::
(Required, object) An object containing the connector fields.
+
--
If you do not want a default connector, specify `null` for this object. If you
want to omit any individual field, specify `null` as its value.

////
NOTE: Fields can be set but are not being used by case configuration. You can set the fields of the connector at <<cases-api-create>>.
////

For {ibm-r} connectors, specify:

`issueTypes`:::
(Required, array of numbers) The type of the incident.

`severityCode`:::
(Required, number) The severity code of the incident.

For {jira} connectors, specify:

`issueType`:::
(Required, string) The type of the issue.

`parent`:::
(Required, string) The key of the parent issue, when the issue type is `Sub-task`.

`priority`:::
(Required, string) The priority of the issue.

For {sn-itsm} connectors, specify:

`category`:::
(Required, string) The category of the incident.

`impact`:::
(Required, string) The effect an incident had on business.

`severity`:::
(Required, string) The severity of the incident.

`subcategory`:::
(Required, string) The subcategory of the incident.

`urgency`:::
(Required, string) The extent to which the incident resolution can be delayed.

For {sn-sir} connectors, specify:

`category`:::
(Required, string) The category of the incident.

`destIp`:::
(Required, string) A comma separated list of destination IPs.

`malwareHash`:::
(Required, string) A comma separated list of malware hashes.

`malwareUrl`:::
(Required, string) A comma separated list of malware URLs.

`priority`:::
(Required, string) The priority of the incident.

`sourceIp`:::
(Required, string) A comma separated list of source IPs.

`subcategory`:::
(Required, string) The subcategory of the incident.

For {swimlane} connectors, specify:

`caseId`:::
(Required, string) The case ID.
--

`id`::
(Required, string) The identifier for the connector. If you do not want a
default connector, use `none`. To retrieve connector IDs, use
<<cases-api-find-connectors>>.

`name`::
(Required, string) The name of the connector. If you do not want a default
connector, use `none`. To retrieve connector names, use
<<cases-api-find-connectors>>.

`type`::
(Required, string) The type of the connector. Valid values are: `.jira`, `.none`,
`.resilient`,`.servicenow`, `.servicenow-sir`, and `.swimlane`.
====

`owner`::
(Required, string) The application that owns the cases. Valid values are:
`cases`, `observability`, or `securitySolution`. This value affects
whether you're setting the default connector for {stack-manage-app},
{observability}, or {security-app}.

`settings`::
(Optional, object)
An object that contains the case settings.
+
.Properties of `settings`
[%collapsible%open]
====
`syncAlerts`:: 
(Required, boolean) Turns alert syncing on or off.
====

=== {api-response-codes-title}

`200`::
   Indicates a successful call.

=== {api-example-title}

Sets a {sn-itsm} connector as the default connector for cases in
{stack-manage-app}:

[source,sh]
--------------------------------------------------
POST api/cases/configure
{
  "owner": "cases",
  "connector": {
    "id": "131d4448-abe0-4789-939d-8ef60680b498",
    "name": "my-serviceNow",
    "type": ".servicenow",
    "fields": null,
  },
  "closure_type": "close-by-user"
}
--------------------------------------------------

The API returns the following response:

[source,json]
--------------------------------------------------
{
  "owner": "cases",
  "closure_type": "close-by-user",
  "created_at": "2022-04-02T01:09:02.303Z",
  "created_by": {
    "email": "moneypenny@hms.gov.uk",
    "full_name": "Ms Moneypenny",
    "username": "moneypenny"
  },
  "updated_at": null,
  "updated_by": null,
  "connector": {
    "id": "131d4448-abe0-4789-939d-8ef60680b498",
    "name": "my-serviceNow",
    "type": ".servicenow",
    "fields": null,
  },
  "mappings": [
    {
      "source": "title", 
      "target": "short_description",
      "action_type": "overwrite"
    },
    {
      "source":"description",
      "target":"description",
      "action_type":"overwrite"
    },
    {
      "source":"comments",
      "target":"work_notes",
      "action_type":"append"
    }
  ],
  "version": "WzE3NywxXQ==",
  "error": null,
  "id": "7349772f-421a-4de3-b8bb-2d9b22ccee30",
}
--------------------------------------------------
