[[cases-api-get-cases-by-alert]]
== Get cases by alert API
++++
<titleabbrev>Get cases by alert</titleabbrev>
++++

preview::[]

Returns the cases associated with a specific alert.

=== {api-request-title}

`GET <kibana host>:<port>/api/cases/alerts/<alert_id>`

`GET <kibana host>:<port>/s/<space_id>/api/cases/alerts/<alert_id>`

=== {api-prereq-title}

You must have `read` privileges for the *Cases* feature in the *Management*,
*{observability}*, or *Security* section of the
<<kibana-feature-privileges,{kib} feature privileges>>, depending on the
`owner` of the cases you're seeking.

=== {api-path-parms-title}

`<alert_id>`::
(Required, string) The alert identifier.

`<space_id>`::
(Optional, string) An identifier for the space. If it is not specified, the
default space is used.

=== {api-query-parms-title}

`owner`::
(Optional, string or array of strings) A filter to limit the retrieved cases to
a specific set of applications. Valid values are: `cases`, `observability`,
and `securitySolution`. If this parameter is omitted, the response contains all
cases that the user has access to read.

=== {api-response-codes-title}

`200`::
   Indicates a successful call.

=== {api-example-title}

Return cases associated with the alert ID
`09f0c261e39e36351d75995b78bb83673774d1bc2cca9df2d15f0e5c0a99a540`:

[source,sh]
--------------------------------------------------
GET api/cases/alerts/09f0c261e39e36351d75995b78bb83673774d1bc2cca9df2d15f0e5c0a99a540
--------------------------------------------------
// KIBANA

The API returns a JSON array containing the identifier and title of the cases.
For example:

[source,json]
--------------------------------------------------
[
    {
        "id": "8af6ac20-74f6-11ea-b83a-553aecdb28b6",
        "title": "Case 1"
    },
    {
        "id": "a18b38a0-71b0-11ea-a0b2-c51ea50a58e2",
        "title": "Case 2"
    }
]
--------------------------------------------------