[[cases-api-get-tag]]
== Get tags API
++++
<titleabbrev>Get tags</titleabbrev>
++++

Aggregates and returns all unique tags from all cases.

=== Request

`GET <kibana host>:<port>/api/cases/tags`

`GET <kibana host>:<port>/s/<space_id>/api/cases/tags`

=== Prerequisite

You must have `read` privileges for the *Cases* feature in the *Management*,
*{observability}*, or *Security* section of the
<<kibana-feature-privileges,{kib} feature privileges>>, depending on the
`owner` of the cases you're seeking.

=== Path parameters

`<case_id>`::
(Required, string) An identifier for the case to retrieve. Use 
<<cases-api-find-cases>> to retrieve case IDs.

`<space_id>`::
(Optional, string) An identifier for the space. If it is not specified, the
default space is used.

=== Query parameters

`owner`::
(Optional, string) Specifies the set of applications to limit the retrieved 
tags. If not specified, the response contains all tags that the user has access 
to read.

==== Response code

`200`::
   Indicates a successful call.

==== Example

Gets all tags for all cases:

[source,sh]
--------------------------------------------------
GET api/cases/tags
--------------------------------------------------
// KIBANA

The API returns a JSON object with all tags for all cases. For example: 

[source,json]
--------------------------------------------------
[
  "windows",
  "phishing",
  "social engineering",
  "bubblegum"
]
--------------------------------------------------