export declare const BASE_PATH: string;
export declare const GRADLE_BIN: string;
export declare const ES_BIN: string;
export declare const ES_PLUGIN_BIN: string;
export declare const ES_CONFIG = "config/elasticsearch.yml";
export declare const ES_KEYSTORE_BIN: string;
export declare const STATEFUL_ROLES_ROOT_PATH: string;
export declare const SERVERLESS_OPERATOR_USERS_PATH: string;
export declare const SERVERLESS_SERVICE_TOKENS_PATH: string;
export declare const SERVERLESS_USERS_PATH: string;
export declare const SERVERLESS_USERS_ROLES_PATH: string;
export declare const SERVERLESS_ROLES_ROOT_PATH: string;
export declare const SERVERLESS_ROLE_MAPPING_PATH: string;
export declare const SERVERLESS_SECRETS_PATH: string;
export declare const SERVERLESS_SECRETS_SSL_PATH: string;
export declare const SERVERLESS_JWKS_PATH: string;
export declare const SERVERLESS_IDP_METADATA_PATH: string;
export declare const SERVERLESS_OPERATOR_PATH: string;
export declare const SERVERLESS_UIAM_ENTRYPOINT_PATH: string;
export declare const SERVERLESS_UIAM_CERTIFICATE_BUNDLE_PATH: string;
export declare const SERVERLESS_RESOURCES_PATHS: string[];
export declare const SERVERLESS_CONFIG_PATH = "/usr/share/elasticsearch/config/";
export declare const SERVERLESS_FILES_PATH = "/usr/share/elasticsearch/config/files/";
