[[dashboard-import-api]]
== Dashboard import and export APIs

Import and export dashboards with the corresponding saved objects, such as visualizations, saved
searches, and index patterns.

WARNING: Do not write documents directly to the `.kibana` index. When you write directly
to the `.kibana` index, the data becomes corrupted and permanently breaks future {kib} versions.

[[dashboard-import-api-import]]
=== Import dashboard API

experimental[] Import dashboards and corresponding saved objects.

[[dashboard-api-import-request]]
==== Request

`POST /api/kibana/dashboards/import`

[[dashboard-api-import-params]]
==== Query parameters

`force`::
  (Optional, boolean) Overwrite any existing objects on ID conflict.
  
`exclude`::
  (Optional, array) Saved object types that you want to exclude from the import.

[[dashboard-api-import-request-body]]
==== Request body

Use the complete response body from the <<dashboard-api-export, Export dashboard API>> as the request body. Do not manually construct a payload to the endpoint.

[[dashboard-api-import-response-body]]
==== Response body

`objects`:: 
  (array) A top level property that includes the saved objects. 

[[dashboard-api-import-codes]]
==== Response code

`200`::
  Indicates a successful call, even if there are errors importing individual saved objects. If there ar errors, the error information is returned in the response body on an object-by-object basis.

[[dashboard-api-import-example]]
==== Example

[source,js]
--------------------------------------------------
POST api/kibana/dashboards/import?exclude=index-pattern
{
  "objects": [
    {
      "id": "80b956f0-b2cd-11e8-ad8e-85441f0c2e5c",
      "type": "visualization",
      "updated_at": "2018-09-07T18:40:33.247Z",
      "version": 1,
      "attributes": {
        "title": "Count Example",
        "visState": "{\"title\":\"Count Example\",\"type\":\"metric\",\"params\":{\"addTooltip\":true,\"addLegend\":false,\"type\":\"metric\",\"metric\":{\"percentageMode\":false,\"useRanges\":false,\"colorSchema\":\"Green to Red\",\"metricColorMode\":\"None\",\"colorsRange\":[{\"from\":0,\"to\":10000}],\"labels\":{\"show\":true},\"invertColors\":false,\"style\":{\"bgFill\":\"#000\",\"bgColor\":false,\"labelColor\":false,\"subText\":\"\",\"fontSize\":60}}},\"aggs\":[{\"id\":\"1\",\"enabled\":true,\"type\":\"count\",\"schema\":\"metric\",\"params\":{}}]}",
        "uiStateJSON": "{}",
        "description": "",
        "version": 1,
        "kibanaSavedObjectMeta": {
          "searchSourceJSON": "{\"index\":\"90943e30-9a47-11e8-b64d-95841ca0b247\",\"query\":{\"query\":\"\",\"language\":\"lucene\"},\"filter\":[]}"
        }
      }
    },
    {
      "id": "90943e30-9a47-11e8-b64d-95841ca0b247",
      "type": "index-pattern",
      "updated_at": "2018-09-07T18:39:47.683Z",
      "version": 1,
      "attributes": {
        "title": "kibana_sample_data_logs",
        "timeFieldName": "timestamp",
        "fields": "<truncated for example>",
        "fieldFormatMap": "{\"hour_of_day\":{}}"
      }
    },
    {
      "id": "942dcef0-b2cd-11e8-ad8e-85441f0c2e5c",
      "type": "dashboard",
      "updated_at": "2018-09-07T18:41:05.887Z",
      "version": 1,
      "attributes": {
        "title": "Example Dashboard",
        "hits": 0,
        "description": "",
        "panelsJSON": "[{\"gridData\":{\"w\":24,\"h\":15,\"x\":0,\"y\":0,\"i\":\"1\"},\"version\":\"7.0.0-alpha1\",\"panelIndex\":\"1\",\"type\":\"visualization\",\"id\":\"80b956f0-b2cd-11e8-ad8e-85441f0c2e5c\",\"embeddableConfig\":{}}]",
        "optionsJSON": "{\"useMargins\":true,\"hidePanelTitles\":false}",
        "version": 1,
        "timeRestore": false,
        "kibanaSavedObjectMeta": {
          "searchSourceJSON": "{\"query\":{\"query\":\"\",\"language\":\"lucene\"},\"filter\":[]}"
        }
      }
    }
  ]
}
--------------------------------------------------
// KIBANA

[float]
[[dashboard-api-export]]
=== Export dashboard API

experimental[] Export dashboards and corresponding saved objects.

[[dashboard-api-export-request]]
==== Request

`GET /api/kibana/dashboards/export`

[[dashboard-api-export-params]]
==== Query parameters

`dashboard`::
  (Required, array|string) The IDs of the dashboards that you want to export.

[[dashboard-api-export-response-body]]
==== Response body

`objects`:: 
  (array) A top level property that includes the saved objects. The order of the objects is not guaranteed. Use the exact response body as the request body for the corresponding <<dashboard-import-api-import, Import dashboard API>>.
  
[[dashboard-api-export-codes]]
==== Response code

`200`::
  Indicates a successful call.

[float]
[[dashboard-api-export-example]]
==== Example

[source,js]
--------------------------------------------------
GET api/kibana/dashboards/export?dashboard=942dcef0-b2cd-11e8-ad8e-85441f0c2e5c <1>
--------------------------------------------------
// KIBANA

<1> In this example, `942dcef0-b2cd-11e8-ad8e-85441f0c2e5c` is the dashboard ID.

