[[saved-objects-api]]
== Saved objects APIs

Manage {kib} saved objects, including dashboards, visualizations, and more.

WARNING: Do not write documents directly to the `.kibana` index. When you write directly
to the `.kibana` index, the data becomes corrupted and permanently breaks future {kib} versions.

NOTE: For managing {kib} index patterns, use the <<index-patterns-api, index patterns API>>.

The following saved objects APIs are available: 

* <<saved-objects-api-get, Get object API>> to retrieve a single {kib} saved object by ID

* <<saved-objects-api-resolve, Resolve object API>> to retrieve a single {kib} saved object by ID, using any legacy URL alias if it exists

* <<saved-objects-api-bulk-get, Bulk get objects API>> to retrieve multiple {kib} saved objects by ID

* <<saved-objects-api-bulk-resolve, Bulk resolve objects API>> to retrieve multiple {kib} saved objects by ID, using any legacy URL aliases if they exist

* <<saved-objects-api-find, Find objects API>> to retrieve a paginated set of {kib} saved objects by various conditions

* <<saved-objects-api-create, Create saved object API>> to create {kib} saved objects

* <<saved-objects-api-bulk-create, Bulk create saved objects API>> to create multiple {kib} saved objects

* <<saved-objects-api-update, Update object API>> to update the attributes for existing {kib} saved objects

* <<saved-objects-api-bulk-update, Bulk update objects API>> to update the attributes for multiple existing {kib} saved objects

* <<saved-objects-api-delete, Delete object API>> to remove {kib} saved objects

* <<saved-objects-api-export, Export objects API>> to retrieve sets of saved objects that you want to import into {kib}

* <<saved-objects-api-import, Import objects API>> to create sets of {kib} saved objects from a file created by the export API

* <<saved-objects-api-resolve-import-errors, Resolve import errors API>> to resolve errors from the import API

* <<saved-objects-api-rotate-encryption-key, Rotate encryption key API>> to rotate the encryption key for encrypted saved objects

include::saved-objects/get.asciidoc[]
include::saved-objects/bulk_get.asciidoc[]
include::saved-objects/find.asciidoc[]
include::saved-objects/create.asciidoc[]
include::saved-objects/bulk_create.asciidoc[]
include::saved-objects/update.asciidoc[]
include::saved-objects/bulk_update.asciidoc[]
include::saved-objects/delete.asciidoc[]
include::saved-objects/export.asciidoc[]
include::saved-objects/import.asciidoc[]
include::saved-objects/resolve_import_errors.asciidoc[]
include::saved-objects/resolve.asciidoc[]
include::saved-objects/bulk_resolve.asciidoc[]
include::saved-objects/rotate_encryption_key.asciidoc[]
