/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Elastic Security - Timeline - Get Timeline API
 *   version: 2023-10-31
 */

import { z } from '@kbn/zod';

import { TimelineResponse } from '../model/components.gen';

export type GetTimelineRequestQuery = z.infer<typeof GetTimelineRequestQuery>;
export const GetTimelineRequestQuery = z.object({
  /**
   * The ID of the template timeline to retrieve
   */
  template_timeline_id: z.string().optional(),
  /**
   * The ID of the Timeline to retrieve.
   */
  id: z.string().optional(),
});
export type GetTimelineRequestQueryInput = z.input<typeof GetTimelineRequestQuery>;

export type GetTimelineResponse = z.infer<typeof GetTimelineResponse>;
export const GetTimelineResponse = z.union([
  z.object({
    data: z.object({
      getOneTimeline: TimelineResponse,
    }),
  }),
  z.object({}),
]);
