[[<ACTION-TYPE>-action-type]]
== <ACTION-TYPE> connector and action
++++
<titleabbrev><ACTION-TYPE></titleabbrev>
++++

Include a short description of the connector type.

[float]
[[define-<ACTION-TYPE>-ui]]
=== Create connectors in {kib}

You can create connectors in *{stack-manage-app} > {connectors-ui}*
or as needed when you're creating a rule.

// Optionally add a screenshot

[float]
[[<ACTION-TYPE>-connector-configuration]]
==== Connector configuration

<ACTION-TYPE> connectors have the following configuration properties:

////
List of user-facing connector configurations. This should align with the fields available in the Create connector flyout form for this connector type.
////

Property1:: A short description of this property.
Property2:: A short description of this property with format hints. This can be specified in `this specific format`.

[float]
[[preconfigured-<ACTION-TYPE>-configuration]]
=== Create preconfigured connectors

If you are running {kib} on-prem, you can define connectors by
adding `xpack.actions.preconfigured` settings to your `kibana.yml` file.
For example:

////
Example preconfigured format for this connector type
////

[source,text]
--
xpack.actions.preconfigured:
  my-<ACTION-TYPE>:
    name: preconfigured-<ACTION-TYPE>-connector-type
    actionTypeId: .<ACTION-TYPE>
    config:
      property1: value1
      property2: value2
    secrets:
      property3: value3
--

////
List of properties from the ConfigSchema and SecretsSchema for this action type.
////
Config defines information for the connector type.

`property1`:: A short description of this property.
`property2`:: A short descriptionn of this property.

Secrets defines sensitive information for the connector type.

`property3`:: A short descriptionn of this property.

[float]
[[<ACTION-TYPE>-action-configuration]]
=== Test connectors

You can test connectors with the <<execute-connector-api,run connector API>> or
as you're creating or editing the connector in {kib}.

<ACTION-TYPE> actions have the following properties.

////
List of user-facing action configurations. This should align with the fields available in the Action section of the Create/Update alert flyout.
////

Property1:: A short description of this property.
Property2:: A short description of this property with format hints. This can be specified in `this specific format`.

////
Optional - additional configuration details here
[[configuring-<ACTION-TYPE>]]
==== Configure <ACTION-TYPE>
////
