[[api]]
= REST API

[partintro]
--
Some {kib} features are provided via a REST API, which is ideal for creating an integration with {kib}, or automating
certain aspects of configuring and deploying {kib}.

Each API has one of the following labels:

* *Stable* APIs should be safe to use extensively in production. Any breaking
changes to these APIs should only occur in major versions and will be
clearly documented in the breaking changes documentation for that release.

* *Beta* APIs are on track to become stable, permanent features of {kib}.
Caution should be exercised in their use since it is possible we'd have to make
a breaking change to these APIs in a minor version, but we'll avoid this
wherever possible.

* *Experimental* APIs are just that - an experiment. An experimental API might
have breaking changes in any version of {kib}, or it might even be removed
entirely.

If a label is missing from an API, it is considered `experimental`.

NOTE: You cannot access the APIs via the Console in {kib}.

[float]
== APIs
* <<features-api>>
* <<spaces-api>>
* <<role-management-api>>
* <<saved-objects-api>>
* <<dashboard-import-api>>
* <<logstash-configuration-management-api>>
* <<url-shortening-api>>
* <<upgrade-assistant-api>>
--

include::api/features.asciidoc[]
include::api/spaces-management.asciidoc[]
include::api/role-management.asciidoc[]
include::api/saved-objects.asciidoc[]
include::api/dashboard-import.asciidoc[]
include::api/logstash-configuration-management.asciidoc[]
include::api/url-shortening.asciidoc[]
include::api/upgrade-assistant.asciidoc[]
