
[role="xpack"]
[[canvas]]
= Canvas

[partintro]
--

Canvas is a data visualization and presentation tool that is sits within Kibana. With Canvas, you can pull live data directly from Elasticsearch, and combine the data with colors, images, text, and your imagination to create dynamic, multi-page, pixel-perfect displays. If you are a little bit creative, a little bit technical, and a whole lot curious, then Canvas is for you. 

With Canvas, you can:

* Create and personalize your work space with backgrounds, borders, colors, fonts, and more. 

* Customize your workpad with your own visualizations, such as images and text.

* Show off your data with charts, graphs, progress monitors, and more.

* Focus the data you want to display with filters.

//<<link to some examples of Canvas in use>>

For a quick overview of Canvas, watch link:https://www.youtube.com/watch?v=ZqvF_5-1xjQ[Stand out with Canvas].
//When Dave moves these videos, update this link.

--

include::canvas/canvas-getting-started.asciidoc[]

include::canvas/canvas-workpad.asciidoc[]

include::canvas/canvas-function-reference.asciidoc[]

include::canvas/canvas-common-functions.asciidoc[]

include::canvas/canvas-server-functions.asciidoc[]

include::canvas/canvas-client-functions.asciidoc[]

include::canvas/canvas-tinymath-functions.asciidoc[]
