[[release-notes]]
= {kib} Release Notes
++++
<titleabbrev>Release Notes</titleabbrev>
++++

[partintro]
--
// Use these for links to issue and pulls. Note issues and pulls redirect one to
// each other on Github, so don't worry too much on using the right prefix.
:issue: https://github.com/elastic/kibana/issues/
:pull: https://github.com/elastic/kibana/pull/

This section summarizes the changes in each release.

* <<release-notes-7.0.0-alpha1>>

--

[[release-notes-7.0.0]]
== {kib} 7.0.0

//[float]
//[[breaking-7.0.0]]
//=== Breaking Changes

//[float]
//=== Breaking Java Changes

//[float]
//=== Deprecations

//[float]
//=== New Features

//[float]
//=== Enhancements

//[float]
//=== Bug Fixes

//[float]
//=== Regressions

//[float]
//=== Known Issues

[[release-notes-7.0.0-alpha1]]
== {kib} 7.0.0-alpha1

[float]
[[breaking-7.0.0]]
=== Breaking changes

For more details about breaking changes in this release, see 
<<breaking-changes-7.0, Breaking changes in 7.0>>.

Discover::
* Does not apply `query:queryString:options` to `query_string` filters {pull}15640[#15640]
* Removes `default_field` from `query:queryString:options` {pull}18966[#18966]

Monitoring::
* Removes `node_resolver` setting {pull}21181[#21181]

Operations::
* Removes tribe node support {pull}16397[#16397]
* Creates separate startup scripts for development and production {pull}13806[#13806]
* Sets default port based on protocol  {pull}21564[#21564]
* Removes deprecated `/shorten` API {pull}21861[#21861]

[float]
[[deprecation-7.0.0]]
=== Deprecations

Geo::
* Fixes legacy tilemap loading {pull}22095[#22095]

[float]
[[K7-design-7.0.0]]
=== K7 UI Design

{kib} 7.0.0-alpha1 includes a new design for {kib} called K7. In this early stage, 
K7 is still a little rough around the edges. If you'd like to switch back to the 
existing K6 design, go to *Management > Advanced Settings* and turn 
off the *k7design* setting. The option to switch to the old design 
will be removed before 7.0.0 GA.

[float]
[[enhancement-7.0.0]]
=== Enhancements

Machine Learning::
* Updates job type and APM module icon to new designs {pull}25380[#25380]
* Allows model plot enablement via checkbox in  MultiMetric/Population Job creation {pull}24914[#24914]
* Adds support for the rare detector for charts in Anomaly Explorer and Singe Metric viewer {pull}21524[#21524]

Reporting::
* Adds png output to reports {pull}24759[#24759]
* Sorts ascending on sort order first then ascending on name. Any menu item 
without a sort order gets set to zero. {pull}25058[#25058]

Visualizations::
* Adds a console.error for visualize errors {pull}24581[#24581]

[float]
[[bug-7.0.0]]
=== Bug fixes

APM::
* Overrides EUI chart default styles for gridlines {pull}21723[#21723]
* Adds section titles to span detail modal {pull}20717[#20717]

Canvas::
* Fixes duplicate `Value` options in math select value {pull}25556[#25556]
* Gets correct plugins path {pull}25448[#25448]
* Quotes the index pattern in SQL input {pull}25488[#25488]
* Decreases the size of tray toggle {pull}25470[#25470]
* Improves the plugin pre-build {pull}25267[#25267]

Dashboard::
* Removes `dashboardContext` function and makes Timelion, Vega, and Time Series 
Visual Builder use `buildEsQuery` {pull}23227[#23227]

Design::
* Converts Security UI from LESS to Sass {pull}25079[#25079]
* Adds boilerplate Sass for Kibana core {pull}21185[#21185]

Discover::
* Adds debug code to flaky field_data test {pull}15535[#15535]
* Gets even more debug info for flaky field_data test {pull}17627[#17627]

Geo::
* Fixes feature/align map config settings {pull}19450[#19450]

Kibana App::

* Adds warning to the `documentation_links` file about link validation gotcha {pull}24786[#24786]
* Adds workaround for `getDerivedStateFromProps` change in react 16.4 {pull}25142[#25142]

Kibana Home &amp; Add Data::
* Fixes "Set up index patterns" link on home page {pull}16128[#16128]

Machine Learning::
* Shows useful error on invalid query in JobList search bar {pull}25153[#25153]
* Adds user privilege check to Jobs List group selector control {pull}25225[#25225]
* Fixes file data viz file size check and formats as bytes {pull}25295[#25295]
* Fixes the layout of the cards in the Data Visualizer on IE {pull}25383[#25383]
* Adds better error reporting for reading and importing data {pull}24269[#24269]
* Displays an ordinal y axis for low cardinality rare charts {pull}24852[#24852]
* Fixes typo in job validation message {pull}25130[#25130]
* Removes deprecated `angularjs` based jobs list and related code {pull}25216[#25216]

Management::
* Adds boilerplate for remote clusters management app {pull}25369[#25369]
* Adds `ignore_failure` to ingest common auto complete in console {pull}24915[#24915]
* Removes support for expression-based scripted fields {pull}14310[#14310]
* Adds WatchErrors to capture invalid watches {pull}23887[#23887]
* Rewords the translation id for error with missing property in Watcher {pull}24753[#24753]

Monitoring::
* Renames Monitoring `FormattedMessage` to `FormattedAlert` {pull}24197[#24197]
* Uses the cluster name from metadata if it exists {pull}24495[#24495]

Operations::
* Removes node fallback from kibana-keystore {pull}15066[#15066]
* Adds debug script to set inspect flags {pull}15967[#15967]
* Uses snake case for scripts/kibana-keystore.js and scripts/kibana-plugin.js {pull}15331[#15331]
* Updates license info in package.json {pull}20353[#20353]
* Fixes error log formatting {pull}24788[#24788]
* Matches chalk dependency version on Kibana with the one used on X-Pack {pull}20621[#20621]
* Fixes non-conforming licenses on devDependencies and adds the ability to whitelist devOnly licenses {pull}23859[#23859]
* Adds jsxa11y into eslint rules {pull}23932[#23932]
* Reverts Bump react-grid-layout to 0.16.0 {pull}14912[#14912]
* Reverts breaking change for Status API {pull}21927[#21927]
* Converts `utils/collection` to TypeScript {pull}23992[#23992]
* Removes usage of update_all_types {pull}16406[#16406]
* Improves the `yarn kbn bootstrap` speed by using yarn workspaces for packages inside `packages/*` and `x-pack` {pull}24095[#24095]
* Runs jenkins:unit task with dev flag in order to run license check {pull}19832[#19832]
* Does not break on startup in debug mode {pull}19219[#19219]


Platform::
* Transforms plugin deprecations before checking for unused settings {pull}21294[#21294]
* Expands list of restricted globals in `eslint-config-kibana` {pull}15798[#15798]
* Makes logs easier to read on Windows with chalk colors {pull}15557[#15557]

Querying &amp; Filtering::
* Fixes wildcard queries against the default field {pull}24778[#24778]

Reporting::
* Returns promise in Reporting jobs API {pull}24769[#24769]

Security::
* Implements the K7 login screen {pull}23512[#23512]

Sharing::

* Fixes issue with debounce function running after component was unmounted {pull}15045[#15045]

Visualizations::
* Defaults the scroll wheel zoom to false on Vega maps {pull}21169[#21169]
* Fixes problem within the input_vis_control plugin that prevents it from updating correctly 
if the field is switched, and then switched back to the previous field {pull}25164[#25164]
* Uses `vega-nocanvas` instead of vega lib {pull}16137[#16137]
* Migrates visualization from Angular to React {pull}16425[#16425]
* Fixes maps for reporting (#15272) {pull}15358[#15358]
* Stops creation of nested search source per postflightrequest {pull}20373[#20373]
* Moves inspector code from Vis to embeddable visualize handler {pull}24112[#24112]
* Removes inspector from Vis {pull}24112[#24112]




