[[release-notes]]
= Release notes

[partintro]
--
// Use these for links to issue and pulls. Note issues and pulls redirect one to
// each other on Github, so don't worry too much on using the right prefix.
:issue: https://github.com/elastic/kibana/issues/
:pull: https://github.com/elastic/kibana/pull/

This section summarizes the changes in each release.

* <<release-notes-8.0.0-alpha1>>

--


[[release-notes-8.0.0-alpha1]]
== {kib} 8.0.0-alpha1

coming[8.0.0]

The following changes have been released for the first time in {kib} 8.0.0-alpha1.

[float]
[[breaking-changes-8.0.0]]
=== Breaking changes

Breaking changes can prevent your application from optimal operation and performance.

1. Review the breaking changes.

2. Mitigate the impact to your application.

3. To complete the upgrade, use the <<upgrade-assistant,Upgrade Assistant>>.

// tag::notable-breaking-changes[]

[float]
[[enterprise-search-change]]
==== Enterprise Search changes

[discrete]
[[breaking-106307]]
.Required security plugin in 8.0
[%collapsible]
====
*Details* +
Enterprise Search now requires that you enable X-Pack Security. For more information, refer to {kibana-pull}106307[#106307]

*Impact* +
Enable X-Pack Security.
====

[float]
[[index-pattern-change]]
==== Index pattern changes

[discrete]
[[breaking-35173]]
.Removed support for time-based interval index patterns
[%collapsible]
====
*Details* +
Time-based interval index patterns were deprecated in 5.x. In 6.x, you could no longer create time-based interval index patterns, but they continued to function as expected. Support for these index patterns has been removed in 8.0. For more information, refer to {kibana-pull}35173[#35173]

*Impact* +
You must migrate your time_based index patterns to a wildcard pattern. For example, logstash-*. 
====

[float]
[[operations-changes]]
==== Operations changes

[discrete]
[[breaking-93835]]
.Removed platform from archive root directory
[%collapsible]
====
*Details* +
For the `.tar.gz` and `.zip` archives, `platform` has been removed from the `root` folder name. For more information, refer to {kibana-pull}93835[#93835]

*Impact* +
The `root` folder name now appears as `kibana-8.0.0-SNAPSHOT-linux-aarch64.tar.gz -> kibana-8.0.0-SNAPSHOT`.
====
      
[discrete]
[[breaking-90511]]
.Removed default support for TLS v1.0 and v1.1
[%collapsible]
====
*Details* +
The default support for TLS v1.0 and v1.1 has been removed. For more information, refer to {kibana-pull}90511[#90511]

*Impact* +
To enable support, set the environment variable to `NODE_OPTIONS=--tls-min-1.0`.
====
           
[discrete]
[[breaking-74424]]
.Removed support for sysv init
[%collapsible]
====
*Details* +
Systems that don't have `service` aliased to use kibana.service are unable to use `service start kibana`. For more information, refer to {kibana-pull}74424[#74424]

*Impact* +
If your system doesn't have `service` aliased to use kibana.service, use `systemctl start kibana.service`.
====
       
[discrete]
[[breaking-42353]]
.Disabled response logging as a default
[%collapsible]
====
*Details* +
By default, responses are not logged. Previously, responses were logged if `logging.json` was set to `true`, `logging.dest` was specified, or a TTY was detected. For more information, refer to {kibana-pull}42353[#42353]

*Impact* +
To log responses, set `logging.events.response=*` in kibana.yml.
====

[float]
[[reporting-changes-8.0.0-alpha1]]
==== Reporting changes
      
[discrete]
[[breaking-52539]]
.Removed legacy Reporting job params compatibility shim
[%collapsible]
====
*Details* +
*Reporting* is no longer compatible with POST URL snippets generated with {kib} 6.2.0 and earlier. For more information, refer to {kibana-pull}52539[#52539]

*Impact* +
If you use POST URL snippets to automatically generate PDF reports, regenerate the POST URL strings.
====

[float]
[[rest-api-changes]]
==== Security changes

[discrete]
[[breaking-47929]]
.Removed `/api/security/v1/saml` route
[%collapsible]
====
*Details* +
The `/api/security/v1/saml` route has been removed and is reflected in the kibana.yml `server.xsrf.whitelist` setting, {es}, and the Identity Provider SAML settings. For more information, refer to {kibana-pull}47929[#47929]

*Impact* +
Use the `/api/security/saml/callback` route.
====

[discrete]
[[breaking-41700]]
.Reject legacy browsers by default
[%collapsible]
====
*Details* +
To provide the maximum level of protection for most installations, the csp.strict config is now enabled by default. Legacy browsers, such as IE11, are unable to access {kib} unless explicitly enabled. For more information, refer to {kibana-pull}41700[#41700]

*Impact* +
To enable support for legacy browsers, set `csp.strict: false` in kibana.yml.
====

[float]
[[settings-changes-8.0.0-alpha1]]
==== Settings changes
      
[discrete]
[[breaking-106061]]
.Use new session timeout defaults 
[%collapsible]
====
*Details* +
The default values for the session timeout `xpack.security.session.{lifespan|idleTimeout}` settings have changed. For more information, refer to {kibana-pull}106061[#106061]

*Impact* +
Use the following default values:

* `xpack.security.session.idleTimeout: 1h`
* `xpack.security.session.lifespan: 30d`
====

[discrete]
[[breaking-87114]]
.Removed support for setting `server.host` to '0'
[%collapsible]
====
*Details* +
Support for configuring {kib} with `0` as the `server.host` has been removed. For more information, refer to {kibana-pull}87114[#87114]

*Impact* +
You are now unable to use `0` as the `server.host`.
====

[discrete]
[[breaking-38657]]
.Removed `xpack.security.authProviders` and `xpack.security.public`
[%collapsible]
====
*Details* +
The `xpack.security.public` and `xpack.security.authProviders` settings have been removed. For more information, refer to {kibana-pull}38657[#38657]

*Impact* +
Use the `xpack.security.authc.saml.realm` setting.
====

[discrete]
[[breaking-22696]]
.Removed useUTC deprecation
[%collapsible]
====
*Details* +
The `logging.useUTC` setting has been removed. For more information, refer to {kibana-pull}22696[#22696]

*Impact* +
The default timezone is UTC. To change the timezone, set `logging.timezone: false` in kibana.yml. Change the timezone when the system, such as a docker container, is configured for a nonlocal timezone.  
====  

// end::notable-breaking-changes[]

[float]
[[deprecations-8.0.0]]
=== Deprecations

The following functionality is deprecated in 8.0.0, and will be removed in 9.0.0. Deprecated functionality does not have an immediate impact on your application, but we strongly recommend you make the necessary updates after you upgrade to 8.0.0.

[discrete]
[[deprecation-74424]]
.Removed support for SysV init
[%collapsible]
====
*Details* +
Systems that don't have `service` aliased to use kibana.service are unable to use `service start kibana`. For more information, refer to {kibana-pull}74424[#74424]

*Impact* +
If your system doesn't have `service` aliased to use kibana.service, use `systemctl start kibana.service`.
====
      
[discrete]
[[deprecation-33603]]
.Removed `xpack:defaultAdminEmail` setting
[%collapsible]
====
*Details* +
The `xpack:default_admin_email` setting for monitoring use has been removed. For more information, refer to {kibana-pull}33603[#33603]

*Impact* +
Use the `xpack.monitoring.clusterAlertsEmail` in kibana.yml.
====

[float]
[[enhancements-and-bug-fixes-v8.0.0]]
=== Bug fix

The 8.0.0-alpha1 release includes the following bug fix.

Operations::
* Moves systemd service to /usr/lib/systemd/system {kibana-pull}83571[#83571]

//[[release-notes-8.0.0]]
//== {kib} 8.0.0

//coming::[8.0.0]

