[[release-notes]]
= Release notes

[partintro]
--
// Use these for links to issue and pulls. Note issues and pulls redirect one to
// each other on Github, so don't worry too much on using the right prefix.
:issue: https://github.com/elastic/kibana/issues/
:pull: https://github.com/elastic/kibana/pull/

Review important information about the {kib} 8.0.0 releases.

* <<release-notes-8.0.0>>
* <<release-notes-8.0.0-rc2>>
* <<release-notes-8.0.0-rc1>>
* <<release-notes-8.0.0-beta1>>
* <<release-notes-8.0.0-alpha2>>
* <<release-notes-8.0.0-alpha1>>

--
[[release-notes-8.0.0]]
== {kib} 8.0.0

Review the {kib} 8.0.0 changes, then use the {kibana-ref-all}/7.17/upgrade-assistant.html[Upgrade Assistant] to complete the upgrade.

[float]
[[breaking-changes-8.0.0]]
=== Breaking change

Breaking changes can prevent your application from optimal operation and performance.
Before you upgrade to 8.0.0, review the breaking change, then mitigate the impact to your application.

// tag::notable-breaking-changes[]

[discrete]
[[breaking-123754]]
.Removes the `console.ssl` setting
[%collapsible]
====
*Details* +
The `console.ssl` setting has been removed. For more information, refer to {kibana-pull}123754[#123754].

*Impact* +
Before you upgrade to 8.0.0, remove `console.ssl` from kibana.yml.
====

// end::notable-breaking-changes[]


To review the breaking changes in previous versions, refer to the following: 

<<breaking-changes-8.0.0-rc2,8.0.0-rc2>> | <<breaking-changes-8.0.0-rc1,8.0.0-rc1>> | <<breaking-changes-8.0.0-beta1,8.0.0-beta1>> | <<breaking-changes-8.0.0-alpha2,8.0.0-alpha2>> | 
<<breaking-changes-8.0.0-alpha1,8.0.0-alpha1>>

[float]
[[deprecations-8.0.0]]
=== Deprecation

The following functionality is deprecated in 8.0.0, and will be removed in 9.0.0.
Deprecated functionality does not have an immediate impact on your application, but we strongly recommend
you make the necessary updates after you upgrade to 8.0.0.

[discrete]
[[deprecation-123229]]
.Removes support for `monitoring.cluster_alerts.allowedSpaces`
[%collapsible]
====
*Details* +
The `monitoring.cluster_alerts.allowedSpaces` setting, which {kib} uses to create Stack Monitoring alerts, has been removed. For more information, refer to {kibana-pull}123229[#123229].

*Impact* +
Before you upgrade to 8.0.0, remove `monitoring.cluster_alerts.allowedSpaces` from kibana.yml.
====

To review the deprecations in previous versions, refer to the following:

<<deprecations-8.0.0-rc1,8.0.0-rc1>> | <<deprecations-8.0.0-alpha1,8.0.0-alpha1>>

[float]
[[known-issue-8.0.0]]
=== Known issue

[discrete]
[[known-issue-123550]]
.Importing and copying saved objects causes weak links to break
[%collapsible]
====
*Details* +
{kib} supports weak links in some saved objects. For example, a dashboard may include a Markdown panel that contains a relative URL to
another dashboard. Weak links are defined by free text, _not_ the saved object's relationships, and can break if **both** of the following
conditions are true:

* You are importing saved objects into multiple spaces, _OR_ you are copying saved objects into another space
* Before you upgraded to 8.0.0, the saved objects did not already exist in the destinations

In 8.0.0 and later, weak links break because <<saved-object-ids-impact-when-using-import-and-copy,saved object IDs can change during import or copy>>.
This applies to both the UI and the API.
This issue will be fixed 8.0.1 and 8.1.0. For more information, refer to {kibana-issue}123550[#123550].

*Impact* +
Saved objects in 7.x that are migrated during upgrade are **not** impacted.
Only _new_ saved objects that are imported or copied _multiple times_ (causing object IDs to change) are impacted.
If you are impacted, you can re-import or re-copy your saved objects after the fix is
implemented to preserve the weak links.
====

[float]
[[features-8.0.0]]
=== Features
For information about the features introduced in 8.0.0, refer to <<whats-new,What's new in 8.0>>.

Elastic Security::
For the Elastic Security 8.0.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].

To review the features in previous versions, refer to the following: 

<<features-8.0.0-rc2,8.0.0-rc2>> | <<features-8.0.0-rc1,8.0.0-rc1>> | <<features-8.0.0-beta1,8.0.0-beta1>> | <<features-8.0.0-alpha2,8.0.0-alpha2>>

[[enhancements-and-bug-fixes-v8.0.0]]
=== Enhancements and bug fixes

For detailed information about the 8.0.0 release, review the enhancements and bug fixes.

[float]
[[enhancement-v8.0.0]]
==== Enhancements
Dashboard::
Clone ReferenceOrValueEmbeddables by value {kibana-pull}122199[#122199]

Elastic Security::
For the Elastic Security 8.0.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].

[float]
[[fixes-v8.0.0]]
==== Bug Fixes
APM::
Restrict aggregated transaction metrics search to date range {kibana-pull}123445[#123445]

Elastic Security::
For the Elastic Security 8.0.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].

Fleet::
Allow empty strings for required text fields in package policies {kibana-pull}123610[#123610]

Maps::
Fixes Label border color is not removed from legend when disabled {kibana-pull}122705[#122705]

Monitoring::
Ensure logstash getNodes always contains a uuid {kibana-pull}124201[#124201]

Security::
Long-running requests no longer cause sporadic logouts in certain cases, even when user sessions are active {kibana-pull}122155[#122155]

[[release-notes-8.0.0-rc2]]
== {kib} 8.0.0-rc2

For information about the {kib} 8.0.0-rc2 release, review the following information.

[float]
[[breaking-changes-8.0.0-rc2]]
=== Breaking change

Breaking changes can prevent your application from optimal operation and performance.
Before you upgrade, review the breaking change, then mitigate the impact to your application.

[discrete]
[[breaking-122722]]
.Removes the ability to use `elasticsearch.username: elastic` in production
[%collapsible]
====
*Details* +
In production, you are no longer able to use the `elastic` superuser to authenticate to {es}. For more information, refer to {kibana-pull}122722[#122722].

*Impact* +
When you configure `elasticsearch.username: elastic`, {kib} fails.
====

To review the breaking changes in previous versions, refer to the following: 

<<breaking-changes-8.0.0-rc1,8.0.0-rc1>> | <<breaking-changes-8.0.0-beta1,8.0.0-beta1>> | <<breaking-changes-8.0.0-alpha2,8.0.0-alpha2>> | 
<<breaking-changes-8.0.0-alpha1,8.0.0-alpha1>>

[float]
[[features-8.0.0-rc2]]
=== Features
{kib} 8.0.0-rc2 adds the following new and notable features.

Dashboard::
Dashboard Integration {kibana-pull}115991[#115991]
Elastic Security::
For the Elastic Security 8.0.0-rc2 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Monitoring::
Enterprise Search Stack Monitoring {kibana-pull}114303[#114303]
Observability::
* Adds Agent Keys in APM settings - Create agent keys {kibana-pull}120373[#120373]
* Adds Agent Keys in APM settings - Agent key table {kibana-pull}119543[#119543]
* Allows users to set Download Speed, Upload Speed, and Latency for their synthetic monitors in Uptime {kibana-pull}118594[#118594]
Platform::
Changes saved objects management inspect view to a read-only JSON view of the whole saved object {kibana-pull}112034[#112034]

[[enhancements-and-bug-fixes-v8.0.0-rc2]]
=== Enhancements and bug fixes

For detailed information about the 8.0.0-rc2 release, review the enhancements and bug fixes.

[float]
[[enhancement-v8.0.0-rc2]]
==== Enhancements
Elastic Security::
For the Elastic Security 8.0.0-rc2 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Security::
Adds session cleanup audit logging {kibana-pull}122419[#122419]
Observability::
Make a monitor's steps details page work on mobile resolutions in Uptime {kibana-pull}122171[#122171]

[float]
[[fixes-v8.0.0-rc2]]
==== Bug Fixes
Alerting::
Fixes PagerDuty timestamp validation {kibana-pull}122321[#122321]
Dashboard::
* Creates Explicit Diffing System {kibana-pull}121241[#121241]
* Fixes blank panel save and display issue {kibana-pull}120815[#120815]
* Fixes full screen error when pressing back arrow on browser {kibana-pull}118113[#118113]
Elastic Security::
For the Elastic Security 8.0.0-rc2 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Maps::
* Fixes Point to point and Tracks layers label properties not showing in the legend {kibana-pull}122993[#122993]
* Fixes Color ramp UI for percent of a top term in join layer is broken {kibana-pull}122718[#122718]
Observability::
* Updates index pattern permission error in APM {kibana-pull}122680[#122680]
* Honor time unit for Inventory Threshold in Metrics {kibana-pull}122294[#122294]
* Adds locator to aid other plugins in linking properly to Uptime {kibana-pull}123004[#123004]
* Fixes a bug in which headers would be incorrectly centered on desktop in Uptime {kibana-pull}122643[#122643]

[[release-notes-8.0.0-rc1]]
== {kib} 8.0.0-rc1

Review the {kib} 8.0.0-rc1 changes, then use the <<upgrade-assistant,Upgrade Assistant>> to complete the upgrade.

[float]
[[breaking-changes-8.0.0-rc1]]
=== Breaking changes

Breaking changes can prevent your application from optimal operation and performance.
Before you upgrade, review the breaking changes, then mitigate the impact to your application.

[discrete]
[[breaking-118854]]
.Splits package policy `upgrade` endpoint for Fleet
[%collapsible]
====
*Details* +
For package policy upgrades, the packagePolicy `upgrade` endpoint format supports a mutative upgrade operation (when `dryRun: false`) and a read-only dry run operation (when `dryRun: true`):

[source,text]
--
 POST /package_policies/upgrade
 {
   packagePolicyIds: [...],
   dryRun: false
 }
--

For more information, refer to {kibana-pull}118854[#118854].

*Impact* +
The endpoint is now split into two separate endpoints:

[source,text]
--
 POST /package_policies/upgrade
 {
   packagePolicyIds: [...]
 }

 POST /package_policies/upgrade/dry_run
 {
   packagePolicyIds: [...]
 }
--
====
      
[discrete]
[[breaking-119945]]
.Removes APM jobs from Machine Learning
[%collapsible]
====
*Details* +
APM Node.js and RUM JavaScript anomaly detection job modules have been removed. For more information, refer to {kibana-pull}119945[#119945].

*Impact* +
When you upgrade to 8.0.0, you are unable to create and view the APM Node.js and RUM JavaScript jobs in Machine Learning.
====

[discrete]
[[breaking-118300]]
.Fails migrations for unknown types
[%collapsible]
====
*Details* +
Unknown saved object types now cause {kib} migrations to fail. For more information, refer to {kibana-issue}107678[#107678].

*Impact* +
To complete the migration, re enable plugins or delete documents from the index in the previous version.
====

[discrete]
[[breaking-116821]]
.Removes deprecated config fields from Logs and Metrics APIs and saved objects
[%collapsible]
====
*Details* +
On the Logs and Metrics UIs, references to the following API and saved object deprecated fields have been removed: 

* `timestamp`
* `tiebreaker`
* `container`
* `pod`
* `host`

For more information, refer to {kibana-pull}116821[#116821] and {kibana-pull}115874[#115874].

*Impact* +
When you upgrade to 8.0.0, you are unable to use references to the deprecated fields.
====

To review the breaking changes in previous versions, refer to the following: 

<<breaking-changes-8.0.0-beta1,8.0.0-beta1>> | <<breaking-changes-8.0.0-alpha2,8.0.0-alpha2>> | 
<<breaking-changes-8.0.0-alpha1,8.0.0-alpha1>>

[float]
[[deprecations-8.0.0-rc1]]
=== Deprecations

Deprecated functionality does not have an immediate impact on your application, but we strongly recommend you make the necessary updates after you complete the upgrade.

[discrete]
[[deprecation-120689]]
.Renames the `autocreate` data view APM setting
[%collapsible]
====
*Details* +
The `xpack.apm.autocreateApmIndexPattern` APM setting has been removed. For more information, refer to {kibana-pull}120689[#120689].

*Impact* +
To automatically create data views in APM, use `xpack.apm.autoCreateApmDataView`.
====

[discrete]
[[deprecation-119494]]
.Updates Fleet API to improve consistency
[%collapsible]
====
*Details* +
The Fleet API has been updated to improve consistency:

* Hyphens are changed to underscores in some names.
* The `pkgkey` path parameter in the packages endpoint is split.
* The `response` and `list` properties are renamed to `items` or `item` in some
responses.

For more information, refer to {kibana-pull}119494[#119494].

*Impact* +
When you upgrade to 8.0.0, use the following API changes:

* Use `enrollment_api_keys` instead of `enrollment-api-keys`.

* Use `agent_status` instead of `agent-status`.

* Use `service_tokens` instead of `service-tokens`.

* Use `/epm/packages/{packageName}/{version}` instead of `/epm/packages/{pkgkey}`.

* Use `items[]` instead of `response[]` in:
+
[source,text]
--
/api/fleet/enrollment_api_keys
/api/fleet/agents
/epm/packages/
/epm/categories
/epm/packages/_bulk
/epm/packages/limited
/epm/packages/{packageName}/{version} <1>
--
<1> Use `items[]` when the verb is `POST` or `DELETE`. Use `item` when the verb
is `GET` or `PUT`.

For more information, refer to {fleet-guide}/fleet-api-docs.html[Fleet APIs].

====

To review the deprecations in previous versions, refer to the <<deprecations-8.0.0-alpha1,8.0.0-alpha1 release notes>>. 


[float]
[[features-8.0.0-rc1]]
=== Features
{kib} 8.0.0-rc1 adds the following new and notable features.

Elastic Security::
For the Elastic Security 8.0.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Management::
Display managed badge for transforms {kibana-pull}117679[#117679]
Monitoring::
Enterprise Search Stack Monitoring {kibana-pull}114303[#114303]
Observability::
* Adds ability to create agent keys in APM settings {kibana-pull}120373[#120373]
* Adds Agent key table in APM settings {kibana-pull}119543[#119543]
* Allows users to set Download Speed, Upload Speed, and Latency for their synthetic monitors {kibana-pull}118594[#118594]

[[enhancements-and-bug-fixes-v8.0.0-rc1]]
=== Enhancements and bug fixes

For detailed information about the 8.0.0-rc1 release, review the enhancements and bug fixes.

[float]
[[enhancement-v8.0.0-rc1]]
=== Enhancements
Canvas::
Reverts By-Value Embeddables {kibana-pull}117613[#117613]
Discover::
Adds multi-layer time axis for opt-out only {kibana-pull}115853[#115853]
Elastic Security::
For the Elastic Security 8.0.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Fleet::
Adds consistent `_meta` property to all Fleet ES assets {kibana-pull}119380[#119380]
Kibana Home & Add Data::
Moves overview page and link to the accordion solution title {kibana-pull}114018[#114018]
Lens & Visualizations::
* Handle removal of deprecated date histogram interval in *Vega* {kibana-pull}109090[#109090]
* Adds value labels to Heatmap in *Lens* {kibana-pull}106406[#106406]
Machine Learning::
* Adds support for `force` stop deployment {kibana-pull}118563[#118563]
* Refactors data view loading to remove unnecessary searches {kibana-pull}116455[#116455]
Observability::
* Service maps: Adds sparklines to the detail popover {kibana-pull}120021[#120021]
* Offer users upgrade to multi-metric job {kibana-pull}119980[#119980]
* Display relevant anomalies from multi-metric job {kibana-pull}119709[#119709]
* Adds service icon for the originating service in traces table {kibana-pull}119421[#119421]
* Auto attachment for java agent beta in APM integration settings {kibana-pull}119131[#119131]
* Errors: Enhancements to the Errors list page (part II) {kibana-pull}118878[#118878]
* Store Alerts View table state in localStorage {kibana-pull}118207[#118207]
* Handle other values popup when correlated value is not in top 10 {kibana-pull}118069[#118069]
* Adds links to navigate from alerts table to rule {kibana-pull}118035[#118035]
* Reinstates ML multi-metric job {kibana-pull}117836[#117836]
* Re-enables metric-based UI {kibana-pull}117021[#117021]
* Make Alerts page use shared {kib} time range {kibana-pull}115192[#115192]
* Adds enabled toggle {kibana-pull}119994[#119994]
* Adds missing tooltip to the report metric badge in *Exploratory View* {kibana-pull}119940[#119940]
* Adds step duration in step list {kibana-pull}116266[#116266]
Platform::
Moves developer architecture docs to user docs {kibana-pull}119125[#119125]
Reporting::
* Decouples screenshotting plugin from the reporting {kibana-pull}120110[#120110]
* Updates the design of the *Reports* management UI, including the addition of a link to {kib} app where the report was generated {kibana-pull}111412[#111412]
Security::
Adds ability to clone role mappings {kibana-pull}118434[#118434]
Adds user logout audit events {kibana-pull}121455[#121455]

[float]
[[fixes-v8.0.0-rc1]]
=== Bug Fixes
Canvas::
* Fixes Error overflow {kibana-pull}122158[#122158]
* Fixes expression input {kibana-pull}121490[#121490]
* Hides edit menu when in view-only mode {kibana-pull}118779[#118779]
Dashboard::
* Allow text wrapping for panel titles and dashboard descriptions for PDF generation {kibana-pull}121360[#121360]
* Page now resets to zero when rows per page is changed on *Add from Library* window {kibana-pull}118627[#118627]
* Fixes full screen error when pressing back arrow in browser {kibana-pull}118113[#118113]
Elastic Security::
For the Elastic Security 8.0.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Fleet::
* Adds `installed_kibana_space_id` to `epm-packages` saved objects {kibana-pull}120517[#120517]
* Handle Saved Object ID changes {kibana-pull}119527[#119527]
* Fixes upgradeable agents filter {kibana-pull}119338[#119338]
Lens & Visualizations::
* Enables normal mode for percentage charts in *Lens* {kibana-pull}120197[#120197]
* Fixes existing fields query for epoch_millis dates in *Lens* {kibana-pull}119508[#119508]
* Include frozen indices in *Lens* {kibana-pull}118555[#118555]
* Fixes focus on legend action popovers in *Lens* {kibana-pull}115066[#115066]
Machine Learning::
* Fixes data view search based on title {kibana-pull}120737[#120737]
* Data frame analytics wizard: Only allow data view creation if job will be started immediately {kibana-pull}120042[#120042]
* Fixes anomaly detection module manifest queries to ignore frozen and cold data tiers {kibana-pull}119635[#119635]
* Catches syntax error in job wizard editor {kibana-pull}119457[#119457]
* Fixes error handling for missing data view in data frame analytics wizard {kibana-pull}119455[#119455]
* Ensures auto refresh interval is used in Data Frame Analytics list {kibana-pull}117959[#117959]
* Ignores frozen indices in data recognizer {kibana-pull}117208[#117208]
Management::
* Fixes data grid column actions button when histogram charts are visible {kibana-pull}120202[#120202]
* Disables delete data view for data frame analytics and transforms wizards {kibana-pull}119732[#119732]
* Check {kib} capabilities for all saving, editing, and deleting {kibana-pull}118480[#118480]
* Adds autocomplete for search_after and pit in search query {kibana-pull}117864[#117864]
* Autocomplete for t_test aggregation {kibana-pull}117782[#117782]
* Disables create data view for data frame analytics and transforms wizards {kibana-pull}117690[#117690]
Maps::
* Fixes an issue where drawings do not show when there is a global filter {kibana-pull}121239[#121239]
* Use minimum symbol size if meta is not loaded {kibana-pull}119119[#119119]
* Do not fail migration when JSON.parse fails {kibana-pull}117342[#117342]
* Do not allow label overlap {kibana-pull}116190[#116190]
Monitoring::
Correct linear regression formula {kibana-pull}120222[#120222]
Observability::
* Renames alerting types in Infra {kibana-pull}121061[#121061]
* Renames occurrences of `alert_type` to `rule_type` in Infra {kibana-pull}120455[#120455]
* Fixes failing alerts table pagination functional tests {kibana-pull}119985[#119985]
* Switch to _source for updating documents instead of fields API {kibana-pull}118245[#118245]
* Fixes an issue where search terms with certain characters caused the APM UI to crash {kibana-pull}118063[#118063]
* Ignore unavailable indices for ML jobs {kibana-pull}117632[#117632]
* Disables the actions button when users have inadequate privileges {kibana-pull}117488[#117488]
* Replaces manual rate calculation with `rate` agg {kibana-pull}115651[#115651]
* Adds migration to fix incorrect action group spelling {kibana-pull}119626[#119626]
* Fixes bug with manage views button {kibana-pull}118547[#118547]
* Disables No Data checkboxes for doc count alerts {kibana-pull}117194[#117194]
* Prevent event propagation on step_duration {kibana-pull}122039[#122039]
* Disables the button to create alerts in Uptime when users do not have permissions to do so {kibana-pull}120379[#120379]
* Fixes a bug that prevented users from saving Uptime configurations when the `inspect` option was turned on {kibana-pull}119142[#119142]
* Adds a callout to informs users that they do not have permissions to create ML jobs for Uptime monitors {kibana-pull}117684[#117684]
Platform::
Fixes font glitches in code editor {kibana-pull}121392[#121392]
Reporting::
Fixes an issue where PDF and PNG reports break on Windows operating systems when the {kib} server hostname is `0.0.0.0` {kibana-pull}117022[#117022]

[[release-notes-8.0.0-beta1]]
== {kib} 8.0.0-beta1

Review the {kib} 8.0.0-beta1 changes, then use the <<upgrade-assistant,Upgrade Assistant>> to complete the upgrade.

[float]
[[breaking-changes-8.0.0-beta1]]
=== Breaking changes

Breaking changes can prevent your application from optimal operation and performance. Review the following breaking changes, then mitigate the impact to your application.

To review the breaking changes in previous versions, refer to the following: 

<<breaking-changes-8.0.0-alpha2,8.0.0-alpha2>> | <<breaking-changes-8.0.0-alpha1,8.0.0-alpha1>>

[float]
[[alerting-breaking-changes-8.0.0-beta1]]
==== Alerting 
      
[discrete]
[[breaking-114558]]
.Removes `xpack.task_manager.index`
[%collapsible]
====
*Details* +
The `xpack.task_manager.index` setting has been removed. For more information, refer to {kibana-pull}114558[#114558].

*Impact* +
Before you upgrade to 8.0.0, remove `xpack.task_manager.index` from kibana.yml.
====

[discrete]
[[breaking-113461]]
.Removes ability to remove plugins
[%collapsible]
====
*Details* +
The `xpack.actions.enabled` setting has been removed. For more information, refer to {kibana-pull}113461[#113461].

*Impact* +
Before you upgrade to 8.0.0, remove `xpack.actions.enabled` from kibana.yml.
====

[float]
[[lens-visualizations-breaking-changes-8.0.0-beta1]]
==== Lens & visualizations

[discrete]
[[breaking-113516]]
.Removes display options from legacy gauge
[%collapsible]
====
*Details* +
The *Display warnings* option has been removed from the aggregation-based gauge visualization. For more information, refer to {kibana-pull}113516[#113516].

*Impact* +
When you create aggregation-based gauge visualizations, the *Display warnings* option is no longer available in *Options > Labels*.
====

[discrete]
[[breaking-112643]]
.Removes settings from visEditors plugins
[%collapsible]
====
*Details* +
The following deprecated visEditors plugin settings have been removed:

* `metric_vis.enabled`
* `table_vis.enabled`
* `tagcloud.enabled`
* `metrics.enabled`
* `metrics.chartResolution`
* `chartResolution`
* `metrics.minimumBucketSize`
* `minimumBucketSize`
* `vega.enabled`
* `vega.enableExternalUrls`
* `vis_type_table.legacyVisEnabled`
* `timelion_vis.enabled`
* `timelion.enabled`
* `timelion.graphiteUrls`
* `timelion.ui.enabled`

For more information, refer to {kibana-pull}112643[#112643].

*Impact* +
Before you upgrade, make the following changes in kibana.yml:

* Replace `metric_vis.enabled` with `vis_type_metric.enabled`
* Replace `table_vis.enabled` with `vis_type_table.enabled`
* Replace `tagcloud.enabled` with `vis_type_tagcloud.enabled`
* Replace `metrics.enabled` with `vis_type_timeseries.enabled`
* Replace `metrics.chartResolution` and `chartResolution` with `vis_type_timeseries.chartResolution`
* Replace `metrics.minimumBucketSize` and `minimumBucketSize` with `vis_type_timeseries.minimumBucketSize`
* Replace `vega.enabled` with `vis_type_vega.enabled`
* Replace `vega.enableExternalUrls` with `vis_type_vega.enableExternalUrls`
* Remove `vis_type_table.legacyVisEnabled`
* Replace `timelion_vis.enabled` with `vis_type_timelion.enabled`
* Replace `timelion.enabled` with `vis_type_timelion.enabled`
* Replace `timelion.graphiteUrls` with `vis_type_timelion.graphiteUrls`
* Remove `timelion.ui.enabled`

====

[discrete]
[[breaking-111704]]
.Removes dimming opacity setting
[%collapsible]
====
*Details* +
The *Dimming opacity* setting in *Advanced Settings* has been removed. For more information, refer to {kibana-pull}111704[#111704].

*Impact* +
When you upgrade to 8.0.0, you are no longer able to configure the dimming opactiy for visualizations. 
====

[discrete]
[[breaking-110985]]
.Removes Less stylesheet support
[%collapsible]
====
*Details* +
In *TSVB*, custom Less stylesheets have been removed. For more information, refer to {kibana-pull}110985[#110985].

*Impact* +
Existing less stylesheets are automatically converted to CSS stylesheets. 
====

[discrete]
[[breaking-110571]]
.Disables the input string mode
[%collapsible]
====
*Details* +
In *TSVB*, the *Index pattern selection mode* option has been removed. For more information, refer to {kibana-pull}110571[#110571].

*Impact* +
To use index patterns and {es} indices in *TSVB* visualizations:

. Open the main menu, then click *Stack Management > Advanced Settings*.

. Select *Allow string indices in TSVB*.

. Click *Save changes*.
====

[float]
[[logs-breaking-changes-8.0.0-beta1]]
==== Logs

[discrete]
[[breaking-115974]]
.Removes deprecated alias config entries
[%collapsible]
====
*Details* +
The deprecated `xpack.infra.sources.default.logAlias` and `xpack.infra.sources.default.logAlias` settings have been removed. For more information, refer to {kibana-pull}115974[#115974].

*Impact* +
Before you upgrade, remove the settings from kibana.yml, then configure the settings in <<logs-app,Logs>>.
====

[discrete]
[[breaking-61302]]
.Removes configurable fields in settings
[%collapsible]
====
*Details* +
The *Logs* and *Metrics* configurable fields settings have been removed. For more information, refer to {kibana-pull}61302[#61302].

*Impact* +
Configure the settings in https://www.elastic.co/guide/en/ecs/current/ecs-reference.html[ECS].
====

[float]
[[machine-learning-breaking-changes-8.0.0-beta1]]
==== Machine learning
      
[discrete]
[[breaking-115444]]
.Grants access to machine learning features when base privileges are used
[%collapsible]
====
*Details* +
Machine learning features are included as base privileges. For more information, refer to {kibana-pull}115444[#115444].

*Impact* +
If you do not want to grant users privileges to machine learning features, update <<xpack-security,*Users* and *Roles*>>.
====

[float]
[[maps-breaking-changes-8.0.0-beta1]]
==== Maps

[discrete]
[[breaking-116184]]
.Removes proxyElasticMapsServiceInMaps
[%collapsible]
====
*Details* +
The `map.proxyElasticMapsServiceInMaps` setting has been removed. For more information, refer to {kibana-pull}116184[#116184].

*Impact* +
Install the on-prem version of the <<maps-connect-to-ems,Elastic Maps Service>>, which is a Docker service that resides in the Elastic Docker registry, in an accessible location on your internal network. When you complete the installation, update kibana.yml to point to the service.
====

[float]
[[operations-breaking-changes-8.0.0-beta1]]
==== Operations 

[discrete]
[[breaking-111535]]
.Removes environment variables
[%collapsible]
====
*Details* +
The `CONFIG_PATH` and `DATA_PATH` environment variables have been removed. For more information, refer to {kibana-pull}111535[#111535].

*Impact* +
Replace the `CONFIG_PATH` environment variable with `KBN_PATH_CONF`, and replace `DATA_PATH` with the `path.data` setting.
====

[float]
[[platform-breaking-changes-8.0.0-beta1]]
==== Platform 
      
[discrete]
[[breaking-114379]]
.Removes supports for csp.rules configuration
[%collapsible]
====
*Details* +
Support for the `csp.rules` configuration property has been removed. For more information, refer to {kibana-pull}114379[#114379].

*Impact* +
Configuring the default `csp.script_src`, `csp.workers_src`, and `csp.style_src` values is not required.
====

[discrete]
[[breaking-113653]]
.Changes and removes deprecated core settings and deprecated settings from core plugins
[%collapsible]
====
*Details* +
The deprecation notice for `server.cors` has changed from `level:critical` to `level:warning`.

The following settings have changed:

* The `xpack.banners.placement` value has been renamed
* The `newsfeed.defaultLanguage` newsfeed item retrieval method and default language has changed

Support for the following configuration settings has been removed:

* `newsfeed.defaultLanguage`
* `cpu.cgroup.path.override`
* `cpuacct.cgroup.path.override`
* `server.xsrf.whitelist`
* `xpack.xpack_main.xpack_api_polling_frequency_millis`
* `KIBANA_PATH_CONF`

For more information, refer to {kibana-pull}113653[#113653].

*Impact* +
* The `header` value provided to the `xpack.banners.placement` configuration has been renamed to 'top'
* The `newsfeed.defaultLanguage` newsfeed items are retrieved based on the browser locale and default to English
* Replace `cpu.cgroup.path.override` with `ops.cGroupOverrides.cpuPath`
* Replace `cpuacct.cgroup.path.override` with `ops.cGroupOverrides.cpuAcctPath`
* Replace `server.xsrf.whitelist` with `server.xsrf.allowlist`
* Replace `xpack.xpack_main.xpack_api_polling_frequency_millis` with `xpack.licensing.api_polling_frequency`
* Replace `KIBANA_PATH_CONF` path to the {kib} configuration file using the `KBN_PATH_CONF` environment variable
====

[discrete]
[[breaking-113495]]
.Removes `enabled` settings from plugins
[%collapsible]
====
*Details* +
Using `{plugin_name}.enabled` to disable plugins has been removed. Some plugins, such as `telemetry`, `newsfeed`, `reporting`, and the various `vis_type` plugins will continue to support this setting. All other {kib} plugins will not support this setting. Any new plugin will support this setting only when specified in the `configSchema`. For more information, refer to {kibana-pull}113495[#113495].

The `xpack.security.enabled` setting has been removed. For more information, refer to {kibana-pull}111681[#111681].

*Impact* +
Before you upgrade to 8.0.0:

* Remove `{plugin_name}.enabled` from kibana.yml. If you use the setting to control user access to {kib} applications, use <<tutorial-secure-access-to-kibana,*Features* controls>> instead.
* Replace `xpack.security.enabled` with {ref}/security-settings.html#general-security-settings[`xpack.security.enabled`] in elasticsearch.yml.
====

[discrete]
[[breaking-113367]]
.Removes `--plugin-dir` cli option
[%collapsible]
====
*Details* +
The `plugins.scanDirs` setting and `--plugin-dir` cli option have been removed. For more information, refer to {kibana-pull}113367[#113367].

*Impact* +
Before you upgrade to 8.0.0, remove `plugins.scanDirs` from kibana.yml.
====

[discrete]
[[breaking-113296]]
.Removes support for `optimize.*` settings
[%collapsible]
====
*Details* +
The legacy `optimize.*` settings have been removed. If your configuration uses the following legacy `optimize.*` settings, {kib} fails to start:

* `optimize.lazy`
* `optimize.lazyPort`
* `optimize.lazyHost`
* `optimize.lazyPrebuild`
* `optimize.lazyProxyTimeout`
* `optimize.enabled`
* `optimize.bundleFilter`
* `optimize.bundleDir`
* `optimize.viewCaching`
* `optimize.watch`
* `optimize.watchPort`
* `optimize.watchHost`
* `optimize.watchPrebuild`
* `optimize.watchProxyTimeout`
* `optimize.useBundleCache`
* `optimize.sourceMaps`
* `optimize.workers`
* `optimize.profile`
* `optimize.validateSyntaxOfNodeModules`

For more information, refer to {kibana-pull}113296[#113296].

*Impact* +
To run the `@kbn/optimizer` separately in development, pass `--no-optimizer` to `yarn start`. For more details, refer to {kibana-pull}73154[#73154]. 
====

[discrete]
[[breaking-113173]]
.Removes `so/server/es` settings
[%collapsible]
====
*Details* +
Some of the `so/server/es` settings have been removed. If your configuration uses the following settings, {kib} fails to start:

* `savedObjects.indexCheckTimeout`
* `server.xsrf.token`
* `elasticsearch.preserveHost`
* `elasticsearch.startupTimeout`

For more information, refer to {kibana-pull}113173[#113173].

*Impact* +
Before you upgrade to 8.0.0., remove these settings from kibana.yml.
====

[discrete]
[[breaking-113068]]
.Adds requirement for inline scripting
[%collapsible]
====
*Details* +
To start {kib}, you must enable inline scripting in {es}. For more information, refer to {kibana-pull}113068[#113068].

*Impact* +
Enable link:https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-scripting-security.html[inline scripting].
====

[discrete]
[[breaking-112773]]
.Removes `kibana.index` settings
[%collapsible]
====
*Details* +
The `kibana.index`, `xpack.reporting.index`, and `xpack.task_manager.index` settings have been removed. For more information, refer to {kibana-pull}112773[#112773].

*Impact* +
Use spaces, cross-cluster replication, or cross-cluster search. To migrate to <<xpack-spaces,spaces>>, export your <<managing-saved-objects, saved objects>> from a tenant into the default space. For more details, refer to link:https://github.com/elastic/kibana/issues/82020[#82020].
====
  
[discrete]
[[breaking-112305]]
.Removes legacy logging
[%collapsible]
====
*Details* +
The logging configuration and log output format has changed. For more information, refer to {kibana-pull}112305[#112305].

*Impact* +
Use the new <<logging-configuration, logging system configuration>>. 
====

[float]
[[reporting-breaking-changes-8.0.0-beta1]]
==== Reporting
      
[discrete]
[[breaking-114216]]
.Removes reporting settings
[%collapsible]
====
*Details* +
The following settings have been removed: 

* `xpack.reporting.capture.concurrency`

* `xpack.reporting.capture.settleTime`

* `xpack.reporting.capture.timeout`

* `xpack.reporting.kibanaApp`

For more information, refer to {kibana-pull}114216[#114216].

*Impact* +
Before you upgrade to 8.0.0, remove the settings from kibana.yml.
====

[float]
[[rest-api-breaking-changes-8.0.0-beta1]]
==== REST API 

[discrete]
[[breaking-114730]]
.Removes `/api/settings`
[%collapsible]
====
*Details* +
The `/api/settings` REST API has been removed. For more information, refer to {kibana-pull}114730[#114730].

*Impact* +
Use `/api/stats`.
====

[float]
[[security-breaking-changes-8.0.0-beta1]]
==== Security

[discrete]
[[breaking-116191]]
.Removes legacy audit logger
[%collapsible]
====
*Details* +
The legacy audit logger has been removed. For more information, refer to {kibana-pull}116191[#116191].

*Impact* +
Audit logs will be written to the default location in the new ECS format. To change the output file, filter events, and more, use the <<audit-logging-settings, audit logging settings>>.
====

[float]
[[deprecations-8.0.0-beta1]]
=== Deprecations

Deprecated functionality does not have an immediate impact on your application, but we strongly recommend you make the necessary updates after you complete the upgrade.

To review the 8.0.0 depcrecations, refer to the <<deprecations-8.0.0-alpha1,8.0.0-alpha1 release notes>>. 
  
[float]
[[features-8.0.0-beta1]]
=== Features
The 8.0.0-beta1 release adds the following new and notable features.

Dashboard::
* Dashboard Integration {kibana-pull}115991[#115991]
Elastic Security::
For the Elastic Security 8.0.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Machine Learning::
* Addition of new Model Management tab {kibana-pull}115772[#115772]
Platform::
* Changes edit view to json read-only view {kibana-pull}112034[#112034]

[float]
[[enhancement-v8.0.0-beta1]]
=== Enhancements

The 8.0.0-beta1 release includes the following enhancements.

Canvas::
* By-Value embeddables {kibana-pull}113827[#113827]
* Toolbar UI updates {kibana-pull}113329[#113329]
Elastic Security::
For the Elastic Security 8.0.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Lens & Visualizations::
* Handle removal of deprecated date histogram interval in *Vega* {kibana-pull}109090[#109090]
* Adds value labels to Heatmap in *Lens* {kibana-pull}106406[#106406]
Logs::
* Make Alerts page use shared Kibana time range {kibana-pull}115192[#115192]
Machine Learning::
* Adds support to {fleet} {integrations} for installing ML models {kibana-pull}107710[#107710]
* Adds Index data visualizer grid embeddable as extra view within Discover {kibana-pull}107184[#107184]
Maps::
* Use Elastic Maps Service v8.0 {kibana-pull}116217[#116217]
* Use desaturated map tiles instead of bright map tiles by default {kibana-pull}116179[#116179]
* Use ES mvt {kibana-pull}114553[#114553]
Security::
* Register "minimal" feature privileges regardless of the current license level {kibana-pull}115992[#115992]
Uptime::
* Uptime index config using kibana.yml {kibana-pull}115775[#115775]

[float]
[[fixes-v8.0.0-beta1]]
=== Bug fixes

The 8.0.0-beta1 release includes the following bug fixes.

Management::
* Removes freeze action from Cold phase {kibana-pull}116160[#116160]
* Disallow creating runtime and scripted fields with * in the name {kibana-pull}116119[#116119]
Querying & Filtering::
* Fixes Add filter button doesnt close popup after openning {kibana-pull}111917[#111917]

[[release-notes-8.0.0-alpha2]]
== {kib} 8.0.0-alpha2

Review the {kib} 8.0.0-alpha2 changes, then use the <<upgrade-assistant,Upgrade Assistant>> to complete the upgrade.

[float]
[[breaking-changes-8.0.0-alpha2]]
=== Breaking changes

Breaking changes can prevent your application from optimal operation and performance. Review the following breaking changes, then mitigate the impact to your application.

To review the breaking changes in the previous version, refer to <<breaking-changes-8.0.0-alpha1,8.0.0-alpha1>>.

[discrete]
[[breaking-110830]]
.Changes the `GET /api/status` default behavior
[%collapsible]
====
*Details* +
`GET /api/status` reports a new and more verbose payload. For more information, refer to {kibana-pull}110830[#110830].

*Impact* +
To retrieve the {kib} status in the previous format, use `GET /api/status?v7format=true`.
====
      
[discrete]
[[breaking-110738]]
.Removes support for legacy exports
[%collapsible]
====
*Details* +
In {kib} 8.0.0 and later, the legacy format from {kib} 6.x is unsupported. For more information, refer to {kibana-pull}110738[#110738]

*Impact* +
Using the user interface to import saved objects is restricted to `.ndjson` format imports.
====
      
[discrete]
[[breaking-109896]]
.Removes `map.regionmap.*`
[%collapsible]
====
*Details* +
The deprecated `map.regionmap.*` setting in kibana.yml has been removed. For more information, refer to {kibana-pull}109896[#109896].

*Impact* +
If you have maps that use `map.regionmap` layers:

. Remove the `map.regionmap` layer.

. To recreate the choropleth layer, use <<import-geospatial-data,GeoJSON upload>> to index your static vector data into {es}. 

. Create a choropleth layer from the indexed vector data. 
====
      
[discrete]
[[breaking-109798]]
.Removes `kibana.defaultAppId`
[%collapsible]
====
*Details* +
The deprecated `kibana.defaultAppId` setting in kibana.yml, which is also available as `kibana_legacy.defaultAppId`, has been removed. For more information, refer to {kibana-pull}109798[#109798].

*Impact* +
When you upgrade, remove `kibana.defaultAppId` from your kibana.yml file. To configure the default route for users when they enter a space, use the <<defaultroute,`defaultRoute`>> in *Advanced Settings*.
====
      
[discrete]
[[breaking-109350]]
.Removes `courier:batchSearches`
[%collapsible]
====
*Details* +
The deprecated `courier:batchSearches` setting in *Advanced Settings* has been removed. For more information, refer to {kibana-pull}109350[#109350].

*Impact* +
When you upgrade, the `courier:batchSearches` setting will no longer be available.
====
      
[discrete]
[[breaking-108111]]
.Removes `xpack.task_manager.index`
[%collapsible]
====
*Details* +
The deprecated `xpack.task_manager.index` setting in kibana.yml has been removed. For more information, refer to {kibana-pull}108111[#108111].

*Impact* +
When you upgrade, remove `xpack.task_manager.index` from your kibana.yml file.
====
      
[discrete]
[[breaking-108103]]
.Removes dashboard-only mode
[%collapsible]
====
*Details* +
The legacy dashboard-only mode has been removed. For more information, refer to {kibana-pull}108103[#108103].

*Impact* +
To grant users access to only dashboards, create a new role, then assign only the *Dashboard* feature privilege. For more information, refer to <<kibana-feature-privileges,{kib} privileges>>.
====
     
[discrete]
[[breaking-105979]]
.Removes `xpack.maps.showMapVisualizationTypes`
[%collapsible]
====
*Details* +
The deprecated `xpack.maps.showMapVisualizationTypes` setting in kibana.yml has been removed. For more information, refer to {kibana-pull}105979[#105979]

*Impact* +
When you upgrade, remove `xpack.maps.showMapVisualizationTypes` from your kibana.yml file.
====

[float]
[[deprecations-8.0.0-alpha2]]
=== Deprecations

Deprecated functionality does not have an immediate impact on your application, but we strongly recommend you make the necessary updates after you complete the upgrade.

To review the 8.0.0 depcrecations, refer to the <<deprecations-8.0.0-alpha1,8.0.0-alpha1 release notes>>. 
      
[float]
[[features-8.0.0-alpha2]]
=== Features
The 8.0.0-alpha2 release adds the following new and notable feature.

Security::
* Adds the interactive setup mode {kibana-pull}106881[#106881]
      
[float]
[[enhancement-v8.0.0-alpha2]]
=== Enhancements
The 8.0.0-alpha2 release includes the following enhancements.

Elastic Security::
For the Elastic Security 8.0.0-alpha2 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Security::
* Interactive setup mode {kibana-pull}106881[#106881]

[[release-notes-8.0.0-alpha1]]
== {kib} 8.0.0-alpha1

Review the {kib} 8.0.0-alpha1 changes, then use the <<upgrade-assistant,Upgrade Assistant>> to complete the upgrade.

[float]
[[breaking-changes-8.0.0-alpha1]]
=== Breaking changes

Breaking changes can prevent your application from optimal operation and performance. Review the breaking changes, then mitigate the impact to your application. 

[float]
[[enterprise-search-change]]
==== Enterprise Search changes

[discrete]
[[breaking-106307]]
.Required security plugin in 8.0
[%collapsible]
====
*Details* +
Enterprise Search now requires that you enable X-Pack Security. For more information, refer to {kibana-pull}106307[#106307]

*Impact* +
Enable X-Pack Security.
====

[float]
[[index-pattern-change]]
==== Index pattern changes

[discrete]
[[breaking-35173]]
.Removed support for time-based interval index patterns
[%collapsible]
====
*Details* +
Time-based interval index patterns were deprecated in 5.x. In 6.x, you could no longer create time-based interval index patterns, but they continued to function as expected. Support for these index patterns has been removed in 8.0. For more information, refer to {kibana-pull}35173[#35173]

*Impact* +
You must migrate your time_based index patterns to a wildcard pattern. For example, logstash-*. 
====

[float]
[[operations-changes]]
==== Operations changes

[discrete]
[[breaking-93835]]
.Removed platform from archive root directory
[%collapsible]
====
*Details* +
After you extract an archive, the output directory no longer includes the target platform. For example, `kibana-8.0.0-linux-aarch64.tar.gz` produces a `kibana-8.0.0` folder. For more information, refer to {kibana-pull}93835[#93835].

*Impact* +
To use the new folder, update the configuration management tools and automation.
====
      
[discrete]
[[breaking-90511]]
.Removed default support for TLS v1.0 and v1.1
[%collapsible]
====
*Details* +
The default support for TLS v1.0 and v1.1 has been removed. For more information, refer to {kibana-pull}90511[#90511].

*Impact* +
To enable support, set `--tls-min-1.0` in the `node.options` configuration file. To locate the configuration file, go to the kibana/config folder or any other configuration with the `KBN_PATH_CONF` environment variable. For example, if you are using a Debian-based system, the configuration file is located in /etc/kibana.
====
           
[discrete]
[[breaking-74424]]
.Removed support for sysv init
[%collapsible]
====
*Details* +
All supported operating systems use systemd service files. Any system that doesn’t have `service` aliased to use kibana.service should use `systemctl start kibana.service` instead of `service start kibana`. For more information, refer to {kibana-pull}74424[#74424].

*Impact* +
If your installation uses .deb or .rpm packages with SysV, migrate to systemd.
====
       
[discrete]
[[breaking-42353]]
.Disabled response logging as a default
[%collapsible]
====
*Details* +
In previous versions, all events are logged in `json` when `logging.json:true`. With the new logging configuration, you can choose the `json` and pattern output formats with layouts. For more information, refer to {kibana-pull}42353[#42353].

*Impact* +
To restore the previous behavior, configure the logging format for each custom appender with the `appender.layout property` in kibana.yml. There is no default for custom appenders, and each appender must be configured expilictly.

[source,yaml]
-------------------
logging:
  appenders:
    custom_console:
      type: console
      layout:
        type: pattern
    custom_json:
      type: console
      layout:
        type: json
  loggers:
    - name: plugins.myPlugin
      appenders: [custom_console]
  root:
    appenders: [default, custom_json]
    level: warn
-------------------
====

[float]
[[reporting-changes-8.0.0-alpha1]]
==== Reporting changes
      
[discrete]
[[breaking-52539]]
.Legacy job parameters are no longer supported
[%collapsible]
====
*Details* +
*Reporting* is no longer compatible with POST URL snippets generated with {kib} 6.2.0 and earlier. For more information, refer to {kibana-pull}52539[#52539]

*Impact* +
If you use POST URL snippets to automatically generate PDF reports, regenerate the POST URL strings.
====

[float]
[[rest-api-changes]]
==== Security changes

[discrete]
[[breaking-47929]]
.Removed `/api/security/v1/saml` route
[%collapsible]
====
*Details* +
The `/api/security/v1/saml` route has been removed and is reflected in the kibana.yml `server.xsrf.whitelist` setting, {es}, and the Identity Provider SAML settings. For more information, refer to {kibana-pull}47929[#47929]

*Impact* +
Use the `/api/security/saml/callback` route, or wait to upgrade to 8.0.0-alpha2 when the `/api/security/saml/callback` route breaking change is reverted. 
====

[discrete]
[[breaking-41700]]
.Reject legacy browsers by default
[%collapsible]
====
*Details* +
To provide the maximum level of protection for most installations, the csp.strict config is now enabled by default. Legacy browsers not supported by Kibana, such as Internet Explorer 11, are unable to access {kib} unless explicitly enabled. All browsers officially supported by Kibana do not have this issue. For more information, refer to {kibana-pull}41700[#41700]

*Impact* +
To enable support for legacy browsers, set `csp.strict: false` in kibana.yml. To effectively enforce the security protocol, we strongly discourage disabling `csp.strict` unless it is critical that you support Internet Explorer 11.
====

[float]
[[settings-changes-8.0.0-alpha1]]
==== Settings changes
      
[discrete]
[[breaking-106061]]
.Use new session timeout defaults 
[%collapsible]
====
*Details* +
The default values for the session timeout `xpack.security.session.{lifespan|idleTimeout}` settings have changed. For more information, refer to {kibana-pull}106061[#106061]

*Impact* +
Use the following default values:

* `xpack.security.session.idleTimeout: 8h`
* `xpack.security.session.lifespan: 30d`
====

[discrete]
[[breaking-87114]]
.Removed support for setting `server.host` to '0'
[%collapsible]
====
*Details* +
Support for configuring {kib} with `0` as the `server.host` has been removed. Please use `0.0.0.0` instead. For more information, refer to {kibana-pull}87114[#87114]

*Impact* +
You are now unable to use `0` as the `server.host`.
====

[discrete]
[[breaking-38657]]
.Removed `xpack.security.public` and `xpack.security.authProviders`
[%collapsible]
====
*Details* +
The `xpack.security.public` and `xpack.security.authProviders` settings have been removed. For more information, refer to {kibana-pull}38657[#38657]

*Impact* +
Use the `xpack.security.authc.saml.realm` and `xpack.security.authc.providers` settings.
====

[discrete]
[[breaking-22696]]
.Removed useUTC deprecation
[%collapsible]
====
*Details* +
The `logging.useUTC` setting has been removed. For more information, refer to {kibana-pull}22696[#22696]

*Impact* +
The default timezone is UTC. To change the timezone, set `logging.timezone: false` in kibana.yml. Change the timezone when the system, such as a docker container, is configured for a nonlocal timezone.  
====  

[discrete]
[[breaking-32049]]
.Removed environment variables `CONFIG_PATH` and `DATA_PATH`
[%collapsible]
====
*Details* +
The environment variables `CONFIG_PATH` and `DATA_PATH` have been removed.  For more information, refer to {kibana-pull}32049[#32049]

*Impact* +
Use the environment variable `KBN_PATH_CONF` instead of `CONFIG_PATH`.  Use the setting `path.data` instead of `DATA_PATH`.
====

[float]
[[deprecations-8.0.0-alpha1]]
=== Deprecations

The following functionality is deprecated in 8.0.0, and will be removed in 9.0.0. Deprecated functionality does not have an immediate impact on your application, but we strongly recommend you make the necessary updates after you complete the upgrade.

[discrete]
[[deprecation-74424]]
.Removed support for SysV init
[%collapsible]
====
*Details* +
Systems that don't have `service` aliased to use kibana.service are unable to use `service start kibana`. For more information, refer to {kibana-pull}74424[#74424]

*Impact* +
If your system doesn't have `service` aliased to use kibana.service, use `systemctl start kibana.service`.
====
      
[discrete]
[[deprecation-33603]]
.Removed `xpack:defaultAdminEmail` setting
[%collapsible]
====
*Details* +
The `xpack:default_admin_email` setting for monitoring use has been removed. For more information, refer to {kibana-pull}33603[#33603]

*Impact* +
Use the `xpack.monitoring.clusterAlertsEmail` in kibana.yml.
====

[float]
[[enhancements-and-bug-fixes-v8.0.0-alpha1]]
=== Bug fix

The 8.0.0-alpha1 release includes the following bug fix.

Operations::
* Moves systemd service to /usr/lib/systemd/system {kibana-pull}83571[#83571]
