[[release-notes]]
= {kib} Release Notes
++++
<titleabbrev>Release Notes</titleabbrev>
++++

[partintro]
--
// Use these for links to issue and pulls. Note issues and pulls redirect one to
// each other on Github, so don't worry too much on using the right prefix.
:issue: https://github.com/elastic/kibana/issues/
:pull: https://github.com/elastic/kibana/pull/

This section summarizes the changes in each release.

* <<release-notes-7.0.0-beta1>>
* <<release-notes-7.0.0-alpha2>>
* <<release-notes-7.0.0-alpha1>>

--

[[release-notes-7.0.0-beta1]]
== {kib} 7.0.0-beta1


[float]
[[breaking-7.0.0-beta1]]
=== Breaking changes

For more details about breaking changes in this release, see 
<<breaking-changes-7.0, Breaking changes in 7.0>>.

Design::
* Removes references to K6 EUI, using the default UI theme in its place {pull}29152[#29152]
Geo::
* Removes the deprecated `regionmap` and `tilemap` kibana.yml configurations. 
Removes the backwards compatibility logic that checked for duplicative settings 
`map.regionmap` and `map.tilemap`. {pull}28609[#28609]
Monitoring::
* Refactors index patterns from configurable to constants {pull}29528[#29528]
Management::
* Adds `configPrefix` to Index Management, License Management, Rollup Jobs, and 
Upgrade Assistant {pull}30149[#30149]
* Removes nested table splits from table visualization {pull}26057[#26057]
* Standardizes use of `index_pattern` in UI code and URLs, replacing `indices` 
and `index`  {pull}29151[#29151] and {pull}29481[#29481]
* Removes app-specific dark mode options and replaces with a global dark mode uiSetting {pull}29017[#29017]
Operations::
* Defers the optimize step in the plugin installer to server start {pull}26983[#26983]
Platform::
* Removes deprecated `i18n.defaultLocale` setting {pull}29325[#29325]
* Removes previously deprecated `elasticsearch*` settings. {pull}29496[#29496]
* Adds new "references" attribute to saved objects for relationships {pull}28199[#28199]
Querying & Filtering::
* Makes KQL the default query language for new searches {pull}27092[#27092]
Reporting::
* Removes Phantom dependency {pull}27142[#27142]
Security::
* Removes deprecated SSL settings {pull}28622[#28622]
* Removes legacy fallback {pull}29107[#29107]
Visualizations::
* Removes Timelion from the app switcher by default {pull}30131[#30131]


[float]
[[deprecation-7.0.0-beta1]]
=== Deprecations
Machine Learning::
* Updates REST endpoint calls to remove _xpack {pull}28069[#28069]
Visualizations::
* Removes old visualize wizard URL {pull}28982[#28982]
* Removes legacy response handler {pull}28985[#28985]
* Removes `legacyIcon` from visualizations {pull}28981[#28981]


[float]
[[enhancement-7.0.0-beta1]]
=== Enhancements
Canvas::
* Removes WebSockets from Canvas expressions interpreter {pull}29792[#29792]
* Optimizes Canvas REST calls via batching {pull}29847[#29847]
Kibana App::
* Replaces Angular timepicker with EuiSuperDatePicker {pull}29204[#29204]
* Upgrades Kibana to Elasticsearch 7.0 {pull}29184[#29184]
Machine Learning::
* Updates HTTP access modules for ECS {pull}29383[#29383]
* Updates auditbeat modules for ECS {pull}29934[#29934]
* Removes non ECS apache, nginx and auditbeat data recognizer modules {pull}30537[#30537]
Observability::
* Converts monitor sparklines to histogram {pull}28502[#28502]
* Adds crosshair sync for monitor page charts {pull}28631[#28631]
Operations::
* Adds support for reindexing APM indices {pull}29845[#29845]
Platform::
* Adds help menu item to header {pull}29664[#29664]
* Implements global dark theme {pull}28445[#28445]
* Removes support for the K6 navigation style {pull}29565[#29565]
Reporting::
* In the Visualization Editor, removes the "Optimize for printing" option when 
exporting the visualization as PNG or PDF. The single visualization will automatically 
be optimized for printing {pull}30456[#30456]
Security::
* Introduces content security policy (CSP) {pull}29545[#29545]
* Warns legacy browsers that do not support content security policy {pull}29957[#29957]
* Adds content security policy strict mode {pull}29856[#29856]
Visualizations::
* Adds a timeout so that Vega respects `elasticsearch.shardTimeout` setting {pull}30482[#30482]


[float]
[[bug-7.0.0-beta1]]
=== Bug fixes
APM::
* Uses form label for Transaction type selector {pull}28322[#28322]
* Fixes icon for View trace button {pull}28908[#28908]
* Shows metric-only services in service overview {pull}30397[#30397]
* Adds span subtype and action to Span Flyout {pull}30041[#30041]
* Updates head title and fixes breadcrumb string issues {pull}29960[#29960]
* Adds fixes for `service.name` scripted field {pull}28488[#28488]
* Updates APM index pattern {pull}30837[#30837]
* Updates APM reindex script {pull}30761[#30761]
* Sets Index Pattern version as string {pull}30789[#30789]
Canvas::
* Adds datetime as a date identifier {pull}29537[#29537]
* Switches sample web logs fonts to 48px {pull}30747[#30747]
* Fixes related to K7 design {pull}30833[#30833]
Design::
* Updates dashboard design {pull}29896[#29896]
* Adjusts side navigation interaction {pull}29978[#29978]
Elasticsearch UI::
* Triggers full load when encountering 403 for index list reload {pull}28243[#28243]
* Updates xpack console specs {pull}29506[#29506]
* Fixes API integration test for follower indices {pull}30260[#30260]
Geo::
* Fixes panel cut off in K7 design {pull}29209[#29209]
* Removes left-over geohash grid code {pull}30312[#30312]
* Uses geo-tile aggregation instead of geohash precision {pull}29776[#29776]
Infrastructure UI::
* Adapts settings ui to saved object version type change {pull}30082[#30082]
Kibana App:: 
* Fixes gauge filters {pull}30057[#30057]
* Fixes fieldformatter calls in pipeline helper {pull}29842[#29842]
* Adds pipeline field formatting {pull}28746[#28746]
* Removes `kibana_table` pipeline type {pull}28979[#28979]
* Moves renderers registry to OSS {pull}28986[#28986]
* Prepares for cut over to the visualize data loader from the current expression 
pipeline data loader {pull}29873[#29873]
* Toggles between Expression Pipeline & Visualize Data loader {pull}29874[#29874]
* Fixes every app that was wrapping `query` in an array unnecessarily {pull}27636[#27636]
* Fixes build issue and reintroduces new filter bar {pull}29752[#29752]
* Adds index pattern URL change notes {pull}30779[#30779]
* Fixes visualization filters to ignore invalid entries {pull}30633[#30633]
* Expands the size of add panels flyout and increases default rows per page {pull}30508[#30508]
Machine Learning::
* Removes use of types in datafeeds  {pull}27572[#27572]
* Fixes metric select double caret {pull}30357[#30357]
* Removes old angular based start datafeed modal {pull}30392[#30392]
* Handles removal of backend ml.enabled node attribute {pull}27604[#27604]
* Edits labels in the Apache and Nginx ECS data recognizer modules {pull}29935[#29935]
* Fixes for K7 compatibility {pull}30536[#30536]
* Fixes broken label style in advanced wizard {pull}30847[#30847]
* Adds ml-ui team to .github/CODEOWNERS {pull}29810[#29810]
Management::
* Removes grunt sterilize - its been replaced by `kbn clean` {pull}27825[#27825]
* Makes Index management table more responsive {pull}28882[#28882]
Monitoring::
* Stops using the normalized derivative value {pull}27416[#27416]
* Updates the title in the left nav to Stack Monitoring {pull}28102[#28102]
* Prepares the Monitoring UI codebase for the incoming changes to `hits.total` {pull}26442[#26442]
* Updates browser title to Stack Monitoring {pull}29638[#29638]
* Fixes Monitoring design {pull}29479[#29479]
* Removes old index patterns that are not expected in 7.0.0 onwards {pull}27915[#27915]
* Removes deprecated `xpack.monitoring.report_stats` setting {pull}30017[#30017]
* Fixes monitoring tests to work with mapping changes {pull}29188[#29188]
* Removes type filter helper {pull}30887[#30887]
Operations::
* Removes svg from url-loader, as it conflicts with other loaders {pull}30888[#30888]
* Uses apiVersion from es plugin in x-pack {pull}30853[#30853]
* Clones saved object document before migrating to prevent accidental mutations {pull}30475[#30475]
Observability::
* Fixes 7.x references to tcp.port {pull}29132[#29132]
* Ports functional tests to 7.x {pull}29398[#29398]
* Ports unit tests to master {pull}29876[#29876]
* Adds missing loading states for filter bar and snapshot components {pull}30122[#30122]
* Removes double-format for duration value {pull}30664[#30664]
Platform::
* Moves the table vis migration to {kib} plugin {pull}29478[#29478]
* Allows passing a default operator to use on saved object client find operations {pull}29339[#29339]
* Fixes saved object repository `bulkCreate` to return migrated references and attributes {pull}29754[#29754]
* Adds missing saved object reference handling for searchSourceJSON filter attribute {pull}29840[#29840]
* Excludes `migrationVersion` and references from `getRootPropertiesObjects` result {pull}30081[#30081]
* Removes dependency on doc versions {pull}29906[#29906]
* Adds typings for saved object client {pull}29951[#29951]
* Uses `lastSubUrl` when appropriate {pull}28735[#28735]
* Removes es _xpack endpoint usage {pull}29465[#29465]
* Adds typings for the `saved_object_finder` react component {pull}30067[#30067]
* Fixes the confirm overwrite modal of saved objects to handle large titles {pull}28590[#28590]
Reporting::
* Refactors routes files and helpers {pull}30111[#30111]
Rollups::
* Removes duplicate rendered sections {pull}28566[#28566]
Security::
* Adds tests for interpreter `createSocket` {pull}29459[#29459]
Visualizations::
* Adds autocomplete to Time Series Visual Builder {pull}30158[#30158]
* Fixes missing Markdown variables {pull}28173[#28173]
* Removes filter bar for Markdown visualizations {pull}30354[#30354]
* Corrects label for OS visualization in logs sample data {pull}30249[#30249]











[[release-notes-7.0.0-alpha2]]
== {kib} 7.0.0-alpha2


[float]
[[breaking-7.0.0-alpha2]]
=== Breaking changes

For more details about breaking changes in this release, see 
<<breaking-changes-7.0, Breaking changes in 7.0>>.

[float]
[[highlight-7.0.0-alpha2]]
=== Highlights
Canvas::
* Canvas now has a template tab in the workpad manager where users can find workpad templates, 
demos, and tutorials to help them get started. See {pull}23966[#23966] for more information.
Kibana App:: 
* Visualizations in Kibana will use a new data pipeline introduced as part of Canvas. 
The change does not yet apply to Vega, Timelion, or Time Series Visual Builder (TSVB). 
See {pull}25711[#25711] for more information.
Index Lifecyle Management:: 
* Implements a user interface to create, update, edit, or delete index lifecyle policies.
See {pull}25553[#25553] for more information.

[float]
[[enhancement-7.0.0-alpha2]]
=== Enhancements
Canvas::
* Implements a clipboard and stores the copied elements in `localStorage` {pull}25890[#25890]
* Adds the ability to reuse assets without editing an element's expression {pull}25764[#25764]
* Adds the `clear` function {pull}26397[#26397]
* Adds workpad-level CSS {pull}24143[#24143]
Dashboard::
* Adds `href` option in addition to `onClick` for navigational links {pull}25233[#25233]
Design::
* Updates logos for marketing {pull}25489[#25489]
* Adds Kibana 7.0 breadcrumbs to home screen {pull}26605[#26605]
* Moves elastic/eui typings to single file {pull}23950[#23950]
Kibana App::
* Maps inspector requests by id so single requests can be reset at a time {pull}26770[#26770]
* Adds ODBC to blurb for start trail {pull}27223[#27223]
Management::
* Adds `Request timestamp` to request inspector stats {pull}25667[#25667]
* Adds "Reload indices" button to Index Management {pull}27033[#27033]
Machine Learning::
* Adds the configuration files for two new auditbeat data recognizer modules for 
detecting unusual processes on hosts and Docker containers {pull}25716[#25716]
* Adds support for saved searches created using Kuery to the job wizards {pull}26094[#26094]
* Allows users to enter their own query in the Discover page; stops passing the query 
from the job datafeed config in custom URLs {pull}26957[#26957]
* Rewrites Calendar to React/EUI {pull}26741[#26741]
* Converts Setting page to React/EUI {pull}27144[#27144]
* Ensures loading indicator is present on initial jobs load {pull}27151[#27151]
* Prevents a new calendar save if a calendar with that id already exists {pull}27104[#27104]
Observability::
* Adds a new plugin for Uptime Monitoring {pull}25480[#25480]
Platform::
* Adds `rest_total_hits_as_int` to all requests in platform code that eventually 
look up `hits.total` {pull}26432[#26432]
* Adds `dist` flag to the configuration context {pull}26545[#26545]
* Prepares `@kbn/datemath` to be republished as `@elastic/datemath` {pull}26559[#26559]
* Wraps `remote` methods in `browser` service {pull}26394[#26394]
* Uses `stream.pipeline` to manage error handling {pull}27246[#27246]
Querying & Filtering::
* Moves the `buildESQuery` module (including filters and Kuery) into a separate package {pull}23345[#23345]
* Adds comment explaining why `getComputedFields` adds a `docvalue` to `docvalue_fields` 
for each date field in an index pattern. {pull}25725[#25725]
* Moves filtering functions out of `vis.API.events` {pull}25280[#25280]
Reporting::
* Adds browser type to the reporting side panel {pull}26307[#26307]
* Adds better logging for `waitForSelector` failure {pull}25762[#25762]
* Enhances error messaging and handling {pull}26299[#26299]
* Adds "Info" button in the Reporting listing {pull}25421[#25421]
Rollups::
* Adds support for rolling up metrics of date fields {pull}26450[#26450]
Security::
* Updates the GET `/api/security/role` endpoint to return the list of roles sorted 
by name, rather than creation date {pull}26491[#26491]
* Updates the Account Settings screen to show the change password form only when
a password change is possible for the authentication realm {pull}26779[#26779]
* Makes space selector a `button` {pull}26889[#26889]
Visualizations::
* Removes experimental flag from Visual Builder (TSVB) {pull}25634[#25634]
* Implements new visualization type selection {pull}23833[#23833]
* Removes `lab` stage for visualizations, making `experimental` the only non-production 
stage available {pull}25702[#25702]

[float]
[[bug-7.0.0-alpha2]]
=== Bug fixes
Canvas::
* Fixes page preview size issue {pull}26795[#26795]
* Fixes visual bug when opening the workpad loader {pull}26647[#26647]
* Fixes page thumbnail sizes {pull}26573[#26573]
* Decreases size of tray toggle {pull}25470[#25470]
* Makes selection border 1px {pull}26739[#26739]
* Fixes interpreter socket error {pull}26870[#26870]
Geo::
* Resolves URL dynamically when requesting EMS data {pull}25685[#25685]
* Fixes EMS hotlink {pull}26868[#26868]
Infrastructure UI:: 
* Fixes potential color bugs {pull}26292[#26292]
* Fixes auto refresh button on node detail page {pull}26426[#26426]
* Changes the time range from the last hour to the last 5 minutes for the Waffle Map {pull}26278[#26278]
* Passes flag in request to force BWC hit count {pull}26517[#26517]
* Replaces redux source slice with constate container {pull}26121[#26121]
* Changes node detail link to set time range to 1 hour {pull}26977[#26977]
* Stops showing sidenav while loading. {pull}27119[#27119]
* Fixes styling after breaking EUI changes {pull}27021[#27021]
* Fixes graphql type generation after package upgrades {pull}26991[#26991]
* Removes usage of `ts-optchain` in the browser {pull}27148[#27148]
Kibana App:: 
* Fixes support for React 16.4+ by only resetting state if adaptors are updated {pull}26138[#26138]
* Fixes scrolling list on Firefox {pull}26246[#26246]
* Guards against empty and undefined index pattern arrays passed to QueryBar {pull}24607[#24607]
* Removes unused indexPattern from vega/tsvb/timelion request handler {pull}26007[#26007]
* Passes global filters from editor down to visualize  {pull}26009[#26009]
* Stops using schemas in aggconfigs to output DSL {pull}26010[#26010]
* Fixes `kbn-interpreter` package to not import from UI {pull}26161[#26161]
* Fixes OSS dynamic plugin loading by reverting to Canvas way of loading plugins {pull}26463[#26463]
* Fixes other bucket option to correctly apply without having to change other settings {pull}26874[#26874]
* Adds `en` as a valid numeral locale setting {pull}25948[#25948]
* Adds `rest_total_hits_as_int` into Kibana App {pull}26404[#26404]
* Uses Canvas pipeline to fetch data inside Visualize {pull}25996[#25996]
Management::
* Fixes index pattern wizard when there are remote clusters but no local indices  {pull}24339[#24339]
* Uses new `_graph` endpoints {pull}26956[#26956]
* Adjusts spacing of Management navigation items {pull}25666[#25666]
* Updates "Disenroll" text to be consistent with menu option "Unenroll" {pull}26816[#26816]
* Fixes broken breadcrumb link for index management {pull}27164[#27164]
* Fixes issue with multiple execution in Console {pull}26933[#26933]
* Reloads full index list when reload hits missing index {pull}27197[#27197]
Machine Learning::
* Allows user to add/edit/delete annotations in the Single Series Viewer {pull}26034[#26034]
* Does not pass datafeed query to Discover in custom URL {pull}26957[#26957]
* Fixes word break in Anomalies and Jobs tables {pull}26978[#26978]
* Fixes alignment of filter icons in the Anomalies table {pull}26253[#26253]
Monitoring::
* Fixes error handling for local stats collection/permissions {pull}26560[#26560]
* Removes initial delay to check and send Telemetry data {pull}26575[#26575]
* Pulls local Kibana usage stats {pull}26496[#26496]
* Converts the Elasticsearch monitoring UIs to using EUI tables and page layout {pull}26217[#26217]
Platform & Operations::
* Decreases start limit and interval {pull}25474[#25474]
* Adds `--download` flag to snapshot command to warm the cache {pull}25830[#25830]
* Implements `--prefer-offline` flag {pull}25840[#25840]
* Fixes watcher routes broken by Hapi upgrade {pull}26713[#26713]
* Fixes non-conforming licenses on devDependencies and adds the ability to whitelist devOnly licenses {pull}23859[#23859]
* Watches optimizer cache invalidation  {pull}24172[#24172]
* Adds `normalizePath` in order to fix watch optimizer when running on Windows {pull}26486[#26486]
* Creates vendor dll for the client modules {pull}22618[#22618]
* Upgrades to NodeJS 10 {pull}25157[#25157]
* Improves plugin version mismatch error message {pull}25774[#25774]
* Improves build/packaging {pull}26096[#26096]
* Swaps `jstimezonedetect` with `moment.tz.guess` {pull}21800[#21800]
* Upgrades resize-observer-polyfill version {pull}26990[#26990]
* Fixes saved objects client `_processBatchQueue` function to handle errors {pull}26763[#26763]
* Changes kbn pm webpack config to generate dist files in mode=none {pull}26847[#26847]
* Hides logs from deleteAll on task: clean client modules into dll {pull}26884[#26884]
* Upgrades `resize-observer-polyfill` version {pull}26990[#26990]
* Uses `single-node` discovery type for the test ES node/cluster {pull}27125[#27125]
* Moves moment to peerDependency in elastic-datemath {pull}27264[#27264]
Reporting::
* Deletes `sortOrder` once items have been sorted and does not pass to `EuiContextMenuItem` 
in the share context menu {pull}26890[#26890]
* Fixes a regression bug in detection of Error and Warning toast notifications {pull}25482[#25482]
* Stops passing an empty `formatConfig` to the fieldFormats helper {pull}27168[#27168]
Rollups:: 
* Shows loading state in Rollup Job detail panel. {pull}25752[#25752]
* Specifies Rollup Jobs breadcrumbs in header. {pull}26590[#26590]
* Requires histogram interval in Rollup Job wizard to be a whole number. {pull}26596[#26596]
Security::
* Moves the server-side `SavedObjectClient` types from the `spaces` plugin to the 
same location as the corresponding JavaScript source files {pull}26448[#26448]
* Respects the `basePath` for the link to the user profile in the k7 header {pull}26417[#26417]
* Fixes `prettier` throw rule error  {pull}26071[#26071]
* Fixes authentication logic to fail out of auth flow on first provider failure {pull}26648[#26648]
* Fixes issues with the `url.search` being null in Node 10 {pull}26992[#26992]
* Fixes DLS query toggle on the role management page {pull}27213[#27213]
Visualizations::
* Fixes filter function on pie chart segment {pull}26321[#26321]
* Rewrites URL when closing vis type selection modal {pull}26327[#26327]
* Changes unbind calls from `.on` to `.off` {pull}24575[#24575]
* Fixes date field in controls visualization by generating labels with the field 
formatter {pull}25654[#25654]
* Replaces LESS files with Sass in `ui/public/vis`, `visLib`, and `visualize` {pull}25333[#25333]
* Replaces LESS files with Sass for the visualization types in `core_plugin/metrics` {pull}24250[#24250]
* Moves `timeout` to `_msearch` body to fix time series visual builder requests {pull}26510[#26510]
* Adds description for all visualization types {pull}26243[#26243]






[[release-notes-7.0.0-alpha1]]
== {kib} 7.0.0-alpha1

[float]
[[breaking-7.0.0-alpha1]]
=== Breaking changes

For more details about breaking changes in this release, see 
<<breaking-changes-7.0, Breaking changes in 7.0>>.

Discover::
* Does not apply `query:queryString:options` to `query_string` filters {pull}15640[#15640]
* Removes `default_field` from `query:queryString:options` {pull}18966[#18966]

Monitoring::
* Removes `node_resolver` setting {pull}21181[#21181]

Operations::
* Removes tribe node support {pull}16397[#16397]
* Creates separate startup scripts for development and production {pull}13806[#13806]
* Sets default port based on protocol  {pull}21564[#21564]
* Removes deprecated `/shorten` API {pull}21861[#21861]
* Plugin installer defers optimization step until server start {pull}26983[#26983]

[float]
[[deprecation-7.0.0-alpha1]]
=== Deprecations

Geo::
* Fixes legacy tilemap loading {pull}22095[#22095]

[float]
[[K7-design-7.0.0-alpha1]]
=== K7 UI Design

{kib} 7.0.0-alpha1 includes a new design for {kib} called K7. In this early stage, 
K7 is still a little rough around the edges. If you'd like to switch back to the 
existing K6 design, go to *Management > Advanced Settings* and turn 
off the *k7design* setting. The option to switch to the old design 
will be removed before 7.0.0 GA.

[float]
[[enhancement-7.0.0-alpha1]]
=== Enhancements

Machine Learning::
* Updates job type and APM module icon to new designs {pull}25380[#25380]
* Allows model plot enablement via checkbox in  MultiMetric/Population Job creation {pull}24914[#24914]
* Adds support for the rare detector for charts in Anomaly Explorer and Singe Metric viewer {pull}21524[#21524]

Reporting::
* Adds png output to reports {pull}24759[#24759]
* Sorts ascending on sort order first then ascending on name. Any menu item 
without a sort order gets set to zero. {pull}25058[#25058]

Visualizations::
* Adds a console.error for visualize errors {pull}24581[#24581]

[float]
[[bug-7.0.0]]
=== Bug fixes

APM::
* Overrides EUI chart default styles for gridlines {pull}21723[#21723]
* Adds section titles to span detail modal {pull}20717[#20717]

Canvas::
* Fixes duplicate `Value` options in math select value {pull}25556[#25556]
* Gets correct plugins path {pull}25448[#25448]
* Quotes the index pattern in SQL input {pull}25488[#25488]
* Decreases the size of tray toggle {pull}25470[#25470]
* Improves the plugin pre-build {pull}25267[#25267]

Dashboard::
* Removes `dashboardContext` function and makes Timelion, Vega, and Time Series 
Visual Builder use `buildEsQuery` {pull}23227[#23227]

Design::
* Converts Security UI from LESS to Sass {pull}25079[#25079]
* Adds boilerplate Sass for Kibana core {pull}21185[#21185]

Discover::
* Adds debug code to flaky field_data test {pull}15535[#15535]
* Gets even more debug info for flaky field_data test {pull}17627[#17627]

Geo::
* Fixes feature/align map config settings {pull}19450[#19450]

Kibana App::

* Adds warning to the `documentation_links` file about link validation gotcha {pull}24786[#24786]
* Adds workaround for `getDerivedStateFromProps` change in react 16.4 {pull}25142[#25142]

Kibana Home &amp; Add Data::
* Fixes "Set up index patterns" link on home page {pull}16128[#16128]

Machine Learning::
* Shows useful error on invalid query in JobList search bar {pull}25153[#25153]
* Adds user privilege check to Jobs List group selector control {pull}25225[#25225]
* Fixes file data viz file size check and formats as bytes {pull}25295[#25295]
* Fixes the layout of the cards in the Data Visualizer on IE {pull}25383[#25383]
* Adds better error reporting for reading and importing data {pull}24269[#24269]
* Displays an ordinal y axis for low cardinality rare charts {pull}24852[#24852]
* Fixes typo in job validation message {pull}25130[#25130]
* Removes deprecated `angularjs` based jobs list and related code {pull}25216[#25216]

Management::
* Adds boilerplate for remote clusters management app {pull}25369[#25369]
* Adds `ignore_failure` to ingest common auto complete in console {pull}24915[#24915]
* Removes support for expression-based scripted fields {pull}14310[#14310]
* Adds WatchErrors to capture invalid watches {pull}23887[#23887]
* Rewords the translation id for error with missing property in Watcher {pull}24753[#24753]

Monitoring::
* Renames Monitoring `FormattedMessage` to `FormattedAlert` {pull}24197[#24197]
* Uses the cluster name from metadata if it exists {pull}24495[#24495]

Operations::
* Removes node fallback from kibana-keystore {pull}15066[#15066]
* Adds debug script to set inspect flags {pull}15967[#15967]
* Uses snake case for scripts/kibana-keystore.js and scripts/kibana-plugin.js {pull}15331[#15331]
* Updates license info in package.json {pull}20353[#20353]
* Fixes error log formatting {pull}24788[#24788]
* Matches chalk dependency version on Kibana with the one used on X-Pack {pull}20621[#20621]
* Fixes non-conforming licenses on devDependencies and adds the ability to whitelist devOnly licenses {pull}23859[#23859]
* Adds jsxa11y into eslint rules {pull}23932[#23932]
* Reverts Bump react-grid-layout to 0.16.0 {pull}14912[#14912]
* Reverts breaking change for Status API {pull}21927[#21927]
* Converts `utils/collection` to TypeScript {pull}23992[#23992]
* Removes usage of update_all_types {pull}16406[#16406]
* Improves the `yarn kbn bootstrap` speed by using yarn workspaces for packages inside `packages/*` and `x-pack` {pull}24095[#24095]
* Runs jenkins:unit task with dev flag in order to run license check {pull}19832[#19832]
* Does not break on startup in debug mode {pull}19219[#19219]


Platform::
* Transforms plugin deprecations before checking for unused settings {pull}21294[#21294]
* Expands list of restricted globals in `eslint-config-kibana` {pull}15798[#15798]
* Makes logs easier to read on Windows with chalk colors {pull}15557[#15557]

Querying &amp; Filtering::
* Fixes wildcard queries against the default field {pull}24778[#24778]

Reporting::
* Returns promise in Reporting jobs API {pull}24769[#24769]

Security::
* Implements the K7 login screen {pull}23512[#23512]

Sharing::

* Fixes issue with debounce function running after component was unmounted {pull}15045[#15045]

Visualizations::
* Defaults the scroll wheel zoom to false on Vega maps {pull}21169[#21169]
* Fixes problem within the input_vis_control plugin that prevents it from updating correctly 
if the field is switched, and then switched back to the previous field {pull}25164[#25164]
* Uses `vega-nocanvas` instead of vega lib {pull}16137[#16137]
* Migrates visualization from Angular to React {pull}16425[#16425]
* Fixes maps for reporting (#15272) {pull}15358[#15358]
* Stops creation of nested search source per postflightrequest {pull}20373[#20373]
* Moves inspector code from Vis to embeddable visualize handler {pull}24112[#24112]
* Removes inspector from Vis {pull}24112[#24112]




