[[release-notes]]
= Release Notes

[partintro]
--
// Use these for links to issue and pulls. Note issues and pulls redirect one to
// each other on Github, so don't worry too much on using the right prefix.
:issue: https://github.com/elastic/kibana/issues/
:pull: https://github.com/elastic/kibana/pull/

This section summarizes the changes in each release.

* <<release-notes-8.0.0-alpha1>>

--


[[release-notes-8.0.0-alpha1]]
== {kib} 8.0.0-alpha1

coming[8.0.0]

[[release-notes-8.0.0]]
== {kib} 8.0.0

coming::[8.0.0]

For information about the {kib} 8.0.0 release, review the following information.

[float]
[[breaking-changes-8.0.0]]
=== Breaking changes

Breaking changes can prevent your application from optimal operation and performance.
Before you upgrade to 8.0.0, review the breaking changes, then mitigate the impact to your application.

// tag::notable-breaking-changes[]

[discrete]
[[breaking-106307]]
.Require security plugin in 8.0
[%collapsible]
====
*Details* +
Enterprise Search now requires X-Pack Security to be enabled. For more information, refer to {kibana-pull}106307[#106307]

*Impact* +
Enable X-Pack Security.
====
      
[discrete]
[[breaking-106061]]
.Provide sensible defaults 
[%collapsible]
====
*Details* +
The default values for for `xpack.security.session.{lifespan|idleTimeout}` session timeout settings have changed. For more information, refer to {kibana-pull}106061[#106061]

*Impact* +
Use the following default values:

* `xpack.security.session.idleTimeout: 1h`
* `xpack.security.session.lifespan: 30d`
====
      
[discrete]
[[breaking-93835]]
.Remove platform from archive root directory
[%collapsible]
====
*Details* +
For the `.tar.gz` and `.zip` archives, `platform` has been removed from the `root` folder name. For more information, refer to {kibana-pull}93835[#93835]

*Impact* +
Before:

`kibana-8.0.0-SNAPSHOT-linux-aarch64.tar.gz -> kibana-8.0.0-SNAPSHOT-aarch64`

After:

`kibana-8.0.0-SNAPSHOT-linux-aarch64.tar.gz -> kibana-8.0.0-SNAPSHOT`
====
      
[discrete]
[[breaking-90511]]
.Remove default support for TLS v1.0 and v1.1
[%collapsible]
====
*Details* +
Removes the default support for TLS v1.0 and v1.1. For more information, refer to {kibana-pull}90511[#90511]

*Impact* +
To enable support, set the environment variable to `NODE_OPTIONS=--tls-min-1.0`.
====
      
[discrete]
[[breaking-87114]]
.Remove support for setting server.host to '0' (breaking)
[%collapsible]
====
*Details* +
Removes support for configuring {kib} with `0` as the `server.host`. For more information, refer to {kibana-pull}87114[#87114]

*Impact* +
You are now unable to use `0` as the `server.host`.
====
      
[discrete]
[[breaking-74424]]
.Remove sysv
[%collapsible]
====
*Details* +
Systems that don't have service aliased to use kibana.service are unable to use should use `service start kibana`. For more information, refer to {kibana-pull}74424[#74424]

*Impact* +
If your system doesn't have service aliased to use kibana.service, use `systemctl start kibana.service`.
====
      
[discrete]
[[breaking-64853]]
.Switch Reporting to Task Manager
[%collapsible]
====
*Details* +
Removes the ES-Queue subservice of *Reporting*, and replaces the functionality with *Task Manager* integration. For more information, refer to {kibana-pull}64853[#64853]

*Impact* +
Before you upgrade to 8.0.0, make sure there are no pending reporting jobs. If you have pending reporting jobs, they will indefinitely remain in the pending state.
====
      
[discrete]
[[breaking-52539]]
.Remove legacy Reporting job params compatibility shim
[%collapsible]
====
*Details* +
*Reporting* is no longer compatible with POST URL snippets generated with {kib} 6.2.0 and earlier. For more information, refer to {kibana-pull}52539[#52539]

*Impact* +
If you depend on POST URL snippets to automatically generate PDF reports, regenerate the POST URL strings.
====
      
[discrete]
[[breaking-47929]]
.Drop `/api/security/v1/saml` route in favour of `/api/security/saml/callback`
[%collapsible]
====
*Details* +
!!TODO!! For more information, refer to {kibana-pull}47929[#47929]

*Impact* +
!!TODO!!
====
      
[discrete]
[[breaking-42353]]
.Disables response logging as a default
[%collapsible]
====
*Details* +
!!TODO!! For more information, refer to {kibana-pull}42353[#42353]

*Impact* +
!!TODO!!
====
      
[discrete]
[[breaking-41700]]
.Reject legacy browsers by default
[%collapsible]
====
*Details* +
!!TODO!! For more information, refer to {kibana-pull}41700[#41700]

*Impact* +
!!TODO!!
====
      
[discrete]
[[breaking-38657]]
.Make `xpack.security.authc.saml.realm` mandatory and completely remove `xpack.security.authProviders` and `xpack.security.public`
[%collapsible]
====
*Details* +
!!TODO!! For more information, refer to {kibana-pull}38657[#38657]

*Impact* +
!!TODO!!
====
      
[discrete]
[[breaking-35173]]
.Remove support for time-based interval index patterns
[%collapsible]
====
*Details* +
!!TODO!! For more information, refer to {kibana-pull}35173[#35173]

*Impact* +
!!TODO!!
====
      
[discrete]
[[breaking-22696]]
.Remove useUTC deprecation, set default timezone to local
[%collapsible]
====
*Details* +
!!TODO!! For more information, refer to {kibana-pull}22696[#22696]

*Impact* +
!!TODO!!
====
      

// end::notable-breaking-changes[]

[float]
[[deprecations-8.0.0]]
=== Deprecations

The following functionality is deprecated in 8.0.0, and will be removed in 9.0.0.
Deprecated functionality does not have an immediate impact on your application, but we strongly recommend
you make the necessary updates after you upgrade to 8.0.0.

[discrete]
[[deprecation-74424]]
.Remove sysv
[%collapsible]
====
*Details* +
!!TODO!! For more information, refer to {kibana-pull}74424[#74424]

*Impact* +
!!TODO!!
====
      
[discrete]
[[deprecation-33603]]
.Remove deprecated xpack:defaultAdminEmail
[%collapsible]
====
*Details* +
!!TODO!! For more information, refer to {kibana-pull}33603[#33603]

*Impact* +
!!TODO!!
====
      

For more information about the features introduced in 8.0.0, refer to <<whats-new,What's new in 8.0>>.

[[enhancements-and-bug-fixes-v8.0.0]]
=== Enhancements and bug fixes

For detailed information about the 8.0.0 release, review the enhancements and bug fixes.

[float]
[[breaking-v8.0.0]]
=== Breaking
[discrete]
[[breaking-106307]]
.Require security plugin in 8.0
[%collapsible]
====
*Details* +
!!TODO!! For more information, refer to {kibana-pull}106307[#106307]

*Impact* +
!!TODO!!
====
      
[discrete]
[[breaking-106061]]
.Provide sensible defaults for `xpack.security.session.{lifespan|idleTimeout}`
[%collapsible]
====
*Details* +
!!TODO!! For more information, refer to {kibana-pull}106061[#106061]

*Impact* +
!!TODO!!
====
      
[discrete]
[[breaking-93835]]
.Removes platform from root folder name for `.tar.gz` and `.zip` archives
[%collapsible]
====
*Details* +
!!TODO!! For more information, refer to {kibana-pull}93835[#93835]

*Impact* +
!!TODO!!
====
      
[discrete]
[[breaking-90511]]
.Remove default support for TLS v1.0 and v1.1
[%collapsible]
====
*Details* +
!!TODO!! For more information, refer to {kibana-pull}90511[#90511]

*Impact* +
!!TODO!!
====
      
[discrete]
[[breaking-87114]]
.Remove support for setting server.host to '0' (breaking)
[%collapsible]
====
*Details* +
!!TODO!! For more information, refer to {kibana-pull}87114[#87114]

*Impact* +
!!TODO!!
====
      
[discrete]
[[breaking-74424]]
.Remove sysv
[%collapsible]
====
*Details* +
!!TODO!! For more information, refer to {kibana-pull}74424[#74424]

*Impact* +
!!TODO!!
====
      
[discrete]
[[breaking-64853]]
.Switch Reporting to Task Manager
[%collapsible]
====
*Details* +
!!TODO!! For more information, refer to {kibana-pull}64853[#64853]

*Impact* +
!!TODO!!
====
      
[discrete]
[[breaking-52539]]
.Remove reporting legacy job params compatibility shim
[%collapsible]
====
*Details* +
!!TODO!! For more information, refer to {kibana-pull}52539[#52539]

*Impact* +
!!TODO!!
====
      
[discrete]
[[breaking-47929]]
.Drop `/api/security/v1/saml` route in favour of `/api/security/saml/callback`
[%collapsible]
====
*Details* +
!!TODO!! For more information, refer to {kibana-pull}47929[#47929]

*Impact* +
!!TODO!!
====
      
[discrete]
[[breaking-42353]]
.Disables response logging as a default
[%collapsible]
====
*Details* +
!!TODO!! For more information, refer to {kibana-pull}42353[#42353]

*Impact* +
!!TODO!!
====
      
[discrete]
[[breaking-41700]]
.Reject legacy browsers by default
[%collapsible]
====
*Details* +
!!TODO!! For more information, refer to {kibana-pull}41700[#41700]

*Impact* +
!!TODO!!
====
      
[discrete]
[[breaking-38657]]
.Make `xpack.security.authc.saml.realm` mandatory and completely remove `xpack.security.authProviders` and `xpack.security.public`
[%collapsible]
====
*Details* +
!!TODO!! For more information, refer to {kibana-pull}38657[#38657]

*Impact* +
!!TODO!!
====
      
[discrete]
[[breaking-35173]]
.Remove support for time-based interval index patterns
[%collapsible]
====
*Details* +
!!TODO!! For more information, refer to {kibana-pull}35173[#35173]

*Impact* +
!!TODO!!
====
      
[discrete]
[[breaking-22696]]
.Remove useUTC deprecation, set default timezone to local
[%collapsible]
====
*Details* +
!!TODO!! For more information, refer to {kibana-pull}22696[#22696]

*Impact* +
!!TODO!!
====
      

[float]
[[deprecation-v8.0.0]]
=== Deprecations
[discrete]
[[deprecation-74424]]
.Remove sysv
[%collapsible]
====
*Details* +
!!TODO!! For more information, refer to {kibana-pull}74424[#74424]

*Impact* +
!!TODO!!
====
      
[discrete]
[[deprecation-33603]]
.Remove deprecated xpack:defaultAdminEmail
[%collapsible]
====
*Details* +
!!TODO!! For more information, refer to {kibana-pull}33603[#33603]

*Impact* +
!!TODO!!
====
      

[float]
[[fixes-v8.0.0]]
=== Bug Fixes
Operations::
* Move systemd service to /usr/lib/systemd/system {kibana-pull}83571[#83571]