[[change_list]]
== Change list

=== 1.2.1
  - Fix a cluster state data shipping for cluster states larger than 16K (in `SMILE` format and without meta data).

=== 1.2.0
  - New Shard Allocation Dashboard.
  - Simplified navigation and dashboard customization.
  - Sense:
    * Update the KB to the ES 1.2.0 API, adding the following:
      * `_cat/plugins`
      * `_cat/segments`
      * `_search/template`
      * `_count`
      * `_snapshot`
      * Alias support for index creation.
      * Significant terms aggregation.
      * Percentiles aggregation.
      * Cardinality aggregation.
      * Time_zone keyword to date_histogram facet/aggregation.
    * Removed deprecated `custom_score` & `custom_boost_factor` from the 1.0 API.
    * Fixed a bug causing the query panel to loose focus after running a command.

  - Charts and Dashboards changes:
    * Added an information icon next to the status information of Cluster Summary panel. Hovering on it will show a
      short explanation of current status.
    * The indices stats table in the Overview dashboard now shows an information icon next to red and yellow indices.
      Hovering on it will show a short shard level summary.
    * Marvel's index template will now be automatically updated upon upgrade.
    * Added field data & filter cache eviction charts to Node Stats dashboard and Index Stats dashboard.
    * Added field data circuit breaker charts to Node Stats dashboard.
    * Added a registration & purchasing form.
    * Hidden indexes are now shown by default.
    * Default cluster pulse default time span to 7 days.
    * Fixed: Split brain detection algorithm didn't fire in some configurations.


  - `marvel.agent.exporter.es.host` configuration option now defaults to port 9200.


=== 1.1.1
  - Fixed: agent did not interpret timeout settings correctly, causing potential connectivity errors when shipping data.

=== 1.1.0
  - Improved Sense's autocomplete suggestions:
    * Added Snapshot & Restore
    * Added Aggregations
    * Added support for url query string parameters
    * Updated for breaking changes in Elasticsearch 1.0
  - Updated welcome splash screen.
  - Sense now uses the last used server when opened (previously used the hostname used to access it).
  - The agent's keep-alive thread is now stopped upon errors to reduce log noise. It will be restarted
    upon successful connection.
  - Improved error reporting for failures of items in the agent's bulk requests.
  - Index Statistics Dashboard: Indexing Rate Primaries chart was based on the wrong field.
  - Introduced `marvel.agent.shard_stats.enabled` to control exporting of shard level statistics. Defaults to `false`.
  - Changed agent's default sampling rate to 10s (was 5s)
  - Added a visual indication for the master node at the Nodes section of the Overview Dashboard
  - Node and Indices tables visually indicate stale data
  - Added error reporting to nodes and indices tables
  - Made the following agent settings changeable via the Cluster Update Settings API:
    * marvel.agent.interval  (also supports setting to -1 to disable exporting)
    * marvel.agent.exporter.es.hosts
    * marvel.agent.exporter.es.timeout
    * marvel.agent.shard_stats.enabled

=== 1.0.2
  - Kibana uses `window.location.protocol` (http or https) to make ES calls.
  - Added support for basic authentication when sending data from agent. See <<configuration>>.
  - Reduced DEBUG logging verbosity.

=== 1.0.1
  - fixed an issue with usage statistics report.
  - improve logging message when running on old Elasticsearch versions.
