[[release-notes]]
= Release notes

[partintro]
--
// Use these for links to issue and pulls. Note issues and pulls redirect one to
// each other on Github, so don't worry too much on using the right prefix.
:issue: https://github.com/elastic/kibana/issues/
:pull: https://github.com/elastic/kibana/pull/

Review important information about the {kib} 9.x releases.

* <<release-notes-9.0.0>>

--


include::upgrade-notes.asciidoc[]

[[release-notes-9.0.0]]
== {kib} 9.0.0

For information about the {kib} 9.0.0 release, review the following information.

[float]
[[breaking-changes-9.0.0]]
=== Breaking changes

[discrete]
.Access to all internal APIs is blocked (9.0.0)
[%collapsible]
====
*Details* +
Access to internal Kibana HTTP APIs is restricted from version 9.0.0. This is to ensure
that HTTP API integrations with Kibana avoid unexpected breaking changes. 
Refer to {kibana-pull}193792[#193792].

*Impact* +
Any HTTP API calls to internal Kibana endpoints will fail with a 400 status code starting
from version 9.0.0.

*Action* +
**Do not integrate with internal HTTP APIs**. They may change or be removed without notice, 
and lead to unexpected behaviors. If you would like some capability to be exposed over an
HTTP API, https://github.com/elastic/kibana/issues/new/choose[create an issue].
We would love to discuss your use case.

====

[float]
[[deprecations-9.0.0]]
=== Deprecations

[float]
[[features-9.0.0]]
=== Features

For more information about the features introduced in 9.0.0, refer to <<whats-new,What's new in 9.0>>.

[[enhancements-and-bug-fixes-v9.0.0]]
=== Enhancements and bug fixes

For detailed information about the 9.0.0 release, review the enhancements and bug fixes.
      

[float]
[[enhancement-v9.0.0]]
=== Enhancements

[float]
[[fixes-v9.0.0]]
=== Bug fixes