[[release-notes]]
= Release notes

[partintro]
--
// Use these for links to issue and pulls. Note issues and pulls redirect one to
// each other on Github, so don't worry too much on using the right prefix.
:issue: https://github.com/elastic/kibana/issues/
:pull: https://github.com/elastic/kibana/pull/

Review important information about the {kib} 7.12.x releases.

* <<release-notes-7.12.0>>

////
TEMPLATE:

[[release-notes-x.x.x]]
== {kib} x.x.x

coming::[x.x.x]

For information about the {kib} x.x.x release, review the following information.

[float]
[[breaking-changes-x.x.x]]
=== Breaking change

Breaking changes can prevent your application from optimal operation and performance. Before you upgrade to x.x.x, review the breaking change, then mitigate the
impact to your application.

// The following section is re-used in the Installation and Upgrade Guide

// tag::notable-breaking-changes[]

[discrete]
[[x.x.x-breaking-change]]
.Breaking change title
[%collapsible]
====
*Details:* +

*Impact* +

====

// end::notable-breaking-changes[]

[float]
[[deprecation-vx.x.x]]
=== Deprecations

The following functionality is deprecated in x.x.x, and will be removed in 8.0.0. Deprecated functionality does not have an immediate impact on your application, but 
we strongly recommend you make the necessary updates after you upgrade to x.x.x. 

[discrete]
[[alerting-7.12.0-deprecation]]
.Deprecation title
[%collapsible]
====
*Details* +

*Impact* +

====

[float]
[[known-issues-vx.x.x]]
=== Known issues

[float]
[[feaatures-vx.x.x]]
=== Features

{kib} x.x.x adds the following new and notable features.

For more information about the new features introduced in x.x.x, refer to 
//{kibana-ref-all}/x.x/whats-new.html[What's new in x.x].

For detailed information about the x.x.x release, refer to <<enhancements-and-bug-fixes-vx.x.x,Enhancements and bug fixes>>.

[[enhancements-and-bug-fixes-vx.x.x]]
=== Enhancements and bug fixes

The x.x.x release includes the following enhancements and bug fixes. 

[float]
[[enhancement-vx.x.x]]
=== Enhancements

[float]
[[bug-vx.x.x]]
=== Bug fixes

////

--

[[release-notes-7.12.0]]
== {kib} 7.12.0

coming::[7.12.0]

For information about the {kib} 7.12.0 release, review the following information.

[float]
[[breaking-changes-7.12.0]]
=== Breaking change

Breaking changes can prevent your application from optimal operation and performance. Before you upgrade to 7.12.0, review the breaking change, then mitigate the
impact to your application.

// The following section is re-used in the Installation and Upgrade Guide

// tag::notable-breaking-changes[]

[discrete]
[[maps-7.12.0-breaking-change]]
.Removes the Geo threshold alert type
[%collapsible]
====
*Details:* +
Geo containment alerts and the Geo threshold alert type have similar functionality, so the Geo threshold alert type has been removed. For more information, refer to {kibana-pull}89632[#89632].

*Impact* +
Use Geo containment alerts.
====

// end::notable-breaking-changes[]

[float]
[[deprecation-v7.12.0]]
=== Deprecations

The following functionality is deprecated in 7.12.0, and will be removed in 8.0.0. Deprecated functionality does not have an immediate impact on your application, but 
we strongly recommend you make the necessary updates after you upgrade to 7.12.0. 

[discrete]
[[alerting-7.12.0-deprecation]]
.Deprecates `services.callCluster` in alerts and actions executors
[%collapsible]
====
*Details* +
Deprecates `services.callCluster` in the alert and action type executors. For more information, refer to {kibana-pull}86474[#86474].

*Impact* +
Use `services.scopedClusterClient`.
====

[discrete]
[[management-7.12.0-deprecation]]
.Deprecates configuring [kib] with a `server.host` value of `0`
[%collapsible]
====
*Details* +
In the new version of joi, `0` is an invalid hostname. When upgraded, the extra validate function can be removed. For more information, refer to {kibana-pull}87114[#87114].

*Impact* +
To bind to all interfaces, use `0.0.0.0`.
====

[discrete]
[[platform-7.12.0-deprecation]]
.Deprecates the use of `elasticsearch.logQueries`
[%collapsible]
====
*Details* +
When `logging.verbose: true` or `logging.root.level: 'debug'`, {es} query logs are now always shown. 
In 7.11.0 and earlier, {es} query logs were not included in verbose logging unless `elasticsearch.logQueries` was configured. 
For more information, refer to {kibana-pull}89296[#89296].

*Impact* +
To use verbose logging without {es} query logs, configure the query logs to `off` in kibana.yml:
[source,js]
----
logging:
  loggers:
     - context: elasticsearch.query
       level: off
----
====

[float]
[[known-issues-v7.12.0]]
=== Known issue

When you create aggregation-based area, bar, and line charts in *Visualize Library*, then split the charts by column, the time filter is applied incorrectly.

To resolve this issue, use the legacy charts library.

. Open the main menu, then click *Stack Management > Advanced settings*.

. Select *Legacy charts library*.
+
For more information, refer to {kibana-pull}94252[#94252].

[float]
[[feaatures-v7.12.0]]
=== Features

{kib} 7.12.0 adds the following new and notable features.

Alerting::
* Adds Search alert {kibana-pull}88528[#88528]
APM::
* Correlations Beta (#86477) {kibana-pull}89952[#89952]
Dashboard::
* Adds the ability to copy a panel to another dashboard {kibana-pull}90856[#90856]
Discover::
* Adds "Hide chart" / "Show chart" persistence {kibana-pull}88603[#88603]
{kib} Home & Add Data::
* Adds custom global header banner {kibana-pull}87438[#87438]
Elastic Security::
For the Elastic Security 7.12.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Lens and visualizations::
* Adds the counter rate, cumulative sum, differences and moving average functions to *Lens* {kibana-pull}84384[#84384]
* Adds the percentile function to *Lens* {kibana-pull}86490[#86490]
* Adds support for histogram mapping type for all numeric functions in *Lens* {kibana-pull}90357[#90357]
* Renames *Visualize* to *Visualize Library* {kibana-pull}91015[#91015]
Logs::
* Show anomalies across the log rate and categorization ML jobs in a swimlane visualization {kibana-pull}89589[#89589]
Management::
* Adds Search Sessions, which enable users to Inspect, Extend, or Delete a saved Search Session {kibana-pull}81707[#81707]
* Allows configuration of expiration, tracking interval, and other Search Session related settings in kibana.yml {kibana-pull}88023[#88023]
* Enables Search Sessions in Discover and Dashboard {kibana-pull}91097[#91097]
* Redesign of the policy phases {kibana-pull}88671[#88671]
* Adds userPermissions method to plugin start interface {kibana-pull}89232[#89232]
* Moves the IndexPatternManagement.formatEditors API to IndexPatternFieldEditor.formatEditors {kibana-pull}89259[#89259]
Maps::
* Removes the Geo containment alert type experimental config settings and refs {kibana-pull}90301[#90301]
Monitoring::
* Removes support for the legacy elasticsearch client from the usage collector's fetch context {kibana-pull}87356[#87356]
Platform::
* Adds the ability to sync colors on dashboard panels {kibana-pull}86180[#86180]
* Explicit typings for request handler context {kibana-pull}88718[#88718]
* Enforce camelCase plugin IDs {kibana-pull}90752[#90752]
Uptime::
* ServiceNow SIR Connector {kibana-pull}88190[#88190]

For more information about the new features introduced in 7.12.0, refer to 
//{kibana-ref-all}/7.12/whats-new.html[What's new in 7.12].

For detailed information about the 7.12.0 release, refer to <<enhancements-and-bug-fixesV7.12.0,Enhancements and bug fixes>>.

[[enhancements-and-bug-fixesV7.12.0]]
=== Enhancements and bug fixes

The 7.12.0 release includes the following enhancements and bug fixes. 

[float]
[[enhancement-v7.12.0]]
=== Enhancements
Alerting::
* Alert and Connector flyouts Save and Save&Test buttons should be active by default. {kibana-pull}86708[#86708]
* Adds a "Refresh" button to the alerts list and alert details views {kibana-pull}87016[#87016]
* Allow user to select existing connector of same type when fixing broken connector {kibana-pull}89062[#89062]
* Adds support for custom alert ids {kibana-pull}89814[#89814]
APM::
* Showing confirmation modal on Alert Add/Edit when flyout closed without saving and changes made. {kibana-pull}86370[#86370]
* Instances latency distribution chart {kibana-pull}88546[#88546]
* Round start and end values {kibana-pull}89030[#89030]
Canvas::
* Adds support for IP data type {kibana-pull}85087[#85087]
* Adds Label option for Dropdown Control {kibana-pull}88505[#88505]
Dashboard::
* Adds URL encoding for URL drilldowns {kibana-pull}86902[#86902]
* Removes Panels from URL {kibana-pull}86939[#86939]
* Adds URL template editor {kibana-pull}88577[#88577]
* Enable right click on visualizations and dashboards listings {kibana-pull}88936[#88936]
* Adds Save as button to top menu {kibana-pull}90320[#90320]
* Improves error messages when in Dashboard {kibana-pull}90668[#90668]
* Adds Unsaved Changes Badge {kibana-pull}91073[#91073]
* Combines Discard & Cancel {kibana-pull}91267[#91267]
* Adds the ability to stay in Edit Mode After Dashboard Quicksave {kibana-pull}91729[#91729]
* Dashboard Save As New by Default {kibana-pull}91761[#91761]
Discover::
* Change default sort handling {kibana-pull}85561[#85561]
* Replaces EuiCodeBlock with Monaco editor {kibana-pull}90781[#90781]
{kib} Home & Add Data::
* Fixes values of `products.min_price` field in Kibana sample ecommerce data set {kibana-pull}90428[#90428]
* Navigation search now implements keyword registration for applications, allowing you to search for applications by keywords as well as by title {kibana-pull}85686[#85686]
* Updated favicons {kibana-pull}87271[#87271]
Elastic Security::
For the Elastic Security 7.12.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Lens and visualizations::
* Adds more in-editor Advanced documentation in *Lens* {kibana-pull}86821[#86821]
* Adds specific IP and Range/Interval sorting to datatable in *Lens* {kibana-pull}87006[#87006]
* Use datagrid with resizable columns for datatable in *Lens* {kibana-pull}88069[#88069]
* Use first decimal when required for data summaries in *Lens* {kibana-pull}88463[#88463]
* Hide column in *Lens* table {kibana-pull}88680[#88680]
* Table column text alignment in *Lens* {kibana-pull}89300[#89300]
* Allow custom label for fields via index pattern field management in *TSVB* {kibana-pull}84612[#84612]
* Align *Lens* and *Visualize Library* top nav buttons and behaviour {kibana-pull}86922[#86922]
* Align *Lens* and *Visualize Library* breadcrumbs {kibana-pull}86941[#86941]
* User should be able to set a specific tilemap service using the mapStyle property in *Vega* {kibana-pull}88440[#88440]
* Leaflet (https://leafletjs.com/) map layer in *Vega* was replaced by MapBox (https://www.mapbox.com/) {kibana-pull}88605[#88605]
* Communicate the index pattern to the dashboard for *Timelion* visualizations {kibana-pull}90623[#90623]
* Adds a new "Series Agg" to count the number of series in *TSVB* {kibana-pull}91225[#91225]
* Support min and max with histogram data types in *TSVB* {kibana-pull}91581[#91581]
* Adds possibility to folding in CodeEditor. Updates 'spec viewer' in *Vega* and 'request/response code viewer' in inspector {kibana-pull}90152[#90152]
Logs::
* Adds sorting capabilities to categories page {kibana-pull}88051[#88051]
* Display category in anomalies table {kibana-pull}88677[#88677]
Machine Learning::
* Adds documentation links in the help menu for machine learning {kibana-pull}85366[#85366]
* Redesign file-based Data Visualizer {kibana-pull}87598[#87598]
* Data Frame Analytics: Adds scatterplot matrix to regression/classification results pages. {kibana-pull}88353[#88353]
* Anomaly Detection: add anomalies map to explorer for jobs with 'lat_long' function {kibana-pull}88416[#88416]
* Improves model snapshot revert UI experience {kibana-pull}88588[#88588]
* Adds embedded map to geo_point fields for Data Visualizer {kibana-pull}88880[#88880]
* Adds ML deep links to navigational search {kibana-pull}88958[#88958]
* Anomaly Detection alert type {kibana-pull}89286[#89286]
* Adds Lens and Discover integration to index based Data Visualizer {kibana-pull}89471[#89471]
* Data Frame Analytics creation: improve existing job check {kibana-pull}89627[#89627]
* Data Frame Analytics: ROC Curve Chart {kibana-pull}89991[#89991]
* Data Frame Analytics: Support early stopping data frame analytics job parameter {kibana-pull}90695[#90695]
* Data Frame Analytics creation wizard: adds support for extended hyper-parameters {kibana-pull}90843[#90843]
* Adds Create Data Frame Analytics card to Data Visualizer {kibana-pull}91011[#91011]
* Anomaly Detection: when no anomalies present for time range show no results message {kibana-pull}91151[#91151]
* Adds index pattern runtime fields to anomaly detection wizards {kibana-pull}91168[#91168]
* Anomaly Detection alert initialisation from the ML app  {kibana-pull}91283[#91283]
* Prevent duplicate notifications about the same anomaly result  {kibana-pull}91485[#91485]
* Filtering runtime mappings in anomaly detection wizards {kibana-pull}91534[#91534]
Management::
* Adds support to configure a URI parts processor {kibana-pull}86163[#86163]
* In Index Management, Data Streams tab now displays data streams with long names much better {kibana-pull}86285[#86285]
* Adds a timeline component to the Index Lifecycle Management plugin so that users get a more intuitive understanding of how long data will be in a given phase {kibana-pull}88024[#88024]
* Adds runtime fields to index patterns and searchsource {kibana-pull}88542[#88542]
* Adds a field editor in the index pattern management app that lets you create and edit runtime fields, adding them to the index pattern field list {kibana-pull}88995[#88995]
* Adds better UI support for runtime fields Transforms  {kibana-pull}90363[#90363]
* Transforms: Adds retention policy options to transform UI {kibana-pull}91162[#91162]
* Transforms: Adds missing bucket checkbox to group by popover form {kibana-pull}91650[#91650]
Maps::
* Always show solution layers {kibana-pull}86053[#86053]
* Labels for polygons and lines {kibana-pull}86191[#86191]
* Term join limit {kibana-pull}86491[#86491]
* Show map saved objects in visualize listing page {kibana-pull}87165[#87165]
* Set containment alert recovery action group to 'No longer contained' {kibana-pull}87182[#87182]
* Support geometry-collection {kibana-pull}87867[#87867]
* Scale control {kibana-pull}88031[#88031]
* Use chart pallete registry to support sync colors in dashboard {kibana-pull}88099[#88099]
* Allow saving maps to dashboards {kibana-pull}88759[#88759]
Metrics::
* Adds custom metrics to node tooltip {kibana-pull}88545[#88545]
* Adds ability to filter anomaly detection datafeed {kibana-pull}89721[#89721]
* Adds helper text to of expressions when creating Threshold Alerts {kibana-pull}89750[#89750]
* Adds warning severity to Metric Alerts {kibana-pull}90070[#90070]
* Adds ability for user to set anomaly threshold {kibana-pull}90313[#90313]
Monitoring::
* Removes deprecated watcher-based cluster alerts {kibana-pull}85047[#85047]
* Large shard alert {kibana-pull}89410[#89410]
* Enable edit/create for Stack Monitoring alerts in Alerts Management {kibana-pull}91726[#91726]
Operations::
* Adds docker images for ARM64 based operating systems {kibana-pull}84831[#84831]
* Enables support for {es} clusters using action.destructive_requires_name=true {kibana-pull}88986[#88986]
Platform::
* Replaces legacy visualize chart library with @elastic/charts {kibana-pull}78154[#78154]
* Implements new palette service {kibana-pull}86876[#86876]
* Support `pit` and `search_after` in server `savedObjects.find` {kibana-pull}89915[#89915]
* Adds support for limited concurrency tasks {kibana-pull}90365[#90365]
Security::
* Adds audit events for spaces {kibana-pull}86343[#86343]
* Updates the user management page with a new design and functionality {kibana-pull}87133[#87133]
* Allow custom index privileges for role management {kibana-pull}88076[#88076]
Sharing::
* Anonymous authentication is now exposed in Dashboard, Discover and Visualize apps in the *Share* menu {kibana-pull}86965[#86965]
Uptime::
* Service overview: Introduce time-series comparison {kibana-pull}88665[#88665]
* Break down transaction table api removing the sparklines {kibana-pull}88946[#88946]
* Expand synthetic journey step thumbnail on hover {kibana-pull}89179[#89179]
* Waterfall filters {kibana-pull}89185[#89185]
* Adds waterfall flyout {kibana-pull}89449[#89449]
* Removes UI filters from UI {kibana-pull}89793[#89793]
* Adds nav search keywords for uptime and user experience app {kibana-pull}90616[#90616]
* Format `PingList` duration time as seconds when appropriate {kibana-pull}90703[#90703]

[float]
[[bug-v7.12.0]]
=== Bug fixes
Alerting::
* Edit alert should show and update all actions with deleted connectors {kibana-pull}86838[#86838]
* Gracefully handling unknown action type {kibana-pull}86910[#86910]
* Adds missing configuration options for the alerting related plugins to the kibana-docker. {kibana-pull}88297[#88297]
* Ensures we always select the correct index in UI tests {kibana-pull}88876[#88876]
* Fixes a bad UX for `xpack.actions.enabled` is set as false. UI should show the proper message instead of the endless spinner. {kibana-pull}89043[#89043]
* Skips Alert Instances that were instantiated but have no scheduled actions {kibana-pull}91179[#91179]
APM::
* Latency percentile labels and instances table support {kibana-pull}91758[#91758]
* [Kql Search Bar suggests values outside the selected time range {kibana-pull}91918[#91918]
Dashboard::
* Fixes Dashboard OnAppLeave {kibana-pull}86193[#86193]
* Fixes Visualize Link Redirecting to Dashboard Linked Visualization {kibana-pull}90243[#90243]
* Removes Multiple History Entries & Stay in Edit Mode on Save As {kibana-pull}92105[#92105]
Discover::
* Adds icon for nested fields in sidebar {kibana-pull}85147[#85147]
* Could not expand cell content in DiscoverGrid {kibana-pull}91289[#91289]
* Fixes icon for conflicting fields {kibana-pull}90641[#90641]
Elastic Security::
For the Elastic Security 7.12.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Lens and visualizations::
* Make sure filter object is persistable {kibana-pull}87828[#87828]
* Close popover on repeated button click {kibana-pull}87834[#87834]
* Make Lens intervals default value adapt to histogram:maxBars Advanced Setting changes {kibana-pull}89305[#89305]
* Fixes telemetry read only error {kibana-pull}91104[#91104]
* Fixes empty display name issue in XY chart {kibana-pull}91132[#91132]
* Pass used histogram interval to chart {kibana-pull}91370[#91370]
* Fixes unformatted timeseries functions {kibana-pull}92498[#92498]
* Fixes sorting undefined, null and NaN values {kibana-pull}92575[#92575]
* Adds better aria-labels for global search and field search in Lens {kibana-pull}89215[#89215]
* Vega Maps Referencing from kibana.yml {kibana-pull}88316[#88316]
* Fixes the timeseries legend, renders the metric, gauge charts for series with empty strings {kibana-pull}90760[#90760]
* Restores signal values on refresh {kibana-pull}90774[#90774]
* Stop inserting zeroes for null series {kibana-pull}90861[#90861]
Logs::
* Use useMlHref hook for ML links {kibana-pull}90935[#90935]
* Check for privileges with user management links {kibana-pull}91134[#91134]
Machine Learning::
* Fixes rare page crash when deleting anomaly detection job {kibana-pull}88622[#88622]
* Allow filtering by mlcategory in Anomaly Explorer Influencers list {kibana-pull}90282[#90282]
* Stops new line on enter key press for KQL query bars {kibana-pull}90960[#90960]
* Data Frame Analytics cloning: ensure classification hyperparameters retained when cloning job {kibana-pull}91507[#91507]
* Data Frame Analytics exploration page: filters improvements {kibana-pull}91748[#91748]
* Fixes event rate chart annotation position {kibana-pull}91899[#91899]
* Data Frame Analytics: Improved error handling for scatterplot matrix. {kibana-pull}91993[#91993]
* Fixes handling of built-in models  {kibana-pull}92154[#92154]
* Data Frame Analytics wizard: ensure required config options are loaded before enabling `Continue` {kibana-pull}92254[#92254]
* Anomaly Explorer:  ensure filtering works as expected when influencer value has trailing backslash {kibana-pull}92471[#92471]
Management::
* Use "untitled" filename for panels with no title in dashboard {kibana-pull}86333[#86333]
* Fixes saved object view path {kibana-pull}89057[#89057]
* Fixes a documentation link in Upgrade Assistant that directed users to information on Snapshot and Restore {kibana-pull}89363[#89363]
* Can't create single character index without wildcard {kibana-pull}90919[#90919]
* Fixes a small form validation bug that required an input for the set processor value field and gsub processor replacement field {kibana-pull}91146[#91146]
* The rollup job form now has an autofocus on the input field after the switch between cron expression and frequency selection {kibana-pull}86324[#86324]
Maps::
* Geo containment latency and concurrent containment fix {kibana-pull}86980[#86980]
* Fixes users without access to Maps should not have the option to create them {kibana-pull}88830[#88830]
* Fixes reporting jobs fail when Elastic Maps Service (EMS) is unavailable {kibana-pull}90834[#90834]
* Fixes geo shape agg telemetry not collecting due to missing index pattern IDs {kibana-pull}90886[#90886]
* Fixes issue preventing WebGL warning message from appearing {kibana-pull}91069[#91069]
Metrics::
* Completely remove GraphQL and Apollo {kibana-pull}89036[#89036]
* Fixes history drawer when navigation is docked {kibana-pull}89630[#89630]
* Fixes alert preview accuracy with new Notify settings {kibana-pull}89939[#89939]
* Fixes saving/loading saved views from URL {kibana-pull}90216[#90216]
* Fixes node details overlay title with long host name {kibana-pull}90825[#90825]
* Fixes alerts repeatedly firing "recovered" actions {kibana-pull}91038[#91038]
Monitoring::
* Fetch status once and change fetchStatus to support an array of clusters {kibana-pull}91749[#91749]
* Adds missing fields for security telemetry {kibana-pull}91920[#91920]
Platform::
* Cancel expired tasks as part of the available workers check {kibana-pull}88483[#88483]
* Reject invalid Timeout values in Task Type Definitions {kibana-pull}88602[#88602]
* Increment task `attempts` when they fail during markTaskAsRunning {kibana-pull}88669[#88669]
* Fixes lens doesn't cancel pending search requests when navigating away or re-running a search {kibana-pull}91486[#91486]
Reporting::
* Deserialize query string options for serverside ES Query {kibana-pull}90050[#90050]
Security::
* Removes the ability to generate an ephemeral encryption key in production {kibana-pull}81511[#81511]
* Fixes ECS audit logging config settings for docker environments {kibana-pull}92497[#92497]
Sharing::
* Resilient saved object migration algorithm {kibana-pull}78413[#78413]

