[[release-notes]]
= {kib} Release Notes
++++
<titleabbrev>Release Notes</titleabbrev>
++++

[partintro]
--
// Use these for links to issue and pulls. Note issues and pulls redirect one to
// each other on Github, so don't worry too much on using the right prefix.
:issue: https://github.com/elastic/kibana/issues/
:pull: https://github.com/elastic/kibana/pull/

This section summarizes the changes in each release.

* <<release-notes-7.0.0-alpha1>>
* <<release-notes-7.0.0-alpha2>>

--

[[release-notes-7.0.0]]
== {kib} 7.0.0

//[float]
//[[breaking-7.0.0]]
//=== Breaking Changes

//[float]
//=== Breaking Java Changes

//[float]
//=== Deprecations

//[float]
//=== New Features

//[float]
//=== Enhancements

//[float]
//=== Bug Fixes

//[float]
//=== Regressions

//[float]
//=== Known Issues


[[release-notes-7.0.0-alpha2]]
== {kib} 7.0.0-alpha2

coming[7.0.0-alpha2]

[float]
[[breaking-7.0.0-alpha2]]
=== Breaking changes

For more details about breaking changes in this release, see 
<<breaking-changes-7.0, Breaking changes in 7.0>>.

[float]
[[enhancement-7.0.0-alpha2]]
=== Enhancements
Canvas::
* Implements a clipboard and stores the copied elements in `localStorage` {pull}25890[#25890]
* Adds the ability to reuse assets without editing an element's expression {pull}25764[#25764]
* Adds the `clear` function {pull}26397[#26397]
* Adds a template tab to the workpad manager where users can find workpad templates, 
demos, and tutorials to help them get started {pull}23966[#23966]
Design::
* Updates logos for marketing {pull}25489[#25489]
* Updates to EUI 5.3.0 {pull}26485[#26485]
* Adds Kibana 7.0 breadcrumbs to home screen {pull}26605[#26605]
* Adds EUI 5.6.0 {pull}26839[#26839]
* Moves elastic/eui typings to single file {pull}23950[#23950]
Index Lifecycle Management::
* Implements a CRUD UI for index lifecycle management policies {pull}25553[#25553]
Kibana App::
* Maps inspector requests by id so single requests can be reset at a time {pull}26770[#26770]
* Moves Canvas interpreter to OSS in Kibana core {pull}25711[#25711]
Management::
* Adds `Request timestamp` to request inspector stats {pull}25667[#25667]
* Adds "Reload indices" button to Index Management {pull}27033[#27033]
Machine Learning::
* Adds the configuration files for two new auditbeat data recognizer modules for 
detecting unusual processes on hosts and Docker containers {pull}25716[#25716]
* Adds support for saved searches created using Kuery to the job wizards {pull}26094[#26094]
* Allows user to enter their own query in the Discover page; stops passing the query 
from the job datafeed config in custom URLs {pull}26957[#26957]
* Rewrites Calendar to React/EUI {pull}26741[#26741]
Platform::
* Adds `rest_total_hits_as_int` to all requests in platform code that eventually 
look up `hits.total` {pull}26432[#26432]
* Adds `dist` flag to the configuration context {pull}26545[#26545]
* Prepares `@kbn/datemath` to be republished as `@elastic/datemath` {pull}26559[#26559]
* Wraps `remote` methods in `browser` service {pull}26394[#26394]
Querying & Filtering::
* Moves the `buildESQuery` module (including filters and Kuery) into a separate package {pull}23345[#23345]
* Adds comment explaining why `getComputedFields` adds a `docvalue` to `docvalue_fields` 
for each date field in an index pattern. {pull}25725[#25725]
* Moves filtering functions out of `vis.API.events` {pull}25280[#25280]
Reporting::
* Adds browser type to the reporting side panel {pull}26307[#26307]
* Adds better logging for `waitForSelector` failure {pull}25762[#25762]
* Enhances error messaging and handling {pull}26299[#26299]
* Adds "Info" button in the Reporting listing {pull}25421[#25421]
Rollups::
* Adds support for rolling up metrics of date fields {pull}26450[#26450]
Security::
* Updates the GET `/api/security/role` endpoint to return the list of roles sorted 
by name, rather than creation date {pull}26491[#26491]
* Updates the Account Settings screen to show the change password form only when
a password change is possible for the authentication realm {pull}26779[#26779]
Visualizations::
* Removes experimental flag from Visual Builder {pull}25634[#25634]
* Implements new visualization type selection {pull}23833[#23833]
* Removes `lab` stage for visualizations, making `experimental` the only non-production 
stage available {pull}25702[#25702]

[float]
[[bug-7.0.0-alpha2]]
=== Bug fixes
Canvas::
* Fixes offset mouse capture after scrolling {pull}27096[#27096]
* Fixes query bug in esdocs {pull}27157[#27157]
* Fixes page preview size issue {pull}26795[#26795]
* Fixes loading component {pull}25819[#25819]
* Updates links to documentation in Canvas {pull}26201[#26201]
* Makes error messages consistent between the `esdocs` and `essql` functions {pull}26399[#26399]
* Fixes visual bug when opening the workpad loader {pull}26647[#26647]
* Fixes page thumbnail sizes {pull}26573[#26573]
* Switches to a hash history manager that supports `pushState` and `replaceState` 
and fixes `urlparam` function {pull}25828[#25828]
* Adds tags to Canvas functional suite {pull}26046[#26046]
* Fixes reporting import and config checking {pull}25829[#25829]
* Adds support for columns with dots {pull}26659[#26659]
* Removes `es_indices` web service and uses the `savedObjectsClient` to get index-patterns {pull}25630[#25630]
* Reduces HTTP POST generation on selections and drags {pull}26391[#26391]
* Decreases size of tray toggle {pull}25470[#25470]
* Adds workpad-level CSS {pull}24143[#24143]
* Makes selection border 1px {pull}26739[#26739]
* Updates TinyMath reference links {pull}27085[#27085]
Geo::
* Resolves URL dynamically when requesting EMS data {pull}25685[#25685]
* Fixes EMS hotlink {pull}26868[#26868]
Infrastructure UI:: 
* Fixes potential color bugs {pull}26292[#26292]
* Fixes auto refresh button on node detail page {pull}26426[#26426]
* Changes the time range from the last hour to the last 5 minutes for the Waffle Map {pull}26278[#26278]
* Passes flag in request to force BWC hit count {pull}26517[#26517]
* Replaces redux source slice with constate container {pull}26121[#26121]
* Changes node detail link to set time range to 1 hour {pull}26977[#26977]
* Stops showing sidenav while loading. {pull}27119[#27119]
* Fixes styling after breaking EUI changes {pull}27021[#27021]
* Fixes graphql type generation after package upgrades {pull}26991[#26991]
* Removes usage of `ts-optchain` in the browser {pull}27148[#27148]
Kibana App:: 
* Fixes auto refresh after page reload {pull}26088[#26088]
* Fixes flash of unstyled dashboard content {pull}25559[#25559]
* Adds `href` option in addition to `onClick` for navigational links {pull}25233[#25233]
* Fixes support for React 16.4+ by only resetting state if adaptors are updated {pull}26138[#26138]
* Shows pagination on saved searches in dashboard read mode {pull}26224[#26224]
* Fixes scrolling list on Firefox {pull}26246[#26246]
* Guards against empty and undefined index pattern arrays passed to QueryBar {pull}24607[#24607]
* Removes unused indexPattern from vega/tsvb/timelion request handler {pull}26007[#26007]
* Passes global filters from editor down to visualize  {pull}26009[#26009]
* Stops using schemas in aggconfigs to output DSL {pull}26010[#26010]
* Fixes check for showing 'show partial buckets' option {pull}25520[#25520]
* Fixes `kbn-interpreter` package to not import from UI {pull}26161[#26161]
* Fixes OSS dynamic plugin loading by reverting to Canvas way of loading plugins {pull}26463[#26463]
* Fixes interpreter socket error {pull}26870[#26870]
* Uses `retry` to avoid stale element references in data table {pull}25973[#25973]
* Fixes other bucket option to correctly apply without having to change other settings {pull}26874[#26874]
Management::
* Fixes index pattern wizard when there are remote clusters but no local indices  {pull}24339[#24339]
* Adds `en` as a valid numeral locale setting {pull}25948[#25948]
* Adds `rest_total_hits_as_int` into Kibana App {pull}26404[#26404]
* Uses new `_graph` endpoints {pull}26956[#26956]
* Fixes fatal IE 11 error from undefined TextEncoder {pull}26966[#26966]
* Adjusts spacing of Management navigation items {pull}25666[#25666]
* Updates "Disenroll" text to be consistent with menu option "Unenroll" {pull}26816[#26816]
* Fixes validation issues with edit policy {pull}27045[#27045]
* Fixes broken breadcrumb link for index management {pull}27164[#27164]
* Fixes for index lifecycle management UI {pull}27153[#27153]
Machine Learning::
* Allows user to add/edit/delete annotations in the Single Series Viewer {pull}26034[#26034]
* Does not pass datafeed query to Discover in custom URL {pull}26957[#26957]
* Fixes word break in Anomalies and Jobs tables {pull}26978[#26978]
* Fixes recognizer job wizard to use dedicated index setting {pull}25706[#25706]
* Ensures jobs from saved searches are cloned in advanced wizard {pull}26002[#26002]
* Aggregates Anomalies table data using configured Kibana timezone {pull}26192[#26192]
* Fixes alignment of filter icons in the Anomalies table {pull}26253[#26253]
* Fixes population chart marker positions {pull}26716[#26716]
Monitoring::
* Uses proper Kibana index for KQL telemetry {pull}26479[#26479]
* Fixes error handling for local stats collection/permissions {pull}26560[#26560]
* Removes initial delay to check and send Telemetry data {pull}26575[#26575]
* Pulls local Kibana usage stats {pull}26496[#26496]
* Adds a new plugin for Uptime Monitoring {pull}25480[#25480]
* Adds server-side user authorization and license checks {pull}26070[#26070]
* Fixes issue with multiple execution in Console {pull}26933[#26933]
* Converts the Elasticsearch monitoring UIs to using EUI tables and page layout {pull}26217[#26217]
Platform & Operations::
* Decreases start limit and interval {pull}25474[#25474]
* Fixes logging.useUTC deprecation unset {pull}26053[#26053]
* Adds `--download` flag to snapshot command to warm the cache {pull}25830[#25830]
* Implements `--prefer-offline` flag {pull}25840[#25840]
* Fixes use disallow license header rule {pull}26309[#26309]
* Fixes watcher routes broken by Hapi upgrade {pull}26713[#26713]
* Fixes non-conforming licenses on devDependencies and adds the ability to whitelist devOnly licenses {pull}23859[#23859]
* Watches optimizer cache invalidation  {pull}24172[#24172]
* Adds `normalizePath` in order to fix watch optimizer when running on Windows {pull}26486[#26486]
* Creates vendor dll for the client modules {pull}22618[#22618]
* Upgrades to NodeJS 10 {pull}25157[#25157]
* Throws error if reindex task fails {pull}26062[#26062]
* Bumps Node to 8.14.0 {pull}26313[#26313]
* Improves plugin version mismatch error message {pull}25774[#25774]
* Provides protection against missing shards {pull}26303[#26303]
* Improves build/packaging {pull}26096[#26096]
* Allows SIGHUP to recreate log file handler {pull}26675[#26675]
* Swaps `jstimezonedetect` with `moment.tz.guess` {pull}21800[#21800]
* Upgrades resize-observer-polyfill version {pull}26990[#26990]
* Fixes saved objects client `_processBatchQueue` function to handle errors {pull}26763[#26763]
* Changes kbn pm webpack config to generate dist files in mode=none {pull}26847[#26847]
* Hides logs from deleteAll on task: clean client modules into dll {pull}26884[#26884]
* Translates URL {pull}26804[#26804]
* Upgrades `resize-observer-polyfill` version {pull}26990[#26990]
Querying & Filtering::
* Changes Timefilter to return strings instead of moments {pull}25625[#25625]
* Uses Canvas pipeline to fetch data inside Visualize {pull}25996[#25996]
Reporting::
* Deletes `sortOrder` once items have been sorted and does not pass to `EuiContextMenuItem` 
in the share context menu {pull}26890[#26890]
* Fixes a regression bug in detection of Error and Warning toast notifications {pull}25482[#25482]
Rollups:: 
* Shows loading state in Rollup Job detail panel. {pull}25752[#25752]
* Specifies Rollup Jobs breadcrumbs in header. {pull}26590[#26590]
* Requires histogram interval in Rollup Job wizard to be a whole number. {pull}26596[#26596]
* Fixes rollup indices request failures so that the create index pattern button isn't blocked {pull}26988[#26988]
Security::
* Fixes anonymous access to status page {pull}24706[#24706]
* Adds `read_ccr` and `manage_ccr` cluster privileges {pull}25605[#25605]
* Fixes redirect after logging in {pull}25546[#25546]
* Makes short URLs space-aware {pull}26181[#26181]
* Adds `manage_follow_index` index privilege for cross-cluster replication to the
role management screen {pull}25720[#25720]
* Allows the public spaces API to work with a gold license {pull}26270[#26270]
* Fixes documentation links for ES role privileges {pull}26466[#26466]
* Initializes authorization mode for reporting jobs {pull}26762[#26762]
* Moves the server-side `SavedObjectClient` types from the `spaces` plugin to the 
same location as the corresponding JavaScript source files {pull}26448[#26448]
* Respects the `basePath` for the link to the user profile in the k7 header {pull}26417[#26417]
* Fixes `prettier` throw rule error  {pull}26071[#26071]
* Makes space selector a `button` {pull}26889[#26889]
* Fixes authentication logic to fail out of auth flow on first provider failure {pull}26648[#26648]
* Fixes issues with the `url.search` being null in Node 10 {pull}26992[#26992]
Visualizations::
* Fixes vertical scroll on long legends {pull}23806[#23806]
* Fixes filter function on pie chart segment {pull}26321[#26321]
* Rewrites URL when closing vis type selection modal {pull}26327[#26327]
* Changes unbind calls from `.on` to `.off` {pull}24575[#24575]
* Makes tooltips visible in stacked line chart {pull}26881[#26881]
* Fixes date field in controls visualization by generating labels with the field 
formatter {pull}25654[#25654]
* Preserves custom axis titles when loading a saved visualization {pull}24176[#24176]
* Replaces LESS files with Sass in `ui/public/vis`, `visLib`, and `visualize` {pull}25333[#25333]
* Replaces LESS files with Sass for the visualization types in `core_plugin/metrics` {pull}24250[#24250]
* Moves `timeout` to `_msearch` body to fix time series visual builder requests {pull}26510[#26510]
* Resolves issue with the `_msearch` timeouts being specified incorrectly, which 
was causing them to be ignored {pull}26446[#26446]
* Adds description for all visualization types {pull}26243[#26243]






[[release-notes-7.0.0-alpha1]]
== {kib} 7.0.0-alpha1

[float]
[[breaking-7.0.0]]
=== Breaking changes

For more details about breaking changes in this release, see 
<<breaking-changes-7.0, Breaking changes in 7.0>>.

Discover::
* Does not apply `query:queryString:options` to `query_string` filters {pull}15640[#15640]
* Removes `default_field` from `query:queryString:options` {pull}18966[#18966]

Monitoring::
* Removes `node_resolver` setting {pull}21181[#21181]

Operations::
* Removes tribe node support {pull}16397[#16397]
* Creates separate startup scripts for development and production {pull}13806[#13806]
* Sets default port based on protocol  {pull}21564[#21564]
* Removes deprecated `/shorten` API {pull}21861[#21861]

[float]
[[deprecation-7.0.0]]
=== Deprecations

Geo::
* Fixes legacy tilemap loading {pull}22095[#22095]

[float]
[[K7-design-7.0.0]]
=== K7 UI Design

{kib} 7.0.0-alpha1 includes a new design for {kib} called K7. In this early stage, 
K7 is still a little rough around the edges. If you'd like to switch back to the 
existing K6 design, go to *Management > Advanced Settings* and turn 
off the *k7design* setting. The option to switch to the old design 
will be removed before 7.0.0 GA.

[float]
[[enhancement-7.0.0]]
=== Enhancements

Machine Learning::
* Updates job type and APM module icon to new designs {pull}25380[#25380]
* Allows model plot enablement via checkbox in  MultiMetric/Population Job creation {pull}24914[#24914]
* Adds support for the rare detector for charts in Anomaly Explorer and Singe Metric viewer {pull}21524[#21524]

Reporting::
* Adds png output to reports {pull}24759[#24759]
* Sorts ascending on sort order first then ascending on name. Any menu item 
without a sort order gets set to zero. {pull}25058[#25058]

Visualizations::
* Adds a console.error for visualize errors {pull}24581[#24581]

[float]
[[bug-7.0.0]]
=== Bug fixes

APM::
* Overrides EUI chart default styles for gridlines {pull}21723[#21723]
* Adds section titles to span detail modal {pull}20717[#20717]

Canvas::
* Fixes duplicate `Value` options in math select value {pull}25556[#25556]
* Gets correct plugins path {pull}25448[#25448]
* Quotes the index pattern in SQL input {pull}25488[#25488]
* Decreases the size of tray toggle {pull}25470[#25470]
* Improves the plugin pre-build {pull}25267[#25267]

Dashboard::
* Removes `dashboardContext` function and makes Timelion, Vega, and Time Series 
Visual Builder use `buildEsQuery` {pull}23227[#23227]

Design::
* Converts Security UI from LESS to Sass {pull}25079[#25079]
* Adds boilerplate Sass for Kibana core {pull}21185[#21185]

Discover::
* Adds debug code to flaky field_data test {pull}15535[#15535]
* Gets even more debug info for flaky field_data test {pull}17627[#17627]

Geo::
* Fixes feature/align map config settings {pull}19450[#19450]

Kibana App::

* Adds warning to the `documentation_links` file about link validation gotcha {pull}24786[#24786]
* Adds workaround for `getDerivedStateFromProps` change in react 16.4 {pull}25142[#25142]

Kibana Home &amp; Add Data::
* Fixes "Set up index patterns" link on home page {pull}16128[#16128]

Machine Learning::
* Shows useful error on invalid query in JobList search bar {pull}25153[#25153]
* Adds user privilege check to Jobs List group selector control {pull}25225[#25225]
* Fixes file data viz file size check and formats as bytes {pull}25295[#25295]
* Fixes the layout of the cards in the Data Visualizer on IE {pull}25383[#25383]
* Adds better error reporting for reading and importing data {pull}24269[#24269]
* Displays an ordinal y axis for low cardinality rare charts {pull}24852[#24852]
* Fixes typo in job validation message {pull}25130[#25130]
* Removes deprecated `angularjs` based jobs list and related code {pull}25216[#25216]

Management::
* Adds boilerplate for remote clusters management app {pull}25369[#25369]
* Adds `ignore_failure` to ingest common auto complete in console {pull}24915[#24915]
* Removes support for expression-based scripted fields {pull}14310[#14310]
* Adds WatchErrors to capture invalid watches {pull}23887[#23887]
* Rewords the translation id for error with missing property in Watcher {pull}24753[#24753]

Monitoring::
* Renames Monitoring `FormattedMessage` to `FormattedAlert` {pull}24197[#24197]
* Uses the cluster name from metadata if it exists {pull}24495[#24495]

Operations::
* Removes node fallback from kibana-keystore {pull}15066[#15066]
* Adds debug script to set inspect flags {pull}15967[#15967]
* Uses snake case for scripts/kibana-keystore.js and scripts/kibana-plugin.js {pull}15331[#15331]
* Updates license info in package.json {pull}20353[#20353]
* Fixes error log formatting {pull}24788[#24788]
* Matches chalk dependency version on Kibana with the one used on X-Pack {pull}20621[#20621]
* Fixes non-conforming licenses on devDependencies and adds the ability to whitelist devOnly licenses {pull}23859[#23859]
* Adds jsxa11y into eslint rules {pull}23932[#23932]
* Reverts Bump react-grid-layout to 0.16.0 {pull}14912[#14912]
* Reverts breaking change for Status API {pull}21927[#21927]
* Converts `utils/collection` to TypeScript {pull}23992[#23992]
* Removes usage of update_all_types {pull}16406[#16406]
* Improves the `yarn kbn bootstrap` speed by using yarn workspaces for packages inside `packages/*` and `x-pack` {pull}24095[#24095]
* Runs jenkins:unit task with dev flag in order to run license check {pull}19832[#19832]
* Does not break on startup in debug mode {pull}19219[#19219]


Platform::
* Transforms plugin deprecations before checking for unused settings {pull}21294[#21294]
* Expands list of restricted globals in `eslint-config-kibana` {pull}15798[#15798]
* Makes logs easier to read on Windows with chalk colors {pull}15557[#15557]

Querying &amp; Filtering::
* Fixes wildcard queries against the default field {pull}24778[#24778]

Reporting::
* Returns promise in Reporting jobs API {pull}24769[#24769]

Security::
* Implements the K7 login screen {pull}23512[#23512]

Sharing::

* Fixes issue with debounce function running after component was unmounted {pull}15045[#15045]

Visualizations::
* Defaults the scroll wheel zoom to false on Vega maps {pull}21169[#21169]
* Fixes problem within the input_vis_control plugin that prevents it from updating correctly 
if the field is switched, and then switched back to the previous field {pull}25164[#25164]
* Uses `vega-nocanvas` instead of vega lib {pull}16137[#16137]
* Migrates visualization from Angular to React {pull}16425[#16425]
* Fixes maps for reporting (#15272) {pull}15358[#15358]
* Stops creation of nested search source per postflightrequest {pull}20373[#20373]
* Moves inspector code from Vis to embeddable visualize handler {pull}24112[#24112]
* Removes inspector from Vis {pull}24112[#24112]




