[[release-notes]]
= Release notes

[partintro]
--
// Use these for links to issue and pulls. Note issues and pulls redirect one to
// each other on Github, so don't worry too much on using the right prefix.
:issue: https://github.com/elastic/kibana/issues/
:pull: https://github.com/elastic/kibana/pull/

Review important information about the {kib} 7.12.x releases.

* <<release-notes-7.12.0>>

--

[[release-notes-7.12.0]]
== {kib} 7.12.0

coming::[7.12.0]

For information about the {kib} 7.12.0 release, review the following information.

[float]
[[breaking-changes-7.12.0]]
=== Breaking changes

Breaking changes can prevent your application from optimal operation and performance.
Before you upgrade to 7.12.0, review the breaking changes, then mitigate the impact to your application.

// tag::notable-breaking-changes[]

[discrete]
[[breaking-89632]]
.Removes geo threshold alert type
[%collapsible]
====
*Details* +
Geo containment alerts and the Geo threshold alert type have similar functionality, so the Geo threshold alert type has been removed. For more information, refer to {kibana-pull}89632[#89632].

*Impact* +
Use Geo containment alerts.
====

[discrete]
[[breaking-so-upgrade-migrations]]
.New saved object upgrade migrations algorithm
[%collapsible]
====
*Details* +
When you upgrade to 7.12.0, {kib} uses a new algorithm to migrate saved objects to reduce the downtime caused by temporary issues, such as network errors or temporarily overloaded {es} clusters. 
With the new algorithm, {kib} now retries the failed migrations without user intervention, which allows the migration to continue after the issues are resolved. 
For more information, refer to <<upgrade-migrations, saved object upgrade migrations>>.

*Impact* +
Before you upgrade to 7.12.0, review the documentation for <<upgrade-migrations-rolling-back, rolling back to a previous version of {kib}>>.
====

[discrete]
[[breaking-kibana-support-for-ccs]]
.{kib} support for CCS
[%collapsible]
====
*Details* +
In 7.12.0, {kib} introduces a major incompatibility with cross-cluster search. When one or more remote {es} clusters use a version prior to 7.12.0, *Discover*, *Maps*, *Canvas*, and *Logs* are 
unable to display the cluster data. For information about the cross-cluster search limitations in {kib}, refer to {kibana-issue}94965[#94965].

*Impact* +
To display the cluster data in *Discover*, load documents directly from `_source`.

. Open the main menu, then click *Stack Management > Advanced Settings*.

. Go to `discover:searchFieldsFromSource`, then select *On*.
====

// end::notable-breaking-changes[]

[float]
[[deprecations-7.12.0]]
=== Deprecations

The following functionality is deprecated in 7.12.0, and will be removed in 8.0.0.
Deprecated functionality does not have an immediate impact on your application, but we strongly recommend
you make the necessary updates after you upgrade to 7.12.0.

[discrete]
[[deprecation-86474]]
.Deprecates `services.callCluster` in alerts and actions executors
[%collapsible]
====
*Details* +
Deprecates `services.callCluster` in the alert and action type executors. For more information, refer to {kibana-pull}86474[#86474].

*Impact* +
Use `services.scopedClusterClient`.
====
      
[discrete]
[[deprecation-87114]]
.Deprecates configuring [kib] with a `server.host` value of `0`
[%collapsible]
====
*Details* +
In the new version of joi, `0` is an invalid hostname. When upgraded, the extra validate function can be removed. For more information, refer to {kibana-pull}87114[#87114].

*Impact* +
To bind to all interfaces, use `0.0.0.0`.
====
      
[discrete]
[[deprecation-89296]]
.Deprecates the use of `elasticsearch.logQueries`
[%collapsible]
====
*Details* +
When `logging.verbose: true` or `logging.root.level: 'debug'`, {es} query logs are now always shown. 
In 7.11.0 and earlier, {es} query logs were not included in verbose logging unless `elasticsearch.logQueries` was configured. 
For more information, refer to {kibana-pull}89296[#89296].

*Impact* +
To use verbose logging without {es} query logs, configure the query logs to `off` in kibana.yml:
[source,js]
----
logging:
  loggers:
     - context: elasticsearch.query
       level: off
----
====
      
[float]
[[features-7.12.0]]
=== Features
{kib} 7.12.0 adds the following new and notable features.

Alerting::
* Search alert {kibana-pull}88528[#88528]
APM::
* Correlations Beta {kibana-pull}89952[#89952]
Canvas::
* Support IP data type {kibana-pull}85087[#85087]
Dashboard::
* Rename Visualize to Visualize Library {kibana-pull}91015[#91015]
* Copy Panel to Dashboard {kibana-pull}90856[#90856]
* Adds switch for color syncing between charts on dashboards {kibana-pull}86180[#86180]
Discover::
* Support mapping defined runtime fields in Discover {kibana-pull}83891[#83891]
Elastic Security::
For the Elastic Security 7.12.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Lens & Visualizations::
* Support histogram mapping type for all numeric functions in *Lens* {kibana-pull}90357[#90357]
* Adds percentile to *Lens* {kibana-pull}86490[#86490]
* Adds counter rate, cumulative sum, differences and moving average to *Lens* {kibana-pull}84384[#84384]
Logs::
* Show anomalies across both the log rate and categorization ML jobs in a swimlane visualization {kibana-pull}89589[#89589]
Machine Learning::
* Adds embedded map to geo_point fields for Data Visualizer {kibana-pull}88880[#88880]
* Anomaly Detection: add anomalies map to explorer for jobs with 'lat_long' function {kibana-pull}88416[#88416]
* Data Frame Analytics: Adds scatterplot matrix to regression/classification results pages {kibana-pull}88353[#88353]
* Redesign file-based Data Visualizer {kibana-pull}87598[#87598]
Management::
* Enable Search Sessions {kibana-pull}91097[#91097]
* Policy phases redesign {kibana-pull}88671[#88671]
* Replace search session constants with kibana.yml configs {kibana-pull}88023[#88023]
* Adds support for URI parts processor {kibana-pull}86163[#86163]
* Management UI {kibana-pull}81707[#81707]
Maps::
* GA Geo containment alerts. Remove Geo containment alert experimental config settings and refs {kibana-pull}90301[#90301]
Platform::
* Implement custom global header banner {kibana-pull}87438[#87438]

For more information about the features introduced in 7.12.0, refer to <<whats-new,What's new in 7.12>>.

[[enhancements-and-bug-fixes-v7.12.0]]
=== Enhancements and bug fixes

For detailed information about the 7.12.0 release, review the enhancements and bug fixes.

[float]
[[enhancement-v7.12.0]]
=== Enhancements
Alerting::
* Adds support for custom alert ids {kibana-pull}89814[#89814]
* Allow user to select existing connector of same type when fixing broken connector {kibana-pull}89062[#89062]
* Search alert {kibana-pull}88528[#88528]
* Adds a "Refresh" button to the alerts list and alert details views {kibana-pull}87016[#87016]
* Alert and Connector flyouts Save and Save&Test buttons should be active by default {kibana-pull}86708[#86708]
APM::
* Correlations Beta {kibana-pull}89952[#89952]
* Round start and end values {kibana-pull}89030[#89030]
* Instances latency distribution chart {kibana-pull}88546[#88546]
* Showing confirmation modal on Alert Add/Edit when flyout closed without saving and changes made {kibana-pull}86370[#86370]
Canvas::
* Support IP data type {kibana-pull}85087[#85087]
Dashboard::
* Dashboard Save As New by Default {kibana-pull}91761[#91761]
* Stay in Edit Mode After Dashboard Quicksave {kibana-pull}91729[#91729]
* Combine Discard & Cancel {kibana-pull}91267[#91267]
* Unsaved Changes Badge {kibana-pull}91073[#91073]
* Rename Visualize to Visualize Library {kibana-pull}91015[#91015]
* Copy Panel to Dashboard {kibana-pull}90856[#90856]
* Improves error messages when in Dashboard {kibana-pull}90668[#90668]
* Adds Save as button to top menu {kibana-pull}90320[#90320]
* Enable right click on visualizations and dashboards listings {kibana-pull}88936[#88936]
* Url template editor {kibana-pull}88577[#88577]
* Enable "by value embeddables" (dashboard.allowByValueEmbeddables) by default {kibana-pull}88390[#88390]
* Align Lens & Visualize Breadcrumbs {kibana-pull}86941[#86941]
* Remove Panels from URL {kibana-pull}86939[#86939]
* Align Lens & Visualize Top nav Buttons & Behaviour {kibana-pull}86922[#86922]
* URL encoding for URL drilldown {kibana-pull}86902[#86902]
* Adds switch for color syncing between charts on dashboards {kibana-pull}86180[#86180]
Discover::
* Replace EuiCodeBlock with Monaco editor in Discover {kibana-pull}90781[#90781]
* Adds support for unmapped fields using the fields API {kibana-pull}89074[#89074]
* Adds "Hide chart" / "Show chart" persistence {kibana-pull}88603[#88603]
* Grouping multifields in a doc table {kibana-pull}88560[#88560]
* Deangularize navbar in context app {kibana-pull}86353[#86353]
* Change default sort handling {kibana-pull}85561[#85561]
* Support mapping defined runtime fields in Discover {kibana-pull}83891[#83891]
Elastic Security::
For the Elastic Security 7.12.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Fleet::
* Install Lens assets from packages if present {kibana-pull}88189[#88189]
Kibana Home & Add Data::
* Fixes values of `products.min_price` field in Kibana sample ecommerce data set {kibana-pull}90428[#90428]
Lens & Visualizations::
* Support min and max with histogram data types in *TSVB* {kibana-pull}91581[#91581]
* Adds a new "Series Agg" to count the number of series in *TSVB* {kibana-pull}91225[#91225]
* Communicate the index pattern to the dashboard in *Timelion* {kibana-pull}90623[#90623]
* Support histogram mapping type for all numeric functions in *Lens* {kibana-pull}90357[#90357]
* Table column text alignment in *Lens* {kibana-pull}89300[#89300]
* Hide column in table in *Lens* {kibana-pull}88680[#88680]
* Use mapbox instead of leaflet in *Vega* {kibana-pull}88605[#88605]
* Use first decimal when required for data summaries in *Lens* {kibana-pull}88463[#88463]
* User should be able to set a specific tilemap service using the mapStyle property in *Vega* {kibana-pull}88440[#88440]
* Use datagrid with resizable columns for datatable in *Lens* {kibana-pull}88069[#88069]
* Adds specific IP and Range/Interval sorting to datatable in *Lens* {kibana-pull}87006[#87006]
* Adds more in-editor Advanced documentation in *Lens* {kibana-pull}86821[#86821]
* Adds percentile to *Lens* {kibana-pull}86490[#86490]
* Allow custom label for fields via index pattern field management in *TSVB* {kibana-pull}84612[#84612]
* Adds counter rate, cumulative sum, differences and moving average to *Lens* {kibana-pull}84384[#84384]
Logs::
* Show anomalies across both the log rate and categorization ML jobs in a swimlane visualization {kibana-pull}89589[#89589]
* Display category in anomalies table {kibana-pull}88677[#88677]
* Adds sorting capabilities to categories page {kibana-pull}88051[#88051]
Machine Learning::
* Anomaly Detection: when no anomalies present for time range show no results message {kibana-pull}91151[#91151]
* Adds Create Data Frame Analytics card to Data Visualizer {kibana-pull}91011[#91011]
* Data Frame Analytics creation wizard: adds support for extended hyper-parameters {kibana-pull}90843[#90843]
* Data Frame Analytics: Support early stopping data frame analytics job parameter {kibana-pull}90695[#90695]
* Data Frame Analytics: ROC Curve Chart {kibana-pull}89991[#89991]
* Data Frame Analytics creation: improve existing job check {kibana-pull}89627[#89627]
* Adds Lens and Discover integration to index based Data Visualizer {kibana-pull}89471[#89471]
* Anomaly Detection alert type {kibana-pull}89286[#89286]
* Adds ML deep links to navigational search {kibana-pull}88958[#88958]
* Adds embedded map to geo_point fields for Data Visualizer {kibana-pull}88880[#88880]
* Improving model snapshot revert UI experience {kibana-pull}88588[#88588]
* Anomaly Detection: add anomalies map to explorer for jobs with 'lat_long' function {kibana-pull}88416[#88416]
* Data Frame Analytics: Adds scatterplot matrix to regression/classification results pages {kibana-pull}88353[#88353]
* Redesign file-based Data Visualizer {kibana-pull}87598[#87598]
* Adds documentation links in the help menu for machine learning {kibana-pull}85366[#85366]
Management::
* Transforms: Adds missing bucket checkbox to group by popover form {kibana-pull}91650[#91650]
* Transforms: Adds retention policy options to transform UI {kibana-pull}91162[#91162]
* Enable Search Sessions {kibana-pull}91097[#91097]
* Adds better UI support for runtime fields Transforms {kibana-pull}90363[#90363]
* Adds folding in kbn-monaco and update some viewers {kibana-pull}90152[#90152]
* Fix retrieval of unmapped fields; Add field filters {kibana-pull}89837[#89837]
* Policy phases redesign {kibana-pull}88671[#88671]
* Adds runtime fields to index patterns and searchsource {kibana-pull}88542[#88542]
* Timeline component {kibana-pull}88024[#88024]
* Replace search session constants with kibana.yml configs {kibana-pull}88023[#88023]
* Managed data streams renamed to Fleet-managed and table layout improvement {kibana-pull}86285[#86285]
* Adds support for URI parts processor {kibana-pull}86163[#86163]
* Management UI {kibana-pull}81707[#81707]
Maps::
* GA Geo containment alerts. Remove Geo containment alert experimental config settings and refs {kibana-pull}90301[#90301]
* Allow saving maps to dashboards {kibana-pull}88759[#88759]
* Use chart pallete registry to support sync colors in dashboard {kibana-pull}88099[#88099]
* Scale control {kibana-pull}88031[#88031]
* Support geometry-collection {kibana-pull}87867[#87867]
* Set containment alert recovery action group to 'No longer contained' {kibana-pull}87182[#87182]
* Show map saved objects in visualize listing page {kibana-pull}87165[#87165]
* Term join limit {kibana-pull}86491[#86491]
* Labels for polygons and lines {kibana-pull}86191[#86191]
* Always show solution layers {kibana-pull}86053[#86053]
Metrics::
* Adds ability for user to set anomaly threshold {kibana-pull}90313[#90313]
* Adds warning severity to Metric Alerts {kibana-pull}90070[#90070]
* Adds helper text to of expressions when creating Threshold Alerts {kibana-pull}89750[#89750]
* Adds ability to filter anomaly detection datafeed {kibana-pull}89721[#89721]
* Adds custom metrics to node tooltip {kibana-pull}88545[#88545]
Monitoring::
* Enable edit/create for Stack Monitoring alerts in Alerts Management {kibana-pull}91726[#91726]
* Large shard alert {kibana-pull}89410[#89410]
* Remove deprecated watcher-based cluster alerts {kibana-pull}85047[#85047]
Operations::
* Rules table page size increase {kibana-pull}93993[#93993]
* Surface package version used in a package policy in UI {kibana-pull}93712[#93712]
* Filtering runtime mappings in anomaly detection wizards {kibana-pull}91534[#91534]
* Prevent duplicate notifications about the same anomaly result {kibana-pull}91485[#91485]
* Anomaly Detection alert initialisation from the ML app {kibana-pull}91283[#91283]
* Adds index pattern runtime fields to anomaly detection wizards {kibana-pull}91168[#91168]
* Format `PingList` duration time as seconds when appropriate {kibana-pull}90703[#90703]
* Adds nav search keywords for uptime and user experience app {kibana-pull}90616[#90616]
* Support `pit` and `search_after` in server `savedObjects.find` {kibana-pull}89915[#89915]
* Feature/80166 add waterfall flyout {kibana-pull}89449[#89449]
* Waterfall filters {kibana-pull}89185[#89185]
* Enables support for ES clusters using `action.destructive_requires_name=true` {kibana-pull}88986[#88986]
* Break down transaction table api removing the sparklines {kibana-pull}88946[#88946]
* Adds Label option for Dropdown Control {kibana-pull}88505[#88505]
Platform::
* Adds support for limited concurrency tasks {kibana-pull}90365[#90365]
* Implement custom global header banner {kibana-pull}87438[#87438]
* Implement new palette service {kibana-pull}86876[#86876]
* Allows apps to register searchable keywords for Global Search {kibana-pull}85686[#85686]
* Use elastic chart library for bar/area/line charts in Visualize {kibana-pull}78154[#78154]
Security::
* Allow custom index privileges for role management {kibana-pull}88076[#88076]
* Redesign user management page, and allow disabling users {kibana-pull}87133[#87133]
* Adds ECS audit events for Spaces {kibana-pull}86343[#86343]
Sharing::
* Expose anonymous access through a switch in sharing menu {kibana-pull}86965[#86965]
Uptime::
* Remove UI filters from UI {kibana-pull}89793[#89793]
* Expand synthetic journey step thumbnail on hover {kibana-pull}89179[#89179]
* Service overview: Introduce time-series comparison {kibana-pull}88665[#88665]
Other::
* Updated favicons {kibana-pull}87271[#87271]

[float]
[[fixes-v7.12.0]]
=== Bug Fixes
Alerting::
* Skips Alert Instances that were instantiated but have no scheduled actions {kibana-pull}91179[#91179]
* Fixes a bad UX for `xpack.actions.enabled` is set as false. UI should show the proper message instead of the endless spinner {kibana-pull}89043[#89043]
* Ensures we always select the correct index in UI tests {kibana-pull}88876[#88876]
* Adds missing configuration options for the alerting related plugins to the kibana-docker {kibana-pull}88297[#88297]
* Gracefully handling unknown action type {kibana-pull}86910[#86910]
* Edit alert should show and update all actions with deleted connectors {kibana-pull}86838[#86838]
APM::
* Fixes hidden search bar in error pages while loading {kibana-pull}93139[#93139]
* Fixes duplicate ML job creation for existing environments {kibana-pull}93098[#93098]
Dashboard::
* Fixes importing dashboards created before ~6.1.0 {kibana-pull}94332[#94332]
* Rename Cancel to Switch to View Mode {kibana-pull}94147[#94147]
* Enable Save Button When Filters Change {kibana-pull}93328[#93328]
* Remove "beta" label from URL Drilldown as it is now GA {kibana-pull}92859[#92859]
* Refactor Initial View Mode {kibana-pull}92747[#92747]
* Make Dashboard Unsaved Changes Space Specific {kibana-pull}92680[#92680]
* Remove Multiple History Entries & Stay in Edit Mode on Save As {kibana-pull}92105[#92105]
* Fixes Visualize Link Redirecting to Dashboard Linked Visualization {kibana-pull}90243[#90243]
* Fixes Dashboard OnAppLeave {kibana-pull}86193[#86193]
Design::
* Modal a11y {kibana-pull}93332[#93332]
* Adding better aria-labels for global search and field search in Lens {kibana-pull}89215[#89215]
* Adds autofocus to cron editor {kibana-pull}86324[#86324]
Discover::
* Fixes filter creation for numeric scripted fields in Discover {kibana-pull}93224[#93224]
* Fixes link from dashboard saved search to Discover {kibana-pull}92937[#92937]
* Fixes navigating from discover single document view back to discover {kibana-pull}92463[#92463]
* Could not expand cell content in DiscoverGrid {kibana-pull}91289[#91289]
* Fixes icon for conflicting fields {kibana-pull}90641[#90641]
* Add icon for nested fields in sidebar {kibana-pull}85147[#85147]
* Fixes context view for date_nanos format with custom timestamps {kibana-pull}54089[#54089]
Elastic Security::
For the Elastic Security 7.12.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Fleet::
* Return empty agents list when submitting a kuery with no keys {kibana-pull}93844[#93844]
* V1 migrations: drop fleet-agent-events during a migration {kibana-pull}92188[#92188]
Lens & Visualizations::
* Fixes cannot brush on bars of vertical bar chart to zoom into data {kibana-pull}94290[#94290]
* Prevent double load in editor in *Lens* {kibana-pull}93930[#93930]
* Fixes median aggregation when used with a scripted field {kibana-pull}93731[#93731]
* Remove portal for screenreader component in *Lens* {kibana-pull}93274[#93274]
* Fixes sorting undefined, null and NaN values in *Lens* {kibana-pull}92575[#92575]
* Fixes bug in Safari and Firefox form rendering in *Lens* {kibana-pull}92542[#92542]
* Fixes unformatted timeseries functions in *Lens* {kibana-pull}92498[#92498]
* Pass used histogram interval to chart in *Lens* {kibana-pull}91370[#91370]
* Fixes empty display name issue in XY chart in *Lens* {kibana-pull}91132[#91132]
* Fixes telemetry read only error in *Lens* {kibana-pull}91104[#91104]
* Stop inserting zeroes for null series in *TSVB* {kibana-pull}90861[#90861]
* Restores signal values on refresh in *Vega* {kibana-pull}90774[#90774]
* Fixes the timeseries legend, renders the metric, gauge charts for series with empty strings in *TSVB* {kibana-pull}90760[#90760]
* Make Lens intervals default value adapt to histogram:maxBars Advanced Setting changes in *Lens* {kibana-pull}89305[#89305]
* Vega Maps Referencing from kibana.yml {kibana-pull}88316[#88316]
* Close popover on repeated button click in *Lens* {kibana-pull}87834[#87834]
* Make sure filter object is persistable in *Lens* {kibana-pull}87828[#87828]
* Upgrading vis with pipeline agg from 6.8 doesn't render {kibana-pull}93427[#93427]
Logs::
* Check for privileges with user management links {kibana-pull}91134[#91134]
* Use useMlHref hook for ML links {kibana-pull}90935[#90935]
Machine Learning::
* DataFrame Analytics models: ensure 'View training data' link activates quick filter in exploration page {kibana-pull}93071[#93071]
* Fixes positions of calendar arrow buttons in start datafeed modal {kibana-pull}92625[#92625]
* Anomaly Explorer: ensure filtering works as expected when influencer value has trailing backslash {kibana-pull}92471[#92471]
* Data Frame Analytics wizard: ensure required config options are loaded before enabling `Continue` {kibana-pull}92254[#92254]
* Fixes event rate chart annotation position {kibana-pull}91899[#91899]
* Data Frame Analytics exploration page: filters improvements {kibana-pull}91748[#91748]
* Data Frame Analytics cloning: ensure classification hyperparameters retained when cloning job {kibana-pull}91507[#91507]
* Stops new line on enter key press for KQL query bars {kibana-pull}90960[#90960]
* Allow filtering by mlcategory in Anomaly Explorer Influencers list {kibana-pull}90282[#90282]
* Fixes rare page crash when deleting anomaly detection job {kibana-pull}88622[#88622]
Management::
* Fixes parent pipeline aggregations with custom metric and custom sort order {kibana-pull}93276[#93276]
* Adding schema for all current query_string settings {kibana-pull}93175[#93175]
* Preserve unknown fields in processors {kibana-pull}91146[#91146]
* Can't create single character index without wildcard {kibana-pull}90919[#90919]
* Use core doc links service {kibana-pull}89363[#89363]
* Fixes saved object view path {kibana-pull}89057[#89057]
* Use "untitled" filename for panels with no title in dashboard {kibana-pull}86333[#86333]
Maps::
* Fixes selecting EMS basemap does not populate input {kibana-pull}92711[#92711]
* Increase index pattern select limit to 1000 {kibana-pull}92093[#92093]
* Fixes issue preventing WebGL warning message from appearing {kibana-pull}91069[#91069]
* Fixes geo shape agg telemetry not collecting due to missing index pattern IDs {kibana-pull}90886[#90886]
* Fixes reporting jobs fail when Elastic Maps Service (EMS) is unavailable {kibana-pull}90834[#90834]
* Fixes users without access to Maps should not have the option to create them {kibana-pull}88830[#88830]
* Geo containment latency and concurrent containment fix {kibana-pull}86980[#86980]
Metrics::
* Use global kibana time for metrics explorer in Default View {kibana-pull}92520[#92520]
* Fixes alerts repeatedly firing "recovered" actions {kibana-pull}91038[#91038]
* Fixes node details overlay title with long host name {kibana-pull}90825[#90825]
* Fixes saving/loading saved views from URL {kibana-pull}90216[#90216]
* Fixes alert preview accuracy with new Notify settings {kibana-pull}89939[#89939]
* Fixes history drawer when navigation is docked {kibana-pull}89630[#89630]
* Completely remove GraphQL and Apollo {kibana-pull}89036[#89036]
Monitoring::
* Security telemetry allowlist fix {kibana-pull}92850[#92850]
* Adds missing fields for security telemetry {kibana-pull}91920[#91920]
* Fetch status once and change fetchStatus to support an array of clusters {kibana-pull}91749[#91749]
Operations::
* Increases pre-packaged socket timeout and chunks the requests {kibana-pull}94531[#94531]
* Fixes first load in Inventory view {kibana-pull}94306[#94306]
* Enables Microsoft Teams for Detection Actions {kibana-pull}94239[#94239]
* Use EuiFieldPassword for password variables in policy editor {kibana-pull}94166[#94166]
* Fixes package policies created with null var values (empty defaults) {kibana-pull}94040[#94040]
* Adds missing mappings to the signals for the indicator rules {kibana-pull}92928[#92928]
* Fixes ECS audit logging config settings for docker environments {kibana-pull}92497[#92497]
* Fixes handling of built-in models {kibana-pull}92154[#92154]
* Adds more granular validation for nested fields {kibana-pull}92041[#92041]
* Data Frame Analytics: Improved error handling for scatterplot matrix {kibana-pull}91993[#91993]
* Fixes loading indicators in the rules management table {kibana-pull}91925[#91925]
* Kql Search Bar suggests values outside the selected time range {kibana-pull}91918[#91918]
* Improves query performance of first and last events {kibana-pull}91790[#91790]
* Latency percentile labels and instances table support {kibana-pull}91758[#91758]
* Update error banner when refreshing rule status on rule details page {kibana-pull}91051[#91051]
Platform::
* Cancel nested executions when main execution is canceled {kibana-pull}91486[#91486]
* Updating SO _find filter parser to take into consideration multi-fields {kibana-pull}90988[#90988]
* Increment task `attempts` when they fail during markTaskAsRunning {kibana-pull}88669[#88669]
* Reject invalid Timeout values in Task Type Definitions {kibana-pull}88602[#88602]
* Cancel expired tasks as part of the available workers check {kibana-pull}88483[#88483]
* Resilient saved object migration algorithm {kibana-pull}78413[#78413]
Querying & Filtering::
* Remove number parsing {kibana-pull}93658[#93658]
* Do not generate nested AST/Elasticsearch queries for same-level AND/OR clauses {kibana-pull}93506[#93506]
* Fixes accessibility in the global query bar {kibana-pull}93411[#93411]
Reporting::
* Deserialize query string options for serverside ES Query {kibana-pull}90050[#90050]
Security::
* Do not generate an ephemeral encryption key in production {kibana-pull}81511[#81511]
