[[release-notes]]
= Release notes

[partintro]
--
// Use these for links to issue and pulls. Note issues and pulls redirect one to
// each other on Github, so don't worry too much on using the right prefix.
:issue: https://github.com/elastic/kibana/issues/
:pull: https://github.com/elastic/kibana/pull/

Review important information about the {kib} 8.0.0 releases.

* <<release-notes-8.4.0>>
//* <<release-notes-8.3.3>>
//* <<release-notes-8.3.2>>
//* <<release-notes-8.3.1>>
//* <<release-notes-8.3.0>>
//* <<release-notes-8.2.3>>
//* <<release-notes-8.2.2>>
//* <<release-notes-8.2.1>>
//* <<release-notes-8.2.0>>
//* <<release-notes-8.1.3>>
//* <<release-notes-8.1.2>>
//* <<release-notes-8.1.1>>
//* <<release-notes-8.1.0>>
//* <<release-notes-8.0.1>>
//* <<release-notes-8.0.0>>
//* <<release-notes-8.0.0-rc2>>
//* <<release-notes-8.0.0-rc1>>
//* <<release-notes-8.0.0-beta1>>
//* <<release-notes-8.0.0-alpha2>>
//* <<release-notes-8.0.0-alpha1>>

--

[[release-notes-8.4.0]]
== {kib} 8.4.0

coming::[8.4.0]

For information about the {kib} 8.4.0 release, review the following information.

[float]
[[breaking-changes-8.4.0]]
=== Breaking changes

Breaking changes can prevent your application from optimal operation and performance.
Before you upgrade to 8.4.0, review the breaking changes, then mitigate the impact to your application.

// tag::notable-breaking-changes[]

[discrete]
[[breaking-135669]]
.xpack.agents.* are uneditable in UI when defined in kibana.yml
[%collapsible]
====
*Details* +
When you configure `setxpack.fleet.agents.fleet_server.hosts` and `xpack.fleet.agents.elasticsearch.hosts` in kibana.yml, you are unable to update the fields on the Fleet UI. For more information, refer to {kibana-pull}135669[#135669].

*Impact* +
To configure `setxpack.fleet.agents.fleet_server.hosts` and `xpack.fleet.agents.elasticsearch.hosts` on the Fleet UI, avoid configuring the settings in kibana.yml.
====
      
[discrete]
[[breaking-134336]]
.Removes the legacy charts library
[%collapsible]
====
*Details* +
The legacy implementation of the *Timelion* visualization charts library has been removed. All *Timelion* visualizations now use the elastic-charts library, which was introduced in 7.15.0. For more information, refer to {kibana-pull}134336[#134336].

*Impact* +
In 8.4.0 and later, you are unable to configure the *Timelion* legacy charts library advanced setting. For information about visualization Advanced Settings, check link:https://www.elastic.co/guide/en/kibana/8.4/advanced-options.html#kibana-visualization-settings[Visualization].
====
      
// end::notable-breaking-changes[]

[float]
[[deprecations-8.4.0]]
=== Deprecations

The following functionality is deprecated in 8.4.0, and will be removed in 9.0.0.
Deprecated functionality does not have an immediate impact on your application, but we strongly recommend
you make the necessary updates after you upgrade to 8.4.0.

[discrete]
[[deprecation-136422]]
.Deprecates interactive users that authenticate with ApiKey is deprecated and support will be removed in a future version
[%collapsible]
====
*Details* +
The ability to authenticate interactive users authenticating with ApiKey has been deprecated, and will be removed in a future version. For more information, refer to {kibana-pull}136422[#136422].

*Impact* +
To authenticate interactive users, use <<kibana-authentication,another authentication method>>. 
====
      
[float]
[[features-8.4.0]]
=== Features
{kib} 8.4.0 adds the following new and notable features.

Alerting::
* Adds the "updated at" feature in new alerts table {kibana-pull}136949[#136949]
* Adds a rule detail table with bulk actions {kibana-pull}136601[#136601]
* Adds bulk Actions for Alerts Table {kibana-pull}135797[#135797]
* Adds the Alerting stack-monitoring PoC {kibana-pull}135365[#135365]
* Adds custom inline/row actions for alerts table {kibana-pull}134015[#134015]

Discover::
Adds the ability to add a custom number of rows in the results and save the specified number with a Saved Search {kibana-pull}135726[#135726]

Elastic Security::
For the Elastic Security 8.4.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].

Fleet::
* Enables package signature verification feature {kibana-pull}137239[#137239]
* Modal to allow user to force install an unverified package {kibana-pull}136108[#136108]
* Display package verification status {kibana-pull}135928[#135928]
* Tag rename and delete feature {kibana-pull}135712[#135712]
* Bulk update agent tags ui {kibana-pull}135646[#135646]
* Adds API to bulk update tags {kibana-pull}135520[#135520]
* Adds and remove agent tags {kibana-pull}135320[#135320]
* Support sorting agent list {kibana-pull}135218[#135218]
* Promote Logstash output support to GA {kibana-pull}135028[#135028]
* Create new API to manage download_source setting {kibana-pull}134889[#134889]

Lens & Visualizations::
* Adds supports for include and exclude terms in *Lens* {kibana-pull}136179[#136179]

Machine Learning::
* Adds random sampler to Data visualizer document count chart {kibana-pull}136150[#136150]
* Adds explain log rate spikes feature to the ML plugin {kibana-pull}135948[#135948]

Management::
* Run packs live {kibana-pull}132198[#132198]
* Ability to set human readable title of data view & ability to edit data view {kibana-pull}124191[#124191]

Monitoring::
Adds stale status reporting for Kibana {kibana-pull}132613[#132613]

Observability::
* Adds Beta label to Infrastructure tab {kibana-pull}136710[#136710]
* Create and add Rule Alerts Summary as a sharable component to the O11y Rule Details {kibana-pull}135805[#135805]
* Rule Details Page - Use RuleStatusPanel from triggersActionsUI {kibana-pull}135643[#135643]
* Cases permissions can be customized to prevent a user from deleting Cases entities (cases themselves, and attachments/comments) {kibana-pull}135487[#135487]
* Top erroneous transactions {kibana-pull}134929[#134929]
* Introduce Alerts tab on service overview page {kibana-pull}134350[#134350]
* Adds single metric report type {kibana-pull}132446[#132446]

Platform::
Adds new bulkUpdatesSchedules method to Task Manager {kibana-pull}132637[#132637]

Security::
Adds the ability to create personal avatars {kibana-pull}132522[#132522]

Sharing::
Adds the new metric visualization {kibana-pull}136567[#136567]

For more information about the features introduced in 8.4.0, refer to <<whats-new,What's new in 8.4>>.

[[enhancements-and-bug-fixes-v8.4.0]]
=== Enhancements and bug fixes

For detailed information about the 8.4.0 release, review the enhancements and bug fixes.
      
[float]
[[enhancement-v8.4.0]]
=== Enhancements
Alerting::
* Adds snooze state UI to Rule Details page {kibana-pull}135146[#135146]
* {REDO} Add Snooze Scheduling UI and API {kibana-pull}134512[#134512]
* Adds recovery context for ES query rule type {kibana-pull}132839[#132839]
* Visualize alerting metrics in Stack Monitoring {kibana-pull}123726[#123726]

Canvas::
* Markdown element auto-applies text changes {kibana-pull}133318[#133318]
* Lines operations keybindings {kibana-pull}132914[#132914]
* Detailed tooltip {kibana-pull}131116[#131116]

Cases::
* Improved the cases search bar functionality. The search functionality will only consider the title and description fields {kibana-pull}136776[#136776]
* Performance improvements were made to reduce the time required to create, update, and delete cases and comments. In our testing we saw around a half second reduction in the round trip time for the UI requests {kibana-pull}136452[#136452]

Dashboard::
Hide controls callout when the `hideAnnouncements` setting is `true` {kibana-pull}136410[#136410]

Design::
* Adds an H1 tag with the workpad title when viewing workpads {kibana-pull}135504[#135504]
* Improve keyboard navigation in Discover top nav menu {kibana-pull}134788[#134788]

Discover::
* Improves the HTML formatting of fields with a list of values {kibana-pull}136684[#136684]
* Adds support for accessing the edit field flyout from the document explorer column popover {kibana-pull}135277[#135277]
* Adds support for copying the query from the add rule flyout {kibana-pull}135098[#135098]
* Adds focus to h1 on navigate for single document and surrounding document views {kibana-pull}134942[#134942]
* Improves the creation and editing of "Elasticsearch query" rule in Management {kibana-pull}134763[#134763]
* Adds data view changed warning after alert rule created {kibana-pull}134674[#134674]
* Make 'Test query' button pretty {kibana-pull}134605[#134605]
* Improves the document explorer timestamp tooltip accessibility {kibana-pull}134411[#134411]
* Adds focus to h1 element when client side routing is executed {kibana-pull}133846[#133846]
* Adds an option to copy column values to Clipboard in Document Explorer {kibana-pull}132330[#132330]

Elastic Security::
For the Elastic Security 8.4.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].

Fleet::
* Remove Kubernetes Package granularity {kibana-pull}136622[#136622]
* Elastic-agent manifests: align with elastic-agent repo; add comments {kibana-pull}136394[#136394]
* Configure source URI in global settings and in agent policy settings {kibana-pull}136263[#136263]
* Adds Kubernetes in platforms selection list && update managed agent installation steps {kibana-pull}136109[#136109]
* That PR will enable user to write custom ingest pipeline for Fleet installed datastream {kibana-pull}134578[#134578]
* Update manifests for agent on kubernetes with new permissions {kibana-pull}133495[#133495]
* Adds support for a textarea type in integrations {kibana-pull}133070[#133070]

Kibana Home & Add Data::
Adds AnalyticsNoDataPage {kibana-pull}134172[#134172]

Lens & Visualizations::
* Adds the ability to set top values limit to 10,000 in *Lens* {kibana-pull}136399[#136399]
* Addss value count to *Lens* {kibana-pull}136385[#136385]
* Adds standard deviation function in *Lens* {kibana-pull}136323[#136323]
* Adds the ability to set the font size for mosaic outer level in *Lens* {kibana-pull}135911[#135911]
* Adds the ability to rank top values by custom metric in *Lens* {kibana-pull}134811[#134811]
* Adds the ability to convert TSVB series agg to *Lens* configuration {kibana-pull}134681[#134681]
* Adds the ability to allow multiple split accessors {kibana-pull}134566[#134566]
* Adds xExtent validation within expression {kibana-pull}134546[#134546]
* Adds the ability to render newlines in data table in *Lens* {kibana-pull}134441[#134441]
* Extends Axis bounds for XY chart when using Interval operation in *Lens* {kibana-pull}134020[#134020]
* Adds the ability to use pick_max instead of clamp for positive only {kibana-pull}133460[#133460]
* Adds a new pick_min/max operation and clamp fixes in *Lens* {kibana-pull}132449[#132449]
* Adds support for percentile_ranks aggregation in *Lens* {kibana-pull}132430[#132430]
* Implements the ability to drag and drop between layers in *Lens* {kibana-pull}132018[#132018]
* Adds optimization for percentiles fetching in *Lens* {kibana-pull}131875[#131875]
* Adds `axes` support {kibana-pull}129476[#129476]

Machine Learning::
* Adds tooltips for disabled actions in the Trained Models list {kibana-pull}137176[#137176]
* Data visualizer: Add field types in-product help {kibana-pull}137121[#137121]
* Plot zero scores on the Overall anomaly swim lane {kibana-pull}136951[#136951]
* One-way cursor sync added from Anomaly detection swimlane to other charts {kibana-pull}136775[#136775]
* Adds action to view datafeed counts chart to jobs list rows {kibana-pull}136274[#136274]
* Data Visualizer: Remove duplicated geo examples, support 'version' type, add filters for boolean fields, and add sticky header to Discover {kibana-pull}136236[#136236]
* Adds a link to ML trained models list from ID in Stack Management app table {kibana-pull}135700[#135700]
* Adds information callouts to trained model testing flyout {kibana-pull}135566[#135566]
* Limit Use full data button in anomaly detection job wizards to past data only {kibana-pull}135449[#135449]
* Replace a fixed Y-axis width with a max width setting for Anomaly Swim Lane Embeddable {kibana-pull}135436[#135436]
* Adds support for setting threading params when starting a trained model deployment {kibana-pull}135134[#135134]
* Management page refactor {kibana-pull}134893[#134893]
* Disable the Single Metric Viewer button for not viewable jobs {kibana-pull}134048[#134048]
* Anomaly Detection: allow snapshot to be reverted from the view datafeed flyout {kibana-pull}133842[#133842]

Management::
* Transforms: Adds per-transform setting for num_failure_retries to creation wizard and edit flyout and authorization info {kibana-pull}135486[#135486]
* Adds sorting to Transform's Audit Messages {kibana-pull}135047[#135047]
* Console now supports saving the state of folding/unfolding of commands {kibana-pull}134810[#134810]
* Render most severe response status code from Console response pane {kibana-pull}134627[#134627]
* You can now create variables in Console {kibana-pull}134215[#134215]
* Make index template previews copyable {kibana-pull}134060[#134060]
* Console now supports adding comments in the body of a request by using `//` for a single line and `/*....*/` for multiline comments {kibana-pull}133852[#133852]
* Improve UX around handling multiple requests {kibana-pull}132494[#132494]
* Adds updated `essql` expression function {kibana-pull}132332[#132332]
* Adds a "get all" REST API for data views: `GET /api/data_views` {kibana-pull}131683[#131683]

Maps::
* Automatically display the maps legend {kibana-pull}136872[#136872]
* Custom raster source example plugin {kibana-pull}136761[#136761]
* Label zoom range style property {kibana-pull}136690[#136690]
* Adjust icon size when cluster resolution changes {kibana-pull}136573[#136573]
* Adds context for 'No longer contained' geo-containment alert {kibana-pull}136451[#136451]
* Keydown+scroll to zoom {kibana-pull}135330[#135330]
* Synchronize map views in dashboard and canvas {kibana-pull}134272[#134272]
* Adds spatial filter from cluster {kibana-pull}133673[#133673]
* Customizable colors in basemaps {kibana-pull}131576[#131576]

Observability::
* Prefer DataView client over SavedObjects client when possible {kibana-pull}136694[#136694]
* Use proper header nesting {kibana-pull}136559[#136559]
* Removes "no data" redirects for observability overview {kibana-pull}136442[#136442]
* Allow connectors to explicitly register which features they will be available in {kibana-pull}136331[#136331]
* Display node details metrics for kubernetes containers {kibana-pull}135585[#135585]
* Replace sourceId with mandatory logView prop in LogStream component {kibana-pull}134850[#134850]
* Backend operation distribution chart {kibana-pull}134561[#134561]
* Display top spans for operation {kibana-pull}134179[#134179]
* Show descriptive loading, empty and error states in the metrics table {kibana-pull}133947[#133947]
* Backend operations detail view + metric charts {kibana-pull}133866[#133866]
* Backend operations list view {kibana-pull}133653[#133653]

Platform::
* Upgrade Kibana logs to ECS 8.4 {kibana-pull}136362[#136362]
* Adds error messaging to the report contents when there is a timeout in page setup {kibana-pull}134868[#134868]
* Adds migrations.discardCorruptObjects flag {kibana-pull}132984[#132984]
* Adds migrations.discardUnknownObjects flag {kibana-pull}132167[#132167]

Querying & Filtering::
Hides the tour component when the hideAnnouncements uiSetting is on {kibana-pull}135990[#135990]

Security::
Adds the ability to navigate to a profile without full page reload {kibana-pull}135543[#135543]

[float]
[[fixes-v8.4.0]]
=== Bug fixes
Alerting::
* Error message hidden after closing action accordion {kibana-pull}136570[#136570]
* Allow wildcard search on rule's name and tags {kibana-pull}136312[#136312]

Canvas::
* Fixes Filter not saving the selected Sort field option {kibana-pull}136085[#136085]
* Fixes "Element status" is inaccurate for grouped elements {kibana-pull}135829[#135829]
* Fixes Canvas filter behaviour on table {kibana-pull}134801[#134801]
* Fixes Uploaded asset not being saved {kibana-pull}133166[#133166]
* Lines operations keybindings {kibana-pull}132914[#132914]
* Fixes pointseries don't get updated on datasource change {kibana-pull}132831[#132831]

Connectors::
* Fixing ES index connector so that it can index into data streams as well as indices {kibana-pull}136011[#136011]
* Verify emails when creating an email connector, even if allowedDomain… {kibana-pull}133859[#133859]

Dashboard::
Fixes Copy to dashboard includes filters {kibana-pull}136275[#136275]

Discover::
* Fixes hiding histogram for rollup data views {kibana-pull}137157[#137157]
* Fixes filtering out custom meta fields of Elasticsearch plugins enhanced documents {kibana-pull}137147[#137147]
* Disables refresh interval for data views without time fields and rollups {kibana-pull}137134[#137134]
* Fixes Discover breadcrumb losing context after page refresh or when opening in a new tab {kibana-pull}136749[#136749]
* Improves support for pinned filters in surrounding documents {kibana-pull}135722[#135722]
* Fixes flaky accessibility functional tests {kibana-pull}135596[#135596]
* Improves alerts popover accessibility and semantics {kibana-pull}135270[#135270]
* Migrate from savedObjectsClient to dataViews and fix the displayed data view name {kibana-pull}135142[#135142]
* Removes _type of metaFields to remove of sidebar {kibana-pull}134453[#134453]
* Fixes legacy sort parameter provided by URL {kibana-pull}134447[#134447]
* Make footer visible under Document Explorer if sample size is less than hits number {kibana-pull}134231[#134231]
* Do not update defaultIndex in case of insufficient permissions {kibana-pull}134202[#134202]
* Fixes flaky test for "allows editing of a newly created field" {kibana-pull}132812[#132812]
* Fixes flaky test for "context encoded URL params" {kibana-pull}132808[#132808]

Elastic Security::
For the Elastic Security 8.4.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].

Fleet::
Using point in time for agent status query to avoid discrepancy {kibana-pull}135816[#135816]

Lens & Visualizations::
* Make reference line chart more robust in *Lens* {kibana-pull}137101[#137101]
* Format the label with the right default formatter in *TSVB* {kibana-pull}136934[#136934]
* Removes extra space from the legend when it is positioned on top/bottom {kibana-pull}135982[#135982]
* Display Y-axis tick labels {kibana-pull}135976[#135976]
* Fixes Date histogram bounds calculation doesn't update "now" {kibana-pull}135899[#135899]
* Fixes internal links in *Vega* {kibana-pull}135890[#135890]
* Do not set non-unique id for legend action popovers in *Lens* {kibana-pull}135656[#135656]
* Fixes non-editable Lens panel when using prefix wildcard in *Lens* {kibana-pull}135654[#135654]
* Removes saved search references from all places on unlink in *Visualize* {kibana-pull}135628[#135628]
* Fix multi-field top values for Heatmap visualizations in *Lens* {kibana-pull}135581[#135581]
* Fixes styling issues in *Lens* {kibana-pull}135406[#135406]
* Show badge for read-only in *Lens* {kibana-pull}135313[#135313]
* Don't let reference line fills on different axes collide in *Lens* {kibana-pull}135299[#135299]
* Fixes css specificity issue in *TSVB* {kibana-pull}135245[#135245]
* Always show palette on first dimension for mosaic in *Lens* {kibana-pull}135198[#135198]
* Wrong `visType` for `horizontal_bar` visualization {kibana-pull}135013[#135013]
* Unlinking Some Agg Based Visualizations Results in Unsaved Changes in *Visualize* {kibana-pull}134229[#134229]
* [Datatable] Ellipsis truncation is not visible in cells. Letters are just cut off. in *Lens* {kibana-pull}134065[#134065]
* Switching dashboard mode doesn't update missing data view prompt in *Visualize* {kibana-pull}133873[#133873]
* Fixes application of suffix formats in *Lens* {kibana-pull}133780[#133780]
* Error messages not centered in *TSVB* {kibana-pull}133288[#133288]
* Use correct time zone for time shifting {kibana-pull}133141[#133141]

Machine Learning::
* Lock the delete annotation button on click {kibana-pull}137306[#137306]
* Fixes globally pinned filters in Data visualizer and query search bar not clearing properly for saved searches {kibana-pull}136897[#136897]
* Fixes overflow in start datafeed modal {kibana-pull}136292[#136292]
* Fixes error in categorization wizard summary step {kibana-pull}134228[#134228]

Management::
* The ILM UI now supports configuring policies with rollover based on `max_primary_shard_docs` {kibana-pull}137364[#137364]
* Fixes a bug in Console when sending a request with encoded characters resulted in an error {kibana-pull}136788[#136788]
* Fixes a bug where the autocomplete popup remains open when navigating away from Console {kibana-pull}136268[#136268]
* Fixes a bug in Index Management where the number of documents for an index could appear wrong {kibana-pull}135748[#135748]
* Fixes a bug in the Painless code editor that was incorrectly handling expressions with multiple division operators {kibana-pull}135423[#135423]

Maps::
* Fixes "other" is always shown in legend for category styling rules {kibana-pull}137008[#137008]
* Fixes Tooltip loses pages on refresh {kibana-pull}135593[#135593]
* Fixes Pinned filters should be visible on new maps without user having to do any action on layers {kibana-pull}135465[#135465]
* Keep timeframe when editing a map from a dashboard {kibana-pull}135374[#135374]
* Reduce precision of coordinates for geo imports {kibana-pull}135133[#135133]
* Fixes onDataLoadEnd and onDataLoadError event handler callbacks only called for source data requests {kibana-pull}134786[#134786]
* Fixes sort not applied to vector tile search request {kibana-pull}134607[#134607]
* Fixes array values out of order in tooltips {kibana-pull}134588[#134588]

Monitoring::
Removes beta icon from logstash pipeline {kibana-pull}131752[#131752]

Observability::
* Invalid array value is permitted in Origin Headers for RUM configuration {kibana-pull}137228[#137228]
* When comparison feature is disabled, we still see the shaded area {kibana-pull}137223[#137223]
* Fixes responsivity Alert Summary chart in the Rule details page {kibana-pull}137175[#137175]
* Fixes custom link filter select value {kibana-pull}137025[#137025]
* Fixes Spark plots loading state when there are no data {kibana-pull}136817[#136817]
* Adds support for metrics for latency distribution histogram {kibana-pull}136594[#136594]
* Navigation from Span to Service breaks due to wrong transactionType {kibana-pull}136569[#136569]
* Breadcrumbs not updating from service jump on service map {kibana-pull}136144[#136144]
* Adds support for metrics for latency distribution histogram {kibana-pull}136083[#136083]
* Disallow spaces in index pattern {kibana-pull}135977[#135977]
* WrappedElasticsearchClientError: Request aborted {kibana-pull}135752[#135752]
* Fixes waterfall skew due to accordion left margins {kibana-pull}135544[#135544]
* Service inventory: detailed stats fetched for all services {kibana-pull}134844[#134844]
* Update network fields {kibana-pull}134471[#134471]
* Fixes Metrics Table Pod link to Details Page {kibana-pull}134354[#134354]
* Adds last updated at label and fix started at label {kibana-pull}134254[#134254]
* Adds event module filter to metrics table {kibana-pull}133872[#133872]

Platform::
* Migrations wait for index status green if create index returns acknowledged=false or shardsAcknowledged=false {kibana-pull}136605[#136605]
* Fixes CSV generator to include unmapped fields in the search source {kibana-pull}132972[#132972]

[[release-notes-8.0.0]]
== {kib} 8.0.0

Review the {kib} 8.0.0 changes, then use the {kibana-ref-all}/7.17/upgrade-assistant.html[Upgrade Assistant] to complete the upgrade.

[float]
[[breaking-changes-8.0.0]]
=== Breaking change

Breaking changes can prevent your application from optimal operation and performance.
Before you upgrade to 8.0.0, review the breaking change, then mitigate the impact to your application.

[discrete]
[[breaking-123754]]
.Removes the `console.ssl` setting
[%collapsible]
====
*Details* +
The `console.ssl` setting has been removed. For more information, refer to {kibana-pull}123754[#123754].

*Impact* +
Before you upgrade to 8.0.0, remove `console.ssl` from kibana.yml.
====

To review the breaking changes in previous versions, refer to the following: 

<<breaking-changes-8.0.0-rc2,8.0.0-rc2>> | <<breaking-changes-8.0.0-rc1,8.0.0-rc1>> | <<breaking-changes-8.0.0-beta1,8.0.0-beta1>> | <<breaking-changes-8.0.0-alpha2,8.0.0-alpha2>> | 
<<breaking-changes-8.0.0-alpha1,8.0.0-alpha1>>

[float]
[[deprecations-8.0.0]]
=== Deprecation

The following functionality is deprecated in 8.0.0, and will be removed in 9.0.0.
Deprecated functionality does not have an immediate impact on your application, but we strongly recommend
you make the necessary updates after you upgrade to 8.0.0.

[discrete]
[[deprecation-123229]]
.Removes support for `monitoring.cluster_alerts.allowedSpaces`
[%collapsible]
====
*Details* +
The `monitoring.cluster_alerts.allowedSpaces` setting, which {kib} uses to create Stack Monitoring alerts, has been removed. For more information, refer to {kibana-pull}123229[#123229].

*Impact* +
Before you upgrade to 8.0.0, remove `monitoring.cluster_alerts.allowedSpaces` from kibana.yml.
====

To review the deprecations in previous versions, refer to the following:

<<deprecations-8.0.0-rc1,8.0.0-rc1>> | <<deprecations-8.0.0-alpha1,8.0.0-alpha1>>

[float]
[[known-issue-8.0.0]]
=== Known issue

[discrete]
[[known-issue-123550]]
.Importing and copying saved objects causes weak links to break
[%collapsible]
====
*Details* +
{kib} supports weak links in some saved objects. For example, a dashboard may include a Markdown panel that contains a relative URL to
another dashboard. Weak links are defined by free text, _not_ the saved object's relationships, and can break if **both** of the following
conditions are true:

* You are importing saved objects into multiple spaces, _OR_ you are copying saved objects into another space
* Before you upgraded to 8.0.0, the saved objects did not already exist in the destinations

In 8.0.0 and later, weak links break because <<saved-object-ids-impact-when-using-import-and-copy,saved object IDs can change during import or copy>>.
This applies to both the UI and the API.
This issue will be fixed 8.0.1 and 8.1.0. For more information, refer to {kibana-issue}123550[#123550].

*Impact* +
Saved objects in 7.x that are migrated during upgrade are **not** impacted.
Only _new_ saved objects that are imported or copied _multiple times_ (causing object IDs to change) are impacted.
If you are impacted, you can re-import or re-copy your saved objects after the fix is
implemented to preserve the weak links.
====

[float]
[[features-8.0.0]]
=== Features
For information about the features introduced in 8.0.0, refer to <<whats-new,What's new in 8.0>>.

Elastic Security::
For the Elastic Security 8.0.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].

To review the features in previous versions, refer to the following: 

<<features-8.0.0-rc2,8.0.0-rc2>> | <<features-8.0.0-rc1,8.0.0-rc1>> | <<features-8.0.0-beta1,8.0.0-beta1>> | <<features-8.0.0-alpha2,8.0.0-alpha2>>

[[enhancements-and-bug-fixes-v8.0.0]]
=== Enhancements and bug fixes

For detailed information about the 8.0.0 release, review the enhancements and bug fixes.

[float]
[[enhancement-v8.0.0]]
==== Enhancements
Dashboard::
Clone ReferenceOrValueEmbeddables by value {kibana-pull}122199[#122199]

Elastic Security::
For the Elastic Security 8.0.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].

[float]
[[fixes-v8.0.0]]
==== Bug Fixes
APM::
Restrict aggregated transaction metrics search to date range {kibana-pull}123445[#123445]

Elastic Security::
For the Elastic Security 8.0.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].

Fleet::
Allow empty strings for required text fields in package policies {kibana-pull}123610[#123610]

Maps::
Fixes Label border color is not removed from legend when disabled {kibana-pull}122705[#122705]

Monitoring::
Ensure logstash getNodes always contains a uuid {kibana-pull}124201[#124201]

Security::
Long-running requests no longer cause sporadic logouts in certain cases, even when user sessions are active {kibana-pull}122155[#122155]

[[release-notes-8.0.0-rc2]]
== {kib} 8.0.0-rc2

For information about the {kib} 8.0.0-rc2 release, review the following information.

[float]
[[breaking-changes-8.0.0-rc2]]
=== Breaking change

Breaking changes can prevent your application from optimal operation and performance.
Before you upgrade, review the breaking change, then mitigate the impact to your application.

[discrete]
[[breaking-122722]]
.Removes the ability to use `elasticsearch.username: elastic` in production
[%collapsible]
====
*Details* +
In production, you are no longer able to use the `elastic` superuser to authenticate to {es}. For more information, refer to {kibana-pull}122722[#122722].

*Impact* +
When you configure `elasticsearch.username: elastic`, {kib} fails.
====

To review the breaking changes in previous versions, refer to the following: 

<<breaking-changes-8.0.0-rc1,8.0.0-rc1>> | <<breaking-changes-8.0.0-beta1,8.0.0-beta1>> | <<breaking-changes-8.0.0-alpha2,8.0.0-alpha2>> | 
<<breaking-changes-8.0.0-alpha1,8.0.0-alpha1>>

[float]
[[features-8.0.0-rc2]]
=== Features
{kib} 8.0.0-rc2 adds the following new and notable features.

Dashboard::
Dashboard Integration {kibana-pull}115991[#115991]
Elastic Security::
For the Elastic Security 8.0.0-rc2 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Monitoring::
Enterprise Search Stack Monitoring {kibana-pull}114303[#114303]
Observability::
* Adds Agent Keys in APM settings - Create agent keys {kibana-pull}120373[#120373]
* Adds Agent Keys in APM settings - Agent key table {kibana-pull}119543[#119543]
* Allows users to set Download Speed, Upload Speed, and Latency for their synthetic monitors in Uptime {kibana-pull}118594[#118594]
Platform::
Changes saved objects management inspect view to a read-only JSON view of the whole saved object {kibana-pull}112034[#112034]

[[enhancements-and-bug-fixes-v8.0.0-rc2]]
=== Enhancements and bug fixes

For detailed information about the 8.0.0-rc2 release, review the enhancements and bug fixes.

[float]
[[enhancement-v8.0.0-rc2]]
==== Enhancements
Elastic Security::
For the Elastic Security 8.0.0-rc2 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Security::
Adds session cleanup audit logging {kibana-pull}122419[#122419]
Observability::
Make a monitor's steps details page work on mobile resolutions in Uptime {kibana-pull}122171[#122171]

[float]
[[fixes-v8.0.0-rc2]]
==== Bug Fixes
Alerting::
Fixes PagerDuty timestamp validation {kibana-pull}122321[#122321]
Dashboard::
* Creates Explicit Diffing System {kibana-pull}121241[#121241]
* Fixes blank panel save and display issue {kibana-pull}120815[#120815]
* Fixes full screen error when pressing back arrow on browser {kibana-pull}118113[#118113]
Elastic Security::
For the Elastic Security 8.0.0-rc2 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Maps::
* Fixes Point to point and Tracks layers label properties not showing in the legend {kibana-pull}122993[#122993]
* Fixes Color ramp UI for percent of a top term in join layer is broken {kibana-pull}122718[#122718]
Observability::
* Updates index pattern permission error in APM {kibana-pull}122680[#122680]
* Honor time unit for Inventory Threshold in Metrics {kibana-pull}122294[#122294]
* Adds locator to aid other plugins in linking properly to Uptime {kibana-pull}123004[#123004]
* Fixes a bug in which headers would be incorrectly centered on desktop in Uptime {kibana-pull}122643[#122643]

[[release-notes-8.0.0-rc1]]
== {kib} 8.0.0-rc1

Review the {kib} 8.0.0-rc1 changes, then use the <<upgrade-assistant,Upgrade Assistant>> to complete the upgrade.

[float]
[[breaking-changes-8.0.0-rc1]]
=== Breaking changes

Breaking changes can prevent your application from optimal operation and performance.
Before you upgrade, review the breaking changes, then mitigate the impact to your application.

[discrete]
[[breaking-118854]]
.Splits package policy `upgrade` endpoint for Fleet
[%collapsible]
====
*Details* +
For package policy upgrades, the packagePolicy `upgrade` endpoint format supports a mutative upgrade operation (when `dryRun: false`) and a read-only dry run operation (when `dryRun: true`):

[source,text]
--
 POST /package_policies/upgrade
 {
   packagePolicyIds: [...],
   dryRun: false
 }
--

For more information, refer to {kibana-pull}118854[#118854].

*Impact* +
The endpoint is now split into two separate endpoints:

[source,text]
--
 POST /package_policies/upgrade
 {
   packagePolicyIds: [...]
 }

 POST /package_policies/upgrade/dry_run
 {
   packagePolicyIds: [...]
 }
--
====
      
[discrete]
[[breaking-119945]]
.Removes APM jobs from Machine Learning
[%collapsible]
====
*Details* +
APM Node.js and RUM JavaScript anomaly detection job modules have been removed. For more information, refer to {kibana-pull}119945[#119945].

*Impact* +
When you upgrade to 8.0.0, you are unable to create and view the APM Node.js and RUM JavaScript jobs in Machine Learning.
====

[discrete]
[[breaking-118300]]
.Fails migrations for unknown types
[%collapsible]
====
*Details* +
Unknown saved object types now cause {kib} migrations to fail. For more information, refer to {kibana-issue}107678[#107678].

*Impact* +
To complete the migration, re enable plugins or delete documents from the index in the previous version.
====

[discrete]
[[breaking-116821]]
.Removes deprecated config fields from Logs and Metrics APIs and saved objects
[%collapsible]
====
*Details* +
On the Logs and Metrics UIs, references to the following API and saved object deprecated fields have been removed: 

* `timestamp`
* `tiebreaker`
* `container`
* `pod`
* `host`

For more information, refer to {kibana-pull}116821[#116821] and {kibana-pull}115874[#115874].

*Impact* +
When you upgrade to 8.0.0, you are unable to use references to the deprecated fields.
====

To review the breaking changes in previous versions, refer to the following: 

<<breaking-changes-8.0.0-beta1,8.0.0-beta1>> | <<breaking-changes-8.0.0-alpha2,8.0.0-alpha2>> | 
<<breaking-changes-8.0.0-alpha1,8.0.0-alpha1>>

[float]
[[deprecations-8.0.0-rc1]]
=== Deprecations

Deprecated functionality does not have an immediate impact on your application, but we strongly recommend you make the necessary updates after you complete the upgrade.

[discrete]
[[deprecation-120689]]
.Renames the `autocreate` data view APM setting
[%collapsible]
====
*Details* +
The `xpack.apm.autocreateApmIndexPattern` APM setting has been removed. For more information, refer to {kibana-pull}120689[#120689].

*Impact* +
To automatically create data views in APM, use `xpack.apm.autoCreateApmDataView`.
====

[discrete]
[[deprecation-119494]]
.Updates Fleet API to improve consistency
[%collapsible]
====
*Details* +
The Fleet API has been updated to improve consistency:

* Hyphens are changed to underscores in some names.
* The `pkgkey` path parameter in the packages endpoint is split.
* The `response` and `list` properties are renamed to `items` or `item` in some
responses.

For more information, refer to {kibana-pull}119494[#119494].

*Impact* +
When you upgrade to 8.0.0, use the following API changes:

* Use `enrollment_api_keys` instead of `enrollment-api-keys`.

* Use `agent_status` instead of `agent-status`.

* Use `service_tokens` instead of `service-tokens`.

* Use `/epm/packages/{packageName}/{version}` instead of `/epm/packages/{pkgkey}`.

* Use `items[]` instead of `response[]` in:
+
[source,text]
--
/api/fleet/enrollment_api_keys
/api/fleet/agents
/epm/packages/
/epm/categories
/epm/packages/_bulk
/epm/packages/limited
/epm/packages/{packageName}/{version} <1>
--
<1> Use `items[]` when the verb is `POST` or `DELETE`. Use `item` when the verb
is `GET` or `PUT`.

For more information, refer to {fleet-guide}/fleet-api-docs.html[Fleet APIs].

====

To review the deprecations in previous versions, refer to the <<deprecations-8.0.0-alpha1,8.0.0-alpha1 release notes>>. 


[float]
[[features-8.0.0-rc1]]
=== Features
{kib} 8.0.0-rc1 adds the following new and notable features.

Elastic Security::
For the Elastic Security 8.0.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Management::
Display managed badge for transforms {kibana-pull}117679[#117679]
Monitoring::
Enterprise Search Stack Monitoring {kibana-pull}114303[#114303]
Observability::
* Adds ability to create agent keys in APM settings {kibana-pull}120373[#120373]
* Adds Agent key table in APM settings {kibana-pull}119543[#119543]
* Allows users to set Download Speed, Upload Speed, and Latency for their synthetic monitors {kibana-pull}118594[#118594]

[[enhancements-and-bug-fixes-v8.0.0-rc1]]
=== Enhancements and bug fixes

For detailed information about the 8.0.0-rc1 release, review the enhancements and bug fixes.

[float]
[[enhancement-v8.0.0-rc1]]
=== Enhancements
Canvas::
Reverts By-Value Embeddables {kibana-pull}117613[#117613]
Discover::
Adds multi-layer time axis for opt-out only {kibana-pull}115853[#115853]
Elastic Security::
For the Elastic Security 8.0.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Fleet::
Adds consistent `_meta` property to all Fleet ES assets {kibana-pull}119380[#119380]
Kibana Home & Add Data::
Moves overview page and link to the accordion solution title {kibana-pull}114018[#114018]
Lens & Visualizations::
* Handle removal of deprecated date histogram interval in *Vega* {kibana-pull}109090[#109090]
* Adds value labels to Heatmap in *Lens* {kibana-pull}106406[#106406]
Machine Learning::
* Adds support for `force` stop deployment {kibana-pull}118563[#118563]
* Refactors data view loading to remove unnecessary searches {kibana-pull}116455[#116455]
Observability::
* Service maps: Adds sparklines to the detail popover {kibana-pull}120021[#120021]
* Offer users upgrade to multi-metric job {kibana-pull}119980[#119980]
* Display relevant anomalies from multi-metric job {kibana-pull}119709[#119709]
* Adds service icon for the originating service in traces table {kibana-pull}119421[#119421]
* Auto attachment for java agent beta in APM integration settings {kibana-pull}119131[#119131]
* Errors: Enhancements to the Errors list page (part II) {kibana-pull}118878[#118878]
* Store Alerts View table state in localStorage {kibana-pull}118207[#118207]
* Handle other values popup when correlated value is not in top 10 {kibana-pull}118069[#118069]
* Adds links to navigate from alerts table to rule {kibana-pull}118035[#118035]
* Reinstates ML multi-metric job {kibana-pull}117836[#117836]
* Re-enables metric-based UI {kibana-pull}117021[#117021]
* Make Alerts page use shared {kib} time range {kibana-pull}115192[#115192]
* Adds enabled toggle {kibana-pull}119994[#119994]
* Adds missing tooltip to the report metric badge in *Exploratory View* {kibana-pull}119940[#119940]
* Adds step duration in step list {kibana-pull}116266[#116266]
Platform::
Moves developer architecture docs to user docs {kibana-pull}119125[#119125]
Reporting::
* Decouples screenshotting plugin from the reporting {kibana-pull}120110[#120110]
* Updates the design of the *Reports* management UI, including the addition of a link to {kib} app where the report was generated {kibana-pull}111412[#111412]
Security::
Adds ability to clone role mappings {kibana-pull}118434[#118434]
Adds user logout audit events {kibana-pull}121455[#121455]

[float]
[[fixes-v8.0.0-rc1]]
=== Bug Fixes
Canvas::
* Fixes Error overflow {kibana-pull}122158[#122158]
* Fixes expression input {kibana-pull}121490[#121490]
* Hides edit menu when in view-only mode {kibana-pull}118779[#118779]
Dashboard::
* Allow text wrapping for panel titles and dashboard descriptions for PDF generation {kibana-pull}121360[#121360]
* Page now resets to zero when rows per page is changed on *Add from Library* window {kibana-pull}118627[#118627]
* Fixes full screen error when pressing back arrow in browser {kibana-pull}118113[#118113]
Elastic Security::
For the Elastic Security 8.0.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Fleet::
* Adds `installed_kibana_space_id` to `epm-packages` saved objects {kibana-pull}120517[#120517]
* Handle Saved Object ID changes {kibana-pull}119527[#119527]
* Fixes upgradeable agents filter {kibana-pull}119338[#119338]
Lens & Visualizations::
* Enables normal mode for percentage charts in *Lens* {kibana-pull}120197[#120197]
* Fixes existing fields query for epoch_millis dates in *Lens* {kibana-pull}119508[#119508]
* Include frozen indices in *Lens* {kibana-pull}118555[#118555]
* Fixes focus on legend action popovers in *Lens* {kibana-pull}115066[#115066]
Machine Learning::
* Fixes data view search based on title {kibana-pull}120737[#120737]
* Data frame analytics wizard: Only allow data view creation if job will be started immediately {kibana-pull}120042[#120042]
* Fixes anomaly detection module manifest queries to ignore frozen and cold data tiers {kibana-pull}119635[#119635]
* Catches syntax error in job wizard editor {kibana-pull}119457[#119457]
* Fixes error handling for missing data view in data frame analytics wizard {kibana-pull}119455[#119455]
* Ensures auto refresh interval is used in Data Frame Analytics list {kibana-pull}117959[#117959]
* Ignores frozen indices in data recognizer {kibana-pull}117208[#117208]
Management::
* Fixes data grid column actions button when histogram charts are visible {kibana-pull}120202[#120202]
* Disables delete data view for data frame analytics and transforms wizards {kibana-pull}119732[#119732]
* Check {kib} capabilities for all saving, editing, and deleting {kibana-pull}118480[#118480]
* Adds autocomplete for search_after and pit in search query {kibana-pull}117864[#117864]
* Autocomplete for t_test aggregation {kibana-pull}117782[#117782]
* Disables create data view for data frame analytics and transforms wizards {kibana-pull}117690[#117690]
Maps::
* Fixes an issue where drawings do not show when there is a global filter {kibana-pull}121239[#121239]
* Use minimum symbol size if meta is not loaded {kibana-pull}119119[#119119]
* Do not fail migration when JSON.parse fails {kibana-pull}117342[#117342]
* Do not allow label overlap {kibana-pull}116190[#116190]
Monitoring::
Correct linear regression formula {kibana-pull}120222[#120222]
Observability::
* Renames alerting types in Infra {kibana-pull}121061[#121061]
* Renames occurrences of `alert_type` to `rule_type` in Infra {kibana-pull}120455[#120455]
* Fixes failing alerts table pagination functional tests {kibana-pull}119985[#119985]
* Switch to _source for updating documents instead of fields API {kibana-pull}118245[#118245]
* Fixes an issue where search terms with certain characters caused the APM UI to crash {kibana-pull}118063[#118063]
* Ignore unavailable indices for ML jobs {kibana-pull}117632[#117632]
* Disables the actions button when users have inadequate privileges {kibana-pull}117488[#117488]
* Replaces manual rate calculation with `rate` agg {kibana-pull}115651[#115651]
* Adds migration to fix incorrect action group spelling {kibana-pull}119626[#119626]
* Fixes bug with manage views button {kibana-pull}118547[#118547]
* Disables No Data checkboxes for doc count alerts {kibana-pull}117194[#117194]
* Prevent event propagation on step_duration {kibana-pull}122039[#122039]
* Disables the button to create alerts in Uptime when users do not have permissions to do so {kibana-pull}120379[#120379]
* Fixes a bug that prevented users from saving Uptime configurations when the `inspect` option was turned on {kibana-pull}119142[#119142]
* Adds a callout to informs users that they do not have permissions to create ML jobs for Uptime monitors {kibana-pull}117684[#117684]
Platform::
Fixes font glitches in code editor {kibana-pull}121392[#121392]
Reporting::
Fixes an issue where PDF and PNG reports break on Windows operating systems when the {kib} server hostname is `0.0.0.0` {kibana-pull}117022[#117022]

[[release-notes-8.0.0-beta1]]
== {kib} 8.0.0-beta1

Review the {kib} 8.0.0-beta1 changes, then use the <<upgrade-assistant,Upgrade Assistant>> to complete the upgrade.

[float]
[[breaking-changes-8.0.0-beta1]]
=== Breaking changes

Breaking changes can prevent your application from optimal operation and performance. Review the following breaking changes, then mitigate the impact to your application.

To review the breaking changes in previous versions, refer to the following: 

<<breaking-changes-8.0.0-alpha2,8.0.0-alpha2>> | <<breaking-changes-8.0.0-alpha1,8.0.0-alpha1>>

[float]
[[alerting-breaking-changes-8.0.0-beta1]]
==== Alerting 
      
[discrete]
[[breaking-114558]]
.Removes `xpack.task_manager.index`
[%collapsible]
====
*Details* +
The `xpack.task_manager.index` setting has been removed. For more information, refer to {kibana-pull}114558[#114558].

*Impact* +
Before you upgrade to 8.0.0, remove `xpack.task_manager.index` from kibana.yml.
====

[discrete]
[[breaking-113461]]
.Removes ability to remove plugins
[%collapsible]
====
*Details* +
The `xpack.actions.enabled` setting has been removed. For more information, refer to {kibana-pull}113461[#113461].

*Impact* +
Before you upgrade to 8.0.0, remove `xpack.actions.enabled` from kibana.yml.
====

[float]
[[lens-visualizations-breaking-changes-8.0.0-beta1]]
==== Lens & visualizations

[discrete]
[[breaking-113516]]
.Removes display options from legacy gauge
[%collapsible]
====
*Details* +
The *Display warnings* option has been removed from the aggregation-based gauge visualization. For more information, refer to {kibana-pull}113516[#113516].

*Impact* +
When you create aggregation-based gauge visualizations, the *Display warnings* option is no longer available in *Options > Labels*.
====

[discrete]
[[breaking-112643]]
.Removes settings from visEditors plugins
[%collapsible]
====
*Details* +
The following deprecated visEditors plugin settings have been removed:

* `metric_vis.enabled`
* `table_vis.enabled`
* `tagcloud.enabled`
* `metrics.enabled`
* `metrics.chartResolution`
* `chartResolution`
* `metrics.minimumBucketSize`
* `minimumBucketSize`
* `vega.enabled`
* `vega.enableExternalUrls`
* `vis_type_table.legacyVisEnabled`
* `timelion_vis.enabled`
* `timelion.enabled`
* `timelion.graphiteUrls`
* `timelion.ui.enabled`

For more information, refer to {kibana-pull}112643[#112643].

*Impact* +
Before you upgrade, make the following changes in kibana.yml:

* Replace `metric_vis.enabled` with `vis_type_metric.enabled`
* Replace `table_vis.enabled` with `vis_type_table.enabled`
* Replace `tagcloud.enabled` with `vis_type_tagcloud.enabled`
* Replace `metrics.enabled` with `vis_type_timeseries.enabled`
* Replace `metrics.chartResolution` and `chartResolution` with `vis_type_timeseries.chartResolution`
* Replace `metrics.minimumBucketSize` and `minimumBucketSize` with `vis_type_timeseries.minimumBucketSize`
* Replace `vega.enabled` with `vis_type_vega.enabled`
* Replace `vega.enableExternalUrls` with `vis_type_vega.enableExternalUrls`
* Remove `vis_type_table.legacyVisEnabled`
* Replace `timelion_vis.enabled` with `vis_type_timelion.enabled`
* Replace `timelion.enabled` with `vis_type_timelion.enabled`
* Replace `timelion.graphiteUrls` with `vis_type_timelion.graphiteUrls`
* Remove `timelion.ui.enabled`

====

[discrete]
[[breaking-111704]]
.Removes dimming opacity setting
[%collapsible]
====
*Details* +
The *Dimming opacity* setting in *Advanced Settings* has been removed. For more information, refer to {kibana-pull}111704[#111704].

*Impact* +
When you upgrade to 8.0.0, you are no longer able to configure the dimming opactiy for visualizations. 
====

[discrete]
[[breaking-110985]]
.Removes Less stylesheet support
[%collapsible]
====
*Details* +
In *TSVB*, custom Less stylesheets have been removed. For more information, refer to {kibana-pull}110985[#110985].

*Impact* +
Existing less stylesheets are automatically converted to CSS stylesheets. 
====

[discrete]
[[breaking-110571]]
.Disables the input string mode
[%collapsible]
====
*Details* +
In *TSVB*, the *Index pattern selection mode* option has been removed. For more information, refer to {kibana-pull}110571[#110571].

*Impact* +
To use index patterns and {es} indices in *TSVB* visualizations:

. Open the main menu, then click *Stack Management > Advanced Settings*.

. Select *Allow string indices in TSVB*.

. Click *Save changes*.
====

[float]
[[logs-breaking-changes-8.0.0-beta1]]
==== Logs

[discrete]
[[breaking-115974]]
.Removes deprecated alias config entries
[%collapsible]
====
*Details* +
The deprecated `xpack.infra.sources.default.logAlias` and `xpack.infra.sources.default.logAlias` settings have been removed. For more information, refer to {kibana-pull}115974[#115974].

*Impact* +
Before you upgrade, remove the settings from kibana.yml, then configure the settings in <<logs-app,Logs>>.
====

[discrete]
[[breaking-61302]]
.Removes configurable fields in settings
[%collapsible]
====
*Details* +
The *Logs* and *Metrics* configurable fields settings have been removed. For more information, refer to {kibana-pull}61302[#61302].

*Impact* +
Configure the settings in https://www.elastic.co/guide/en/ecs/current/ecs-reference.html[ECS].
====

[float]
[[machine-learning-breaking-changes-8.0.0-beta1]]
==== Machine learning
      
[discrete]
[[breaking-115444]]
.Grants access to machine learning features when base privileges are used
[%collapsible]
====
*Details* +
Machine learning features are included as base privileges. For more information, refer to {kibana-pull}115444[#115444].

*Impact* +
If you do not want to grant users privileges to machine learning features, update <<xpack-security,*Users* and *Roles*>>.
====

[float]
[[maps-breaking-changes-8.0.0-beta1]]
==== Maps

[discrete]
[[breaking-116184]]
.Removes proxyElasticMapsServiceInMaps
[%collapsible]
====
*Details* +
The `map.proxyElasticMapsServiceInMaps` setting has been removed. For more information, refer to {kibana-pull}116184[#116184].

*Impact* +
Install the on-prem version of the <<maps-connect-to-ems,Elastic Maps Service>>, which is a Docker service that resides in the Elastic Docker registry, in an accessible location on your internal network. When you complete the installation, update kibana.yml to point to the service.
====

[float]
[[operations-breaking-changes-8.0.0-beta1]]
==== Operations 

[discrete]
[[breaking-111535]]
.Removes environment variables
[%collapsible]
====
*Details* +
The `CONFIG_PATH` and `DATA_PATH` environment variables have been removed. For more information, refer to {kibana-pull}111535[#111535].

*Impact* +
Replace the `CONFIG_PATH` environment variable with `KBN_PATH_CONF`, and replace `DATA_PATH` with the `path.data` setting.
====

[float]
[[platform-breaking-changes-8.0.0-beta1]]
==== Platform 
      
[discrete]
[[breaking-114379]]
.Removes supports for csp.rules configuration
[%collapsible]
====
*Details* +
Support for the `csp.rules` configuration property has been removed. For more information, refer to {kibana-pull}114379[#114379].

*Impact* +
Configuring the default `csp.script_src`, `csp.workers_src`, and `csp.style_src` values is not required.
====

[discrete]
[[breaking-113653]]
.Changes and removes deprecated core settings and deprecated settings from core plugins
[%collapsible]
====
*Details* +
The deprecation notice for `server.cors` has changed from `level:critical` to `level:warning`.

The following settings have changed:

* The `xpack.banners.placement` value has been renamed
* The `newsfeed.defaultLanguage` newsfeed item retrieval method and default language has changed

Support for the following configuration settings has been removed:

* `newsfeed.defaultLanguage`
* `cpu.cgroup.path.override`
* `cpuacct.cgroup.path.override`
* `server.xsrf.whitelist`
* `xpack.xpack_main.xpack_api_polling_frequency_millis`
* `KIBANA_PATH_CONF`

For more information, refer to {kibana-pull}113653[#113653].

*Impact* +
* The `header` value provided to the `xpack.banners.placement` configuration has been renamed to 'top'
* The `newsfeed.defaultLanguage` newsfeed items are retrieved based on the browser locale and default to English
* Replace `cpu.cgroup.path.override` with `ops.cGroupOverrides.cpuPath`
* Replace `cpuacct.cgroup.path.override` with `ops.cGroupOverrides.cpuAcctPath`
* Replace `server.xsrf.whitelist` with `server.xsrf.allowlist`
* Replace `xpack.xpack_main.xpack_api_polling_frequency_millis` with `xpack.licensing.api_polling_frequency`
* Replace `KIBANA_PATH_CONF` path to the {kib} configuration file using the `KBN_PATH_CONF` environment variable
====

[discrete]
[[breaking-113495]]
.Removes `enabled` settings from plugins
[%collapsible]
====
*Details* +
Using `{plugin_name}.enabled` to disable plugins has been removed. Some plugins, such as `telemetry`, `newsfeed`, `reporting`, and the various `vis_type` plugins will continue to support this setting. All other {kib} plugins will not support this setting. Any new plugin will support this setting only when specified in the `configSchema`. For more information, refer to {kibana-pull}113495[#113495].

The `xpack.security.enabled` setting has been removed. For more information, refer to {kibana-pull}111681[#111681].

*Impact* +
Before you upgrade to 8.0.0:

* Remove `{plugin_name}.enabled` from kibana.yml. If you use the setting to control user access to {kib} applications, use <<tutorial-secure-access-to-kibana,*Features* controls>> instead.
* Replace `xpack.security.enabled` with {ref}/security-settings.html#general-security-settings[`xpack.security.enabled`] in elasticsearch.yml.
====

[discrete]
[[breaking-113367]]
.Removes `--plugin-dir` cli option
[%collapsible]
====
*Details* +
The `plugins.scanDirs` setting and `--plugin-dir` cli option have been removed. For more information, refer to {kibana-pull}113367[#113367].

*Impact* +
Before you upgrade to 8.0.0, remove `plugins.scanDirs` from kibana.yml.
====

[discrete]
[[breaking-113296]]
.Removes support for `optimize.*` settings
[%collapsible]
====
*Details* +
The legacy `optimize.*` settings have been removed. If your configuration uses the following legacy `optimize.*` settings, {kib} fails to start:

* `optimize.lazy`
* `optimize.lazyPort`
* `optimize.lazyHost`
* `optimize.lazyPrebuild`
* `optimize.lazyProxyTimeout`
* `optimize.enabled`
* `optimize.bundleFilter`
* `optimize.bundleDir`
* `optimize.viewCaching`
* `optimize.watch`
* `optimize.watchPort`
* `optimize.watchHost`
* `optimize.watchPrebuild`
* `optimize.watchProxyTimeout`
* `optimize.useBundleCache`
* `optimize.sourceMaps`
* `optimize.workers`
* `optimize.profile`
* `optimize.validateSyntaxOfNodeModules`

For more information, refer to {kibana-pull}113296[#113296].

*Impact* +
To run the `@kbn/optimizer` separately in development, pass `--no-optimizer` to `yarn start`. For more details, refer to {kibana-pull}73154[#73154]. 
====

[discrete]
[[breaking-113173]]
.Removes `so/server/es` settings
[%collapsible]
====
*Details* +
Some of the `so/server/es` settings have been removed. If your configuration uses the following settings, {kib} fails to start:

* `savedObjects.indexCheckTimeout`
* `server.xsrf.token`
* `elasticsearch.preserveHost`
* `elasticsearch.startupTimeout`

For more information, refer to {kibana-pull}113173[#113173].

*Impact* +
Before you upgrade to 8.0.0., remove these settings from kibana.yml.
====

[discrete]
[[breaking-113068]]
.Adds requirement for inline scripting
[%collapsible]
====
*Details* +
To start {kib}, you must enable inline scripting in {es}. For more information, refer to {kibana-pull}113068[#113068].

*Impact* +
Enable link:https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-scripting-security.html[inline scripting].
====

[discrete]
[[breaking-112773]]
.Removes `kibana.index` settings
[%collapsible]
====
*Details* +
The `kibana.index`, `xpack.reporting.index`, and `xpack.task_manager.index` settings have been removed. For more information, refer to {kibana-pull}112773[#112773].

*Impact* +
Use spaces, cross-cluster replication, or cross-cluster search. To migrate to <<xpack-spaces,spaces>>, export your <<managing-saved-objects, saved objects>> from a tenant into the default space. For more details, refer to link:https://github.com/elastic/kibana/issues/82020[#82020].
====
  
[discrete]
[[breaking-112305]]
.Removes legacy logging
[%collapsible]
====
*Details* +
The logging configuration and log output format has changed. For more information, refer to {kibana-pull}112305[#112305].

*Impact* +
Use the new <<logging-configuration, logging system configuration>>. 
====

[float]
[[reporting-breaking-changes-8.0.0-beta1]]
==== Reporting
      
[discrete]
[[breaking-114216]]
.Removes reporting settings
[%collapsible]
====
*Details* +
The following settings have been removed: 

* `xpack.reporting.capture.concurrency`

* `xpack.reporting.capture.settleTime`

* `xpack.reporting.capture.timeout`

* `xpack.reporting.kibanaApp`

For more information, refer to {kibana-pull}114216[#114216].

*Impact* +
Before you upgrade to 8.0.0, remove the settings from kibana.yml.
====

[float]
[[rest-api-breaking-changes-8.0.0-beta1]]
==== REST API 

[discrete]
[[breaking-114730]]
.Removes `/api/settings`
[%collapsible]
====
*Details* +
The `/api/settings` REST API has been removed. For more information, refer to {kibana-pull}114730[#114730].

*Impact* +
Use `/api/stats`.
====

[float]
[[security-breaking-changes-8.0.0-beta1]]
==== Security

[discrete]
[[breaking-116191]]
.Removes legacy audit logger
[%collapsible]
====
*Details* +
The legacy audit logger has been removed. For more information, refer to {kibana-pull}116191[#116191].

*Impact* +
Audit logs will be written to the default location in the new ECS format. To change the output file, filter events, and more, use the <<audit-logging-settings, audit logging settings>>.
====

[float]
[[deprecations-8.0.0-beta1]]
=== Deprecations

Deprecated functionality does not have an immediate impact on your application, but we strongly recommend you make the necessary updates after you complete the upgrade.

To review the 8.0.0 depcrecations, refer to the <<deprecations-8.0.0-alpha1,8.0.0-alpha1 release notes>>. 
  
[float]
[[features-8.0.0-beta1]]
=== Features
The 8.0.0-beta1 release adds the following new and notable features.

Dashboard::
* Dashboard Integration {kibana-pull}115991[#115991]
Elastic Security::
For the Elastic Security 8.0.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Machine Learning::
* Addition of new Model Management tab {kibana-pull}115772[#115772]
Platform::
* Changes edit view to json read-only view {kibana-pull}112034[#112034]

[float]
[[enhancement-v8.0.0-beta1]]
=== Enhancements

The 8.0.0-beta1 release includes the following enhancements.

Canvas::
* By-Value embeddables {kibana-pull}113827[#113827]
* Toolbar UI updates {kibana-pull}113329[#113329]
Elastic Security::
For the Elastic Security 8.0.0 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Lens & Visualizations::
* Handle removal of deprecated date histogram interval in *Vega* {kibana-pull}109090[#109090]
* Adds value labels to Heatmap in *Lens* {kibana-pull}106406[#106406]
Logs::
* Make Alerts page use shared Kibana time range {kibana-pull}115192[#115192]
Machine Learning::
* Adds support to {fleet} {integrations} for installing ML models {kibana-pull}107710[#107710]
* Adds Index data visualizer grid embeddable as extra view within Discover {kibana-pull}107184[#107184]
Maps::
* Use Elastic Maps Service v8.0 {kibana-pull}116217[#116217]
* Use desaturated map tiles instead of bright map tiles by default {kibana-pull}116179[#116179]
* Use ES mvt {kibana-pull}114553[#114553]
Security::
* Register "minimal" feature privileges regardless of the current license level {kibana-pull}115992[#115992]
Uptime::
* Uptime index config using kibana.yml {kibana-pull}115775[#115775]

[float]
[[fixes-v8.0.0-beta1]]
=== Bug fixes

The 8.0.0-beta1 release includes the following bug fixes.

Management::
* Removes freeze action from Cold phase {kibana-pull}116160[#116160]
* Disallow creating runtime and scripted fields with * in the name {kibana-pull}116119[#116119]
Querying & Filtering::
* Fixes Add filter button doesnt close popup after openning {kibana-pull}111917[#111917]

[[release-notes-8.0.0-alpha2]]
== {kib} 8.0.0-alpha2

Review the {kib} 8.0.0-alpha2 changes, then use the <<upgrade-assistant,Upgrade Assistant>> to complete the upgrade.

[float]
[[breaking-changes-8.0.0-alpha2]]
=== Breaking changes

Breaking changes can prevent your application from optimal operation and performance. Review the following breaking changes, then mitigate the impact to your application.

To review the breaking changes in the previous version, refer to <<breaking-changes-8.0.0-alpha1,8.0.0-alpha1>>.

[discrete]
[[breaking-110830]]
.Changes the `GET /api/status` default behavior
[%collapsible]
====
*Details* +
`GET /api/status` reports a new and more verbose payload. For more information, refer to {kibana-pull}110830[#110830].

*Impact* +
To retrieve the {kib} status in the previous format, use `GET /api/status?v7format=true`.
====
      
[discrete]
[[breaking-110738]]
.Removes support for legacy exports
[%collapsible]
====
*Details* +
In {kib} 8.0.0 and later, the legacy format from {kib} 6.x is unsupported. For more information, refer to {kibana-pull}110738[#110738]

*Impact* +
Using the user interface to import saved objects is restricted to `.ndjson` format imports.
====
      
[discrete]
[[breaking-109896]]
.Removes `map.regionmap.*`
[%collapsible]
====
*Details* +
The deprecated `map.regionmap.*` setting in kibana.yml has been removed. For more information, refer to {kibana-pull}109896[#109896].

*Impact* +
If you have maps that use `map.regionmap` layers:

. Remove the `map.regionmap` layer.

. To recreate the choropleth layer, use <<import-geospatial-data,GeoJSON upload>> to index your static vector data into {es}. 

. Create a choropleth layer from the indexed vector data. 
====
      
[discrete]
[[breaking-109798]]
.Removes `kibana.defaultAppId`
[%collapsible]
====
*Details* +
The deprecated `kibana.defaultAppId` setting in kibana.yml, which is also available as `kibana_legacy.defaultAppId`, has been removed. For more information, refer to {kibana-pull}109798[#109798].

*Impact* +
When you upgrade, remove `kibana.defaultAppId` from your kibana.yml file. To configure the default route for users when they enter a space, use the <<defaultroute,`defaultRoute`>> in *Advanced Settings*.
====
      
[discrete]
[[breaking-109350]]
.Removes `courier:batchSearches`
[%collapsible]
====
*Details* +
The deprecated `courier:batchSearches` setting in *Advanced Settings* has been removed. For more information, refer to {kibana-pull}109350[#109350].

*Impact* +
When you upgrade, the `courier:batchSearches` setting will no longer be available.
====
      
[discrete]
[[breaking-108111]]
.Removes `xpack.task_manager.index`
[%collapsible]
====
*Details* +
The deprecated `xpack.task_manager.index` setting in kibana.yml has been removed. For more information, refer to {kibana-pull}108111[#108111].

*Impact* +
When you upgrade, remove `xpack.task_manager.index` from your kibana.yml file.
====
      
[discrete]
[[breaking-108103]]
.Removes dashboard-only mode
[%collapsible]
====
*Details* +
The legacy dashboard-only mode has been removed. For more information, refer to {kibana-pull}108103[#108103].

*Impact* +
To grant users access to only dashboards, create a new role, then assign only the *Dashboard* feature privilege. For more information, refer to <<kibana-feature-privileges,{kib} privileges>>.
====
     
[discrete]
[[breaking-105979]]
.Removes `xpack.maps.showMapVisualizationTypes`
[%collapsible]
====
*Details* +
The deprecated `xpack.maps.showMapVisualizationTypes` setting in kibana.yml has been removed. For more information, refer to {kibana-pull}105979[#105979]

*Impact* +
When you upgrade, remove `xpack.maps.showMapVisualizationTypes` from your kibana.yml file.
====

[float]
[[deprecations-8.0.0-alpha2]]
=== Deprecations

Deprecated functionality does not have an immediate impact on your application, but we strongly recommend you make the necessary updates after you complete the upgrade.

To review the 8.0.0 depcrecations, refer to the <<deprecations-8.0.0-alpha1,8.0.0-alpha1 release notes>>. 
      
[float]
[[features-8.0.0-alpha2]]
=== Features
The 8.0.0-alpha2 release adds the following new and notable feature.

Security::
* Adds the interactive setup mode {kibana-pull}106881[#106881]
      
[float]
[[enhancement-v8.0.0-alpha2]]
=== Enhancements
The 8.0.0-alpha2 release includes the following enhancements.

Elastic Security::
For the Elastic Security 8.0.0-alpha2 release information, refer to {security-guide}/release-notes.html[_Elastic Security Solution Release Notes_].
Security::
* Interactive setup mode {kibana-pull}106881[#106881]

[[release-notes-8.0.0-alpha1]]
== {kib} 8.0.0-alpha1

Review the {kib} 8.0.0-alpha1 changes, then use the <<upgrade-assistant,Upgrade Assistant>> to complete the upgrade.

[float]
[[breaking-changes-8.0.0-alpha1]]
=== Breaking changes

Breaking changes can prevent your application from optimal operation and performance. Review the breaking changes, then mitigate the impact to your application. 

[float]
[[enterprise-search-change]]
==== Enterprise Search changes

[discrete]
[[breaking-106307]]
.Required security plugin in 8.0
[%collapsible]
====
*Details* +
Enterprise Search now requires that you enable X-Pack Security. For more information, refer to {kibana-pull}106307[#106307]

*Impact* +
Enable X-Pack Security.
====

[float]
[[index-pattern-change]]
==== Index pattern changes

[discrete]
[[breaking-35173]]
.Removed support for time-based interval index patterns
[%collapsible]
====
*Details* +
Time-based interval index patterns were deprecated in 5.x. In 6.x, you could no longer create time-based interval index patterns, but they continued to function as expected. Support for these index patterns has been removed in 8.0. For more information, refer to {kibana-pull}35173[#35173]

*Impact* +
You must migrate your time_based index patterns to a wildcard pattern. For example, logstash-*. 
====

[float]
[[operations-changes]]
==== Operations changes

[discrete]
[[breaking-93835]]
.Removed platform from archive root directory
[%collapsible]
====
*Details* +
After you extract an archive, the output directory no longer includes the target platform. For example, `kibana-8.0.0-linux-aarch64.tar.gz` produces a `kibana-8.0.0` folder. For more information, refer to {kibana-pull}93835[#93835].

*Impact* +
To use the new folder, update the configuration management tools and automation.
====
      
[discrete]
[[breaking-90511]]
.Removed default support for TLS v1.0 and v1.1
[%collapsible]
====
*Details* +
The default support for TLS v1.0 and v1.1 has been removed. For more information, refer to {kibana-pull}90511[#90511].

*Impact* +
To enable support, set `--tls-min-1.0` in the `node.options` configuration file. To locate the configuration file, go to the kibana/config folder or any other configuration with the `KBN_PATH_CONF` environment variable. For example, if you are using a Debian-based system, the configuration file is located in /etc/kibana.
====
           
[discrete]
[[breaking-74424]]
.Removed support for sysv init
[%collapsible]
====
*Details* +
All supported operating systems use systemd service files. Any system that doesn’t have `service` aliased to use kibana.service should use `systemctl start kibana.service` instead of `service start kibana`. For more information, refer to {kibana-pull}74424[#74424].

*Impact* +
If your installation uses .deb or .rpm packages with SysV, migrate to systemd.
====
       
[discrete]
[[breaking-42353]]
.Disabled response logging as a default
[%collapsible]
====
*Details* +
In previous versions, all events are logged in `json` when `logging.json:true`. With the new logging configuration, you can choose the `json` and pattern output formats with layouts. For more information, refer to {kibana-pull}42353[#42353].

*Impact* +
To restore the previous behavior, configure the logging format for each custom appender with the `appender.layout property` in kibana.yml. There is no default for custom appenders, and each appender must be configured expilictly.

[source,yaml]
-------------------
logging:
  appenders:
    custom_console:
      type: console
      layout:
        type: pattern
    custom_json:
      type: console
      layout:
        type: json
  loggers:
    - name: plugins.myPlugin
      appenders: [custom_console]
  root:
    appenders: [default, custom_json]
    level: warn
-------------------
====

[float]
[[reporting-changes-8.0.0-alpha1]]
==== Reporting changes
      
[discrete]
[[breaking-52539]]
.Legacy job parameters are no longer supported
[%collapsible]
====
*Details* +
*Reporting* is no longer compatible with POST URL snippets generated with {kib} 6.2.0 and earlier. For more information, refer to {kibana-pull}52539[#52539]

*Impact* +
If you use POST URL snippets to automatically generate PDF reports, regenerate the POST URL strings.
====

[float]
[[rest-api-changes]]
==== Security changes

[discrete]
[[breaking-47929]]
.Removed `/api/security/v1/saml` route
[%collapsible]
====
*Details* +
The `/api/security/v1/saml` route has been removed and is reflected in the kibana.yml `server.xsrf.whitelist` setting, {es}, and the Identity Provider SAML settings. For more information, refer to {kibana-pull}47929[#47929]

*Impact* +
Use the `/api/security/saml/callback` route, or wait to upgrade to 8.0.0-alpha2 when the `/api/security/saml/callback` route breaking change is reverted. 
====

[discrete]
[[breaking-41700]]
.Reject legacy browsers by default
[%collapsible]
====
*Details* +
To provide the maximum level of protection for most installations, the csp.strict config is now enabled by default. Legacy browsers not supported by Kibana, such as Internet Explorer 11, are unable to access {kib} unless explicitly enabled. All browsers officially supported by Kibana do not have this issue. For more information, refer to {kibana-pull}41700[#41700]

*Impact* +
To enable support for legacy browsers, set `csp.strict: false` in kibana.yml. To effectively enforce the security protocol, we strongly discourage disabling `csp.strict` unless it is critical that you support Internet Explorer 11.
====

[float]
[[settings-changes-8.0.0-alpha1]]
==== Settings changes
      
[discrete]
[[breaking-106061]]
.Use new session timeout defaults 
[%collapsible]
====
*Details* +
The default values for the session timeout `xpack.security.session.{lifespan|idleTimeout}` settings have changed. For more information, refer to {kibana-pull}106061[#106061]

*Impact* +
Use the following default values:

* `xpack.security.session.idleTimeout: 8h`
* `xpack.security.session.lifespan: 30d`
====

[discrete]
[[breaking-87114]]
.Removed support for setting `server.host` to '0'
[%collapsible]
====
*Details* +
Support for configuring {kib} with `0` as the `server.host` has been removed. Please use `0.0.0.0` instead. For more information, refer to {kibana-pull}87114[#87114]

*Impact* +
You are now unable to use `0` as the `server.host`.
====

[discrete]
[[breaking-38657]]
.Removed `xpack.security.public` and `xpack.security.authProviders`
[%collapsible]
====
*Details* +
The `xpack.security.public` and `xpack.security.authProviders` settings have been removed. For more information, refer to {kibana-pull}38657[#38657]

*Impact* +
Use the `xpack.security.authc.saml.realm` and `xpack.security.authc.providers` settings.
====

[discrete]
[[breaking-22696]]
.Removed useUTC deprecation
[%collapsible]
====
*Details* +
The `logging.useUTC` setting has been removed. For more information, refer to {kibana-pull}22696[#22696]

*Impact* +
The default timezone is UTC. To change the timezone, set `logging.timezone: false` in kibana.yml. Change the timezone when the system, such as a docker container, is configured for a nonlocal timezone.  
====  

[discrete]
[[breaking-32049]]
.Removed environment variables `CONFIG_PATH` and `DATA_PATH`
[%collapsible]
====
*Details* +
The environment variables `CONFIG_PATH` and `DATA_PATH` have been removed.  For more information, refer to {kibana-pull}32049[#32049]

*Impact* +
Use the environment variable `KBN_PATH_CONF` instead of `CONFIG_PATH`.  Use the setting `path.data` instead of `DATA_PATH`.
====

[float]
[[deprecations-8.0.0-alpha1]]
=== Deprecations

The following functionality is deprecated in 8.0.0, and will be removed in 9.0.0. Deprecated functionality does not have an immediate impact on your application, but we strongly recommend you make the necessary updates after you complete the upgrade.

[discrete]
[[deprecation-74424]]
.Removed support for SysV init
[%collapsible]
====
*Details* +
Systems that don't have `service` aliased to use kibana.service are unable to use `service start kibana`. For more information, refer to {kibana-pull}74424[#74424]

*Impact* +
If your system doesn't have `service` aliased to use kibana.service, use `systemctl start kibana.service`.
====
      
[discrete]
[[deprecation-33603]]
.Removed `xpack:defaultAdminEmail` setting
[%collapsible]
====
*Details* +
The `xpack:default_admin_email` setting for monitoring use has been removed. For more information, refer to {kibana-pull}33603[#33603]

*Impact* +
Use the `xpack.monitoring.clusterAlertsEmail` in kibana.yml.
====

[float]
[[enhancements-and-bug-fixes-v8.0.0-alpha1]]
=== Bug fix

The 8.0.0-alpha1 release includes the following bug fix.

Operations::
* Moves systemd service to /usr/lib/systemd/system {kibana-pull}83571[#83571]
