[glossary]
[[glossary]]
= Glossary

<<a_glos>> | <<b_glos>> | <<c_glos>> | <<d_glos>> | <<e_glos>> | <<f_glos>> | <<g_glos>> | <<h_glos>> | <<i_glos>> | <<j_glos>> | <<k_glos>> | <<l_glos>> | <<m_glos>> | <<n_glos>> | <<o_glos>> | <<p_glos>> | <<q_glos>> | <<r_glos>> | <<s_glos>> | <<t_glos>> | <<u_glos>> | V | <<w_glos>> | X | Y | Z

[float]
[[a_glos]]
== A

[glossary]
[[glossary-action]] action ::
+
--
// tag::action-def[]
The alert-specific response that occurs when an alert fires. The response is
customizable and can contain a number of alert context variables.
An alert can have multiple actions.
Refer to
{kibana-ref}/action-types.html[Action and connector types].
// end::action-def[]
--

[[glossary-advanced-settings]] Advanced Settings ::
// tag::advanced-settings-def[]
A UI for editing the settings that control the appearance and behavior
(for example, date format, default index) of {kib}. The UI is part of Management.
Refer to {kibana-ref}/advanced-options.html[Advanced Settings].
// end::advanced-settings-def[]

[[glossary-alert]] alert ::
// tag::alert-def[]
A specified set of <<glossary-condition,conditions>>, schedules, and <<glossary-action,actions>> that notifies the user when the conditions are met.
Refer to <<glossary-alerts-and-actions,Alerts and Actions>>.
// end::alert-def[]

[[glossary-alerts-and-actions]] Alerts and Actions ::
// tag::alerts-and-actions-def[]
A UI that provides comprehensive views across alert types and tools. The UI
allows you to manage all your alerts and connector configurations in one
place and view the active alert instances. Alerts and Actions works along side <<glossary-watcher,Watcher>>.
Refer to {kibana-ref}/alerting-getting-started.html[Alerts and Actions].
// end::alerts-and-actions-def[]

[[glossary-annotation]] annotation ::
// tag::annotation-def[]
A way to augment a data display with descriptive domain knowledge.
// end::alerts-annotation-def[]


[[glossary-app]] app ::
// tag::app-def[]
A experience within Kibana that has a user interface and appears in the side navigation. An app may contain UIs,
such as Inspect in Maps, or tabs, such as Metrics Explorer in Metrics.
// end::app-def[]


[float]
[[b_glos]]
== B

[[glossary-basemap]] basemap ::
// tag::basemap-def[]
The background detail necessary to orient the location of a map.
// end::basemap-def[]

[[glossary-blocklist]] block list ::
// tag::blocklist-def[]
A filtering rule that excludes one or more members from a set.
// end::blocklist-def[]

[[glossary-bucket]] bucket ::
// tag::bucket-def[]
In {es}, a set of documents based on a certain criterion.
// end::bucket-def[]

[[glossary-bucket-aggregation]] bucket aggregation::
// tag::bucket-aggregation-def[]
An aggregation that creates buckets of documents. Each bucket is associated with a
criterion (depending on the aggregation type), which determines whether or not a document
in the current context falls into the bucket.
// end::bucket-aggregation-def[]

[float]
[[c_glos]]
== C

[[glossary-canvas]] Canvas ::
// tag::canvas-def[]
An app that enables you to create presentations and infographics that pull live data directly from {es}.
Refer to {kibana-ref}/canvas.html[Canvas].
// end::canvas-def[]

[[glossary-canvas-language]] Canvas expression language::
// tag::ccanvas-language-def[]
A pipeline-based expression language for manipulating and visualizing data.
Includes dozens of functions and other capabilities, such as table transforms,
type casting, and sub-expressions. Supports TinyMath functions for complex math calculations.
Refer to {kibana-ref}/canvas-function-reference.html[Canvas function reference].
// end::canvas-language-def[]


[[glossary-certainty]] certainty ::
// tag::certainty-def[]
Specifies how many documents must contain a pair of terms before it is considered
to be a useful connection in a graph.
// end::certainty-def[]

[[glossary-condition]] condition ::
// tag::condition-def[]
The logic and customizable variables for when an alert should fire.
// end::condition-def[]

[[glossary-connector]] connector ::
// tag::connector-def[]
A configuration UI with a service API, credentials, and
other information that enables integration with an external system (the destination for an action).
Refer to {kibana-ref}/action-types.html[Action and connector types].
// end::connector-def[]

[[glossary-console]] Console ::
// tag::console-def[]
A tool for interacting with the REST API of Elasticsearch.
You can send requests to Elasticsearch, view responses,
view API documentation, and get your request history.
Refer to {kibana-ref}/console-kibana.html[Console].
// end::console-def[]

[float]
[[d_glos]]
== D

[[glossary-dashboard]] dashboard ::
// tag::dashboard-def[]
A collection of panels that contain elements such as
<<glossary-visualization,visualizations>>, <<glossary-saved-search,saved searches>>, and
<<glossary-map,maps>>.
Provides insights into your data from multiple perspectives.
// end::dashboard-def[]

[[glossary-data-source]] data source ::
// tag::data-source-def[]
A file, database, or service that provides the underlying data for a map, Canvas element, or visualization.
// end::data-source-def[]

[[glossary-discover]] Discover ::
// tag::discover-def[]
An app for searching and filtering your data so that you can narrow it down to
the subset of data that you are interested in.
// end::discover-def[]

[[glossary-drilldown]] drilldown ::
// tag::drilldown-def[]
A custom navigation path between apps. Refer to {kibana-ref}/drilldowns.html[Drilldowns].
// end::drilldown-def[]



[float]
[[e_glos]]
== E

[[glossary-edge]] edge ::
// tag::edge-def[]
In a graph, the links (often lines) between nodes that denote a relationship.
The width of the edges represents the strength of the relationship.  Refer to
{kibana-ref}/xpack-graph.html[Graph].
// end::edge-def[]


[[glossary-ems]] Elastic Maps Service (EMS) ::
// tag::ems-def[]
A service that serves basemap tiles, shape files, and other key features
that are essential for visualizing geospatial data.
// end::ems-def[]

[[glossary-element]] element ::
// tag::element-def[]
A <<glossary-canvas,Canvas>> workpad object that enables you to display images, text, and visualizations.
// end::element-def[]


[float]
[[f_glos]]
== F

[[glossary-feature-controls]] Feature Controls ::
// tag::feature-controls-def[]
A UI that enables administrators to customize which features are
available in each <<glossary-space,space>>. You can use Feature Controls
to customize the navigation bar per space and make certain
features available or not within each given space.  Refer to
{kibana-ref}//xpack-spaces.html#spaces-control-feature-visibility[Control feature access].
// end::feature-controls-def[]

[float]
[[g_glos]]
== G

[[glossary-graph]] graph ::
// tag::graph-def[]
A data structure and visualization that shows interconnections between
a set of entities. Each entity is represented by a node. Connections between
nodes are represented by <<glossary-edge,edges>>.
// end::graph-def[]

[[glossary-grok-debugger]] Grok Debugger ::
// tag::grok-debugger-def[]
A tool for building and debugging grok patterns. Grok is good for parsing logs,
such as syslog, Apache, and other webserver logs. Refer to
{kibana-ref}/xpack-grokdebugger.html[Debugging grok expressions].
// end::grok-debugger-def[]



[float]
[[h_glos]]
== H



[float]
[[i_glos]]
== I

[float]
[[j_glos]]
== J

[float]
[[k_glos]]
== K

[[glossary-kql]] {kib} Query Language (KQL) ::
// tag::kql-def[]
The default language for querying in {kib}. The KQL provides
support for scripted fields. Refer to
{kibana-ref}/kuery-query.html[Kibana Query Language].
// end::kql-def[]


[float]
[[l_glos]]
== L

[[glossary-lens]] Lens ::
// tag::lens-def[]
Enables you to quickly build visualizations by dragging and dropping data fields.
Lens makes makes smart visualization suggestions for your data,
allowing for quick switching between visualization types. Refer to
{kibana-ref}/lens.html[Lens].
// end::lens-def[]


[[glossary-lucene]] Lucene query syntax ::
// tag::lucene-def[]
The query syntax for {kib}’s legacy query language. The Lucene query
syntax is available under the options menu in the query bar and from the
<<glossary-advanced-settings,Advanced Settings UI>>.
// end::lucene-def[]

[[glossary-license-management]] License Management ::
// tag::license-management-def[]
A user interface in <<glossary-management,Stack Management>> that allows you to view the status of your license,
start a trial, or install a new license.
// end::license-management-def[]

[float]
[[m_glos]]
== M

[[glossary-map]] map ::
// tag::map-def[]
A representation of geographic data using symbols and labels.
Refer to {kibana-ref}/maps.html[Maps].
// end::map-def[]

[[glossary-metric-aggregation]] metric aggregation ::
// tag::metric-aggregation-def[]
An aggregation that keeps track of and computes metrics over a set of documents.
// end::metric-aggregation-def[]


[float]
[[n_glos]]
== N

[float]
[[o_glos]]
== O

[float]
[[p_glos]]
== P

[[glossary-painless-lab]] Painless Lab ::
// tag::painless-lab-def[]
An interactive code editor that lets you test and debug Painless scripts in real-time.
Refer to {kibana-ref}/painlesslab.html[Painless Lab].
// end::painless-lab-def[]


[[glossary-panel]] panel ::
// tag::panel-def[]
A module in a <<glossary-dashboard,dashboard>> that can contain a
query element or visualization, such as a chart, table, or list.
// end::panel-def[]


[float]
[[q_glos]]
== Q

[[glossary-query-bar]] query bar ::
// tag::query-bar-def[]
A text field that enables you to submit a query expression that specifies what
information you want to retrieve and interact with.
// end::query-bar-def[]

[[glossary-query-profiler]] Query Profiler ::
// tag::query-profiler-def[]
A tool for inspecting and analyzing search queries,
so you can diagnose and debug poorly performing queries.
Refer to {kibana-ref}/xpack-profiler.html[Query Profiler].
// end::query-profiler-def[]



[float]
[[r_glos]]
== R

[float]
[[s_glos]]
== S

[[glossary-saved-object]] saved object ::
// tag::saved-object-def[]
An object that stores data for later use. A saved object can be a
dashboard, visualization, map, index pattern, or Canvas workpad.
// end::saved-object-def[]

[[glossary-saved-search]] saved search ::
// tag::saved-search-def[]
The query text, filters, and time filter that make up a search,
saved for later retrieval and reuse.
// end::saved-search-def[]

[[glossary-scripted-field]] scripted field ::
// tag::scripted-field-def[]
A field that computes data on the fly from the data in {es} indices.
Scripted field data is shown in Discover and used in visualizations.
// end::scripted-field-def[]

[[glossary-shareable]] shareable ::
// tag::shareable-def[]
A Canvas workpad that can be embedded outside of Kibana
(e.g. on an internal wiki or public website) using HTML and JavaScript.
// end::shareable-def[]

[[glossary-space]] space ::
// tag::space-def[]
A place for organizing <<glossary-dashboard,dashboards>>,
<<glossary-visualization,visualizations>>, and other <<glossary-saved-object,saved objects>> by category.
For example, a space might be based on a team, use case, or individual.
// end::space-def[]

[[glossary-feature-space]] Spaces ::
// tag::space-feature-def[]
A feature that allows you to organize your saved objects into meaningful categories. Refer to
{kibana-ref}/xpack-spaces.html[Spaces].
// end::space-feature-def[]

[[glossary-stack-monitoring]] Stack Monitoring ::
// tag::stack-monitoring-def[]
Features that enable you to monitor the Elastic Stack, including health and
performance data for {es}, Logstash, and Beats. You can also monitor {kib}
and route that data to the monitoring cluster. Refer to
{kibana-ref}/xpack-monitoring.html[Stack Monitoring].
// end::stack-monitoring-def[]

[[glossary-management]] Stack Management ::
// tag::management-def[]
The home for managing the Elastic Stack — indices, clusters, licenses, UI settings,
index patterns, spaces, and more.  Refer to
{kibana-ref}/management.html[Stack Management].
// end::management-def[]


[float]
[[t_glos]]
== T

[[glossary-term-join]] term join ::
// tag::term-join-def[]
A shared key that combines vector features with the results of an
{es} terms aggregation. Term joins augment vector features with
properties for data-driven styling and rich tooltip content in maps.
// end::term-join-def[]

[[glossary-time-filter]] time filter ::
// tag::time-filter-def[]
A control that constrains the search results to a particular time period.
// end::time-filter-def[]

[[glossary-timelion]] Timelion ::
// tag::timelion-def[]
A tool for building a time series visualization that analyzes data in time order.
Refer to {kibana-ref}/timelion.html[Timelion].
// end::timelion-def[]


[[glossary-time-series-data]] time series data ::
// tag::time-series-data-def[]
A series of data indexed in time order.
// end::time-series-data-def[]


[[glossary-TSVB-data]] TSVB ::
// tag::TSVB-def[]
A time series data visualizer that allows you to combine an
infinite number of aggregations to display complex data.
Refer to {kibana-ref}/TSVB.html[TSVB].
// end::TSVB-def[]


[float]
[[u_glos]]
== U

[[glossary-upgrade-assistant]] Upgrade Assistant ::
// tag::upgrade-assistant-def[]
A feature that helps prepare you for an upgrade to the next major version of
{es}. The assistant identifies the deprecated settings in your cluster and
indices and guides you through resolving issues, including reindexing. Refer to
{kibana-ref}/upgrade-assistant.html[Upgrade Assistant].
// end::upgrade-assistant-def[]


[float]
[[v_glos]]
== V

[[glossary-vega]] Vega ::
// tag::vega-def[]
A declarative language used to create interactive visualizations.
Refer to {kibana-ref}/vega-graph.html[Vega].
// end::vega-def[]

[[glossary-vector]] vector ::
// tag::vector-def[]
Points, lines, and polygons used to represent a map.
// end::vector-def[]

[[glossary-visualization]] visualization ::
// tag::visualization-def[]
A graphical representation of query results (e.g., a histogram, line graph, pie chart, or heat map).
// end::visualization-def[]

[float]
[[w_glos]]
== W

[[glossary-watcher]] Watcher ::
// tag::watcher-def[]
The original suite of alerting features.
Refer to
{kibana-ref}/watcher-ui.html[Watcher].
// end::watcher-def[]

[[glossary-workpad]] workpad ::
// tag::workpad-def[]
A workspace where you build presentations of your live data in <<glossary-canvas,Canvas>>.
Refer to
{kibana-ref}/create-canvas-workpad.html[Create a workpad].
// end::workpad-def[]
