[role="exclude",id="redirects"]
= Deleted pages

[partintro]
--

The following pages have moved or been deleted.

--
[role="exclude",id="monitoring-xpack-kibana"]
== Configuring monitoring in {kib}

See <<monitoring-kibana>>.


[role="exclude",id="settings-xpack-kb"]
== {xpack} Settings in {kib}

include::{asciidoc-dir}/../../shared/settings.asciidoc[]

For more {kib} configuration settings, see <<settings>>.

[role="exclude",id="uptime-security"]
== Uptime security

This page has moved. Please see the new section in the {heartbeat-ref}/securing-heartbeat.html[Uptime Monitoring Guide].

[role="exclude",id="infra-read-only-access"]
== Configure source read-only access

This page has moved. Please see {observability-guide}/configure-settings.html[configure settings].

[role="exclude",id="logs-read-only-access"]
== Configure source read-only access

This page has moved. Please see {observability-guide}/configure-data-sources.html[configure data sources].

[role="exclude",id="extend"]
== Extend your use case

This page was deleted. See <<xpack-graph>> and <<xpack-ml>>.

[role="exclude",id="xpack-dashboard-only-mode"]
== Dashboard-only mode

Using the `kibana_dashboard_only_user` role is deprecated.
Use <<kibana-feature-privileges,feature privileges>> instead.

[role="exclude",id="pdf-layout-modes"]
== PDF layout modes

This page has moved. Please see <<reporting-getting-started>>.

[role="exclude",id="xpack-reporting"]
== Reporting from Kibana

This page has moved. Please see <<reporting-getting-started>>.

[role="exclude",id="add-sample-data"]
== Add sample data

This page has moved. Please see <<get-started>>.

[role="exclude",id="tilemap"]
== Coordinate map

This page has moved. Please see <<maps>>.

[role="exclude",id="visualize-maps"]
== Maps

This page has moved. Please see <<maps>>.

[role="exclude",id="development-embedding-visualizations"]
== Embedding Visualizations

This page was deleted. See <<development-visualize-index>>.

[role="exclude",id="development-create-visualization"]
== Developing Visualizations

This page was deleted. See <<development-visualize-index>>.

[role="exclude",id="errors-alerts-with-watcher"]
== Error reports with Watcher

deprecated::[7.9.0]

Watcher error reports have been removed and replaced with Kibana's <<apm-alerts,alerting and actions>> feature.
To create error alerts with new tool, select **Alerts** - **Create threshold alert** - **Error rate**.

More information on this new feature is available in <<apm-alerts>>.

[role="exclude",id="development-security-rbac"]
== Role-based access control

This content has moved to the <<development-rbac, Security>> page.

[role="exclude",id="managing-cross-cluster-replication"]
== Cross-Cluster Replication

This content has moved. See
{ref}/ccr-getting-started.html[Set up cross-cluster replication].

[role="exclude",id="working-remote-clusters"]
== Remote clusters

This content has moved. See
{ref}/ccr-getting-started.html#ccr-getting-started-remote-cluster[Connect to a remote cluster].

[role="exclude",id="adding-policy-to-index"]
== Adding a policy to an index

This content has moved. See
{ref}/set-up-lifecycle-policy.html[Configure a lifecycle policy].

[role="exclude",id="creating-index-lifecycle-policies"]
== Creating an index lifecycle policy

This content has moved. See
{ref}/set-up-lifecycle-policy.html[Configure a lifecycle policy].

[role="exclude",id="index-lifecycle-policies"]
== Index Lifecycle Policies

This content has moved. See
{ref}/index-lifecycle-management.html[ILM: Manage the index lifecycle].

[role="exclude",id="managing-index-lifecycle-policies"]
== Managing index lifecycle policies

This content has moved. See
{ref}/index-lifecycle-management.html[ILM: Manage the index lifecycle].

[role="exclude",id="tutorial-define-index"]
== Define your index patterns

This content has moved. See
<<get-started, Quick start>>.

[role="exclude",id="managing-indices"]
== Index management

This content has moved. See {ref}/index-mgmt.html[Index management].

[role="exclude",id="field-filter"]
== Filter by field

This content has moved. See <<discover, **Discover**>>.

[role="exclude",id="document-context"]
== View a document in context

This content has moved. See <<discover, **Discover**>>.

[role="exclude",id="document-data"]
== View document data

This content has moved. See <<discover, **Discover**>>.

[role="exclude",id="viewing-field-stats"]
== View field data statistics

This content has moved. See <<discover, **Discover**>>.

[role="exclude",id="known-plugins"]
== Known plugins

This content has moved. See <<known-kibana-plugins>>.

[role="exclude",id="url-drilldown"]
== URL drilldown

[float]
[[trigger-picker]]
=== Picking a trigger for a URL drilldown

This page has moved. Refer to <<url-drilldowns>>.

[float]
[[templating]]
=== URL templating

This page has moved. Refer to <<url_templating-language>>.

[float]
[[variables]]
=== Variables

This page has moved. Refer to <<url-template-variables>>.

[float]
[[time-series-visual-builder]]
=== Time Series Visual Builder

This page was deleted. Refer to <<dashboard>>.

[float]
[[kibana-keystore-has-moved-from-the-data-folder-to-the-config-folder]]
=== Kibana Keystore has moved from the Data Folder to the Config Folder

This page has been deleted. Refer to link:https://www.elastic.co/guide/en/kibana/7.9/breaking-changes-7.9.html#user-facing-changes-79[Breaking changes in 7.9].

[float]
[[createvis]]
=== Create Visualization

This page has been deleted. Refer to <<dashboard>>.

[float]
[[data-table]]
=== Data Table

This page has been deleted. Refer to <<dashboard>>.


[float]
[[xy-chart]]
=== Line, Area, and Bar Chart

This page has been deleted. Refer to <<dashboard>>.

[float]
[[add-canvas-events]]
=== Add Canvas Elements

This page has been moved. Refer to <<canvas>>.

[float]
[[vega-lite-tutorial]]
=== Vega-Lite Tutorial

This page has been moved. Refer to <<vega-tutorial-create-a-stacked-area-chart>>.

[float]
[[heatmap-chart]]
=== Heatmap Chart

This page has been moved. Refer to <<types-of-visualizations>>.

[float]
[[interface-overview]]
=== Interface Overview

This page has been moved. Refer to <<dashboard>>.

[float]
[[time-series-visualizations]]
=== Featured Visualizations

This page has been moved. Refer to <<dashboard>>.

[float]
[[timelion-customize]]
=== Customize and format visualizations

This page has been moved. Refer to <<dashboard>>.

[float]
[[dashboard-drilldown]]
=== Dashboard Drilldowns

This page has been moved. Refer to <<dashboard-drilldowns>>.

[float]
[[development-plugin-localization]]
=== Localization for plugins

This page has been moved. PRefer to <<external-plugin-localization>>.

[role="exclude",id="visualize"]
== Visualize

This content has moved. Refer to <<dashboard, **Dashboard**>>.

[role="exclude",id="explore-dashboard-data"]
This content has moved. Refer to <<dashboard, **Dashboard**>>.

[role="exclude",id="ingest-node-pipelines"]
== Ingest Node Pipelines

This content has moved. See {ref}/ingest.html[Ingest pipelines].


[role="exclude",id="create-panels-with-timelion"]
== Timelion

This content has moved. refer to <<timelion>>.


[role="exclude",id="space-rbac-tutorial"]
== Tutorial: Use role-based access control to customize Kibana spaces

This content has moved. refer to <<tutorial-secure-access-to-kibana>>.

[role="exclude",id="search"]
== Search your data

This content has moved. refer to <<kuery-query>>.

[role="exclude",id="discover-document-context"]
== View surrounding documents

This content has moved. refer to <<discover-view-surrounding-documents>>.
