[role="exclude",id="redirects"]
= Deleted pages

[partintro]
--

The following pages have moved or been deleted.

--
[role="exclude",id="monitoring-xpack-kibana"]
== Configuring monitoring in {kib}

See <<monitoring-kibana>>.


[role="exclude",id="settings-xpack-kb"]
== {xpack} Settings in {kib}

include::{asciidoc-dir}/../../shared/settings.asciidoc[]

For more {kib} configuration settings, see <<settings>>.

[role="exclude",id="uptime-security"]
== Uptime security

This page has moved. Please see the new section in the {uptime-guide}/uptime-security.html[Uptime Monitoring Guide].

[role="exclude",id="infra-read-only-access"]
== Configure source read-only access

This page has moved. Please see <<infra-configure-source>>.

[role="exclude",id="logs-read-only-access"]
== Configure source read-only access

This page has moved. Please see <<xpack-logs-configuring>>.

[role="exclude",id="creating-df-kib"]
== Creating {transforms}

This page is deleted. Please see
{stack-ov}/ecommerce-dataframes.html[Transforming the eCommerce sample data].

[role="exclude",id="ml-jobs"]
== Creating {anomaly-jobs}

This page has moved. Please see {stack-ov}/ml-jobs.html[Creating {anomaly-jobs}].

[role="exclude",id="job-tips"]
== Machine learning job tips

This page has moved. Please see {stack-ov}/job-tips.html[Machine learning job tips].
