[role="exclude",id="redirects"]
= Deleted pages

[partintro]
--

The following pages have moved or been deleted.

--
[role="exclude",id="explain-log-rate-spikes"]
== Explain log rate spikes
Refer to <<log-rate-analysis>>.

[role="exclude",id="snapshot-repositories"]
== Snapshot and Restore
Refer to {ref}/snapshot-restore.html[Snapshot and Restore].

[role="exclude",id="snapshot-restore-tutorial"]
== Tutorial: Snapshot and Restore
Refer to {ref}/snapshot-restore.html[Snapshot and Restore].

[role="exclude",id="configuring-tls-communication"]
== Encrypt communications in {kib}
Refer to <<using-kibana-with-security,Configure security in {kib}>>.

[role="exclude",id="configuring-tls"]
== Encrypt TLS communications in {kib}
Refer to {ref}/security-basic-setup-https.html#encrypt-kibana-http[Encrypt HTTP client communications for {kib}].

[float]
[role="exclude",id="configuring-tls-browser-kib"]
=== Encrypt traffic between the browser and {kib}

Refer to {ref}/security-basic-setup-https.html#encrypt-kibana-browser[Encrypt traffic between your browser and {kib}].

[float]
[role="exclude",id="configuring-tls-kib-es"]
=== Encrypt traffic between {kib} and {es}

Refer to {ref}/security-basic-setup-https.html#encrypt-kibana-elasticsearch[Encrypt traffic between {kib} and {es}].

[role="exclude",id="monitoring-xpack-kibana"]
== Configuring monitoring in {kib}

See <<monitoring-kibana>>.


[role="exclude",id="uptime-security"]
== Uptime security

This page has moved. Please see the new section in the {heartbeat-ref}/securing-heartbeat.html[Uptime Monitoring Guide].

[role="exclude",id="infra-read-only-access"]
== Configure source read-only access

This page has moved. Please see {observability-guide}/configure-settings.html[configure settings].

[role="exclude",id="logs-read-only-access"]
== Configure source read-only access

This page has moved. Please see {observability-guide}/configure-data-sources.html[configure data sources].

[role="exclude",id="extend"]
== Extend your use case

This page was deleted. See <<xpack-graph>> and <<xpack-ml>>.

[role="exclude",id="xpack-dashboard-only-mode"]
== Dashboard-only mode

Using the `kibana_dashboard_only_user` role is deprecated.
Use <<kibana-feature-privileges,feature privileges>> instead.

[role="exclude",id="pdf-layout-modes"]
== PDF layout modes

This page has moved. Please see <<reporting-getting-started>>.

[role="exclude",id="xpack-reporting"]
== Reporting from Kibana

This page has moved. Please see <<reporting-getting-started>>.

[role="exclude",id="add-sample-data"]
== Add sample data

This page has moved. Please see <<get-started>>.

[role="exclude",id="tilemap"]
== Coordinate map

This page has moved. Please see <<maps>>.

[role="exclude",id="visualize-maps"]
== Maps

This page has moved. Please see <<maps>>.

[role="exclude",id="development-embedding-visualizations"]
== Embedding Visualizations

This page was deleted. See <<development-visualize-index>>.

[role="exclude",id="development-create-visualization"]
== Developing Visualizations

This page was deleted. See <<development-visualize-index>>.

[role="exclude",id="errors-alerts-with-watcher"]
== Error reports with Watcher

deprecated::[7.9.0]

// Watcher error reports have been removed and replaced with Kibana's <<apm-alerts,alerting and actions>> feature.
// To create error alerts with new tool, select **Alerts** - **Create threshold alert** - **Error rate**.

// More information on this new feature is available in <<apm-alerts>>.

[role="exclude",id="development-security-rbac"]
== Role-based access control

This content has moved to the <<development-rbac, Security>> page.

[role="exclude",id="managing-cross-cluster-replication"]
== Cross-Cluster Replication

This content has moved. See
{ref}/ccr-getting-started.html[Set up cross-cluster replication].

[role="exclude",id="working-remote-clusters"]
== Remote clusters

This content has moved. See
{ref}/ccr-getting-started.html#ccr-getting-started-remote-cluster[Connect to a remote cluster].

[role="exclude",id="adding-policy-to-index"]
== Adding a policy to an index

This content has moved. See
{ref}/set-up-lifecycle-policy.html[Configure a lifecycle policy].

[role="exclude",id="creating-index-lifecycle-policies"]
== Creating an index lifecycle policy

This content has moved. See
{ref}/set-up-lifecycle-policy.html[Configure a lifecycle policy].

[role="exclude",id="index-lifecycle-policies"]
== Index Lifecycle Policies

This content has moved. See
{ref}/index-lifecycle-management.html[ILM: Manage the index lifecycle].

[role="exclude",id="managing-index-lifecycle-policies"]
== Managing index lifecycle policies

This content has moved. See
{ref}/index-lifecycle-management.html[ILM: Manage the index lifecycle].

[role="exclude",id="tutorial-define-index"]
== Define your index patterns

This content has moved. See
<<get-started, Quick start>>.

[role="exclude",id="managing-indices"]
== Index management

This content has moved. See {ref}/index-mgmt.html[Index management].

[role="exclude",id="field-filter"]
== Filter by field

This content has moved. See <<discover, **Discover**>>.

[role="exclude",id="document-context"]
== View a document in context

This content has moved. See <<discover, **Discover**>>.

[role="exclude",id="document-data"]
== View document data

This content has moved. See <<discover, **Discover**>>.

[role="exclude",id="viewing-field-stats"]
== View field data statistics

This content has moved. See <<discover, **Discover**>>.

[role="exclude",id="known-plugins"]
== Known plugins

This content has moved. See <<known-kibana-plugins>>.

[role="exclude",id="url-drilldown"]
== URL drilldown

[float]
[[trigger-picker]]
=== Picking a trigger for a URL drilldown

This page has moved. Refer to <<create-url-drilldowns>>.

[float]
[[templating]]
=== URL templating

This page has moved. Refer to <<url-templating-language>>.

[float]
[[variables]]
=== Variables

This page has moved. Refer to <<url-template-variable>>.

[float]
[[time-series-visual-builder]]
=== Time Series Visual Builder

This page was deleted. Refer to <<dashboard>>.

[float]
[[kibana-keystore-has-moved-from-the-data-folder-to-the-config-folder]]
=== Kibana Keystore has moved from the Data Folder to the Config Folder

This page has been deleted. Refer to link:https://www.elastic.co/guide/en/kibana/7.9/breaking-changes-7.9.html#user-facing-changes-79[Breaking changes in 7.9].

[float]
[[createvis]]
=== Create Visualization

This page has been deleted. Refer to <<dashboard>>.

[float]
[[data-table]]
=== Data Table

This page has been deleted. Refer to <<dashboard>>.


[float]
[[xy-chart]]
=== Line, Area, and Bar Chart

This page has been deleted. Refer to <<dashboard>>.

[float]
[[add-canvas-events]]
=== Add Canvas Elements

This page has been moved. Refer to <<canvas>>.

[float]
[[vega-lite-tutorial]]
=== Vega-Lite Tutorial

This page has been moved. Refer to <<vega-tutorial-create-a-stacked-area-chart>>.

[float]
[[heatmap-chart]]
=== Heatmap Chart

This page has been moved. Refer to <<types-of-visualizations>>.

[float]
[[interface-overview]]
=== Interface Overview

This page has been moved. Refer to <<dashboard>>.

[float]
[[time-series-visualizations]]
=== Featured Visualizations

This page has been moved. Refer to <<dashboard>>.

[float]
[[timelion-customize]]
=== Customize and format visualizations

This page has been moved. Refer to <<dashboard>>.

[float]
[[dashboard-drilldown]]
=== Dashboard Drilldowns

This page has been moved. Refer to <<dashboard-drilldowns>>.

[float]
[[development-plugin-localization]]
=== Localization for plugins

This page has been moved. Refer to <<external-plugin-localization>>.

[role="exclude",id="visualize"]
== Visualize

This content has moved. Refer to <<dashboard, **Dashboard**>>.

[role="exclude",id="explore-dashboard-data"]
This content has moved. Refer to <<dashboard, **Dashboard**>>.

[role="exclude",id="ingest-node-pipelines"]
== Ingest Pipelines

This content has moved. Refer to {ref}/ingest.html[Ingest pipelines].


[role="exclude",id="create-panels-with-timelion"]
== Timelion

This content has moved. Refer to <<timelion>>.


[role="exclude",id="space-rbac-tutorial"]
== Tutorial: Use role-based access control to customize Kibana spaces

This content has moved. Refer to <<tutorial-secure-access-to-kibana>>.

[role="exclude",id="search"]
== Search your data

This content has moved. Refer to <<kuery-query>>.

[role="exclude",id="discover-document-context"]
== View surrounding documents

This content has moved. Refer to <<document-explorer>>.

[role="exclude",id="field-formatters-string"]
== String field formatters

This content has moved. Refer to <<string-field-formatters>>.

[role="exclude",id="embedding"]
== Embed {kib} content in a web page

This content has moved. Refer to <<embedded-content-authentication>> and <<embed-code>>.

[role="exclude",id="reporting-troubleshooting-system-dependencies"]
== System dependencies

This content has moved. Refer to <<install-reporting-packages>>.

[role="exclude",id="graph-getting-started"]
== Create a graph

This content has moved. Refer to <<xpack-graph>>.

[role="exclude",id="graph-limitations"]
== Graph limitations

This content has moved. Refer to <<graph-troubleshooting>>.

[role="exclude",id="profiler-getting-started"]
== Getting start with Search Profiler

This content has moved. Refer to <<xpack-profiler>>.

[role="exclude",id="profiler-complicated"]
== Profiling a more complicated querying

This content has moved. Refer to <<xpack-profiler>>.

[role="exclude",id="profiler-render"]
== Rendering pre-captured profiler JSON

This content has moved. Refer to <<xpack-profiler>>.

[role="exclude",id="index-patterns"]
== Index patterns has been renamed to data views.

This content has moved. Refer to <<data-views>>.

[role="exclude",id="managing-index-patterns"]
== Index patterns has been renamed to data views.

This content has moved. Refer to <<managing-data-views>>.

[role="exclude",id="xpack-kibana-role-management"]
== Kibana role management.

This content has moved. Refer to <<kibana-role-management>>.

[role="exclude",id="upgrade-migrations"]
== Upgrade migrations

This content has moved. Refer to <<saved-object-migrations>>.

[role="exclude",id="upgrade-standard"]
== Standard Upgrade

This content has moved. Refer to {stack-ref}/upgrading-kibana.html[Upgrade Kibana].

[role="exclude",id="brew"]
== Install {kib} on macOS with Homebrew

This page has been deleted. Refer to <<install>>.

[role="exclude",id="discover-view-document"]
== View a document

This page has been deleted. Refer to <<document-explorer>>.

[role="exclude",id="advanced-osquery"]
== Advanced Osquery

This page has been deleted. Refer to <<osquery>>.

[role="exclude",id="ml-sync"]
== Sync machine learning objects API

This page has been deleted. Refer to <<machine-learning-api-sync>>.

[role="exclude",id="managing-alerts-and-actions"]
== Alerts and Actions

This page has been deleted. Refer to <<alerting-getting-started>>.

[role="exclude",id="enhancements-and-bug-fixes-v8.10.0"]
== Enhancements and bug fixes for 8.10.0

This content has moved. Refer to <<enhancements-and-bug-fixes-v8.10.0-revised>> for 8.10.0.

[role="exclude",id="gen-ai-action-type"]
== Generative AI connector and action

This connector was renamed. Refer to <<openai-action-type>>.

[role="exclude",id="apis"]
== APIs

For the most up-to-date API details, refer to the
{kib-repo}/tree/{branch}/x-pack/plugins/alerting/docs/openapi[alerting], {kib-repo}/tree/{branch}/x-pack/plugins/cases/docs/openapi[cases], {kib-repo}/tree/{branch}/x-pack/plugins/actions/docs/openapi[connectors], and {kib-repo}/tree/{branch}/x-pack/plugins/ml/common/openapi[machine learning] open API specifications.

[role="exclude",id="add-case-connectors"]
== Add connectors to cases

This content has moved. Refer to <<manage-cases-settings>>.

[role="exclude", id="create-drilldowns"]
== Create drilldowns

[[url-drilldowns]]
[[url_templating-language]]
[[url-template-variables]]
This content has moved. Refer to <<drilldowns>>.

[role="exclude", id="tsvb"]
== TSVB

[[tsvb-index-pattern-mode]]
This content has moved. Refer to <<tsvb-panel>>.

////
APM redirects
////

:apm-docs-move-notice: This documentation has moved to the {observability-guide}/apm.html[Observability guide] as of version 8.14.

[role="exclude",id="xpack-apm"]
== APM

{apm-docs-move-notice}

Refer to {observability-guide}/apm-ui.html[the APM UI documentation].

[role="exclude",id="apm-ui"]
== Set up

{apm-docs-move-notice}

Refer to {observability-guide}/apm-ui.html[the APM UI documentation].

[role="exclude",id="apm-getting-started"]
== Get started

{apm-docs-move-notice}

Refer to {observability-guide}/apm.html[the APM UI documentation].

[role="exclude",id="services"]
== Services

{apm-docs-move-notice}

Refer to {observability-guide}/apm-services.html[Services].

[role="exclude",id="traces"]
== Traces

{apm-docs-move-notice}

Refer to {observability-guide}/apm-traces.html[Traces].

[role="exclude",id="dependencies"]
== Dependencies

{apm-docs-move-notice}

Refer to {observability-guide}/apm-dependencies.html[Dependencies].

[role="exclude",id="service-maps"]
== Service Map

{apm-docs-move-notice}

Refer to {observability-guide}/apm-service-maps.html[Service Map].

[float]
[[service-maps-supported]]
=== Supported APM agents

Refer to {observability-guide}/apm-service-maps.html#service-maps-supported[Supported APM agents].

[role="exclude",id="service-overview"]
== Service overview

{apm-docs-move-notice}

Refer to {observability-guide}/apm-service-overview.html[Service overview].

[float]
[[service-span-duration]]
=== Span types average duration and dependencies

Refer to {observability-guide}/apm-service-overview.html#service-span-duration[Service overview].

[role="exclude",id="mobile-service-overview"]
== Mobile service overview

{apm-docs-move-notice}

Refer to {observability-guide}/apm-mobile-service-overview.html[Mobile service overview].

[role="exclude",id="transactions"]
== Transactions

{apm-docs-move-notice}

Refer to {observability-guide}/apm-transactions.html[Transactions].

[role="exclude",id="spans"]
== Trace sample timeline

{apm-docs-move-notice}

Refer to {observability-guide}/apm-spans.html[Trace sample timeline].

[role="exclude",id="errors"]
== Errors

{apm-docs-move-notice}

Refer to {observability-guide}/apm-errors.html[Errors].

[role="exclude",id="metrics"]
== Metrics

{apm-docs-move-notice}

Refer to {observability-guide}/apm-metrics.html[Metrics].

[role="exclude",id="infrastructure"]
== Infrastructure

{apm-docs-move-notice}

Refer to {observability-guide}/apm-infrastructure.html[Infrastructure].

[role="exclude",id="logs"]
== Logs

{apm-docs-move-notice}

Refer to {observability-guide}/apm-logs.html[Logs].

[role="exclude",id="apm-how-to"]
== How-to guides

{apm-docs-move-notice}

Refer to {observability-guide}/apm-how-to-guides.html[How-to guides].

[role="exclude",id="agent-configuration"]
== Configure APM agents with central config

{apm-docs-move-notice}

Refer to {observability-guide}/apm-agent-configuration.html[Configure APM agents with central config].

[role="exclude",id="apm-spaces"]
== Control access to APM data

{apm-docs-move-notice}

Refer to {observability-guide}/apm-spaces.html[Control access to APM data].

[role="exclude",id="apm-alerts"]
== Create an alert

{apm-docs-move-notice}

Refer to {observability-guide}/apm-alerts.html[Create an alert].

[role="exclude",id="custom-links"]
== Create custom links

{apm-docs-move-notice}

Refer to {observability-guide}/apm-custom-links.html[Create custom links].

[role="exclude",id="filters"]
== Filter data

{apm-docs-move-notice}

Refer to {observability-guide}/apm-filters.html[Filter data].

[float]
[[environment-selector]]
=== Service environment filter

Refer to {observability-guide}/apm-filters.html#environment-selector[Filter data].

[role="exclude",id="correlations"]
== Find transaction latency and failure correlations

{apm-docs-move-notice}

Refer to {observability-guide}/apm-correlations.html[Find transaction latency and failure correlations].

[role="exclude",id="agent-explorer"]
== Identify deployment details for APM agents

{apm-docs-move-notice}

Refer to {observability-guide}/apm-agent-explorer.html[Identify deployment details for APM agents].

[role="exclude",id="machine-learning-integration"]
== Integrate with machine learning

{apm-docs-move-notice}

Refer to {observability-guide}/apm-machine-learning-integration.html[Integrate with machine learning].

[role="exclude",id="mobile-session-explorer"]
== Exploring mobile sessions with Discover

{apm-docs-move-notice}

Refer to {observability-guide}/apm-mobile-session-explorer.html[Exploring mobile sessions with Discover].

[role="exclude",id="_viewing_sessions_with_discover"]
== Viewing sessions with Discover

{apm-docs-move-notice}

Refer to {observability-guide}/apm-mobile-session-explorer.html#viewing-sessions-with-discover[Viewing sessions with Discover].

[role="exclude",id="apm-lambda"]
== Observe Lambda functions

{apm-docs-move-notice}

Refer to {observability-guide}/apm-lambda.html[Observe Lambda functions].

[role="exclude",id="advanced-queries"]
== Query your data

{apm-docs-move-notice}

Refer to {observability-guide}/apm-advanced-queries.html[Query your data].

[role="exclude",id="storage-explorer"]
== Storage Explorer

{apm-docs-move-notice}

Refer to {observability-guide}/apm-storage-explorer.html[Storage Explorer].

[role="exclude",id="transactions-annotations"]
== Track deployments with annotations

{apm-docs-move-notice}

Refer to {observability-guide}/apm-transactions-annotations.html[Track deployments with annotations].

[role="exclude",id="apm-app-users"]
== Users and privileges

{apm-docs-move-notice}

Refer to {observability-guide}/apm-app-users.html[Users and privileges].

[role="exclude",id="apm-app-reader"]
== Create an APM reader user

{apm-docs-move-notice}

Refer to {observability-guide}/apm-app-reader.html[Create an APM reader user].

[role="exclude",id="apm-app-annotation-user-create"]
== Create an annotation user

{apm-docs-move-notice}

Refer to {observability-guide}/apm-app-annotation-user-create.html[Create an annotation user].

[role="exclude",id="apm-app-central-config-user"]
== Create a central config user

{apm-docs-move-notice}

Refer to {observability-guide}/apm-app-central-config-user.html[Create a central config user].

[role="exclude",id="apm-app-storage-explorer-user-create"]
== Create a storage explorer user

{apm-docs-move-notice}

Refer to {observability-guide}/apm-app-storage-explorer-user-create.html[Create a storage explorer user].

[role="exclude",id="apm-app-api-user"]
== Create an API user

{apm-docs-move-notice}

Refer to {observability-guide}/apm-app-api-user.html[Create an API user].

[role="exclude",id="apm-settings-in-kibana"]
== Settings

{apm-docs-move-notice}

Refer to {observability-guide}/apm-settings-in-kibana.html[Settings].

[role="exclude",id="apm-api"]
== REST API

{apm-docs-move-notice}

Refer to {observability-guide}/apm-api.html[REST API].

[role="exclude",id="agent-config-api"]
== Agent Configuration API

{apm-docs-move-notice}

Refer to {observability-guide}/apm-agent-config-api.html[Agent Configuration API].

[role="exclude",id="apm-annotation-api"]
== Annotation API

{apm-docs-move-notice}

Refer to {observability-guide}/apm-annotation-api.html[Annotation API].

[role="exclude",id="rum-sourcemap-api"]
== RUM source map API

{apm-docs-move-notice}

Refer to {observability-guide}/apm-rum-sourcemap-api.html[RUM source map API].

[role="exclude",id="agent-key-api"]
== APM agent Key API

{apm-docs-move-notice}

Refer to {observability-guide}/apm-agent-key-api.html[APM agent Key API].

[role="exclude",id="troubleshooting"]
== Troubleshooting

{apm-docs-move-notice}

Refer to {observability-guide}/apm-app-troubleshooting.html[Troubleshooting].

:!apm-docs-move-notice:

[role="exclude",id="saved-objects-api-export"]
== Export objects API

Refer to {api-kibana}/group/endpoint-saved-objects[saved objects API].

[role="exclude",id="saved-objects-api-import"]
== Import objects API

Refer to {api-kibana}/group/endpoint-saved-objects[saved objects API].

[role="exclude",id="saved-objects-api-bulk-create"]
== Bulk create saved objects API

Refer to {api-kibana}/group/endpoint-saved-objects[saved objects API].

[role="exclude",id="saved-objects-api-bulk-delete"]
== Bulk delete object API

Refer to {api-kibana}/group/endpoint-saved-objects[saved objects API].

[role="exclude",id="saved-objects-api-bulk-get"]
== Bulk get objects API

Refer to {api-kibana}/group/endpoint-saved-objects[saved objects API].

[role="exclude",id="saved-objects-api-bulk-resolve"]
== Bulk resolve objects API

Refer to {api-kibana}/group/endpoint-saved-objects[saved objects API].

[role="exclude",id="saved-objects-api-bulk-update"]
== Bulk update object API

Refer to {api-kibana}/group/endpoint-saved-objects[saved objects API].

[role="exclude",id="saved-objects-api-create"]
== Create saved objects API

Refer to {api-kibana}/group/endpoint-saved-objects[saved objects API].

[role="exclude",id="saved-objects-api-delete"]
==  Delete object API

Refer to {api-kibana}/group/endpoint-saved-objects[saved objects API].

[role="exclude",id="saved-objects-api-find"]
== Find objects API

Refer to {api-kibana}/group/endpoint-saved-objects[saved objects API].

[role="exclude",id="saved-objects-api-get"]
== Get object API

Refer to {api-kibana}/group/endpoint-saved-objects[saved objects API].

[role="exclude",id="saved-objects-api-resolve-import-errors"]
== Resolve import errors API

[role="exclude",id="saved-objects-api-resolve"]
== Resolve object API

Refer to {api-kibana}/group/endpoint-saved-objects[saved objects API].

[role="exclude",id="saved-objects-api-rotate-encryption-key"]
== Rotate encryption key API

Refer to {api-kibana}/group/endpoint-saved-objects[saved objects API].

[role="exclude",id="saved-objects-api-update"]
== Update object API

Refer to {api-kibana}/group/endpoint-saved-objects[saved objects API].

[role="exclude",id="data-views-api-get-all"]
== Get all data views API

Refer to {api-kibana}/group/endpoint-data-views[data views API].

[role="exclude",id="data-views-runtime-field-api-create"]
== Create runtime field API

Refer to {api-kibana}/group/endpoint-data-views[data views API].

[role="exclude",id="data-views-runtime-field-api-delete"]
== Delete runtime field API

Refer to {api-kibana}/group/endpoint-data-views[data views API].

[role="exclude",id="data-views-runtime-field-api-get"]
== Get runtime field API

Refer to {api-kibana}/group/endpoint-data-views[data views API].

[role="exclude",id="data-views-runtime-field-api-update"]
== Update runtime field API

Refer to {api-kibana}/group/endpoint-data-views[data views API].

[role="exclude",id="data-views-runtime-field-api-upsert"]
== Upsert runtime field API

Refer to {api-kibana}/group/endpoint-data-views[data views API].

[role="exclude",id="data-views-api-create"]
== Create data view API

Refer to {api-kibana}/group/endpoint-data-views[data views API].

[role="exclude",id="data-views-api-default-get"]
== Get default data view API

Refer to {api-kibana}/group/endpoint-data-views[data views API].

[role="exclude",id="data-views-api-default-set"]
== Set default data view API

Refer to {api-kibana}/group/endpoint-data-views[data views API].

[role="exclude",id="data-views-api-delete"]
== Delete data view API

Refer to {api-kibana}/group/endpoint-data-views[data views API].

[role="exclude",id="data-views-api-get"]
== Get data view API

Refer to {api-kibana}/group/endpoint-data-views[data views API].

[role="exclude",id="data-views-api-swap-references-preview"]
== Swap references preview data view API

Refer to {api-kibana}/group/endpoint-data-views[data views API].

[role="exclude",id="data-views-api-swap-references"]
== Swap references data view API

Refer to {api-kibana}/group/endpoint-data-views[data views API].

[role="exclude",id="data-views-fields-api-update"]
== Update data view fields API

Refer to {api-kibana}/group/endpoint-data-views[data views API].

[role="exclude",id="data-views-api-update"]
== Update data view API

Refer to {api-kibana}/group/endpoint-data-views[data views API].

[role="exclude",id="create-rule-api"]
== Create rule API

Refer to {api-kibana}/group/endpoint-alerting[alerting API].

[role="exclude",id="delete-rule-api"]
== Delete rule API

Refer to {api-kibana}/group/endpoint-alerting[alerting API].

[role="exclude",id="disable-rule-api"]
== Disable rule API

Refer to {api-kibana}/group/endpoint-alerting[alerting API].

[role="exclude",id="enable-rule-api"]
== Enable rule API

Refer to {api-kibana}/group/endpoint-alerting[alerting API].

[role="exclude",id="find-rules-api"]
== Find rules API

Refer to {api-kibana}/group/endpoint-alerting[alerting API].

[role="exclude",id="get-rule-api"]
== Get rule API

Refer to {api-kibana}/group/endpoint-alerting[alerting API].

[role="exclude",id="get-alerting-framework-health-api"]
== Get alerting framework health API

Refer to {api-kibana}/group/endpoint-alerting[alerting API].

[role="exclude",id="list-rule-types-api"]
== Get rule types API

Refer to {api-kibana}/group/endpoint-alerting[alerting API].

[role="exclude",id="mute-alert-api"]
== Mute alert API

Refer to {api-kibana}/group/endpoint-alerting[alerting API].

[role="exclude",id="mute-all-alerts-api"]
== Mute all alerts API

Refer to {api-kibana}/group/endpoint-alerting[alerting API].

[role="exclude",id="unmute-alert-api"]
== Unmute alert API

Refer to {api-kibana}/group/endpoint-alerting[alerting API].

[role="exclude",id="unmute-all-alerts-api"]
== Unmute all alerts API

Refer to {api-kibana}/group/endpoint-alerting[alerting API].

[role="exclude",id="update-rule-api"]
== Update rule API

Refer to {api-kibana}/group/endpoint-alerting[alerting API].

[role="exclude",id="alerts-api"]
== Deprecated 7.x APIs

Refer to {api-kibana}/group/endpoint-alerting[alerting API].

[role="exclude",id="update-connector-api"]
== Update connector API

Refer to {api-kibana}/group/endpoint-connectors[connectors API].

[role="exclude",id="list-connector-types-api"]
== List connector types API

Refer to {api-kibana}/group/endpoint-connectors[connectors API].

[role="exclude",id="get-connector-api"]
== Get connector API

Refer to {api-kibana}/group/endpoint-connectors[connectors API].

[role="exclude",id="get-all-connectors-api"]
== Get all connectors API

Refer to {api-kibana}/group/endpoint-connectors[connectors API].

[role="exclude",id="execute-connector-api"]
== Run connector API

Refer to {api-kibana}/group/endpoint-connectors[connectors API].

[role="exclude",id="delete-connector-api"]
== Delete connector API

Refer to {api-kibana}/group/endpoint-connectors[connectors API].

[role="exclude",id="create-connector-api"]
== Create connector API

Refer to {api-kibana}/group/endpoint-connectors[connectors API].

[role="exclude",id="actions-and-connectors-legacy-apis"]
== Deprecated 7.x APIs

Refer to {api-kibana}/group/endpoint-connectors[connectors API].

[role="exclude",id="cases-api-add-comment"]
== Add comment to case API

Refer to {api-kibana}/group/endpoint-cases[cases API].

[role="exclude",id="cases-api-create"]
== Create case API

Refer to {api-kibana}/group/endpoint-cases[cases API].

[role="exclude",id="cases-api-delete-cases"]
== Delete cases API

Refer to {api-kibana}/group/endpoint-cases[cases API].

[role="exclude",id="cases-api-delete-comments"]
== Delete comments from case API

Refer to {api-kibana}/group/endpoint-cases[cases API].

[role="exclude",id="cases-api-find-case-activity"]
== Find case activity API

Refer to {api-kibana}/group/endpoint-cases[cases API].

[role="exclude",id="cases-api-find-cases"]
== Find cases API

Refer to {api-kibana}/group/endpoint-cases[cases API].

[role="exclude",id="cases-api-find-connectors"]
== Find connectors API

Refer to {api-kibana}/group/endpoint-cases[cases API].

[role="exclude",id="cases-api-get-alerts"]
== Get alerts attached to case API

Refer to {api-kibana}/group/endpoint-cases[cases API].

[role="exclude",id="cases-api-get-case-activity"]
== Get case activity API

Refer to {api-kibana}/group/endpoint-cases[cases API].

[role="exclude",id="cases-api-get-case"]
== Get case API

Refer to {api-kibana}/group/endpoint-cases[cases API].

[role="exclude",id="cases-api-get-cases-by-alert"]
== Get cases by alert API

Refer to {api-kibana}/group/endpoint-cases[cases API].

[role="exclude",id="cases-api-get-comments"]
== Get comments API

Refer to {api-kibana}/group/endpoint-cases[cases API].

[role="exclude",id="cases-get-configuration"]
== Get case configuration API

Refer to {api-kibana}/group/endpoint-cases[cases API].

[role="exclude",id="cases-api-get-reporters"]
== Get reporters API

Refer to {api-kibana}/group/endpoint-cases[cases API].

[role="exclude",id="cases-api-get-status"]
== Get case status API

Refer to {api-kibana}/group/endpoint-cases[cases API].

[role="exclude",id="cases-api-get-tag"]
== Get tags API

Refer to {api-kibana}/group/endpoint-cases[cases API].

[role="exclude",id="cases-api-push"]
== Push case API

Refer to {api-kibana}/group/endpoint-cases[cases API].

[role="exclude",id="cases-api-set-configuration"]
== Set case configuration API

Refer to {api-kibana}/group/endpoint-cases[cases API].

[role="exclude",id="cases-api-update-comment"]
== Update case comment API

Refer to {api-kibana}/group/endpoint-cases[cases API].

[role="exclude",id="cases-api-update-configuration"]
== Update case configuration API

Refer to {api-kibana}/group/endpoint-cases[cases API].

[role="exclude",id="cases-api-update"]
== Update cases API

Refer to {api-kibana}/group/endpoint-cases[cases API].

[role="exclude",id="machine-learning-api-sync"]
== Sync {ml} saved objects API

Refer to {api-kibana}/group/endpoint-ml[machine learning APIs].
