[[releasenotes]]
== Kibana 4.3 Release Notes

The 4.3 release of Kibana requires Elasticsearch 2.1 or later.

Using event times to create index names is *deprecated* in this release of Kibana. Support for this functionality will be 
removed entirely in the next major Kibana release. Elasticsearch 2.1 includes sophisticated date parsing APIs that Kibana 
uses to determine date information, removing the need to specify dates in the index pattern name.

[float]
[[enhancements]]
== Enhancements

* {k4issue}5109[Issue 5109]: Adds custom JSON and filter alias naming for filters.
* {k4issue}1726[Issue 1726]: Adds a color field formatter for value ranges in numeric fields.
* {k4issue}4342[Issue 4342]: Increased performance for wildcard indices.
* {k4issue}1600[Issue 1600]: Support for global time zones.
* {k4pull}5275[Pull Request 5275]: Highlighting values in Discover can now be disabled.
* {k4issue}5212[Issue 5212]: Adds support for multiple certificate authorities.
* {k4issue}2716[Issue 2716]: The open/closed position of the spy panel now persists across UI state changes.

[float]
[[bugfixes]]
== Bug Fixes

* {k4issue}5165[Issue 5165]: Resolves a display error in embedded views.
* {k4issue}5021[Issue 5021]: Improves visualization dimming for dashboards with auto-refresh.

[float]
=== Kibana 4.3.1 Release Notes

* Fixes XSS vulnerability (CVE pending) - Thanks to Vladimir Ivanov for responsibly reporting.
* {k4pull}5469[Pull Request 5469]: Fixes a caching issue when creating new index patterns.
* {k4pull}5509[Pull Request 5509]: Prevents exception on discover panel when using non-time-based patterns.
* {k4pull}5525[Pull Request 5525]: Non-standard cookie format no longer causes fatal error.
* {k4pull}5536[Pull Request 5536]: Fixes broken image links on URL formatter.
* {k4pull}5542[Pull Request 5542]: Uses a modern cipher list for TLS.
* {k4pull}5560[Pull Request 5560]: Removes brushing ability when dealing with non-time-based indices.
* {k4pull}5571[Pull Request 5571]: Fixes fatal error when using Shield and a time range with no results.
* {k4pull}5572[Pull Request 5572]: Improves Elasticsearch version verification.
* {k4pull}5586[Pull Request 5586]: Fixes fatal error when trying to "export all" on large datasets.
* {k4pull}5587[Pull Request 5587]: Fixes xsrf-token-related fatal error when server restarts.
* {k4pull}5598[Pull Request 5598]: Allows passing node flags via NODE_OPTIONS.
* {k4pull}5603[Pull Request 5603]: Bump node.js version from 0.12.7 to 0.12.9 due to security fixes in node.
* {k4pull}5636[Pull Request 5636]: Fixes bug that would cause plugin install to fail.
* {k4pull}5642[Pull Request 5642]: Fixes sorting behavior when wildcard index pattern matches multiple prefixes.
