[[releasenotes]]
== Kibana 4.3 Release Notes

The 4.3 release of Kibana requires Elasticsearch 2.1 or later.

Using event times to create index names is *deprecated* in this release of Kibana. Support for this functionality will be 
removed entirely in the next major Kibana release. Elasticsearch 2.1 includes sophisticated date parsing APIs that Kibana 
uses to determine date information, removing the need to specify dates in the index pattern name.

[float]
[[enhancements]]
== Enhancements

* {k4issue}5109[Issue 5109]: Adds custom JSON and filter alias naming for filters.
* {k4issue}1726[Issue 1726]: Adds a color field formatter for value ranges in numeric fields.
* {k4issue}4342[Issue 4342]: Increased performance for wildcard indices.
* {k4issue}1600[Issue 1600]: Support for global time zones.
* {k4pull}5275[Pull Request 5275]: Highlighting values in Discover can now be disabled.
* {k4issue}5212[Issue 5212]: Adds support for multiple certificate authorities.
* {k4issue}2716[Issue 2716]: The open/closed position of the spy panel now persists across UI state changes.

[float]
[[bugfixes]]
== Bug Fixes

* {k4issue}5165[Issue 5165]: Resolves a display error in embedded views.
* {k4issue}5021[Issue 5021]: Improves visualization dimming for dashboards with auto-refresh.
