[[timelion]]
= Timelion

[partintro]
--
Timelion is a time series data visualizer that enables you to combine totally
independent data sources within a single visualization. It's driven by a simple
expression language you use to retrieve time series data, perform calculations
to tease out the answers to complex questions, and visualize the results.

For example, Timelion enables you to easily get the answers to questions like:

* How many pages does each unique user view over time?
* What's the difference in traffic volume between this Friday and last Friday?
* What percent of Japan's population came to my site today?
* What's the 10-day moving average of the S&P 500?
* What's the cumulative sum of all search requests received in the last 2 years?


Ready to experience all that is Timelion? This tutorial shows you how to:

* {kib-ref}timelion-create.html[Create a time series chart with multiple expressions]
* {kib-ref}timelion-customize.html[Customize the visualization type and formatting options]
* {kib-ref}timelion-math.html[Use mathematical functions to manipulate your data]
* {kib-ref}timelion-conditional.html[Track trends and use conditional logic to format outliers]
* {kib-ref}timelion-save.html[Add Timelion visualizations to a dashboard]
* {kib-ref}timelion-inline-help.html[Reference inline help]
--
include::timelion/timelion-create.asciidoc[]

include::timelion/timelion-customize.asciidoc[]

include::timelion/timelion-math.asciidoc[]

include::timelion/timelion-conditional.asciidoc[]

include::timelion/timelion-save.asciidoc[]

include::timelion/timelion-inline-help.asciidoc[]