[[vertical-bar-chart]]
=== Vertical Bar Charts

This chart's Y axis is the _metrics_ axis. The following aggregations are available for this axis:

include::y-axis-aggs.asciidoc[]

The _buckets_ aggregations determine what information is being retrieved from your data set.

Before you choose a buckets aggregation, specify if you are splitting slices within a single chart or splitting into
multiple charts. A multiple chart split must run before any other aggregations. When you split a chart, you can change 
if the splits are displayed in a row or a column by clicking the *Rows | Columns* selector.

include::x-axis-aggs.asciidoc[]

You can click the *Advanced* link to display more customization options for your metrics or bucket aggregation:

*Exclude Pattern*:: Specify a pattern in this field to exclude from the results.
*Exclude Pattern Flags*:: A standard set of Java flags for the exclusion pattern.
*Include Pattern*:: Specify a pattern in this field to include in the results.
*Include Pattern Flags*:: A standard set of Java flags for the inclusion pattern.
*JSON Input*:: A text field where you can add specific JSON-formatted properties to merge with the aggregation 
definition, as in the following example:

[source,shell]
{ "script" : "doc['grade'].value * 1.2" }

NOTE: In Elasticsearch releases 1.4.3 and later, this functionality requires you to enable 
{ref}/modules-scripting.html[dynamic Groovy scripting].

The availability of these options varies depending on the aggregation you choose.

Select the *Options* to change the following aspects of the table:

*Bar Mode*:: When you have multiple Y-axis aggregations defined for your chart, you can use this drop-down to affect 
how the aggregations display on the chart:

_stacked_:: Stacks the aggregations on top of each other.
_percentage_:: Displays each aggregation as a proportion of the total.
_grouped_:: Groups the results horizontally by the lowest-priority sub-aggregation.

Checkboxes are available to enable and disable the following behaviors:

*Show Tooltip*:: Check this box to enable the display of tooltips.
*Show Legend*:: Check this box to enable the display of a legend next to the chart.
*Scale Y-Axis to Data Bounds*:: The default Y axis bounds are zero and the maximum value returned in the data. Check 
this box to change both upper and lower bounds to match the values returned in the data.
