[[visualize]]
= Visualize

[partintro]
--
_Visualize_ enables you to create visualizations of the data from your Elasticsearch indices, which you can add to <<dashboard, dashboards>> to analyze and compare.

Kibana visualizations are based on Elasticsearch queries. By using a series of Elasticsearch {ref}/search-aggregations.html[aggregations] to extract and process your data, you can create charts that show you the trends, spikes, and dips you need to know about.

Create visualizations from a search saved in <<discover, Discover>>, or start with a new search query.

[float]
[[visualization-types]]
== Types of visualizations

{kib} includes many visualizations that you can use to display your data.

[horizontal]
<<xy-chart,Area>>:: Compare different series in X/Y charts.
<<controls,Controls>>:: Add interactive inputs to Kibana Dashboards.
<<tilemap,Coordinate Map>>:: Plot latitude and longitude coordinates on a map.
<<data-table,Data Table>>:: Display the raw data of a composed aggregation.
<<goal-chart,Gauge>>:: Display a specified range where your metric falls.
<<goal-chart,Goal>>:: Display how your metric progresses toward a fixed goal.
<<heatmap-chart,Heat Map>>:: Shade cells within a matrix.
<<xy-chart,Horizontal Bar>>::
<<xy-chart,Line>>::
<< ,Maps>>:: Create and style maps with multiple layers and indices.
<<markdown-widget,Markdown>>:: Display free-form information or instructions.
<<metric-chart,Metric>>:: Display a single number.
<<pie-chart,Pie>>:: Display source contributions to a total.
<<regionmap,Region Map>>:: Display metrics on a thematic map where shape color intensity corresponds to metric values.
<<TSVB,TSVB>>:: Visualize time series data using pipeline aggregations.
<<tagcloud-chart,Tag Cloud>>:: Display words as a cloud, where the size of the word correspond to its importance.
<<timelion,Timelion>>:: Compute and combine data from multiple time series data sets.
<<vega-graph,Vega>>:: User-defined graphs, external data sources, images, and user-defined interactivity.
<<xy-chart,Vertical Bar>>:: 

[float]
[[createvis]]
== Create a visualization

Short description.

. In the side navigation, click *Visualize*.

. Click *Create new visualization*.

. On the *New Visualization* window, choose the type of visualization you want to use.

. On the *New Area/Choose a source* window, specify a search query to retrieve the data for your visualization:

** To enter new search criteria, select the index pattern for the indices that
contain the data you want to visualize. The visualization builder
opens with a wildcard query that matches all of the documents in the selected
indices.
** To build a visualization from a saved search, click the name of the saved
search you want to use. The visualization builder opens and loads the
selected query.
+
NOTE: When you build a visualization from a saved search, any subsequent
modifications to the saved search automatically appear in the
visualization. To disable automatic updates, disconnect the visualization
from the saved search.
--

include::visualize/area-chart.asciidoc[]

include::visualize/saving.asciidoc[]

include::visualize/visualize_rollup_data.asciidoc[]

include::visualize/xychart.asciidoc[]

include::visualize/controls.asciidoc[]

include::visualize/datatable.asciidoc[]

include::visualize/markdown.asciidoc[]

include::visualize/metric.asciidoc[]

include::visualize/goal.asciidoc[]

include::visualize/pie.asciidoc[]

include::visualize/tilemap.asciidoc[]

include::visualize/regionmap.asciidoc[]

include::visualize/timelion.asciidoc[]

include::visualize/tsvb.asciidoc[]

include::visualize/tagcloud.asciidoc[]

include::visualize/heatmap.asciidoc[]

include::visualize/vega.asciidoc[]

include::visualize/inspector.asciidoc[]
