[[visualize]]
= Visualize

[partintro]
--
_Visualize_ enables you to create visualizations of the data from your Elasticsearch indices, which you can add to <<dashboard, dashboards>> to analyze and compare.

Kibana visualizations are based on Elasticsearch queries. By using a series of Elasticsearch {ref}/search-aggregations.html[aggregations] to extract and process your data, you can create charts that show you the trends, spikes, and dips you need to know about.

Create visualizations from a search saved in <<discover, Discover>>, or start with a new search query.

[float]
[[visualization-types]]
== Types of visualizations

{kib} includes many visualizations that you can use to display your data.

[float]
[[basic-chart-types]]
=== Basic charts

[horizontal]
<<visualize-chart,Area, bar, and line charts>>:: Compare data series in x- and y-axis charts.
<<pie-chart,Pie charts>>:: Display source contributions to a total.

[float]
[[data-visualization-types]]
=== Data

[horizontal]
<<data-table,Data table>>:: Display the raw data of a composed aggregation.
<<goal-chart,Gauge>>:: Display a specified range where your metric falls.
<<goal-chart,Goal>>:: Display how your metric progresses toward a fixed goal.
<<metric-chart,Metric>>:: Display a single number.

[float]
[[maps-visualization-types]]
=== Maps

[horizontal]
<<heatmap-chart,Heat map>>:: Shade cells within a matrix.
<< ,Maps>>:: Create and style maps with multiple layers and indices.
<<regionmap,Region map>>:: Display metrics on a thematic map where shape color intensity corresponds to metric values.
<<tilemap,Coordinate map>>:: Plot latitude and longitude coordinates on a map.

[float]
[[time-series-types]]
=== Time series

[horizontal]
<<TSVB,TSVB>>:: Visualize time series data using pipeline aggregations.
<<timelion,Timelion>>:: Compute and combine data from multiple time series data sets.

[float]
[[other-visualization-types]]
=== Other

[horizontal]
<<controls,Controls>>:: Add interactive inputs to Kibana Dashboards.
<<markdown-widget,Markdown>>:: Display free-form information or instructions.
<<tagcloud-chart,Tag cloud>>:: Display words as a cloud, where the size of the word correspond to its importance.
<<vega-graph,Vega>>:: User-defined graphs, external data sources, images, and user-defined interactivity.

[float]
[[aggregation-types]]
== Data aggregation 

Short description.

[float]
[[metric-aggregations]]
=== Metric aggregations

Short description. 

Count:: Returns a raw count of the elements in the selected index pattern.

Average:: Returns the average. 

Sum:: Returns the total sum.

Min:: Returns the minimum value.

Max:: Returns the maximum value.

Unique Count:: Returns the number of unique values.

Standard Deviation:: Returns the standard deviation of the data.

Top Hit:: Returns one or more of the top values from a specified field in your documents.

Percentiles:: Divides the values in a numeric field into specified percentile bands.

Percentile Rank:: Returns the percentile rankings for the values in the specified numeric field.

For more information about Elasticsearch metric aggregrations, refer to {ref}/search-aggregations-metrics.html[Metric aggregations].

[float]
[[parent-pipeline-aggregations]]
=== Parent pipeline aggregations

For each parent pipeline aggregation, you define the metric for the calculated aggregation.

Derivative:: Calculates the derivative of the specified metrics.

Culumlative Sum:: Calculates the cumulative sum of the specified metric in a parent histogram.

Moving Average:: Slides a window across the data and displays the average value of the window.

Serial Diff:: Subtracts the values in a time series at various time periods.

For more information about Elasticsearch parent pipeline aggregations, refer to {ref}/search-aggregations-pipeline.html[Pipeline aggregations].

[float]
[[sibling-pipeline-aggregations]]
=== Sibling pipeline aggregations

Sibling pipeline aggregations require a bucket aggregation that defines the buckets that run the sibling aggregation.

Average Bucket:: Calculates the average value of the specified metric.

Sum Bucket:: Calculates the sum of the specified metric values.

Min Bucket:: Calculates the minimum value of the specified metric.

Max Bucket:: Calculates the maximum value of the specified metric.

For more information about Elasticsearch sibling pipeline aggregations, refer to {ref}/search-aggregations-pipeline.html[Pipeline aggregations].

[float]
[[buckets-aggregations]]
=== Buckets aggregations

Buckets aggregations determine the information that is retrieved from your data set.

TIP: Buckets are analogous to SQL `GROUP BY` statements.

Date Histogram:: Builds from a numeric field and organized by date.

Histogram:: Builds from a numeric field.

IPv4 Range:: Specifies a range of IPv4 ranges.

Terms:: Specifies the top or bottom _n_ elements of a field to display.

Filters:: Specifies a set of filters that you can apply to the data.

Significant filters:: Displays the results of the experimental _significant terms_ aggregation.

For more information about Elasticsearch bucket aggregations, refer to * {ref}/search-aggregations-bucket.html[Bucket aggregation].

[float]
[[sub-aggregations]]
=== Sub aggregations

Short description.

The first aggregation determines the data set for any subsequent aggregations. Sub aggregations are applied from top to bottom. 

For more information about working with sub aggregations, see https://www.elastic.co/blog/kibana-aggregation-execution-order-and-you[Kibana, Aggregation Execution Order, and You].

[float]
[[createvis]]
== Create a visualization

Short description.

. In the side navigation, click *Visualize*.

. Click *Create new visualization*.

. On the *New Visualization* window, select the type of visualization you want to use.

. On the *New Area/Choose a source* window, specify a search query to retrieve the data for your visualization:

** To enter new search criteria, select the index pattern for the indices that
contain the data you want to visualize. The visualization builder
opens with a wildcard query that matches all of the documents in the selected
indices.
** To build a visualization from a saved search, click the name of the saved
search you want to use. The visualization builder opens and loads the
selected query.
+
NOTE: When you build a visualization from a saved search, any subsequent
modifications to the saved search automatically appear in the
visualization. To disable automatic updates, disconnect the visualization
from the saved search.
--

include::visualize/charts.asciidoc[]

include::visualize/pie.asciidoc[]

include::visualize/datatable.asciidoc[]

include::visualize/goal.asciidoc[]

include::visualize/metric.asciidoc[]

include::visualize/heatmap.asciidoc[]

include::visualize/regionmap.asciidoc[]

include::visualize/tilemap.asciidoc[]

include::visualize/tsvb.asciidoc[]

include::visualize/timelion.asciidoc[]

include::visualize/saving.asciidoc[]

include::visualize/visualize_rollup_data.asciidoc[]

include::visualize/controls.asciidoc[]

include::visualize/markdown.asciidoc[]

include::visualize/tagcloud.asciidoc[]

include::visualize/vega.asciidoc[]

include::visualize/inspector.asciidoc[]
