[[whats-new]]
== What's New in Kibana 4.1

[float]
[[key-features]]
=== Key Features

* {k4pull}2518[Pull Request 2518]: You can pin filters to make the filter persist across Kibana functionality, from 
the Visualize tab to Discover to a Dashboard.
* {k4pull}2731[Pull Request 2731]: Field formatting options now supported in Settings.
* {k4pull}3154[Pull Request 3154]: New chart: Bubble chart, derived from the basic line chart.
* {k4pull}3212[Pull Request 3212]: You can now install Kibana on Linux with a package manager such as `apt-get`.
* {k4pull}3271[Pull Request 3271] and {k4pull}3262[3262]: New aggregations: IPv4 and Date range aggregations enable 
you to specify buckets for these qualities.
* {k4pull}3290[Pull Request 3290]: You can select a time interval for the Discover display of time series data.
* {k4pull}3470[Pull Request 3470]: New metric: Percentile ranks.
* {k4pull}3573[Pull Request 3573]: Kibana objects (visualizations, dashboards, and searches) can be imported and 
exported.
* {k4pull}3830[Pull Request 3830]: New chart: Heatmap, a tile map display variant.

[float]
[[improvements]]
=== Improvements

* {k4pull}3164[Pull Request 3164]: You can now store a specific time range with a dashboard.
* {k4pull}3233[Pull Request 3233]: New Y axis scale options, log scale and square root scale.
* {k4pull}3237[Pull Request 3237]: Date Histogram bucket aggregation now supports custom intervals, from seconds to 
years.
* {k4pull}3273[Pull Request 3273]: Line smoothing for for line and area charts.
* {k4pull}3464[Pull Request 3464]: You can now specify the extent of the Y axis for charts.
* {k4pull}3526[Pull Request 3526]: You can add columns to Discover's list of results directly from an entry's table of 
fields.
* {k4pull}3671[Pull Request 3671]: Tile maps now support latitude/longitude filtering.
* {k4pull}3800[Pull Request 3800]: You can now pause auto-refresh on a dashboard.


[float]
=== Kibana 4.1.4

* Fixes XSS vulnerability (CVE pending) - Thanks to Vladimir Ivanov for responsibly reporting.
* {k4pull}5418[Pull Request 5418]: Fixes fatal error in Firefox when attempting to overwrite an index pattern.
* {k4pull}5509[Pull Request 5509]: Prevents exception on discover panel when using non-time-based patterns.
* {k4pull}5576[Pull Request 5576]: Improves Elasticsearch version verification.
* {k4pull}5603[Pull Request 5639]: Fixes xsrf-token-related fatal error when server restarts.
