/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: PND Investigation component schemas
 *   version: 1
 */

import { z, lazySchema } from '@kbn/zod/v4';

export const TemplateId = lazySchema(() => z.enum(['investigation', 'proposal', 'incident']));
export type TemplateId = z.infer<typeof TemplateId>;
export type TemplateIdEnum = typeof TemplateId.enum;
export const TemplateIdEnum = TemplateId.enum;

/**
 * Template revision this record was instantiated from. Pinned on the record at creation so a later template revision does not retroactively change how an existing record is validated or rendered.
 */
export const TemplateVersion = lazySchema(() => z.number().int().min(1));
export type TemplateVersion = z.infer<typeof TemplateVersion>;

/**
 * Brief bucket recommendation for an investigation
 */
export const RecommendedAction = lazySchema(() =>
  z.enum(['contain', 'escalate', 'investigate', 'tune', 'create'])
);
export type RecommendedAction = z.infer<typeof RecommendedAction>;
export type RecommendedActionEnum = typeof RecommendedAction.enum;
export const RecommendedActionEnum = RecommendedAction.enum;

export const ProposalStatus = lazySchema(() =>
  z.enum(['pending', 'approved', 'modified', 'dismissed', 'escalated', 'deferred', 'executed'])
);
export type ProposalStatus = z.infer<typeof ProposalStatus>;
export type ProposalStatusEnum = typeof ProposalStatus.enum;
export const ProposalStatusEnum = ProposalStatus.enum;

/**
 * Structured reason an analyst dismissed a proposal (MVP requirement).
 */
export const DismissalReason = lazySchema(() =>
  z.enum([
    'wrong',
    'duplicate',
    'insufficient_evidence',
    'low_value',
    'out_of_scope',
    'already_handled',
    'other',
  ])
);
export type DismissalReason = z.infer<typeof DismissalReason>;
export type DismissalReasonEnum = typeof DismissalReason.enum;
export const DismissalReasonEnum = DismissalReason.enum;

export const WatchTier = lazySchema(() =>
  z.enum(['floor', 'officer', 'dark', 'deep', 'detection', 'ad'])
);
export type WatchTier = z.infer<typeof WatchTier>;
export type WatchTierEnum = typeof WatchTier.enum;
export const WatchTierEnum = WatchTier.enum;

export const EvidenceRef = lazySchema(() =>
  z.object({
    id: z.string(),
    /**
     * Attachment or document type (e.g. alert, log, case)
     */
    type: z.string(),
    label: z.string().optional(),
    url: z.string().optional(),
  })
);
export type EvidenceRef = z.infer<typeof EvidenceRef>;

export const TimelineEvent = lazySchema(() =>
  z.object({
    id: z.string(),
    /**
     * ISO 8601 timestamp
     */
    timestamp: z.string(),
    /**
     * Event category (e.g. triage, proposal, escalation)
     */
    type: z.string(),
    summary: z.string(),
    /**
     * User or watch that produced the event
     */
    actor: z.string().nullable().optional(),
  })
);
export type TimelineEvent = z.infer<typeof TimelineEvent>;

export const Investigation = lazySchema(() =>
  z.object({
    id: z.string(),
    template_id: z.literal('investigation'),
    template_version: TemplateVersion.optional(),
    title: z.string(),
    /**
     * ISO 8601 timestamp
     */
    createdAt: z.string(),
    /**
     * ISO 8601 timestamp
     */
    updatedAt: z.string(),
    watch_id: z.string(),
    watch_execution_id: z.string(),
    watch_tier: WatchTier.optional(),
    severity: z.string().optional(),
    assignee: z.string().nullable().optional(),
    status: z.string().optional(),
    pendingProposalCount: z.number().int().min(0),
    recommendedAction: RecommendedAction.optional(),
    /**
     * Primary asset or surface impacted
     */
    affectedSurface: z.string().optional(),
    summary: z.string().optional(),
    /**
     * Brief priority score (0-100) for queue ranking
     */
    priorityScore: z.number().int().min(0).max(100).optional(),
    /**
     * Durable record label shown in Brief (e.g. CASE-2047)
     */
    recordId: z.string().optional(),
    /**
     * Leading proposal CTA label for Brief cards
     */
    primaryActionLabel: z.string().optional(),
    events: z.array(TimelineEvent),
  })
);
export type Investigation = z.infer<typeof Investigation>;

export const RuleTuningTrigger = lazySchema(() =>
  z.object({
    reason: z.literal('false_positive'),
    alertId: z.string(),
    ruleRef: z.string().optional(),
    confidence: z.number().min(0).max(1),
    investigationId: z.string(),
  })
);
export type RuleTuningTrigger = z.infer<typeof RuleTuningTrigger>;

export const Proposal = lazySchema(() =>
  z.object({
    id: z.string(),
    template_id: z.literal('proposal'),
    template_version: TemplateVersion.optional(),
    /**
     * Investigation id this proposal belongs to
     */
    parentConversationId: z.string(),
    /**
     * Proposal action type (e.g. contain, escalate, tune)
     */
    type: z.string(),
    confidence: z.number().min(0).max(1),
    reasoning: z.string(),
    evidenceRefs: z.array(EvidenceRef),
    status: ProposalStatus,
    assignee: z.string().nullable(),
    /**
     * ISO 8601 deadline for response
     */
    sla: z.string().nullable(),
    events: z.array(TimelineEvent),
    sourceWatchId: z.string(),
    approvalRequired: z.boolean(),
    summary: z.string(),
    recommendation: z.string(),
    /**
     * Set when status is dismissed; structured reason (MVP requirement).
     */
    dismissalReason: DismissalReason.optional(),
    /** ISO timestamp set when an analyst decision is recorded. */
    decidedAt: z.string().optional(),
    /**
     * Contrary evidence — shown alongside supporting evidenceRefs so uncertainty is visible (MVP requirement).
     */
    evidenceAgainst: z.array(EvidenceRef).optional(),
    /**
     * Optional — surfaced by Floor Worker when an alert is dispositioned as false positive. Detection Watch subscribes to this.
     */
    ruleTuningTrigger: RuleTuningTrigger.optional(),
  })
);
export type Proposal = z.infer<typeof Proposal>;

export const Incident = lazySchema(() =>
  z.object({
    id: z.string(),
    template_id: z.literal('incident'),
    template_version: TemplateVersion.optional(),
    forkedFromInvestigationId: z.string(),
    watch_id: z.string().optional(),
    status: z.string().optional(),
    severity: z.string().optional(),
    assignee: z.string().nullable().optional(),
    events: z.array(TimelineEvent),
  })
);
export type Incident = z.infer<typeof Incident>;
