[[development-visualize-index]]
== Developing Visualizations

[IMPORTANT]
==============================================
These pages document internal APIs and are not guaranteed to be supported across future versions of {kib}.
==============================================

The internal APIs for creating custom visualizations are in a state of heavy churn as
they are being migrated to the new {kib} platform, and large refactorings have been
happening across minor releases in the `7.x` series. In particular, in `7.5` and later
we have made significant changes to the legacy APIs as we work to gradually replace them.

As a result, starting in `7.5` we have removed the documentation for the legacy APIs
to prevent confusion. We expect to be able to create new documentation later in `7.x`
when the visualizations plugin has been completed.

We would recommend waiting until later in `7.x` to upgrade your plugins if possible.
If you would like to keep up with progress on the visualizations plugin in the meantime,
here are a few resources:

* The {kibana-ref-all}/8.0/release-notes-8.0.0.html#breaking-changes-8.0.0[8.0.0 breaking changes], where we try to capture any changes to the APIs as they occur across minors.
* link:https://github.com/elastic/kibana/issues/44121[Meta issue] which is tracking the move of the plugin to the new {kib} platform
* Our link:https://www.elastic.co/blog/join-our-elastic-stack-workspace-on-slack[Elastic Stack workspace on Slack].
* The {kib-repo}blob/{branch}/src/plugins/visualizations[source code], which will continue to be
the most accurate source of information.
