[[dashboard-import-api-export]]
=== Dashboard export API
++++
<titleabbrev>Dashboard export</titleabbrev>
++++

Export dashboards and corresponding saved objects, such as visualizations, saved searches, and index patterns.

experimental[This functionality is *experimental* and may be changed or removed completely in a future release.]

NOTE: You cannot access the endpoint via the Console in Kibana.

[float]
[[dashboard-import-api-export-request]]
==== Request

`GET /api/kibana/dashboards/export`

[float]
[[dashboard-import-api-export-params]]
==== Query parameters

`dashboard` (Required)::
  (array|string) The IDs of the dashboards that you want to export.

[float]
[[dashboard-import-api-export-response-body]]
==== Response body

The response body includes a top level `objects` property that contains an array of saved objects. The order of the objects is not guaranteed. Use the exact response body as the request body for the corresponding <<dashboard-import-api-import, Import Dashboard API>>.

[float]
[[dashboard-import-api-export-example]]
==== Example

[source,js]
--------------------------------------------------
GET api/kibana/dashboards/export?dashboard=942dcef0-b2cd-11e8-ad8e-85441f0c2e5c <1>
--------------------------------------------------
// KIBANA

<1> In this example, `942dcef0-b2cd-11e8-ad8e-85441f0c2e5c` is the dashboard ID.

A successful call returns a response code of `200` along with the exported objects as the response body.
