/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

/**
 * Grandfathered unbounded action input schemas that predate `action_input_bounds.test.ts`.
 *
 * DO NOT ADD ENTRIES. New (and newly-edited) action input schemas must be bounded — add a
 * `.max()` to strings/arrays and an entry-count `.refine()` to records instead. This list
 * exists only so the bounding rule could be turned on for the whole package without first
 * fixing every legacy spec; it should only ever shrink. When you bound one of the inputs
 * below, `action_input_bounds.test.ts` will fail until its entry is removed here.
 */
export const KNOWN_UNBOUNDED_ACTION_INPUTS: string[] = [
  'AbuseIPDBConnector: reportIp.input.categories: unbounded z.array() — add .max(n) on the element count',
  'AbuseIPDBConnector: reportIp.input.comment: unbounded z.string() — add .max(n) (or a bounded format)',
  'AbuseIPDBConnector: bulkCheck.input.network: unbounded z.string() — add .max(n) (or a bounded format)',
  'AlienVaultOTXConnector: getIndicator.input.indicator: unbounded z.string() — add .max(n) (or a bounded format)',
  'AlienVaultOTXConnector: getIndicator.input.section: unbounded z.string() — add .max(n) (or a bounded format)',
  'AlienVaultOTXConnector: searchPulses.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'AlienVaultOTXConnector: getPulse.input.pulseId: unbounded z.string() — add .max(n) (or a bounded format)',
  'AlienVaultOTXConnector: getRelatedPulses.input.indicator: unbounded z.string() — add .max(n) (or a bounded format)',
  'AmazonS3: listBuckets.input.region: unbounded z.string() — add .max(n) (or a bounded format)',
  'AmazonS3: listBuckets.input.prefix: unbounded z.string() — add .max(n) (or a bounded format)',
  'AmazonS3: listBucketObjects.input.bucket: unbounded z.string() — add .max(n) (or a bounded format)',
  'AmazonS3: listBucketObjects.input.region: unbounded z.string() — add .max(n) (or a bounded format)',
  'AmazonS3: listBucketObjects.input.prefix: unbounded z.string() — add .max(n) (or a bounded format)',
  'AmazonS3: listBucketObjects.input.continuationToken: unbounded z.string() — add .max(n) (or a bounded format)',
  'AmazonS3: downloadFile.input.bucket: unbounded z.string() — add .max(n) (or a bounded format)',
  'AmazonS3: downloadFile.input.key: unbounded z.string() — add .max(n) (or a bounded format)',
  'AnsibleControllerConnector: request.input.query: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'AnsibleControllerConnector: launchJobTemplate.input.extraVars: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'AnsibleControllerConnector: launchJobTemplate.input.credentials: unbounded z.array() — add .max(n) on the element count',
  'ArgocdConnector: request.input.query: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'ArgocdConnector: listApplications.input.projects: unbounded z.array() — add .max(n) on the element count',
  'ArgocdConnector: syncApplication.input.syncOptions: unbounded z.array() — add .max(n) on the element count',
  'ArgocdConnector: syncApplication.input.resources: unbounded z.array() — add .max(n) on the element count',
  'AwsLambdaConnector: invoke.input.functionName: unbounded z.string() — add .max(n) (or a bounded format)',
  'AwsLambdaConnector: invoke.input.qualifier: unbounded z.string() — add .max(n) (or a bounded format)',
  'AwsLambdaConnector: listFunctions.input.marker: unbounded z.string() — add .max(n) (or a bounded format)',
  'AwsLambdaConnector: getFunction.input.functionName: unbounded z.string() — add .max(n) (or a bounded format)',
  'AwsLambdaConnector: getFunction.input.qualifier: unbounded z.string() — add .max(n) (or a bounded format)',
  'AwsXRay: getInsight.input.insightId: unbounded z.string() — add .max(n) (or a bounded format)',
  'AwsXRay: batchGetTraces.input.traceIds[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'AwsXRay: getInsightImpactGraph.input.insightId: unbounded z.string() — add .max(n) (or a bounded format)',
  'AwsXRay: getInsightEvents.input.insightId: unbounded z.string() — add .max(n) (or a bounded format)',
  'AwsXRay: getTraceGraph.input.traceIds[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'AwsXRay: startTraceRetrieval.input.traceIds[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'AzureBlob: listContainers.input.prefix: unbounded z.string() — add .max(n) (or a bounded format)',
  'AzureBlob: listContainers.input.marker: unbounded z.string() — add .max(n) (or a bounded format)',
  'AzureBlob: listBlobs.input.container: unbounded z.string() — add .max(n) (or a bounded format)',
  'AzureBlob: listBlobs.input.prefix: unbounded z.string() — add .max(n) (or a bounded format)',
  'AzureBlob: listBlobs.input.marker: unbounded z.string() — add .max(n) (or a bounded format)',
  'AzureBlob: getBlob.input.container: unbounded z.string() — add .max(n) (or a bounded format)',
  'AzureBlob: getBlob.input.blobName: unbounded z.string() — add .max(n) (or a bounded format)',
  'AzureBlob: getBlobProperties.input.container: unbounded z.string() — add .max(n) (or a bounded format)',
  'AzureBlob: getBlobProperties.input.blobName: unbounded z.string() — add .max(n) (or a bounded format)',
  'BigQuery: runQuery.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'BigQuery: runQuery.input.location: unbounded z.string() — add .max(n) (or a bounded format)',
  'BigQuery: executeQuery.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'BigQuery: executeQuery.input.location: unbounded z.string() — add .max(n) (or a bounded format)',
  'BigQuery: getQueryResults.input.jobId: unbounded z.string() — add .max(n) (or a bounded format)',
  'BigQuery: getQueryResults.input.projectId: unbounded z.string() — add .max(n) (or a bounded format)',
  'BigQuery: getQueryResults.input.location: unbounded z.string() — add .max(n) (or a bounded format)',
  'BigQuery: getQueryResults.input.pageToken: unbounded z.string() — add .max(n) (or a bounded format)',
  'BigQuery: listDatasets.input.projectId: unbounded z.string() — add .max(n) (or a bounded format)',
  'BigQuery: listDatasets.input.pageToken: unbounded z.string() — add .max(n) (or a bounded format)',
  'Box: aiQaMultiFile.input.fileIds: unbounded z.array() — add .max(n) on the element count',
  'Box: callTool.input.arguments: record key is an unbounded string — bound it with .max(n)',
  'Box: callTool.input.arguments: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'BraveSearchConnector: webSearch.input.q: unbounded z.string() — add .max(n) (or a bounded format)',
  'Buildkite: getBuild.input.buildNumber|0: unbounded z.string() — add .max(n) (or a bounded format)',
  'Buildkite: cancelBuild.input.buildNumber|0: unbounded z.string() — add .max(n) (or a bounded format)',
  'Buildkite: rebuild.input.buildNumber|0: unbounded z.string() — add .max(n) (or a bounded format)',
  'Buildkite: retryFailedJobs.input.buildNumber|0: unbounded z.string() — add .max(n) (or a bounded format)',
  'Buildkite: listJobs.input.buildNumber|0: unbounded z.string() — add .max(n) (or a bounded format)',
  'Buildkite: unblockJob.input.buildNumber|0: unbounded z.string() — add .max(n) (or a bounded format)',
  'Buildkite: retryJob.input.buildNumber|0: unbounded z.string() — add .max(n) (or a bounded format)',
  'Buildkite: getJobLog.input.buildNumber|0: unbounded z.string() — add .max(n) (or a bounded format)',
  'Buildkite: createBuildAnnotation.input.buildNumber|0: unbounded z.string() — add .max(n) (or a bounded format)',
  'Buildkite: listBuildAnnotations.input.buildNumber|0: unbounded z.string() — add .max(n) (or a bounded format)',
  'Buildkite: listArtifacts.input.buildNumber|0: unbounded z.string() — add .max(n) (or a bounded format)',
  'ConfluenceCloudConnector: listPages.input.cursor: unbounded z.string() — add .max(n) (or a bounded format)',
  'ConfluenceCloudConnector: listPages.input.spaceId|0: unbounded z.string() — add .max(n) (or a bounded format)',
  'ConfluenceCloudConnector: listPages.input.spaceId|1: unbounded z.array() — add .max(n) on the element count',
  'ConfluenceCloudConnector: listPages.input.spaceId|1[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'ConfluenceCloudConnector: listPages.input.title: unbounded z.string() — add .max(n) (or a bounded format)',
  'ConfluenceCloudConnector: listPages.input.status|0: unbounded z.string() — add .max(n) (or a bounded format)',
  'ConfluenceCloudConnector: listPages.input.status|1: unbounded z.array() — add .max(n) on the element count',
  'ConfluenceCloudConnector: listPages.input.status|1[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'ConfluenceCloudConnector: listPages.input.bodyFormat: unbounded z.string() — add .max(n) (or a bounded format)',
  'ConfluenceCloudConnector: getPage.input.id: unbounded z.string() — add .max(n) (or a bounded format)',
  'ConfluenceCloudConnector: getPage.input.bodyFormat: unbounded z.string() — add .max(n) (or a bounded format)',
  'ConfluenceCloudConnector: listSpaces.input.cursor: unbounded z.string() — add .max(n) (or a bounded format)',
  'ConfluenceCloudConnector: listSpaces.input.ids|0: unbounded z.string() — add .max(n) (or a bounded format)',
  'ConfluenceCloudConnector: listSpaces.input.ids|1: unbounded z.array() — add .max(n) on the element count',
  'ConfluenceCloudConnector: listSpaces.input.ids|1[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'ConfluenceCloudConnector: listSpaces.input.keys|0: unbounded z.string() — add .max(n) (or a bounded format)',
  'ConfluenceCloudConnector: listSpaces.input.keys|1: unbounded z.array() — add .max(n) on the element count',
  'ConfluenceCloudConnector: listSpaces.input.keys|1[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'ConfluenceCloudConnector: listSpaces.input.type: unbounded z.string() — add .max(n) (or a bounded format)',
  'ConfluenceCloudConnector: listSpaces.input.status: unbounded z.string() — add .max(n) (or a bounded format)',
  'ConfluenceCloudConnector: getSpace.input.id: unbounded z.string() — add .max(n) (or a bounded format)',
  'Dropbox: search.input.fileExtensions: unbounded z.array() — add .max(n) on the element count',
  'Dropbox: search.input.fileCategories: unbounded z.array() — add .max(n) on the element count',
  'Dropbox: callTool.input.arguments: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'FigmaConnector: getFile.input.fileKey: unbounded z.string() — add .max(n) (or a bounded format)',
  'FigmaConnector: getFile.input.nodeIds: unbounded z.string() — add .max(n) (or a bounded format)',
  'FigmaConnector: renderNodes.input.fileKey: unbounded z.string() — add .max(n) (or a bounded format)',
  'FigmaConnector: renderNodes.input.nodeIds: unbounded z.string() — add .max(n) (or a bounded format)',
  'FigmaConnector: listProjectFiles.input.projectId: unbounded z.string() — add .max(n) (or a bounded format)',
  'FigmaConnector: listTeamProjects.input.teamId: unbounded z.string() — add .max(n) (or a bounded format)',
  'FigmaConnector: listTeamProjects.input.url: unbounded z.string() — add .max(n) (or a bounded format)',
  'FirecrawlConnector: scrape.input.url: unbounded z.string() — add .max(n) (or a bounded format)',
  'FirecrawlConnector: search.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'FirecrawlConnector: map.input.url: unbounded z.string() — add .max(n) (or a bounded format)',
  'FirecrawlConnector: map.input.search: unbounded z.string() — add .max(n) (or a bounded format)',
  'FirecrawlConnector: crawl.input.url: unbounded z.string() — add .max(n) (or a bounded format)',
  'FirecrawlConnector: crawlAndWait.input.url: unbounded z.string() — add .max(n) (or a bounded format)',
  'GcpCloudFunctionsConnector: invoke.input.functionName: unbounded z.string() — add .max(n) (or a bounded format)',
  'GcpCloudFunctionsConnector: listFunctions.input.pageToken: unbounded z.string() — add .max(n) (or a bounded format)',
  'GcpCloudFunctionsConnector: getFunction.input.functionName: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: searchCode.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: searchRepositories.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: searchIssues.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: searchIssues.input.sort: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: searchPullRequests.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: searchPullRequests.input.sort: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: searchUsers.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: listIssues.input.owner: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: listIssues.input.repo: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: listIssues.input.after: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: listPullRequests.input.owner: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: listPullRequests.input.repo: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: listPullRequests.input.after: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: listCommits.input.owner: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: listCommits.input.repo: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: listCommits.input.sha: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: listCommits.input.after: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: listBranches.input.owner: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: listBranches.input.repo: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: listBranches.input.after: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: listReleases.input.owner: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: listReleases.input.repo: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: listReleases.input.after: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: listTags.input.owner: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: listTags.input.repo: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: listTags.input.after: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: getCommit.input.owner: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: getCommit.input.repo: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: getCommit.input.sha: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: getLatestRelease.input.owner: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: getLatestRelease.input.repo: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: pullRequestRead.input.owner: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: pullRequestRead.input.repo: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: getFileContents.input.owner: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: getFileContents.input.repo: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: getFileContents.input.path: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: getFileContents.input.ref: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: getIssue.input.owner: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: getIssue.input.repo: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: getIssueComments.input.owner: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: getIssueComments.input.repo: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: callTool.input.name: unbounded z.string() — add .max(n) (or a bounded format)',
  'GithubConnector: callTool.input.arguments: record key is an unbounded string — bound it with .max(n)',
  'GithubConnector: callTool.input.arguments: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'GmailConnector: searchMessages.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'GmailConnector: searchMessages.input.pageToken: unbounded z.string() — add .max(n) (or a bounded format)',
  'GmailConnector: getMessage.input.messageId: unbounded z.string() — add .max(n) (or a bounded format)',
  'GmailConnector: getAttachment.input.messageId: unbounded z.string() — add .max(n) (or a bounded format)',
  'GmailConnector: getAttachment.input.attachmentId: unbounded z.string() — add .max(n) (or a bounded format)',
  'GmailConnector: listMessages.input.pageToken: unbounded z.string() — add .max(n) (or a bounded format)',
  'GmailConnector: listMessages.input.labelIds: unbounded z.array() — add .max(n) on the element count',
  'GmailConnector: listMessages.input.labelIds[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleCalendar: searchEvents.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleCalendar: searchEvents.input.timeMin: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleCalendar: searchEvents.input.timeMax: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleCalendar: getEvent.input.eventId: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleCalendar: listCalendars.input.pageToken: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleCalendar: listEvents.input.timeMin: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleCalendar: listEvents.input.timeMax: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleCalendar: listEvents.input.pageToken: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleCalendar: freeBusy.input.timeMin: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleCalendar: freeBusy.input.timeMax: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleCalendar: freeBusy.input.calendarIds: unbounded z.array() — add .max(n) on the element count',
  'GoogleCalendar: freeBusy.input.calendarIds[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleCloudStorageConnector: listProjects.input.pageToken: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleCloudStorageConnector: listProjects.input.filter: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleCloudStorageConnector: listBuckets.input.project: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleCloudStorageConnector: listBuckets.input.pageToken: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleCloudStorageConnector: listBuckets.input.prefix: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleCloudStorageConnector: listObjects.input.bucket: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleCloudStorageConnector: listObjects.input.prefix: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleCloudStorageConnector: listObjects.input.delimiter: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleCloudStorageConnector: listObjects.input.pageToken: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleCloudStorageConnector: getObjectMetadata.input.bucket: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleCloudStorageConnector: getObjectMetadata.input.object: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleCloudStorageConnector: downloadObject.input.bucket: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleCloudStorageConnector: downloadObject.input.object: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleDriveConnector: searchFiles.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleDriveConnector: searchFiles.input.pageToken: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleDriveConnector: listFiles.input.pageToken: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleDriveConnector: downloadFile.input.fileId: unbounded z.string() — add .max(n) (or a bounded format)',
  'GoogleDriveConnector: getFileMetadata.input.fileIds: unbounded z.array() — add .max(n) on the element count',
  'GoogleDriveConnector: getFileMetadata.input.fileIds[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'HubSpotConnector: searchCrmObjects.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'HubSpotConnector: searchCrmObjects.input.properties: unbounded z.array() — add .max(n) on the element count',
  'HubSpotConnector: searchCrmObjects.input.properties[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'HubSpotConnector: searchCrmObjects.input.after: unbounded z.string() — add .max(n) (or a bounded format)',
  'HubSpotConnector: getCrmObject.input.objectId: unbounded z.string() — add .max(n) (or a bounded format)',
  'HubSpotConnector: getCrmObject.input.properties: unbounded z.array() — add .max(n) on the element count',
  'HubSpotConnector: getCrmObject.input.properties[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'HubSpotConnector: listOwners.input.after: unbounded z.string() — add .max(n) (or a bounded format)',
  'HubSpotConnector: searchDeals.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'HubSpotConnector: searchDeals.input.pipeline: unbounded z.string() — add .max(n) (or a bounded format)',
  'HubSpotConnector: searchDeals.input.dealStage: unbounded z.string() — add .max(n) (or a bounded format)',
  'HubSpotConnector: searchDeals.input.ownerId: unbounded z.string() — add .max(n) (or a bounded format)',
  'HubSpotConnector: searchDeals.input.after: unbounded z.string() — add .max(n) (or a bounded format)',
  'HubSpotConnector: searchBroad.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'JinaReaderConnector: browse.input.url: unbounded z.string() — add .max(n) (or a bounded format)',
  'JinaReaderConnector: browse.input.options: record key is an unbounded string — bound it with .max(n)',
  'JinaReaderConnector: browse.input.options: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'JinaReaderConnector: search.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'JinaReaderConnector: search.input.options: record key is an unbounded string — bound it with .max(n)',
  'JinaReaderConnector: search.input.options: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'JinaReaderConnector: fileToMarkdown.input.file: unbounded z.string() — add .max(n) (or a bounded format)',
  'JinaReaderConnector: fileToMarkdown.input.filename: unbounded z.string() — add .max(n) (or a bounded format)',
  'JinaReaderConnector: fileToMarkdown.input.options: record key is an unbounded string — bound it with .max(n)',
  'JinaReaderConnector: fileToMarkdown.input.options: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'JinaReaderConnector: fileToRenderedImage.input.file: unbounded z.string() — add .max(n) (or a bounded format)',
  'JinaReaderConnector: fileToRenderedImage.input.filename: unbounded z.string() — add .max(n) (or a bounded format)',
  'JinaReaderConnector: fileToRenderedImage.input.options: record key is an unbounded string — bound it with .max(n)',
  'JinaReaderConnector: fileToRenderedImage.input.options: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'JiraConnector: searchIssuesWithJql.input.jql: unbounded z.string() — add .max(n) (or a bounded format)',
  'JiraConnector: searchIssuesWithJql.input.nextPageToken: unbounded z.string() — add .max(n) (or a bounded format)',
  'JiraConnector: getIssue.input.issueId: unbounded z.string() — add .max(n) (or a bounded format)',
  'JiraConnector: getProjects.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'JiraConnector: getProject.input.projectId: unbounded z.string() — add .max(n) (or a bounded format)',
  'JiraConnector: searchUsers.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'JiraConnector: searchUsers.input.username: unbounded z.string() — add .max(n) (or a bounded format)',
  'JiraConnector: searchUsers.input.accountId: unbounded z.string() — add .max(n) (or a bounded format)',
  'JiraConnector: searchUsers.input.property: unbounded z.string() — add .max(n) (or a bounded format)',
  'KubernetesConnector: request.input.query: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'KubernetesConnector: createResource.input.manifest: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'KubernetesConnector: applyResource.input.manifest: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'KubernetesConnector: patchResource.input.patch|0: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'KubernetesConnector: patchResource.input.patch|1: unbounded z.array() — add .max(n) on the element count',
  'MicrosoftTeams: listJoinedTeams.input.userId: unbounded z.string() — add .max(n) (or a bounded format)',
  'MicrosoftTeams: listChannels.input.teamId: unbounded z.string() — add .max(n) (or a bounded format)',
  'MicrosoftTeams: listChannelMessages.input.teamId: unbounded z.string() — add .max(n) (or a bounded format)',
  'MicrosoftTeams: listChannelMessages.input.channelId: unbounded z.string() — add .max(n) (or a bounded format)',
  'MicrosoftTeams: listChats.input.userId: unbounded z.string() — add .max(n) (or a bounded format)',
  'MicrosoftTeams: listChatMessages.input.chatId: unbounded z.string() — add .max(n) (or a bounded format)',
  'MicrosoftTeams: searchMessages.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'MondayCom: createItem.input.columnValues: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'MondayCom: changeItemColumnValues.input.columnValues: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'MondayCom: createSubitem.input.columnValues: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'MondayCom: callTool.input.arguments: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'NewRelic: listIssues.input.states: unbounded z.array() — add .max(n) on the element count',
  'NewRelic: listIssues.input.priority: unbounded z.array() — add .max(n) on the element count',
  'NewRelic: listIncidents.input.states: unbounded z.array() — add .max(n) on the element count',
  'NewRelic: listIncidents.input.priority: unbounded z.array() — add .max(n) on the element count',
  'NotionConnector: searchPageOrDSByTitle.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'NotionConnector: searchPageOrDSByTitle.input.startCursor: unbounded z.string() — add .max(n) (or a bounded format)',
  'NotionConnector: getPage.input.pageId: unbounded z.string() — add .max(n) (or a bounded format)',
  'NotionConnector: getDataSource.input.dataSourceId: unbounded z.string() — add .max(n) (or a bounded format)',
  'NotionConnector: queryDataSource.input.dataSourceId: unbounded z.string() — add .max(n) (or a bounded format)',
  'NotionConnector: queryDataSource.input.filter: unbounded z.string() — add .max(n) (or a bounded format)',
  'NotionConnector: queryDataSource.input.startCursor: unbounded z.string() — add .max(n) (or a bounded format)',
  'OnePasswordConnector: listUsers.input.pageToken: unbounded z.string() — add .max(n) (or a bounded format)',
  'OnePasswordConnector: getUser.input.uuid: unbounded z.string() — add .max(n) (or a bounded format)',
  'OnePasswordConnector: suspendUser.input.uuid: unbounded z.string() — add .max(n) (or a bounded format)',
  'OnePasswordConnector: reactivateUser.input.uuid: unbounded z.string() — add .max(n) (or a bounded format)',
  'Outlook: searchMessages.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'Outlook: listMessages.input.folderId: unbounded z.string() — add .max(n) (or a bounded format)',
  'Outlook: listMessages.input.filter: unbounded z.string() — add .max(n) (or a bounded format)',
  'Outlook: listMessages.input.orderby: unbounded z.string() — add .max(n) (or a bounded format)',
  'Outlook: getMessage.input.messageId: unbounded z.string() — add .max(n) (or a bounded format)',
  'Outlook: listAttachments.input.messageId: unbounded z.string() — add .max(n) (or a bounded format)',
  'Outlook: getAttachment.input.messageId: unbounded z.string() — add .max(n) (or a bounded format)',
  'Outlook: getAttachment.input.attachmentId: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: listSchedules.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: listSchedules.input.include: unbounded z.array() — add .max(n) on the element count',
  'PagerdutyConnector: listSchedules.input.include[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: listSchedules.input.team_ids: unbounded z.array() — add .max(n) on the element count',
  'PagerdutyConnector: listSchedules.input.team_ids[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: listSchedules.input.user_ids: unbounded z.array() — add .max(n) on the element count',
  'PagerdutyConnector: listSchedules.input.user_ids[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: listEscalationPolicies.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: listEscalationPolicies.input.user_ids: unbounded z.array() — add .max(n) on the element count',
  'PagerdutyConnector: listEscalationPolicies.input.user_ids[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: listEscalationPolicies.input.team_ids: unbounded z.array() — add .max(n) on the element count',
  'PagerdutyConnector: listEscalationPolicies.input.team_ids[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: listIncidents.input.status: unbounded z.array() — add .max(n) on the element count',
  'PagerdutyConnector: listIncidents.input.status[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: listIncidents.input.service_ids: unbounded z.array() — add .max(n) on the element count',
  'PagerdutyConnector: listIncidents.input.service_ids[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: listIncidents.input.user_ids: unbounded z.array() — add .max(n) on the element count',
  'PagerdutyConnector: listIncidents.input.user_ids[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: listIncidents.input.since: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: listIncidents.input.until: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: listIncidents.input.urgencies: unbounded z.array() — add .max(n) on the element count',
  'PagerdutyConnector: listIncidents.input.urgencies[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: listIncidents.input.sort_by: unbounded z.array() — add .max(n) on the element count',
  'PagerdutyConnector: listIncidents.input.sort_by[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: listOncalls.input.schedule_ids: unbounded z.array() — add .max(n) on the element count',
  'PagerdutyConnector: listOncalls.input.schedule_ids[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: listOncalls.input.user_ids: unbounded z.array() — add .max(n) on the element count',
  'PagerdutyConnector: listOncalls.input.user_ids[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: listOncalls.input.escalation_policy_ids: unbounded z.array() — add .max(n) on the element count',
  'PagerdutyConnector: listOncalls.input.escalation_policy_ids[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: listOncalls.input.since: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: listOncalls.input.until: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: listOncalls.input.time_zone: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: listUsers.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: listTeams.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: getSchedule.input.schedule_id: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: getIncident.input.incident_id: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: getEscalationPolicy.input.policy_id: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: getTeam.input.team_id: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: callTool.input.name: unbounded z.string() — add .max(n) (or a bounded format)',
  'PagerdutyConnector: callTool.input.arguments: record key is an unbounded string — bound it with .max(n)',
  'PagerdutyConnector: callTool.input.arguments: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'PostHog: createExternalReference.input.config: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'SalesforceConnector: query.input.soql: unbounded z.string() — add .max(n) (or a bounded format)',
  'SalesforceConnector: query.input.nextRecordsUrl: unbounded z.string() — add .max(n) (or a bounded format)',
  'SalesforceConnector: get_record.input.sobjectName: unbounded z.string() — add .max(n) (or a bounded format)',
  'SalesforceConnector: get_record.input.recordId: unbounded z.string() — add .max(n) (or a bounded format)',
  'SalesforceConnector: list_records.input.sobjectName: unbounded z.string() — add .max(n) (or a bounded format)',
  'SalesforceConnector: list_records.input.nextRecordsUrl: unbounded z.string() — add .max(n) (or a bounded format)',
  'SalesforceConnector: search.input.searchTerm: unbounded z.string() — add .max(n) (or a bounded format)',
  'SalesforceConnector: search.input.returning: unbounded z.string() — add .max(n) (or a bounded format)',
  'SalesforceConnector: search.input.nextRecordsUrl: unbounded z.string() — add .max(n) (or a bounded format)',
  'SalesforceConnector: describe.input.sobjectName: unbounded z.string() — add .max(n) (or a bounded format)',
  'SalesforceConnector: download_file.input.contentVersionId: unbounded z.string() — add .max(n) (or a bounded format)',
  'Sentry: createIssueAlertRule.input.conditions: unbounded z.array() — add .max(n) on the element count',
  'Sentry: createIssueAlertRule.input.conditions[]: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'Sentry: createIssueAlertRule.input.actions: unbounded z.array() — add .max(n) on the element count',
  'Sentry: createIssueAlertRule.input.actions[]: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'Sentry: updateIssueAlertRule.input.conditions: unbounded z.array() — add .max(n) on the element count',
  'Sentry: updateIssueAlertRule.input.conditions[]: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'Sentry: updateIssueAlertRule.input.actions: unbounded z.array() — add .max(n) on the element count',
  'Sentry: updateIssueAlertRule.input.actions[]: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'ServicenowSearch: search.input.table: unbounded z.string() — add .max(n) (or a bounded format)',
  'ServicenowSearch: search.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'ServicenowSearch: search.input.encodedQuery: unbounded z.string() — add .max(n) (or a bounded format)',
  'ServicenowSearch: search.input.fields: unbounded z.string() — add .max(n) (or a bounded format)',
  'ServicenowSearch: getRecord.input.table: unbounded z.string() — add .max(n) (or a bounded format)',
  'ServicenowSearch: getRecord.input.sysId: unbounded z.string() — add .max(n) (or a bounded format)',
  'ServicenowSearch: getRecord.input.fields: unbounded z.string() — add .max(n) (or a bounded format)',
  'ServicenowSearch: listRecords.input.table: unbounded z.string() — add .max(n) (or a bounded format)',
  'ServicenowSearch: listRecords.input.encodedQuery: unbounded z.string() — add .max(n) (or a bounded format)',
  'ServicenowSearch: listRecords.input.fields: unbounded z.string() — add .max(n) (or a bounded format)',
  'ServicenowSearch: listRecords.input.orderBy: unbounded z.string() — add .max(n) (or a bounded format)',
  'ServicenowSearch: listTables.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'ServicenowSearch: getComments.input.tableName: unbounded z.string() — add .max(n) (or a bounded format)',
  'ServicenowSearch: getComments.input.recordSysId: unbounded z.string() — add .max(n) (or a bounded format)',
  'ServicenowSearch: getAttachment.input.sysId: unbounded z.string() — add .max(n) (or a bounded format)',
  'ServicenowSearch: describeTable.input.table: unbounded z.string() — add .max(n) (or a bounded format)',
  'SharepointOnline: getAllSites.input.search: unbounded z.string() — add .max(n) (or a bounded format)',
  'SharepointOnline: getSitePages.input.siteId: unbounded z.string() — add .max(n) (or a bounded format)',
  'SharepointOnline: getSitePageContents.input.siteId: unbounded z.string() — add .max(n) (or a bounded format)',
  'SharepointOnline: getSitePageContents.input.pageId: unbounded z.string() — add .max(n) (or a bounded format)',
  'SharepointOnline: getSite.input|0.siteId: unbounded z.string() — add .max(n) (or a bounded format)',
  'SharepointOnline: getSite.input|1.relativeUrl: unbounded z.string() — add .max(n) (or a bounded format)',
  'SharepointOnline: getSiteDrives.input.siteId: unbounded z.string() — add .max(n) (or a bounded format)',
  'SharepointOnline: getSiteLists.input.siteId: unbounded z.string() — add .max(n) (or a bounded format)',
  'SharepointOnline: getSiteListItems.input.siteId: unbounded z.string() — add .max(n) (or a bounded format)',
  'SharepointOnline: getSiteListItems.input.listId: unbounded z.string() — add .max(n) (or a bounded format)',
  'SharepointOnline: getDriveItems.input.driveId: unbounded z.string() — add .max(n) (or a bounded format)',
  'SharepointOnline: getDriveItems.input.path: unbounded z.string() — add .max(n) (or a bounded format)',
  'SharepointOnline: downloadDriveItem.input.driveId: unbounded z.string() — add .max(n) (or a bounded format)',
  'SharepointOnline: downloadDriveItem.input.itemId: unbounded z.string() — add .max(n) (or a bounded format)',
  'SharepointOnline: downloadItemFromURL.input.downloadUrl: unbounded z.string() — add .max(n) (or a bounded format)',
  'SharepointOnline: callGraphAPI.input.path: unbounded z.string() — add .max(n) (or a bounded format)',
  'SharepointOnline: callGraphAPI.input.query: record key is an unbounded string — bound it with .max(n)',
  'SharepointOnline: callGraphAPI.input.query: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'SharepointOnline: callGraphAPI.input.query.<value>|0: unbounded z.string() — add .max(n) (or a bounded format)',
  'SharepointOnline: search.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'SharepointOnline: search.input.entityTypes: unbounded z.array() — add .max(n) on the element count',
  'SharepointServer: getListItems.input.listTitle: unbounded z.string() — add .max(n) (or a bounded format)',
  'SharepointServer: getFolderContents.input.path: unbounded z.string() — add .max(n) (or a bounded format)',
  'SharepointServer: downloadFile.input.path: unbounded z.string() — add .max(n) (or a bounded format)',
  'SharepointServer: search.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'SharepointServer: callRestApi.input.path: unbounded z.string() — add .max(n) (or a bounded format)',
  'ShodanConnector: searchHosts.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'ShodanConnector: countResults.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'ShodanConnector: countResults.input.facets: unbounded z.string() — add .max(n) (or a bounded format)',
  'Slack: searchMessages.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'Slack: searchMessages.input.inChannel: unbounded z.string() — add .max(n) (or a bounded format)',
  'Slack: searchMessages.input.fromUser: unbounded z.string() — add .max(n) (or a bounded format)',
  'Slack: searchMessages.input.after: unbounded z.string() — add .max(n) (or a bounded format)',
  'Slack: searchMessages.input.before: unbounded z.string() — add .max(n) (or a bounded format)',
  'Slack: searchMessages.input.cursor: unbounded z.string() — add .max(n) (or a bounded format)',
  'Slack: listChannels.input.types: unbounded z.array() — add .max(n) on the element count',
  'Slack: listChannels.input.cursor: unbounded z.string() — add .max(n) (or a bounded format)',
  'Slack: resolveChannelId.input.name: unbounded z.string() — add .max(n) (or a bounded format)',
  'Slack: resolveChannelId.input.types: unbounded z.array() — add .max(n) on the element count',
  'Slack: resolveChannelId.input.cursor: unbounded z.string() — add .max(n) (or a bounded format)',
  'Slack: listUserConversations.input.types: unbounded z.array() — add .max(n) on the element count',
  'Slack: createConversation.input.name: unbounded z.string() — add .max(n) (or a bounded format)',
  'Slack: inviteToConversation.input.channel: unbounded z.string() — add .max(n) (or a bounded format)',
  'Slack: inviteToConversation.input.users: unbounded z.string() — add .max(n) (or a bounded format)',
  'Slack: sendMessage.input.channel: unbounded z.string() — add .max(n) (or a bounded format)',
  'Slack: sendMessage.input.text: unbounded z.string() — add .max(n) (or a bounded format)',
  'Slack: sendMessage.input.threadTs: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: runQuery.input.statement: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: runQuery.input.database: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: runQuery.input.schema: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: runQuery.input.warehouse: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: runQuery.input.role: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: runQuery.input.bindings: record key is an unbounded string — bound it with .max(n)',
  'Snowflake: runQuery.input.bindings: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'Snowflake: runQuery.input.bindings.<value>.value: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: runQuery.input.queryTag: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: executeStatement.input.statement: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: executeStatement.input.database: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: executeStatement.input.schema: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: executeStatement.input.warehouse: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: executeStatement.input.role: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: executeStatement.input.bindings: record key is an unbounded string — bound it with .max(n)',
  'Snowflake: executeStatement.input.bindings: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'Snowflake: executeStatement.input.bindings.<value>.value: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: executeStatement.input.queryTag: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: getStatementStatus.input.statementHandle: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: cancelStatement.input.statementHandle: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: listDatabases.input.like: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: listDatabases.input.startsWith: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: listDatabases.input.fromName: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: listSchemas.input.like: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: listSchemas.input.startsWith: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: listSchemas.input.fromName: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: listSchemas.input.database: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: listTables.input.like: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: listTables.input.startsWith: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: listTables.input.fromName: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: listTables.input.database: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: listTables.input.schema: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: listViews.input.like: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: listViews.input.startsWith: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: listViews.input.fromName: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: listViews.input.database: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: listViews.input.schema: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: describeTable.input.database: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: describeTable.input.schema: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: describeTable.input.name: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: describeView.input.database: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: describeView.input.schema: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: describeView.input.name: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: listCortexSearchServices.input.like: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: listCortexSearchServices.input.fromName: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: listCortexSearchServices.input.database: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: listCortexSearchServices.input.schema: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: cortexSearch.input.database: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: cortexSearch.input.schema: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: cortexSearch.input.serviceName: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: cortexSearch.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: cortexSearch.input.columns: unbounded z.array() — add .max(n) on the element count',
  'Snowflake: cortexSearch.input.columns[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'Snowflake: cortexSearch.input.filter: record key is an unbounded string — bound it with .max(n)',
  'Snowflake: cortexSearch.input.filter: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'TavilyConnector: tavilySearch.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'TavilyConnector: tavilyExtract.input.urls: unbounded z.array() — add .max(n) on the element count',
  'TavilyConnector: tavilyExtract.input.urls[]: unbounded z.string() — add .max(n) (or a bounded format)',
  'TavilyConnector: tavilyCrawl.input.url: unbounded z.string() — add .max(n) (or a bounded format)',
  'TavilyConnector: tavilyCrawl.input.instructions: unbounded z.string() — add .max(n) (or a bounded format)',
  'TavilyConnector: tavilyMap.input.url: unbounded z.string() — add .max(n) (or a bounded format)',
  'TavilyConnector: tavilyMap.input.instructions: unbounded z.string() — add .max(n) (or a bounded format)',
  'TavilyConnector: callTool.input.name: unbounded z.string() — add .max(n) (or a bounded format)',
  'TavilyConnector: callTool.input.arguments: record key is an unbounded string — bound it with .max(n)',
  'TavilyConnector: callTool.input.arguments: record entry count is unbounded — add .refine((v) => Object.keys(v).length <= n, ...)',
  'URLVoidConnector: scanDomain.input.domain: unbounded z.string() — add .max(n) (or a bounded format)',
  'URLVoidConnector: checkUrl.input.url: unbounded z.string() — add .max(n) (or a bounded format)',
  'URLVoidConnector: getDomainInfo.input.domain: unbounded z.string() — add .max(n) (or a bounded format)',
  'VirusTotalConnector: scanFileHash.input.hash: unbounded z.string() — add .max(n) (or a bounded format)',
  'VirusTotalConnector: scanUrl.input.url|0: unbounded z.string() — add .max(n) (or a bounded format)',
  'VirusTotalConnector: scanUrl.input.url|1: unbounded z.string() — add .max(n) (or a bounded format)',
  'VirusTotalConnector: getAnalysisResults.input.id: unbounded z.string() — add .max(n) (or a bounded format)',
  'VirusTotalConnector: submitFile.input.file: unbounded z.string() — add .max(n) (or a bounded format)',
  'VirusTotalConnector: submitFile.input.filename: unbounded z.string() — add .max(n) (or a bounded format)',
  'ZendeskConnector: search.input.query: unbounded z.string() — add .max(n) (or a bounded format)',
  'ZendeskConnector: search.input.sortBy: unbounded z.string() — add .max(n) (or a bounded format)',
  'ZendeskConnector: search.input.include: unbounded z.string() — add .max(n) (or a bounded format)',
  'ZendeskConnector: listTickets.input.include: unbounded z.string() — add .max(n) (or a bounded format)',
  'ZendeskConnector: getTicket.input.ticketId: unbounded z.string() — add .max(n) (or a bounded format)',
  'ZendeskConnector: getTicketComments.input.ticketId: unbounded z.string() — add .max(n) (or a bounded format)',
  'ZendeskConnector: getTicketComments.input.include: unbounded z.string() — add .max(n) (or a bounded format)',
  'Zoom: listMeetings.input.userId: unbounded z.string() — add .max(n) (or a bounded format)',
  'Zoom: listMeetings.input.nextPageToken: unbounded z.string() — add .max(n) (or a bounded format)',
  'Zoom: getMeetingDetails.input.meetingId: unbounded z.string() — add .max(n) (or a bounded format)',
  'Zoom: getPastMeetingDetails.input.meetingId: unbounded z.string() — add .max(n) (or a bounded format)',
  'Zoom: getMeetingRecordings.input.meetingId: unbounded z.string() — add .max(n) (or a bounded format)',
  'Zoom: listUserRecordings.input.userId: unbounded z.string() — add .max(n) (or a bounded format)',
  'Zoom: listUserRecordings.input.from: unbounded z.string() — add .max(n) (or a bounded format)',
  'Zoom: listUserRecordings.input.to: unbounded z.string() — add .max(n) (or a bounded format)',
  'Zoom: listUserRecordings.input.nextPageToken: unbounded z.string() — add .max(n) (or a bounded format)',
  'Zoom: downloadRecordingFile.input.downloadUrl: unbounded z.string() — add .max(n) (or a bounded format)',
  'Zoom: getMeetingParticipants.input.meetingId: unbounded z.string() — add .max(n) (or a bounded format)',
  'Zoom: getMeetingParticipants.input.nextPageToken: unbounded z.string() — add .max(n) (or a bounded format)',
  'Zoom: getMeetingRegistrants.input.meetingId: unbounded z.string() — add .max(n) (or a bounded format)',
  'Zoom: getMeetingRegistrants.input.nextPageToken: unbounded z.string() — add .max(n) (or a bounded format)',
];
