openapi: 3.0.0
info:
  title: List Evals Evaluators API endpoint
  version: '1'
paths:
  /internal/evals/evaluators:
    get:
      x-codegen-enabled: true
      x-labels: [ess, serverless]
      operationId: ListEvaluators
      description: Lists available evaluators for the internal evals API
      summary: List evaluators
      tags:
        - Evals API
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  evaluators:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          maxLength: 256
                        version:
                          type: string
                          maxLength: 64
                        kind:
                          type: string
                          enum:
                            - llm
                            - code
                        description:
                          type: string
                          maxLength: 2048
                        reference_data_schema:
                          type: object
                          additionalProperties: true
                      required:
                        - name
                        - version
                        - kind
                        - description
                required:
                  - evaluators
