notify:
  - slack:
      channels:
        - '#kibana-operations-alerts'
    if: (build.branch == 'main' || build.branch =~ /^[0-9]+\.[0-9x]+\$/) && (build.state == 'passed' || build.state == 'failed')
  - slack:
      channels:
        - '#mission-control'
      message: |
        Kibana has been bumped to `${NEW_VERSION}` on branch `${BRANCH}` and a DRA build has begun.
        Build: ${BUILDKITE_BUILD_URL}
    if: build.state == "passed"

steps:
  - command: .buildkite/scripts/steps/version_bump/bump.sh
    key: bump-version
    label: Bump version
    agents:
      image: family/kibana-ubuntu-2404
      imageProject: elastic-images-prod
      provider: gcp
      machineType: n2-standard-4
    env:
      DRY_RUN: 'true'

  - wait

  - label: 'Fetch DRA Artifacts'
    key: fetch-dra-artifacts
    depends_on: bump-version
    agents:
      image: docker.elastic.co/release-eng/wolfi-build-essential-release-eng:latest
      cpu: 250m
      memory: 512Mi
      ephemeralStorage: 1Gi
    command:
      - echo "Starting DRA artifacts retrieval..."
    timeout_in_minutes: 240
    retry:
      automatic:
        - exit_status: '*'
          limit: 2
      manual:
        permit_on_passed: true

    plugins:
      - elastic/json-watcher#v1.0.0:
          url: 'https://artifacts-staging.elastic.co/kibana/latest/${BRANCH}.json'
          field: '.version'
          expected_value: '${NEW_VERSION}'
          polling_interval: '30'
      - elastic/json-watcher#v1.0.0:
          url: 'https://storage.googleapis.com/elastic-artifacts-snapshot/kibana/latest/${BRANCH}.json'
          field: '.version'
          expected_value: '${NEW_VERSION}-SNAPSHOT'
          polling_interval: '30'
