[[data-views-runtime-field-api-delete]]
=== Delete runtime field API
++++
<titleabbrev>Delete runtime field</titleabbrev>
++++

experimental[] Delete a runtime field from a data view.

[[data-views-runtime-field-api-delete-request]]
==== Request

`DELETE <kibana host>:<port>/api/data_views/data_view/<data_view_id>/runtime_field/<name>`

`DELETE <kibana host>:<port>/s/<space_id>/api/data_views/data_view/<data_view_id>/runtime_field/<name>`

[[data-views-runtime-field-api-delete-path-params]]
==== Path parameters

`space_id`::
(Optional, string) An identifier for the space. If `space_id` is not provided in the URL, the default space is used.

`data_view_id`::
(Required, string) The ID of the data view your want to delete a runtime field from.

`name`::
(Required, string) The name of the runtime field you want to delete.


==== Example

Delete a runtime field from a data view:

[source,sh]
--------------------------------------------------
$ curl -X DELETE api/data_views/data_view/<my-view>/runtime_field/<runtime-field-name>
--------------------------------------------------
// KIBANA


[discrete]
[[data-views-runtime-field-api-delete-deprecated]]
=== Delete runtime field API (deprecated)

[[data-views-runtime-field-api-delete-request-deprecated]]
==== Request

`DELETE <kibana host>:<port>/api/index_patterns/index_pattern/<index_pattern_id>/runtime_field/<name>`

`DELETE <kibana host>:<port>/s/<space_id>/api/index_patterns/index_pattern/<index_pattern_id>/runtime_field/<name>`

[[data-views-runtime-field-api-delete-path-params-deprecated]]
==== Path parameters

`space_id`::
(Optional, string) An identifier for the space. If `space_id` is not provided in the URL, the default space is used.

`index_pattern_id`::
(Required, string) The ID of the data view your want to delete a runtime field from.

`name`::
(Required, string) The name of the runtime field you want to delete.


==== Example

Delete a runtime field from a data view:

[source,sh]
--------------------------------------------------
$ curl -X DELETE api/index_patterns/index_pattern/<my-pattern>/runtime_field/<runtime-field-name>
--------------------------------------------------
// KIBANA