import React from 'react';
import type { RuleActionAlertsFilterProperty, RuleActionParam } from '@kbn/alerting-plugin/common';
import type { RuleAction, ActionTypeIndex, ActionConnector, ActionTypeRegistryContract, NotifyWhenSelectOptions } from '../../../types';
import type { ActionAccordionFormProps } from './action_form';
export type ActionTypeFormProps = {
    actionItem: RuleAction;
    actionConnector: ActionConnector;
    index: number;
    onAddConnector: () => void;
    onConnectorSelected: (id: string) => void;
    onDeleteAction: () => void;
    setActionUseAlertDataForTemplate?: (enabled: boolean, index: number) => void;
    setActionParamsProperty: (key: string, value: RuleActionParam, index: number) => void;
    setActionFrequencyProperty: (key: string, value: RuleActionParam, index: number) => void;
    setActionAlertsFilterProperty: (key: string, value: RuleActionAlertsFilterProperty, index: number) => void;
    actionTypesIndex: ActionTypeIndex;
    connectors: ActionConnector[];
    actionTypeRegistry: ActionTypeRegistryContract;
    recoveryActionGroup?: string;
    isActionGroupDisabledForActionType?: (actionGroupId: string, actionTypeId: string) => boolean;
    hideNotifyWhen?: boolean;
    hasAlertsMappings?: boolean;
    minimumThrottleInterval?: [number | undefined, string];
    notifyWhenSelectOptions?: NotifyWhenSelectOptions[];
    featureId: string;
    producerId: string;
    ruleTypeId?: string;
    disableErrorMessages?: boolean;
} & Pick<ActionAccordionFormProps, 'defaultActionGroupId' | 'actionGroups' | 'setActionGroupIdByIndex' | 'setActionParamsProperty' | 'messageVariables' | 'summaryMessageVariables' | 'defaultActionMessage' | 'defaultSummaryMessage'>;
export declare const ActionTypeForm: ({ actionItem, actionConnector, index, onAddConnector, onConnectorSelected, onDeleteAction, setActionUseAlertDataForTemplate, setActionParamsProperty, setActionFrequencyProperty, setActionAlertsFilterProperty, actionTypesIndex, connectors, defaultActionGroupId, defaultActionMessage, messageVariables, summaryMessageVariables, actionGroups, setActionGroupIdByIndex, actionTypeRegistry, isActionGroupDisabledForActionType, recoveryActionGroup, hideNotifyWhen, defaultSummaryMessage, hasAlertsMappings, minimumThrottleInterval, notifyWhenSelectOptions, producerId, featureId, ruleTypeId, disableErrorMessages, }: ActionTypeFormProps) => React.JSX.Element | null;
