ifdef::env-github[]
:es:              Elasticsearch
:kib:             Kibana
:branch:          master
:kibana-ref:      https://www.elastic.co/guide/en/kibana/{branch}
endif::[]

ifdef::env-github[]
NOTE: Links will only work when {kibana-ref}/kibana-dashboard.html[this page] is viewed in our {kibana-ref}/development.html[developer guide].
endif::[]

[[kibana-dashboard]]
== Dashboard

Dashboard is an application inside Kibana that allows users to create and view custom dashboards.

[discrete]
=== Dashboard panels

Dashboard panels are extensible via the <<embeddable-plugin>> API. The dashboard plugin itself
doesn't register any panels (although it is, itself, an Embeddable). These panel types (visualizations,
saved searches, maps, machine learning swimlanes, etc) are registered from other plugins.

[discrete]
=== Dashboard embeddable

Dashboard itself is also an Embeddable. This can be used to embed dashboards in other solutions.

You can view an example of this inside {kib-repo}blob/{branch}/examples/dashboard_embeddable_examples.

Just run Kibana with <<example-plugins>>.
