[role="xpack"]
[[email-action-type]]
=== Email action

The email action type uses the SMTP protocol to send mail message, using an integration of https://nodemailer.com/[Nodemailer]. Email message text is sent as both plain text and html text.

[float]
[[email-connector-configuration]]
==== Connector configuration

Email connectors have the following configuration properties:

Name::      The name of the connector. The name is used to identify a  connector in the management UI connector listing, or in the connector list when configuring an action.
Sender::    The from address for all emails sent with this connector, specified in `user@host-name` format.
Host::      Host name of the service provider. If you are using the <<action-settings, `xpack.actions.whitelistedHosts`>> setting, make sure this hostname is whitelisted.
Port::      The port to connect to on the service provider.
Secure::    If true the connection will use TLS when connecting to the service provider. See https://nodemailer.com/smtp/#tls-options[nodemailer TLS documentation] for more information.
Username::  username for 'login' type authentication.
Password::  password for 'login' type authentication.

[float]
[[Preconfigured-email-configuration]]
==== Preconfigured action type

[source,text]
--
 my-email:
   name: preconfigured-email-action-type
   actionTypeId: .email
   config:
     from: testsender@test.com
     host: validhostname
     port: 8080
     secure: false
   secrets:
     user: testuser
     password: passwordkeystorevalue
--

`config` defines the action type specific to the configuration and contains the following properties:

[cols="2*<"]
|===

| `from`
| An email address that corresponds to *Sender*.

| `host`
| A string that corresponds to *Host*.

| `port`
| A number that corresponds to *Port*.

| `secure`
| A boolean that corresponds to *Secure*.

|===

`secrets` defines sensitive information for the action type:

[cols="2*<"]
|===

| `user`
| A string that corresponds to *User*.

| `password`
| A string that corresponds to *Password*. Should be stored in the <<creating-keystore, {kib} keystore>>.

|===

[[email-action-configuration]]
==== Action configuration

Email actions have the following configuration properties:

To, CC, BCC::    Each is a list of addresses. Addresses can be specified in `user@host-name` format, or in `name <user@host-name>` format. One of To, CC, or BCC must contain an entry.
Subject::       The subject line of the email.
Message::       The message text of the email. Markdown format is supported.
