[role="xpack"]
[[index-action-type]]
=== Index action

The index action type will index a document into {es}.

[float]
[[index-connector-configuration]]
==== Connector configuration

Index connectors have the following configuration properties:

Name::      The name of the connector. The name is used to identify a  connector in the management UI connector listing, or in the connector list when configuring an action.
Index::     The {es} index to be written to.
Refresh::   Setting for the {ref}/docs-refresh.html[refresh] policy for the write request.
Execution time field::  This field will be automatically set to the time the alert condition was detected.

[float]
[[Preconfigured-index-configuration]]
==== Preconfigured action type properties: 

[source,text]
--
 id: 'my-index'
 name: action-type-index
 actionTypeId: .index
 config:
   index: .kibana
   refresh: true
   executionTimeField: somedate
--

`config:` define action type specific to the configuration. The config object contains the following properties:

[cols="3*<"]
|=====

|`index:`
 | String
 | correspond to *Index*.
|`refresh:`
 | Boolean
 | correspond to *Refresh*.
|`executionTimeField:`
 | String
 | correspond to *Execution time field*.

|=====


[float]
[[index-action-configuration]]
==== Action configuration

Index actions have the following properties:

Document::  The document to index in json format.
