[role="xpack"]
[[index-action-type]]
=== Index action

The index action type will index a document into {es}.

[float]
[[index-connector-configuration]]
==== Connector configuration

Index connectors have the following configuration properties:

Name::      The name of the connector. The name is used to identify a  connector in the management UI connector listing, or in the connector list when configuring an action.
Index::     The {es} index to be written to.
Refresh::   Setting for the {ref}/docs-refresh.html[refresh] policy for the write request.
Execution time field::  This field will be automatically set to the time the alert condition was detected.

[float]
[[Preconfigured-index-configuration]]
==== Preconfigured action type

[source,text]
--
 my-index:
   name: action-type-index
   actionTypeId: .index
   config:
     index: .kibana <1>
     refresh: true <2>
     executionTimeField: somedate <3>
--

`config` defines the action type specific to the configuration and contains the following properties:

<1> `index:` is a string and correspond to *Index*.
<2> `refresh:` is a boolean and correspond to *Refresh*.
<3> `executionTimeField:` is a string and correspond to *Execution time field*.


[float]
[[index-action-configuration]]
==== Action configuration

Index actions have the following properties:

Document::  The document to index in json format.
