[role="xpack"]
[[resilient-action-type]]
=== IBM Resilient action
++++
<titleabbrev>IBM Resilient</titleabbrev>
++++

The IBM Resilient action type uses the https://developer.ibm.com/security/resilient/rest/[RESILIENT REST v2] to create IBM Resilient incidents.

[float]
[[resilient-connector-configuration]]
==== Connector configuration

IBM Resilient connectors have the following configuration properties.

Name::      The name of the connector. The name is used to identify a  connector in the **Stack Management** UI connector listing, and in the connector list when configuring an action.
URL::       IBM Resilient instance URL.
Organization ID:: IBM Resilient organization ID.
API key ID::  The authentication key ID for HTTP Basic authentication.
API key secret::  The authentication key secret for HTTP Basic authentication.

[float]
[[Preconfigured-resilient-configuration]]
==== Preconfigured action type

[source,text]
--
 my-resilient:
   name: preconfigured-resilient-action-type
   actionTypeId: .resilient
   config:
     apiUrl: https://elastic.resilient.net
     orgId: ES
   secrets:
     apiKeyId: testuser
     apiKeySecret: tokenkeystorevalue
--

Config defines information for the action type.

`apiUrl`:: An address that corresponds to *URL*.
`orgId`:: An ID that corresponds to *Organization ID*.

Secrets defines sensitive information for the action type.

`apiKeyId`:: A string that corresponds to *API key ID*.
`apiKeySecret`:: A string that corresponds to *API Key secret*. Should be stored in the <<creating-keystore, {kib} keystore>>.

[float]
[[resilient-action-configuration]]
==== Action configuration

IBM Resilient actions have the following configuration properties.

Subaction::        The subaction to perform: `pushToService`, `getFields`, `incidentTypes`, or `severity`.
Subaction params:: The parameters of the subaction.

==== `pushToService` subaction configuration

Incident:: The IBM resilient incident has the following properties:
* `name` - A name for the issue, used for searching the contents of the knowledge base.
* `description` - The details about the incident.
* `externalId` - The ID of the incident in IBM Resilient. If present, the incident is updated. Otherwise, a new incident is created.
* `incidentTypes` - An array with the IDs of IBM Resilient incident types.
* `severityCode` - The IBM Resilient ID of the severity code.
Comments:: A comment in the form of `{ commentId: string, version: string, comment: string }`.

===== `getFields` subaction configuration

The `getFields` subaction has not parameters. Provide an empty object `{}`.

===== `incidentTypes` subaction configuration

The `incidentTypes` subaction has no parameters. Provide an empty object `{}`.

===== `severity` subaction configuration

The `severity` subaction has no parameters. Provide an empty object `{}`.

[[configuring-resilient]]
==== Configuring and testing IBM Resilient

IBM Resilient offers https://www.ibm.com/security/intelligent-orchestration/resilient[Instances], which you can use to test incidents.
