[role="xpack"]
[[servicenow-action-type]]
=== ServiceNow action
++++
<titleabbrev>ServiceNow</titleabbrev>
++++

The ServiceNow action type uses the https://developer.servicenow.com/app.do#!/rest_api_doc?v=orlando&id=c_TableAPI[V2 Table API] to create ServiceNow incidents.

[float]
[[servicenow-connector-configuration]]
==== Connector configuration

ServiceNow connectors have the following configuration properties.

Name::      The name of the connector. The name is used to identify a  connector in the **Stack Management** UI connector listing, and in the connector list when configuring an action.
URL::       ServiceNow instance URL.
Username::  Username for HTTP Basic authentication.
Password::  Password for HTTP Basic authentication.

[float]
[[Preconfigured-servicenow-configuration]]
==== Preconfigured action type

[source,text]
--
 my-servicenow:
   name: preconfigured-servicenow-action-type
   actionTypeId: .servicenow
   config:
     apiUrl: https://dev94428.service-now.com/
   secrets:
     username: testuser
     password: passwordkeystorevalue
--

Config defines information for the action type.

`apiUrl`:: An address that corresponds to *URL*.

Secrets defines sensitive information for the action type.

`username`:: A string that corresponds to *Username*.
`password`::  A string that corresponds to *Password*. Should be stored in the <<creating-keystore, {kib} keystore>>.

[float]
[[servicenow-action-configuration]]
==== Action configuration

ServiceNow actions have the following configuration properties.

Subaction::        The subaction to perform: `pushToService`, `getFields`, `getIncident`, or `getChoices`.
Subaction params:: The parameters of the subaction.

==== `pushToService` subaction configuration

Incident:: The ServiceNow incident has the following properties:
* `short_description` - A short description for the incident, used for searching the contents of the knowledge base.
* `description` - The details about the incident.
* `externalId` - The ID of the incident in ServiceNow. If present, the incident is updated. Otherwise, a new incident is created.
* `severity` - The severity of the incident.
* `urgency` - The extent to which the incident resolution can delay.
* `impact` - The effect an incident has on business. Can be measured by the number of affected users or by how critical it is to the business in question.
* `category` - The name of the category in ServiceNow.
* `subcategory` - The name of the subcategory in ServiceNow.
Comments:: A comment in the form of `{ commentId: string, version: string, comment: string }`.

===== `getFields` subaction configuration

The `getFields` subaction has no parameters. Provide an empty object `{}`.

===== `getIncident` subaction configuration

External ID:: The ID of the incident in ServiceNow.

===== `getChoices` subaction configuration

Fields:: An array of fields. Example: `[priority, category, impact]`.

[[configuring-servicenow]]
==== Configure ServiceNow

ServiceNow offers free https://developer.servicenow.com/dev.do#!/guides/madrid/now-platform/pdi-guide/obtaining-a-pdi[Personal Developer Instances], which you can use to test incidents.
