[role="xpack"]
[[servicenow-action-type]]
=== ServiceNow action

ServiceNow action type using https://developer.servicenow.com/app.do#!/rest_api_doc?v=orlando&id=c_TableAPI[V2 Table API] to create ServiceNow incidents.

[float]
[[servicenow-connector-configuration]]
==== Connector configuration

ServiceNow connectors have the following configuration properties:

Name::      The name of the connector. The name is used to identify a  connector in the management UI connector listing, or in the connector list when configuring an action.
URL::       ServiceNow instance URL.
Username::  Username for HTTP Basic authentication.
Password::  Password for HTTP Basic authentication.

[float]
[[Preconfigured-servicenow-configuration]]
==== Preconfigured action type

[source,text]
--
 my-servicenow:
   name: preconfigured-servicenow-action-type
   actionTypeId: .servicenow
   config:
     apiUrl: https://dev94428.service-now.com/
   secrets:
     username: testuser
     password: passwordkeystorevalue
--

`config` defines the action type specific to the configuration and contains the following properties:

[cols="2*<"]
|===

| `apiUrl`
| An address that corresponds to *Sender*.

|===

`secrets` defines sensitive information for the action type:

[cols="2*<"]
|===

| `username`
| A string that corresponds to *User*.

| `password`
| A string that corresponds to *Password*. Should be stored in the <<creating-keystore, {kib} keystore>>.

|===

[[servicenow-action-configuration]]
==== Action configuration

ServiceNow actions have the following configuration properties:

Urgency::              The extent to which the incident's resolution can bear delay.
Severity::             The severity value of the incident.
Impact::               The effect an incident has on business. Can be measured by number of users affected or by the criticality of the business system in question.
Short description::    A short text field to describe the incident. The book icon will search the knowledge base using the contents of the short description. 
Description::          The details about the incident issue in question.
Additional comments::  The additional instructions or other information meant for the client, and any work notes or steps shoudl be taken to troubleshoot the issue.

[[configuring-servicenow]]
==== Configuring and testing ServiceNow

ServiceNow offers free https://developer.servicenow.com/dev.do#!/guides/madrid/now-platform/pdi-guide/obtaining-a-pdi[Personal Developer Instances], which you can use to test incidents.
