[role="xpack"]
[[servicenow-action-type]]
=== ServiceNow action
++++
<titleabbrev>ServiceNow</titleabbrev>
++++

The {sn} action type uses the https://docs.servicenow.com/bundle/sandiego-application-development/page/integrate/inbound-rest/concept/c_TableAPI.html[V2 Table API] to create {sn} incidents. The {sn-itsm} connector can be used for rule actions and cases. The {sn-sir} connector can only be used for cases.

[float]
[[servicenow-connector-configuration]]
==== Connector configuration

ServiceNow connectors have the following configuration properties.

Name::      The name of the connector. The name is used to identify a  connector in the **Stack Management** UI connector listing, and in the connector list when configuring an action.
URL::       ServiceNow instance URL.
Username::  Username for HTTP Basic authentication.
Password::  Password for HTTP Basic authentication.

[float]
[[Preconfigured-servicenow-configuration]]
==== Preconfigured action type

[source,text]
--
 my-servicenow:
   name: preconfigured-servicenow-action-type
   actionTypeId: .servicenow
   config:
     apiUrl: https://dev94428.service-now.com/
   secrets:
     username: testuser
     password: passwordkeystorevalue
--

Config defines information for the action type.

`apiUrl`:: An address that corresponds to *URL*.

Secrets defines sensitive information for the action type.

`username`:: A string that corresponds to *Username*.
`password`::  A string that corresponds to *Password*. Should be stored in the <<creating-keystore, {kib} keystore>>.

[float]
[[servicenow-action-configuration]]
==== Action configuration

ServiceNow actions have the following configuration properties.

Urgency::              The extent to which the incident resolution can delay.
Severity::             The severity of the incident.
Impact::               The effect an incident has on business. Can be measured by the number of affected users or by how critical it is to the business in question.
Short description::    A short description for the incident, used for searching the contents of the knowledge base.
Description::          The details about the incident.
Additional comments::  Additional information for the client, such as how to troubleshoot the issue.

[[configuring-servicenow]]
==== Configure ServiceNow

ServiceNow offers free https://developer.servicenow.com/dev.do#!/guides/madrid/now-platform/pdi-guide/obtaining-a-pdi[Personal Developer Instances], which you can use to test incidents.
