[role="xpack"]
[[servicenow-action-type]]
=== ServiceNow action

The ServiceNow action type uses the https://developer.servicenow.com/app.do#!/rest_api_doc?v=orlando&id=c_TableAPI[V2 Table API] to create ServiceNow incidents.

[float]
[[servicenow-connector-configuration]]
==== Connector configuration

ServiceNow connectors have the following configuration properties:

Name::      The name of the connector. The name is used to identify a  connector in the **Stack Management** UI connector listing, and in the connector list when configuring an action.
URL::       ServiceNow instance URL.
Username::  Username for HTTP Basic authentication.
Password::  Password for HTTP Basic authentication.

[float]
[[Preconfigured-servicenow-configuration]]
==== Preconfigured action type

[source,text]
--
 my-servicenow:
   name: preconfigured-servicenow-action-type
   actionTypeId: .servicenow
   config:
     apiUrl: https://dev94428.service-now.com/
   secrets:
     username: testuser
     password: passwordkeystorevalue
--

[[servicenow-connector-config-properties]]
**`config`** defines the action type specific to the configuration and contains the following properties:

[cols="2*<"]
|===

| `apiUrl`
| An address that corresponds to *URL*.

|===

[[servicenow-connector-secrets-properties]]
**`secrets`** defines sensitive information for the action type and contains the following properties:

[cols="2*<"]
|===

| `username`
| A string that corresponds to *Username*.

| `password`
| A string that corresponds to *Password*. Should be stored in the <<creating-keystore, {kib} keystore>>.

|===

[[servicenow-action-configuration]]
==== Action configuration

ServiceNow actions have the following configuration properties:

Subaction::        The sub action to perform. It can be `pushToService`, `getFields`, `getIncident`, and `getChoices`.
Subaction Params:: The parameters of the subaction.

===== pushToService subaction configuration

Incident:: The ServiceNow incident.

[cols="3*<"]
|===

| `short_description`
| A short description for the incident, used for searching the contents of the knowledge base.
| string

| `description`
| The details about the incident.
| string _(optional)_

| `externalId`
| The id of the incident in ServiceNow. If presented the incident will be update. Otherwise a new incident will be created.
| string _(optional)_

| `severity`
| The severity of the incident.
| string _(optional)_

| `urgency`
| The extent to which the incident resolution can delay.
| string _(optional)_

| `impact`
| The effect an incident has on business. Can be measured by the number of affected users or by how critical it is to the business in question.
| string _(optional)_

| `category`
| The name of the category in ServiceNow.
| string _(optional)_

| `subcategory`
| The name of the subcategory in ServiceNow.
| string _(optional)_

|===

Comments:: The comments of the case. A comment is of the form `{ commentId: string, version: string, comment: string }`.

===== getFields subaction configuration

No parameters for `getFields` sub-action. Provide an empty object `{}`.

===== getIncident subaction configuration

External ID:: The id of the incident in ServiceNow.

===== getChoices subaction configuration

Fields:: An array of fields. Example: `[priority, category, impact]`.

[[configuring-servicenow]]
==== Configuring and testing ServiceNow

ServiceNow offers free https://developer.servicenow.com/dev.do#!/guides/madrid/now-platform/pdi-guide/obtaining-a-pdi[Personal Developer Instances], which you can use to test incidents.
