[role="xpack"]
[[webhook-action-type]]
=== Webhook action

The Webhook action type uses https://github.com/axios/axios[axios] to send a POST or PUT request to a web service.

[float]
[[webhook-connector-configuration]]
==== Connector configuration

Webhook connectors have the following configuration properties:

Name::      The name of the connector. The name is used to identify a  connector in the management UI connector listing, or in the connector list when configuring an action.
URL::       The request URL. If you are using the <<action-settings, `xpack.actions.whitelistedHosts`>> setting, make sure the hostname is whitelisted.
Method::    HTTP request method, either `post`(default) or `put`.
Headers::   A set of key-value pairs sent as headers with the request
User::      An optional username. If set, HTTP basic authentication is used. Currently only basic authentication is supported.
Password::  An optional password. If set, HTTP basic authentication is used. Currently only basic authentication is supported.

[float]
[[Preconfigured-webhook-configuration]]
==== Preconfigured action type 

[source,text]
--
 my-webhook:
   name: preconfigured-webhook-action-type
   actionTypeId: .webhook
   config:
     url: https://test.host <1.1>
     method: POST <1.2>
     headers: <1.3>
       testheader: testvalue
   secrets:
     user: testuser <2.1>
     password: passwordkeystorevalue <2.2>
--

`config` defines the action type specific to the configuration and contains the following properties:

<1.1> `url:` is URL string and correspond to *URL*.
<1.2> `method:` is a string and correspond to *Method*.
<1.3> `headers:` is Record<String, String> and correspond to *Headers*.

`secrets` defines action type sensitive configuration:

<2.1> `user:` is a string and correspond to *User*.
<2.2> `password:` is a string and correspond to *Password*. Should be stored in the <<creating-keystore, {kib} keystore>>.

[float]
[[webhook-action-configuration]]
==== Action configuration

Webhook actions have the following properties:

Body::      A json payload sent to the request URL.
