[role="xpack"]
[[apm-settings-kb]]
=== APM settings in Kibana
++++
<titleabbrev>APM settings</titleabbrev>
++++

You do not need to configure any settings to use APM. It is enabled by default.
If you'd like to change any of the default values,
copy and paste the relevant settings below into your `kibana.yml` configuration file.

[float]
[[general-apm-settings-kb]]
==== General APM settings

// This content is reused in the APM app documentation.
// Any changes made in this file will be seen there as well.
// tag::general-apm-settings[]

If you'd like to change any of the default values,
copy and paste the relevant settings into your `kibana.yml` configuration file.
Changing these settings may disable features of the APM App.

`xpack.apm.enabled`::
Set to `false` to disable the APM app. Defaults to `true`.

`xpack.apm.ui.enabled`{ess-icon}::
Set to `false` to hide the APM app from the menu. Defaults to `true`.

`xpack.apm.ui.transactionGroupBucketSize` {ess-icon}::
Number of top transaction groups displayed in the APM app. Defaults to `1000`.

`xpack.apm.ui.maxTraceItems` {ess-icon}::
Maximum number of child items displayed when viewing trace details. Defaults to `1000`.

`apm_oss.indexPattern` {ess-icon}::
The index pattern used for integrations with Machine Learning and Query Bar.
It must match all apm indices. Defaults to `apm-*`.

`apm_oss.errorIndices` {ess-icon}::
Matcher for all {apm-server-ref}/error-indices.html[error indices]. Defaults to `apm-*`.

`apm_oss.onboardingIndices`::
Matcher for all onboarding indices. Defaults to `apm-*`.

`apm_oss.spanIndices` {ess-icon}::
Matcher for all {apm-server-ref}/span-indices.html[span indices]. Defaults to `apm-*`.

`apm_oss.transactionIndices` {ess-icon}::
Matcher for all {apm-server-ref}/transaction-indices.html[transaction indices]. Defaults to `apm-*`.

`apm_oss.metricsIndices`::
Matcher for all {apm-server-ref}/metricset-indices.html[metrics indices]. Defaults to `apm-*`.

`apm_oss.sourcemapIndices`::
Matcher for all {apm-server-ref}/sourcemap-indices.html[source map indices]. Defaults to `apm-*`.

// end::general-apm-settings[]
