[role="xpack"]
[[apm-settings-kb]]
=== APM Settings in Kibana
++++
<titleabbrev>APM Settings</titleabbrev>
++++

You do not need to configure any settings to use APM. It is enabled by default.
If you'd like to change any of the default values,
copy and paste the relevant settings below into your `kibana.yml` configuration file.

[float]
[[general-apm-settings-kb]]
==== General APM Settings

xpack.apm.enabled:: Set to `false` to disabled the APM plugin {kib}. Defaults to
`true`.

xpack.apm.ui.enabled:: Set to `false` to hide the APM plugin {kib} from the menu. Defaults to
`true`.

xpack.apm.ui.transactionGroupBucketSize:: Number of top transaction groups displayed in APM plugin in Kibana. Defaults to `100`.

apm_oss.indexPattern:: Index pattern is used for integrations with Machine Learning and Kuery Bar. It must match all apm indices. Defaults to `apm-*`.

apm_oss.errorIndices:: Matcher for indices containing error documents. Defaults to `apm-*`.

apm_oss.onboardingIndices:: Matcher for indices containing onboarding documents. Defaults to `apm-*`.

apm_oss.spanIndices:: Matcher for indices containing span documents. Defaults to `apm-*`.

apm_oss.transactionIndices:: Matcher for indices containing transaction documents. Defaults to `apm-*`.
