[role="xpack"]
[[infrastructure-ui-settings-kb]]
=== Infrastructure UI Settings in Kibana
++++
<titleabbrev>Infrastructure UI Settings</titleabbrev>
++++

You do not need to configure any settings to use Infrastructure UI. It is enabled by default.

[float]
[[general-infra-ui-settings-kb]]
==== General Infrastructure UI Settings

xpack.infra.enabled:: Set to `false` to disabled the Logs and Infrastructure UI plugin {kib}. Defaults to
`true`.

xpack.infra.sources.default.logAlias:: Index pattern for matching indices that contain log data. Defaults to
`filebeat-*`.

xpack.infra.sources.default.metricAlias:: Index pattern for matching indices that contain Metricbeat data. Defaults to
`metricbeat-*`.

xpack.infra.sources.default.fields.timestamp:: Timestamp used to for sorting log entries. Defaults to
`@timestamp`.

xpack.infra.sources.default.fields.message:: Fields used for the message for Logs UI. Defaults to
`['message', '@message']`.

xpack.infra.sources.default.fields.tiebreaker:: Field used to break ties between two entries
with the same timestamp. Defaults to `_doc`

xpack.infra.sources.default.fields.host:: Field used to identify hosts.
Defaults to `beat.hostname`

xpack.infra.sources.default.fields.container:: Field used to identify Docker containers.
Defaults to `docker.container.name`

xpack.infra.sources.default.fields.pod:: Field used to identify Kubernetes pods.
Defaults to `kubernetes.pod.name`