[[logging-settings]]
=== Logging settings in {kib}
++++
<titleabbrev>Logging settings</titleabbrev>
++++

// QUESTION: IS THIS SECTION NEEDED? IF SO, ONLY LIST ONE_LINE VERSIONS OF SETTINGS, OTHERWISE, REMOVE THIS
{kib} relies on three high-level entities to set the logging service: appenders, loggers, and root.

- Appenders define where log messages are displayed (stdout or console) and their layout (`pattern` or `json`). They also allow you to specify if you want the logs stored and, if so, where (file on the disk).
- Loggers define what logging settings, such as the level of verbosity and the appenders, to apply to a particular context. Each log entry context provides information about the service or plugin that emits it and any of its sub-parts, for example, `metrics.ops` or `elasticsearch.query`.
- Root is a logger that applies to all the log entries in {kib}.

Refer to the <<log-settings-examples, examples>> for common configuration use cases. To learn more about possible configuration values, go to <<logging-configuration, Configure Logging in {kib}>>.

