[[telemetry-settings-kbn]]
=== Telemetry settings in {kib}
++++
<titleabbrev>Telemetry settings</titleabbrev>
++++

Usage Collection (also known as Telemetry) is enabled by default. This allows us to learn what our users are most interested in, so we can improve our products and services.

Refer to our https://www.elastic.co/legal/product-privacy-statement[Privacy Statement] to learn more.

You can control whether this data is sent from the {kib} servers, or if it should be sent
from the user's browser, in case a firewall is blocking the connections from the server. Additionally, you can decide to completely disable this feature either in the config file or in {kib} via *Management > Kibana > Advanced Settings > Usage Data*.

[float]
[[telemetry-general-settings]]
==== General telemetry settings


[[telemetry-enabled]] `telemetry.enabled`::
  Set to `true` to send cluster statistics to Elastic. Reporting your
  cluster statistics helps us improve your user experience. Set to `false` to disable statistics reporting from any
  browser connected to the {kib} instance. Defaults to `true`.

`telemetry.sendUsageFrom`::
  Set to `'server'` to report the cluster statistics from the {kib} server.
  If the server fails to connect to our endpoint at https://telemetry.elastic.co/, it assumes
  it is behind a firewall and falls back to `'browser'` to send it from users' browsers
  when they are navigating through {kib}. Defaults to `'server'`.

[[telemetry-optIn]] `telemetry.optIn`::
  Set to `false` to stop sending any telemetry data to Elastic. Reporting your
cluster statistics helps us improve your user experience. *Default: `true`.* +
+
This setting can be changed at any time in <<advanced-options, Advanced Settings>>.
To prevent users from disabling it,
set <<telemetry-allowChangingOptInStatus, `telemetry.allowChangingOptInStatus`>> to `false` and <<settings-telemetry-optIn, `telemetry.optIn`>> to `true`.

`telemetry.allowChangingOptInStatus`::
  Set to `false` to disallow overwriting the <<telemetry-optIn, `telemetry.optIn`>> setting via the <<advanced-options, Advanced Settings>> in {kib}. *Default: `true`.* +
+
[NOTE]
============
When `false`, <<telemetry-optIn, `telemetry.optIn`>> must be `true`. To disable telemetry and not allow users to change that parameter, use <<telemetry-enabled, `telemetry.enabled`>>.
============
