[[telemetry-settings-kbn]]
=== Telemetry settings in Kibana
++++
<titleabbrev>Telemetry settings</titleabbrev>
++++

By default, the Usage Collection (also known as Telemetry) is enabled. This
help us to learn about the {kib} features our users are more interested in, so we
can focus our efforts on making them even better.

You can control whether this data is sent from the {kib} servers or, if it should be sent 
from the user's browser, in case there is a firewall blocking those connections from the server. Additionally, you can decide to completely disable this feature either in the config file or the {kib} UI (via Management > Kibana > Advanced Settings > Usage Data).

See our https://www.elastic.co/legal/privacy-statement[Privacy Statement] to learn more.

[float]
[[telemetry-general-settings]]
==== General telemetry settings

`telemetry.enabled`:: *Default: true*.
Set to `true` to send cluster statistics to Elastic. Reporting your
cluster statistics helps us improve your user experience. Your data is never
shared with anyone. Set to `false` to disable statistics reporting from any
browser connected to the {kib} instance.

`telemetry.sendUsageFrom`:: *Default: 'browser'*.
Set to `'server'` to report the cluster statistics from the {kib} server.
If the server fails to connect to our endpoint at https://telemetry.elastic.co/, it assumes
it is behind a firewall and falls back to `'browser'` to send it from the users' browsers
when they are navigating through {kib}.

`telemetry.optIn`:: *Default: true*.
Set to `true` to auto opt-in the cluster into reporting statistics. You can also opt out through the
*Advanced Settings* in {kib}.

`telemetry.allowChangingOptInStatus`:: *Default: true*.
Set to `true` to allow overwriting the `telemetry.optIn` flag via the {kib} UI. 
N.B.: When `false`, `telemetry.optIn` must be `true`. If you want to disable the telemetry and do not give any of the users the chance to change that parameter, use `telemetry.enabled`.
