import type { EventAnnotationConfig, RangeEventAnnotationConfig, PointInTimeEventAnnotationConfig, QueryPointEventAnnotationConfig } from './types';
export declare const defaultAnnotationColor: string;
export declare const defaultAnnotationRangeColor = "#F04E981A";
export declare const isRangeAnnotationConfig: (annotation?: EventAnnotationConfig) => annotation is RangeEventAnnotationConfig;
export declare const isManualPointAnnotationConfig: (annotation?: EventAnnotationConfig) => annotation is PointInTimeEventAnnotationConfig;
export declare const isQueryAnnotationConfig: (annotation?: EventAnnotationConfig) => annotation is QueryPointEventAnnotationConfig;
export declare const createCopiedAnnotation: (newId: string, timestamp: string, source?: EventAnnotationConfig) => EventAnnotationConfig;
export declare const defaultAnnotationLabel: string;
export declare const defaultRangeAnnotationLabel: string;
export declare const getDefaultManualAnnotation: (id: string, timestamp: string) => EventAnnotationConfig;
export declare const getDefaultQueryAnnotation: (id: string, fieldName: string, timeField: string) => EventAnnotationConfig;
