/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

import type { Template } from '../../../../common/types/domain/template/v1';

// Mock data - remove when API is available
export const MOCK_TEMPLATES: Template[] = [
  {
    templateId: 'template-1',
    name: 'Security Incident Template',
    owner: 'securitySolution',
    definition: 'fields:\n  - name: severity\n    type: keyword',
    templateVersion: 1,
    deletedAt: null,
    description: 'Template for security incident cases with predefined fields',
    tags: ['security', 'incident', 'critical'],
    author: 'john.doe',
    fieldCount: 8,
    fieldNames: [
      { name: 'severity', label: 'Severity', type: 'keyword', control: 'SELECT_BASIC' },
      { name: 'priority', label: 'Priority', type: 'keyword', control: 'SELECT_BASIC' },
      {
        name: 'affected_systems',
        label: 'Affected Systems',
        type: 'keyword',
        control: 'CHECKBOX_GROUP',
      },
      { name: 'incident_type', label: 'Incident Type', type: 'keyword', control: 'SELECT_BASIC' },
      { name: 'source_ip', label: 'Source IP', type: 'keyword', control: 'INPUT_TEXT' },
      { name: 'destination_ip', label: 'Destination IP', type: 'keyword', control: 'INPUT_TEXT' },
      { name: 'timestamp', label: 'Timestamp', type: 'date', control: 'DATE_PICKER' },
      { name: 'status', label: 'Status', type: 'keyword', control: 'SELECT_BASIC' },
    ],
    usageCount: 45,
    lastUsedAt: '2024-01-20T14:45:00.000Z',
    isDefault: true,
  },
  {
    templateId: 'template-2',
    name: 'Observability Alert Template',
    owner: 'observability',
    definition: 'fields:\n  - name: service\n    type: keyword',
    templateVersion: 1,
    deletedAt: null,
    description: 'Template for observability alerts and monitoring issues',
    tags: ['observability', 'monitoring', 'alerts'],
    author: 'jane.smith',
    fieldCount: 5,
    fieldNames: [
      { name: 'service', label: 'Service', type: 'keyword', control: 'INPUT_TEXT' },
      { name: 'environment', label: 'Environment', type: 'keyword', control: 'SELECT_BASIC' },
      { name: 'alert_type', label: 'Alert Type', type: 'keyword', control: 'SELECT_BASIC' },
      { name: 'threshold', label: 'Threshold', type: 'keyword', control: 'INPUT_TEXT' },
      { name: 'metric_name', label: 'Metric Name', type: 'keyword', control: 'INPUT_TEXT' },
    ],
    usageCount: 32,
    lastUsedAt: '2024-01-18T09:30:00.000Z',
    isDefault: false,
  },
  {
    templateId: 'template-3',
    name: 'General Support Template',
    owner: 'cases',
    definition: 'fields:\n  - name: category\n    type: keyword',
    templateVersion: 1,
    deletedAt: null,
    description: 'General purpose template for support cases',
    tags: ['support', 'general'],
    author: 'bob.wilson',
    fieldCount: 4,
    fieldNames: [
      { name: 'category', label: 'Category', type: 'keyword', control: 'SELECT_BASIC' },
      { name: 'priority', label: 'Priority', type: 'keyword', control: 'SELECT_BASIC' },
      { name: 'customer_id', label: 'Customer ID', type: 'keyword', control: 'INPUT_TEXT' },
      { name: 'product', label: 'Product', type: 'keyword', control: 'INPUT_TEXT' },
    ],
    usageCount: 78,
    lastUsedAt: '2024-01-19T11:15:00.000Z',
    isDefault: false,
  },
  {
    templateId: 'template-4',
    name: 'Malware Investigation',
    owner: 'securitySolution',
    definition: 'fields:\n  - name: malware_type\n    type: keyword',
    templateVersion: 1,
    deletedAt: null,
    description: 'Template for malware investigation and threat analysis',
    tags: ['security', 'malware', 'threat'],
    author: 'john.doe',
    fieldCount: 12,
    fieldNames: [
      { name: 'malware_type', label: 'Malware Type', type: 'keyword', control: 'SELECT_BASIC' },
      { name: 'file_hash', label: 'File Hash', type: 'keyword', control: 'INPUT_TEXT' },
      { name: 'file_name', label: 'File Name', type: 'keyword', control: 'INPUT_TEXT' },
      { name: 'file_path', label: 'File Path', type: 'keyword', control: 'INPUT_TEXT' },
      { name: 'registry_key', label: 'Registry Key', type: 'keyword', control: 'INPUT_TEXT' },
      { name: 'process_name', label: 'Process Name', type: 'keyword', control: 'INPUT_TEXT' },
      {
        name: 'network_indicator',
        label: 'Network Indicator',
        type: 'keyword',
        control: 'INPUT_TEXT',
      },
      { name: 'c2_server', label: 'C2 Server', type: 'keyword', control: 'INPUT_TEXT' },
      {
        name: 'affected_hosts',
        label: 'Affected Hosts',
        type: 'keyword',
        control: 'CHECKBOX_GROUP',
      },
      { name: 'ioc_type', label: 'IOC Type', type: 'keyword', control: 'SELECT_BASIC' },
      { name: 'severity', label: 'Severity', type: 'keyword', control: 'SELECT_BASIC' },
      {
        name: 'containment_status',
        label: 'Containment Status',
        type: 'keyword',
        control: 'SELECT_BASIC',
      },
    ],
    usageCount: 23,
    lastUsedAt: '2024-01-17T10:00:00.000Z',
    isDefault: false,
  },
  {
    templateId: 'template-5',
    name: 'Performance Issue Template',
    owner: 'observability',
    definition: 'fields:\n  - name: latency\n    type: keyword',
    templateVersion: 1,
    deletedAt: null,
    description: 'Template for tracking performance degradation issues',
    tags: ['performance', 'latency', 'metrics'],
    author: 'alice.johnson',
    fieldCount: 6,
    usageCount: 56,
    lastUsedAt: '2024-01-21T08:30:00.000Z',
    isDefault: false,
  },
  {
    templateId: 'template-6',
    name: 'Phishing Attack Response',
    owner: 'securitySolution',
    definition: 'fields:\n  - name: attack_vector\n    type: keyword',
    templateVersion: 1,
    deletedAt: null,
    description: 'Template for handling phishing attack incidents',
    tags: ['security', 'phishing', 'email'],
    author: 'john.doe',
    fieldCount: 10,
    usageCount: 67,
    lastUsedAt: '2024-01-22T16:00:00.000Z',
    isDefault: false,
  },
  {
    templateId: 'template-7',
    name: 'Infrastructure Outage',
    owner: 'observability',
    definition: 'fields:\n  - name: affected_service\n    type: keyword',
    templateVersion: 1,
    deletedAt: null,
    description: 'Template for infrastructure outage and downtime incidents',
    tags: ['infrastructure', 'outage', 'downtime'],
    author: 'jane.smith',
    fieldCount: 7,
    usageCount: 89,
    lastUsedAt: '2024-01-23T07:45:00.000Z',
    isDefault: false,
  },
  {
    templateId: 'template-8',
    name: 'Data Breach Investigation',
    owner: 'securitySolution',
    definition: 'fields:\n  - name: data_type\n    type: keyword',
    templateVersion: 1,
    deletedAt: null,
    description: 'Template for data breach and unauthorized access investigations',
    tags: ['security', 'data-breach', 'compliance'],
    author: 'charlie.brown',
    fieldCount: 15,
    usageCount: 12,
    lastUsedAt: '2024-01-16T13:30:00.000Z',
    isDefault: false,
  },
  {
    templateId: 'template-9',
    name: 'Application Error Tracking',
    owner: 'observability',
    definition: 'fields:\n  - name: error_code\n    type: keyword',
    templateVersion: 1,
    deletedAt: null,
    description: 'Template for tracking application errors and exceptions',
    tags: ['application', 'errors', 'debugging'],
    author: 'alice.johnson',
    fieldCount: 8,
    usageCount: 134,
    lastUsedAt: '2024-01-24T09:15:00.000Z',
    isDefault: false,
  },
  {
    templateId: 'template-10',
    name: 'Compliance Audit Template',
    owner: 'cases',
    definition: 'fields:\n  - name: regulation\n    type: keyword',
    templateVersion: 1,
    deletedAt: null,
    description: 'Template for compliance audits and regulatory reviews',
    tags: ['compliance', 'audit', 'regulatory'],
    author: 'bob.wilson',
    fieldCount: 9,
    usageCount: 28,
    lastUsedAt: '2024-01-15T11:00:00.000Z',
    isDefault: false,
  },
  {
    templateId: 'template-11',
    name: 'Network Intrusion Detection',
    owner: 'securitySolution',
    definition: 'fields:\n  - name: source_ip\n    type: keyword',
    templateVersion: 1,
    deletedAt: null,
    description: 'Template for network intrusion and suspicious activity',
    tags: ['security', 'network', 'intrusion'],
    author: 'john.doe',
    fieldCount: 11,
    usageCount: 41,
    lastUsedAt: '2024-01-25T10:20:00.000Z',
    isDefault: false,
  },
  {
    templateId: 'template-12',
    name: 'Log Analysis Template',
    owner: 'observability',
    definition: 'fields:\n  - name: log_level\n    type: keyword',
    templateVersion: 1,
    deletedAt: null,
    description: 'Template for log analysis and anomaly detection',
    tags: ['logs', 'analysis', 'anomaly'],
    author: 'jane.smith',
    fieldCount: 6,
    usageCount: 95,
    lastUsedAt: '2024-01-26T14:30:00.000Z',
    isDefault: false,
  },
  {
    templateId: 'template-13',
    name: 'Vulnerability Assessment',
    owner: 'securitySolution',
    definition: 'fields:\n  - name: cve_id\n    type: keyword',
    templateVersion: 1,
    deletedAt: null,
    description: 'Template for vulnerability scanning and remediation',
    tags: ['security', 'vulnerability', 'remediation'],
    author: 'charlie.brown',
    fieldCount: 13,
    usageCount: 36,
    lastUsedAt: '2024-01-27T08:00:00.000Z',
    isDefault: false,
  },
  {
    templateId: 'template-14',
    name: 'Service Degradation',
    owner: 'observability',
    definition: 'fields:\n  - name: impact\n    type: keyword',
    templateVersion: 1,
    deletedAt: null,
    description: 'Template for service degradation and partial outages',
    tags: ['service', 'degradation', 'sla'],
    author: 'alice.johnson',
    fieldCount: 5,
    usageCount: 72,
    lastUsedAt: '2024-01-28T11:30:00.000Z',
    isDefault: false,
  },
  {
    templateId: 'template-15',
    name: 'Customer Escalation',
    owner: 'cases',
    definition: 'fields:\n  - name: priority\n    type: keyword',
    templateVersion: 1,
    deletedAt: null,
    description: 'Template for customer escalation and priority support',
    tags: ['customer', 'escalation', 'priority'],
    author: 'bob.wilson',
    fieldCount: 7,
    usageCount: 53,
    lastUsedAt: '2024-01-29T15:45:00.000Z',
    isDefault: false,
  },
];
