/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

import { deepFreeze } from '@kbn/std';
import type { DocLinks, BuildFlavor } from './types';
import { getDocLinksMeta } from './get_doc_meta';

export interface GetDocLinkOptions {
  kibanaBranch: string;
  buildFlavor: BuildFlavor;
}

export const getDocLinks = ({ kibanaBranch, buildFlavor }: GetDocLinkOptions): DocLinks => {
  const meta = getDocLinksMeta({ kibanaBranch, buildFlavor });

  // const DOC_LINK_VERSION = meta.version;
  // const ECS_VERSION = meta.ecs_version;
  // const ELASTIC_WEBSITE_URL = meta.elasticWebsiteUrl;
  const ELASTIC_GITHUB = meta.elasticGithubUrl;
  const SEARCH_LABS_URL = meta.searchLabsUrl;
  const ELASTIC_DOCS = meta.docsWebsiteUrl;

  // const ELASTICSEARCH_DOCS = `https://www.elastic.co/guide/en/elasticsearch/reference/current/`;
  // const KIBANA_DOCS = `https://www.elastic.co/guide/en/kibana/current/`;
  // const KIBANA_REF = `${ELASTIC_DOCS}reference/kibana/`;
  // const FLEET_DOCS = `https://www.elastic.co/guide/en/fleet/current/`;
  // const INTEGRATIONS_DEV_DOCS = `https://www.elastic.co/guide/en/integrations-developer/current/`;
  // const PLUGIN_DOCS = `https://www.elastic.co/guide/en/elasticsearch/plugins/current/`;
  // const OBSERVABILITY_DOCS = `https://www.elastic.co/guide/en/observability/current/`;
  // const APM_DOCS = `https://www.elastic.co/guide/en/apm/`;
  // const SECURITY_SOLUTION_DOCS = `https://www.elastic.co/guide/en/security/current/`;
  // const ENTERPRISE_SEARCH_DOCS = `https://www.elastic.co/guide/en/enterprise-search/current/`;
  // const ESRE_DOCS = `https://www.elastic.co/guide/en/esre/current/`;
  // const SEARCH_UI_DOCS = `https://www.elastic.co/guide/en/search-ui/current/`;
  // const MACHINE_LEARNING_DOCS = `https://www.elastic.co/guide/en/machine-learning/current/`;
  // const SERVERLESS_DOCS = `https://www.elastic.co/guide/en/serverless/current/`;
  const SEARCH_LABS_REPO = `${ELASTIC_GITHUB}elasticsearch-labs/`;
  const isServerless = buildFlavor === 'serverless';

  return deepFreeze({
    elasticStackGetStarted: isServerless
      ? `${ELASTIC_DOCS}deploy-manage/deploy/elastic-cloud/serverless`
      : `${ELASTIC_DOCS}get-started`,
    apiReference: `${ELASTIC_DOCS}reference`,
    upgrade: {
      upgradingStackOnPrem: `${ELASTIC_DOCS}deploy-manage/upgrade/deployment-or-cluster`,
      upgradingStackOnCloud: `${ELASTIC_DOCS}deploy-manage/upgrade/deployment-or-cluster`,
    },
    apm: {
      kibanaSettings: `${ELASTIC_DOCS}solutions/observability/apps/applications-ui-settings`,
      supportedServiceMaps: isServerless
        ? `${ELASTIC_DOCS}solutions/observability/apps/service-map#observability-apm-service-map-supported-apm-agents`
        : `${ELASTIC_DOCS}solutions/observability/apps/service-map#service-maps-supported`,
      customLinks: isServerless
        ? `${ELASTIC_DOCS}solutions/observability/apps/create-custom-links`
        : `${ELASTIC_DOCS}solutions/observability/apps/create-custom-links`,
      droppedTransactionSpans: `https://www.elastic.co/guide/en/apm/guide/current/data-model-spans.html#data-model-dropped-spans`,
      upgrading: `https://www.elastic.co/guide/en/apm/guide/current/upgrade.html`,
      metaData: `https://www.elastic.co/guide/en/apm/guide/current/data-model-metadata.html`,
      overview: `https://www.elastic.co/guide/en/apm/guide/current/apm-overview.html`,
      tailSamplingPolicies: isServerless
        ? `${ELASTIC_DOCS}solutions/observability/apps/transaction-sampling`
        : `https://www.elastic.co/guide/en/observability/current/apm-sampling.html#apm-tail-based-sampling`,
      elasticAgent: `https://www.elastic.co/guide/en/apm/guide/current/upgrade-to-apm-integration.html`,
      storageExplorer: `${ELASTIC_DOCS}solutions/observability/apps/storage-explorer`,
      spanCompression: isServerless
        ? `${ELASTIC_DOCS}solutions/observability/apps/spans`
        : `https://www.elastic.co/guide/en/observability/current/apm-data-model-spans.html#apm-spans-span-compression`,
      transactionSampling: isServerless
        ? `${ELASTIC_DOCS}solutions/observability/apps/transaction-sampling`
        : `${ELASTIC_DOCS}solutions/observability/apps/transaction-sampling`,
      indexLifecycleManagement: `https://www.elastic.co/guide/en/apm/guide/current/ilm-how-to.html`,
    },
    canvas: {
      guide: `${ELASTIC_DOCS}explore-analyze/visualize/canvas`,
    },
    cloud: {
      beatsAndLogstashConfiguration: `${ELASTIC_DOCS}deploy-manage/deploy/elastic-cloud/find-cloud-id`,
      indexManagement: `${ELASTIC_DOCS}manage-data/lifecycle/index-lifecycle-management/migrate-index-management`,
    },
    console: {
      guide: `${ELASTIC_DOCS}explore-analyze/query-filter/tools/console`,
      serverlessGuide: `https://www.elastic.co/guide/en/serverless/current/devtools-run-api-requests-in-the-console.html`,
    },
    dashboard: {
      guide: `${ELASTIC_DOCS}explore-analyze/dashboards`,
      drilldowns: `${ELASTIC_DOCS}explore-analyze/dashboards/drilldowns`,
      drilldownsTriggerPicker: `${ELASTIC_DOCS}explore-analyze/dashboards/drilldowns#create-url-drilldowns`,
      urlDrilldownTemplateSyntax: `${ELASTIC_DOCS}explore-analyze/dashboards/drilldowns#url-templating-language`,
      urlDrilldownVariables: `${ELASTIC_DOCS}explore-analyze/dashboards/drilldowns#url-template-variable`,
    },
    discover: {
      guide: `${ELASTIC_DOCS}explore-analyze/discover`,
      fieldStatistics: `${ELASTIC_DOCS}explore-analyze/discover/show-field-statistics`,
      fieldTypeHelp: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/field-data-types`,
      dateFieldTypeDocs: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/date`,
      dateFormatsDocs: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/mapping-date-format`,
      documentExplorer: `${ELASTIC_DOCS}explore-analyze/discover/document-explorer`,
    },
    filebeat: {
      base: `https://www.elastic.co/guide/en/beats/filebeat/current`,
      installation: `${ELASTIC_DOCS}reference/beats/filebeat/filebeat-installation-configuration`,
      configuration: `${ELASTIC_DOCS}reference/beats/filebeat/configuring-howto-filebeat`,
      elasticsearchModule: `${ELASTIC_DOCS}reference/beats/filebeat/filebeat-module-elasticsearch`,
      elasticsearchOutput: `${ELASTIC_DOCS}reference/beats/filebeat/elasticsearch-output`,
      kafkaOutput: `${ELASTIC_DOCS}reference/beats/filebeat/kafka-output`,
      startup: `${ELASTIC_DOCS}reference/beats/filebeat/filebeat-starting`,
      exportedFields: `${ELASTIC_DOCS}reference/beats/filebeat/exported-fields`,
      suricataModule: `${ELASTIC_DOCS}reference/beats/filebeat/filebeat-module-suricata`,
      zeekModule: `${ELASTIC_DOCS}reference/beats/filebeat/filebeat-module-zeek`,
    },
    auditbeat: {
      base: `https://www.elastic.co/guide/en/beats/auditbeat/current`,
      auditdModule: `${ELASTIC_DOCS}reference/beats/auditbeat/auditbeat-module-auditd`,
      systemModule: `${ELASTIC_DOCS}reference/beats/auditbeat/auditbeat-module-system`,
    },
    enterpriseSearch: {
      aiSearchDoc: `https://www.elastic.co/guide/en/esre/current/`,
      aiSearchHelp: `https://www.elastic.co/guide/en/esre/current/help.html`,
      apiKeys: `${ELASTIC_DOCS}deploy-manage/api-keys/elasticsearch-api-keys`,
      behavioralAnalytics: `https://www.elastic.co/guide/en/elasticsearch/reference/current/behavioral-analytics-overview.html`,
      behavioralAnalyticsCORS: `https://www.elastic.co/guide/en/elasticsearch/reference/current/behavioral-analytics-cors.html`,
      behavioralAnalyticsEvents: `https://www.elastic.co/guide/en/elasticsearch/reference/current/behavioral-analytics-event.html`,
      buildConnector: `${ELASTIC_DOCS}reference/search-connectors/self-managed-connectors`,
      bulkApi: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-bulk`,
      configuration: `https://www.elastic.co/guide/en/enterprise-search/current/configuration.html`,
      connectors: `${ELASTIC_DOCS}reference/search-connectors`,
      connectorsClientDeploy: `${ELASTIC_DOCS}reference/search-connectors/self-managed-connectors#es-connectors-deploy-connector-service`,
      connectorsMappings: `${ELASTIC_DOCS}reference/search-connectors/connectors-ui-in-kibana#es-connectors-usage-index-create-configure-existing-index`,
      connectorsAzureBlobStorage: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-azure-blob`,
      connectorsBox: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-box`,
      connectorsClients: `${ELASTIC_DOCS}reference/search-connectors#es-connectors-build`,
      connectorsConfluence: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-confluence`,
      connectorsDropbox: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-dropbox`,
      connectorsContentExtraction: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-content-extraction`,
      connectorsGithub: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-github`,
      connectorsGmail: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-gmail`,
      connectorsGoogleCloudStorage: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-google-cloud`,
      connectorsGoogleDrive: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-google-drive`,
      connectorsJira: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-jira`,
      connectorsMicrosoftSQL: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-ms-sql`,
      connectorsMongoDB: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-mongodb`,
      connectorsMySQL: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-mysql`,
      connectorsNative: `${ELASTIC_DOCS}reference/search-connectors#es-connectors-native`,
      connectorsNetworkDrive: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-network-drive`,
      connectorsNotion: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-notion`,
      connectorsOneDrive: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-onedrive`,
      connectorsOracle: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-oracle`,
      connectorsOutlook: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-outlook`,
      connectorsPostgreSQL: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-postgresql`,
      connectorsRedis: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-redis`,
      connectorsS3: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-s3`,
      connectorsSalesforce: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-salesforce`,
      connectorsServiceNow: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-servicenow`,
      connectorsSharepoint: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-sharepoint`,
      connectorsSharepointOnline: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-sharepoint-online`,
      connectorsSlack: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-slack`,
      connectorsTeams: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-teams`,
      connectorsZoom: `${ELASTIC_DOCS}reference/search-connectors/es-connectors-zoom`,
      crawlerExtractionRules: `https://www.elastic.co/guide/en/enterprise-search/current/crawler-extraction-rules.html`,
      crawlerManaging: `https://www.elastic.co/guide/en/enterprise-search/current/crawler-managing.html`,
      crawlerOverview: `https://www.elastic.co/guide/en/enterprise-search/current/crawler.html`,
      deployTrainedModels: `${ELASTIC_DOCS}explore-analyze/machine-learning/nlp/ml-nlp-deploy-models`,
      documentLevelSecurity: `${ELASTIC_DOCS}deploy-manage/users-roles/cluster-or-deployment-auth/controlling-access-at-document-field-level`,
      e5Model: `${ELASTIC_DOCS}explore-analyze/machine-learning/nlp/ml-nlp-e5`,
      elser: `${ELASTIC_DOCS}solutions/search/semantic-search/semantic-search-semantic-text`,
      engines: `https://www.elastic.co/guide/en/enterprise-search/current/engines.html`,
      indexApi: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-create`,
      inferenceApiCreate: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-inference-put`,
      inferenceApisConfigureChunking: `${ELASTIC_DOCS}api/doc/elasticsearch/group/endpoint-inference#infer-chunking-config`,
      ingestionApis: `${ELASTIC_DOCS}solutions/search`,
      ingestPipelines: `${ELASTIC_DOCS}solutions/search/ingest-for-search`,
      knnSearch: `${ELASTIC_DOCS}solutions/search/vector/knn`,
      knnSearchCombine: `${ELASTIC_DOCS}solutions/search/vector/knn#_combine_approximate_knn_with_other_features`,
      languageAnalyzers: `${ELASTIC_DOCS}reference/text-analysis/analysis-lang-analyzer`,
      languageClients: `https://www.elastic.co/guide/en/enterprise-search/current/programming-language-clients.html`,
      licenseManagement: `https://www.elastic.co/guide/en/enterprise-search/current/license-management.html`,
      machineLearningStart: `${ELASTIC_DOCS}explore-analyze/machine-learning/nlp/nlp-end-to-end-tutorial`,
      mailService: `https://www.elastic.co/guide/en/enterprise-search/current/mailer-configuration.html`,
      mlDocumentEnrichment: `${ELASTIC_DOCS}explore-analyze/machine-learning/machine-learning-in-kibana/inference-processing`,
      searchApplicationsTemplates: `${ELASTIC_DOCS}solutions/search/search-applications/search-application-api`,
      searchApplicationsSearchApi: `${ELASTIC_DOCS}solutions/search/search-applications/search-application-security`,
      searchApplications: `${ELASTIC_DOCS}solutions/search/search-applications`,
      searchApplicationsSearch: `${ELASTIC_DOCS}solutions/search/search-applications/search-application-client`,
      searchLabs: `${SEARCH_LABS_URL}`,
      searchLabsRepo: `${SEARCH_LABS_REPO}`,
      semanticSearch: `${ELASTIC_DOCS}solutions/search/semantic-search`,
      searchTemplates: `${ELASTIC_DOCS}solutions/search/search-templates`,
      semanticTextField: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/semantic-text`,
      start: `https://www.elastic.co/guide/en/enterprise-search/current/start.html`,
      supportedNlpModels: `${ELASTIC_DOCS}explore-analyze/machine-learning/nlp/ml-nlp-model-ref`,
      syncRules: `${ELASTIC_DOCS}reference/search-connectors/es-sync-rules`,
      syncRulesAdvanced: `${ELASTIC_DOCS}reference/search-connectors/es-sync-rules#es-sync-rules-advanced`,
      trainedModels: `${ELASTIC_DOCS}explore-analyze/machine-learning/data-frame-analytics/ml-trained-models`,
      textEmbedding: `${ELASTIC_DOCS}explore-analyze/machine-learning/nlp/ml-nlp-model-ref#ml-nlp-model-ref-text-embedding`,
      troubleshootSetup: `https://www.elastic.co/guide/en/enterprise-search/current/troubleshoot-setup.html`,
      usersAccess: `https://www.elastic.co/guide/en/enterprise-search/current/users-access.html`,
    },
    metricbeat: {
      base: `https://www.elastic.co/guide/en/beats/metricbeat/current`,
      configure: `${ELASTIC_DOCS}reference/beats/metricbeat/configuring-howto-metricbeat`,
      httpEndpoint: `${ELASTIC_DOCS}reference/beats/metricbeat/http-endpoint`,
      install: `${ELASTIC_DOCS}reference/beats/metricbeat/metricbeat-installation-configuration`,
      start: `${ELASTIC_DOCS}reference/beats/metricbeat/metricbeat-starting`,
    },
    heartbeat: {
      base: `https://www.elastic.co/guide/en/beats/heartbeat/current`,
    },
    libbeat: {
      getStarted: `${ELASTIC_DOCS}reference/beats`,
    },
    logstash: {
      base: `https://www.elastic.co/guide/en/logstash/current`,
      inputElasticAgent: `${ELASTIC_DOCS}reference/logstash/plugins-inputs-elastic_agent`,
    },
    winlogbeat: {
      base: `https://www.elastic.co/guide/en/beats/winlogbeat/current`,
    },
    aggs: {
      composite: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-bucket-composite-aggregation`,
      composite_missing_bucket: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-bucket-composite-aggregation#_missing_bucket`,
      date_histogram: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-bucket-datehistogram-aggregation`,
      date_range: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-bucket-daterange-aggregation`,
      date_format_pattern: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-bucket-daterange-aggregation#date-format-pattern`,
      filter: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-bucket-filter-aggregation`,
      filters: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-bucket-filters-aggregation`,
      geohash_grid: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-bucket-geohashgrid-aggregation`,
      histogram: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-bucket-histogram-aggregation`,
      ip_range: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-bucket-iprange-aggregation`,
      range: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-bucket-range-aggregation`,
      significant_terms: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-bucket-significantterms-aggregation`,
      terms: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-bucket-terms-aggregation`,
      terms_doc_count_error: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-bucket-terms-aggregation#_per_bucket_document_count_error`,
      rare_terms: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-bucket-rare-terms-aggregation`,
      avg: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-metrics-avg-aggregation`,
      avg_bucket: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-pipeline-avg-bucket-aggregation`,
      max_bucket: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-pipeline-max-bucket-aggregation`,
      min_bucket: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-pipeline-min-bucket-aggregation`,
      sum_bucket: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-pipeline-sum-bucket-aggregation`,
      cardinality: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-metrics-cardinality-aggregation`,
      count: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-metrics-valuecount-aggregation`,
      cumulative_sum: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-metrics-sum-aggregation`,
      derivative: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-pipeline-derivative-aggregation`,
      geo_bounds: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-metrics-geobounds-aggregation`,
      geo_centroid: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-metrics-geocentroid-aggregation`,
      max: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-metrics-max-aggregation`,
      median: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-metrics-percentile-aggregation`,
      min: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-metrics-min-aggregation`,
      moving_avg: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-pipeline-movfn-aggregation`,
      percentile_ranks: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-metrics-percentile-rank-aggregation`,
      serial_diff: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-pipeline-serialdiff-aggregation`,
      std_dev: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-metrics-extendedstats-aggregation`,
      sum: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-metrics-sum-aggregation`,
      top_hits: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-metrics-top-hits-aggregation`,
      top_metrics: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-metrics-top-metrics`,
      change_point: `${ELASTIC_DOCS}reference/aggregations/search-aggregations-change-point-aggregation`,
    },
    runtimeFields: {
      overview: `${ELASTIC_DOCS}manage-data/data-store/mapping/runtime-fields`,
      mapping: `${ELASTIC_DOCS}manage-data/data-store/mapping/map-runtime-field`,
    },
    scriptedFields: {
      scriptFields: `https://www.elastic.co/guide/en/elasticsearch/reference/8.18/search-request-body.html`,
      scriptAggs: `${ELASTIC_DOCS}explore-analyze/query-filter/aggregations`,
      painless: `${ELASTIC_DOCS}explore-analyze/scripting/modules-scripting-painless`,
      painlessApi: `https://www.elastic.co/guide/en/elasticsearch/painless/8.18/painless-api-reference.html`,
      painlessLangSpec: `${ELASTIC_DOCS}reference/scripting-languages/painless/painless-language-specification`,
      painlessSyntax: `${ELASTIC_DOCS}reference/scripting-languages/painless/painless-language-specification`,
      painlessWalkthrough: `${ELASTIC_DOCS}reference/scripting-languages/painless/brief-painless-walkthrough`,
      painlessLanguage: `${ELASTIC_DOCS}reference/scripting-languages/painless/painless-language-specification`,
      luceneExpressions: `${ELASTIC_DOCS}explore-analyze/scripting/modules-scripting-expression`,
    },
    indexPatterns: {
      introduction: isServerless
        ? `${ELASTIC_DOCS}explore-analyze/find-and-organize/data-views`
        : `${ELASTIC_DOCS}explore-analyze/find-and-organize/data-views`,
      fieldFormattersNumber: `${ELASTIC_DOCS}explore-analyze/numeral-formatting`,
      fieldFormattersString: `${ELASTIC_DOCS}explore-analyze/find-and-organize/data-views#string-field-formatters`,
      runtimeFields: `${ELASTIC_DOCS}explore-analyze/find-and-organize/data-views#runtime-fields`,
      migrateOffScriptedFields: `${ELASTIC_DOCS}explore-analyze/find-and-organize/data-views#migrate-off-scripted-fields`,
    },
    addData: `${ELASTIC_DOCS}manage-data/ingest`,
    kibana: {
      askElastic: `https://www.elastic.co/products/kibana/ask-elastic?blade=kibanaaskelastic`,
      createGithubIssue: `${ELASTIC_GITHUB}kibana/issues/new/choose`,
      feedback: `https://www.elastic.co/products/kibana/feedback?blade=kibanafeedback`,
      guide: `${ELASTIC_DOCS}get-started/the-stack`,
      autocompleteSuggestions: `${ELASTIC_DOCS}explore-analyze/query-filter/filtering#autocomplete-suggestions`,
      secureSavedObject: `${ELASTIC_DOCS}deploy-manage/security/secure-saved-objects`,
      xpackSecurity: `${ELASTIC_DOCS}deploy-manage/security`,
      restApis: `${ELASTIC_DOCS}api/`,
      dashboardImportExport: `${ELASTIC_DOCS}api/`,
      upgradeNotes: `${ELASTIC_DOCS}release-notes/breaking-changes`,
    },
    upgradeAssistant: {
      overview: `${ELASTIC_DOCS}deploy-manage/upgrade/prepare-to-upgrade/upgrade-assistant`,
      batchReindex: `${ELASTIC_DOCS}api/`,
      remoteReindex: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-reindex#reindex-from-remote`,
      unfreezeApi: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-indices-unfreeze`,
      reindexWithPipeline: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-reindex#reindex-with-an-ingest-pipeline`,
    },
    rollupJobs: `${ELASTIC_DOCS}manage-data/lifecycle/rollup/getting-started-kibana`,
    elasticsearch: {
      docsBase: `https://www.elastic.co/guide/en/elasticsearch/reference/current/`,
      asyncSearch: `${ELASTIC_DOCS}solutions/search/async-search-api`,
      dataStreams: `${ELASTIC_DOCS}manage-data/data-store/data-streams`,
      deprecationLogging: `${ELASTIC_DOCS}deploy-manage/monitor/logging-configuration/update-elasticsearch-logging-levels#deprecation-logging`,
      createEnrichPolicy: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-enrich-put-policy`,
      matchAllQuery: `${ELASTIC_DOCS}reference/query-languages/query-dsl/query-dsl-match-all-query`,
      enrichPolicies: `${ELASTIC_DOCS}manage-data/ingest/transform-enrich/data-enrichment#enrich-policy`,
      createIndex: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-indices-create`,
      frozenIndices: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-indices-unfreeze`,
      gettingStarted: `${ELASTIC_DOCS}solutions/search/get-started`,
      hiddenIndices: `${ELASTIC_DOCS}reference/elasticsearch/rest-apis/api-conventions#hidden`,
      ilm: `${ELASTIC_DOCS}manage-data/lifecycle/index-lifecycle-management`,
      ilmForceMerge: `${ELASTIC_DOCS}reference/elasticsearch/index-lifecycle-actions/ilm-forcemerge`,
      ilmFreeze: `https://www.elastic.co/blog/significantly-decrease-your-elasticsearch-heap-memory-usage`,
      ilmDelete: `${ELASTIC_DOCS}reference/elasticsearch/index-lifecycle-actions/ilm-delete`,
      ilmPhaseTransitions: `${ELASTIC_DOCS}manage-data/lifecycle/index-lifecycle-management/index-lifecycle#ilm-phase-transitions`,
      ilmReadOnly: `${ELASTIC_DOCS}reference/elasticsearch/index-lifecycle-actions/ilm-readonly`,
      ilmRollover: `${ELASTIC_DOCS}reference/elasticsearch/index-lifecycle-actions/ilm-rollover`,
      ilmSearchableSnapshot: `${ELASTIC_DOCS}reference/elasticsearch/index-lifecycle-actions/ilm-searchable-snapshot`,
      ilmSetPriority: `${ELASTIC_DOCS}reference/elasticsearch/index-lifecycle-actions/ilm-set-priority`,
      ilmShrink: `${ELASTIC_DOCS}reference/elasticsearch/index-lifecycle-actions/ilm-shrink`,
      ilmWaitForSnapshot: `${ELASTIC_DOCS}reference/elasticsearch/index-lifecycle-actions/ilm-wait-for-snapshot`,
      indexModules: `${ELASTIC_DOCS}reference/elasticsearch/index-settings/index-modules`,
      indexSettings: `${ELASTIC_DOCS}reference/elasticsearch/index-settings/index-modules#index-modules-settings`,
      dynamicIndexSettings: `${ELASTIC_DOCS}reference/elasticsearch/index-settings/index-modules#dynamic-index-settings`,
      indexTemplates: `${ELASTIC_DOCS}manage-data/data-store/templates`,
      mapping: `${ELASTIC_DOCS}manage-data/data-store/mapping`,
      mappingAnalyzer: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/analyzer`,
      mappingCoerce: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/coerce`,
      mappingCopyTo: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/copy-to`,
      mappingDocValues: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/doc-values`,
      mappingDynamic: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/dynamic`,
      mappingDynamicFields: `${ELASTIC_DOCS}manage-data/data-store/mapping/dynamic-field-mapping`,
      mappingDynamicTemplates: `${ELASTIC_DOCS}manage-data/data-store/mapping/dynamic-templates`,
      mappingEagerGlobalOrdinals: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/eager-global-ordinals`,
      mappingEnabled: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/enabled`,
      mappingFieldData: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/text#fielddata-mapping-param`,
      mappingFieldDataEnable: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/text#before-enabling-fielddata`,
      mappingFieldDataFilter: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/text#field-data-filtering`,
      mappingFieldDataTypes: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/field-data-types`,
      mappingFormat: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/mapping-date-format`,
      mappingIgnoreAbove: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/ignore-above`,
      mappingIgnoreMalformed: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/ignore-malformed`,
      mappingIndex: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/mapping-index`,
      mappingIndexOptions: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/index-options`,
      mappingIndexPhrases: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/index-phrases`,
      mappingIndexPrefixes: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/index-prefixes`,
      mappingJoinFieldsPerformance: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/parent-join#_parent_join_and_performance`,
      mappingMeta: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/mapping-field-meta`,
      mappingMetaFields: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/mapping-meta-field`,
      mappingMultifields: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/multi-fields`,
      mappingNormalizer: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/normalizer`,
      mappingNorms: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/norms`,
      mappingNullValue: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/null-value`,
      mappingParameters: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/mapping-parameters`,
      mappingPositionIncrementGap: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/position-increment-gap`,
      mappingRankFeatureFields: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/rank-feature`,
      mappingRouting: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/mapping-routing-field`,
      mappingSettingsLimit: `${ELASTIC_DOCS}reference/elasticsearch/index-settings/mapping-limit`,
      mappingSimilarity: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/similarity`,
      mappingSourceFields: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/mapping-source-field`,
      mappingSourceFieldsDisable: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/mapping-source-field#disable-source-field`,
      mappingSyntheticSourceFields: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/mapping-source-field#synthetic-source`,
      mappingStore: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/mapping-store`,
      mappingSubobjects: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/subobjects`,
      mappingTermVector: `${ELASTIC_DOCS}reference/elasticsearch/mapping-reference/term-vector`,
      mappingTypesRemoval: `${ELASTIC_DOCS}manage-data/data-store/mapping/removal-of-mapping-types`,
      migrateIndexAllocationFilters: `${ELASTIC_DOCS}manage-data/lifecycle/index-lifecycle-management/migrate-index-allocation-filters-to-node-roles`,
      migrationApiDeprecation: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-migration-deprecations`,
      nodeRoles: `${ELASTIC_DOCS}reference/elasticsearch/configuration-reference/node-settings#node-roles`,
      releaseHighlights: `https://www.elastic.co/guide/en/elasticsearch/reference/8.18/release-highlights.html`,
      latestReleaseHighlights: `https://www.elastic.co/guide/en/starting-with-the-elasticsearch-platform-and-its-solutions/8.18/new.html`,
      remoteClusters: `${ELASTIC_DOCS}deploy-manage/remote-clusters/remote-clusters-self-managed`,
      remoteClustersProxy: `${ELASTIC_DOCS}deploy-manage/remote-clusters/remote-clusters-self-managed#proxy-mode`,
      remoteClusersProxySettings: `${ELASTIC_DOCS}deploy-manage/remote-clusters/remote-clusters-settings#remote-cluster-proxy-settings`,
      remoteClustersOnPremSetupTrustWithCert: `${ELASTIC_DOCS}deploy-manage/remote-clusters/remote-clusters-cert`,
      remoteClustersOnPremSetupTrustWithApiKey: `${ELASTIC_DOCS}deploy-manage/remote-clusters/remote-clusters-api-key`,
      remoteClustersCloudSetupTrust: `${ELASTIC_DOCS}deploy-manage/remote-clusters/ec-enable-ccs`,
      remoteClustersCreateCloudClusterApiKey: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-security-create-cross-cluster-api-key`,
      remoteClustersOnPremPrerequisitesApiKey: `${ELASTIC_DOCS}deploy-manage/remote-clusters/remote-clusters-api-key#remote-clusters-prerequisites-api-key`,
      remoteClustersOnPremSecurityApiKey: `${ELASTIC_DOCS}deploy-manage/remote-clusters/remote-clusters-api-key#remote-clusters-security-api-key`,
      remoteClustersOnPremPrerequisitesCert: `${ELASTIC_DOCS}deploy-manage/remote-clusters/remote-clusters-cert#remote-clusters-prerequisites-cert`,
      remoteClustersOnPremSecurityCert: `${ELASTIC_DOCS}deploy-manage/remote-clusters/remote-clusters-cert#remote-clusters-security-cert`,
      rollupMigratingToDownsampling: `${ELASTIC_DOCS}manage-data/lifecycle/rollup/migrating-from-rollup-to-downsampling`,
      rrf: `${ELASTIC_DOCS}reference/elasticsearch/rest-apis/reciprocal-rank-fusion`,
      scriptParameters: `${ELASTIC_DOCS}explore-analyze/scripting/modules-scripting-using#prefer-params`,
      secureCluster: `${ELASTIC_DOCS}deploy-manage/security`,
      shardAllocationSettings: `${ELASTIC_DOCS}reference/elasticsearch/configuration-reference/cluster-level-shard-allocation-routing-settings#cluster-shard-allocation-settings`,
      sortSearch: `${ELASTIC_DOCS}reference/elasticsearch/rest-apis/sort-search-results`,
      tutorialUpdateExistingDataStream: `${ELASTIC_DOCS}manage-data/lifecycle/data-stream/tutorial-update-existing-data-stream`,
      transportSettings: `${ELASTIC_DOCS}reference/elasticsearch/configuration-reference/networking-settings#common-network-settings`,
      typesRemoval: `${ELASTIC_DOCS}manage-data/data-store/mapping/removal-of-mapping-types`,
      setupUpgrade: `${ELASTIC_DOCS}deploy-manage/upgrade/deployment-or-cluster`,
      apiCompatibilityHeader: `${ELASTIC_DOCS}reference/elasticsearch/rest-apis/api-conventions#api-compatibility`,
      migrationGuide: `${ELASTIC_DOCS}release-notes/breaking-changes`,
    },
    siem: {
      guide: `${ELASTIC_DOCS}solutions/security`,
      gettingStarted: `${ELASTIC_DOCS}solutions/security`,
      privileges: `${ELASTIC_DOCS}solutions/security/get-started/elastic-security-requirements`,
      ml: `${ELASTIC_DOCS}solutions/security/advanced-entity-analytics/anomaly-detection`,
      ruleChangeLog: `${ELASTIC_DOCS}reference/prebuilt-rules-downloadable-updates`,
      detectionsReq: `${ELASTIC_DOCS}solutions/security/detect-and-alert/detections-requirements`,
      networkMap: `${ELASTIC_DOCS}solutions/security/explore/configure-network-map-data`,
      troubleshootGaps: `${ELASTIC_DOCS}solutions/security/detect-and-alert/monitor-rule-executions#troubleshoot-gaps`,
      ruleApiOverview: `${ELASTIC_DOCS}api/doc/kibana/group/endpoint-security-detections-api`,
      configureAlertSuppression: `${ELASTIC_DOCS}solutions/security/detect-and-alert/suppress-detection-alerts#_configure_alert_suppression`,
    },
    server: {
      protocol: `${ELASTIC_DOCS}reference/kibana/configuration-reference/general-settings#server-protocol`,
      publicBaseUrl: `${ELASTIC_DOCS}reference/kibana/configuration-reference/general-settings#server-publicBaseUrl`,
    },
    logging: {
      enableDeprecationHttpDebugLogs: `${ELASTIC_DOCS}reference/kibana/configuration-reference/logging-settings#enable-http-debug-logs`,
    },
    securitySolution: {
      artifactControl: `${ELASTIC_DOCS}solutions/security/configure-elastic-defend/configure-updates-for-protection-artifacts`,
      avcResults: `https://www.elastic.co/blog/elastic-security-av-comparatives-business-test`,
      bidirectionalIntegrations: `${ELASTIC_DOCS}solutions/security/endpoint-response-actions/third-party-response-actions`,
      trustedApps: `${ELASTIC_DOCS}solutions/security/manage-elastic-defend/trusted-applications`,
      eventFilters: `${ELASTIC_DOCS}solutions/security/manage-elastic-defend/event-filters`,
      blocklist: `${ELASTIC_DOCS}solutions/security/manage-elastic-defend/blocklist`,
      threatIntelInt: `${ELASTIC_DOCS}solutions/security/get-started/enable-threat-intelligence-integrations`,
      endpointArtifacts: `${ELASTIC_DOCS}solutions/security/manage-elastic-defend/optimize-elastic-defend`,
      eventMerging: `${ELASTIC_DOCS}solutions/security/configure-elastic-defend/configure-data-volume-for-elastic-endpoint`,
      policyResponseTroubleshooting: {
        full_disk_access: `${ELASTIC_DOCS}solutions/security/configure-elastic-defend/enable-access-for-macos-monterey#enable-fda-endpoint`,
        macos_system_ext: `${ELASTIC_DOCS}solutions/security/configure-elastic-defend/enable-access-for-macos-monterey#system-extension-endpoint`,
        linux_deadlock: `${ELASTIC_DOCS}troubleshoot/security/elastic-defend#linux-deadlock`,
      },
      packageActionTroubleshooting: {
        es_connection: `${ELASTIC_DOCS}troubleshoot/security/elastic-defend`,
      },
      responseActions: `${ELASTIC_DOCS}solutions/security/endpoint-response-actions`,
      configureEndpointIntegrationPolicy: `${ELASTIC_DOCS}solutions/security/configure-elastic-defend/configure-an-integration-policy-for-elastic-defend`,
      exceptions: {
        value_lists: `${ELASTIC_DOCS}solutions/security/detect-and-alert/create-manage-value-lists`,
      },
      privileges: `${ELASTIC_DOCS}solutions/security/configure-elastic-defend/elastic-defend-feature-privileges`,
      manageDetectionRules: `${ELASTIC_DOCS}solutions/security/detect-and-alert/manage-detection-rules`,
      createDetectionRules: `${ELASTIC_DOCS}solutions/security/detect-and-alert/create-detection-rule`,
      updatePrebuiltDetectionRules: isServerless
        ? `${ELASTIC_DOCS}solutions/security/detect-and-alert/install-manage-elastic-prebuilt-rules#update-prebuilt-rules`
        : `${ELASTIC_DOCS}solutions/security/detect-and-alert/install-manage-elastic-prebuilt-rules#update-prebuilt-rules`,
      prebuiltRuleCustomizationPromoBlog: isServerless
        ? '' // URL for Serverless to be added later, once the blog post is published. Issue: https://github.com/elastic/kibana/issues/209000
        : `https://www.elastic.co/blog/security-prebuilt-rules-editing`,
      createEsqlRuleType: `${ELASTIC_DOCS}solutions/security/detect-and-alert/create-detection-rule#create-esql-rule`,
      ruleUiAdvancedParams: `${ELASTIC_DOCS}solutions/security/detect-and-alert/create-detection-rule#rule-ui-advanced-params`,
      entityAnalytics: {
        riskScorePrerequisites: `${ELASTIC_DOCS}solutions/security/advanced-entity-analytics/entity-risk-scoring-requirements`,
        entityRiskScoring: `${ELASTIC_DOCS}solutions/security/advanced-entity-analytics/entity-risk-scoring`,
        assetCriticality: `${ELASTIC_DOCS}solutions/security/advanced-entity-analytics/asset-criticality`,
      },
      detectionEngineOverview: `${ELASTIC_DOCS}solutions/security/detect-and-alert`,
      aiAssistant: `${ELASTIC_DOCS}solutions/security/ai/ai-assistant`,
      signalsMigrationApi: `${ELASTIC_DOCS}api/doc/kibana/group/endpoint-security-detections-api`,
      legacyEndpointManagementApiDeprecations: `${ELASTIC_DOCS}release-notes/breaking-changes#breaking-199598`,
      legacyRuleManagementBulkApiDeprecations: `${ELASTIC_DOCS}release-notes/breaking-changes#breaking-207091`,
      siemMigrations: `https://www.elastic.co/guide/en/security/current/siem-migration.html`,
      llmPerformanceMatrix: `${ELASTIC_DOCS}solutions/security/ai/large-language-model-performance-matrix`,
    },
    query: {
      eql: `${ELASTIC_DOCS}explore-analyze/query-filter/languages/eql`,
      kueryQuerySyntax: `${ELASTIC_DOCS}explore-analyze/query-filter/languages/kql`,
      luceneQuery: `${ELASTIC_DOCS}reference/query-languages/query-dsl/query-dsl-query-string-query`,
      luceneQuerySyntax: `${ELASTIC_DOCS}reference/query-languages/query-dsl/query-dsl-query-string-query#query-string-syntax`,
      percolate: `${ELASTIC_DOCS}reference/query-languages/query-dsl/query-dsl-percolate-query`,
      queryDsl: `${ELASTIC_DOCS}explore-analyze/query-filter/languages/querydsl`,
      queryESQL: `${ELASTIC_DOCS}explore-analyze/query-filter/languages/esql`,
      queryESQLExamples: `${ELASTIC_DOCS}explore-analyze/query-filter/languages/esql`,
    },
    search: {
      sessions: `${ELASTIC_DOCS}explore-analyze/discover/search-sessions`,
      sessionLimits: `${ELASTIC_DOCS}explore-analyze/discover/search-sessions#_limitations`,
    },
    date: {
      dateMath: `${ELASTIC_DOCS}reference/elasticsearch/rest-apis/common-options#date-math`,
      dateMathIndexNames: `${ELASTIC_DOCS}reference/elasticsearch/rest-apis/api-conventions`,
    },
    management: {
      dashboardSettings: `${ELASTIC_DOCS}reference/kibana/advanced-settings#kibana-dashboard-settings`,
      indexManagement: isServerless
        ? `${ELASTIC_DOCS}manage-data/data-store/index-basics`
        : `${ELASTIC_DOCS}manage-data/data-store/templates/index-management-in-ui`,
      kibanaSearchSettings: `${ELASTIC_DOCS}reference/kibana/advanced-settings#kibana-search-settings`,
      discoverSettings: `${ELASTIC_DOCS}reference/kibana/advanced-settings#kibana-discover-settings`,
      rollupSettings: `${ELASTIC_DOCS}reference/kibana/advanced-settings#kibana-rollups-settings`,
      visualizationSettings: `${ELASTIC_DOCS}reference/kibana/advanced-settings#kibana-visualization-settings`,
      timelionSettings: `${ELASTIC_DOCS}reference/kibana/advanced-settings#kibana-timelion-settings`,
      generalSettings: `${ELASTIC_DOCS}reference/kibana/advanced-settings#kibana-general-settings`,
      savedObjectsApiList: `${ELASTIC_DOCS}api/#saved-objects-api`,
      apiKeys: `${ELASTIC_DOCS}deploy-manage/api-keys/elasticsearch-api-keys`,
    },
    ml: {
      guide: `${ELASTIC_DOCS}explore-analyze/machine-learning`,
      aggregations: `${ELASTIC_DOCS}explore-analyze/machine-learning/anomaly-detection/ml-configuring-aggregation`,
      anomalyDetection: `${ELASTIC_DOCS}explore-analyze/machine-learning/anomaly-detection`,
      anomalyDetectionBucketSpan: `${ELASTIC_DOCS}explore-analyze/machine-learning/anomaly-detection/ml-ad-run-jobs#ml-ad-bucket-span`,
      anomalyDetectionConfiguringCategories: `${ELASTIC_DOCS}explore-analyze/machine-learning/anomaly-detection/ml-configuring-categories`,
      anomalyDetectionCardinality: `${ELASTIC_DOCS}explore-analyze/machine-learning/anomaly-detection/ml-ad-run-jobs#ml-ad-cardinality`,
      anomalyDetectionCreateJobs: `${ELASTIC_DOCS}explore-analyze/machine-learning/anomaly-detection/ml-ad-run-jobs#ml-ad-create-job`,
      anomalyDetectionDetectors: `${ELASTIC_DOCS}explore-analyze/machine-learning/anomaly-detection/ml-ad-run-jobs#ml-ad-detectors`,
      anomalyDetectionFunctions: `${ELASTIC_DOCS}explore-analyze/machine-learning/anomaly-detection/ml-functions`,
      anomalyDetectionInfluencers: `${ELASTIC_DOCS}explore-analyze/machine-learning/anomaly-detection/ml-ad-run-jobs#ml-ad-influencers`,
      anomalyDetectionJobs: `${ELASTIC_DOCS}explore-analyze/machine-learning/anomaly-detection/ml-ad-finding-anomalies`,
      anomalyDetectionJobResource: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-ml-put-job#ml-put-job-path-parms`,
      anomalyDetectionJobResourceAnalysisConfig: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-ml-put-job#put-analysisconfig`,
      anomalyDetectionJobTips: `${ELASTIC_DOCS}explore-analyze/machine-learning/anomaly-detection/ml-ad-run-jobs#ml-ad-job-tips`,
      anomalyDetectionScoreExplanation: `${ELASTIC_DOCS}explore-analyze/machine-learning/anomaly-detection/ml-ad-explain`,
      alertingRules: `${ELASTIC_DOCS}explore-analyze/machine-learning/anomaly-detection/ml-configuring-alerts`,
      anomalyDetectionModelMemoryLimits: `${ELASTIC_DOCS}explore-analyze/machine-learning/anomaly-detection/ml-ad-run-jobs#ml-ad-model-memory-limits`,
      calendars: `${ELASTIC_DOCS}explore-analyze/machine-learning/anomaly-detection/ml-ad-run-jobs#ml-ad-calendars`,
      classificationEvaluation: `${ELASTIC_DOCS}explore-analyze/machine-learning/data-frame-analytics/ml-dfa-classification#ml-dfanalytics-classification-evaluation`,
      customRules: `${ELASTIC_DOCS}explore-analyze/machine-learning/anomaly-detection/ml-ad-run-jobs#ml-ad-rules`,
      customUrls: `${ELASTIC_DOCS}explore-analyze/machine-learning/anomaly-detection/ml-configuring-url`,
      dataFrameAnalytics: `${ELASTIC_DOCS}explore-analyze/machine-learning/data-frame-analytics`,
      dFAPrepareData: `${ELASTIC_DOCS}explore-analyze/machine-learning/data-frame-analytics/ml-dfa-overview#prepare-transform-data`,
      dFAStartJob: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-ml-start-data-frame-analytics`,
      dFACreateJob: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-ml-put-data-frame-analytics`,
      featureImportance: `${ELASTIC_DOCS}explore-analyze/machine-learning/data-frame-analytics/ml-feature-importance`,
      outlierDetectionRoc: `${ELASTIC_DOCS}explore-analyze/machine-learning/data-frame-analytics/ml-dfa-finding-outliers#ml-dfanalytics-roc`,
      regressionEvaluation: `${ELASTIC_DOCS}explore-analyze/machine-learning/data-frame-analytics/ml-dfa-regression#ml-dfanalytics-regression-evaluation`,
      classificationAucRoc: `${ELASTIC_DOCS}explore-analyze/machine-learning/data-frame-analytics/ml-dfa-classification#ml-dfanalytics-class-aucroc`,
      setUpgradeMode: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-ml-set-upgrade-mode`,
      trainedModels: `${ELASTIC_DOCS}explore-analyze/machine-learning/data-frame-analytics/ml-trained-models`,
      startTrainedModelsDeployment: `${ELASTIC_DOCS}explore-analyze/machine-learning/nlp/ml-nlp-deploy-model`,
      logsAnomalyDetectionConfigs: `${ELASTIC_DOCS}reference/data-analysis/machine-learning/ootb-ml-jobs-logs-ui`,
      metricsAnomalyDetectionConfigs: `${ELASTIC_DOCS}reference/data-analysis/machine-learning/ootb-ml-jobs-metrics-ui`,
      nlpElser: `${ELASTIC_DOCS}explore-analyze/machine-learning/nlp/ml-nlp-elser`,
      nlpE5: `${ELASTIC_DOCS}explore-analyze/machine-learning/nlp/ml-nlp-e5`,
      nlpImportModel: `${ELASTIC_DOCS}explore-analyze/machine-learning/nlp/ml-nlp-import-model`,
    },
    transforms: {
      guide: isServerless
        ? `${ELASTIC_DOCS}explore-analyze/transforms`
        : `${ELASTIC_DOCS}explore-analyze/transforms`,
      alertingRules: `${ELASTIC_DOCS}explore-analyze/transforms/transform-alerts`,
    },
    visualize: {
      guide: `${ELASTIC_DOCS}explore-analyze/visualize`,
      lens: `https://www.elastic.co/what-is/kibana-lens`,
      lensPanels: `${ELASTIC_DOCS}explore-analyze/visualize/lens`,
      maps: `https://www.elastic.co/maps`,
      vega: `${ELASTIC_DOCS}explore-analyze/visualize/custom-visualizations-with-vega`,
      tsvbIndexPatternMode: `${ELASTIC_DOCS}explore-analyze/visualize/legacy-editors#tsvb-index-patterns-mode`,
    },
    observability: {
      guide: isServerless
        ? `${ELASTIC_DOCS}solutions/observability`
        : `${ELASTIC_DOCS}solutions/observability/get-started`,
      infrastructureThreshold: `${ELASTIC_DOCS}solutions/observability/incident-management/create-an-inventory-rule`,
      logsThreshold: `${ELASTIC_DOCS}solutions/observability/incident-management/create-log-threshold-rule`,
      metricsThreshold: `${ELASTIC_DOCS}solutions/observability/incident-management/create-metric-threshold-rule`,
      customThreshold: isServerless
        ? `${ELASTIC_DOCS}solutions/observability/incident-management/create-custom-threshold-rule`
        : `${ELASTIC_DOCS}solutions/observability/incident-management/create-custom-threshold-rule`,
      monitorStatus: `${ELASTIC_DOCS}solutions/observability/incident-management/create-monitor-status-rule`,
      monitorUptime: isServerless
        ? `${ELASTIC_DOCS}solutions/observability/apps/synthetic-monitoring`
        : `https://www.elastic.co/guide/en/observability/current/monitor-uptime-synthetics.html#monitoring-uptime`,
      tlsCertificate: `${ELASTIC_DOCS}solutions/observability/incident-management/create-tls-certificate-rule`,
      uptimeDurationAnomaly: `${ELASTIC_DOCS}solutions/observability/incident-management/create-an-uptime-duration-anomaly-rule`,
      monitorLogs: isServerless
        ? `${ELASTIC_DOCS}solutions/observability/logs/logs-explorer`
        : `${ELASTIC_DOCS}solutions/observability/logs/explore-logs`,
      analyzeMetrics: isServerless
        ? `${ELASTIC_DOCS}solutions/observability/infra-and-hosts/analyze-infrastructure-host-metrics`
        : `${ELASTIC_DOCS}solutions/observability/infra-and-hosts/analyze-infrastructure-host-metrics`,
      monitorUptimeSynthetics: isServerless
        ? `${ELASTIC_DOCS}solutions/observability/apps/synthetic-monitoring`
        : `${ELASTIC_DOCS}solutions/observability/apps/synthetic-monitoring`,
      userExperience: `${ELASTIC_DOCS}solutions/observability/apps/real-user-monitoring-user-experience`,
      createAlerts: isServerless
        ? `${ELASTIC_DOCS}solutions/observability/incident-management/alerting`
        : `${ELASTIC_DOCS}solutions/observability/incident-management/alerting`,
      syntheticsAlerting: isServerless
        ? `${ELASTIC_DOCS}solutions/observability/apps/configure-synthetics-settings#synthetics-settings-alerting`
        : `${ELASTIC_DOCS}solutions/observability/apps/configure-synthetics-settings#synthetics-settings-alerting`,
      syntheticsCommandReference: isServerless
        ? `${ELASTIC_DOCS}solutions/observability/apps/configure-synthetics-projects#synthetics-configuration-playwright-options`
        : `${ELASTIC_DOCS}solutions/observability/apps/configure-synthetics-projects#synthetics-configuration-playwright-options`,
      syntheticsProjectMonitors: isServerless
        ? `${ELASTIC_DOCS}solutions/observability/apps/create-monitors-with-project-monitors`
        : `${ELASTIC_DOCS}solutions/observability/apps/create-monitors-with-project-monitors#synthetic-monitor-choose-project`,
      syntheticsMigrateFromIntegration: `${ELASTIC_DOCS}solutions/observability/apps/migrate-from-elastic-synthetics-integration`,
      slo: isServerless
        ? `${ELASTIC_DOCS}solutions/observability/incident-management/service-level-objectives-slos`
        : `${ELASTIC_DOCS}solutions/observability/incident-management/service-level-objectives-slos`,
      sloBurnRateRule: isServerless
        ? `${ELASTIC_DOCS}solutions/observability/incident-management/create-an-slo-burn-rate-rule`
        : `${ELASTIC_DOCS}solutions/observability/incident-management/create-an-slo-burn-rate-rule`,
      aiAssistant: `${ELASTIC_DOCS}explore-analyze/ai-assistant`,
    },
    alerting: {
      guide: isServerless
        ? `${ELASTIC_DOCS}explore-analyze/alerts-cases/alerts`
        : `${ELASTIC_DOCS}explore-analyze/alerts-cases/alerts/create-manage-rules`,
      actionTypes: isServerless
        ? `${ELASTIC_DOCS}deploy-manage/manage-connectors`
        : `${ELASTIC_DOCS}reference/kibana/connectors-kibana`,
      apmRulesErrorCount: isServerless
        ? `${ELASTIC_DOCS}solutions/observability/incident-management/create-an-error-count-threshold-rule`
        : `${ELASTIC_DOCS}solutions/observability/apps/create-apm-rules-alerts`,
      apmRulesTransactionDuration: isServerless
        ? `${ELASTIC_DOCS}solutions/observability/incident-management/create-latency-threshold-rule`
        : `${ELASTIC_DOCS}solutions/observability/apps/create-apm-rules-alerts`,
      apmRulesTransactionError: isServerless
        ? `${ELASTIC_DOCS}solutions/observability/incident-management/create-failed-transaction-rate-threshold-rule`
        : `${ELASTIC_DOCS}solutions/observability/apps/create-apm-rules-alerts`,
      apmRulesAnomaly: isServerless
        ? `${ELASTIC_DOCS}solutions/observability/incident-management/create-an-apm-anomaly-rule`
        : `${ELASTIC_DOCS}solutions/observability/apps/create-apm-rules-alerts`,
      emailAction: `${ELASTIC_DOCS}reference/kibana/connectors-kibana/email-action-type`,
      emailActionConfig: `${ELASTIC_DOCS}reference/kibana/connectors-kibana/email-action-type`,
      emailExchangeClientSecretConfig: `${ELASTIC_DOCS}reference/kibana/connectors-kibana/email-action-type#exchange-client-secret`,
      emailExchangeClientIdConfig: `${ELASTIC_DOCS}reference/kibana/connectors-kibana/email-action-type#exchange-client-tenant-id`,
      generalSettings: `${ELASTIC_DOCS}reference/kibana/configuration-reference/alerting-settings#general-alert-action-settings`,
      indexAction: `${ELASTIC_DOCS}reference/kibana/connectors-kibana/index-action-type`,
      esQuery: `${ELASTIC_DOCS}explore-analyze/alerts-cases/alerts/rule-type-es-query`,
      indexThreshold: `${ELASTIC_DOCS}explore-analyze/alerts-cases/alerts/rule-type-index-threshold`,
      maintenanceWindows: isServerless
        ? `${ELASTIC_DOCS}explore-analyze/alerts-cases/alerts/maintenance-windows`
        : `${ELASTIC_DOCS}explore-analyze/alerts-cases/alerts/maintenance-windows`,
      pagerDutyAction: `${ELASTIC_DOCS}reference/kibana/connectors-kibana/pagerduty-action-type`,
      preconfiguredConnectors: `${ELASTIC_DOCS}reference/kibana/connectors-kibana/pre-configured-connectors`,
      preconfiguredAlertHistoryConnector: `${ELASTIC_DOCS}reference/kibana/connectors-kibana/pre-configured-connectors#preconfigured-connector-alert-history`,
      serviceNowAction: `${ELASTIC_DOCS}reference/kibana/connectors-kibana/servicenow-action-type#configuring-servicenow`,
      serviceNowSIRAction: `${ELASTIC_DOCS}reference/kibana/connectors-kibana/servicenow-sir-action-type`,
      setupPrerequisites: `${ELASTIC_DOCS}explore-analyze/alerts-cases/alerts/alerting-setup#alerting-prerequisites`,
      slackAction: `${ELASTIC_DOCS}reference/kibana/connectors-kibana/slack-action-type#configuring-slack-webhook`,
      slackApiAction: `${ELASTIC_DOCS}reference/kibana/connectors-kibana/slack-action-type#configuring-slack-web-api`,
      teamsAction: `${ELASTIC_DOCS}reference/kibana/connectors-kibana/teams-action-type#configuring-teams`,
      connectors: `${ELASTIC_DOCS}reference/kibana/connectors-kibana`,
      legacyRuleApiDeprecations: `${ELASTIC_DOCS}release-notes/breaking-changes#breaking-201550`,
    },
    taskManager: {
      healthMonitoring: `${ELASTIC_DOCS}deploy-manage/monitor/kibana-task-manager-health-monitoring`,
    },
    maps: {
      connectToEms: `${ELASTIC_DOCS}explore-analyze/visualize/maps/maps-connect-to-ems`,
      guide: isServerless ? `${ELASTIC_DOCS}explore-analyze/visualize/maps` : `${ELASTIC_DOCS}explore-analyze/visualize/maps`,
      importGeospatialPrivileges: `${ELASTIC_DOCS}explore-analyze/visualize/maps/import-geospatial-data#import-geospatial-privileges`,
      gdalTutorial: `https://www.elastic.co/blog/how-to-ingest-geospatial-data-into-elasticsearch-with-gdal`,
      termJoinsExample: `${ELASTIC_DOCS}explore-analyze/visualize/maps/terms-join#_example_term_join`,
    },
    monitoring: {
      alertsKibana: `${ELASTIC_DOCS}deploy-manage/monitor/monitoring-data/configure-stack-monitoring-alerts`,
      alertsKibanaCpuThreshold: `${ELASTIC_DOCS}deploy-manage/monitor/monitoring-data/configure-stack-monitoring-alerts#kibana-alerts-cpu-threshold`,
      alertsKibanaDiskThreshold: `${ELASTIC_DOCS}deploy-manage/monitor/monitoring-data/configure-stack-monitoring-alerts#kibana-alerts-disk-usage-threshold`,
      alertsKibanaJvmThreshold: `${ELASTIC_DOCS}deploy-manage/monitor/monitoring-data/configure-stack-monitoring-alerts#kibana-alerts-jvm-memory-threshold`,
      alertsKibanaMissingData: `${ELASTIC_DOCS}deploy-manage/monitor/monitoring-data/configure-stack-monitoring-alerts#kibana-alerts-missing-monitoring-data`,
      alertsKibanaThreadpoolRejections: `${ELASTIC_DOCS}deploy-manage/monitor/monitoring-data/configure-stack-monitoring-alerts#kibana-alerts-thread-pool-rejections`,
      alertsKibanaCCRReadExceptions: `${ELASTIC_DOCS}deploy-manage/monitor/monitoring-data/configure-stack-monitoring-alerts#kibana-alerts-ccr-read-exceptions`,
      alertsKibanaLargeShardSize: `${ELASTIC_DOCS}deploy-manage/monitor/monitoring-data/configure-stack-monitoring-alerts#kibana-alerts-large-shard-size`,
      alertsKibanaClusterAlerts: `${ELASTIC_DOCS}deploy-manage/monitor/monitoring-data/configure-stack-monitoring-alerts#kibana-alerts-cluster-alerts`,
      metricbeatBlog: `https://www.elastic.co/blog/external-collection-for-elastic-stack-monitoring-is-now-available-via-metricbeat`,
      monitorElasticsearch: `${ELASTIC_DOCS}deploy-manage/monitor/stack-monitoring/collecting-monitoring-data-with-metricbeat`,
      monitorKibana: `${ELASTIC_DOCS}deploy-manage/monitor/stack-monitoring/kibana-monitoring-metricbeat`,
      monitorLogstash: `${ELASTIC_DOCS}reference/logstash/monitoring-with-metricbeat`,
      troubleshootKibana: `${ELASTIC_DOCS}troubleshoot/kibana/monitoring`,
    },
    reporting: {
      cloudMinimumRequirements: `${ELASTIC_DOCS}explore-analyze/report-and-share#reporting-on-cloud-resource-requirements`,
      grantUserAccess: `${ELASTIC_DOCS}deploy-manage/deploy/kibana-reporting-configuration#grant-user-access`,
      browserSystemDependencies: `${ELASTIC_DOCS}deploy-manage/deploy/kibana-reporting-configuration#install-reporting-packages`,
      browserSandboxDependencies: `${ELASTIC_DOCS}explore-analyze/report-and-share/reporting-troubleshooting-pdf#reporting-troubleshooting-sandbox-dependency`,
    },
    security: {
      apiKeyServiceSettings: `${ELASTIC_DOCS}reference/elasticsearch/configuration-reference/security-settings#api-key-service-settings`,
      clusterPrivileges: `${ELASTIC_DOCS}elasticsearch/reference/security-privileges#privileges-list-cluster`,
      definingRoles: `${ELASTIC_DOCS}deploy-manage/users-roles/cluster-or-deployment-auth/defining-roles`,
      elasticsearchSettings: `${ELASTIC_DOCS}reference/elasticsearch/configuration-reference/security-settings`,
      elasticsearchEnableSecurity: `${ELASTIC_DOCS}deploy-manage/deploy/self-managed/installing-elasticsearch`,
      elasticsearchEnableApiKeys: `${ELASTIC_DOCS}reference/elasticsearch/configuration-reference/security-settings#api-key-service-settings`,
      indicesPrivileges: `${ELASTIC_DOCS}elasticsearch/reference/security-privileges#privileges-list-indices`,
      kibanaTLS: `${ELASTIC_DOCS}deploy-manage/security/set-up-basic-security#encrypt-internode-communication`,
      kibanaPrivileges: `${ELASTIC_DOCS}deploy-manage/users-roles/cluster-or-deployment-auth/kibana-privileges`,
      mappingRoles: `${ELASTIC_DOCS}deploy-manage/users-roles/cluster-or-deployment-auth/mapping-users-groups-to-roles`,
      mappingRolesFieldRules: `${ELASTIC_DOCS}deploy-manage/users-roles/cluster-or-deployment-auth/role-mapping-resources#mapping-roles-rule-field`,
      runAsPrivilege: `${ELASTIC_DOCS}elasticsearch/reference/security-privileges#_run_as_privilege`,
      deprecatedV1Endpoints: `${ELASTIC_DOCS}release-notes/breaking-changes#breaking-199656`,
      enableElasticSearchSecurityFeatures: `${ELASTIC_DOCS}deploy-manage/security/set-up-minimal-security#_enable_elasticsearch_security_features`,
    },
    spaces: {
      kibanaLegacyUrlAliases: `${ELASTIC_DOCS}extend/kibana/legacy-url-aliases`,
      kibanaDisableLegacyUrlAliasesApi: `${ELASTIC_DOCS}api/doc/kibana/v8/group/endpoint-spaces`,
    },
    watcher: {
      jiraAction: `${ELASTIC_DOCS}explore-analyze/alerts-cases/watcher/actions-jira`,
      pagerDutyAction: `${ELASTIC_DOCS}explore-analyze/alerts-cases/watcher/actions-pagerduty`,
      slackAction: `${ELASTIC_DOCS}explore-analyze/alerts-cases/watcher/actions-slack`,
      ui: `${ELASTIC_DOCS}explore-analyze/alerts-cases/watcher`,
    },
    ccs: {
      guide: `${ELASTIC_DOCS}solutions/search/cross-cluster-search`,
      skippingDisconnectedClusters: `${ELASTIC_DOCS}solutions/search/cross-cluster-search#skip-unavailable-clusters`,
    },
    apis: {
      bulkIndexAlias: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-indices-update-aliases`,
      indexStats: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-indices-stats`,
      byteSizeUnits: `${ELASTIC_DOCS}reference/elasticsearch/rest-apis/api-conventions#byte-units`,
      createAutoFollowPattern: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-ccr-put-auto-follow-pattern`,
      createFollower: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-ccr-follow`,
      createIndex: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-indices-create`,
      createSnapshotLifecyclePolicy: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-slm-put-lifecycle`,
      createRoleMapping: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-security-put-role-mapping`,
      createRoleMappingTemplates: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-security-put-role-mapping#_role_templates`,
      createRollupJobsRequest: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-rollup-put-job#rollup-put-job-api-request-body`,
      createApiKey: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-security-create-api-key`,
      createPipeline: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-ingest-put-pipeline`,
      createTransformRequest: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-transform-put-transform#put-transform-request-body`,
      cronExpressions: `${ELASTIC_DOCS}reference/elasticsearch/rest-apis/api-conventions`,
      executeWatchActionModes: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-watcher-execute-watch#watcher-api-execute-watch-action-mode`,
      indexExists: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-indices-exists`,
      inferTrainedModel: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-ml-infer-trained-model`,
      multiSearch: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-msearch`,
      openIndex: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-indices-open`,
      putComponentTemplate: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-cluster-put-component-template`,
      painlessExecute: `${ELASTIC_DOCS}reference/scripting-languages/painless/painless-api-examples`,
      painlessExecuteAPIContexts: `${ELASTIC_DOCS}reference/scripting-languages/painless/painless-api-examples#_contexts`,
      putComponentTemplateMetadata: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-cluster-put-component-template#component-templates-metadata`,
      putEnrichPolicy: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-enrich-put-policy`,
      putIndexTemplateV1: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-indices-put-template`,
      putSnapshotLifecyclePolicy: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-slm-put-lifecycle`,
      putWatch: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-watcher-put-watch`,
      restApis: `${ELASTIC_DOCS}reference/elasticsearch/rest-apis`,
      searchPreference: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-search#search-preference`,
      securityApis: `${ELASTIC_DOCS}api/doc/elasticsearch/group/endpoint-security`,
      simulatePipeline: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-ingest-simulate`,
      tasks: `${ELASTIC_DOCS}api/doc/elasticsearch/group/endpoint-tasks`,
      timeUnits: `${ELASTIC_DOCS}reference/elasticsearch/rest-apis/api-conventions#time-units`,
      unfreezeIndex: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-indices-unfreeze`,
      updateTransform: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-transform-update-transform`,
    },
    plugins: {
      azureRepo: `${ELASTIC_DOCS}deploy-manage/tools/snapshot-and-restore/azure-repository`,
      gcsRepo: `${ELASTIC_DOCS}deploy-manage/tools/snapshot-and-restore/google-cloud-storage-repository`,
      hdfsRepo: `${ELASTIC_DOCS}reference/elasticsearch/plugins/repository-hdfs`,
      ingestAttachment: `${ELASTIC_DOCS}reference/enrich-processor/attachment`,
      s3Repo: `${ELASTIC_DOCS}deploy-manage/tools/snapshot-and-restore/s3-repository`,
      snapshotRestoreRepos: `${ELASTIC_DOCS}deploy-manage/tools/snapshot-and-restore/self-managed`,
      mapperSize: `${ELASTIC_DOCS}reference/elasticsearch/plugins/mapper-size-usage`,
    },
    snapshotRestore: {
      guide: `${ELASTIC_DOCS}deploy-manage/tools/snapshot-and-restore`,
      changeIndexSettings: `${ELASTIC_DOCS}reference/elasticsearch/index-settings/index-modules`,
      createSnapshot: `${ELASTIC_DOCS}deploy-manage/tools/snapshot-and-restore/create-snapshots`,
      getSnapshot: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-snapshot-get`,
      registerSharedFileSystem: `${ELASTIC_DOCS}deploy-manage/tools/snapshot-and-restore/shared-file-system-repository#filesystem-repository-settings`,
      registerSourceOnly: `${ELASTIC_DOCS}deploy-manage/tools/snapshot-and-restore/source-only-repository#source-only-repository-settings`,
      registerUrl: `${ELASTIC_DOCS}deploy-manage/tools/snapshot-and-restore/read-only-url-repository#read-only-url-repository-settings`,
      restoreSnapshot: `${ELASTIC_DOCS}deploy-manage/tools/snapshot-and-restore/restore-snapshot`,
      restoreSnapshotApi: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-snapshot-restore#restore-snapshot-api-request-body`,
      searchableSnapshotSharedCache: `${ELASTIC_DOCS}deploy-manage/tools/snapshot-and-restore/searchable-snapshots#searchable-snapshots-shared-cache`,
      slmStart: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-slm-start`,
    },
    ingest: {
      append: `${ELASTIC_DOCS}reference/enrich-processor/append-processor`,
      bytes: `${ELASTIC_DOCS}reference/enrich-processor/bytes-processor`,
      circle: `${ELASTIC_DOCS}reference/enrich-processor/ingest-circle-processor`,
      convert: `${ELASTIC_DOCS}reference/enrich-processor/convert-processor`,
      csv: `${ELASTIC_DOCS}reference/enrich-processor/csv-processor`,
      date: `${ELASTIC_DOCS}reference/enrich-processor/date-processor`,
      dateIndexName: `${ELASTIC_DOCS}reference/enrich-processor/date-index-name-processor`,
      dissect: `${ELASTIC_DOCS}reference/enrich-processor/dissect-processor`,
      dissectKeyModifiers: `${ELASTIC_DOCS}reference/enrich-processor/dissect-processor#dissect-key-modifiers`,
      dotExpander: `${ELASTIC_DOCS}reference/enrich-processor/dot-expand-processor`,
      drop: `${ELASTIC_DOCS}reference/enrich-processor/drop-processor`,
      enrich: `${ELASTIC_DOCS}manage-data/ingest/transform-enrich/data-enrichment`,
      fail: `${ELASTIC_DOCS}reference/enrich-processor/fail-processor`,
      foreach: `${ELASTIC_DOCS}reference/enrich-processor/foreach-processor`,
      geoIp: `${ELASTIC_DOCS}reference/enrich-processor/geoip-processor`,
      geoMatch: `${ELASTIC_DOCS}manage-data/ingest/transform-enrich/example-enrich-data-based-on-geolocation`,
      grok: `${ELASTIC_DOCS}reference/enrich-processor/grok-processor`,
      gsub: `${ELASTIC_DOCS}reference/enrich-processor/gsub-processor`,
      htmlString: `${ELASTIC_DOCS}reference/enrich-processor/htmlstrip-processor`,
      inference: `${ELASTIC_DOCS}reference/enrich-processor/inference-processor`,
      inferenceClassification: `${ELASTIC_DOCS}reference/enrich-processor/inference-processor#inference-processor-classification-opt`,
      inferenceRegression: `${ELASTIC_DOCS}reference/enrich-processor/inference-processor#inference-processor-regression-opt`,
      join: `${ELASTIC_DOCS}reference/enrich-processor/join-processor`,
      json: `${ELASTIC_DOCS}reference/enrich-processor/json-processor`,
      kv: `${ELASTIC_DOCS}reference/enrich-processor/kv-processor`,
      lowercase: `${ELASTIC_DOCS}reference/enrich-processor/lowercase-processor`,
      pipeline: `${ELASTIC_DOCS}reference/enrich-processor/pipeline-processor`,
      pipelines: isServerless
        ? `${ELASTIC_DOCS}manage-data/ingest/transform-enrich/ingest-pipelines-serverless`
        : `${ELASTIC_DOCS}manage-data/ingest/transform-enrich/ingest-pipelines`,
      csvPipelines: `${ELASTIC_DOCS}reference/ecs/ecs-converting`,
      pipelineFailure: `${ELASTIC_DOCS}manage-data/ingest/transform-enrich/ingest-pipelines#handling-pipeline-failures`,
      processors: `${ELASTIC_DOCS}reference/enrich-processor`,
      arrayOrJson: `${ELASTIC_DOCS}reference/enrich-processor#ingest-process-category-array-json-handling`,
      dataEnrichment: `${ELASTIC_DOCS}reference/enrich-processor#ingest-process-category-data-enrichment`,
      dataFiltering: `${ELASTIC_DOCS}reference/enrich-processor#ingest-process-category-data-filtering`,
      dataTransformation: `${ELASTIC_DOCS}reference/enrich-processor#ingest-process-category-data-transformation`,
      pipelineHandling: `${ELASTIC_DOCS}reference/enrich-processor#ingest-process-category-pipeline-handling`,
      remove: `${ELASTIC_DOCS}reference/enrich-processor/remove-processor`,
      rename: `${ELASTIC_DOCS}reference/enrich-processor/rename-processor`,
      script: `${ELASTIC_DOCS}reference/enrich-processor/script-processor`,
      set: `${ELASTIC_DOCS}reference/enrich-processor/set-processor`,
      setSecurityUser: `${ELASTIC_DOCS}reference/enrich-processor/ingest-node-set-security-user-processor`,
      sort: `${ELASTIC_DOCS}reference/enrich-processor/sort-processor`,
      split: `${ELASTIC_DOCS}reference/enrich-processor/split-processor`,
      trim: `${ELASTIC_DOCS}reference/enrich-processor/trim-processor`,
      uppercase: `${ELASTIC_DOCS}reference/enrich-processor/uppercase-processor`,
      uriParts: `${ELASTIC_DOCS}reference/enrich-processor/uri-parts-processor`,
      urlDecode: `${ELASTIC_DOCS}reference/enrich-processor/urldecode-processor`,
      userAgent: `${ELASTIC_DOCS}reference/enrich-processor/user-agent-processor`,
    },
    fleet: {
      guide: `${ELASTIC_DOCS}reference/ingestion-tools/fleet`,
      fleetServer: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/fleet-server`,
      fleetServerAddFleetServer: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/deployment-models`,
      settings: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/fleet-settings`,
      kafkaSettings: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/kafka-output-settings`,
      logstashSettings: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/ls-output-settings`,
      esSettings: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/es-output-settings`,
      settingsFleetServerHostSettings: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/fleet-settings#fleet-server-hosts-setting`,
      settingsFleetServerProxySettings: `${ELASTIC_DOCS}reference/kibana/configuration-reference/fleet-settings#fleet-data-visualizer-settings`,
      troubleshooting: `${ELASTIC_DOCS}troubleshoot/ingest/fleet/common-problems`,
      elasticAgent: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/install-elastic-agents`,
      beatsAgentComparison: `${ELASTIC_DOCS}manage-data/ingest/tools`,
      datastreams: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/data-streams`,
      datastreamsILM: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/data-streams#data-streams-ilm`,
      datastreamsNamingScheme: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/data-streams#data-streams-naming-scheme`,
      datastreamsManualRollover: `${ELASTIC_DOCS}manage-data/data-store/data-streams/use-data-stream#manually-roll-over-a-data-stream`,
      datastreamsTSDS: `${ELASTIC_DOCS}manage-data/data-store/index-types/tsdb`,
      datastreamsTSDSMetrics: `${ELASTIC_DOCS}manage-data/data-store/index-types/tsdb#time-series-metric`,
      datastreamsDownsampling: `${ELASTIC_DOCS}manage-data/data-store/data-streams/downsampling-time-series-data-stream`,
      installElasticAgent: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/install-fleet-managed-elastic-agent`,
      installElasticAgentStandalone: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/install-standalone-elastic-agent`,
      grantESAccessToStandaloneAgents: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/grant-access-to-elasticsearch`,
      upgradeElasticAgent: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/upgrade-elastic-agent`,
      learnMoreBlog: `https://www.elastic.co/blog/elastic-agent-and-fleet-make-it-easier-to-integrate-your-systems-with-elastic`,
      apiKeysLearnMore: isServerless
        ? `${ELASTIC_DOCS}deploy-manage/api-keys/serverless-project-api-keys`
        : `${ELASTIC_DOCS}deploy-manage/api-keys/elasticsearch-api-keys`,
      onPremRegistry: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/air-gapped`,
      packageSignatures: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/package-signatures`,
      secureLogstash: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/secure-logstash-connections`,
      agentPolicy: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/agent-policy`,
      api: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/fleet-api-docs`,
      uninstallAgent: `${ELASTIC_DOCS}solutions/security/configure-elastic-defend/uninstall-elastic-agent`,
      installAndUninstallIntegrationAssets: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/install-uninstall-integration-assets`,
      elasticAgentInputConfiguration: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/elastic-agent-input-configuration`,
      policySecrets: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/agent-policy#agent-policy-secret-values`,
      remoteESOoutput: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/remote-elasticsearch-output`,
      performancePresets: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/es-output-settings#es-output-settings-performance-tuning-settings`,
      scalingKubernetesResourcesAndLimits: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/scaling-on-kubernetes#_specifying_resources_and_limits_in_agent_manifests`,
      roleAndPrivileges: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/fleet-roles-privileges`,
      proxiesSettings: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/fleet-agent-proxy-support`,
      unprivilegedMode: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/elastic-agent-unprivileged#unprivileged-change-mode`,
      httpMonitoring: `${ELASTIC_DOCS}reference/ingestion-tools/fleet/agent-policy#change-policy-enable-agent-monitoring`,
    },
    integrationDeveloper: {
      upload: `${ELASTIC_DOCS}extend/integrations/upload-new-integration`,
    },
    ecs: {
      guide: `${ELASTIC_DOCS}reference/ecs`,
      dataStreams: `${ELASTIC_DOCS}reference/ecs/ecs-data_stream`,
    },
    clients: {
      /** Changes to these URLs must also be synched in src/platform/plugins/shared/custom_integrations/server/language_clients/index.ts */
      guide: `${ELASTIC_DOCS}reference/elasticsearch/clients`,
      goConnecting: `${ELASTIC_DOCS}reference/elasticsearch/clients/go/connecting`,
      goGettingStarted: `${ELASTIC_DOCS}reference/elasticsearch/clients/go/getting-started`,
      goIndex: `${ELASTIC_DOCS}reference/elasticsearch/clients/go`,
      goOverview: `${ELASTIC_DOCS}reference/elasticsearch/clients/go`,
      javaBasicAuthentication: `${ELASTIC_DOCS}reference/elasticsearch/clients/java/_basic_authentication`,
      javaIndex: `${ELASTIC_DOCS}reference/elasticsearch/clients/java`,
      javaInstallation: `${ELASTIC_DOCS}reference/elasticsearch/clients/java/installation`,
      javaIntroduction: `${ELASTIC_DOCS}reference/elasticsearch/clients/java`,
      javaRestLow: `${ELASTIC_DOCS}reference/elasticsearch/clients/java/java-low-level-rest-client`,
      jsAdvancedConfig: `${ELASTIC_DOCS}reference/elasticsearch/clients/javascript/advanced-config`,
      jsApiReference: `${ELASTIC_DOCS}reference/elasticsearch/clients/javascript/api-reference`,
      jsBasicConfig: `${ELASTIC_DOCS}reference/elasticsearch/clients/javascript/basic-config`,
      jsClientConnecting: `${ELASTIC_DOCS}reference/elasticsearch/clients/javascript/connecting`,
      jsIntro: `${ELASTIC_DOCS}reference/elasticsearch/clients/javascript`,
      netGuide: `${ELASTIC_DOCS}reference/elasticsearch/clients/dotnet`,
      netIntroduction: `${ELASTIC_DOCS}reference/elasticsearch/clients/dotnet`,
      netNest: `https://www.elastic.co/guide/en/elasticsearch/client/net-api/8.18/nest.html`,
      netSingleNode: `${ELASTIC_DOCS}reference/elasticsearch/clients/dotnet/connecting#single-node`,
      phpConfiguration: `${ELASTIC_DOCS}reference/elasticsearch/clients/php/configuration`,
      phpConnecting: `${ELASTIC_DOCS}reference/elasticsearch/clients/php/connecting`,
      phpInstallation: `${ELASTIC_DOCS}reference/elasticsearch/clients/php/installation`,
      phpGuide: `${ELASTIC_DOCS}reference/elasticsearch/clients/php`,
      phpOverview: `${ELASTIC_DOCS}reference/elasticsearch/clients/php`,
      pythonAuthentication: `${ELASTIC_DOCS}reference/elasticsearch/clients/python/connecting#authentication`,
      pythonConfig: `${ELASTIC_DOCS}reference/elasticsearch/clients/python/configuration`,
      pythonConnecting: `${ELASTIC_DOCS}reference/elasticsearch/clients/python/connecting`,
      pythonGuide: `${ELASTIC_DOCS}reference/elasticsearch/clients/python`,
      pythonOverview: `${ELASTIC_DOCS}reference/elasticsearch/clients/python`,
      rubyAuthentication: `${ELASTIC_DOCS}reference/elasticsearch/clients/ruby/connecting#client-auth`,
      rubyAdvancedConfig: `${ELASTIC_DOCS}reference/elasticsearch/clients/ruby/advanced-config`,
      rubyBasicConfig: `${ELASTIC_DOCS}reference/elasticsearch/clients/ruby/basic-config`,
      rubyExamples: `${ELASTIC_DOCS}reference/elasticsearch/clients/ruby/examples`,
      rubyOverview: `${ELASTIC_DOCS}reference/elasticsearch/clients/ruby`,
      rustGuide: `${ELASTIC_DOCS}reference/elasticsearch/clients/rust`,
      rustOverview: `${ELASTIC_DOCS}reference/elasticsearch/clients/rust`,
      eland: `${ELASTIC_DOCS}reference/elasticsearch/clients/eland`,
    },
    endpoints: {
      troubleshooting: `${ELASTIC_DOCS}troubleshoot/security/elastic-defend#ts-endpoints`,
    },
    legal: {
      privacyStatement: `https://www.elastic.co/legal/product-privacy-statement`,
      generalPrivacyStatement: `https://www.elastic.co/legal/privacy-statement`,
      termsOfService: `https://www.elastic.co/legal/elastic-cloud-account-terms`,
      dataUse: `https://www.elastic.co/legal/privacy-statement#how-we-use-the-information`,
    },
    kibanaUpgradeSavedObjects: {
      resolveMigrationFailures: `${ELASTIC_DOCS}troubleshoot/kibana/migration-failures`,
      repeatedTimeoutRequests: `${ELASTIC_DOCS}troubleshoot/kibana/migration-failures#_repeated_time_out_requests_that_eventually_fail`,
      routingAllocationDisabled: `${ELASTIC_DOCS}troubleshoot/kibana/migration-failures#routing-allocation-disabled`,
      clusterShardLimitExceeded: `${ELASTIC_DOCS}troubleshoot/kibana/migration-failures#cluster-shard-limit-exceeded`,
    },
    searchUI: {
      appSearch: `https://www.elastic.co/guide/en/search-ui/current/tutorials/app-search`,
      elasticsearch: `https://www.elastic.co/guide/en/search-ui/current/tutorials/elasticsearch`,
    },
    serverlessClients: {
      clientLib: `${ELASTIC_DOCS}reference/elasticsearch/clients`,
      goApiReference: `${ELASTIC_DOCS}reference/elasticsearch/clients/go/getting-started-serverless`,
      goGettingStarted: `${ELASTIC_DOCS}reference/elasticsearch/clients/go/getting-started-serverless`,
      httpApis: `${ELASTIC_DOCS}deploy-manage/deploy/elastic-cloud/tools-apis`,
      httpApiReferences: `${ELASTIC_DOCS}deploy-manage/deploy/elastic-cloud/tools-apis`,
      jsApiReference: `${ELASTIC_DOCS}reference/elasticsearch/clients/javascript/getting-started`,
      jsGettingStarted: `${ELASTIC_DOCS}reference/elasticsearch/clients/javascript/getting-started`,
      phpApiReference: `${ELASTIC_DOCS}reference/elasticsearch/clients/php/getting-started`,
      phpGettingStarted: `${ELASTIC_DOCS}reference/elasticsearch/clients/php/getting-started`,
      pythonApiReference: `${ELASTIC_DOCS}reference/elasticsearch/clients/python/getting-started`,
      pythonGettingStarted: `${ELASTIC_DOCS}reference/elasticsearch/clients/python/getting-started`,
      pythonReferences: `${ELASTIC_DOCS}reference/elasticsearch/clients/python/getting-started`,
      rubyApiReference: `${ELASTIC_DOCS}reference/elasticsearch/clients/ruby/getting-started`,
      rubyGettingStarted: `${ELASTIC_DOCS}reference/elasticsearch/clients/ruby/getting-started`,
    },
    serverlessSearch: {
      integrations: `${ELASTIC_DOCS}manage-data/ingest`,
      integrationsLogstash: `${ELASTIC_DOCS}reference/logstash`,
      integrationsBeats: `${ELASTIC_DOCS}reference/beats`,
      integrationsConnectorClient: `${ELASTIC_DOCS}reference/search-connectors`,
      integrationsConnectorClientAvailableConnectors: `${ELASTIC_DOCS}reference/search-connectors#elasticsearch-ingest-data-through-integrations-connector-client-available-connectors`,
      integrationsConnectorClientRunFromSource: `${ELASTIC_DOCS}reference/search-connectors#elasticsearch-ingest-data-through-integrations-connector-client-run-from-source`,
      integrationsConnectorClientRunWithDocker: `${ELASTIC_DOCS}reference/search-connectors#elasticsearch-ingest-data-through-integrations-connector-client-run-with-docker`,
      gettingStartedExplore: `${ELASTIC_DOCS}solutions/search/get-started`,
      gettingStartedIngest: `${ELASTIC_DOCS}solutions/search/get-started`,
      gettingStartedSearch: `${ELASTIC_DOCS}solutions/search/get-started`,
    },
    serverlessSecurity: {
      apiKeyPrivileges: `${ELASTIC_DOCS}deploy-manage/api-keys/serverless-project-api-keys#api-keys-restrict-privileges`,
    },
    synthetics: {
      featureRoles: isServerless
        ? `${ELASTIC_DOCS}solutions/observability/apps/grant-users-access-to-secured-resources`
        : `${ELASTIC_DOCS}solutions/observability/apps/grant-users-access-to-secured-resources`,
    },
    telemetry: {
      settings: `${ELASTIC_DOCS}reference/kibana/configuration-reference/telemetry-settings`,
    },
    playground: {
      chatPlayground: `${ELASTIC_DOCS}solutions/search/rag/playground`,
      retrievalOptimize: `${ELASTIC_DOCS}solutions/search/rag/playground-query#playground-query-relevance`,
      retrieval: `${ELASTIC_DOCS}solutions/search/rag/playground-query`,
      context: `${ELASTIC_DOCS}solutions/search/rag/playground-context`,
      hiddenFields: `${ELASTIC_DOCS}solutions/search/rag/playground-query#playground-hidden-fields`,
    },
    inferenceManagement: {
      inferenceAPIDocumentation: `${ELASTIC_DOCS}api/doc/elasticsearch/operation/operation-inference-put`,
    },
    cases: {
      legacyApiDeprecations: `${ELASTIC_DOCS}release-notes/breaking-changes#breaking-201004`,
    },
    synonyms: {
      synonymsAPIDocumentation: `${ELASTIC_DOCS}api/doc/elasticsearch/group/endpoint-synonyms`,
    },
  });
};
