[[create-connector-api]]
== Create connector API
++++
<titleabbrev>Create connector</titleabbrev>
++++

Creates a connector.

[[create-connector-api-request]]
=== {api-request-title}

`POST <kibana host>:<port>/api/actions/connector`

`POST <kibana host>:<port>/s/<space_id>/api/actions/connector`

=== {api-prereq-title}

You must have `all` privileges for the *Actions and Connectors* feature in the
*Management* section of the
<<kibana-feature-privileges,{kib} feature privileges>>.

[[create-connector-api-path-params]]
=== {api-path-parms-title}

`space_id`::
  (Optional, string) An identifier for the space. If `space_id` is not provided
  in the URL, the default space is used.

[role="child_attributes"]
[[create-connector-api-request-body]]
=== {api-request-body-title}

`config`::
(Required, object) The configuration for the connector. Configuration properties
vary depending on the connector type. For example:
+
.Index connectors
[%collapsible%open]
====
`executionTimeField`::
(Optional, string) Specifies a field that will contain the time the alert
condition was detected. The default value is `null`.

`index`::
(Required, string) The {es} index to be written to.

`refresh`::
(Optional, boolean) The {ref}/docs-refresh.html[refresh] policy for the write
request. The default value is `false`.

====
+
.Jira connectors
[%collapsible%open]
====

`apiUrl`::
(Required, string) The Jira instance URL.

`projectKey`::
(Required, string) The Jira project key.
====
+
For more configuration properties, refer to <<action-types>>.

`connector_type_id`::
(Required, string) The connector type ID for the connector.

`name`::
(Required, string) The display name for the connector.

`secrets`::
(Required, object) The secrets configuration for the connector. Secrets
configuration properties vary depending on the connector type. For information
about the secrets configuration properties, refer to <<action-types>>.
+
--
WARNING: Remember these values. You must provide them each time you call the <<update-connector-api, update>> API.
--
+
.Jira connectors
[%collapsible%open]
====
`apiToken`::
(Required, string) The Jira API authentication token for HTTP basic
authentication.

`email`::
(Required, string) The account email for HTTP Basic authentication.
====

[[create-connector-api-request-codes]]
=== {api-response-codes-title}

`200`::
    Indicates a successful call.

[[create-connector-api-example]]
=== {api-examples-title}

[source,sh]
--------------------------------------------------
POST api/actions/connector
{
  "name": "my-connector",
  "connector_type_id": ".index",
  "config": {
    "index": "test-index"
  }
}
--------------------------------------------------
// KIBANA

The API returns the following:

[source,sh]
--------------------------------------------------
{
  "id": "c55b6eb0-6bad-11eb-9f3b-611eebc6c3ad",
  "connector_type_id": ".index",
  "name": "my-connector",
  "config": {
    "index": "test-index",
    "refresh": false,
    "executionTimeField": null
  },
  "is_preconfigured": false,
  "is_deprecated": false,
  "is_missing_secrets": false
}
--------------------------------------------------
