[[create-connector-api]]
=== Create connector API
++++
<titleabbrev>Create connector</titleabbrev>
++++

Creates a connector.

[[create-connector-api-request]]
==== {api-request-title}

`POST <kibana host>:<port>/api/actions/connector`

`POST <kibana host>:<port>/s/<space_id>/api/actions/connector`

=== {api-prereq-title}

You must have `all` privileges for the *Actions and Connectors* feature in the
*Management* section of the
<<kibana-feature-privileges,{kib} feature privileges>>.

[[create-connector-api-path-params]]
==== {api-path-parms-title}

`space_id`::
  (Optional, string) An identifier for the space. If `space_id` is not provided
  in the URL, the default space is used.

[[create-connector-api-request-body]]
==== {api-request-body-title}

`name`::
  (Required, string) The display name for the connector.

`connector_type_id`::
  (Required, string) The connector type ID for the connector.

`config`::
  (Required, object) The configuration for the connector. Configuration properties vary depending on
  the connector type. For information about the configuration properties, refer to <<action-types,Action and connector types>>.

`secrets`::
  (Required, object) The secrets configuration for the connector. Secrets configuration properties vary
  depending on the connector type. For information about the secrets configuration properties, refer to <<action-types,Action and connector types>>.
+
WARNING: Remember these values. You must provide them each time you call the <<update-connector-api, update>> API.

[[create-connector-api-request-codes]]
==== {api-response-codes-title}

`200`::
    Indicates a successful call.

[[create-connector-api-example]]
==== {api-examples-title}

[source,sh]
--------------------------------------------------
POST api/actions/connector
{
  "name": "my-connector",
  "connector_type_id": ".index",
  "config": {
    "index": "test-index"
  }
}
--------------------------------------------------
// KIBANA

The API returns the following:

[source,sh]
--------------------------------------------------
{
  "id": "0999e890-ccd3-11ec-b9ad-1d74772507a3",
  "name": "my-connector",
  "config": {
    "index": "test-index",
    "refresh": false,
    "executionTimeField": null
  },
  "connector_type_id": ".index",
  "is_preconfigured": false,
  "is_deprecated": false,
  "is_missing_secrets": false
}
--------------------------------------------------
