[[actions-and-connectors-api-create]]
=== Create action API
++++
<titleabbrev>Create action API</titleabbrev>
++++

experimental[] Create {kib} actions.

[[actions-and-connectors-api-create-request]]
==== Request

`POST <kibana host>:<port>/api/actions/action`

[[actions-and-connectors-api-create-request-body]]
==== Request body

`name`::
  (Required, string) The display name for the action.

`actionTypeId`::
  (Required, string) The action type ID for the action.

`config`::
  (Required, object) The action configuration. Configuration properties vary depending on
  the action type. Some action types will have no configuration properties. See the specific action type to determine required fields.

`secrets`::
  (Required, object) The secrets configuration for the action. Secrets properties vary
  depending on the action type. Some action types will have no secrets properties. See the specific ation type to determine required fields.

[[actions-and-connectors-api-create-request-codes]]
==== Response code

`200`::
    Indicates a successful call.

[[actions-and-connectors-api-create-example]]
==== Example

[source,sh]
--------------------------------------------------
$ curl -X POST api/actions/action  -H 'kbn-xsrf: true' -H 'Content-Type: application/json' -d '
{
  "name": "my-action",
  "actionTypeId": ".index",
  "config": {
    "index": "test-index"
  }
}'
--------------------------------------------------
// KIBANA

The API returns the following:

[source,sh]
--------------------------------------------------
{
  "id": "c55b6eb0-6bad-11eb-9f3b-611eebc6c3ad",
  "actionTypeId": ".index",
  "name": "my-action",
  "config": {
    "index": "test-index",
    "refresh": false,
    "executionTimeField": null
  },
  "isPreconfigured": false
}
--------------------------------------------------

==== Action type configuration and secrets

[options="header"]
|===

| Type | Id | Config

| Email
| `.email`
| <<email-connector-config-properties, Email config and secrets properties>>

| Index
| `.index`
| <<index-connector-config-properties, Index config and secrets properties>>

| Jira
| `.jira`
| <<jira-connector-config-properties, Jira config and secrets properties>>

| PagerDuty
| `.pagerduty`
| <<pagerduty-connector-config-properties, PagerDuty config and secrets properties>>

| IBM Resilient
| `.resilient`
| <<resilient-connector-config-properties, IBM Resilient config and secrets properties>>

| Server log
| `.server-log`
| <<server-log-connector-configuration, Server log config and secrets properties>>

| ServiceNow ITSM
| `.servicenow`
| <<servicenow-connector-config-properties, ServiceNow ITSM config and secrets properties>>

| Slack
| `.slack`
| <<slack-connector-config-properties, Slack config and secrets properties>>

| Microsoft Teams
| `.teams`
| <<teams-connector-config-properties, Microsoft Teams config and secrets properties>>

| Webhook
| `.webhook`
| <<webhook-connector-config-properties, Webhook config and secrets properties>>

|===