[[create-connector-api]]
=== Create connector API
++++
<titleabbrev>Create connector</titleabbrev>
++++

Creates a connector.

[[create-connector-api-request]]
==== Request

`POST <kibana host>:<port>/api/actions/connector`

`POST <kibana host>:<port>/s/<space_id>/api/actions/connector`

[[create-connector-api-path-params]]
==== Path parameters

`space_id`::
  (Optional, string) An identifier for the space. If `space_id` is not provided in the URL, the default space is used.

[[create-connector-api-request-body]]
==== Request body

`name`::
  (Required, string) The display name for the connector.

`connector_type_id`::
  (Required, string) The connector type ID for the connector.

`config`::
  (Required, object) The configuration for the connector. Configuration properties vary depending on
  the connector type. For information about the configuration properties, refer to <<action-types,Action and connector types>>.

`secrets`::
  (Required, object) The secrets configuration for the connector. Secrets configuration properties vary
  depending on the connector type. For information about the secrets configuration properties, refer to <<action-types,Action and connector types>>.
+
WARNING: Remember these values. You must provide them each time you call the <<update-connector-api, update>> API.

[[create-connector-api-request-codes]]
==== Response code

`200`::
    Indicates a successful call.

[[create-connector-api-example]]
==== Example

[source,sh]
--------------------------------------------------
$ curl -X POST api/actions/connector  -H 'kbn-xsrf: true' -H 'Content-Type: application/json' -d '
{
  "name": "my-connector",
  "connector_type_id": ".index",
  "config": {
    "index": "test-index"
  }
}'
--------------------------------------------------
// KIBANA

The API returns the following:

[source,sh]
--------------------------------------------------
{
  "id": "c55b6eb0-6bad-11eb-9f3b-611eebc6c3ad",
  "connector_type_id": ".index",
  "name": "my-connector",
  "config": {
    "index": "test-index",
    "refresh": false,
    "executionTimeField": null
  },
  "is_preconfigured": false,
  "is_deprecated": false,
  "is_missing_secrets": false
}
--------------------------------------------------
