[[execute-connector-api]]
== Run connector API
++++
<titleabbrev>Run connector</titleabbrev>
++++

Runs a connector by ID.

[[execute-connector-api-request]]
=== {api-request-title}

`POST <kibana host>:<port>/api/actions/connector/<id>/_execute`

`POST <kibana host>:<port>/s/<space_id>/api/actions/connector/<id>/_execute`

[[execute-connector-api-desc]]
=== {api-description-title}

You can use this API to test an <<alerting-concepts-actions,action>> that 
involves interaction with Kibana services or integrations with third-party
systems.

[[execute-connector-api-prereq]]
=== {api-prereq-title}

You must have `read` privileges for the *Actions and Connectors* feature in the
*Management* section of the
<<kibana-feature-privileges,{kib} feature privileges>>.

If you use an index connector, you must also have `all`, `create`, `index`, or
`write` {ref}/security-privileges.html[indices privileges].

[[execute-connector-api-params]]
=== {api-path-parms-title}

`id`::
(Required, string) The ID of the connector.

`space_id`::
(Optional, string) An identifier for the space. If `space_id` is not provided in
the URL, the default space is used.

[role="child_attributes"]
[[execute-connector-api-request-body]]
=== {api-request-body-title}

`params`::
(Required, object) The parameters of the connector. Parameter properties vary
depending on the connector type. For information about the parameter properties,
refer to <<action-types>>.
+
--
.Jira connectors
[%collapsible%open]
====
`subAction`::
(Required, string) The action to test. For example, `pushToService`.

`subActionParams`::
(Required, object) TBD
+
.Properties of `subActionParams`
[%collapsible%open]
=====
comments::
(Optional, array of objects) TBD
+
.Properties of `comments`
[%collapsible%open]
======
comment::
(string) Additional information for the client, such as how to troubleshoot the
issue.

commentId::
(integer) A unique identifier for the comment.
======

incident::
(object) TBD
+
.Properties of `incident`
[%collapsible%open]
======
`description`::
(Optional, string) The details about the incident.

`labels`::
(Optional, array of strings) The labels for the incident. For example, `["LABEL1"]`.

`issueType`::
(Optional, integer) The type of issue. For example, `10006`.

`parent`::
(Optional, string) The ID or key of the parent issue. Only applies to `Subtask` types of issues.

`priority`::
(Optional, string) The priority of the incident. For example, `Lowest`.

`summary`::
(Required, string) TBD

`title`::
(Optional, string) A title for the issue, used for searching the contents of the knowledge
base.
======
=====
For more information, refer to
{kibana-ref}/jira-action-type.html[{jira} connector and action].
====

.Server log connectors
[%collapsible%open]
====
`level`::
(Optional, string) The log level of the message: `trace`, `debug`, `info`,
`warn`, `error`, or `fatal`. Defaults to `info`.

`message`::
(Required, string) The message to log.
====
--

[[execute-connector-api-codes]]
=== {api-response-codes-title}

`200`::
    Indicates a successful call.

[[execute-connector-api-example]]
=== {api-examples-title}

Run an index connector:

[source,sh]
--------------------------------------------------
POST api/actions/connector/c55b6eb0-6bad-11eb-9f3b-611eebc6c3ad/_execute
{
  "params": {
    "documents": [
      {
        "id": "test_doc_id",
        "name": "test_doc_name",
        "message": "hello, world"
      }
    ]
  }
}
--------------------------------------------------
// KIBANA

The API returns the following:

[source,sh]
--------------------------------------------------
{
  "status": "ok",
  "data": {
    "took": 10,
    "errors": false,
    "items": [
      {
        "index": {
          "_index": "test-index",
          "_id": "iKyijHcBKCsmXNFrQe3T",
          "_version": 1,
          "result": "created",
          "_shards": {
            "total": 2,
            "successful": 1,
            "failed": 0
          },
          "_seq_no": 0,
          "_primary_term": 1,
          "status": 201
        }
      }
    ]
  },
  "connector_id": "c55b6eb0-6bad-11eb-9f3b-611eebc6c3ad"
}
--------------------------------------------------

Run a server log connector:

[source,sh]
--------------------------------------------------
POST api/actions/connector/7fc7b9a0-ecc9-11ec-8736-e7d63118c907/_execute
{
  "params": {
    "level": "warn",
    "message": "Test warning message"
  }
}
--------------------------------------------------
// KIBANA

The API returns the following:

[source,sh]
--------------------------------------------------
{"status":"ok","connector_id":"7fc7b9a0-ecc9-11ec-8736-e7d63118c907"}
--------------------------------------------------