[[get-all-connectors-api]]
== Get all connectors API
++++
<titleabbrev>Get all connectors</titleabbrev>
++++

Retrieves all connectors.

[NOTE]
====
For the most up-to-date API details, refer to the
{kib-repo}/tree/{branch}/x-pack/plugins/actions/docs/openapi[open API specification]. For a preview, check out <<connector-apis>>.
====

[discrete]
[[get-all-connectors-api-request]]
=== {api-request-title}

`GET <kibana host>:<port>/api/actions/connectors`

`GET <kibana host>:<port>/s/<space_id>/api/actions/connectors`

[discrete]
=== {api-prereq-title}

You must have `read` privileges for the *{connectors-feature}* feature in the
*Management* section of the
<<kibana-feature-privileges,{kib} feature privileges>>.

[discrete]
[[get-all-connectors-api-path-params]]
=== {api-path-parms-title}

`space_id`::
  (Optional, string) An identifier for the space. If `space_id` is not provided in the URL, the default space is used.

[discrete]
[[get-all-connectors-api-codes]]
=== {api-response-codes-title}

`200`::
    Indicates a successful call.

[discrete]
[[get-all-connectors-api-example]]
=== {api-examples-title}

[source,sh]
--------------------------------------------------
GET api/actions/connectors
--------------------------------------------------
// KIBANA

The API returns the following:

[source,sh]
--------------------------------------------------
[
  {
    "id": "preconfigured-mail-connector",
    "connector_type_id": ".email",
    "name": "email: preconfigured-mail-connector",
    "is_preconfigured": true,
    "is_deprecated": false,
    "referenced_by_count": 0 <1>
  },
  {
    "id": "c55b6eb0-6bad-11eb-9f3b-611eebc6c3ad",
    "connector_type_id": ".index",
    "name": "my-connector",
    "config": {
      "index": "test-index",
      "refresh": false,
      "executionTimeField": null
    },
    "is_preconfigured": false,
    "is_deprecated": false,
    "is_missing_secrets": false,
    "referenced_by_count": 3
  }
]
--------------------------------------------------

<1> `referenced_by_count` indicates the number of saved objects that reference the connector. This value is not calculated if `is_preconfigured` is `true`.